### PR TITLE
Pull data newline char fix

### LINKED ISSUE #1695: pulldata doesn't work on external CSVs with ^M as line ending characters
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
Pulldata doesn't work on external CSVs with ^M as carriage returns 

#### Steps to reproduce the problem
Download the form and data below. 
[test.xlsx.zip](https://github.com/opendatakit/collect/files/1543582/test.xlsx.zip)
[test.xml.zip](https://github.com/opendatakit/collect/files/1543615/test.xml.zip)
[data-bad.csv.zip](https://github.com/opendatakit/collect/files/1543585/data-bad.csv.zip)
[data-good.csv.zip](https://github.com/opendatakit/collect/files/1543586/data-good.csv.zip)

Push the form and the good data to the device.
```
adb push test.xml /sdcard/odk/forms/
adb push data-good.csv /sdcard/odk/forms/test-media/data.csv
```
Open the form in Collect. Test with household:`K050003` and member:`05`.  It will pull up a study site: `California`. 

Now push the bad data.
```
adb push data-bad.csv /sdcard/odk/forms/test-media/data.csv
```
Re-open form in Collect. Test with household:`K050003` and member:`05`. It will not pull up any site data.

#### Other information
If you open up the CSVs in vim, you'll see that bad data has `^M` (DOS/Windows) as line ending characters.
data-bad

The good data has "proper" newlines.
data-good

I have not looked at the SQLite DB that CSVs go into and to see what is written there for both good and bad data, but that might a good place to start.

I have not explored how this works with external itemsets. The behavior there might be different.

### PR DESCRIPTION
**Pull request by xsteelej**
Closes #1695

#### What has been done to verify that this works as intended?

This has been verified on a Pixel 2 XL device

Installed the form and good data onto the device:

**1)**

`adb push test.xml /sdcard/odk/forms/`
`adb push data-good.csv /sdcard/odk/forms/test-media/data.csv`

Opened the _test_ form in Collect and verified that Household: **K050003** Member: **05** Pulls up the Study site: **California**.

**2)**
Installed the bad data onto the device:

`adb push data-bad.csv /sdcard/odk/forms/test-media/data.csv
`

Opened the _test_ form in Collect and verified that Household: **K050003** Member: **05** Pulls up the Study site: **California**.

#### Why is this the best possible solution? Were any other approaches considered?

No other approaches were considered, this seems to be the simplest solution.

#### Are there any risks to merging this code? If so, what are they?

No apparent risks.

#### Do we need any specific form for testing your changes? If so, please attach one.

Forms attached to the issue: https://github.com/opendatakit/collect/issues/1695

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @xsteelej, and welcome! This looks great to me. I've added the `needs testing` tag following our process outlined in [CONTRIBUTING.md](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#the-review-process) for one additional round of manual verification.

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 1]
```diff
@@ -263,4 +265,23 @@ private void onProgress(String message) {
...
+     * Removes the presence of a Byte Order Mark from the initial UTF-8 String
+     *
+     * Fixes issue: https://github.com/opendatakit/collect/issues/1695
+     *
+     * @param firstLine String to scan for a Byte Order Marker
+     * @return String with any Byte Order Marker removed
+     */
+    private String replaceByteOrderMark(String firstLine) {
+        final String BOM = "\uFEFF";
+        if (firstLine.startsWith(BOM)) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Could you remove this if else statement using just:
`return firstLine.startsWith(BOM) ? firstLine.substring(1) : firstLine`

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 2]
```diff
@@ -263,4 +265,23 @@ private void onProgress(String message) {
             formLoaderTask.publishExternalDataLoadingProgress(message);
         }
     }
+
+    /**
+     * replaceByteOrderMark
+     *
+     * Removes the presence of a Byte Order Mark from the initial UTF-8 String
+     *
+     * Fixes issue: https://github.com/opendatakit/collect/issues/1695
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: I would remove the link fo issue since we generally don't do that in other places. If someone needs to find the issue it's easy using GIT.

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 3]
```diff
@@ -263,4 +265,23 @@ private void onProgress(String message) {
...
+     *
+     * @param firstLine String to scan for a Byte Order Marker
+     * @return String with any Byte Order Marker removed
+     */
+    private String replaceByteOrderMark(String firstLine) {
+        final String BOM = "\uFEFF";
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: I would recommend removing this variable since you added a good comment above and it's used only in one place below (you can just use `\uFEFF`).

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java (hunk 2 above)
Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Agreed

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java (hunk 3 above)
Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: I only put it there for code readability purposes, but yes it can be removed.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: I think it's clear enough thanks to your comment above.

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java (hunk 1 above)
Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Yes it could be rewritten as you suggested with using the ternary operator. However, I have avoided doing so unless it's a very simple assignment because you can't easily step through / set breakpoints on the two cases.

Would you consider this as a must change?

Thanks

**Comment by xsteelej** [comment]
Thanks for the comments @grzesiek2010

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: It's not a must but if you look at our code (newly implemented changes) this approach is popular and other reviewers also prefer the ternary operator like me.

Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Ok, fair enough. I'll make the change to be consistent with other code.

Thanks

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs testing"

@xsteelej I'll add the label again once you update the pr. Thanks in advance :smile:

**Comment by xsteelej** [comment]
Hi @grzesiek2010, I've updated the PR with your review comment changes.

Thanks

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 4]
```diff
@@ -263,4 +265,16 @@ private void onProgress(String message) {
...
+    /**
+     * replaceByteOrderMark
+     *
+     * Removes the presence of a Byte Order Mark from the initial UTF-8 String
+     *
+     * @param firstLine String to scan for a Byte Order Marker
+     * @return String with any Byte Order Marker removed
+     */
+    private String replaceByteOrderMark(String firstLine) {
+        return (firstLine.startsWith("\uFEFF")) ? firstLine.substring(1) : firstLine;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Please remove those parentheses since it's not needed.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 5]
```diff
@@ -263,4 +265,16 @@ private void onProgress(String message) {
...
+
+    /**
+     * replaceByteOrderMark
+     *
+     * Removes the presence of a Byte Order Mark from the initial UTF-8 String
+     *
+     * @param firstLine String to scan for a Byte Order Marker
+     * @return String with any Byte Order Marker removed
+     */
+    private String replaceByteOrderMark(String firstLine) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Could you just change this method name? I think `removeByteOrderMark` would be better since it's removing not replacing.

Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: No problem, agreed

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 6]
```diff
@@ -263,4 +265,16 @@ private void onProgress(String message) {
             formLoaderTask.publishExternalDataLoadingProgress(message);
         }
     }
+
+    /**
+     * removeByteOrderMark
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Please remove this line it's not needed.

Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Line 270?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Yes we don't need the method name at the top of the comment

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java [hunk 7]
```diff
@@ -263,4 +265,14 @@ private void onProgress(String message) {
             formLoaderTask.publishExternalDataLoadingProgress(message);
         }
     }
+
+    /**
+     * Removes the presence of a Byte Order Mark from the initial UTF-8 String
+     *
+     * @param firstLine String to scan for a Byte Order Marker
+     * @return String with any Byte Order Marker removed
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: Thanks for your patience! I have one last question about this comment. You say that you remove any BOM but in fact, you remove only the first one? Is that enough? if so please improve this comment removing `any`

Comment (xsteelej) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java]: The BOM only appears at the start of the file and so would only appear as the first Character in the String. I'll improve the comment.

**Comment by grzesiek2010** [comment]
@xsteelej don't know if you noticed but checkstyle failed on your branch because of:

> android/external/ExternalSQLiteOpenHelper.java:275:47: Parameter name 'BOMCheckString' must match pattern '^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'. [ParameterName]

the first letter in a parameter name can't be capital :wink:

**Comment by xsteelej** [comment]
Hi @grzesiek2010.. I had noticed that, I'll fix that later todsy. That aside, are you happy with the comments now?

**Comment by grzesiek2010** [comment]
> That aside, are you happy with the comments now?

yes now it's perfect just please fix the parameter name (remember to change it in the comment too :wink: ) and it's ready for testing.

**Comment by xsteelej** [comment]
Great, thanks!

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
### Tested with success!
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]
