### PR TITLE
Fixed playing videos in android 12

### LINKED ISSUE #4954: Videos in forms do not play in Android 12
#### Software and hardware versions 
Collect v2021.3.2, Android 12, Pixel 3a

#### Steps to reproduce the problem
Use this [farmer-registration.zip](https://github.com/getodk/collect/files/7812482/farmer-registration.zip) with videos on an Android 12 device. Try to play one of the videos in the form. You will get a "No activity found to handle: View Video".

#### Other information 
This same form works on earlier versions of Android. I have Google Photos (traditionally what Android has used to play videos) installed.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4954 

#### What has been done to verify that this works as intended?
I tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
It uses the new `IntentLauncher` that we implemented recently to keep the code responsible for launching intents in one place to avoid bugs like this one.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should just fix the issue but please take a quick look at other media files too especially on android 12 to make sure there are no other bugs in this area.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used:
[mediaTest.zip](https://github.com/getodk/collect/files/7817997/mediaTest.zip)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java [hunk 1]
```diff
@@ -41,25 +41,32 @@
...
+
 import timber.log.Timber;
 
 /**
  * Represents a label for a prompt/question or a select choice. The label can have media
  * attached to it as well as text (such as audio, video or an image).
  */
 public class AudioVideoImageTextLabel extends RelativeLayout implements View.OnClickListener {
+    @Inject
+    MediaUtils mediaUtils;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java]: I think we could avoid using Dagger here and just pass `MediaUtils` in with `setVideo`. We do state in [our code guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#dependency-injection) that it's "best to avoid Dagger and use normal Java constructors" if possible.

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt [hunk 2]
```diff
@@ -41,6 +41,13 @@ class MediaUtils {
     }
 
     fun openFile(context: Context, file: File, expectedMimeType: String?) {
+        if (!file.exists()) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt:44]: Moving this to a helper seems like a great opportunity to add a test for the behaviour. Good time to create a `MediaUtilsTest`?

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java [hunk 3]
```diff
@@ -106,6 +107,9 @@
     @Inject
     SettingsProvider settingsProvider;
 
+    @Inject
+    MediaUtils mediaUtils;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:112]: Again, I think we could avoid Dagger here and just use the constructor as before.

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java [hunk 4]
```diff
@@ -134,6 +135,9 @@
     @Inject
     StringRequester stringRequester;
 
+    @Inject
+    MediaUtils mediaUtils;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: Again, I think we could avoid Dagger here and just use the constructor.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: Fixed.

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:112]: We agree not to change it because that would require passing that object through the entire hierarchy of widgets (something we need to look into since it's not the first problem like that).

File: collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java]: Here the case is similar like with `QuestionWidget`... this class is used not only in questions (`QuestionWidget`) but also in choices `SelectMultipleListAdapter` and `SelectOneListAdapter` those adapters might be used in select widgets but also in dialogs (widgets with `minimal` appearance) so i would need to inject MediaUtils there (`SelectMultipleListAdapter` and `SelectOneListAdapter`) and pass through that hierarchy. Do you like such a solution more?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java]: Yeah, I think I'd still prefer to keep Dagger out of the view. `MediaUtils` could be passed to the adapter constructors in the widgets right (given they all have access to the `@Inject`ed field)?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java]: Yeah if you have normal widgets that's true but choices might be also used in dialogs you you have `minimal` appearance and then it has to go through more classes but ok it's done.

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt:44]: Yeah I will look into this. If this is the only thing let's mark the pr as `needs testing`.

**Comment by seadowg** [comment]
@grzesiek2010 could you back off the `merge` and `rebase` this onto master instead?

**Comment by grzesiek2010** [comment]
Theoretically yeah but rebasing onto master throws a lot of conflicts and I find it much riskier because during solving those conflicts I can make a mistake and spoil something. Fixing those conflicts here using Github was muuuch easier so I decided to do that.

Generally I agree that we should rebase onto master but in all cases? To me what I said about the risk make me think it's ok to solve conflicts in this way.

**Comment by seadowg** [comment]
> Generally I agree that we should rebase onto master but in all cases? To me what I said about the risk make me think it's ok to solve conflicts in this way.

100% agree. If it was feeling dicey doing a rebase then fair enough - backing out to a merge makes sense.

**Comment by kkrawczyk123** [comment]
**Tested with success!**

Verified cases:
- verified on emulator with Android 12
- regression check on Android 5.1, 8.1 and 10 
- add, create, play video and seflie and video widgets 
- form with input question and play video
- form with select question and play video

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt:44]: Ok tests added.

**Comment by srujner** [comment]
**Tested with success!**

Verified also on emulator with Android 12 and I did a regression check on Android 11

File: collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+import org.odk.collect.android.BuildConfig
+import org.odk.collect.androidshared.system.IntentLauncher
+import org.robolectric.shadows.ShadowToast
+import java.io.File
+
+@RunWith(AndroidJUnit4::class)
+class MediaUtilsTest {
+
+    private val context = ApplicationProvider.getApplicationContext<Context>()
+    private lateinit var intentLauncher: IntentLauncher
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:27]: These can all be initialized up here and avoid the `lateinit`.

Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt]: These can all be initialized up here and avoid the `lateinit`.

File: collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+            Uri.parse("content://org.odk.collect.android.provider/external_files/Android/data/org.odk.collect.android/files/image.png")
+        )
+
+        val contextCaptor = argumentCaptor<Context>()
+        val intentCaptor = argumentCaptor<Intent>()
+        val runnableCaptor = argumentCaptor<() -> Unit>()
+
+        mediaUtils.openFile(context, file, "image/*")
+
+        verify(intentLauncher).launch(
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:59]: An alternative to this that might be more readable (that using agument captors) is to build an `Intent` for the expectation. I think `Intent.equals` works pretty well if I recall correctly.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt]: Done

File: collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:59]: The problem is that we have a function as a parameter in `launch`. I'm not interested in verifying it here but also I can't use `any()` since mixing `any()` and real object when you verify parameters is not possible. If I'm missing something about testing cases like this one please let me know.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:59]: Oh you can do `any()` and object assertions together, but you have to use `eq()` for the object assertions rather than just passing the object as the parameter. The error message you get back from mixing `any()` and plain objects is really not helpful!

As an aside, if you find you need to use an argument captor, it can often be a sign that it'd be easier to make the mock manually by extending the class than using mockito.

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:59]: Ok but intent does not override equals so I can't use eq() for that since it would always check referential equality.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.kt:59]: Ach, my bad I thought `Intent` had a nice `equals()`. Never mind!

**Review by seadowg — APPROVED** [review]
