### PR TITLE
Finish activity when the dialog is canceled

### LINKED ISSUE #5872: Clicking back button or outside the error dialog area in FormUriActivity does not closes the activity
#### Problem description
`FormUriActivity` serves as a guard that protects starting form-filling if all the required conditions are not met. If there is something wrong a dialog with an explanation should be displayed. The dialog has a cancel button that closes the activity. However, if a user taps out of the dialog area (or the device back button) the the dialog is closed but we are not moved to the main menu.

#### Steps to reproduce the problem
1. Create the demo project and download one form
2. Create another project and keep it active (do not switch back to the demo project)
3. Open the [Collect tester](https://github.com/grzesiek2010/collectTester) app and click `Fetch blank forms with content provider`
4. Try to open your form

#### Expected behavior
The activity should be finished. If we tried to open a form from Collect we should be moved to the main menu. If it was via an external app we should be moved back to that app.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5872 

#### Why is this the best possible solution? Were any other approaches considered?
When the dialog is closed the activity should be finished too. No matter if we close the dialog by clicking the cancel button or press the device back button.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I've just fixed the issue making sure the activity is always finished when we close the error dialog. It's a safe change so we can focus on testing the scenario described in the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 1]
```diff
@@ -709,6 +711,16 @@ class FormUriActivityTest {
         assertStartSavedFormIntent(null, instance.dbId, true)
     }
 
+    @Test
+    fun `The activity should be finished after clicking the back button when an error dialog is displayed`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:715]: Why do we need this test when all the other tests now assert on the cancellation behaviour?

**Review by seadowg — CHANGES_REQUESTED** [review]
Why do we need this test when all the other tests now assert on the cancellation behaviour?

**Comment by grzesiek2010** [comment]
> Why do we need this test when all the other tests now assert on the cancellation behaviour?

All the existing tests verified clicking the cancel button but the new one pressing the back button.

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 10,12,13

- Issue #5872 is no longer reproducing;
