### PR TITLE
Fix multiclicking in ManualProjectCreatorDialog 

### LINKED ISSUE #4641: Able to multiclick on Add button on manually enter project details view
#### Software and hardware versions 
Collect v2021.2, Android v all device used...

#### Problem description
I have noticed that I can click on Add button on manually enter project details view multiple times and add the same project multiple times. 
ezgif com-gif-maker (2)
(I am not sure why this video has such bad quality - I used the same app as always)

#### Steps to reproduce the problem
1. Click on Add project
2. Click on Manually enter project details
3. Input URL
4. Tap multiple times on Add button

#### Expected behavior
User should not be able to Add multiple project by multi-clicking on Add button

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4641

#### What has been done to verify that this works as intended?
I tested the fix manually and also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It's the only solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This will be tested later as a whole feature.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt [hunk 1]
```diff
@@ -121,4 +123,13 @@ class ManualProjectCreatorDialogTest {
             Intents.release()
         }
     }
+
+    @Test
+    fun `MultiClickSafeButton should be used to protect from multiclicking`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt]: OK, this is very opinionated and a bit hand wavy: I honestly wouldn't bother with tests like these that just check types. It ends up feeling like the test and the implementation are exact mirrors of each other and don't really enforce behaviour. We have to trust that `MultiClickSafeButton` does the right thing for this test to really mean anything, so it doesn't really give us much confidence or protection, I'd argue.

Interested in your thoughts!

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt]: `MultiClickSafeButton` is widely used so I think confirming it's present like in this test in enough. I thought we had tests for that button (for `MultiClickSafeImageButton` and `MultiClickSafeTextInputEditText` too) but it looks like we don't. So I would rather add tests for those views and in other places only check if they are used. I don't think it should block this issue because we have believed it worked so far (in like 10 classes) we can do that now too and create a separate issue for adding tests.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt]: Oh sorry, I didn't mean we needed more tests, I meant we can just delete these tests. I feel like just making the button a `MultiClickSafeButton` is enough, as we "trust" it (like you say). This is one of the few times I'm saying we can just get rid of a test rather than asking for more haha.

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt]: Ok but then we need something more I think so I created this issue https://github.com/getodk/collect/issues/4645

**Review by seadowg — APPROVED** [review]
