### PR TITLE
Disable 'Save as draft' when 'Moving backwards' is disabled

### LINKED ISSUE #5148: Clicking "Save as draft" when "Moving backwards" is disabled creates inaccessible submissions
#### Software and hardware versions 
Collect v2022.2.2+

#### Steps to reproduce the problem
1. In protected Form Entry Settings, uncheck Moving backwards. 
1. Accept the suggested other setting changes.
1. Fill out a form
1. Click "Save as draft" on the end screen
1. See that the filled form is inaccessible

#### Expected behavior

The Moving backwards setting should also uncheck "Save as draft" (in the "Form End" section) to force finalization.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5148 

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
There is not much to discuss here. I've handled that new setting in the same way like other settings related to moving backwards/editing forms.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test the case described in the issue and generally that the settings that should be disabled when moving backwards is disabled are handled properly.
**It's also important to make sure that settings are migrated properly. For example, if moving backwards was disabled in the previous version after upgrading `Save as draft` should be disabled, and `Finalize` should be enabled (in Settings -> Access control -> Form Entry Settings).**

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/MovingBackwardsTest.kt [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import org.junit.Rule
+import org.junit.Test
+import org.junit.rules.RuleChain
+import org.junit.runner.RunWith
+import org.odk.collect.android.R
+import org.odk.collect.android.support.rules.CollectTestRule
+import org.odk.collect.android.support.rules.TestRuleChain
+
+@RunWith(AndroidJUnit4::class)
+class MovingBackwardsTest {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/MovingBackwardsTest.kt:13]: What's the thinking around adding this instead of adding tests to `FormEntryAccessPreferencesFragmentTest`?

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/MovingBackwardsTest.kt:13]: We can't test disabling moving backwards in isolation (using fragment-scenario like in `FormEntryAccessPreferencesFragmentTest`) because that fragment displays `MovingBackwardsDialog` which calls a listener from `ProjectPreferencesActivity` and then it calls a method from `FormEntryAccessPreferencesFragment`, so there is that activity involved.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/MovingBackwardsTest.kt [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+    fun whenMovingBackwardDisabledWithPreventingUsersFormBypassingIt_finalizedShouldBecomeEnabled() {
+        rule.startAtMainMenu()
+            .openProjectSettingsDialog()
+            .clickSettings()
+            .clickAccessControl()
+            .clickFormEntrySettings()
+            .clickOnString(R.string.finalize)
+            .clickMovingBackwards()
+            .clickOnString(R.string.yes)
+            .assertFinalizeChecked()
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/MovingBackwardsTest.kt]: Is this the wrong assertion? Also, what do you think about making this test part of the first test?

**Review by seadowg — CHANGES_REQUESTED** [review]
Just a (potential) test change here. This is ready for QA!

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:
- Issue #5148 is no longer reproducing;
- Regression check in Form Entry Settings;
- Upgrade app from the older version;
- Moving backwards disabled;
- Regression check on Saving as Draft;
- Switching between projects, adding duplicated projects;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10
