### PR TITLE
Make sure database files always exist when used

### LINKED ISSUE #5042: The app crashes after deleting and adding a project again
#### Problem description
The app crashes after deleting and adding a project again.

```
Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
        at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1729)
        at org.odk.collect.android.database.forms.DatabaseFormsRepository.deleteForms(DatabaseFormsRepository.java:239)
        at org.odk.collect.android.database.forms.DatabaseFormsRepository.delete(DatabaseFormsRepository.java:164)
        at org.odk.collect.android.utilities.FormsDirDiskFormsSynchronizer.synchronizeAndReturnError(FormsDirDiskFormsSynchronizer.java:101)
        at org.odk.collect.android.utilities.FormsDirDiskFormsSynchronizer.synchronize(FormsDirDiskFormsSynchronizer.java:44)
        at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.fetchFormDetails(ServerFormsDetailsFetcher.kt:51)
        at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:63)
        at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:39)
```

#### Steps to reproduce the problem
1. Crete Demo project
2. Download one form
3. Delete the project
4. Create Demo project again
5. Try to download forms.

#### Other information 
The issue is similar to https://github.com/getodk/collect/issues/4870 but it looks like not the same.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5042 

#### What has been done to verify that this works as intended?
I tested the app manually and also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
We store `dbHepers` [in a map that lives as long as the application does](https://github.com/getodk/collect/pull/5043/files#diff-6f4c63e8a1ee58d804a57e12e4101c5c12e6df35c95a318ab164e0f7b7156353R50). Thanks to that we don't need to create new (duplicate) objects every time. The problem was that if database file was deleted it wasn't recreated if we accessed such an object saved in memory (because the object was taken from that map).
Now every time we access `dbHelper` I check if its file exist.  

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change should just fix the issue and have no side effects. Please verify briefly accessing our databases so basicly downloading and opening forms. Please also verify this issue: https://github.com/getodk/collect/issues/4870 because I think it might be also addressed by this pull request.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+import org.junit.Assert.assertTrue
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.odk.collect.android.database.forms.DatabaseFormsRepository
+import org.odk.collect.shared.TempFiles.createTempDir
+import java.io.File
+
+@RunWith(AndroidJUnit4::class)
+// https://github.com/getodk/collect/issues/5042
+class DatabaseFilePresenceTest {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt]: Could this not be a direct test of `DatabaseConnection` so we're not involving a repo?

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt [hunk 2]
```diff
@@ -26,29 +27,28 @@ open class DatabaseConnection(
...
-                migrator
-            )
+    private val dbHelper: SQLiteOpenHelper
+        get() {
+            val databasePath = path + File.separator + name
+            if (openHelpers.containsKey(databasePath) && !File(databasePath).exists()) {
+                openHelpers.remove(databasePath)
+            }
+
+            return openHelpers.getOrPut(databasePath) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt:39]: Maybe we could just use `if-else` (either get one of put and return) here instead of `getOrPut` now? I think that'd be clearer.

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt [hunk 3]
```diff
@@ -26,29 +27,28 @@ open class DatabaseConnection(
...
-                name,
-                null,
-                databaseVersion,
-                migrator
-            )
+    private val dbHelper: SQLiteOpenHelper
+        get() {
+            val databasePath = path + File.separator + name
+            if (openHelpers.containsKey(databasePath) && !File(databasePath).exists()) {
+                openHelpers.remove(databasePath)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt]: Do you think we need to call `close()` on this invalid "open" helper now? It feels like we must be leaking something otherwise.

**Review by seadowg — CHANGES_REQUESTED** [review]
Wow. This was subtle. Great detective work 🕵️‍♂️. There are a couple of things to discuss/tweak that I've left comments about inline.

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt:39]: `getOrPut` is better because it's null safe with if-else the syntax would look worse unless I'm missing something.

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt]: Yeah I think you are right.

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt:39]: Ah you're right we'd always end up having to deal with the nullable result of `get`

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt]: I think you meant: **Could this ~~not~~ be** ?

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt]: Yes. 

Sorry this is ridiculous (probably colloquial?) use of the English language which where I'm really asking: "**is there a reason this is not** a direct test of DatabaseConnection so we're not involving a repo". I guess saying "Could this not be X" is like saying "Why can't this be X". I've no idea where this comes from, and I'll try and avoid using it - as soon as you pointed it out I got very confused as to what I even meant!

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt]: Ah right... I was aware of such constructions in English but I didn't get enough sleep today to catch it probably :) 
Yes it can be DatabaseConnection test.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseFilePresenceTest.kt]: haha yes it definitely does what English does best: be ambiguous. Probably one of those things that makes a lot more sense spoken (with emphasis and tone) than written. I'm also not sure if it's even valid, but native speakers are always the worst at sticking to the rules I guess.

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseConnectionTest.kt [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+import org.junit.Assert.assertFalse
+import org.junit.Assert.assertTrue
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.odk.collect.android.database.forms.FormDatabaseMigrator
+import org.odk.collect.shared.TempFiles.createTempDir
+import java.io.File
+
+@RunWith(AndroidJUnit4::class)
+// https://github.com/getodk/collect/issues/5042
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/database/DatabaseConnectionTest.kt]: We should move this down to the individual test so that it doesn't end up being out of context if we add a second test case.

**Review by seadowg — APPROVED** [review]
Looks good! One tweak to the test but this is ready for QA.

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseConnectionTest.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseConnectionTest.kt]: Done.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 5.1, 8.1 and 10

Verified cases:
- unfortunately, issue #4870 has not been fixed and it's still visible on Android 5.1
- demo project
- another Central project, Google Drive project
- download forms, fill, send, auto-send, match exactly
- download the same form twice
- add project manually, using qr code

**Comment by srujner** [comment]
**Tested with success!**
Verified also on Android 11
