### PR TITLE
Show error when mysterious reload crash would happen

### LINKED ISSUE #5241: Null formController
#### ODK Collect version
v2022.3.0

#### Android version
9, 10, 11 (maybe other too)

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4e09834954ffc3ee419ef8f9d316d2ed?versions=v2022.3.0%20(4477)&time=last-seven-days&types=crash&sessionEventKey=62EAAD7202EE000131F54D37A810577A_1706145731068221603

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.odk.collect.android.javarosawrapper.FormController.getEvent()' on a null object reference
       at org.odk.collect.android.activities.FormEntryActivity.onScreenRefresh(FormEntryActivity.java:1398)
       at org.odk.collect.android.formentry.FormIndexAnimationHandler.handle(FormIndexAnimationHandler.kt:23)
       at org.odk.collect.android.activities.FormEntryActivity.lambda$setupViewModels$7(FormEntryActivity.java:470)
       at org.odk.collect.android.activities.FormEntryActivity.$r8$lambda$T1V91JgXeCj2xNxpJOqRFsZ76xg(FormEntryActivity.java)
       at org.odk.collect.android.activities.FormEntryActivity$$InternalSyntheticLambda$1$c215df7b263d2a4690ddbf172f65e5f56e8023672153174df88d6c10c303a1fb$3.onChanged(FormEntryActivity.java:4)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
       at android.app.Activity.dispatchActivityPostStarted(Activity.java:1396)
       at android.app.Activity.performStart(Activity.java:8268)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3861)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:63)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6006)
       at android.app.ActivityThread.access$3400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
```

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5241

We decided on this approach in a separate conversation due to not having any other theories around a potential fix (or reproduction steps).

#### What has been done to verify that this works as intended?

Verified manually with modified code to simulate crash.

#### Why is this the best possible solution? Were any other approaches considered?

This doesn't solve the problem - a user can still get into the scenario that causes the crash (however that happens), but know we exit form entry gracefully, and encourage them to get in touch. This will hopefully mean that we will get more info from folks if they're experiencing this repeatedly.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should be fairly low risk as I've only added code that will run in a state we can't reproduce. Can skip QA.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -467,7 +467,12 @@ private void setupViewModels() {
                 .get(FormEntryViewModel.class);
 
         formEntryViewModel.getCurrentIndex().observe(this, index -> {
-            formIndexAnimationHandler.handle(index);
+            if (index != null && Collect.getInstance().getFormController() == null) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:470]: The dialog would not show for [this instance of the crash](https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/f2cab4a813a668ccdfa072f6c5d17d02?time=last-seven-days&types=crash&versions=v2022.3.1%20(4482)&sessionEventKey=62F2A20603C700014E1B2D7DCF0831FC_1708386372765513524) for example, right? In that case, the form index change happened before the nulling of form controller so this block would not run?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:470]: No, currently `handle` is being called so it must go through here.

**Review by lognaturel — APPROVED** [review]
