### PR TITLE
Fixes tab label size in Delete Saved Form (Fixes #416)

### LINKED ISSUE #416: The label in tabs in Delete Saved Form are not fully visible in some phones
#### Software and hardware versions 
Collect v1.4.14-24-g5d0db9f-dirty, Android v4.4.2, Xolo Q700s plus(screen size 4.5 inch 480x854 pixels) 

#### Problem description
The label in tabs (Saved forms & Blank forms) in Delete Saved Form are not fully visible. Refer to attached image.

device-2017-02-16-155920

#### Expected behavior
The tab labels should be completely visible.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
device-2017-02-25-163512

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@lognaturel please review

File: collect_app/src/main/java/org/odk/collect/android/activities/FileManagerTabs.java [hunk 1]
```diff
@@ -65,19 +66,21 @@ protected void onCreate(Bundle savedInstanceState) {
         int fontsize = Collect.getQuestionFontsize();
 
         ViewGroup rllf = (ViewGroup) tw.getChildAt(0);
-        mTVFF = getTextViewChild(rllf);
+        TextView mTVFF = getTextViewChild(rllf);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FileManagerTabs.java]: I like your change to local variables very much BUT it means the name should also change because the `m` prefix convention is used to indicate members/fields.

It would be best to issue separate pull requests for fixes and refactoring. That makes the review easier and reduces the risk of making errors. For this one, go ahead and just make the change here. You'll probably want to change the variable name to something a bit more descriptive in addition to removing the `m` prefix.

Then, if you want to take on a bigger refactor of this class, please do! Even just a pass improving names would be great.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Awesome, @shobhitagarwal1612! Let's get those UI bugs fixed. :) Just a quick change to the refactoring part and we'll be ready to merge.

**Review by lognaturel — APPROVED** [review]
