### PR TITLE
Log current screen after saving a form

### LINKED ISSUE #5915: In track changes form saving an empty answer and then entering the value results in missing values in audit logs
#### ODK Collect version
the master version 1f9155c7f1f6c1d91532993fd45cc9b68270124a
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
In a form which track changes saving and empty answer (by click the floppy disc icon) and then entering an answer in the question results in missing values of the answer in audit logs.
The issue was found while testing #5904. The issue doesn’t occur on the store version 2023.3.1
#### Steps to reproduce the problem
1. Open trackingChangesAndLocationTestFrom (or any form that track changes).
[trackingChangesAndLocationTestForm.xml.txt](https://github.com/getodk/collect/files/13938018/trackingChangesAndLocationTestForm.xml.txt)
2. While on the first question (don’t enter anything) click the save button (floppy disc icon).
3. Enter something in the question.
4. Go to end and save the form.
5. Go to CSV with audit logs and check if the entered answer is present.
#### Expected behavior
All values should be saved in audit logs of the track changes form.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5915 

#### Why is this the best possible solution? Were any other approaches considered?
Logging the current screen was removed in this pr: https://github.com/getodk/collect/pull/5839 so to fix the issue I've just brought it back.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should just solve the issue. I don't think it's risky since the fix brings back the code that already existed in v2023.3.1 and older versions but it's not the first issue with audits we have discovered recently so there might be more.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt [hunk 1]
```diff
@@ -164,4 +164,43 @@ class AuditTest {
...
+        assertThat(auditLog.size, equalTo(10))
+
+        assertThat(auditLog[0].get("event"), equalTo("form start"))
+
+        assertThat(auditLog[1].get("event"), equalTo("question"))
+        assertThat(auditLog[1].get("new-value"), equalTo(""))
+
+        assertThat(auditLog[2].get("event"), equalTo("form save"))
+
+        assertThat(auditLog[3].get("event"), equalTo("question"))
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt:192]: Can you add an assertion on the question paths here (and in the other `question` events)? I think that'll help readability.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt:192]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- issue #5915 doesn't occur
- regression checks in audit logs

**Comment by srujner** [comment]
Tested with Success!

Verified on device with Android 13
