### PR TITLE
Fixed missing „form resume” in audit log events when moving backward in not allowed in Collect settings

### LINKED ISSUE #5253: Missing „form resume” in audit log events when moving backward in not allowed in Collect settings
**Software and hardware versions** 

Collect v2022.2.3,  Android probably all

**Problem description**

When moving backwards is not allowed in Collect settings and the user resumes a form with audit from a save point there is no information about „form resume” in audit log events.

**Steps to reproduce the problem**

1. Go to Collect Settings → Access control → Form Entry Settings.
2. Uncheck Moving backwards.
3. Go to a form with audit (e.g. AuditTest).
[AuditTest.xml.txt](https://github.com/getodk/collect/files/9358273/AuditTest.xml.txt)

4. Fill some answers.
5. Kill the app (while the form is opened).
6. Go back to Collect and the form.
7. Save Form and Exit.
8. Go to audit.csv file of the form.

**Expected behavior**

There should be information about „form resume” in audit.csv file .

**Other information** 

I haven’t checked earlier versions of Collect, so the issue may occur there as well.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5253 

#### What has been done to verify that this works as intended?
I've added automated tests and verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
There is nothing to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue. I don't think it can affect anything else.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt [hunk 1]
```diff
@@ -55,4 +59,31 @@ class AuditTest {
...
+            .pressBack(MainMenuPage())
+            .startBlankForm("One Question Audit")
+            .fillOut(
+                FormEntryPage.QuestionAndAnswer("what is your age", "31")
+            )
+            .let {
+                CollectHelpers.killAndReopenApp()
+            }
+
+        MainMenuPage().startBlankForm("One Question Audit")
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt]: I think it'd make sense for the test to save and exit the form as well to check the audit log is in the state we think it should be after the session has ended (as that's what would get uploaded).

File: collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.kt [hunk 2]
```diff
@@ -57,4 +60,20 @@ object CollectHelpers {
                 it.save(ProjectKeys.KEY_SELECTED_GOOGLE_ACCOUNT, accountName)
             }
     }
+
+    fun killAndReopenApp() {
+        val device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
+
+        // kill
+        device.pressRecentApps()
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.kt]: Wow I'd not realised you could do this! I think I tried something similar, but kept ending up with the test exiting as soon the app was killed.

A couple of things here:

1. I think that `killAndReopenApp` could just be a method on `Page`. To be really purist about it, it could take both a package name to restart and a destination page to assert on (here you'd pass `"org.odk.collect.android"` and a `MainMenuPage` instance).
2. It looks like this doesn't actual restart the process (`Application#onCreate` is not called again). We do already have a helper for simulating that (`CollectHelpers.simulateProcessRestart` could be called after the `swipeUp` though.

**Review by seadowg — DISMISSED** [review]

**Review by seadowg — CHANGES_REQUESTED** [review]
Looks good! Would just like to see a couple of tweaks to tests.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt]: Fixed.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.kt]: > I think that killAndReopenApp could just be a method on Page. To be really purist about it, it could take both a package name to restart and a destination page to assert on (here you'd pass "org.odk.collect.android" and a MainMenuPage instance).

Done but do the package name I used `BuildConfig.APPLICATION_ID` so that we don't have to hardcode it.

> It looks like this doesn't actual restart the process (Application#onCreate is not called again). We do already have a helper for simulating that (CollectHelpers.simulateProcessRestart could be called after the swipeUp though.

Maybe the process is not restarted to keep the test running... never mind I've added `CollectHelpers.simulateProcessRestart()`.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
The "form resume" event is present but the last question before killing the app is missing. On the master version the last question (before killing) also appears only once but there isn't the form resume question so then seems ok. Should there be two events for the last question- event before killing the app and event after going back to the app? So I'm not really sure if it's a separate issue or the PR.

Steps to reproduce:
1. Open Audit Test form.
2. Fill questions 1,2,3.
3. While on the question 3 kill the app.
4. Go back to the form.
5. Tap next and fill questions 4,5,6 and send the form.
text3missing

Text 3 question is missing before the "form resume" event. It appears after the event (going back to the app).

**Comment by grzesiek2010** [comment]
It works fine to me if on master that question is also logged only once. I think this will be fixed in https://github.com/getodk/collect/issues/5721

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on the device with Android 10

**Verified cases:**
- issue #5253 is no longer reproducible
- regression checks in audit logs

The mentioned issue will be tested again along with #5721

**Comment by srujner** [comment]
**Tested with Success!**

Verified on the device with Android 13
