### PR TITLE
Only detect exact collinear intersections in traces

### LINKED ISSUE #6979: Invalid geoshape with points which are almost in the same line
#### ODK Collect version
the master version 897c7ace99785d78a0e1e4fa5216aa5dd34d3010
(The feature isn't in the store version yet)
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
I think this might be the case Callum mentioned on the weekly meeting - an invalid geoshape with points which are almost in the same line.
The shape was created with automatic location recording set to 1 second, "none" accuracy.
The geometry is in the form below or in https://docs.google.com/document/d/1fJMvTl7nEvMkqvx2MJiKxq3iSgK6a6faXw6h8Zemx7E/edit?tab=t.0

Image

#### Steps to reproduce the problem
1.  Scan user "invalid polygons".
    https://test.getodk.cloud/projects/629/app-users
2. Open geoshape geatrace defaults example forms.
3. Go to "test same line" question and try to swipe to the next question.
4.  Open the map.

#### Expected behavior
I'm not sure if this is a valid or invalid shape

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6979

#### Why is this the best possible solution? Were any other approaches considered?

I've removed the default epsilon from our orientation which is used as part of intersection detection. Instead, now an epsilon can be passed to both `LineSegment#intersects` and `Trace#intersects`. This allows us to only detect **exact** collinear intersections (one endpoint touching another line) in the app, while also allowing tolerance for testing with linear interpolation (which is hard to get 100% exact).

We may want to use an epsilon in the app as well, but until we get more feedback, avoiding false positives is safer - I think leaving the ability to add one in right now is a good idea.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This should make it very hard to create an intersection where the endpoint of one segment is touching (or close to touching) another line.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@dbemke is this looking better?

**Comment by dbemke** [comment]
> is this looking better?

Issue #6979 and the one described in #6967 don't show that they are invalid polygon. 
I tried to "create" similar one and none of them violated the constraint.
I manually moved the points so that when I zoom in I can see them in one line and they don't violate the constraint - I'm not sure whether this case should be treated as intersection or not. @alyblenkin What do you think?  Is it the result users want (the sides of the polygon are super close and are treated as a valid polygon) or his is the case they want to avoid?
**Steps to reproduce:**
1. Scan user "invalid polygons" https://test.getodk.cloud/projects/629/app-users
2. Go to geoshape and geotrace defaults example to "test same line max" and open the map.

The geometry is also in https://docs.google.com/document/d/1daqyvOECyh6pYMeealpVbPWrmONF4DgUHVvrcbRgWrE/edit?tab=t.0

**Comment by seadowg** [comment]
> Issue https://github.com/getodk/collect/issues/6979 and the one described in https://github.com/getodk/collect/pull/6967 don't show that they are invalid polygon.
I tried to "create" similar one and none of them violated the constraint.
I manually moved the points so that when I zoom in I can see them in one line and they don't violate the constraint - I'm not sure whether this case should be treated as intersection or not.

Good to discuss further, but for this PR let's go with it as-is. I think we're going to need some feedback from users: making endpoint intersections "fuzzy" could be disastrous for some cases.

File: shared/src/test/java/org/odk/collect/shared/geometry/support/GeometryTestUtils.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        })
+    }
+
+    fun Trace.addRandomIntersectingSegment(): Trace {
+        val intersectionSegment = segments().dropLast(1).random()
+        val intersectPosition = Random.nextDouble(0.1, 1.0)
+        val intersectionPoint = intersectionSegment.interpolate(intersectPosition)
+        val lineSegment = LineSegment(points.last(), intersectionPoint)
+        val intersectingSegment =
+            LineSegment(lineSegment.start, lineSegment.interpolate(1.1))
```
Comment (seadowg) [inline shared/src/test/java/org/odk/collect/shared/geometry/support/GeometryTestUtils.kt:58]: Adding a line that intersects through another (rather than just touching) avoids needing to use an epsilon to account for the inaccurate `interpolate` and is far more realistic.

File: shared/src/main/java/org/odk/collect/shared/geometry/Geometry.kt [hunk 2]
```diff
@@ -25,21 +25,21 @@ fun Trace.segments(): List<LineSegment> {
 /**
  * Returns `true` if any segment of the trace intersects with any other and `false` otherwise.
  */
-fun Trace.intersects(): Boolean {
+fun Trace.intersects(epsilon: Double = 0.0): Boolean {
```
Comment (seadowg) [inline shared/src/main/java/org/odk/collect/shared/geometry/Geometry.kt:28]: As mentioned in the PR description, I'm assuming we're going to end up tuning an epsilon for the `intersects` XPath function or allowing it to be tweaked so I've left this in.

File: shared/src/test/java/org/odk/collect/shared/geometry/GeometryTest.kt [hunk 3]
```diff
@@ -214,31 +218,24 @@ class GeometryTest {
...
             )
 
             // Check adding an intersection makes intersects true
-            if (!intersects) {
-                val intersectionSegment = trace.segments().random()
-                val intersectPosition = Random.nextDouble(0.1, 1.0)
-                val intersectionPoint = intersectionSegment.interpolate(intersectPosition)
-                val intersectingTrace =
-                    Trace(trace.points + listOf(trace.points.last(), intersectionPoint))
+            if (!intersects && !trace.isClosed()) {
```
Comment (grzesiek2010) [inline shared/src/test/java/org/odk/collect/shared/geometry/GeometryTest.kt]: Why do we skip this step for closed polygons? We can still add another segment to make sure `#intersects` returns true.

File: shared/src/test/java/org/odk/collect/shared/geometry/support/GeometryTestUtils.kt [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+    }
+
+    fun Trace.scale(factor: Double): Trace {
+        return Trace(points.map {
+            Point(it.x * factor, it.y * factor)
+        })
+    }
+
+    fun Trace.addRandomIntersectingSegment(): Trace {
+        val intersectionSegment = segments().dropLast(1).random()
```
Comment (grzesiek2010) [inline shared/src/test/java/org/odk/collect/shared/geometry/support/GeometryTestUtils.kt:53]: Why do we need to ignore the last segment? As I understand it, it avoids the scenario when the additional segment lies on the last segment but why? This still would be treated as an intersection.

Comment (seadowg) [reply shared/src/test/java/org/odk/collect/shared/geometry/support/GeometryTestUtils.kt:53]: Good question! I'd meant to add a comment when moving this to a method and then forgotten:

```
/**
* Choose random segment, a random (interpolated) point on that segment and then create a new
* trace with an additional point just beyond that to create an intersecting trace.
*
* Never chooses the last segment as a target for intersecting as that can only create a
* collinear intersection which is unlikely to be accurate due to inaccuracies in [interpolate].
*/
```

This is basically the "two consecutive segments intersect" special case, and we test this it specifically (`Trace#intersects returns true when two segments and they intersect`).

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16, 11

**Verified cases:**
- Issue #6979 does not occur
- Intersects in Geoshape and Geotrace questions
- Different recording modes

**Comment by dbemke** [comment]
**Tested with success**

Verified on Android 10

**Review by grzesiek2010 — APPROVED** [review]
