### PR TITLE
Prevent NPE in QuitFormDialogFragment

### LINKED ISSUE #4036: NPE in FormSaveViewModel
From https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8ca03d40871475f87917f721719cd4aa?time=last-seven-days&sessionId=5F429670034E0001384141414334DC52_DNE_0_v2

#### Software and hardware versions 
Collect v1.28.0-beta.1

#### Problem description

Stacktrace:

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.odk.collect.android.formentry.audit.AuditEventLogger org.odk.collect.android.javarosawrapper.FormController.getAuditEventLogger()' on a null object reference
       at org.odk.collect.android.formentry.saving.FormSaveViewModel.getAuditEventLogger(FormSaveViewModel.java:253)
       at org.odk.collect.android.formentry.QuitFormDialogFragment.lambda$onCreateDialog$0(QuitFormDialogFragment.java:93)
       at org.odk.collect.android.formentry.-$$Lambda$QuitFormDialogFragment$kkJKBUgJhZUYv_cQAWuh7PWDoCM.onItemClick(-.java:8)
       at android.widget.AdapterView.performItemClick(AdapterView.java:321)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
       at android.widget.AbsListView$3.run(AbsListView.java:4151)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

#### Steps to reproduce the problem

My guess it that somehow the form is being quit before the `formController` has been set on the `FormSaveViewModel`.

#### Expected behavior

A `null` `formController` shouldn't cause a crash (as much as it wants to).

#### Other information 

I think a good fix for this kind of thing is to move the logging logic to the view model so that it can just no-op on a `null` `formController`. A good idea for this specific one would be to create a `quit` or `ignore` action on the `FormSaveViewModel` that could take care of logging and removing temp instances etc.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4036

This hopefully fixes the crash but it's hard to validate as we don't have reproduction steps.

#### What has been done to verify that this works as intended?

Isolated code with bug and wrote new test to cover it.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just prevent the one case where a `null` could be set. I think it's a simple enough change that we can merge without QA but maybe still good for them to check loading forms and then ignoring changes here so we're confident when we do a patch release.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java [hunk 1]
```diff
@@ -84,16 +81,7 @@ public Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {
                     listener.onSaveChangesClicked();
                 }
             } else {
-                ExternalDataManager manager = Collect.getInstance().getExternalDataManager();
-                if (manager != null) {
-                    manager.close();
-                }
-
-                if (viewModel.getAuditEventLogger() != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java:92]: The weird thing here is that there is `null` protection in here.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 2]
```diff
@@ -519,8 +520,9 @@ private void loadForm() {
             formLoaderTask = (FormLoaderTask) data;
         } else if (data == null) {
             if (!newForm) {
-                if (getFormController() != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:522]: This is the one place where it seemed like we could pass a `null` to `formLoaded` as we are checking the singleton field isn't `null` and then calling the method again. Assigning it here means that we only deal with the one value (`null` or not).

File: collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java [hunk 3]
```diff
@@ -83,7 +84,11 @@ public FormSaveViewModel(SavedStateHandle stateHandle, Clock clock, FormSaver fo
     }
 
     @Override
-    public void formLoaded(FormController formController) {
+    public void formLoaded(@NotNull FormController formController) {
+        if (formController == null) {
+            Timber.e(new IllegalArgumentException("null FormController passed to formLoaded"));
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java:89]: My thinking here is that we can track this in non fatals in Crashlytics and hopefully gain some insight into whats happening (if this continues).

File: collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java [hunk 4]
```diff
@@ -127,8 +128,15 @@ public void saveForm(Uri instanceContentURI, boolean shouldFinalize, String upda
...
     // Cleanup when user exits a form without saving
-    public void removeTempInstance() {
+    public void ignoreChanges() {
+        ExternalDataManager manager = Collect.getInstance().getExternalDataManager();
+        if (manager != null) {
+            manager.close();
+        }
+
         if (formController != null && formController.getInstanceFile() != null) {
+            formController.getAuditEventLogger().logEvent(AuditEvent.AuditEventType.FORM_EXIT, true, System.currentTimeMillis());
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java:138]: Much easier to protect form `null` in the view model

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java [hunk 5]
```diff
@@ -411,6 +411,12 @@ public void replaceRecentFileForQuestion_whenQuestionIndexHasAnswer_onRecreating
         verify(mediaUtils).deleteImageFileFromMediaProvider("blah");
     }
 
+    @Test
+    public void ignoreChanges_whenFormControllerNotSet_doesNothing() {
+        FormSaveViewModel viewModel = new FormSaveViewModel(savedStateHandle, () -> CURRENT_TIME, formSaver, mediaUtils, null);
+        viewModel.ignoreChanges(); // Checks nothing explodes
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:417]: Definitely could be expanded on but this is good enough to give us a harness to prevent a regression on this particular bug.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:417]: Haven't you shaken your fist in my general direction about tests without assertions before?! 😅 

More seriously, I'm not really thinking of anything meaningful to assert and I do think it's ok.

**Review by lognaturel — APPROVED** [review]
It's not urgent so let's have QA look at it.

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java (hunk 5 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:417]: Haha probably. Do as I say not as I do right...

But yeah I think this test would ideally check that calls aren't made but here it felt the real focus was just to make sure nothing exploded. There is a comment 😉

**Comment by lognaturel** [comment]
Since we weren't able to get QA on this today and it is increasing in frequency, we've decided to merge and release. I think this may be a symptom of a deeper issue (why is the `formController` `null` so often?) but I can't think of a way to identify it other than putting this fix out there and seeing if other crashes or user-reported problems show up.

I went through carefully one more time. There is a subtle change in that if `formController.getInstanceFile()` is `null`, a form exit audit event won't be written.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
On Friday, I spent some time trying to reproduce this crash but I failed. I haven't established repro steps. That's why I can only confirm that the actions listed below work correctly.

Verified on Android 7.0, 8.1, 10.0

Verified cases on released v1.28.1:
* change theme in the middle of filling form with audit and load form from savepoint
* change language in the middle of filling form with audit and load form from savepoint
* close app in the middle of filling form with audit and load form from savepoint
* close app on hierarchy view and load form from savepoint
* restart device in the middle of filling form with audit and load form from savepoint
* close app in the middle of repeat group with audit and load form from savepoint
* close app in the middle of filling form with audit  -> clear cashe -> no crash
* close app in the middle of filling form with audit and tracking location in background and load form from savepoint
* close app in the middle of filling form with audit and nested groups in background and load form from savepoint
* ignored changes which were loaded from savepoint
* saved changes which were loaded from savepoint

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 9.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
