### PR TITLE
Fix autosend scheduling

### LINKED ISSUE #6120: Forms are not being auto sent after restoring connection that matches auto send setting
#### ODK Collect version
the store version 2024.1.3

#### Android version
10

#### Device used
Redmi 9T

#### Problem description
Forms are not being auto sent after restoring connection that matches auto send setting

#### Steps to reproduce the problem
1. Turn on cellular
2. Turn off wifi
3. Go to settings > form management
4. Set auto send to Wifi only
5. Finalize any form
6. Enable wifi

#### Expected behavior
After restoring connection that matches auto send setting, forms should be sent

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6120

This also: 
* Fixes problems introduced recently where form level auto send was no longer working
* Makes sure that pending auto send jobs will run after an app upgrade (even if there is a change in the underlying code)
* Will not run "Cellular only" auto send when connected to a metered wifi (like a hotspot), but will retry later (with an exponential back off)

It's probably a good idea to wait on merging this until it's marked "behaviour verified" as we've seen a lot of churn on auto send recently.

#### Why is this the best possible solution? Were any other approaches considered?

I would have loved to have a more elegant solution for "cellular only", but couldn't find one that would work within the WorkManager world. I think the compromise of having other settings work optimally within Android's current background job setup is correct though.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This should mean that auto send now behaves more like how we'd "expect". One caveat to highlight is that metered wifi (like a hotspot) will not work with "wifi only" or "cellular only". The work around for this (other than using "wifi or cellular") is to change the wifi to "unmetered" in Android's settings.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@WKobus could you take another look at this when you get a chance? The biggest change since you last looked is that "cellular only" shouldn't run when connected to a metered wifi (like a hotspot), but should run eventually if you then just connect to cellular (although it might take a few minutes).

File: async/src/main/java/org/odk/collect/async/Scheduler.kt [hunk 1]
```diff
@@ -81,7 +81,8 @@ interface Scheduler {
 
     enum class NetworkType {
         WIFI,
-        CELLULAR
+        CELLULAR,
+        OTHER
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/Scheduler.kt:85]: `OTHER` would just be any other connected network. Android devices can theoretically have network delivered via Ethernet or Bluetooth for example. These kinds of connections would still satisfy WorkManager's (and our won) "connected" constraint.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt [hunk 2]
```diff
@@ -18,10 +18,4 @@ interface TaskSpec {
      * once instead of doing that after every single execution.
      */
     fun getTask(context: Context, inputData: Map<String, String>, isLastUniqueExecution: Boolean): Supplier<Boolean>
-
-    /**
-     * Returns class that can be used to schedule this task using Android's
-     * WorkManager framework
-     */
-    fun getWorkManagerAdapter(): Class<out WorkerAdapter>
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/TaskSpec.kt:26]: I realised we didn't need all this and could just use strings (and no arg constructors) to integrate with WorkManager. It will eventually have to store our class names as strings anyway.

File: async/src/main/java/org/odk/collect/async/network/ConnectivityProvider.kt [hunk 3]
```diff
@@ -0,0 +1,24 @@
+package org.odk.collect.async.network
+
+import android.content.Context
+import android.net.ConnectivityManager
+import org.odk.collect.async.Scheduler
+
+class ConnectivityProvider(private val context: Context) : NetworkStateProvider {
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/network/ConnectivityProvider.kt:7]: We'll need to replace this implementation at some point, as it's pretty much all deprecated.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt [hunk 4]
```diff
@@ -216,6 +214,14 @@ class InstancesDataService(
         }
     }
 
+    fun instanceFinalized(projectId: String, form: Form) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt:217]: I think we'd ideally have a method that's more like:

```
fun finalizeInstance(projectId: String, instance: Instance)
```

But the code that finalises a form during form entry and finalises during bulk finalisation is very different at the moment (the former happens pre save to disk), so that's something for another day.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt [hunk 5]
```diff
@@ -135,6 +175,26 @@ class AutoSendTest {
             )
     }
 
+    @Test
+    fun whenFormHasAutoSendDisabled_fillingAndFinalizingForm_doesNotSendForm_regardlessOfSetting() {
+        testDependencies.server.alwaysReturnError()
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt]: Why do we need this? We are not testing failures here just disabled autosend on a form level.

File: async/src/main/java/org/odk/collect/async/network/NetworkStateProvider.kt [hunk 6]
```diff
@@ -0,0 +1,12 @@
+package org.odk.collect.async.network
+
+import org.odk.collect.async.Scheduler
+
+interface NetworkStateProvider {
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/network/NetworkStateProvider.kt:5]: It's used in `MapBoxInitializationFragment` and you need to fix the import there.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt [hunk 7]
```diff
@@ -1,33 +1,31 @@
...
-import org.odk.collect.settings.enums.StringIdEnumUtils.getAutoSend
 
 object InstanceAutoSendFetcher {
 
     fun getInstancesToAutoSend(
-        application: Application,
         instancesRepository: InstancesRepository,
         formsRepository: FormsRepository,
-        settingsProvider: SettingsProvider
+        formAutoSend: Boolean = false
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:13]: What's going on here? Why would we only get those instances without auto-send enabled on a form level?

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitSchedulerTest.kt [hunk 8]
```diff
@@ -118,15 +119,25 @@ class FormUpdateAndInstanceSubmitSchedulerTest {
...
             eq("AutoSendWorker:myProject"),
-            any<AutoSendTaskSpec>(),
+            any<SendFormsTaskSpec>(),
             eq(mapOf(TaskData.DATA_PROJECT_ID to "myProject")),
             eq(Scheduler.NetworkType.CELLULAR)
         )
     }
 
+    @Test
+    fun `scheduleSubmit does nothing if auto send is disabled`() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitSchedulerTest.kt]: `scheduleSubmit` -> `scheduleAutoSend` and the same in the tests above.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt [hunk 9]
```diff
@@ -1,33 +1,31 @@
...
     ): List<Instance> {
         val allFinalizedForms = instancesRepository.getAllByStatus(
             Instance.STATUS_COMPLETE,
             Instance.STATUS_SUBMISSION_FAILED
         )
 
-        val autoSendSetting =
-            settingsProvider.getUnprotectedSettings().getAutoSend(application)
+        val filter: (Form) -> Boolean = if (formAutoSend) {
+            { form -> form.autoSend != null && form.autoSend == "true" }
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:21]: Are we sure it's simply `true` or `false` not `TREUE`, `FALSE` etc.?

File: async/src/main/java/org/odk/collect/async/network/ConnectivityProvider.kt [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+    override val currentNetwork: Scheduler.NetworkType?
+        get() {
+            return if (connectivityManager.activeNetworkInfo?.isConnected == true) {
+                when (connectivityManager.activeNetworkInfo?.type) {
+                    ConnectivityManager.TYPE_WIFI -> Scheduler.NetworkType.WIFI
+                    ConnectivityManager.TYPE_MOBILE -> Scheduler.NetworkType.CELLULAR
+                    null -> null
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/network/ConnectivityProvider.kt]: Is this case possible?

File: async/build.gradle.kts [hunk 11]
```diff
@@ -42,6 +42,9 @@ dependencies {
     implementation(Dependencies.androidx_core_ktx)
     implementation(Dependencies.kotlinx_coroutines_android)
     implementation(Dependencies.androidx_work_runtime)
+    implementation(project(":analytics")) {
+        exclude("com.google.firebase")
```
Comment (grzesiek2010) [inline async/build.gradle.kts:46]: Why do we need this?

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java [hunk 12]
```diff
@@ -68,19 +68,31 @@ public void cancelUpdates(String projectId) {
...
+        } else if (autoSendSetting == AutoSend.WIFI_AND_CELLULAR) {
+            networkConstraint = null;
+        } else {
+            return;
         }
 
         HashMap<String, String> inputData = new HashMap<>();
         inputData.put(TaskData.DATA_PROJECT_ID, projectId);
-        scheduler.networkDeferred(getAutoSendTag(projectId), new AutoSendTaskSpec(), inputData, networkType);
+        scheduler.networkDeferred(getAutoSendTag(projectId), new SendFormsTaskSpec(), inputData, networkConstraint);
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java:87]: I think we don't need to create objects here like `new SendFormsTaskSpec()`. those objects are never used and we just need the class name to create an object based on it later. That means you can pass class names directly here.

File: async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt [hunk 13]
```diff
@@ -0,0 +1,47 @@
...
+            return Result.retry()
+        }
+
+        val specClass = inputData.getString(DATA_TASK_SPEC_CLASS)!!
+        val spec = Class.forName(specClass).getConstructor().newInstance() as TaskSpec
+
+        val stringInputData = inputData.keyValueMap.mapValues { it.value.toString() }
+        val completed =
+            spec.getTask(applicationContext, stringInputData, isLastUniqueExecution(spec)).get()
+        val maxRetries = spec.maxRetries
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt:29]: You can remove this variable and use `spec.maxRetries` directly.

File: async/src/test/java/org/odk/collect/async/TaskSpecWorkerTest.kt [hunk 14]
```diff
@@ -3,118 +3,157 @@ package org.odk.collect.async
...
+            .withMaxRetries(-1)
+            .doReturn(false)
 
         worker.doWork()
+        assertThat(TestTaskSpec.wasLastUniqueExecution, equalTo(true))
+    }
+}
 
-        verify(spec).getTask(any(), any(), eq(true))
+class TestTaskSpec : TaskSpec {
```
Comment (grzesiek2010) [inline async/src/test/java/org/odk/collect/async/TaskSpecWorkerTest.kt]: It could be private if it's used only by this class.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt [hunk 15]
```diff
@@ -18,10 +18,4 @@ interface TaskSpec {
      * once instead of doing that after every single execution.
      */
     fun getTask(context: Context, inputData: Map<String, String>, isLastUniqueExecution: Boolean): Supplier<Boolean>
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/TaskSpec.kt:20]: I think it should be renamed to `executeTask` for example as this does not return the tasks but just the result `true`/`false`.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt [hunk 16]
```diff
@@ -82,15 +90,20 @@ class AutoSendTest {
...
+                testDependencies.scheduler,
+                R.string.wifi_autosend
+            )
             .copyForm("one-question-autosend.xml")
             .startBlankForm("One Question Autosend")
             .inputText("31")
             .swipeToEndScreen()
             .clickSend()
 
+        testDependencies.networkStateProvider.goOnline(Scheduler.NetworkType.CELLULAR)
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:106]: Why do you need this? Finalizing a form itself should be enough to trigger auto-send right?

**Comment by lognaturel** [comment]
This one would be really great to get in the next beta if possible. @seadowg did you want @getodk/testers to take another look before review or can @grzesiek2010 take a look?

**Comment by seadowg** [comment]
@lognaturel Yup! Thanks for the nudge. @WKobus are you able to take another look?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Comment by grzesiek2010** [comment]
> or can @grzesiek2010 take a look?

I was already finishing my review.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt (hunk 7 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:13]: Because it gets called in two cases:

1. `formAutoSend` is `false`: We are doing a regular auto send triggered by sending a form without auto send enabled at a form level
2. `formAutoSend` is `true`: We are doing an auto end triggered by a form with auto send enabled and just want to send the "opt-in" forms

The two different cases have different network constraints - we don't want to deal with non "opt-in" forms in case 2. I guess we technically could send the form level auto send `true` forms with the other ones if they're waiting to send (in case 1), but I found it simpler to separate the logic out entirely.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt (hunk 9 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:21]: The spec only accounts for `true` and `false`: https://getodk.github.io/xforms-spec/#submission-attributes.

File: async/build.gradle.kts (hunk 11 above)
Comment (seadowg) [reply async/build.gradle.kts:46]: If you remove it, you'll see there's a conflict because of some Guice dependencies both Firebase and WorkManager use.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java (hunk 12 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java:87]: Potentially, I'd need to experiment with `TaskSpecWorker` using a Kotlin object instead of a class (the way the reflection would work would be different if there's no constructor). Let's look at that when we're next playing with async stuff?

File: async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt (hunk 13 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt:29]: It needs to be captured so that the smart cast in `else if` below can work.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt (hunk 15 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/TaskSpec.kt:20]: It returns a `Supplier` that can then be executed and doesn't actually execute any work itself.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt (hunk 16 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:106]: We're checking that the form level auto send runs despite the setting being "Wifi only". To do that we set the current connection to cellular before running background tasks to make sure it doesn't care about the mismatch.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java (hunk 12 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java:87]: Ok.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue #6120 doesn’t occur
- regression checks in auto send options
- finalizing forms and switching to different auto send option that enable/disable sending
- hotspot connected and finalizing/sending forms with different auto send options
- auto send in different and duplicate projects

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14
