### PR TITLE
FIx #1900 Pictures taken by the SelfieWidget are rotated incorrectly …

### LINKED ISSUE #1900: Pictures taken by the SelfieWidget are rotated incorrectly on Android 4.4 and 4.2
#### Software and hardware versions 
Collect v1.12
Android v4.4 and 4.2

#### Problem description
Pictures taken by the SelfieWidget are rotated incorrectly

#### Steps to reproduce the problem
1. User uses device in vertical orientation
2. User takes selfie image
3. Image is rotated

| case/device  | Samsung J1 | Infinix | 
| ------------- | ------------- | ------------- |
| Android | 4.4 | 4.2 |
| selfie widget, front camera, vertical device orientation | **horizontal** | **horizontal** |
| selfie widget, front camera, horizontal device orientation | horizontal | horizontal |

#### Expected behavior
Image is not rotated

#### Other information
Related to #1877

### PR DESCRIPTION
**Pull request by ShenJack**
…on Android 4.4 and 4.2

Closes #1900 

The cause may be that the step to set the **output orientation was forgotten** on the version before. 
  
In this commit, I set the output rotation once the camera instance is obtained.

Test has passed on 7.0.1 using the old Camera API (actually the version android 4.2 and 4.4 use).

More tests are needed.

@mmarciniak90

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java [hunk 1]
```diff
@@ -90,6 +105,11 @@ private void savePhoto(byte[] data) {
         }
     }
 
+    /**
+     * Get an available front {@link Camera} instance, and do some initialization for it.
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: Doc comments should use the indicative verb mood. In this case get -> gets, do -> does.

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java [hunk 2]
```diff
@@ -98,9 +118,23 @@ private Camera getCameraInstance() {
...
+                cameraInfo = camInfo;
                 camera.setDisplayOrientation(90);
+
             }
         }
+
+        // Set the rotation of the camera which the output picture need.
+        if (camera != null) {
+            Camera.Parameters parameters;
+            parameters = camera.getParameters();
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: These two lines can be combined into: 
`Camera.Parameters parameters = camera.getParameters();`
If `parameters` were in scope a bit longer, I would recommend adding `final`.

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java [hunk 3]
```diff
@@ -146,4 +180,19 @@ public static boolean isFrontCameraAvailable() {
         }
         return false; // No front-facing camera found
     }
+
+    /**
+     * Calculate the front camera rotation
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: Verb mood: “Calculates”

**Comment by lognaturel** [comment]
Thank you, @ShenJack! And great comments (@dcbriccetti is right about indicative mood but he's only saying that because the comments are there and good! 😊)

@akshay-ap, you said you were interested in verifying this on your device -- thank you! You can do this by pulling @ShenJack's branch and then running Collect as you usually do:
```
git remote add ShenJack https://github.com/ShenJack/collect
get fetch ShenJack
git checkout fix-1900
```

I just did the same on Android 4.1.1 on an old Alcatel One Touch 5020D and it works great.

**Comment by dcbriccetti** [comment]
>the comments are there and good!

Yes!

**Comment by ShenJack** [comment]
@dcbriccett @lognaturel 
I‘m grateful for your warm reminder, it's really nice to have you here.

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java [hunk 4]
```diff
@@ -98,9 +118,22 @@ private Camera getCameraInstance() {
...
         }
+
+        // Set the rotation of the camera which the output picture need.
+        if (camera != null) {
+            Camera.Parameters parameters = camera.getParameters();
+            int rotation = ORIENTATIONS.get(getWindowManager().getDefaultDisplay().getRotation());
+            parameters.setRotation(calcCameraRotation(rotation));
+            camera.setParameters(parameters);
+        } else {
+            Timber.e("No Available front camera");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: I'm wondering if it should be `Timber.e` it's not our fault if a device doesn't have a front camera but then it's visible in our reports as a fatal issue.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.
Verified cases:
* Device without front camera
* Image Widget with back camera (vertical and horizontal orientation)
* Image Widget with front camera (vertical and horizontal orientation)
* Selfie Widget (vertical and horizontal orientation)

| case/device  | Samsung J1 | Infinix | LG F90 |
| ------------- | ------------- | ------------- | ------------- |
| **Android** | **4.4** | **4.2** | **4.4** |
| selfie widget, front camera, vertical device orientation | vertical | vertical | vertical |
| selfie widget, front camera, horizontal device orientation | horizontal | horizontal | horizontal |

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java (hunk 4 above)
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: I'm wondering if it should be `Timber.e` it's not our fault if a device doesn't have a front camera but then it's visible in our reports as a fatal issue. I think it should be `Timber.w` or even `Timber.i`

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java (hunk 4 above)
Comment (ShenJack) [reply collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java]: I’ll change it right way.

**Review by grzesiek2010 — APPROVED** [review]

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @ShenJack! And great catch on that logging, @grzesiek2010.
