### PR TITLE
Revise notification flows

### LINKED ISSUE #5811: Form opened twice after going to notifications
#### ODK Collect version
the store version 2023.2.4, 2023.3. Beta 1
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
If a user taps some notification (not connected with the form that is being completed) , he is moved e.g. to the list of new forms. Then after going back to the form there are 2 instances of the form opened.
If a form contains background audio recording, the recording is not stopped (while the user is e.g. on the list of new forms).
#### Steps to reproduce the problem
1. There is some notification in the device (e.g. failed update notification – to create use a broken form and add access to it in a project on Central)
[asasas.xml.txt](https://github.com/getodk/collect/files/13205597/asasas.xml.txt)
2. Go to a new form and fill something .
3. Go to notifications and tap the failed update notification.
4. When moved to the list of new forms, open the form from step 2.
5. Edit an already filled answer.
6. Tap the device back button and discard changes.

The form opens again the answer that was entered in step 2 is present.

#### Expected behavior
The form shouldn’t open twice/ the user shouldn't be moved to a different place in the app while the form is opened.
#### Other information
If the notification is connected with a different project ,the user is moved to the other project.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5811 

The solution here is to make all (event) notifications follow these rules:

- Success notifications have title and subtitle, clicking returns to or opens app
- Failure notifications have title and subtitle and "Show details" action, clicking returns to or opens app, clicking action shows errors screen (on top of current task)
- Clicking notification or action dismisses notification

#### Why is this the best possible solution? Were any other approaches considered?

For each case, there are probably better solutions, but for now we want to get on solid ground and avoid any weird problems from notification flows (like that encountered in the issue). The biggest sacrifice we're making here is that we're removing ways for users to fix problems that the notifications are flagging (like failed match exactly syncs). However, these were half baked anyway as they would only work if the user was currently in the correct project and could cause issues if they were midway through form entry.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should only change the behaviour of notifications. It'd be good to try and find if the new flows allow any weird navigation scenarios.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormUpdatesAvailableNotificationBuilder.kt [hunk 1]
```diff
@@ -2,28 +2,19 @@ package org.odk.collect.android.notifications.builders
...
+import org.odk.collect.android.notifications.NotificationUtils
 import org.odk.collect.android.utilities.ApplicationConstants.RequestCodes
 import org.odk.collect.strings.localization.getLocalizedString
 
 object FormUpdatesAvailableNotificationBuilder {
 
     @JvmStatic
     fun build(application: Application, projectName: String): Notification {
-        val intent = Intent(application, FormDownloadListActivity::class.java).apply {
-            putExtra(FormDownloadListActivity.DISPLAY_ONLY_UPDATED_FORMS, true)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormUpdatesAvailableNotificationBuilder.kt:19]: That flag (`DISPLAY_ONLY_UPDATED_FORMS`) was introduced only for this notification I guess so probably we can get rid of it at all?

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt [hunk 2]
```diff
@@ -62,13 +60,13 @@ class PreviouslyDownloadedOnlyTest {
             .clickNotification(
                 "ODK Collect",
                 "Form updates available",
-                GetBlankFormPage()
-            )
+                MainMenuPage()
+            ).pressBackKillingApp()
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt]: Why do we need this here? and only here?

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+object NotificationUtils {
+
+    /**
+     * Creates a [PendingIntent] that will start the [MainMenuActivity]. [MainMenuActivity]
+     * finishes automatically if it's not started as the root of a task, so that means the
+     * [Intent] will either land the user where they were last or reopen the app.
+     */
+    fun createOpenAppContentIntent(context: Context, requestCode: Int): PendingIntent {
+        val intent = Intent(context, MainMenuActivity::class.java)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt]: I believe we handle the case when we try to open the main menu but there are no projects? The scenario would be like:
1. Wait for one of the notifications that opens the main menu.
2. Delete the project.
3. Click the notification.

File: collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt [hunk 4]
```diff
@@ -2,42 +2,49 @@ package org.odk.collect.android.notifications.builders
...
 
         return NotificationCompat.Builder(
             application,
             NotificationManagerNotifier.COLLECT_NOTIFICATION_CHANNEL
         ).apply {
-            setContentIntent(getNotificationPendingIntent(application, allFormsUploadedSuccessfully))
+            setContentIntent(
+                NotificationUtils.createOpenAppContentIntent(
+                    application,
+                    RequestCodes.FORMS_UPLOADED_NOTIFICATION
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt]: Those request codes are not used anywhere so we can keep them in builder classes (here in this class for example).

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt]: And do we need to use the MainMenuActivity here explicitly? How about using the package name like this:
```
        val intent = context
            .packageManager
            .getLaunchIntentForPackage(BuildConfig.APPLICATION_ID)
```

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt [hunk 5]
```diff
@@ -66,8 +66,7 @@ class AutoSendTest {
 
         testDependencies.scheduler.runDeferredTasks()
 
-        mainMenuPage
-            .clickViewSentForm(1)
+        mainMenuPage.clickViewSentForm(1)
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:69]: What's the point of checking this here if we do not check the status (success/failed)? No matter if sending failed or not the form will be there.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt [hunk 6]
```diff
@@ -128,17 +120,17 @@ class AutoSendTest {
...
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:123]: As above:
> What's the point of checking this here if we do not check the status (success/failed)? No matter if sending failed or not the form will be there.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 7]
```diff
@@ -31,36 +32,30 @@ class NotificationDrawer {
...
-
         return this
     }
 
     fun <D : Page<D>> clickAction(
         appName: String,
         actionText: String,
-        destination: D
+        destination: D,
+        cancelsNotification: Boolean = false
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt:58]: This seems to be unused.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 8]
```diff
@@ -113,6 +114,12 @@ class NotificationDrawer {
         isOpen = false
     }
 
+    fun assertNoNotification(appName: String) {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: This can be private.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 9]
```diff
@@ -31,36 +32,30 @@ class NotificationDrawer {
...
+        if (body != null) {
+            assertExpandedText(device, appName, body)
         }
 
-        assertExpandedText(device, appName, subtext)
-
         return this
     }
 
     fun <D : Page<D>> clickAction(
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt:54]: This action seems to always receive the same set of values so maybe it would be good to add them as defaults.

File: collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt]: And maybe if it's not used anywhere else we can use notification ids as those request codes? The ones stored in `NotificationManagerNotifier`:
```
        const val FORM_UPDATE_NOTIFICATION_ID = 0
        const val FORM_SYNC_NOTIFICATION_ID = 1
        private const val AUTO_SEND_RESULT_NOTIFICATION_ID = 1328974928
```

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt]: I'm testing that we don't end up with two Main Menus. I guess it's weird to test that just here and it's so situational that any test is probably not give us as much confidence. I'll take this out and we can rely on the fact that we have confidence from manual testing and that we use the same "return to app" everywhere (`NotificationUtils.createOpenAppContentIntent`).

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/notifications/NotificationUtils.kt]: > I believe we handle the case when we try to open the main menu but there are no projects?

Yeah that would just reopen the launch screen.

> And do we need to use the MainMenuActivity here explicitly?


Oh good call I don't think we do. Will try using the launch intent.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt (hunk 9 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt:54]: The values are always passed from other methods though, so it would mean adding a default app name to `NotificationDrawer`. I'd rather avoid that as there is currently no reason for `NotificationDrawer` to know anything about Collect.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt (hunk 5 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:69]: It's still checking that the form moves to "Sent" which is valuable, but I see your point that it doesn't check that the form ends up with the correct status. I'll have a look into if this is tested elsewhere, and if not add coverage here.

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt:69]: A bunch of other tests fail if I mess with code that updates instance statuses after sending so I think this is ok for now.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java [hunk 10]
```diff
@@ -79,7 +79,6 @@ public abstract static class RequestCodes {
         public static final int CHANGE_SETTINGS = 27;
         public static final int MEDIA_FILE_PATH = 28;
 
-        public static final int FORMS_UPLOADED_NOTIFICATION = 97;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java:82]: If we were able to remove `FORMS_UPLOADED_NOTIFICATION` we probably could remove `FORMS_DOWNLOADED_NOTIFICATION` and `FORM_UPDATES_AVAILABLE_NOTIFICATION` too and use notificationIds instead?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10

**Verified cases:**
- success notification
- failure notification
- clicking notification when another project is opened
- clicking notification while in different parts of the app

**Comment by srujner** [comment]
Tested with Success!

Verified on Androids: 13
