### PR TITLE
Handle null keys in OnSharedPreferenceChangeListener

### LINKED ISSUE #4854: java.lang.NullPointerException: key must not be null in SharedPreferencesSettings.java:97
#### Software and hardware versions 
Collect v2021.3-beta.1

#### Problem description
https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/d4d78455112bae2d503d48f73df9a553?time=last-seven-days&versions=v2021.3-beta.1%20(4292)&sessionEventKey=61667725020300015968C5348B05B0A3_1596873768629674450

```
Fatal Exception: java.lang.NullPointerException: key must not be null
       at org.odk.collect.android.preferences.source.SharedPreferencesSettings.registerOnSettingChangeListener$lambda-0(SharedPreferencesSettings.java:97)
       at org.odk.collect.android.preferences.source.SharedPreferencesSettings.$r8$lambda$7Kl22lxy0uUdedCvQQUrWlYE6o8(SharedPreferencesSettings.java)
       at org.odk.collect.android.preferences.source.SharedPreferencesSettings$$InternalSyntheticLambda$0$351760d6388a07562ff63c51f0ce448e269d4776e379b344df8460c746941a71$0.onSharedPreferenceChanged(SharedPreferencesSettings.java:2)
       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:629)
       at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
       at org.odk.collect.android.preferences.source.SharedPreferencesSettings.clear(SharedPreferencesSettings.java:53)
       at org.odk.collect.android.projects.ProjectDeleter.performProjectDeletion(ProjectDeleter.java:57)
       at org.odk.collect.android.projects.ProjectDeleter.deleteCurrentProject(ProjectDeleter.java:27)
       at org.odk.collect.android.preferences.screens.ProjectManagementPreferencesFragment.deleteProject(ProjectManagementPreferencesFragment.java:83)
       at org.odk.collect.android.preferences.screens.ProjectManagementPreferencesFragment.onPreferenceClick$lambda-1(ProjectManagementPreferencesFragment.java:72)
       at org.odk.collect.android.preferences.screens.ProjectManagementPreferencesFragment.$r8$lambda$AYUTKRulvFDAu3pt2Z_moHJyWnk(ProjectManagementPreferencesFragment.java)
       at org.odk.collect.android.preferences.screens.ProjectManagementPreferencesFragment$$InternalSyntheticLambda$0$42427d181b7c591964ae8282eee025be51edd9e0afee98a384bfa4089dd86635$1.onClick(ProjectManagementPreferencesFragment.java:2)
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4854 

#### What has been done to verify that this works as intended?
The crash occurred while deleting a project on Android 11 so I verified that scenario.

#### Why is this the best possible solution? Were any other approaches considered?
The crash was caused by bumping android_target_sdk to 30 since according to the [documentation](https://developer.android.com/reference/android/content/SharedPreferences.OnSharedPreferenceChangeListener):

> Apps targeting Build.VERSION_CODES.R on devices running OS versions Android R or later, will receive a null value when preferences are cleared.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify that deleting projects on Android 11 does not cause any crash.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/preferences/source/SharedPreferencesSettings.kt [hunk 1]
```diff
@@ -93,8 +93,10 @@ class SharedPreferencesSettings(
 
     override fun registerOnSettingChangeListener(listener: Settings.OnSettingChangeListener) {
         val sharedPreferencesListener =
-            SharedPreferences.OnSharedPreferenceChangeListener { _, key ->
-                listener.onSettingChanged(key)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/preferences/source/SharedPreferencesSettings.kt:97]: I'm guessing we don't need a test for this change as it explodes our UI tests on Android 11?

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/preferences/source/SharedPreferencesSettings.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/preferences/source/SharedPreferencesSettings.kt:97]: Yes. As I said on slack we have test that would catch it if we ran them on API 30.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 11

Tested cases:
- delete demo project 
- delete different server's projects
- delete all projects
- delete project manually from files
- Android 11
- regression checks on other Android versions 
- try to delete project when submissions filled

**Comment by mmarciniak90** [comment]
Tested with success on Android versions: 8.1, 9.0, 10.0
