### PR TITLE
Catch NPE from #4204

### LINKED ISSUE #4204: NPE in FormEntryViewModel.java:86
#### Software and hardware versions 
Collect v1.28.x

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/534ada560093cfeb6de0107286b43b3f?time=last-seven-days&versions=v1.28.3%20(3959)&sessionEventKey=5FA27246022000011325DEFD0327C76A_1469641808994180352

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
       at org.odk.collect.android.formentry.FormEntryViewModel.addRepeat(FormEntryViewModel.java:86)
       at org.odk.collect.android.activities.FormEntryActivity$4.onAddRepeatClicked(FormEntryActivity.java:1763)
       at org.odk.collect.android.formentry.repeats.AddRepeatDialog.lambda$show$0(AddRepeatDialog.java:22)
       at org.odk.collect.android.formentry.repeats.-$$Lambda$AddRepeatDialog$cqe_gnMZqwigRgODoyw0mha9oJI.onClick(-.java:2)
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6819)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
```

The issue is related with: https://github.com/getodk/collect/pull/4148

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4204

#### What has been done to verify that this works as intended?
I added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
There is no other solution we just need to catch null values that `exception.getCause()` might return.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Probably it doesn't require testing since we can't even reproduce the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 1]
```diff
@@ -83,14 +83,14 @@ public void addRepeat(boolean fromPrompt) {
         try {
             formController.newRepeat();
         } catch (RuntimeException e) {
-            error.setValue(e.getCause().getMessage());
+            error.setValue(e.getCause() != null ? e.getCause().getMessage() : "Unknown issue occurred while adding a new group");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: I think that if there's no cause, we should use the exception's own message. That should still provide more specific information.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Ok done.

**Review by lognaturel — APPROVED** [review]
