### PR TITLE
Fixed back button behavior in FormHierarchyActivity

### LINKED ISSUE #3799: Collect crashes when user removes all repeat groups and clicks on device back button
#### Software and hardware versions 
Collect v1.25.1 (older versions were not verified)

#### Problem description
Collect crashes when user removes all repeat groups and clicks on device back button

#### Steps to reproduce the problem
1. User starts form [nested-repeats.xml.txt](https://github.com/getodk/collect/files/4519317/nested-repeats.xml.txt)
2. User adds one group
3. User goes to hierarchy view
4. User clicks on bin
5. User sees empty hierarchy view

6. User clicks on the device back button
7. Collect crashes

##### Alternative case
1. User starts form [repeatTest.xml.txt](https://github.com/getodk/collect/files/4519385/repeatTest.xml.txt)
2. User adds one group
3. User goes to hierarchy view
4. User clicks on bin
5. User clicks on the device back button
6. User is moved to form, dialog 
7. Error dialog is visible in background

#### Expected behavior
Question dialog allowing to add group should appear without errors and crashes

#### Notes
Noticed during testing #3656

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3799

#### What has been done to verify that this works as intended?
I tested the implemented changes manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
We didn't handle a case when the index we started from (opening the `FormHierarchyActivity`) is deleted and then clicking device back button we try to get back to that index. My fix checks the index and tries to navigate back to the first relevant question if the starting index has been deleted. It's the best solution. We could also try to navigate to the beginning/end of the form but I find my solution better.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should just fix the issue and have no side effects. The change in behavior (intended or not) might be only visible if we click device back button being in `FormHierarchyActivity` so just that functionality should be tested.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with repeats.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by SaumiaSinghal — APPROVED** [review]

**Comment by SaumiaSinghal** [comment]
Hi @grzesiek2010, I very much like the changes. My solution just jumps to the beginning of the form. I implemented this as I came across only those crashes in which the `startIndex` was not deleted and forgot to include that case. It is a more promising approach to try and go to the most relevant question if the `startIndex` has been deleted. Thanks for providing a better approach. :)

File: collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java [hunk 1]
```diff
@@ -746,6 +747,29 @@ protected void onBackPressedWithoutLogger() {
         super.onBackPressed();
     }
 
+    private void navigateToTheLastRelevantIndex(FormController formController) {
+        FormEntryController fec = new FormEntryController(new FormEntryModel(formController.getFormDef()));
+        formController.jumpToIndex(startIndex);
+
+        // startIndex might no longer exist if it was a part of repeat group that has been removed
+        while (true) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java:755]: I don't love while(true), but the other option here would be a do-while and I like that even less so I agree with your choice.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java [hunk 2]
```diff
@@ -746,6 +747,29 @@ protected void onBackPressedWithoutLogger() {
         super.onBackPressed();
     }
 
+    private void navigateToTheLastRelevantIndex(FormController formController) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java:750]: I think this is a candidate for moving to JavaRosa's `FormEntryController`. It could become something like `jumpToIndexOrFirstPriorAvailable`. If you agree, please file an issue there. The two advantages are that it reduces complexity in Collect and that we would be able to use really fast unit tests for testing it.

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java:750]: That seems fine I'll file an issue.

**Comment by mmarciniak90** [comment]
@grzesiek2010 I can confirm that mentioned cases work correct but when I turned ON `Don't keep activities` option I noticed that dialog allowing to add group is doubled which causes a crash.

Verified on Androids: 6.0, 7.0, 8.1, 9.0

**Comment by grzesiek2010** [comment]
> but when I turned ON Don't keep activities option I noticed that dialog allowing to add group is doubled which causes a crash.

it's not directly caused by this pr but I fixed it.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 5.1, 7.1 and 10.

Verified cases:
- scenarios from issue
- dark mode light mode
- add and delete more groups
- dont keep activities 
- delete group from hierarchy
- delete group from edit prompt
- different forms with groups
- using back button in hierarchy view

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
