### PR TITLE
Fix crash when media file download fails

### LINKED ISSUE #4324: Crash when downloading media file fails
#### Software and hardware versions 
Collect v1.29.0

#### Problem description

The app crashes if there is an HTTP error when attempting to fetch media files.

#### Steps to reproduce the problem

1. Set up a server where a media file request will fail (with a 500 etc)
2. Download the form with the media file using Get Blank Form

The app will crash

#### Expected behavior

The user should see a failure message rather than a crash.

#### Other information 

Looks like this is because `OkHttpConnection.executeGetRequest` returns `null` in  the event of an HTTP error and our `ServerFormDownloader` is not accounting for a nullable result.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4324 

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

The crash made a lot of sense given how `OkHttpConnection` is tested and behaved so really just needed to add a test to drive out accounting for the failure case in `OpenRosaFormSource`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Just checking the issue is fixed is probably enough.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java [hunk 1]
```diff
@@ -100,13 +100,27 @@ public ManifestFile fetchManifest(String manifestURL) throws FormSourceException
...
+        }
     }
 
     @Override
+    @NotNull
     public InputStream fetchMediaFile(String mediaFileURL) throws FormSourceException {
-        return mapException(() -> openRosaXMLFetcher.getFile(mediaFileURL, null));
+        InputStream mediaFile = mapException(() -> openRosaXMLFetcher.getFile(mediaFileURL, null));
+
+        if (mediaFile != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java]: Wouldn't it be better to check this in mapException and throw `new FormSourceException(FETCH_ERROR)` there? Then it would be in one place.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java]: Yeah, I think you're right. It feels like a good place for some defensive programming.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I still don't think this is new, right? Do you think it should go in the point release, @seadowg? I'm leaning towards yes since it does look very safe.

**Comment by seadowg** [comment]
@lognaturel I was assuming it was new and was introduced during the server code rework, but I could be totally wrong. Either way I think it's good to go in.

**Review by grzesiek2010 — APPROVED** [review]
