### PR TITLE
Fixed creating multiple files for recording selfie videos

### LINKED ISSUE #4268: Unexpected copy of selfie video is visible in main ODK directory if a form is filled after data migration
#### Software and hardware versions 
Collect v1.27.3 (older versions were not verified)

#### Problem description
Unexpected copy of selfie video is visible in main ODK directory if a form is filled after data migration

#### Steps to reproduce the problem
1. ODK data are migrated to internal storage
2. User fills a form with **Selfie video** widget
3. User records selfie video and finishes form

#### Actual result
* Copy of selfie video is visible in main ODK directory 
* Removing submission does not clear the copy of selfie video
* Uninstalling does not remove the copy of selfie video - this behavior does not always occur, the condition is undefined

Screenshot_20201204-135312

#### Expected behavior
Copy of selfie video should not be created

#### Other information 
The issue is not visible if data are not migrated

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4268 

#### What has been done to verify that this works as intended?
I tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that we created a new tmp file for every recording https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4268?expand=1#diff-f63fc4d1f7f735577c9fb1d0cb030deff5c0c4693005671cd7352cdf8a359a85L129 which we didn't remove. I decided to use the same solution we have for image files where we create a reusable tmp file in cache directory https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4268?expand=1#diff-305ec7a913eed2277d0af06a536383d929631be636da49be48e21df4bfb625d4R87

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
With the fix the app should use a reusable tmp file for recording selfie videos instead of creating a new file in the app directory.
It's a safe and isolate change so we can test just the behavior described in the issue.

I also implemented code improvements touching the DrawWidget so please make sure answers are saved witout regression (no need to test changing colors or something just saving output images)

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with selfie video widget like the demo All widgets form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 1]
```diff
@@ -123,10 +124,8 @@ public static void savePhoto(String path, byte[] data) {
...
         }
     }
-  
-    public static String getVideoFilePath(Context context) {
-        final File dir = context.getExternalFilesDir(null);
-        return (dir == null ? "" : (dir.getAbsolutePath() + "/"))
-                + System.currentTimeMillis() + ".mp4";
+
+    public static String getVideoFilePath() {
+        return new StoragePathProvider().getTmpVideoPath();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: If you're going to be creating a new `StoragePathProvider` here anyway I think you can do away with the indirection and just use `new StoragePathProvider().getTmpVideoPath()` inline.

File: collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java [hunk 2]
```diff
@@ -79,11 +79,11 @@ public String getStorageRootDirPath() {
                 : getUnscopedStorageRootDirPath();
     }
 
-    public String getTmpFilePath() {
+    public String getTmpImageFilePath() {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java:82]: This is an existing issue but still want to highlight it. I don't think we know the image is a `jpg`. It could be a `png`, `bmp`, ... We should fix this at some point. Maybe a separate issue?

**Review by lognaturel — CHANGES_REQUESTED** [review]
Nice. One other method to take out of `CameraUtils` and another issue to file, I think.

For QA, please make sure it's clear from the PR description that this also changes the drawing widgets.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: Done.

File: collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java:82]: You are right I'll file an issue.

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java:82]: Hmm unfortunately I think it's not possible... we pass our tmp file starting a camera app because it's a way to capture a full-size photo:
https://developer.android.com/training/camera/photobasics#TaskPath

we don't know what format such an external app is going to return so like in the documentation we use jpg. Then the captured photo is saved to our tmp file.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java:82]: I see. Can we check the mime type and fix the extension later? I think all images are submitted with a jpg extension but maybe I’m remembering wrong.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 9.0

Tested scenarios:
- save form
- finalize
- edit submission
- change video
- change video and ignore changes 
- remove submission
- regression checks on: image, audio, draw, signature, annotate, video, selfie, file widgets

**Comment by mmarciniak90** [comment]
Verified on Android versions: 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

File: collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java:82]: No really, I mean we can read mime type using the tmp file where an external app saves captured photos but it's pointless because it will always be jpeg.
