### PR TITLE
Fixed BaseEncoding$DecodingException

### LINKED ISSUE #4740: BaseEncoding$DecodingException
#### Software and hardware versions 
Collect v2021.2.0

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/af3e3def7568395f1fe76cadafc4bb5a?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=61009DC6028300010C4FE545FB872E17_1568208913187990777

```
Caused by com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: :
       at com.google.common.io.BaseEncoding$Alphabet.decode(BaseEncoding.java:492)
       at com.google.common.io.BaseEncoding$Base64Encoding.decodeTo(BaseEncoding.java:974)
       at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:233)
       at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:217)
       at com.google.api.client.util.Base64.decodeBase64(Base64.java:104)
       at org.odk.collect.android.utilities.CompressionUtils.decompress(CompressionUtils.java:74)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$startScanning$1.onChanged(QrCodeProjectCreatorDialog.java:219)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$startScanning$1.onChanged(QrCodeProjectCreatorDialog.java:41)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at org.odk.collect.android.views.BarcodeViewDecoder$1.barcodeResult(BarcodeViewDecoder.java:21)
       at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
       at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4740 

#### What has been done to verify that this works as intended?
I reproduced the issue and verified that the fix does the job. I also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
The only solution is to catch exception that might be thrown if we scan invalid qr codes and display a toast like I did. We do the same in other parts of our project. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix so we can focus on verifying that the issue no longer exist.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt [hunk 1]
```diff
@@ -128,4 +131,37 @@ class QrCodeProjectCreatorDialogTest {
...
+                settingsImporter: SettingsImporter?,
+                context: Context,
+                storagePathProvider: StoragePathProvider
+            ): ProjectCreator {
+                return projectCreator
+            }
+        })
+
+        val scenario = RobolectricHelpers.launchDialogFragmentInContainer(QrCodeProjectCreatorDialog::class.java, R.style.Theme_MaterialComponents)
+        scenario.onFragment {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt]: Not a big deal, but just to point out that we don't need the assertions to be in `onFragment` here. That's only needed if we have to access the `Fragment` itself. Good to change before merging!

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 5.1, 8.1, 9.0, 10.0, 11.0

Verified cases:
* invalid QR code - toast with message 'QR code does not contain valid settings' is visible
* invalid, inverted QR code
* valid QR code
* valid inverted QR code
* scan QR codes from the first launch screen
* scan QR codes form Add project options

File: collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt]: Fixed.
