### PR TITLE
Nested groups with `field-list` appearance

### LINKED ISSUE #1255: Nested groups with `field-list` appearance
Analyzing the firebase crash reports I found out that some users might try to use a form that contains a group with `field-list` appearance which contains another group. It's not allowed and I'm wondering if there is any particular reason why. 
Everything inside that group with  `field-list` appearance should be displayed on one page of course other groups as well even if they don't have `field-list` appearance.

What do you think?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1255 

#### What has been done to verify that this works as intended?
I tested lots of cases and I prepared an automated test.

#### Why is this the best possible solution? Were any other approaches considered?
We should allow adding groups inside a field-list group. I mean regular groups not repeat sections (it doesn't make sense), that's why I used a code for recursively grabbing all indices in a field-list group. This is the only solution I can imagine here.

#### Are there any risks to merging this code? If so, what are they?
In my opinion, it's very risky. I tried to be careful and I tested lot's of cases, I prepared an automated test too but you can never be sure everything is ok. It's possible I missed something. That's why I think that navigation in forms should be really really well tested by @mmarciniak90  

#### Do we need any specific form for testing your changes? If so, please attach one.
[form1.xml.txt](https://github.com/opendatakit/collect/files/1681571/form1.xml.txt)
[form2.xml.txt](https://github.com/opendatakit/collect/files/1681572/form2.xml.txt)
[form3.xml.txt](https://github.com/opendatakit/collect/files/1681573/form3.xml.txt)
[form4.xml.txt](https://github.com/opendatakit/collect/files/1681574/form4.xml.txt)
[form5.xml.txt](https://github.com/opendatakit/collect/files/1681575/form5.xml.txt)
[form6.xml.txt](https://github.com/opendatakit/collect/files/1681576/form6.xml.txt)
[form7.xml.txt](https://github.com/opendatakit/collect/files/1681577/form7.xml.txt)
[form8.xml.txt](https://github.com/opendatakit/collect/files/1681578/form8.xml.txt)
[form9.xml.txt](https://github.com/opendatakit/collect/files/1681579/form9.xml.txt)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
If it's ok we should create a separate issue for visual improvements because we need to decide how to highlight nested group names.

**Comment by mmarciniak90** [comment]
I noticed one case:
* User starts form: [metadata2.xml.txt](https://github.com/opendatakit/collect/files/1689484/metadata2.xml.txt)

Results:
* Error message is visible on Collect v1.12.2

* Loading form does not end on Collect with this changes

**Comment by grzesiek2010** [comment]
@mmarciniak90 
I tried v1.12.2 and current master branch and I can't see such a dialog. Please check other devices. If it's not a problem caused by my changes we should create a separate issue.

**Comment by mmarciniak90** [comment]
Yes, @grzesiek2010  you have right. This problem depends on Android version. 
Error dialog is visible on Android 4.4 and below.
Loading form does not end on Android 5.1 and above.
I created a separate issue #1833

**Comment by mmarciniak90** [comment]
Tested with success!
Verified on Android: 4.1, 4.4, 5.1, 6.0, 7.0

@opendatakit-bot label "behavior verified"

**Comment by dcbriccetti** [comment]
I’m looking at this now.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 1]
```diff
@@ -503,18 +510,14 @@ public int stepToNextEvent(boolean stepIntoGroup) {
...
                         getFormIndex(), true); // descend into group
-        for (int i = 0; i < gd.getChildren().size(); i++) {
-            indicies.add(idxChild);
-            // don't descend
-            idxChild = formEntryController.getModel().incrementIndex(idxChild, false);
-        }
+        indicies.addAll(getIndices(gd, idxChild));
 
         // jump to the end of the group
         formEntryController.jumpToIndex(indicies.get(indicies.size() - 1));
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Why add the result of getIndices to a second List? I suggest a simplification. Note the correct spelling of *indices*, and use of the more general `List` instead of `ArrayList`.

screen shot 2018-02-07 at 3 19 08 pm

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 2]
```diff
@@ -399,8 +399,15 @@ private boolean indexIsInFieldList(FormIndex index) {
                 // no group
                 return false;
             }
-            FormEntryCaption grp = captions[captions.length - 2];
-            return groupIsFieldList(grp.getIndex());
+            // If at least one of groups you are inside is field list your index is in field list
+            boolean groupIsFieldList;
+            for (FormEntryCaption caption : captions) {
+                groupIsFieldList = groupIsFieldList(caption.getIndex());
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: I suggest inlining `groupIsFieldList`. You’ll remove two lines of code and lose no clarity.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 3]
```diff
@@ -570,13 +569,12 @@ public int stepToPreviousScreenEvent() throws JavaRosaException {
...
-                                FormEntryCaption fc = fclist[fclist.length - 2];
-                                GroupDef pd = (GroupDef) fc.getFormElement();
-                                if (pd.getChildren().size() == 1
-                                        && ODKView.FIELD_LIST.equalsIgnoreCase(
-                                                pd.getAppearanceAttr())) {
-                                    formEntryController.jumpToIndex(fc.getIndex());
+                            boolean groupIsFieldList;
+                            for (FormEntryCaption caption : fclist) {
+                                groupIsFieldList = groupIsFieldList(caption.getIndex());
+                                if (groupIsFieldList) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Inline

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 4]
```diff
@@ -812,7 +810,7 @@ public void setLanguage(String language) {
      */
     public FormEntryPrompt[] getQuestionPrompts() throws RuntimeException {
 
-        ArrayList<FormIndex> indicies = new ArrayList<FormIndex>();
+        ArrayList<FormIndex> indicies = new ArrayList<>();
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Spelling, and it’s a good practice to make the type general: `List` in this case.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 5]
```diff
@@ -880,6 +853,23 @@ public void setLanguage(String language) {
         return questions;
     }
 
+    private List<FormIndex> getIndices(GroupDef gd, FormIndex idxChild) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: I wonder if this method could be made easier to read and understand. I offer some suggestions. 

screen shot 2018-02-07 at 4 01 20 pm

It might be clearer still if you didn’t modify the formal parameter idxChild. And even though this is a private method, a doc comment might be warranted.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 6]
```diff
@@ -503,18 +510,14 @@ public int stepToNextEvent(boolean stepIntoGroup) {
...
                         .getChild(getFormIndex());
         FormIndex idxChild =
                 formEntryController.getModel().incrementIndex(
                         getFormIndex(), true); // descend into group
-        for (int i = 0; i < gd.getChildren().size(); i++) {
-            indicies.add(idxChild);
-            // don't descend
-            idxChild = formEntryController.getModel().incrementIndex(idxChild, false);
-        }
+        indicies.addAll(getIndices(gd, idxChild));
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Why add the result of getIndices to a second List? I suggest a simplification. Note the correct spelling of *indices*, and use of the more general `List` instead of `ArrayList`.

screen shot 2018-02-07 at 3 19 08 pm

**Comment by dcbriccetti** [comment]
Now I’ll get in and really understand the change, and may have more comments.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 7]
```diff
@@ -0,0 +1,390 @@
...
+
+            @Override
+            public void onProgressStep(String stepMessage) {
+
+            }
+        });
+        formLoaderTask.execute(formPath(formName));
+    }
+
+    @Test
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: There are 390 lines of code spent in this file. How about factoring out the identical parts of these tests, or combining them in some other way.

“My point today is that, if we wish to count lines of code, we should not regard them as "lines produced" but as "lines spent": the current conventional wisdom is so foolish as to book that count on the wrong side of the ledger.”
Dijkstra (1988) "On the cruelty of really teaching computing science (EWD1036).

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
This concludes phase one of my review. I’ll return after FormController.getIndices is easier to understand.

**Comment by grzesiek2010** [comment]
@dcbriccetti Thanks for your review, I implemented all code improvements you suggested and refactored the test too.

**Comment by grzesiek2010** [comment]
I'm adding @opendatakit-bot label "behavior verified" again since removing it was a mistake.

File: collect_app/src/androidTest/assets/forms/formNavigationTestForms/form1.xml [hunk 8]
```diff
@@ -0,0 +1,61 @@
+<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
+    <h:head>
+        <h:title>form1</h:title>
```
Comment (lognaturel) [inline collect_app/src/androidTest/assets/forms/formNavigationTestForms/form1.xml]: Name something like group-bind-no-ref-in-fieldlist

File: collect_app/src/androidTest/assets/forms/formNavigationTestForms/form2.xml [hunk 9]
```diff
@@ -0,0 +1,61 @@
+<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
+    <h:head>
+        <h:title>form2</h:title>
+        <model>
+            <instance>
+                <data id="build_form2_1517303824">
```
Comment (lognaturel) [inline collect_app/src/androidTest/assets/forms/formNavigationTestForms/form2.xml]: Name something like field-list-in-field-list

File: collect_app/src/androidTest/assets/forms/formNavigationTestForms/form3.xml [hunk 10]
```diff
@@ -0,0 +1,61 @@
+<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
+    <h:head>
+        <h:title>form3</h:title>
```
Comment (lognaturel) [inline collect_app/src/androidTest/assets/forms/formNavigationTestForms/form3.xml]: Name something like group-no-bind-no-ref-in-field-list

File: collect_app/src/androidTest/assets/forms/formNavigationTestForms/form4.xml [hunk 11]
```diff
@@ -0,0 +1,61 @@
+<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
+    <h:head>
+        <h:title>form4</h:title>
+        <model>
+            <instance>
+                <data id="build_form4_1517307219">
```
Comment (lognaturel) [inline collect_app/src/androidTest/assets/forms/formNavigationTestForms/form4.xml]: group-no-bind-no-ref-in-group

File: collect_app/src/androidTest/assets/forms/formNavigationTestForms/form5.xml [hunk 12]
```diff
@@ -0,0 +1,61 @@
+<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
+    <h:head>
+        <h:title>form5</h:title>
+        <model>
+            <instance>
+                <data id="build_form4_1517307426">
```
Comment (lognaturel) [inline collect_app/src/androidTest/assets/forms/formNavigationTestForms/form5.xml]: group-no-bind-no-ref-after-text-in-group

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 13]
```diff
@@ -570,13 +567,10 @@ public int stepToPreviousScreenEvent() throws JavaRosaException {
                         if (ODKView.FIELD_LIST.equalsIgnoreCase(gd.getAppearanceAttr())) {
                             // OK this group is a field-list... see what the parent is...
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Replace with `// jump to outermost containing field-list`

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 14]
```diff
@@ -812,7 +806,7 @@ public void setLanguage(String language) {
      */
     public FormEntryPrompt[] getQuestionPrompts() throws RuntimeException {
 
-        ArrayList<FormIndex> indicies = new ArrayList<FormIndex>();
+        List<FormIndex> indices = new ArrayList<>();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Should be declared when `getIndicesForForGroup` is first called so you don't need the `addAll`.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 15]
```diff
@@ -880,6 +849,24 @@ public void setLanguage(String language) {
         return questions;
     }
 
+    private List<FormIndex> getIndicesForGroup(GroupDef gd, FormIndex idxChild) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: A comment here would be helpful. Something like `Recursively get all indices contained in this group and its children.`

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: I would tend to split this into a method that only takes a `GroupDef` as a parameter and a recursive helper that takes both the group and the index (`currentChild` would be a more descriptive name).

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 16]
```diff
@@ -824,41 +818,16 @@ public void setLanguage(String language) {
...
-
-            if (gd.getChildren().size() == 1 && getEvent(idxChild)
-                    == FormEntryController.EVENT_GROUP) {
-                // if we have a group definition within a field-list attribute group, and this is
-                // the
-                // only child in the group, check to see if it is also a field-list appearance.
-                // If it is, then silently recurse into it to pick up its elements.
-                // Work-around for the inconsistent treatment of field-list groups and repeats in
-                // 1.1.7 that
-                // either breaks forms generated by build or breaks forms generated by XLSForm.
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: @grzesiek2010 Do you understand what broken state this was referring to? The commit that removes this comment should have a description of why it is no longer relevant. It might also be helpful to include some tests that use forms from XLSForm. The only difference I know of is that XLSForm includes `ref` attributes on groups whereas Build doesn't but there may be something else.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 17]
```diff
@@ -824,41 +818,16 @@ public void setLanguage(String language) {
...
-                idxChild = formEntryController.getModel().incrementIndex(idxChild, false);
-            }
+            indices.addAll(getIndicesForGroup(gd, idxChild));
 
             // we only display relevant questions
-            ArrayList<FormEntryPrompt> questionList = new ArrayList<FormEntryPrompt>();
-            for (int i = 0; i < indicies.size(); i++) {
-                FormIndex index = indicies.get(i);
+            List<FormEntryPrompt> questionList = new ArrayList<>();
+            for (int i = 0; i < indices.size(); i++) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: While you're here, change to `for (FormIndex index : indices)`?

**Review by lognaturel — DISMISSED** [review]
Nice, @grzesiek2010! This is complex code. The PR template question about the best possible solution is a good opportunity to consider the way the code was written. For example, in this case, is recursively grabbing all indices in a group the only approach? What else might you have considered? Why is it a necessary change?

It's great to see some tests as well. Could you please name the XML files according to the cases that they test? I made some suggestions. It would also be helpful to have a comment in the test file describing why these tests are valuable and what issue they relate to. Consider also making clear which cases failed before your implemented changes and why. Finally, when there is a failure it should be clear which of the forms has failed. Currently it's not clear because we always get a comparison error in the same `testIndices` method.

@dcbriccetti Anything else from your side?

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 18]
```diff
@@ -44,315 +44,60 @@
     private static final String FORMS_DIRECTORY = "/odk/forms/";
 
     @Test
-    public void test1() throws IOException {
+    public void formNavigationTestCase() throws IOException {
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: It’s great to see this so much shorter. Thanks.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java (hunk 14 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Yes, indeed.
screen shot 2018-02-18 at 6 47 10 pm

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java (hunk 18 above)
Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: Yes but now it's not possible to tell what case failed! I think this is a good opportunity for parameterized tests.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java (hunk 16 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: It was possible to have a field-list group inside another field-list but only if it was the only child. I tested such a form as I remember. It was just one case when you were able to have another group inside a field-list before my changes. So we just handled the simplest case as I understand.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: Since I implemented changes for handling everything we don't need that.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: It was this case https://github.com/grzesiek2010/collect/blob/559b87a4d1ac23550a7d214ca6b36f561b97bf10/collect_app/src/androidTest/assets/forms/formNavigationTestForms/fieldListInFieldList.xml

**Comment by grzesiek2010** [comment]
@lognaturel I think it's ready.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 19]
```diff
@@ -842,21 +837,22 @@ public void setLanguage(String language) {
...
-            // We have a quesion, so just get the one prompt
+            // We have a question, so just get the one prompt
             questions[0] = getQuestionPrompt();
         }
 
         return questions;
     }
 
-    private List<FormIndex> getIndices(GroupDef gd, FormIndex idxChild) {
+    // Recursively get all indices contained in this group and its children
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Might as well make this a doc comment and change the verb mood to declarative: “gets”.
/** Recursively gets all indices contained in this group and its children */

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java (hunk 15 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: I wanted to work out what you meant here, @lognaturel. Like this?

screen shot 2018-02-19 at 1 04 49 pm

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: That’s what I had in mind. Worth it or just personal preference? I also don’t think idxChild is a very helpful name and would tend to use currentChild or something that doesn’t require thinking.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: I think it’s worth it. I also like currentChild (or idxCurrentChild or currentChildIndex), but forgot to make that change in the code shown above.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: It removes code duplication, and the concern of finding the starting index, from the callers.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java (hunk 16 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: This does not answer the question of WHY the field-list in field-list case was explicitly handled. The comment makes it seem like that was a deliberate choice and that has me nervous.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java (hunk 18 above)
Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: @grzesiek2010 do you see what I mean by this? For example, change any of the `"-1, "` entries to `"-10"`. How will you know which case failed? 

You can read about parameterized tests at https://github.com/junit-team/junit4/wiki/parameterized-tests and @ggalmazor will surely have some good advice if you need.

Good to see a comment at the top! "it might be tricky" should be elaborated on -- what are the kinds of errors or regressions this verifies? Tests can be a big help when getting to know new code so it's a good opportunity to provide a little context. What do the lists of numbers represent? Why do you go backwards once at the end while navigating the form? Etc.

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java (hunk 16 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/logic/FormController.java:836]: So I don't know why. I guess it was the easiest case and someone wanted to handle that (at least that). Now we want to handle all possible cases. But I don't really understand the last line.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java (hunk 18 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: I implemented changes using parameterized tests let me know if it is satisfying for you.

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: But there is one problem when any test failed it displays a name of the last one...I'm not sure why it was ok when I tested an example from your link. I guess it's because we load a form and it's another task.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 20]
```diff
@@ -0,0 +1,139 @@
...
+import java.io.OutputStream;
+import java.util.Arrays;
+
+import timber.log.Timber;
+
+import static junit.framework.Assert.assertEquals;
+
+/**
+ * This test has been created in order to check indices while navigating through a form.
+ * It's especially important while navigate through a form which contains nested groups and if we
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: while navigating through a form that contains

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 21]
```diff
@@ -0,0 +1,139 @@
...
+ * use groups with field-list appearance because in that case we need to collect all indices of
+ * questions we want to display on one page (we need to recursively get all indices contained in
+ * such a group and its children). It might be also tricky when navigate backwards because then we
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: navigating

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 22]
```diff
@@ -0,0 +1,139 @@
...
+            prepareFile(formName);
+        } catch (IOException e) {
+            Timber.i(e);
+        }
+        FormLoaderTask formLoaderTask = new FormLoaderTask(formPath(formName), null, null);
+        formLoaderTask.setFormLoaderListener(new FormLoaderListener() {
+            @Override
+            public void loadingComplete(FormLoaderTask task) {
+                try {
+                    for (int i = 0; i < expectedIndices.length - 1; i++) {
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: I’m finding it challenging to understand the “- 1”, “- 2”, “stepToNext...”, “stepToPrevious...”, “+ 1”, and why there are two assertEquals(expectedIndices...) each time through the loop. I wonder if a few comments in here would help me and others.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 23]
```diff
@@ -0,0 +1,139 @@
...
+
+            @Override
+            public void onProgressStep(String stepMessage) {
+
+            }
+        });
+        formLoaderTask.execute(formPath(formName));
+    }
+
+    private void prepareFile(String formName) throws IOException {
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: Pardon my Android ignorance, but why must we copy these files? Perhaps the method name, or a comment, could say why.

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: It's because FormLoaderTask loads forms from SD card so we need to put all forms there. I added a comment.

**Comment by grzesiek2010** [comment]
@lognaturel I fixed the problem with my test: https://github.com/opendatakit/collect/pull/1821/commits/fa52abe20f94f4a29f972a1f1089919d1d01a98a 
As I thought it was because of used AsyncTask.
I added [AsynctTask().get()](https://developer.android.com/reference/android/os/AsyncTask.html#get%28%29) and now I know which set of parameters failed.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java (hunk 22 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: We have two asserts because I check the current index and the index after navigating (back or forward). I added a comment.

Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: I agree this is still confusing. How about a comment on `testIndices` that says something like "For each form, simulate swiping forward through screens until the end of the form and then swiping back once. Verify the expected indices before and after each swipe."

And for the test patterns, something above the array like "Expected indices when swiping forward until the end of the form and back once. An index of `-1` indicates the start or end of a form."

I don't really know how/if to explain what the `FormIndex` toString represents (comma-separated lists). A `FormIndex` represents where in the form we are. The `toString` prints out the path through nested structures that gets us to the current screen. The idea is that a field-list should not have any nesting. That's why they show up as "0". The tests demonstrate that this is true even when other groups are nested in the field list. Something like "0, 0, 2" means it's the 3rd question within two levels of nesting, both groups being the first at their level.

I think it's ok to just add the two comments I mentioned above. @dcbriccetti?

**Review by lognaturel — COMMENTED** [review]
It's still a bit hard to tell where a failure has occurred because all forms have multiple -1 entries and some have other duplicates but at least it's clear which form is failing so I'm satisfied. I've suggested a couple more comments to add. @dcbriccetti, please mark as `needs testing` when you're ok with this.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java (hunk 22 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: I've just added comments.

**Comment by lognaturel** [comment]
@dcbriccetti Have the changes you requested been satisfyingly addressed?

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 24]
```diff
@@ -0,0 +1,149 @@
...
+ */
+@RunWith(Parameterized.class)
+public class FormNavigationTestCase {
+
+    private static final String FORMS_DIRECTORY = "/odk/forms/";
+
+    @Parameters(name = "{0}")
+    public static Iterable<Object[]> data() {
+        // Expected indices when swiping forward until the end of the form and back once.
+        // An index of -1 indicates the start or end of a form
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: A single comment with no period is fine. But when there are two sentences together they should both end with periods.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 25]
```diff
@@ -0,0 +1,149 @@
...
+        } catch (IOException e) {
+            Timber.i(e);
+        }
+        FormLoaderTask formLoaderTask = new FormLoaderTask(formPath(formName), null, null);
+        formLoaderTask.setFormLoaderListener(new FormLoaderListener() {
+            @Override
+            public void loadingComplete(FormLoaderTask task) {
+                try {
+                    // For each form, simulate swiping forward through screens until the end of the
+                    // form and then swiping back once. Verify the expected indices before and after each swipe
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: The second sentence needs a period.

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 26]
```diff
@@ -0,0 +1,149 @@
...
+
+            }
+        });
+        formLoaderTask.execute(formPath(formName)).get();
+    }
+
+    /*
+    FormLoaderTask loads forms from SD card so we need to put each form there
+     */
+    private void prepareFile(String formName) throws IOException {
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: This could be a doc comment ( /** ... */ ). Might the method have a more descriptive, specific name? `copyToSdCard`, perhaps?

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 27]
```diff
@@ -399,8 +400,13 @@ private boolean indexIsInFieldList(FormIndex index) {
                 // no group
                 return false;
             }
-            FormEntryCaption grp = captions[captions.length - 2];
-            return groupIsFieldList(grp.getIndex());
+            // If at least one of groups you are inside is field list your index is in field list
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]:
```
If at least one of     groups you are inside is   field list  your index is in   field list
If at least one of the groups you are inside is a field list, your index is in a field list
```

File: collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java [hunk 28]
```diff
@@ -0,0 +1,149 @@
...
+                {"fieldListInFieldList.xml", new String[] {"-1, ", "0, ", "-1, ", "0, "}},
+                {"regularGroupWithFieldListGroupInside.xml", new String[] {"-1, ", "0, 0, ", "-1, ", "0, 0, "}},
+                {"twoNestedRegularGroups.xml", new String[] {"-1, ", "0, 0, 0, ", "0, 0, 1, ", "0, 0, 2, ", "-1, ", "0, 0, 2, "}},
+                {"regularGroupWithQuestionAndRegularGroupInside.xml", new String[] {"-1, ", "0, 0, ", "0, 1, 0, ", "0, 1, 1, ", "-1, ", "0, 1, 1, "}},
+                {"regularGroupWithQuestionsAndRegularGroupInside.xml", new String[] {"-1, ", "0, 0, ", "0, 1, 0, ", "0, 2, ", "-1, ", "0, 2, "}},
+                {"fieldListWithQuestionAndRegularGroupInside.xml", new String[] {"-1, ", "0, ", "-1, ", "0, "}},
+                {"fieldListWithQuestionsAndRegularGroupsInside.xml", new String[] {"-1, ", "0, ", "-1, ", "0, "}},
+                {"threeNestedFieldListGroups.xml", new String[] {"-1, ", "0, ", "-1, ", "0, "}}
+        });
+    }
```
Comment (dcbriccetti) [inline collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java]: You might consider a further beautification like this, to remove some boilerplate and line things up better. If you prefer it how you have it now, that’s fine with me. This is inspired by domain-specific languages.
```
@Parameters(name = "{0}")
public static Iterable<Object[]> data() {
    // Expected indices when swiping forward until the end of the form and back once.
    // An index of -1 indicates the start or end of a form
    return Arrays.asList(
            ei("simpleFieldList.xml",
                    "-1, ", "0, ", "-1, ", "0, "),
            ei("fieldListInFieldList.xml",
                    "-1, ", "0, ", "-1, ", "0, "),
            ei("regularGroupWithFieldListGroupInside.xml",
                    "-1, ", "0, 0, ", "-1, ", "0, 0, "),
            ei("twoNestedRegularGroups.xml",
                    "-1, ", "0, 0, 0, ", "0, 0, 1, ", "0, 0, 2, ", "-1, ", "0, 0, 2, "),
            ei("regularGroupWithQuestionAndRegularGroupInside.xml",
                    "-1, ", "0, 0, ", "0, 1, 0, ", "0, 1, 1, ", "-1, ", "0, 1, 1, "),
            ei("regularGroupWithQuestionsAndRegularGroupInside.xml",
                    "-1, ", "0, 0, ", "0, 1, 0, ", "0, 2, ", "-1, ", "0, 2, "),
            ei("fieldListWithQuestionAndRegularGroupInside.xml",
                    "-1, ", "0, ", "-1, ", "0, "),
            ei("fieldListWithQuestionsAndRegularGroupsInside.xml",
                    "-1, ", "0, ", "-1, ", "0, "),
            ei("threeNestedFieldListGroups.xml",
                    "-1, ", "0, ", "-1, ", "0, "));
}

/** Expected indices for each form */
private static Object[] ei(String formName, String... expectedIndices) {
    return new Object[] {formName, expectedIndices};
}

```

**Comment by dcbriccetti** [comment]
Thanks, @grzesiek2010. I made some more suggestions, none of which would change the logic if implemented, so I’ll now mark as needs testing.

**Review by dcbriccetti — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Verified cases:
* new forms
* saved forms
* jumping to question / go to end / go to start

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank for your patience through all the iterating here, @grzesiek2010!
