### PR TITLE
Fixed hiding error in external widgets

### LINKED ISSUE #6266: Constraint violation message is not dismissed when value from external app changes
#### ODK Collect version
v2024.2.0

#### Android version
Android 14

#### Device used
Galaxy A13

#### Problem description
Using an external app question, when I get a different value from the external app, I may still see a stale error message that does not apply to the new value.

#### Steps to reproduce the problem
Use a form with an external app call and a constraint on it such as [this one](https://docs.google.com/spreadsheets/d/1XCPbItGnIxBDuQgAT4uhC5sYkd2cxiYDq3EpjIBhBu0/edit?gid=0#gid=0)
Violate the constraint, see that a message is shown as expected
Launch the app again, see that the message is still shown

#### Expected behavior
The error message is dismissed when the constraint condition is met

#### Other information 

I did some initial debugging and noticed that `ExStringWidget.hideError` overrides `QuestionWidget.hideError` without calling `super`. I added the `super` call and I believe that results in the currently-expected behavior: the error message is dismissed whenever the value changes.

~My original expectation was that values from external apps (+ barcode, etc) would be validated on return to Collect. I guess that would be different from other question types so maybe we don't want that? I also expected that fields in field lists would get their validation messages updated dynamically but it looks like it's only done on swipe, right?~ We can split this out into a separate issue if we eventually want but it's probably not that important.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6266 

#### Why is this the best possible solution? Were any other approaches considered?
It's a bug fix so nothing to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks? 
This fixes hiding errors in external string widgets. Other widgets should not be affected but we can't be sure maybe we have similar issues with other types of questions as well (it would be good to test them).

#### Do we need any specific form for testing your changes? If so, please attach one.
The form that is attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java [hunk 1]
```diff
@@ -64,6 +66,26 @@ public void widgetShouldBeRegisteredForContextMenu() {
         assertThat(viewsRegisterForContextMenu.get(1).getId(), is(widget.getId()));
     }
 
+    @Test
+    public void errorDisappearsOnSetData() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java:70]: We should have such tests for other question types. Here is a separate issue for that https://github.com/getodk/collect/issues/6274.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success**

Verified on devices with Android 10, 14

**Verified Cases:**

- Issue #6266 does not occur
- External question types with constraint appearance
- Regression check on constraint appearance
