### PR TITLE
Always release the lock on form exit

### LINKED ISSUE #6763: Blocked opening and downloading entity forms after opening a manually added form with the wrong entity spec version
#### ODK Collect version
the store version 2025.1.5, v2025.2.0 beta 5
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Blocked opening and downloading entity forms after opening a manually added form with the wrong entity spec version. After following steps below there’s information about blocking entity forms because of updating entities. It isn't possible to download forms (no progress bar) and it isn't possible to open entities form.
#### Steps to reproduce the problem
1. Download a project with some entity forms user 2084 in https://test.getodk.cloud/projects/564/app-users.
2. Manually add an entity form with the wrong entity spec version to the forms folder.
[trees_update_non_existing_spec.xml.txt](https://github.com/user-attachments/files/20651108/trees_update_non_existing_spec.xml.txt)
3. Go to Start new form and open the form.
4. Tap ok in the error message
5. In Start new form tap the arrow to refresh the list (check the progress bar).
6. Try to open any of the entity forms
#### Expected behavior
Opening forms shouldn't be blocked. Downloading should work as expected.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6763 

#### Why is this the best possible solution? Were any other approaches considered?
See the comment below.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think we can focus on the scenario described in the issue. I don’t see any other risks.

#### Do we need any specific form for testing your changes? If so, please attach one.
As described in the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 1]
```diff
@@ -374,9 +374,7 @@ private void updateIndex(boolean isAsync, @Nullable FailedValidationResult valid
     public void exit() {
         formSessionRepository.clear(sessionId);
         ReferenceManager.instance().reset();
-        if (form != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:377]: `form` can be `null` if it can't be opened (as in the case described in the issue). In that situation, if a lock was acquired during form opening, it couldn’t be released on form exit.
We no longer need that check, since we now use `FORM_ENTRY_TOKEN` to acquire and release the lock (previously it was `formFilePath`).

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 are you able to add a test as well? Otherwise, this is good to go.

**Comment by dbemke** [comment]
**Tested with success!**

Verified on a device with Android 10

**Comment by WKobus** [comment]
Tested with success!

Verified on a device with Android 15
