### PR TITLE
Fixed decoding qr codes

### LINKED ISSUE #5984: Some QR codes with settings can't be recognized
#### ODK Collect version
v2024.1

#### Problem description
Some QR codes with settings can't be recognized. I've reproduced the issue with the QR code that the user reporting the issue shared with me in private. Unfortunately, the QR code contains private data so I can't share it here.
I was able to reproduce the issue using just that one QR (trying ~30 others) so it indicates it's rather a rare case.

#### Steps to reproduce the problem
Just try to scan or import a QR code.

#### Expected behavior
All valid QR codes should be recognized and the settings they store loaded correctly. 

#### Other information 
The problem was originally reported on the forum: https://forum.getodk.org/t/import-qr-code-settings-error-odk-v2024-1/45267

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5984 

#### Why is this the best possible solution? Were any other approaches considered?
[DecodeHintType.PURE_BARCODE](https://github.com/getodk/collect/pull/5985/files#diff-43b24c9305ea5ed0083cda5127a295cf6aa95eaa440708a1f36edcdd01b704dbR46) is what we used when reading QR codes was initially implemented. Then we removed it because it turned out that there were some QR codes that couldn't be decoded because of that flag. Now we learned that there are also QR codes that can't be decoded if it's not present. Generally, that flag shouldn't be needed it doesn't even matter if I set it's value to true or false... it just needs to be there.
**To sum up there are codes that work only with that flag and also there are codes that work only if it's not present!**

If you wonder if it's because of how we generate QR codes the answer is no I've used an online tool for generating QR codes and the result was the same.

I would like to report that issue in https://github.com/journeyapps/zxing-android-embedded but the only QR code that reproduces this issue contains private data and I can't share it (I only have the one that files when DecodeHintType.`PURE_BARCODE` is present https://github.com/getodk/collect/blob/master/qr-code/src/test/assets/qrScreenshotFromCollect.png) ... maybe the QA team will be able to find one another.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please try to find another QR code that doesn't work on v2023.4.1. If you are not able to do that I will share the one I have in private as it contains private data.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt [hunk 1]
```diff
@@ -26,14 +27,26 @@ class QRCodeDecoderImpl : QRCodeDecoder {
...
+                    .decode(
+                        getBinaryBitmap(bitmap),
+                        mapOf(
+                            DecodeHintType.TRY_HARDER to TRUE,
+                            DecodeHintType.POSSIBLE_FORMATS to BarcodeFormat.QR_CODE
+                        )
                     )
-                )
+            } catch (e: NotFoundException) {
+                QRCodeMultiReader()
```
Comment (seadowg) [inline qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt:42]: It's probably worth adding a comment here describing what's going on.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt (hunk 1 above)
Comment (grzesiek2010) [reply qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt:42]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by lognaturel** [comment]
🤪

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:
- issue #5984 is no longer reproducing;
- Regression check on Scanning and importing QR codes;
- Exporting QR code from older version and scanning it on newer;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10
