### PR TITLE
Do not crash if the old cache folder can't be deleted

### LINKED ISSUE #4751: Unable to delete directory /storage/emulated/0/Android/data/org.odk.collect.android/files/.cache
#### Software and hardware versions 
Collect v2021.2.0

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4729455e1e3dfa242dfff05259fe1590?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=61019DC800ED00017E23CE5DBC231659_1568487182557973950

```
Caused by java.io.IOException: Unable to delete directory /storage/emulated/0/Android/data/org.odk.collect.android/files/.cache.
       at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1581)
       at org.odk.collect.android.application.initialization.ExistingProjectMigrator.run(ExistingProjectMigrator.java:59)
       at org.odk.collect.android.application.initialization.upgrade.AppUpgrader.upgrade(AppUpgrader.java:14)
       at org.odk.collect.android.application.initialization.ApplicationInitializer.performUpgradeIfNeeded(ApplicationInitializer.java:71)
       at org.odk.collect.android.application.initialization.ApplicationInitializer.initialize(ApplicationInitializer.java:62)
       at org.odk.collect.android.application.Collect.onCreate(Collect.java:127)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6321)
       at android.app.ActivityThread.access$1800(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4751

#### What has been done to verify that this works as intended?
I just reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
Catching exception should be a sufficient solution since it's not a big problem if we don't remove the old cache folder.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/application/initialization/ExistingProjectMigrator.kt [hunk 1]
```diff
@@ -56,7 +56,11 @@ class ExistingProjectMigrator(
             }
         }
 
-        FileUtils.deleteDirectory(File(rootDir, ".cache"))
+        try {
+            FileUtils.deleteDirectory(File(rootDir, ".cache"))
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/application/initialization/ExistingProjectMigrator.kt:60]: I think it would be good to have a test to ensure this remains in place. The test (which can go in `ExistingProjectMigrator`) could just delete the cache directory before running `run()` and just check that nothing explodes - just a "does not explode test" but still important.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/application/initialization/ExistingProjectMigrator.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/application/initialization/ExistingProjectMigrator.kt:60]: Ok I added a test but making it a normal file not dir because only then I can force it to throw the exception. If I delete a dir that does not exist everything is fine because `deleteDirectory`() is a utility method and it checks that case.

**Review by seadowg — APPROVED** [review]
