### PR TITLE
Fixed updating app bar color

### LINKED ISSUE #6374: App bar flashes when audio is being played/recorded and the user scrolls down
#### ODK Collect version
the master version 1bd1af19c70a8a01293f33e6e12268cd91a1b44c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The app bar flashes when audio is being played/recorded and the user scrolls down in the audio widget. 
It happens both in the portrait (if there are more question on the page) and the landscape view.

https://github.com/user-attachments/assets/7f1e47c3-4124-45da-8fde-2757f21c0bcc

#### Steps to reproduce the problem
1. Go to All question types form to Audio widget.
2. Record sound.
3. Rotate the device so it's in the landscape view.
4. Play the audio.
5. Scroll down.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6374

#### Why is this the best possible solution? Were any other approaches considered?
It turns out that the issue is not limited to recording audio in form entries, as we initially thought and as described in the issue. It's a broader problem that can affect any screen where a scrolling view is placed directly beneath the AppBarLayout. I've detailed this in my comment:

```
     When scrolling, the top app bar fills with a contrasting color to create a visual separation.
     This works automatically if your scrolling view (e.g., `RecyclerView`, `ListView`) is placed directly
     beneath the `AppBarLayout`. However, if the scrolling view is nested within another view
     (such as a `ConstraintLayout`, which is common in this app), you need to help the app bar determine
     whether it should lift by setting `app:liftOnScrollTargetViewId` to the ID of the scrolling view.
     Since this `AppBarLayout` is used throughout the app with various scrolling views, it’s best to
     use a shared ID like `scrollable_container`.
     If the scrollable view is added programmatically or it is displayed in a `ViewPager` with a
     shared id, it may not work as expected anyway, and `app:liftOnScrollTargetViewId` might
     need to be updated programmatically after adding such a view.
     The `ODKView` and its `odk_view_container` or `DeleteFormsActivity` are good examples of this scenario.
```

To summarize, in cases of more complex views, we need to explicitly specify which view the app bar should track for scrolling, which can be done in XML, but in some instances, it needs to be handled programmatically (e.g., ODKView, ViewPager). I attempted to rework the form entry layout to prevent the scrollable container from being added dynamically each time a new screen is displayed, which would eliminate the need to set the view programmatically. However, this approach proved challenging and would require some complex and potentially messy code changes, so I decided not to proceed.

I opted for a hybrid approach, setting the view ID in XML wherever possible and handling it programmatically only when the XML solution doesn't work. Although setting IDs programmatically could be done throughout, I prefer to avoid it whenever possible, as I don't like it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change requires testing how the app bar color changes during scrolling. Since each screen behaves differently, we need to test all occurrences of the app bar throughout the app.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/ObviousProgressBar.kt [hunk 1]
```diff
@@ -3,23 +3,30 @@ package org.odk.collect.androidshared.ui
...
 
 /**
  * A progress bar that shows for a minimum amount fo time so it's obvious to the user that
  * something has happened.
  */
-class ObviousProgressBar(context: Context, attrs: AttributeSet?) : ProgressBar(context, attrs) {
+class ObviousProgressBar(
+    context: Context,
+    attrs: AttributeSet?
+) : LinearProgressIndicator(context, attrs) {
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/ui/ObviousProgressBar.kt:15]: This looks a lot nicer! I think it needs to be set to be Indeterminate so it will animate properly. Right now it just shows as a blue bar.

File: androidshared/src/main/res/layout/app_bar_layout.xml [hunk 2]
```diff
@@ -1,4 +1,16 @@
 <?xml version="1.0" encoding="utf-8"?>
+<!--
+     When scrolling, the top app bar fills with a contrasting color to create a visual separation.
+     This works automatically if your scrolling view (e.g., `RecyclerView`, `ListView`) is placed directly
+     beneath the `AppBarLayout`. However, if the scrolling view is nested within another view
```
Comment (seadowg) [inline androidshared/src/main/res/layout/app_bar_layout.xml:5]: Is it "beneath" or is it if the two are children in the same `CoordinatorLayout`? It might be worth also linking to the docs here: https://developer.android.com/reference/com/google/android/material/appbar/AppBarLayout.

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt [hunk 3]
```diff
@@ -42,6 +44,8 @@ class DeleteBlankFormFragment(
             }
         )
     }
+    private var appBarLayout: AppBarLayout? = null
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: These fields should be removed, and the views should be accessed via `OfflineMapLayersPickerBinding.bind(requireView())` (or just `view` in `onViewCreated`) so we don't leak anything after `onDestroy`.

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt [hunk 4]
```diff
@@ -80,11 +85,17 @@ class DeleteBlankFormFragment(
...
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+        appBarLayout = requireActivity().findViewById(org.odk.collect.androidshared.R.id.appBarLayout)
         val blankFormListMenuProvider =
             BlankFormListMenuProvider(requireActivity(), blankFormListViewModel)
         menuHost.addMenuProvider(blankFormListMenuProvider, viewLifecycleOwner, State.RESUMED)
     }
 
+    override fun onResume() {
+        super.onResume()
+        appBarLayout?.setLiftOnScrollTargetView(list)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: Why does this call end up in `onResume` and not `onViewCreated`?

File: collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt [hunk 5]
```diff
@@ -46,6 +48,8 @@ class DeleteSavedFormFragment(
             }
         )
     }
+    private var appBarLayout: AppBarLayout? = null
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt]: Same thing here with the fields as for `DeleteBlankFormFragment`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: `onViewCreated` is called once but we need to update the view that appbar observes every time we switch between blank and saved forms (it is a viewpager) because we have two lists with the same id.

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: I can't do that as `appBarLayout` is not a part of the layout used in this fragment (the fragment is included using `viewpager`) and the same with the ist that should be watched. I also can't move this to `onViewCreated` because: https://github.com/getodk/collect/pull/6390#discussion_r1745281852

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/ObviousProgressBar.kt (hunk 1 above)
Comment (grzesiek2010) [reply androidshared/src/main/java/org/odk/collect/androidshared/ui/ObviousProgressBar.kt:15]: Right, fixed.

File: collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt]: https://github.com/getodk/collect/pull/6390#discussion_r1745303492

File: androidshared/src/main/res/layout/app_bar_layout.xml (hunk 2 above)
Comment (grzesiek2010) [reply androidshared/src/main/res/layout/app_bar_layout.xml:5]: > Is it "beneath" or is it if the two are children in the same CoordinatorLayout?

Both :smile: They are children in the same `CoordinatorLayout` and that layout works in the way that displayed the app bar above and the scrolling view beneath. If the scrolling view is there without any wrapper everything is fine out of the box.

> It might be worth also linking to the docs here: https://developer.android.com/reference/com/google/android/material/appbar/AppBarLayout

This document does not emphasize the importance of the aspect mentioned in the comment at all, so I believe it is useless.

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: The interaction between `ViewPager2` and `AppBarLayout` here are really annoying! It feels like this is probably something that's missing from the `MenuProvider` system right now. So to sum it up: we want to set the `RecyclerView` child of a fragment (which is in a child fragment) as the scroll target view for an `AppBarLayout` when the fragment is shown in the view page right? I think we can do that generally in the `onResume` of `MultiSelectListFragment`:


```kotlin
override fun onResume() {
    super.onResume()
    
    val list = MultiSelectListBinding.bind(requireView()).list
    val appBarLayout =
        requireActivity().findViewById<AppBarLayout>(org.odk.collect.androidshared.R.id.appBarLayout)
    appBarLayout?.setLiftOnScrollTargetView(list)
}
```

We could probably make this a bit more configurable by passing in an optional app bar layout id to `MultiSelectListFragment`'s constructor, but I think this sort of approach will work well with the "configuration over convention" choice to always have `appBarLayout` use the same id.

I think there's also ways we could go further to generalize it using lifecycle observers similarly to how `MenuHost` is implemented on `ComponentActivity`, but I think we can leave that to Google.

**Review by seadowg — DISMISSED** [review]
https://github.com/getodk/collect/pull/6390#discussion_r1751968601

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/DeleteBlankFormFragment.kt]: Done.

**Review by lognaturel — APPROVED** [review]
I've verified that the last change suggested by Callum has been addressed.

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14

**Verified cases**
- Issue #6374 does not occur
- Check on app bar across app
- Landscape and portrait view
- Light and dark mode

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
