### PR TITLE
Fix `./` expressions in entity filters

### LINKED ISSUE #6788: `./` causes crashes in entity list choice filters
A choice filter (or calculate) that uses an explicit relative path like `./my_property = 'hello'`  (instead of the equivalent but more common `my_property = 'hello'`) causes [a crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/3f1eed7d618a14389757f07ea02aad69?time=last-seven-days&types=crash&sessionEventKey=685AFA00026A000106CBF41B4130A8EA_2098257972300279335) when used on an entity list:

```java
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.javarosa.xpath.expr.XPathQName.name' on a null object reference in method 'org.odk.collect.shared.Query org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.xPathEqExprToQuery(org.javarosa.xpath.expr.XPathEqExpr, org.javarosa.core.model.instance.DataInstance, org.javarosa.core.model.condition.EvaluationContext)'
       at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.xPathEqExprToQuery(LocalEntitiesFilterStrategy.kt:94)
       at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.xPathExpressionToQuery(LocalEntitiesFilterStrategy.kt:62)
       at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.filter(LocalEntitiesFilterStrategy.kt:42)
       at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
       at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:377)
       at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:343)
       at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:250)
       at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:219)
       at org.javarosa.xpath.expr.XPathPathExprEval.eval(XPathPathExprEval.java:34)
       at org.javarosa.xpath.expr.XPathPathExpr.eval(XPathPathExpr.java:213)
       at org.javarosa.xpath.XPathConditional.evalNodeset(XPathConditional.java:94)
       at org.javarosa.core.model.ItemsetBinding.getChoices(ItemsetBinding.java:125)
       at org.javarosa.form.api.FormEntryPrompt.getSelectChoices(FormEntryPrompt.java:222)
       at org.javarosa.form.api.FormEntryPrompt.getAnswerValue(FormEntryPrompt.java:98)
       at org.odk.collect.android.formentry.audit.AuditUtils.logCurrentScreen(AuditUtils.kt:22)
       at org.odk.collect.android.formentry.FormEntryViewModel.updateIndex(FormEntryViewModel.java:365)
       at org.odk.collect.android.formentry.FormEntryViewModel.lambda$moveForward$3(FormEntryViewModel.java:224)
```

In this case, the "node side" of the expression is really `node()/my_property` (rather than `my_property`), so we can't assume that the node's child ref is the first step of the XPath path expression.

We typically don't write forms or test with `./`, but reproducing this should be easy by changing any existing entity follow-up form so that it uses `./<property> = ?` instead of `<property> = ?` (which should just behave the same).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6788

#### Why is this the best possible solution? Were any other approaches considered?

I've just made sure that `./` and `node()` expressions work correctly (and are optimized) when used with entity lists. We could have alternatively skipped optimization, but this seemed like it would have been an equivalent amount of effort.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue! Verifying should be fairly simple: any entity update or follow-up form that uses an expression like `<property> = <something>` can be changed to `./<property> = <something>` or `node()/<property> = <something>` as all of these should behave the same.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: entities/src/main/java/org/odk/collect/entities/javarosa/parse/XPathExpressionExt.kt [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+import org.javarosa.xpath.expr.XPathStep.AXIS_CHILD
+import org.javarosa.xpath.expr.XPathStep.AXIS_SELF
+import org.javarosa.xpath.expr.XPathStep.TEST_TYPE_NODE
+import org.odk.collect.shared.Query
+
+object XPathExpressionExt {
+
+    /**
+     * Converts an XPath expression to a [Query]. For example:
+     * - `label = 'blah'` will be converted to `Query.StringEq("label", "foo")`
```
Comment (grzesiek2010) [inline entities/src/main/java/org/odk/collect/entities/javarosa/parse/XPathExpressionExt.kt]: I think it should be `...Query.StringEq("label", "blah")`

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Androids: 10,14

**Verified cases:**
- issue #6788 doesn't occur
