### PR TITLE
Only auto send forms when auto send is enabled

### LINKED ISSUE #6112: Finalized forms are being auto sent while auto send setting is set to off
#### ODK Collect version
the master version d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5

#### Android version
11, 14

#### Device used
Samsung Galaxy M12, Pixel 7a

#### Problem description
Finalized forms are being auto sent while auto send setting is set to off

#### Steps to reproduce the problem
Preconditions:
Auto send setting is set to off

1. Open any form
2. Go to end
3. Press Finalize button
4. Go to sent forms

#### Expected behavior
Finalized forms should not be auto sent while auto send setting is set to off

### LINKED ISSUE #6113: After finalizing form and changing auto send setting forms that should be sent are being finalized
#### ODK Collect version
the master version d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5

#### Android version
10, 14

#### Device used
Samsung Galaxy M12, Pixel 7a

#### Problem description
After finalizing form and changing auto send setting, forms that should be sent are being finalized, additionally forms that are already in ready to send are not being auto sent.

#### Steps to reproduce the problem
Precondition:
Wifi is on

1. Go to settings > form management and set auto send to cellular only
2. Go to any form
3. Finalize form
4. Go to settings > form management and set auto send to wifi only or wifi or cellular 
5. Go to any form
6. Send form
7. Go to Ready to send view

#### Expected behavior
When wifi is on and auto send setting is set to wifi only or wifi and cellular form should be sent, when pressing send button at the end of page and forms from ready to send should be auto sent also.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6112
Closes #6113

This corrects the logic to check if auto send is enabled or not, and fixes how we schedule deferred work so we're able to change network constraints for an existing task.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

There's definitely a bunch of risk here again as it's hard to reason about and test all the different scenarios you can get into with background work. The only thing affected here is auto send though thankfully so other background tasks don't need to be verified.

#### Do we need any specific form for testing your changes? If so, please attach one.

The only thing to keep in mind is that forms can have auto send enabled/disabled themselves which massively complicates the workflows here.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt [hunk 1]
```diff
@@ -37,7 +37,7 @@ class CoroutineAndWorkManagerScheduler(foregroundContext: CoroutineContext, back
             .setInputData(workManagerInputData)
             .build()
 
-        workManager.beginUniqueWork(tag, ExistingWorkPolicy.APPEND_OR_REPLACE, workRequest).enqueue()
+        workManager.beginUniqueWork(tag, ExistingWorkPolicy.REPLACE, workRequest).enqueue()
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt:40]: From the `ExistingWorkPolicy.REPLACE docs`:

> If there is existing pending (uncompleted) work with the same unique name, cancel and delete it. Then, insert the newly-specified work.

This is the behaviour we want for auto send (currently the only thing that uses `networkDeferred`. We schedule auto send in two places:

1. When finalizing a form
2. When changing the auto send settings

For scenario 1, we could just use `KEEP` as we don't need to schedule another autosend task if one is already waiting to run (as the task submits all eligible forms). Scenario 2 requires `REPLACE` however as we might be changing the constraints of the task and so want to cancel the existing one.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt [hunk 2]
```diff
@@ -1,23 +1,32 @@
...
+        formsRepository: FormsRepository,
+        settingsProvider: SettingsProvider
     ): List<Instance> {
         val allFinalizedForms = instancesRepository.getAllByStatus(
             Instance.STATUS_COMPLETE,
             Instance.STATUS_SUBMISSION_FAILED
         )
 
+        val autoSendSetting =
+            settingsProvider.getUnprotectedSettings().getAutoSend(application)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:25]: We can probably flip how these enums work in the future so that the source of truth is in Kotlin/Java strings rather than in Android ones so we don't have to deal with `Context` in places like this. We'd just need to set the entry values for the UI preference programmatically instead. I think that's a change for another day however.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt [hunk 3]
```diff
@@ -1,23 +1,32 @@
...
+
         return allFinalizedForms.filter {
             formsRepository.getLatestByFormIdAndVersion(it.formId, it.formVersion)?.let { form ->
-                form.shouldFormBeSentAutomatically(true)
+                form.shouldFormBeSentAutomatically(autoSendSetting != AutoSend.OFF)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:29]: Is it ok that here we simply check if it's not off but in other places where `shouldFormBeSentAutomatically` is called we check the network state as well by calling `AutoSendSettingsProvider.isAutoSendEnabledInSettings`?
I guess it is because of https://github.com/getodk/collect/pull/6071/files#diff-ccbed5ebca33fb62147ab3c2b6c1d038bedcb5642afd683a911a94e8f01981f7R72 but just wanted to double-check.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt:29]: Yeah my goal was to move that check to `WorkManger`'s network constraints so we don't have to deal with the network provider in here (and we're not wasting battery running the job when the connection type is wrong).

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android: 11

**Verified cases:**

- Listed issues do not occur:
#6112 
#6113
- All auto send settings
- Regression check on auto send
- Forms with auto send set to true
- Auto send while connected to hotspot

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android: 13
