### PR TITLE
Blank space is visible after removing an image answer

### LINKED ISSUE #1824: Blank space is visible after removing an image answer
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Blank space is visible after removing an image answer.

#### Steps to reproduce the problem
blank_space

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1824 

#### What has been done to verify that this works as intended?
I tested attached form.

#### Why is this the best possible solution? Were any other approaches considered?
The fix is very small. Rest of changes are for sharing common code.

#### Are there any risks to merging this code? If so, what are they?
I refactored the code used by all Image widgets to share common code so we need to test all of those widgets.

#### Do we need any specific form for testing your changes? If so, please attach one.
[blankSpace.xml.txt](https://github.com/opendatakit/collect/files/1688806/blankSpace.xml.txt)

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@grzesiek2010 I noticed that selfie widget has `Choose Image` option which was not allowed before.

**Comment by grzesiek2010** [comment]
@mmarciniak90 
I fixed the problem.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.4, 5.1, 6.0, 7.0, 8.0.

Verified cases: 
* Checked blankSpace form
* Checked [photos.xml.txt](https://github.com/opendatakit/collect/files/1702869/photos.xml.txt) form
* Checked 'All widgets' form
* New and saved form
* 'Do not keep activities' turned on
* Selfie widget has only a 'Take Picture' button

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

File: collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java [hunk 1]
```diff
@@ -39,6 +41,15 @@ public BaseImageWidget(Context context, FormEntryPrompt prompt) {
...
     }
 
+    @Override
+    public IAnswerData getAnswer() {
+        if (binaryName != null) {
+            return new StringData(binaryName);
+        } else {
+            return null;
+        }
+    }
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java]: While you’re moving it, you might consider shrinking it:
`return binaryName == null ? null : new StringData(binaryName);`

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java [hunk 2]
```diff
@@ -103,6 +103,7 @@ protected void setUpLayout() {
         if (splits.length != 6) {
             Timber.w("Only have %d alignment values", splits.length);
         }
+        iarray = new int[6];
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: If you’re gonna set iarray to 6 zeroes here, you can shorten the code below to 
```
for (int i = 0; i < splits.length; ++i) {
    iarray[i] = Integer.parseInt(splits[i]);
}
```

File: collect_app/src/main/java/org/odk/collect/android/widgets/AbstractImageWidget.java [hunk 3]
```diff
@@ -17,10 +17,15 @@
...
 
 import android.content.Context;
+import android.support.annotation.Nullable;
+import android.widget.ImageView;
 
 import org.javarosa.form.api.FormEntryPrompt;
 
 public abstract class AbstractImageWidget extends QuestionWidget {
+    @Nullable
+    protected ImageView imageView;
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AbstractImageWidget.java]: It might simplify the history if you combined some of the similar refactoring commits into groups. (Fields, methods.) I don’t know if that’s hard to do.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java (hunk 2 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: The commit message says only “Fixed bug”. What bug does this fix? And were you able to exercise this code, it being part of AlignedImageWidget, which @lognaturel says requires an external application to run? Perhaps it’s best not to change this file.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
It must have been enjoyable deleting all that duplicated code!

File: collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java]: Fixed, thanks.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: When it comes to ODK Camera app I tested it and it works like on master branch I can open the app but then there is a crash after capturing an image, so there is something wrong with that app. I doubt someone uses that app.

As you can see in this commit https://github.com/opendatakit/collect/pull/1825/commits/5dedbeeca0d855e37a2e8def4ac311c99ffddb9d I just moved iarray field initialization. Why? because it caused a crash after my refactoring the value of that field was always null and to be honest I have no idea why default initialization was ignored.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: If we’re not reasonably certain the AlignedImageWidget is never used, then we need to continue to maintain and test it—or at least not change it. Would you agree? Can you share the details of the failure that led you to move the array initialization? If you do keep your change, then you really should make the change I suggested above, otherwise the change causes decay (the code **apparently** showing a naive unawareness that `new int[6]` initializes the array’s elements to 0 [to be clear, I’m not suggesting *you* are either naive or unaware]).

**Comment by dcbriccetti** [comment]
You probably already know this, but I found this helpful when I squashed (actually “fixed up”) some commits yesterday:
https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: You are right when it comes to that `for` loop we could improve that and I did it. I didn't see that because I just fixed the bug I run into. 
Here is the stcktrace:

> java.lang.NullPointerException: Attempt to write to null array
at org.odk.collect.android.widgets.AlignedImageWidget.setUpLayout(AlignedImageWidget.java:110)

that's is the riddle I was talking about on Slack: https://opendatakit.slack.com/archives/C35470318/p1518448269000563

As I sad the default initialization was ignored and it was always null :scream: 

>If we’re not reasonably certain the AlignedImageWidget is never used, then we need to continue to maintain and test it—or at least not change it. Would you agree?

Maybe you are right maybe we should not touch that widget at all since we can't test it well.

To sum: I fixed that small thing with a loop so we can merge it or if you really want I could also revert changes in that `AlignedImageWidget` at all.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: Can you point me to a point in time in your branch where I can experience the NPE? I’m inclined to get to the bottom of it.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: Just revert the change I made in this commit and open mentioned `AlignedImageWidget`.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: Or you can get back to https://github.com/opendatakit/collect/pull/1825/commits/26f6c5751b4be24ba46281f0bdf8197a57860b2d

**Comment by grzesiek2010** [comment]
I'm adding @opendatakit-bot label "behavior verified" again since removing it was a mistake.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java (hunk 2 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: The problem was (or is) that AlignedImageWidget calls super which calls back into AlignedImageWidget’s setUpLayout, which uses a field, iarray, before AlignedImageWidget itself is initialized. 

It might be good to get some other opinions on how best to avoid this. I’m inclined to think that you should avoid manipulating fields before the object is initialized. I can’t recall if and how I’ve dealt with this in the past.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
Even though it is worked around, I think we should be confident we are dealing correctly with object initialization and order of calls (super, setUpLayout).

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java (hunk 2 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: Says @ggalmazor:

To solve that I'd separate clearly the construction of the object from its initialization for the UI. During construction, all those fields should receive their value, and the fields should be final wherever it's possible. Then, after creating the instance, we could call `initUI()` or something like that, which would use that field safely

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: initUi should be initUi, says I.

**Comment by grzesiek2010** [comment]
@dcbriccetti 
I fixed the hierarchy. Now we don't need that change with initialization. Please take a look.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AbstractImageWidget.java (hunk 3 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AbstractImageWidget.java]: Agreed! Getting to the most useful level of granularity is certainly an art. In this case I think it would be nice to have all commits up to 1b61ef4 squashed into one with a message like "Pull duplicated code to abstract base class". @grzesiek2010 you can do that with `rebase -i` and a series of squashes. There are some later commits that should also be included in that one. You can move them up and squash them with `rebase -i` as well.

If this were a smaller change I would squash the whole thing on merge but I think it will be helpful for the future to separate out the refactor from the fix.

**Review by lognaturel — CHANGES_REQUESTED** [review]
@grzesiek2010 this looks good to me. Please get this down to ~3 commits so we have useful history for the future: pulling to base class, fixing the bug and reworking `selfie`.

Thanks for the thorough review, @dcbriccetti, hopefully things are looking good to you as well.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java [hunk 4]
```diff
@@ -67,10 +67,13 @@
 
     private String instanceFolder;
     
-    private int[] iarray;
+    private int[] iarray = new int[6];
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java]: I see benefit in making this `final`

File: collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java [hunk 5]
```diff
@@ -99,32 +90,28 @@ public void onClick(View v) {
...
             chooseButton.setVisibility(View.GONE);
             annotateButton.setVisibility(View.GONE);
         }
         errorTextView.setVisibility(View.GONE);
+    }
 
-        // retrieve answer from data model and update ui
-        binaryName = prompt.getAnswerText();
-
+    @Override
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: I’m working on an idea that won’t require you to override `setUpBinary` here. Overriding it duplicates code and complicates maintenance.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: I recommend you cherry pick this commit into your branch and see what you think of it.
https://github.com/dcbriccetti/collect/commit/28dce19a69401f917fe268bc6e911a4b165dc6b0

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: After this is addressed, I will like the code, and suggest it be retested by QA.

**Comment by grzesiek2010** [comment]
@lognaturel @daveycrockett it's ready.

**Review by dcbriccetti — APPROVED** [review]
I’ve carefully reviewed the code changes, and tested all the widgets in the provided form, and I’m happy with the change. I don’t know whether it should be tested again by QA.

**Comment by dcbriccetti** [comment]
(I’m not the king of the wild frontier. That’s another Dave.)

**Review by lognaturel — APPROVED** [review]
