### PR TITLE
Prevent opening for review encrypted forms after finalizing

### LINKED ISSUE #5642: Viewing encrypted submissions via snackbar
#### ODK Collect version
the beta version 2023.2 Beta 3
#### Android version
10
#### Device used
Redmi 9T
#### Problem description
After sending a submission in an encrypted project it is possible to "view” the sent form via snackbar. The user is moved to the view of a sent form with "Nothing available to display”. It’s seems ok since the submission was encrypted but on the other hand allowing the user to view something that isn’t available seems unnecessary so I’m not sure if it’s expected or not.
encryptedsubmissionview

#### Steps to reproduce the problem
1. Add and encrypted project to Collect.
2. Go to any form and send a submission.
3. When moved to the main menu, in the snackbar click "View”.

#### Expected behaviour

The "View" button should not appear for encrypted submissions.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5642 

#### What has been done to verify that this works as intended?
I've tested the changes manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
The only thing of note is how I determine if an instance is encrypted. I've decided to use the easiest solution and check the `CAN_EDIT_WHEN_COMPLETE` column from the `instances.db`. It turns out that the only way of having `false` in that column is when a form is encrypted. This column probably should be renamed to reflect its real purpose but that's something for the future, I don't want to introduce database upgrades now because it would be risky. 
Another option would be to check the `BASE64_RSA_PUBLIC_KEY` from the `forms.db` (if it's not null) but that would be more complex since I would need to browse the forms db instead of just checking the instance that is already available.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The case described in the issue was not the only way of opening an encrypted form. There were two more:
- opening the list of forms to send and clicking on a form
- using an external app (like the collect tester) and opening an encrypted form via that app

Please reproduce those two cases too and make sure they are handled properly.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java [hunk 1]
```diff
@@ -37,6 +37,23 @@ public class EncryptedFormTest {
     public RuleChain copyFormChain = TestRuleChain.chain(testDependencies)
             .around(rule);
 
+    @Test
+    public void instanceOfEncryptedForm_cantBeViewedAfterFinalizing() {
+        rule.startAtMainMenu()
+                .copyForm("encrypted.xml")
+                .setServer(testDependencies.server.getURL())
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java]: I don't think test needs the `setServer`

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt [hunk 2]
```diff
@@ -329,12 +329,16 @@ class MainMenuActivity : LocalizedActivity() {
...
         val formSavedSnackbarDetails = mainMenuViewModel.getFormSavedSnackbarDetails(uri)
 
-        formSavedSnackbarDetails?.let { it ->
+        formSavedSnackbarDetails?.let {
             SnackbarUtils.showLongSnackbar(
                 binding.root,
                 getString(it.first),
-                action = SnackbarUtils.Action(getString(it.second)) {
-                    formLauncher.launch(FormFillingIntentFactory.editInstanceIntent(this, uri))
+                action = if (it.second == null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt]: This change doesn't have a test. Would probably be good to add one in `MainMenuActivityTest`.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt [hunk 3]
```diff
@@ -329,12 +329,16 @@ class MainMenuActivity : LocalizedActivity() {
...
+                    null
+                } else {
+                    SnackbarUtils.Action(getString(it.second!!)) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt]: You could avoid the `!!` with a `let` or `apply` here.

**Review by seadowg — DISMISSED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java]: Right, fixed.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt]: Fixed.

**Comment by lognaturel** [comment]
> check the CAN_EDIT_WHEN_COMPLETE column from the instances.db

This seems like the right call to me and in fact I'm not bothered by the name, really. Maybe we could rename the constant to `CAN_OPEN_WHEN_FINALIZED` (without changing the db column name) to better reflect the terminology we use today. The finalization concept must have been called completion at some point (predates me) but it's not entirely accurate (a form can be complete but not yet finalized) so it must have been changed in the UI at some point but not in the code. It's "can edit" because it didn't used to be possible to view sent forms and finalized forms were editable. So there's definitely some legacy to the name but the fact that it's more general than "is encrypted" seems ok.

**Review by lognaturel — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

Verified cases:
- issue #5642 is no longer reproducing
- trying to view a finalized encrypted form in Ready to Send
- trying to view a sent encrypted form in Sent
- saved, finalized, sent encrypted forms in Collect Intents Tester app
- moving backwards enabled and disabled

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13
