### PR TITLE
Cannot choose an image from GD on Samsung Galaxy S4

### LINKED ISSUE #2151: Cannot choose an image from GD on Samsung Galaxy S4
#### Software and hardware versions 
Collect v1.14.1 and older versions

#### Problem description
Cannot choose an image from GD on Samsung Galaxy S4 Android 5. What interesting the problem doesn't occur on other devices even with the same Android version. 

#### Steps to reproduce the problem
1. Open a form with ImageWidget
2. Choose an image from GD

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2151 

#### What has been done to verify that this works as intended?
I've tested Image widgets with GD using the mentioned device.

#### Why is this the best possible solution? Were any other approaches considered?
Don't know why but the in most case `uri.getAuthority()` returns 
`com.google.android.apps.docs.storage
`but for the mentioned device it's
`com.google.android.apps.docs.storage.legacy
`
#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with `ImageWidget`

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

No.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java [hunk 1]
```diff
@@ -617,9 +617,8 @@ public static boolean isGooglePhotosUri(Uri uri) {
      * @param uri The Uri to check
      * @return Whether the Uri authority is Google Drive.
      */
-    public static boolean isGoogleDriveDocument(Uri uri) {
-        return "com.google.android.apps.docs.storage".equals(uri.getAuthority())
-                || uri.getAuthority().startsWith("com.google.android.apps.photos.content");
+    private static boolean isGoogleDriveDocument(Uri uri) {
+        return uri.getAuthority().startsWith("com.google.android.apps.");
```
Comment (yanokwa) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: It sounds like the safest fix here would be to check for `com.google.android.apps.docs.storage` AND `com.google.android.apps.photos.content`. Why did you drop the photos URI?

**Review by yanokwa — CHANGES_REQUESTED** [review]
I'd prefer a narrower fix or an explanation of why it's safe to drop the `com.google.android.apps.photos.content`. Maybe git blame might provide insights into why that URI was added to begin with.

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: I know GD uri might contain:
`com.google.android.apps.docs.storage`
`com.google.android.apps.docs.storage.legacy`
`com.google.android.apps.photos.content`

all of them starts with `com.google.android.apps.` so I think it's ok to use it, maybe there is another case we don't know like this issue.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: if it starts with `com.google.android.apps.` it must be a GD uri no matter what is after that las dot.

Comment (yanokwa) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: I'd rather be conservative and do a whitelist. That is, there might also be `com.google.android.apps.bad.stuff` with unknown behavior.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: so maybe 
`return uri.getAuthority().startsWith("com.google.android.apps.docs.storage") || uri.getAuthority().startsWith("com.google.android.apps.photos.content");` ?

Comment (yanokwa) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: Yeah, that would be ideal.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java]: Ok, it's done.

**Review by yanokwa — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success.**

Verified on Android: 5.1, 6.0, 7.0, 8.0. 
Older Android versions do not have this feature.

Verified cases:
* tested photo types: jpg, jpeg, png, gif
* tested widgets: image, annotate, web view image, align image.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot  label "behavior verified"
