### PR TITLE
Fix for #5634 Crash after zooming map

### LINKED ISSUE #5634: Crash of the app after zooming to points in a map-internal-select form with Google maps
#### ODK Collect version
2023.1.1, the store version 2023.1.2, the master version 3f5ab8e84d64a27bb60ecf6cf3672b8548a07d8b
#### Android version
8.1, 10, 13
#### Device used
Nexus 5X, Redmi 9T, Galaxy A23
#### Problem description
When Google maps is set as a source of map zooming to all points crashes the app in map-internal select form.
In other version of the form without added traces the issue doesn’t occur. Form not causing the crash 
[map-internal-select(2).xlsx.txt](https://github.com/getodk/collect/files/11758991/map-internal-select.2.xlsx.txt)

#### Steps to reproduce the problem
1. Go to map-internal-select form.
[map-internal-select(1).xlsx.txt](https://github.com/getodk/collect/files/11758924/map-internal-select.1.xlsx.txt)
2. Tap "Select place”.
3. Tap on the button to zoom to all points.
#### Expected behavior
The app shouldn’t crash.
#### Other information
The issue doesn’t occur in Select on from map in the demo project or random select one map froms with geojson, csv, xml attachments.

### PR DESCRIPTION
**Pull request by dimwight**
Fixes #5634

#### What has been done to verify that this works as intended?
Tested manually using issue form.

#### Why is this the best possible solution? Were any other approaches considered?
The issue seems analogous (even identical) to #5379, with Google's `CameraUpdate` again choking on `LatLng` data. Rather than simply updating to handle the `IllegalStateException` thrown by this issue, I've generalised to `RuntimeException`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Behaviour is now as in #5393.  No impact on tests.

#### Do we need any specific form for testing your changes? If so, please attach one.
Form provided in #5634.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java [hunk 1]
```diff
@@ -263,7 +263,9 @@ public void onSaveInstanceState(@NonNull Bundle outState) {
                 new Handler().postDelayed(() -> {
                     try {
                         moveOrAnimateCamera(CameraUpdateFactory.newLatLngBounds(bounds, 0), animate);
-                    } catch (IllegalArgumentException e) { // https://github.com/getodk/collect/issues/5379
+                        // https://github.com/getodk/collect/issues/5379
+                        // https://github.com/getodk/collect/issues/5634
+                    } catch (RuntimeException e) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java]: I think I'd prefer to go with a more specific `IllegalStateException` catch here (as you suggest as an alternative in the PR description). `RuntimeException` is very broad, and might catch an unrecoverable exception that we'd actually rather have crash the app.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java (hunk 1 above)
Comment (dimwight) [reply collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java]: Well yes, better safe than sorry.

**Comment by grzesiek2010** [comment]
Shouldn't we fix zooming so that it works well for points/traces/shapes instead of catching the exception? It could be a good short-term solution to avoid crashes if we wanted to have a release soon but otherwise it's not a proper solution to me. @seadowg what do you think?

**Comment by seadowg** [comment]
@grzesiek2010 great point! I think avoiding the crash is a good step forward, but agree that we probably want to add another issue for improving the zoom behaviour. That's probably a good thing to look at after @getodk/testers have had a play with this.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10

**Verified cases:**
- issue #5634 is no longer reproducible
- different sources of maps

**Comment by srujner** [comment]
Tested with Success!

Verified on Androids: 13

**Comment by dimwight** [comment]
> Tested with Success!

Thanks guys 😀
