### PR TITLE
FIx #2159 The user is not able to add audio and video from Google Drive.

### LINKED ISSUE #2159: The user is not able to add audio and video from Google Drive
#### Software and hardware versions 
Collect master
Android 5.1, 6.0, 7.0, 8.0

#### Problem description
The user is not able to add audio and video from Google Drive

#### Steps to reproduce the problem
1. The user tries to add an audio file from Google Drive
2. The user tries to add video file from Google Drive
3. The user sees message and file is not attached

| | |
|---|---|
|screenshot_20180427-101524|screenshot_20180427-101752|

#### Expected behavior
1. User is able to add audio and video file from Google Drive

### PR DESCRIPTION
**Pull request by ShenJack**
FIx #2159 The user is not able to add audio and video from Google Drive.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -775,6 +790,60 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
...
+     * and if it's from Google Drive and not cached yet, we'll retrieve it using network.
+     * This may take a long time.
+     *
+     * @param selectedFile uri of the selected audio
+     * @see #getFileExtensionFromUri(Uri)
+     */
+    private void saveChosenAudioVideo(Uri selectedFile) {
+        String extension = getFileExtensionFromUri(selectedFile);
+
+        String instanceFolder1 = Collect.getInstance().getFormController()
```
Comment (jd-alexander) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Is there a special reson why this variable is called `instanceFolder1` instead of just `instanceFolder`? I see that `instanceFolder` is being used as a local variable in another function but that shouldn't affect this one, so it would be good if the 1 is removed because as soon as I saw it I started looking for `instanceFolder2` :smile:

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 2]
```diff
@@ -811,6 +880,31 @@ private void saveChosenImage(Uri selectedImage) {
...
+     * Using contentResolver to get a file's extension by the uri returned from OnActivityResult.
+     *
+     * @param fileUri Whose name we want to get
+     * @return The file's extension
+     * @see #onActivityResult(int, int, Intent)
+     * @see #saveChosenAudioVideo(Uri)
+     * @see android.content.ContentResolver
+     */
+    private String getFileExtensionFromUri(Uri fileUri) {
+        Cursor returnCursor =
```
Comment (jd-alexander) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: It would probably be alot cleaner to wrap the usage of this `Cursor` using [try with resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) so that you don't have to manually close the `Cursor`

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 3]
```diff
@@ -811,6 +880,31 @@ private void saveChosenImage(Uri selectedImage) {
...
+                getContentResolver().query(fileUri, null, null, null, null);
+        int nameIndex = returnCursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
+        returnCursor.moveToFirst();
+        String filename = returnCursor.getString(nameIndex);
+        returnCursor.close();
+        if (filename.lastIndexOf('.') != -1) {
+            return filename.substring(filename.lastIndexOf('.'));
+        } else {
+            return "";
```
Comment (jd-alexander) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Can you expound a bit on what's happening right here where a substring version is being returned in one case and in the other an empty string.

**Review by jd-alexander — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 2 above)
Comment (ShenJack) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Thank you and it sounds great! actually I rarely use this feature before, but I'll add it. this works wonderful.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 1 above)
Comment (ShenJack) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Oops, I'll change it right away.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 3 above)
Comment (ShenJack) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Thank you for your reminder above,  well  I found some Mp3 files' name don't contain extension, but can be played as audio, so I write so, but I still believe there are some way to get its extension.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java [hunk 4]
```diff
@@ -134,23 +134,45 @@ public IAnswerData getAnswer() {
...
+     * @param object Uri or File of the chosen file.
+     * @see org.odk.collect.android.activities.FormEntryActivity#onActivityResult(int, int, Intent)
+     */
     @Override
-    public void setBinaryData(Object binaryuri) {
-        if (binaryuri == null || !(binaryuri instanceof Uri)) {
-            Timber.w("AudioWidget's setBinaryData must receive a Uri object.");
+    public void setBinaryData(Object object) {
+        File newAudio;
+        // get the file path and create a copy in the instance folder
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java:150]: This comment is sufficient -- the ones below are very similar to the code and don't add additional info!

File: collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java [hunk 5]
```diff
@@ -219,23 +219,47 @@ public IAnswerData getAnswer() {
...
+     * @param object Uri or File of the chosen file.
+     * @see org.odk.collect.android.activities.FormEntryActivity#onActivityResult(int, int, Intent)
+     */
     @Override
-    public void setBinaryData(Object binaryuri) {
-        if (binaryuri == null || !(binaryuri instanceof Uri)) {
-            Timber.w("AudioWidget's setBinaryData must receive a Uri object.");
+    public void setBinaryData(Object object) {
+        File newVideo = null;
+        // get the file path and create a copy in the instance folder
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java:235]: Same comment as above -- this comment is enough and the ones below can be removed.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 6]
```diff
@@ -734,9 +735,23 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
...
             case RequestCodes.AUDIO_CHOOSER:
+                // Same with VIDEO_CHOOSER.
             case RequestCodes.VIDEO_CHOOSER:
-                saveFileAnswer(intent.getData());
+                /*
+                * Start a task to save the chosen video with a new Thread,
+                * This could support retrieving file from Google Drive.
+                * */
+                showDialog(SAVING_DIALOG);
+                Runnable saveVideoRunnable = new Runnable() {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: What about naming this `saveMediaRunnable` so it's a little more general?

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 7]
```diff
@@ -775,6 +790,60 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
...
+    /**
+     * Save a copy of the chosen audio/video in Collect's own path such as
+     * "/storage/emulated/0/odk/instances/{form name}/filename",
+     * and if it's from Google Drive and not cached yet, we'll retrieve it using network.
+     * This may take a long time.
+     *
+     * @param selectedFile uri of the selected audio
+     * @see #getFileExtensionFromUri(Uri)
+     */
+    private void saveChosenAudioVideo(Uri selectedFile) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Similar to the comment above, how about calling this `saveChosenMedia`?

**Review by lognaturel — COMMENTED** [review]
Just a couple of stylistic suggestions, @ShenJack.

Up to you if you want to handle generic files in this PR or start another one.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 5.1, 6.0, 7.0, 8.1
Audio and Video widgets load files from Google Drive

Problem is still visible on `File widget` but I created a separate issue to fix this - #2258

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by ShenJack** [comment]
@mmarciniak90  Thanks a lot for testing my changes, I'll go on to fix the issue of File Widget.
