### PR TITLE
Make instance subtext translatable

### LINKED ISSUE #1419: Filled form/instance details are not localized
#### Software and hardware versions 
All versions

#### Problem description
Date/time and status strings used as filled form status are saved as full strings in the database so they're localized when generated.

#### Steps to reproduce the problem
Fill a form in one language. Change the language. Look at the instance details and see that the status and date/time string are in the initial language.

#### Expected behavior
Filled form date/time status string is localized to interface language.

#### Other information 
We will need to discuss how to approach this. First thing might be to try to understand why the information was saved as a string in the first place. Can that information be disaggregated into two fields (status and date/time)? Given that these strings currently exist in users' instance databases in whatever language, what would the migration path to the new schema be? Is it the case that the status is hardcoded to English? If so, that may make things easier. Another alternative might be to keep the existing column and use it if it's populated or use the two new columns if it's not.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1419 

#### What has been done to verify that this works as intended?
- tested installing apk with database v5 on v4 and v4 on v5
- tested the content of instance subtext

#### Why is this the best possible solution? Were any other approaches considered?
I decided to remove `displaySubtext` column which keeps an untranslatable instance subtext and use `date` column to create such subtext dynamically (to make it translatable). `date` column stores last update dates so it's the same value as in `displaySubtext`. There is no need to use the `displaySubtext` column.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I upgraded the instances database version so it's a thing that should be carefully tested, upgrading/downgrading @mmarciniak90 I'm counting on your creativity here like in #3193.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java [hunk 1]
```diff
@@ -196,10 +196,10 @@ public void syncComplete(@NonNull String result) {
 
     private void setupAdapter() {
         String[] data = new String[]{
-                InstanceColumns.DISPLAY_NAME, InstanceColumns.DISPLAY_SUBTEXT, InstanceColumns.DELETED_DATE
+                InstanceColumns.DISPLAY_NAME, InstanceColumns.DELETED_DATE
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java:199]: Maybe the subtext was saved in the DB so that it could be passed into the adapter this way? I know it doesn't particularly matter and maybe it was just an accident but I keep wondering why in the world the string was stored in the DB if there was also a coded representation of the state this whole time!

File: collect_app/src/main/java/org/odk/collect/android/provider/InstanceProviderAPI.java [hunk 2]
```diff
@@ -19,9 +19,6 @@
 import android.net.Uri;
 import android.provider.BaseColumns;
 
-/**
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/provider/InstanceProviderAPI.java:22]: Thank you.

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java:199]: Maybe... maybe the author didn't know it's possible to handle dates and create an appropriate subtext in the adapter.

**Comment by mmarciniak90** [comment]
**Tested with success**

**Verified on Android**: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

**Verified cases:**
* `Edit Saved Form` view
* `Send Finalized Form` view
* `View Send Form` view 
* `Delete Saved Form -> Saved Forms` view
* statuses: finalized, saved,send, deleted, failed
* upgrade from v1.22.2, v1.23-beta.

Downgrade the application is not possible.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
