### PR TITLE
Issue#1976 There are no separator lines in SelectOneSearchWidget

### LINKED ISSUE #1976: There are no separator lines in SelectOneSearchWidget
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
There are no separator lines in `SelectOneSearchWidget`

#### Steps to reproduce the problem
screenshot_2018-03-06-14-55-04
screenshot_2018-03-06-14-55-14

#### Expected behavior
I'm not sure whether we should add those lines in `SelectOneSearchWidget` or maybe remove them at all (from other widgets) but the layout in both cases should be consistent.

@lognaturel which approach do you prefer?

@opendatakit-bot label "quick win"
@opendatakit-bot label "needs discussion"

### PR DESCRIPTION
**Pull request by akashdobaria**
Closes #1976 

#### What has been done to verify that this works as intended?
The widget has been opened on different screen sizes(4, 4.5, 5, 5.5 and 9 inch) and different versions of Android (APIs: 22,23,24,25,26). The search for specific item and selection works fine.

#### Why is this the best possible solution? Were any other approaches considered?
I haven't gone through all widgets if other widgets have the same problem. This is the best solution for this issue because it doesn't have to deal with other classes/objects. It fetches default line separator and applies to the LinearLayout.

#### Are there any risks to merging this code? If so, what are they?
I don't think there is any risk of merging this update.

#### Do we need any specific form for testing your changes? If so, please attach one.
N/A

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java [hunk 1]
```diff
@@ -34,8 +36,10 @@
  */
 @SuppressLint("ViewConstructor")
 public class SelectOneSearchWidget extends AbstractSelectOneWidget implements OnCheckedChangeListener, AudioPlayListener {
+    Context mContext;
```
Comment (jd-alexander) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java]: Hey @akashdobaria you don't have to go through the hassle of creating a field to store the `Context` because the underlying base class of this widget which is a `RelativeLayout` gets it via it's constructor. That's the reason for the call to  `super(context,prompt,false); `. 
So all you have to do is call `getContext()` and you are good to go :smile:

Comment (akashdobaria) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java]: Hi @jd-alexander ,
Thank you for your review. I'll make the changes and push it. :)

Comment (jd-alexander) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java]: Awesome :sunglasses:

**Comment by jd-alexander** [comment]
Thanks for your contribution! 
Just a note, your commit messages can be made a bit more meaningful so you can easily track the changes you made. eg. that last commit you made could be something like "removed context and used getContext of RelativeLayout" or something like that.

**Comment by akashdobaria** [comment]
Hi @jd-alexander ,
I am sorry. I am contributing for the first time and I keep getting nervous about my first contribution. Thank you for your suggestion. I really appreciate it. 😃

**Comment by lognaturel** [comment]
No need to apologize, @akashdobaria, we're all here to help each other and ODK users get the best tools possible!

@jd-alexander is right that this change could be squashed into one and given a descriptive commit message. Bonus points if it explains **why** the change was made, not just what it is. Here's a great article on writing good commit messages: https://medium.com/square-corner-blog/how-square-writes-commit-messages-8e92fcbf77c9

Here's my favorite article on reworking history to make it nicer: https://dev.bleacherreport.com/small-commits-for-fun-and-profit-part-2-git-commit-amend-and-git-rebase-interactive-e986d4a64c21. You can use `git rebase -i` to squash all commits into one and then rename the resulting one with `--amend`. Finally you'll `push --force` to rework the history here (that's ok to do because it's not master).

These are great things to learn BUT since the goal is to squash to one commit, this is also something a committer can do on merge through Github. So up to you @akashdobaria if you want to try it out or keep it for next time!

**Comment by akashdobaria** [comment]
Hi @lognaturel ,
Thank you so much for the tips and articles. I would like to try these things on my repositories first so that I can make sure I really understand how this works and don't make any mistakes. I would give it a try next time for sure. :)

File: collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java [hunk 2]
```diff
@@ -65,7 +74,6 @@ protected void createLayout() {
                 buttons.add(createRadioButton(i));
             }
         }
-
```
Comment (huangyz0918) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java]: I think you should not make changes in blank lines, it’s a unrelated change. A good choice is to fix these unrelated changes and ci errors in a single commit ( you can squash them into one commit like @lognaturel said using `git rebase -i` )
Good luck

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by grzesiek2010** [comment]
@akashdobaria thanks, it looks good to me.

**Comment by kkrawczyk123** [comment]
### Tested with success!
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you and welcome, @akashdobaria!
