### PR TITLE
Project delete does not fully clear state

### LINKED ISSUE #4710: Project delete does not fully clear state
- If the last project is deleted, the meta setting for current project id is still set. The implication is that getting the current project results in a different exception which is not the end of the world. I ran into this working on #4707 but I don't really know how important it is.

- There seems to be some settings retained. I don't yet have exact repro steps but I did something like create a demo project from the special link from the first launch screen, reconfigure that project, delete that project, then manually add the demo project URL and ended up with the reconfigured settings.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4710 

#### What has been done to verify that this works as intended?
I tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I added clearing settings for the project that we remove in `ProjectDeleter` which is responsible for deleting. This is the best place and I can't think of any better solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a pretty safe and isolated change so we just need to verify that the bug does not exist and that's it.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
I'm wondering if a simpler implementation (which would also need less testing) would be to just have the `ProjectDeleter` clear the general and admin settings for the project directly. That way we only need to make changes to `ProjectDeleter`. It could also be tested pretty easily using the `InMemSettingsProvider` - the general and admin could be set up with any keys (`foo`, `bar` etc) and then checked to see that they are gone after project deletion.

I guess that would leave references to old settings objects around in `SharedPreferencesSettingsProvider` but they're just in-mem and I don't think would cause any problems?

What do you think?

**Review by lognaturel — DISMISSED** [review]
Great! I think the most compelling reason to do this ends up being not to leave user credentials lying around.

**Comment by lognaturel** [comment]
Sigh, hadn't noticed @seadowg's change request. Simpler and more easily testable is certainly nice. I agree it wouldn't be an issue to temporarily leave settings in memory. But I don't feel strongly about making the change.

**Comment by grzesiek2010** [comment]
> What do you think?

Yeah it makes the fix a bit smaller so here you go.

File: collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt [hunk 1]
```diff
@@ -22,6 +28,7 @@ import org.odk.collect.shared.TempFiles
 import org.odk.collect.testshared.BooleanChangeLock
 import java.io.File
 
+@RunWith(AndroidJUnit4::class)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt]: I don't think you need the Android test runner here right?

**Review by seadowg — APPROVED** [review]
Looks great! One comment about a line I don't think we need, but nothing blocking this getting merged for me.
