### PR TITLE
Fixed using the quick appearance in SelectOneFromMapWidget

### LINKED ISSUE #5540: Unable to reopen a map in select one from map with appearance quick
#### ODK Collect version
2022.4.4, 2023.1.2 ,the master version db8f7ec7342fa558fe43424909b5fb40fd0d5bc1
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
The user is unable to reopen the map when there was a point/trace selected and appearance quick is applied in the question. When the quick appearance is added to select one from map question, the form doesn’t advance immediately to the next question once a selection is made.
#### Steps to reproduce the problem
1. Go to Select fieldlist quick form.
[Select fieldlist quick.xlsx.txt](https://github.com/getodk/collect/files/11159267/Select.fieldlist.quick.xlsx.txt)
2. Go to questions with Map widget select one from geojson attachment.
3. Tap "Select place”.
4. Select a point on the map.
5. Try to reopen the map by tapping "Select place”.
#### Expected behavior

Select one from map with `quick` should skip the summary sheet when the user clicks on a point, and then skip to the next question (like other select widgets). If the user navigates back to a select one from map question, they should be able to change their selection by clicking "Select place" and then a point.

#### Other information 
I also created and checked appearance quick in a select one form map form with csv attachment and points and traces included in xlsx file. In all cases the map doesn't reopen.
[selectonefrommapwithgeojsoncsvquick.xlsx.txt](https://github.com/getodk/collect/files/11159255/selectonefrommapwithgeojsoncsvquick.xlsx.txt)
[pointandtraces.csv](https://github.com/getodk/collect/files/11159257/pointandtraces.csv)
[pointsandtraces.geojson.txt](https://github.com/getodk/collect/files/11159262/pointsandtraces.geojson.txt)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5540

#### Why is this the best possible solution? Were any other approaches considered?
We have one method `onFeatureClicked` (renamed to `onFeatureSelected`) to handle both cases - selecting items by a user and selecting items (automatically) after opening a map where there is already a selected item. Because of that, we weren't able to distinguish those two cases without introducing a new parameter `selectedByUser`. Only if the action is performed by a user we should close the map (if the `quick` appearance is used).
When it comes to the second part of the issue - navigating automatically to the next question it works in a similar way to normal selects. There is a listener and when there is a new answer we call the listener.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The changes can only affect the SelectOneFromMap widget so we can focus on testing it. Please make sure the issue is fixed and there is everything fine with that widget.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt [hunk 1]
```diff
@@ -804,6 +804,75 @@ class SelectionMapFragmentTest {
         scenario.moveToState(Lifecycle.State.DESTROYED)
     }
 
+    @Test // https://github.com/getodk/collect/issues/5540
```
Comment (seadowg) [inline geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt]: I don't think we need to link the Github issue in either of these tests. The behaviour makes a lot of sense without the extra context.

File: collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidget.kt [hunk 2]
```diff
@@ -22,10 +23,18 @@ import org.odk.collect.androidshared.ui.DialogFragmentUtils
...
 @SuppressLint("ViewConstructor")
-class SelectOneFromMapWidget(context: Context, questionDetails: QuestionDetails) :
-    QuestionWidget(context, questionDetails), WidgetDataReceiver {
+class SelectOneFromMapWidget(
+    context: Context,
+    questionDetails: QuestionDetails,
+    private val autoAdvance: Boolean
+) : QuestionWidget(context, questionDetails), WidgetDataReceiver {
+
+    lateinit var autoAdvanceListener: AdvanceToNextListener
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidget.kt]: Could we just pass in or set the `autoAdvanceListener` rather than piggybacking it on `context`? I know other widgets use this trick, but I think I'd prefer if this worked more like the widget change listener so there's only one way (and an explicit) way of setting it.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidget.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidget.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
What is the expected result after changes in the PR? When I go Select one form map question with quick appearance, I open the map and tap a point/trace/shape the map is closed and I'm moved to the next question. It feels like the step in which the user confirms the choice by tapping "Select" in the bottom sheet (which is opened after tapping a point) is skipped.

**Comment by grzesiek2010** [comment]
> What is the expected result after changes in the PR? When I go Select one form map question with quick appearance, I open the map and tap a point/trace/shape the map is closed and I'm moved to the next question. It feels like the step in which the user confirms the choice by tapping "Select" in the bottom sheet (which is opened after tapping a point) is skipped.

This is expected. Using the quick appearance should skip displaying the bottom sheet. It worked like that before, the only bug was that it was not possible to change the answer when one was already selected because the map was immediately closed. Plus navigating to the next question didn't work too as I remember.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- issue #5540 doesn’t occur
- select one from map with the quick appearance on a field-list
- different sources of maps
- offline layers
- don’t keep activities enabled and disabled
- regression checks in select one from map
- regression checks in geo widgets

**Comment by srujner** [comment]
Tested with Success!

Verified on device with Android 13
