### PR TITLE
Fixed parsing the doc with deleted entities

### LINKED ISSUE #6667: Crash (parse error) after deleting entities
#### ODK Collect version
the master version e263c1edb6f48d47af454d6f9f7b175b2e9ee83d
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's a crash after deleting entities after steps described below.
Image

#### Steps to reproduce the problem
1. Download a project with a registration form and an update form (e.g. user "movies" in https://staging.getodk.cloud/projects/101/app-users)
2. Fill and send the registration form creating entity A
3. Fill and send the registration form creating entity B.
4. Delete A and B on Central.
5. Refresh the list of blank forms.
#### Other information
If I restore one of the entities on Central, the crash won’t occur again.
If I create just 1 entity, (update it or not) and delete it, the issue doesn't occur.
#### Expected behavior
The app shouldn't crash.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6667 

#### Why is this the best possible solution? Were any other approaches considered?
The implementation of parsing the document was incorrect. If the document contained multiple `<entity>` children, an exception was thrown due to the way we tried to retrieve those children one by one.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The issue occurred when there was more than one deleted entity. Please test such scenarios. I don't think there is any big risk here.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: open-rosa/src/main/java/org/odk/collect/openrosa/parse/OpenRosaResponseParser.kt [hunk 1]
```diff
@@ -8,5 +8,5 @@ import org.odk.collect.openrosa.forms.EntityIntegrity
 interface OpenRosaResponseParser {
     fun parseFormList(document: Document): List<FormListItem>?
     fun parseManifest(document: Document): List<MediaFile>?
-    fun parseIntegrityResponse(doc: Document): List<EntityIntegrity>?
+    fun parseIntegrityResponse(doc: Document): List<EntityIntegrity>
```
Comment (seadowg) [inline open-rosa/src/main/java/org/odk/collect/openrosa/parse/OpenRosaResponseParser.kt]: We still want to return `null` in cases where the document is invalid so that form download fails

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Androids 10

**Verified cases:**
- issue #6667 doesn't occur
- deleting and restoring entities in different forms with different datasets

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15
