### PR TITLE
Don't let user save invalid preferences

### LINKED ISSUE #2086: Import/Export settings can crash app with certain invalid QR codes
#### Software and hardware versions 
[Collect v1.14.0-beta.1](https://github.com/opendatakit/collect/releases/tag/v1.14.0-beta.1), Android v6.0.1, [Samsung A5](http://www.samsung.com/ph/smartphones/galaxy-a5-2016-a510/SM-A510YZKDXTC/)

#### Import/Export settings is broken
First thing I noticed is that the QR code wasn't previewed.
screenshot_20180331-031538

Then for few minutes it then shows a popup message saying "**ODK Collect has stopped.**"

#### Steps to reproduce the problem

1. Fresh install [**Collect v1.14.0-beta.1**](https://github.com/opendatakit/collect/releases/tag/v1.14.0-beta.1)
2. Go to **Admin settings** › **Import/Export settings**
3. Wait for it... (later, ODK Collect will break itself)

### PR DESCRIPTION
**Pull request by seadowg**
Closes #2086 

This blocks a user from saving preferences from a QR code where the value type doesn't match the default for that key. 

There is also a second change that warns the user that they currently have invalid preferences saved. This prevents a crash that was occurring and let's them know they need to re import. This was a minor change just to account for anyone currently stuck in the scenario discovered in #2086.

#### What has been done to verify that this works as intended?

Robolectric level tests added for `GeneralSharedPreferences` and `AggregatePreferencesAdder`. Manually verified using a device and both a valid and invalid QR code.

I'd like for there to be more tests around the error handling at a `Fragment` level but I ran into problems with `PreferencesFragment` and Robolectric` not playing nice. I'm up for digging into this further but didn't want to hold up a fix to the issue.

#### Why is this the best possible solution? Were any other approaches considered?

I did consider reworking `GeneralSharedPreferences` so that individual preferences have type safety and (i.e. there is a Preference object or a `setX` method). I'm probably going to look at this next but again it felt like a big change to make before getting a fix in.

I also think it would be good to try and remove the singletons stored at a process level (both `GeneralSharedPreferences` and `GENERAL_KEYS`). Generally I've found that having singletons that live beyond the `Application` lifecycle creates problems with testing as both Robolectric and plain ol' JUnit tests can run into weird scenarios with test pollution. Again I'd like to potentially look at this next.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only major change is it blocking them from saving "invalid" preferences. I'd definitely like a sense check on if there are any major risks around that!

#### Do we need any specific form for testing your changes? If so, please attach one.

N/A

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
My bad. Misread the first checkbox and ran all the tests but not the PMD check. Will fix now.

File: collect_app/src/test/java/org/odk/collect/android/preferences/GeneralSharedPreferencesTest.java [hunk 1]
```diff
@@ -40,6 +40,7 @@ public void save_allowsNullValues() {
     }
 
     @Test(expected = GeneralSharedPreferences.ValidationException.class)
+    @SuppressWarnings("PMD.UseAssertTrueInsteadOfAssertEquals")
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/preferences/GeneralSharedPreferencesTest.java]: Generally agree with the check here but feel like an `assertFalse` would make the code less readable (and considerable) as we're asserting on the value stored rather than asserting on a result or flag. Happy to change if people disagree!

File: collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesAdder.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
+package org.odk.collect.android.preferences;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesAdder.java:15]: Please add [a license header](https://github.com/opendatakit/collect/blob/master/LICENSE.md#appendix-how-to-apply-the-apache-license-to-your-work) here and on the other new classes! The copyright holder is either you or your employer. 

I also think it'd be good to have a comment on the class and why it is its own thing since it's a bit unusual (at least for this code base). I do like the approach of splitting off a fragment to bypass non-testability of existing code. That's a strategy we could likely use elsewhere as a stop-gap for new code as the overall testability of the system increases.

File: collect_app/src/test/java/org/odk/collect/android/utilities/SavePreferencesFromJSONTest.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    public void setup() {
+        prefs().edit().clear().commit(); // Make it simpler to test what is written to prefs
+    }
+
+    private SharedPreferences prefs() {
+        return PreferenceManager.getDefaultSharedPreferences(RuntimeEnvironment.application);
+    }
+
+    @Test
+    public void whenAggregatePreferencesAreInCorrect_callsFailureAndDoesntSaveValue() throws Exception {
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/utilities/SavePreferencesFromJSONTest.java]: Name should probably be `AreIncorrect` -- I had to read this several times to figure out what being inside "correct" meant. 😆

File: collect_app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -654,4 +654,5 @@
     <string name="missing_google_account_dialog_desc">To submit forms via Google Sheets you have to set up your Google account in the Server settings.</string>
     <string name="sms_invalid_phone_number_description">Set a destination phone number for SMS submissions or change your transport type.</string>
     <string name="notification_channel_name">General notifications</string>
+    <string name="corrupt_imported_preferences_error">Saved/imported configuration is corrupt. Please re-import.</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: I think we always use the word "settings" in user-facing text. So maybe "Current settings are corrupt."?

If this were common, I'd suggest we reset the settings to defaults to make it easier to recover. It's not super common so maybe the message could be "From the admin settings, reset settings or import working ones." to provide just a bit more guidance.

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 5]
```diff
@@ -269,7 +270,11 @@ public void onSuccess() {
 
             @Override
             public void onFailure(Exception exception) {
-                ToastUtils.showLongToast(Collect.getInstance().getString(R.string.invalid_qrcode));
+                if (exception instanceof GeneralSharedPreferences.ValidationException) {
+                    ToastUtils.showLongToast(Collect.getInstance().getString(R.string.invalid_qrcode));
+                }
+
+                Timber.e(exception);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Since this is recoverable, I think logging it at level `d` or `w` would be better. What do you think? (I recognize it was at `e` before!)

We don't really have good guidelines for these levels and should write them somewhere. `e` logs to Crashlytics in production so we try to reserve it for things where there is actually something wrong with the software rather than the user input.

File: collect_app/src/test/java/org/odk/collect/android/preferences/GeneralSharedPreferencesTest.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/preferences/GeneralSharedPreferencesTest.java]: Agreed, suppressing locally looks fine to me.

**Review by lognaturel — COMMENTED** [review]
A few surface comments, suggestions and questions but overall it looks great to me!

**Comment by lognaturel** [comment]
Just remembered you had some notes in the PR description I wanted to respond to.

> I also think it would be good to try and remove the singletons stored at a process level (both GeneralSharedPreferences and GENERAL_KEYS).

Agreed. Some discussion around the best way to do this would definitely be appreciated. @shobhitagarwal1612 has been wanting to discuss https://github.com/opendatakit/collect/pull/1871 and other alternative approaches.

File: collect_app/src/test/java/org/odk/collect/android/utilities/SavePreferencesFromJSONTest.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/utilities/SavePreferencesFromJSONTest.java]: Haha very good point!

File: collect_app/src/main/res/values/strings.xml (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/res/values/strings.xml]: Cool that makes sense. I'll change it to that.

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java (hunk 5 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Ah right. Yeah definitely doesn't make sense to log this as a crash. Personally I'd be tempted to not log it. Generally I want crash reporting for fatal issues but find I'm usually debugging issues with the debugger tools in Android so tend to to keep my logs pretty quiet. 

I'll remove the logging for this case but let me know if you disagree!

**Comment by kkrawczyk123** [comment]
I can see a crash when rotate device on Fill Blank Form view on all my Android devices from 4.1 to 8.1. 

I scanned code attached in the issue, I saw the toast telling me that QR code does not contain valid settings, but does that mean that none settings are imported at all? When I am using dark mode n Androids 6.0 and 7.0, I am losing it after scanning that code. Go out of admin settings and open fill blank form or any other option - light mode is visible. When I kill an app and open again I have light mode (Android 7.0) and on Android 6.0 I am losing dark mode immediately. It makes me feel that something is exported anyway. @seadowg, could you please investigate that?

@opendatakit-bot unlabel "needs testing"

**Comment by seadowg** [comment]
@kkrawczyk123 hey! So I'm not able to reproduce the crash. I'm pretty new to the app so maybe some step by step instructions to reproduce would be helpful?

In terms of it saving some settings and not the invalid ones I think that is what happens. It actually is a little strange:
1. QR code is scanned
2. App looks at for for each key it might expect to be in the data (i.e. "server_url" or "password") from the QR code and then:
    - If it is: set that value in settings
    - If it is **but the value is invalid**: don't set the value and go straight to 3
    - If it isn't: reset the value to the default
3. Return to home if successful or show an error if not

I guess that this means depending on what key is invalid it might save some settings, reset others but then fail before resetting others to their default value. It's a pretty confusing scenario for the user I think. Does it make sense do you think to reset all the values in settings to their default if importing fails?

Sorry if none of that makes any sense I found it quite hard to describe!

**Comment by shobhitagarwal1612** [comment]
Just an idea:
Since we have a QRCode of currently applied settings (saved in directory), we can use that as a fallback whenever the scanned QRCode is faulty to revert back to the last known good state. 
I think that's what people in general would expect whenever something bad happens.

**Comment by seadowg** [comment]
@shobhitagarwal1612 that also works as a fallback!

**Comment by seadowg** [comment]
@kkrawczyk123 this should be good for testing again. I haven't had a chance myself as I need access to a device and had to leave my office early today. If you get a chance though let me know!

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot label "behavior verified"

**Comment by seadowg** [comment]
@kkrawczyk123 🙌. Thanks so much!

**Comment by zestyping** [comment]
This looks all set and ready to go!  @yanokwa, want to approve?

File: collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceSaver.java [hunk 6]
```diff
@@ -0,0 +1,98 @@
+package org.odk.collect.android.preferences;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceSaver.java:15]: Please add a license header

File: collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceValidator.java [hunk 7]
```diff
@@ -0,0 +1,28 @@
+package org.odk.collect.android.preferences;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceValidator.java:15]: Please add a license header

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

**Comment by seadowg** [comment]
@shobhitagarwal1612 ah sorry should have caught those. Been on vacation but will take a look at updating when I get a chance

**Comment by seadowg** [comment]
@shobhitagarwal1612 that's fixed now! Sorry for the delay: just got back from vacation 🏝

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
Thank you so much @seadowg :tada: :tada:
