### PR TITLE
Store the server URL that was imported by QR code

### LINKED ISSUE #3043: Store the server URL that was imported by QR code.
#### Software and hardware versions 
Collect v1.21.x, Android vx.x.x, device used...

#### Problem description
Only URLs that were introduced manually in General Settings/Server are stored in the drop-down URL list after using another server URL. User does not have to input the URL again, just choose it from the list, switching servers, when needed, is very easy and comfortable. 
When the server's URL is imported by QR code it is visible in the General Settings/Server right after import. But when you change it to default one or another introduced manually it is not visible on the drop-down URL list and to use it, the user has to input the URL manually again.

#### Steps to reproduce the problem
1. Introduce server URL on the one device, open Admin Settings, Import/Export Settings
2. On another device open Admin Settings, Import/Export Settings and Scan Code from the first device
3. Open General Settings/Server on the device on which you've just imported the settings, the URL introduced on the second device should be visible.
4. Click on URL, on displayed dialog use the drop-down arrow and change URL to another from the list. 
5. Click on URL again, imported server URL is not visible on the drop-down list.

#### Expected behavior
I think that imported URL should be stored on the URL list, as with Aggregate it is much easier to input manually the URL it is far more complicated with Central (nearly not possible at all). I think it might be a good idea to give users the opportunity to jump between Aggregate and Central without a must to scan the QR code every time especially when they are in the field and they do not have computers. 
Another good question is if the whole list of the URL used on 1st device should be stored on the 2nd or just the one used when QR code was scanned. 
@lognaturel @yanokwa @grzesiek2010 what do you think about that improvement suggestion?

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3043 

#### What has been done to verify that this works as intended?
I tested importing settings from QR code and from `collect. settings` file.

#### Why is this the best possible solution? Were any other approaches considered?
It just fixes the bug, there is no other solution than including the history of used urls (max 5) to exported settings.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Tested importing settings from QR code and from `collect. settings` file would be enough. It's not a risky pr.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
What this does is make the saved list of servers part of the settings export. That means that if a device has a list of saved servers and then another device is configured from the first device, the second device will get the same saved list of servers.

I don't think that's the desired behavior. Each device should have its own history of saved servers. But if a device is configured by reading a QR code/collect.settings, the server that gets set from those settings should be added to the recent server list.

A concrete example:
- I currently have url1, url2 and url3 in my recent URLs list
- I scan the following QR code which puts a long Central URL in my URL list:
appuser
- I switch to the default server
- I should see the long, imported URL in my recent list

I would also expect url1, url2 and url3 to still be in my recent URLs list. I would expect the settings import to only reset settings that could have been included in the import but it looks like it resets all application settings, is that correct?

**Review by lognaturel — CHANGES_REQUESTED** [review]
See note about expected behavior.

**Comment by grzesiek2010** [comment]
Yes, you are right. I improved the solution and now it works as expected.

File: collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
+package org.odk.collect.android.preferences.utielities;
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java]: utielities -> utilities

**Review by priusak — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@lognaturel do you think it's ready for testing? Looks as if it's the last pr here which we would need to test for v1.24.

**Comment by lognaturel** [comment]
It's on my list to look at by the end of the day. I only took a quick pass and it looks good. The only thing I've flagged so far is a typo.

**Review by lognaturel — COMMENTED** [review]
Typo

File: collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+import org.junit.runner.RunWith;
+import org.odk.collect.android.R;
+import org.odk.collect.android.preferences.GeneralSharedPreferences;
+
+import java.util.List;
+
+import static junit.framework.TestCase.assertEquals;
+import static org.odk.collect.android.preferences.utielities.KnownUrlListUtils.KNOWN_URL_LIST;
+
+@RunWith(AndroidJUnit4.class)
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java]: Why have this annotation? As far as I know it doesn't do anything and it's deprecated.

File: collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import java.util.Collections;
+import java.util.List;
+
+public class KnownUrlListUtils {
+    static final String KNOWN_URL_LIST = "knownUrlList";
+
+    private KnownUrlListUtils() {
+    }
+
+    public static void addUrlToList(String url) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java]: The intended behavior of this method is non-obvious enough that it would be helpful to have a comment that describes its side effects.

File: collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+        List<String> urlList = getUrlList();
+
+        if (urlList.contains(url)) {
+            urlList.remove(url);
+        } else if (urlList.size() == 5) {
+            if (urlList.get(4).equals(Collect.getInstance().getString(R.string.default_server_url))) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java]: This ensures that the default server URL is always preserved in the list, right? And that is new behavior? That doesn't seem right to me -- if the default URL hasn't been used, I think it makes sense to replace it.

**Review by lognaturel — CHANGES_REQUESTED** [review]
👍 That's the behavior I had in mind!

I think the tests will be eventually candidates for moving to Robolectric but that will take doing something like adding a setter for the shared preferences in `GeneralSharedPreferences`. I'd be ok with this going in as-is and getting revised later but @seadowg may have some suggestions for making the change now.

Other than that, a couple questions inline.

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 I think we could potentially have tests at a lower level but I'd want to look at reworking the way these kinds of prefs are stored (like @lognaturel brings up). Right now it's nice to have tests at the Espresso level expressing the feature in terms of what the user sees I think - I'd maybe change the name of the test to reflect that though. We could go with something like `ChangingServerURLTest`?

File: collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java]: Fixed.

File: collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtilsTest.java]: Right, it's not needed, fixed.

File: collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java]: Ok I added a comment.

File: collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/preferences/utielities/KnownUrlListUtils.java]: Yes, I don't know why but I was sure it worked in that way before, fixed.

**Comment by grzesiek2010** [comment]
ok, I think I fixed everything.

**Review by lognaturel — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.2, 4.4, 5.1, 6.0, 7.1, 8.1 and 9.0

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
