### PR TITLE
Fix closing notification drawer

### LINKED ISSUE #6391: Fix flaky `PreviouslyDownloadedOnlyTest`
The test `whenPreviouslyDownloadedOnlyEnabledWithAutomaticDownload_checkingAutoDownload_downloadsUpdatedForms_andDisplaysNotification` in `PreviouslyDownloadedOnlyTest` appears to fail sporadically ([example](https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/6131532677228825813/details?stepId=bs.7dcd1ea5254f9819&testCaseId=9)).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6391 

#### Why is this the best possible solution? Were any other approaches considered?
As I said in my comment:

`It appears that sometimes the notification drawer does not close automatically when it should such as after clicking on a notification or its action. This could be due to a bug in Android.`

I hope this fixes the issue but we can't be sure so we will see.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 1]
```diff
@@ -79,6 +79,16 @@ class NotificationDrawer {
     ): D {
         val device = waitForNotification(appName, title)
         device.findObject(By.text(title)).click()
+
+        /*
+        It appears that sometimes the notification drawer does not close automatically
+        after clicking on a notification. This could be due to a bug in Android.
+         */
+        val manageButton = device.findObject(By.text("Manage"))
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: I like this solution. My only worry here is that we might end up with a timing issue if "Manage" hangs around for a small amount of time. Maybe we can add a wait in here (like we do in `waitForNotification`) that waits for it to disappear (and times out).

I'm also thinking we should pull this out to a method and do it everywhere we're expecting the notification drawer to close?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: > My only worry here is that we might end up with a timing issue if "Manage" hangs around for a small amount of time. Maybe we can add a wait in here (like we do in waitForNotification) that waits for it to disappear (and times out).

I've added waiting for 1s but it shouldn't be necessary as we perform other actions before like clicking on a notification or its action so that button should be already there at the time we try to find it.

> I'm also thinking we should pull this out to a method and do it everywhere we're expecting the notification drawer to close?

Yeah, we can do that.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 2]
```diff
@@ -154,4 +151,17 @@ class NotificationDrawer {
...
         }
     }
+
+    /**
+     * It appears that sometimes the notification drawer does not close automatically when it should
+     * such as after clicking on a notification or its action. This could be due to a bug in Android.
+     */
+    private fun closeNotificationDrawerIfOpened() {
+        val device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
+        device.wait(Until.hasObject(By.text("Manage")), TimeInMs.ONE_SECOND)
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: Sorry I probably wasn't very clear in my last comment. I meant we want to wait for "Manage" to be gone, not for it to appear. Then if that wait fails we can do `device.pressBack`. That way we account for any delay in closing the drawer. In more abstract terms, we want to "wait for the notification drawer to close and then close it ourselves if it's not closed".

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: Ah ok, done.

**Review by seadowg — APPROVED** [review]
