### PR TITLE
Fixed centering texts in forms

### LINKED ISSUE #4370: Centered texts are not centered vertically
#### Software and hardware versions 
All versions

#### Problem description
Centered texts are not centered vertically
Screenshot_1611920658

#### Steps to reproduce the problem
Try the attached form: 
[centerText.xlsx](https://github.com/getodk/collect/files/5893894/centerText.xlsx)

#### Other information 
https://forum.getodk.org/t/how-to-align-text-at-the-center/32227/3

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4370

| Before  | After |
| ------------- | ------------- |
| Screenshot_1611920658  | Screenshot_1611924307  |

#### What has been done to verify that this works as intended?
I added one test and also verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that in some case [Html.fromHtml()](https://developer.android.com/reference/android/text/Html#fromHtml(java.lang.String,%20int)) might return values with new lines at the end for example. See:
https://stackoverflow.com/questions/9589381/remove-extra-line-breaks-after-html-fromhtml/9974562

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix and we can just test the scenario described in the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Yes I think we should add info about centering in https://docs.getodk.org/form-styling/ so that it's clear for our users.
https://github.com/getodk/docs/issues/1315

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/StringUtils.java [hunk 1]
```diff
@@ -158,5 +158,25 @@ public static boolean isBlank(String string) {
 
         return true;
     }
+
+    private static CharSequence trim(CharSequence text) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/StringUtils.java:162]: Could we just use `String#trim` for this or is there an extra case we need covered? Looks like the test passes using `toString().trim()` but I might be missing something/test needs to be stricter.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/utilities/StringUtils.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/StringUtils.java:162]: We can't  because we need to return `CharSequence` not string (to use it with `TextView.setText()`) otherwise html styling won't work

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010 I created form with multiselect [4371minimalTest.xml.txt](https://github.com/getodk/collect/files/5931676/4371minimalTest.xml.txt)

The appearance for multiple select should albo be improved.



@getodk-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
Unfortunately fixing that issue is not trivial. We concatenate all selected choices where every single choice might have its own styling and the result then is like:
`<p style="text-align:center">a</p>, <p style="text-align:center">b</p>, <p style="text-align:center">c</p>`
If you open any html editor and paste the text then the result will be the same like you noticed.

To fix the issue we would need to go through all the choices then if every choice should be centered remove the styling and add one general for the entire result. That's not easy and might be full of different cases if choices have different styling so it's not what we want here.

**Comment by lognaturel** [comment]
I agree it's not worth fixing this specific case. @grzesiek2010 how about we add a note to the select multiple documentation and say that style will be applied to the list of selected choices and that this might have unexpected results so should be verified? We can even specifically call out centering as something that won't make sense with select multiple options.

**Comment by grzesiek2010** [comment]
> how about we add a note to the select multiple documentation and say that style will be applied to the list of selected choices and that this might have unexpected results so should be verified?

shouldn't it be added to the [Form styling](https://docs.getodk.org/form-styling/#) section? I need to update it either way to let the users know centering is also possible.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 7.0, 8.1, 10.0

**Verified cases:**
- centered options in `select one` question
- centered options in `minimal` appearance
- centered question represented on `field-list`
- edit saved form
- send to Central
- light/dark mode
- English/Spanish language
- RTL language
- rotation
- minimization
- regression check select one/multi on All widget form

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1, 7.1 and 9.0. Answers are actually not centered on Android 5.1:
Screenshot from 2021-02-11 14-07-25

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
