### PR TITLE
Use foreground service to sync forms manually

### LINKED ISSUE #6825: Match exactly stops downloading when the screen is locked
#### ODK Collect version
the store version 2025.3.0 beta 1 (probably all versions)
#### Android version

10, 16, 16

#### Device used

Redmi 9T, Galaxy 6a, Pixel 7a
#### Problem description

Match exactly stops downloading when the screen is locked and on battery

#### Steps to reproduce the problem
1. Scan user "1000 media" https://test.getodk.cloud/projects/629/app-users
2. Lock the screen for 30min.
3. After 30min unlock the screen check if the form is in "Start new form"
#### Expected behavior
Downloading should continue.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6825

This changes how manual refreshes (from the "Start new form" page) work - they should now show a notification while running (after 10 seconds on some devices) and should always complete regardless of the screen being off or not. Scheduled updates will still not work if they take a long time and run after the screen is off.

#### Why is this the best possible solution? Were any other approaches considered?

The reasons to switch to a foreground service here were:

- 10 minute limit for WorkManager: https://developer.android.com/develop/background-work/background-tasks#will_there_be_a_bad_user_experience_if_the_task_is_deferred_or_interrupted
- Doze mode restrictions: https://developer.android.com/training/monitoring-device-state/doze-standby#restrictions

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only change in behaviour here should be manual refreshes. Otherwise, the app should behave as before.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt [hunk 1]
```diff
@@ -43,11 +69,51 @@ class TaskSpecWorker(
...
+        val intent = WorkManager.getInstance(context).createCancelPendingIntent(id)
+
+        val notification = NotificationCompat.Builder(applicationContext, notificationChannel)
+            .setSmallIcon(org.odk.collect.icons.R.drawable.ic_notification_small)
+            .setContentTitle(context.getString(notificationTitle))
+            .setPriority(NotificationCompat.PRIORITY_LOW)
+            .setContentIntent(intent)
+            .build()
+
+        return ForegroundInfo(1, notification, foregroundType)
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt]: Notification id should be a const as well.

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt [hunk 2]
```diff
@@ -25,6 +26,32 @@ class CoroutineAndWorkManagerScheduler(
...
+    override fun immediate(
+        tag: String,
+        spec: TaskSpec,
+        inputData: Map<String, String>,
+        notificationInfo: NotificationInfo
+    ) {
+        val workManagerInputData = Data.Builder()
+            .putString(TaskSpecWorker.DATA_TASK_SPEC_CLASS, spec.javaClass.name)
+            .putBoolean(TaskSpecWorker.FOREGROUND, true)
+            .putInt(TaskSpecWorker.FOREGROUND_TYPE, FOREGROUND_SERVICE_TYPE_DATA_SYNC)
```
Comment (grzesiek2010) [inline async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt]: I get a warning that `FOREGROUND_SERVICE_TYPE_DATA_SYNC` was added in API 29 won't this be a problem?

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt [hunk 3]
```diff
@@ -75,14 +79,29 @@ class BlankFormListViewModel(
...
-            {
-                formsDataService.matchFormsWithServer(projectId)
-            },
-            { value: Boolean ->
-                result.value = value
-            }
-        )
+
+        if (FeatureFlags.FOREGROUND_SERVICE_UPDATES) {
+            scheduler.immediate(
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt:84]: With the new approach, there is no visual confirmation if the sync finished successfully or not. There should be something, I think.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt (hunk 1 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt]: Good catch. It should really get passed with the notification channel I'm realizing.

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt:84]: Good point! I think that should be additional though as we can probably do something better than a toast seeing as we need to reimplement any way. @alyblenkin are you able to create an issue?

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt (hunk 2 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt]: It just gets ignored on earlier versions. I'll make sure this warning is ignored here as well.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
Should issue #6825 be closed? The PR doesn't include all parts of the issue and the issue is quite important.

**Comment by seadowg** [comment]
@dbemke Good point! The notification problem has been separated out to https://github.com/getodk/collect/issues/6835. I think we may still want to add foreground service syncing on project setup, but let's see how we feel after that's done.

**Comment by dbemke** [comment]
In the PR the toast informing "Form update succeeded" (while manually refreshing the list of form in start new form) doesn’t appear. Is it expected?

**Comment by seadowg** [comment]
> In the PR the toast informing "Form update succeeded" (while manually refreshing the list of form in start new form) doesn’t appear. Is it expected?

Yup! There's no success feedback right now.

**Comment by srujner** [comment]
@seadowg But are you sure that #6825 is fixed here?
Cause I'm still able to reproduce it on Android 12 and 14

**Comment by seadowg** [comment]
@srujner ah sorry I should have been clearer in my [earlier comment](https://github.com/getodk/collect/pull/6824#issuecomment-3163968681)! The problem will still exist and is (now) expected - the only way to allow scheduled match exactly (or auto update syncs) to definitely run when the screen is locked is for the user to remove battery restrictions in the app's system settings. All we can do is work around it by making manual syncing more reliable (this) and making it clearer when scheduled updates don't complete (https://github.com/getodk/collect/issues/6835). We'll also potentially make the first sync (when the user adds the project) more reliable in the same way we've done here.

**Comment by grzesiek2010** [comment]
@getodk/testers  this should be available on **master** as merging it to **v2025.2.x** was a mistake: https://github.com/getodk/collect/pull/6845

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- manual refresh after a new form version, new media, new entity added
- automatic match exactly after manual refresh
- tapping "form syncing" notification while in the project/ while in another project
- downloading a project with a form containing a lot of media and locking the screen
- locking the screen while updating a form

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 16

**Comment by srujner** [comment]
**Tested with Success!**

Verified on a device with Android 12, 14
