### PR TITLE
Fix: Automatic keyboard visiblility (#1864)

### LINKED ISSUE #1864: The keyboard should be visible just after showing an EditText field if a requested application is missing.
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
The keyboard should be visible just after showing an EditText field if a requested application is missing.
#### Steps to reproduce the problem
1. Use `All widgets` form
2. Go to` Ex string widget` or `Ex integer widget` or `Ex decimal widget`
3. Click on the `Launch` button.

#### Expected behavior
The field for manual putting an answer is visible and active but the keyboard is hidden so we should show the keyboard automatically. 

#### Other information 
ezgif com-video-to-gif

It should work in the same way in BearingWidget.

@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by sashank27**
Closes #1864 

#### What has been done to verify that this works as intended?
All the three widgets were tested on a device, and they work as expected.

#### Why is this the best possible solution? Were any other approaches considered?
There is only an additional call to `setFocus()` 

#### Are there any risks to merging this code? If so, what are they?
No.
#### Do we need any specific form for testing your changes? If so, please attach one.
No.

@lognaturel @grzesiek2010 please review

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java [hunk 1]
```diff
@@ -265,6 +265,7 @@ public void onButtonClick(int buttonId) {
             }
         } else {
             onException(errorString);
+            setFocus(getContext());
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: This change looks strange to me. I would rather expect something like https://stackoverflow.com/a/5106399 Could you explain that `setFocus`?
and even if it' ok it should be in `onException()` method I think.

Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: This change looks strange to me. I would rather expect something like https://stackoverflow.com/a/5106399 Could you explain that `setFocus`?
and even if it' ok it should be in `onException()` method I think.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java (hunk 1 above)
Comment (sashank27) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: @grzesiek2010 if you look the `setFocus()` method, it does the same thing as given in the link. Whether or not to put `setFocus()` inside `onException()` is a doubt. The reason is that because the `onException()` is a general method of handling exceptions, which may or may not involve handling the keyboard visibility.
If you say, I can perform the changes in the PR.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: Ahhh `setFocus()` is our method. I got it. But that `setFocus()` method does more than we need (too much if statements). We just need to show the keyboard. So I would recommend creating a new method just for showing the keyboard then you can use it here and probably you can refactor that `setFocus()` method and use your method there too.

**Comment by sashank27** [comment]
@grzesiek2010 @lognaturel did all the changes. Please review

**Comment by sashank27** [comment]
@grzesiek2010 @lognaturel please review it so that I may work in other issues as well.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java [hunk 2]
```diff
@@ -265,9 +265,15 @@ public void onButtonClick(int buttonId) {
             }
         } else {
             onException(errorString);
+            showKeyboard(getContext());
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: I think it should be in `onException()` since we call  `answer.requestFocus()` there too.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java (hunk 2 above)
Comment (sashank27) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: Yep, that would be better.

**Comment by sashank27** [comment]
@grzesiek2010 @lognaturel, please review the changes

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: @grzesiek2010 you didn't like the use of `setFocus` because of the extra check on `hasExApp` and on read-only? Those don't seem like a big deal to me and using `setFocus` is clearer.

Comment (sashank27) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: @lognaturel so should I use `setFocus()` or my new method?

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java [hunk 3]
```diff
@@ -268,6 +268,11 @@ public void onButtonClick(int buttonId) {
         }
     }
 
+    private void showKeyboard(Context context) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: You don't need to pass context here you can just use getContext() method one line below.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java [hunk 4]
```diff
@@ -284,6 +289,7 @@ private void onException(String toastText) {
                 toastText, Toast.LENGTH_SHORT)
                 .show();
         this.answer.requestFocus();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java]: You show keyboard for answer EditText so I think you can move this line to the showKeyboard() method, and you can get rid of `this.`

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by lognaturel** [comment]
@grzesiek2010 why didn't like the use of setFocus? Is it because of the extra check on hasExApp and on read-only? Those are very small checks and using the same methods reduces redundancy.

**Comment by grzesiek2010** [comment]
I was thinking about a bigger refactoring that's why I wanted to have extracted method just for showing the keyboard. 
@sashank27 me and @lognaturel were talking about a few minutes ago. Sorry for that but we agreed your first solution with using `setFocus()` method was ok and the refactoring I meant should be implemented in a separate pr. I'm going to file another issue for that.

**Comment by sashank27** [comment]
So @grzesiek2010 @lognaturel should I edit the current PR, or should I create a new PR for it?
I don't think creating a new issue is necessary. I can make the above changes here only.

**Comment by lognaturel** [comment]
I think we've now managed to thoroughly confuse ourselves! My preference would have been to fix the behavior in the simplest way and consider a refactor later.

That said, since we've reached this point and @grzesiek2010 is happy with the changes, let's do a quick manual verification pass (that's what the `needs testing` tag is for) and get it merged.

@sashank27 Thanks for your patience!

**Comment by sashank27** [comment]
No problem @lognaturel :smile: . Happy to contribute more here :smiley:

**Comment by mmarciniak90** [comment]
@sashank27 Could you clean the code? We should refactor the code later. For now, we want to solve this case in the simplest way.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Merging now before we get even more confused!

The good news is that we almost always have very smooth communication and agreement between everyone. The bad news is that this time we got a little tangled. 😊Once @grzesiek2010 approved the PR, I should have let things be. We will do better next time!

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Verified cases:
* Ex string widget
* Ex integer widget

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
