### PR TITLE
Selection map cleanup

### LINKED ISSUE #4943: Support `map` appearance in `select`/`select_one_from_file`
As discussed on [the forum](https://forum.getodk.org/t/ability-to-load-locations-into-the-geowidget-to-guide-data-collection/27406/12) (along with design details), we want to add support for `.geojson` files in Select questions. This means adding a `map` appearance for `select_one`/`select_one_from_file` (it's opaque to Collect which "select one" is actually being used in the form) that allows the enumerator to select an item from a map. Each item in the map is positioned using data from the select choice's `geometery` column.

## Backlog
 
- [x] #4947
- [x] #4949
- [x] #4948 
- [x] Make sure button text size uses dynamic font size (`answerSize`)

## Cleanup

- [x] Investigate moving shared map behaviour from `SelectionMapFragment` into `MapFragment` implementations (maintaining map zoom on recreate for instance)
- [x] Remove individual implementations of zoom behaviour
- [x] Investigate extracting `maps` module to house `MapFragment`, `MapPoint` and `MapFragmentFactory` and creating modules for each implementation (classic **D**epenednecy **I**nversion **P**rinciple setup)
- [x] Organize `geo` package structure
- [x] Add loading state/progress dialog to maps - currently DB operations are all happening on the UI thread (existing problem)
- [x] Add tests to cover bottom sheet behaviour (currently untestable due to animations always running)

### LINKED ISSUE #5171: Mapbox should zoom to points on the map of forms
#### Software and hardware versions 
The issue will be visible after merging https://github.com/getodk/collect/pull/5141

#### Problem description
Mapbox should zoom to points on the map of forms after opening the map.

#### Steps to reproduce the problem
1. Select mapbox in Settings -> Maps
2. Save a few forms with geo widget so that they are visible on the map of forms (points should be saved using different location than the current one so that's it's cleared if the map is zoomed to the current location or the points)
3. Open the map of forms. 

#### Expected behavior
The map should be zoomed in a way that shows all poinst 

#### Other information 
This is not a new issue however with the old mapbox implementation it wasn't visible (or not always visible)
Possible solution: https://github.com/getodk/collect/commit/34089a4eaa54e8b4dab9cccf3a383b85adb58ced

### LINKED ISSUE #5172: Selected points should preserve activity recreation
#### Software and hardware versions 
The issue will be visible after merging https://github.com/getodk/collect/pull/5141

#### Problem description
Points selected on the map should be highlighted even after activity recreation.

#### Steps to reproduce the problem
1. Select mapbox in Settings -> Maps
2. Save a few forms with geo widget so that they are visible on the map of forms
3. Open the map of forms.
4. Select any point and rotate your device

#### Expected behavior
Selected point should be still highlighted

#### Other information 
This is not a new issue however with the old mapbox implementation it wasn't visible (or not always visible)
Possible solution: https://github.com/getodk/collect/commit/b2cea654a7e338398ddd6ecc0f22a12362b21139

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4943
Closes #5171 
Closes #5172 
~~Blocked by #5141~~

To understand changes here, it'd be best to review the checkmarks in the issue and then run through the PR commit by commit.

#### What has been done to verify that this works as intended?

New tests and verified manually.

#### Why is this the best possible solution? Were any other approaches considered?

The commits are mostly pretty small and iterative, so hopefully everything is clear. I'll leave comments inline for anything that stands out to me.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

It'd be good to review the selection map views (Form Map and Select One From Map) and also all the map engines in general (sorry 😭).

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: maps/src/main/java/org/odk/collect/maps/MapFragmentFactory.kt [hunk 1]
```diff
@@ -1,7 +1,5 @@
 package org.odk.collect.maps
 
-import android.content.Context
-
 interface MapFragmentFactory {
-    fun createMapFragment(context: Context): MapFragment?
+    fun createMapFragment(): MapFragment
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/MapFragmentFactory.kt:4]: We're now in an awkward situation of the result of this method having two expected types (`MapFragment` and `Fragment`). Ideally, `MapFragment` would be defined like this:

```kotlin
abstract class MapFragment : Fragment()
```

But, right now we can't do that because some implementations extend their mapping framework's Fragment. We might want to think about reworking them so that the mapping framework Fragment ends up as a child of the `MapFragment` instead, but I didn't want to add more rework to this PR.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
I've found a crash in OSM, the bug does not occur in Google Maps and Mapbox and cannot be reproduced on master. 

**Steps to Reproduce:**
1. Go to Project Settings -> Maps and Select OSM as Source;
2. Download all Widgets form;
3. Open GeoTrace or GeoShape widget;
4. Click on Back button or Save button;
5. The app will crash.

**Expected Behavior:**
The application should not crash.

**Other Information:**
Stack trace:
    Process: org.odk.collect.android, PID: 5057
    java.lang.RuntimeException: Unable to destroy activity {org.odk.collect.android/org.odk.collect.geo.geopoly.GeoPolyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.LinearRing.setPoints(java.util.List)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5061)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5090)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.LinearRing.setPoints(java.util.List)' on a null object reference
        at org.osmdroid.views.overlay.PolyOverlayWithIW.setPoints(PolyOverlayWithIW.java:379)
        at org.odk.collect.osmdroid.OsmDroidMapFragment$PolyFeature.update(OsmDroidMapFragment.java:799)
        at org.odk.collect.osmdroid.OsmDroidMapFragment$PolyFeature.dispose(OsmDroidMapFragment.java:808)
        at org.odk.collect.osmdroid.OsmDroidMapFragment.clearFeatures(OsmDroidMapFragment.java:352)
        at org.odk.collect.osmdroid.OsmDroidMapFragment.onDestroy(OsmDroidMapFragment.java:176)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3251)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:780)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:335)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
        at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:615)
        at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:350)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2844)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2820)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:345)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:306)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
        at org.odk.collect.geo.geopoly.GeoPolyActivity.onDestroy(GeoPolyActivity.java:186)
        at android.app.Activity.performDestroy(Activity.java:8203)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5046)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5090) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.app.ActivityThread.main(ActivityThread.java:7592) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2022-07-11 12:50:50.502 1616-2016/? E/InputDispatcher: channel 'c1cb015 org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-07-11 12:50:50.502 1616-2016/? E/InputDispatcher: channel 'f9c4a7 org.odk.collect.android/org.odk.collect.geo.geopoly.GeoPolyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-07-11 12:50:50.508 1616-2016/? E/InputDispatcher: channel 'b6f369b org.odk.collect.android/org.odk.collect.android.activities.MainMenuActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-07-11 12:50:50.542 1616-1787/? E/system_server: Invalid ID 0x00000000.
2022-07-11 12:50:50.576 6279-6279/? E/collect.androi: Unknown bits set in runtime_flags: 0x40000
2022-07-11 12:50:50.580 6279-6279/? E/collect.androi: Not starting debugger since process cannot load the jdwp agent.
2022-07-11 12:50:50.766 6279-6279/? E/libc: Access denied finding property "ro.vendor.df.effect.conflict"
2022-07-11 12:50:50.766 6279-6279/? E/libc: Access denied finding property "ro.vendor.knock.type"
2022-07-11 12:50:51.245 1616-3362/? E/WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
2022-07-11 12:50:51.858 5558-5652/? E/PowerKeeper.Event: oops, parse AM_RESTART_ACTIVITY_AI parameter error

**Comment by dbemke** [comment]
**Software and hardware versions** 
Android 10, 11, 12

**Problem description**

For Google Maps, OSM, Mapbox zoom to points on the map of forms after opening the map is not kept properly after rotating to landscape orientation. When 3 points were added on the map, after rotating to landscape orientation only 1 point is shown.
If map is opened in landscape orientation, rotating doesn’t affect the zoom.

**Steps to reproduce the problem**

1. Select Google/ Mapbox/ OSM as source of maps.
2. Go to All widgets forms.
3. Save a few forms with geo widget so that they are visible on the map of forms .
4. Open the map of forms in portrait orientation.
5. Rotate to landscape orientation.

**Expected behavior**

User is able to see all points on map after rotating the screen.

**Other information** 

On master commit d40f33070231abba7c07f19c25262109d155d91a  starting from portrait orientation and then rotating doesn’t affect the zoom, but after starting from landscape orientation and rotating twice only one point is shown.

**Comment by seadowg** [comment]
@srujner @dbemke thanks folks. Will look at these today.

**Comment by seadowg** [comment]
> If map is opened in landscape orientation, rotating doesn’t affect the zoom.

@dbemke this looks like an existing behaviour (the current release behaves the same way). We just maintain the zoom "level" on rotation. Rotating and keeping all the points in view would actually have to change the zoom level as the requirement to get the points in a horizontal frame or vertical one will usually be different. We could switch to the behaviour you describe, but it would be a new feature.

**Comment by seadowg** [comment]
> I've found a crash in OSM, the bug does not occur in Google Maps and Mapbox and cannot be reproduced on master.

@srujner  This should be fixed now

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 2]
```diff
@@ -805,7 +805,6 @@ public void dispose() {
                 map.getOverlays().remove(marker);
             }
             markers.clear();
-            update();
```
Comment (seadowg) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java:782]: I can't work out why this would have been there. Any ideas @grzesiek2010?

Comment (grzesiek2010) [reply osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java:782]: If removing polylines and polygons work as expected without it then the only thing from that method that might be needed is
`map.invalidate()`
without it the map might be updated with a visible delay I guess (but I'm not 100% sure).

**Comment by srujner** [comment]
@seadowg I've found another issue with manual recording point in GeoShape widget, unfortunately it's not reproducing on master.

**Other Information:** 
Reproducing only in GeoShape widget for Google Maps and OSM on all devices.

**Steps to Reproduce:**

- Go to Project Settings -> Maps and Select OSM/Google Maps as Source;
- Download all Widgets form;
- Open GeoShape widget;
- Select Manual location recording and click start;
- Record 4 points and click save button;
- Click on "View or change GeoShape" button;
- There will be "-1" recorded points.

**Expected Behavior:**
Number of recorded points should stay the same.

https://user-images.githubusercontent.com/85225519/178716570-f8803a03-4a7e-48d9-94ac-171e9df5897e.mp4

**Comment by dbemke** [comment]
I've created a separate issue for OSM and problem described in link, because it's also on master.
 In OSM clicking View or Change Geotrace/Geoshape, after having saved a few points in manual location recording, zooms to a wrong place #5184

**Comment by seadowg** [comment]
> I've found another issue with manual recording point in GeoShape widget, unfortunately it's not reproducing on master.

@srujner wow this is a nasty one. Looking at the code, it seemed like the bug was in code I hadn't touched, so I checked the older versions of the app and I'm able to reproduce this on both `master`, the latest beta and in v2022.2.3. Could you check again?

**Comment by srujner** [comment]
@seadowg of course, will check it right away.

**Comment by srujner** [comment]
@seadowg hmm that's a bit weird. Now I was able to reproduce this issue on master, but when i tried to do it again it took me like 10 times so it looks like it cannot be reproduced 100%. Either way You are right and it's not PR fault. Do You want me to create a separate issue for this one then?

**Comment by seadowg** [comment]
> Do You want me to create a separate issue for this one then?

Yup sounds good!

**Comment by srujner** [comment]
Issue with number of recorded points; #[5186](https://github.com/getodk/collect/issues/5186)

**Comment by dbemke** [comment]
**Tested with Success!**
Verified on Androids: 8.1, 11

**Verified cases:**
    • Issue [#5171](https://github.com/getodk/collect/issues/5171) [#5172](https://github.com/getodk/collect/issues/5172)  and OSM crash are no longer reproducing; 
    • Other bugs were reported as separate issues; 
    • Regression checks for GeoPoint, GeoTrace, GeoShape widgets; 
    • Regression checks on external geo widgets; 
    • Regression checks on Forms: geojson, gps_accuracy_threshold, map internal-select, placement_map, TestingGeoPointWidgetWithValue, OSM_buildings; 
    • Select Map forms; 
    • Offline Layers; 
    • Placement by tapping, manual mode and automatic mode 
    • Google Maps, Mapbox, OSM; 
    • Collecting Location in background; 
    • View Submissions on map; 
    • Sending Submission to Central; 
    • Switching between maps Google/OSM/Mapbox 
    • Map view with displayed points 
    • Screen rotation, 
    • Minimize app, using backward button, 
    • Light and Dark mode,

**Comment by srujner** [comment]
**Tested with Success!**
Verified also on Androids: 5.1, 10 and 12
