### PR TITLE
Fixed displaying saved forms to delete

### LINKED ISSUE #6017: Deleting a sent form in "Delete form- Saved Forms" doesn’t remove the form from the list
#### ODK Collect version
the master version e49eae16657d6677abde44e4475c1f08d3ccf9ae
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Deleting a sent form in "Delete form- Saved Forms" doesn’t remove the form from the list. (In Sent the form is grayed out and there’s info that it has been deleted.)
The issue doesn’t occur in the store version 2024.1.2.
#### Steps to reproduce the problem
1. Send a form.
2. Go to "Delete Form-Saved forms".
3. Select the form and click "Delete Selected".
4. In the dialog click "Delete Forms".
5. Check if the form was removed from the list.
#### Expected behavior
A deleted sent form should disappear from the list of forms to delete.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6017 

#### Why is this the best possible solution? Were any other approaches considered?
I could have edited `InstancesDataService` by adding a new flow specifically for undelete instances (and read them from the repository) but:
1. This would make testing more difficult than what I did because I would need to rework the view model test completely so that it tests a real `InstancesDataService` object.
2. I'm not sure if exposing different flows for different scenarios (all instances, undelete instances, etc) is what we want to have in our data service. Maybe exposing just one like now is clearer.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should fix filtering forms to delete so that the soft-deleted ones (forms that have already been deleted but still exist in the database so that we can keep track of sent forms for example). are not displayed on the list.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt [hunk 1]
```diff
@@ -142,7 +142,7 @@ class DeleteFormsActivity : LocalizedActivity() {
                     showAllVersions = true
                 )
 
-                SavedFormListViewModel::class.java -> SavedFormListViewModel(
+                DeleteSavedFormListViewModel::class.java -> DeleteSavedFormListViewModel(
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt]: I'm not sure about this rename. I was envisioning that we'd be able to use `SavedFormListViewModel` in other places (like "Drafts") in the future. But, maybe it makes more sense to have this (`DeleteSavedFormListViewModel`) name now and rename in the future if we do end up generalising it?

**Review by seadowg — CHANGES_REQUESTED** [review]
It looks like there's some conflicts blocking this.

> I could have edited InstancesDataService by adding a new flow specifically for undelete instances (and read them from the repository) but:
>
> 1. This would make testing more difficult than what I did because I would need to rework the view model test completely so that it tests a real InstancesDataService object.
> 2. I'm not sure if exposing different flows for different scenarios (all instances, undelete instances, etc) is what we want to have in our data service. Maybe exposing just one like now is clearer.

Good points. I guess it's a trade off, if we expose different Flows/LiveData values for different "filters" over the data then there is definitely more complexity in the data service to manage this and more API to care about from clients. On the other hand, exposing "everything" and then filtering in memory will definitely be less efficient than pushing that work all the way to the DB. I think sticking with the least change for now (what you've done) is a good idea. If we do need to change it later once we're using the data service for all our lists, we'll be better informed to make that decision then.

File: collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt]: Yeah, I thought that with the new changes that view model could not be shared but that's not true in Drafts as you said we would also need to filter out deleted forms. I've removed that change.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android: 11

**Verified cases:**

- Issue https://github.com/getodk/collect/issues/6017 does not occur
- Deleting blank / saved forms
- Deleting forms with different states
- Forms with auto delete
- Deleting forms while sending

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android: 10

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android: 13
