### PR TITLE
Remove the newly introduced async operations from FormEntryViewModel

### LINKED ISSUE #5895: Collect is not returning the answer in some Widgets
**ODK Collect version**
the master version ee016ccddd023ed4ed3d825d83c642011e6e85c7
**Android version**
10,12, 13

**Device used**
Google Pixel 3a, 6a

**Problem description**
When I open some widgets, the response is not returned in the collect. 
So far i noticed it for the GeoWidgets, Bearing Widget, Signature Widget, Draw Widget and Barcode Widgets

**Steps to reproduce the problem**

1. **Have Don't keep activities Enabled!**;
2. Create a demo project and download All Widgets form;
3. Open All widgets form and navigate to the Geo Widgets;
4. Go through all Geo widgets and save the answers;
5. You'll notice that no answer is visible in the collect.

**Expected behavior**
Answers should be returned and visible in the app.

### LINKED ISSUE #5900: Missing values in audit logs of track changes forms - only values of the first question are present
#### ODK Collect version
the master version 431b1b1592ad49c4d618abd10c30362e4e990416
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
In audit logs of track changes forms only the first question is saved and shown in the audit CSV. The events of other questions are present but the filled values in answers are missing. After editing the saved form in the audit logs there are only values of the first questions. 
The issue doesn’t occur on the store version.
#### Steps to reproduce the problem
1. Go to a form with track changes option.
e.g. 
[track-changes-reason-on-edit-2q.xml.txt](https://github.com/getodk/collect/files/13872458/track-changes-reason-on-edit-2q.xml.txt)
2. Fill the form and save as draft.
3. Go to "Drafts”. Edit and save the form.
4. Check logs in the audit CSV.
#### Expected behavior
Track changes form should save all values in all questions in the audit logs.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5895 
Closes #5900
Reopens #5229

The problem was caused by the introduction of asynchronous index updating.
When `Don't keep activities` is enabled activities are destroyed after leaving them so the `FormFillingActivity` will be destroyed every time we start an activity to get data eg. after starting camera apps, after starting activities to get geolocation, etc 
So the flow is like:
1. When a user goes to the `BearingWidget` in the `All widgets` form and clicks the button a new activity (`BearingActivity`) is started and the `FormFillingActivity` is destroyed
2. When a user accepts the answer the `BearingActivity` is being closed and the app goes back to the `FormFillingActivity` that needs to be created again.
3. [formEntryViewModel.refresh();](https://github.com/getodk/collect/compare/master...grzesiek2010:collect:COLLECT-5895?expand=1#diff-0bf62cb249d6cb5715c94f28798547065602dc39e890993332bb6ed5fb42d88cL698) is called what triggers creating a new `ODKView` but since it's now an async process, `onActivityResult` is called before a new `ODKView` is created and the there is no view (question) we can update by passing a new answer to it.

@seadowg 
we could fix this problem with the changes I've implemented in this pull request but now I see that's not the only regression caused by introducing those async operations. Another one is https://github.com/getodk/collect/issues/5900. There the problem is that the order of operations has been changed (updating index and flushing audit events). For example in the `moveForward` method flushing used to take place before updating the index (and this is what we need) but now it takes place after see: https://github.com/getodk/collect/commit/2ef4a48561a0742d8c581511ead46fba03d6d329#diff-56f94c263309e5efe7fa5fe934a08aa2b4b7fcec3e0ddb72319c7bee967fcdffR194

I'm afraid we might have more bugs caused by introducing those async operations so maybe it would be better to revert that change at all. What do you think?

#### Why is this the best possible solution? Were any other approaches considered?
As we discussed here and in slack, removing the newly introduced async operations that mess up with other synchronous operations would be the best solution for now.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think we can focus on verifying that the two mentioned issues are really fixed. There might be other issues like that (weird) but it's not possible to guess where.

#### Do we need any specific form for testing your changes? If so, please attach one.
For #5895 it would be the form attached to the issue.
 
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
> I'm afraid we might have more bugs caused by introducing those async operations so maybe it would be better to revert that change at all. What do you think?

I think reverting is a good idea - it's a really important change that we want to make, but it seems like we're not done with it yet. We can then open a new PR with a "reverts revert" commit and fix these issues there. I think like with 5888, we probably should have held back from merging this one without QA.

**Review by seadowg — CHANGES_REQUESTED** [review]
As discussed above, I think we should go with a revert instead.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt [hunk 1]
```diff
@@ -74,6 +74,22 @@ class AuditTest {
         assertThat(auditLog[1].get("new-value"), equalTo("31"))
     }
 
+    @Test // https://github.com/getodk/collect/issues/5900
+    fun navigatingToNextQuestion_savesAnswersFormCurrentScreenToAuditLog() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt]: "Form" -> "From"

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 2]
```diff
@@ -877,7 +877,7 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
         // button or another question to jump to so we need to rebuild the view.
         if (requestCode == RequestCodes.HIERARCHY_ACTIVITY || requestCode == RequestCodes.CHANGE_SETTINGS) {
             activityDisplayed();
-            formEntryViewModel.refreshSync();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Instead of removing `refreshSync` could we keep it and `refresh` and just switch to using `refreshSync` everywhere (and `updateIndex(false)` inside `FormEntryViewModel`. We definitely want to move away from loading select choices and other things that happen when moving screens on the UI thread, so even if it's unused I'd like to leave the "infrastructure" in. Having `refreshSync` deprecated also flags that we don't want to add anything else in that uses it.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt]: Fixed.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Done.

**Comment by seadowg** [comment]
I've marked that this PR will reopen #5229 as discussed.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 3]
```diff
@@ -118,12 +118,9 @@ public void promptForNewRepeat() {
...
 
-        worker.immediate((Supplier<Void>) () -> {
-            jumpBackIndex = formController.getFormIndex();
-            jumpToNewRepeat();
-            updateIndex();
-            return null;
-        }, ignored -> {});
+        jumpBackIndex = formController.getFormIndex();
+        jumpToNewRepeat();
+        refreshSync();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Can we switch all these internal `refreshSync` calls to `updateIndex(false)`?

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java [hunk 4]
```diff
@@ -69,7 +69,7 @@ public void setup() {
     public void refresh_whenEventIsBeginningOfForm_stepsForwards() {
         formController.setCurrentEvent(FormEntryController.EVENT_BEGINNING_OF_FORM);
 
-        viewModel.refresh();
+        viewModel.refreshSync();
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java]: We can still use `refresh` in tests as we're flushing the `Scheduler` after.

**Review by seadowg — CHANGES_REQUESTED** [review]
Looking good! Just a couple of last tweaks.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Yes.

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10

**Verified cases:**
- issues #5895, #5900 don’t occur
- regression checks in audit logs
- don’t keep activities enabled and disabled in All widgets
- saving answers in different orders/ways in forms

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Androids: 13
