### PR TITLE
Offline basemap selection shouldn't be lost on screen rotation

### LINKED ISSUE #2647: Offline basemap selection is lost on screen rotation
#### Software and hardware versions 
All versions of Collect.

#### Problem description
If you have selected an offline basemap in the GeoTrace or GeoShape activities, then when the screen is rotated, your selection is lost.

#### Steps to reproduce the problem
Install an .mbtiles file on the device.  Start collecting a GeoTrace or GeoShape.  Tap the "layers" button on the right and choose your .mbtiles file.  The new basemap should appear.

Now rotate the screen.  Your selected basemap disappears.

#### Expected behavior
The basemap should stay there regardless of whether the screen is rotated.

(See related items: #2310, #2640)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2647 

#### What has been done to verify that this works as intended?
I tested layers using different widgets (`GeoShape`, `GeoTrace`, `GeoPointMap` - it doesn't matter if we use google maps or OSM).

#### Why is this the best possible solution? Were any other approaches considered?
I just use `onSaveInstanceState/onRestoreInstanceState` what is pretty obvious here. Additionally, I implemented a base class in order to remove duplicated code (probably that class could be used to share more code but it's for next prs).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change allows keeping (after screen rotation) a selected layer even if it's different than the one selected in `General Settings`. 
Changing layers should be tested here because it's the functionality that might be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
`All widgets` form is a good one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java [hunk 1]
```diff
@@ -105,19 +105,20 @@ public MapHelper(Context context, MapView osmMap, IRegisterReceiver iregisterRec
...
 
-    private static String getOsmBasemap() {
+    private String getOsmBasemap() {
         return sharedPreferences.getString(PreferenceKeys.KEY_MAP_BASEMAP, OPENMAP_STREETS);
     }
 
     public void setBasemap() {
         if (googleMap != null) {
-            String basemap = getGoogleBasemap();
+            String basemap = selectedLayer == null ? getGoogleBasemap() : offilineOverlays[selectedLayer];
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java]: Make sure this doesn't crash when `selectedLayer` is out of bounds.

File: collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java [hunk 2]
```diff
@@ -140,10 +141,8 @@ public void setBasemap() {
             }
         } else if (osmMap != null) {
             //OSMMAP
-            String basemap = getOsmBasemap();
-
             ITileSource tileSource = null;
-
+            String basemap = selectedLayer == null ? getOsmBasemap() : offilineOverlays[selectedLayer];
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java]: Make sure this doesn't crash when `selectedLayer` is out of bounds.

File: collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java [hunk 3]
```diff
@@ -320,4 +318,8 @@ private boolean isFileFormatSupported(File file) {
         }
         return result;
     }
+
+    public int getSelectedLayer() {
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java:319]: Since `selectedLayer` can be null, this method might crash.  Shouldn't it return an `Integer` instead?

Also, it would be good to add a docstring for this method to explain what this integer is (e.g. "Returns the integer index of (whatever) in (whatever), or null in the case when (whatever).")

**Comment by zestyping** [comment]
Thanks!  I had a look and added a few comments.  Once they're addressed, I think this will be ready for testing.  (@lognaturel I will be away this weekend so I won't be able to tell opendatakit-bot to tag it, but as soon as the comments are addressed I think it's ready and anyone should feel free to tag it.)

**Comment by grzesiek2010** [comment]
@zestyping thanks! I added improvements and added `needs testing` label.

File: collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java [hunk 4]
```diff
@@ -320,4 +310,9 @@ private boolean isFileFormatSupported(File file) {
         }
         return result;
     }
+
+    // returns the index of selected map layer
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java]: Thanks for addressing all the other comments!

I'd still like to suggest that two improvements to this description, though.

1. If you use `/** ... */` instead of `//`, then the comment will be interpreted as JavaDoc for this method.  That means that the description will appear in automatically generated documentation and will pop up automatically in Android Studio when someone hovers over the method or autocompletes it.

2. Because this is a public method, it's better to write this in a way that can be understood by someone who is a user of this class, not an implementor of it.  Someone who doesn't know the implementation won't be able to tell what "index of selected map layer" means—for example, does "index" mean an index into an array?  What is the array?  What does it mean for a map layer to be selected?  Does this imply that there are multiple layers displayed on top of each other?  We should try to write these is such a way as to avoid the possibility of such confusion.  Also, the description is incomplete—this method can return null.  What does it mean when it returns null?

Here's an example of how one might write a description for this method:

    /**
     * If the current basemap is an offline layer, returns the index of the offline
     * layer's filename in the list of all the filenames ending in ".mbtiles" in the
     * Collect.OFFLINE_LAYERS directory; otherwise returns null.
     */

Does that make sense?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java]: Thanks, I added a comment according to your example but with a small modification.
The modification is that I this method can return only numbers, not nulls. Why? because in the array of layers we always keep 'None' option at first place, so 0 means None and offline layers use indexes 1,2...etc. Maybe it's a little bit confusing but it would need more refactoring to change this approach so let's leave it as it is.

**Comment by zestyping** [comment]
Oh I'm really glad you updated the comment to make it correctly reflect
reality, then!  Clearly I misunderstood how it was supposed to work, so
explaining it in the comment helps a lot.  Thank you!

File: collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java (hunk 4 above)
Comment (zestyping) [reply collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java]: Oh I'm really glad you updated the comment to make it correctly reflect
reality, then!  Clearly I misunderstood how it was supposed to work, so
explaining it in the comment helps a lot.  Thank you!

**Comment by kkrawczyk123** [comment]
@grzesiek2010, Offline basemap selectin is lost after screen rotation on Geopoint widget with maps appearance and Geopoint type with placement-map appearance when OSM Map is selected on Androids 4.1, 4.2, 4.4 and 6.0. The issue does not occur on Android 8.1 and I am not able to choose any offline layer on Android 7.0, probably because of https://github.com/opendatakit/collect/issues/2624.

@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@kkrawczyk123 
the problem you have noticed should be fixed. Thanks.

**Comment by kkrawczyk123** [comment]
@grzesiek2010  I confirmed that issue mentioned above has been fixed but I have noticed another one.  I set in user interface settings offline basemap as my default view and I went to geowidgets - I opened Select Offline Layer and it is selected by default which is good and I am not loosing it when rotate screen. But when I choose none option and then rotate the screen - my choice of none is lost. 

@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

@kkrawczyk123 

you can continue testing.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Confirmed that issues have been fixed and also consult with @grzesiek2010 that offline basemap feature needs further improvement that will be added in other pr.
Verified on Androids: 4.2, 4.4, 5.1, 6.0 and 8.1. 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by yanokwa — APPROVED** [review]
Sorry I took so long to merge this!
