### PR TITLE
Disable StrictMode for FormHiearchyActivity

### LINKED ISSUE #6397: View hierarchy with filtered entity selects crashes debug builds
#### ODK Collect version

`master` (365128c) when using a debug build

#### Problem description

There's a StrictMode violation when viewing the hierarchy if there's a filtered entity select on screen (as the hierarchy loads select choices on the UI thread).

#### Steps to reproduce the problem

1. Add a form with filtered selects that uses an entity instance
2. Open the form and navigate to the hierarchy with that question

#### Expected behavior

The app shouldn't crash! 

We'll probably want to add specific StrictMode calls to `DatabaseEntitiesRepository` (like we do with `DatabaseInstancesRepository`) to fix this as the real™️ fix of reworking the hierarchy is probably a focus for another release.

#### Other information 

Stacktrace:

```
java.lang.RuntimeException: StrictMode ThreadPolicy violation
     	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1876)
     	at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1733)
     	at android.os.StrictMode$AndroidBlockGuardPolicy.startHandlingViolationException(StrictMode.java:1704)
     	at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1626)
     	at android.os.StrictMode.noteSlowCall(StrictMode.java:2694)
     	at org.odk.collect.db.sqlite.DatabaseConnection.getReadableDatabase(DatabaseConnection.kt:36)
     	at org.odk.collect.android.database.entities.DatabaseEntitiesRepository.listExists(DatabaseEntitiesRepository.kt:317)
     	at org.odk.collect.android.database.entities.DatabaseEntitiesRepository.getAllByProperty(DatabaseEntitiesRepository.kt:224)
     	at org.odk.collect.entities.javarosa.intance.LocalEntitiesInstanceAdapter.queryEq(LocalEntitiesInstanceAdapter.kt:57)
     	at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.filter(LocalEntitiesFilterStrategy.kt:46)
     	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
     	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:377)
     	at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:343)
     	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:250)
     	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:219)
     	at org.javarosa.xpath.expr.XPathPathExprEval.eval(XPathPathExprEval.java:34)
     	at org.javarosa.xpath.expr.XPathPathExpr.eval(XPathPathExpr.java:213)
     	at org.javarosa.xpath.XPathConditional.evalNodeset(XPathConditional.java:94)
     	at org.javarosa.core.model.ItemsetBinding.getChoices(ItemsetBinding.java:125)
     	at org.javarosa.form.api.FormEntryPrompt.getSelectChoices(FormEntryPrompt.java:222)
     	at org.javarosa.form.api.FormEntryPrompt.getAnswerValue(FormEntryPrompt.java:98)
     	at org.javarosa.form.api.FormEntryPrompt.getAnswerText(FormEntryPrompt.java:154)
     	at org.odk.collect.android.formhierarchy.QuestionAnswerProcessor.getQuestionAnswer(QuestionAnswerProcessor.kt:28)
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.refreshView(FormHierarchyActivity.java:672)
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.refreshView(FormHierarchyActivity.java:591)
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.onCreate(FormHierarchyActivity.java:278)
     	at android.app.Activity.performCreate(Activity.java:8054)
     	at android.app.Activity.performCreate(Activity.java:8034)
     	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
     	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
     	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
     	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
     	at android.os.Handler.dispatchMessage(Handler.java:106)
     	at android.os.Looper.loopOnce(Looper.java:201)
     	at android.os.Looper.loop(Looper.java:288)
     	at android.app.ActivityThread.main(ActivityThread.java:7870)
     	at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.strictmode.CustomViolation: Accessing readable DB
     	at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1626) 
     	at android.os.StrictMode.noteSlowCall(StrictMode.java:2694) 
     	at org.odk.collect.db.sqlite.DatabaseConnection.getReadableDatabase(DatabaseConnection.kt:36) 
     	at org.odk.collect.android.database.entities.DatabaseEntitiesRepository.listExists(DatabaseEntitiesRepository.kt:317) 
     	at org.odk.collect.android.database.entities.DatabaseEntitiesRepository.getAllByProperty(DatabaseEntitiesRepository.kt:224) 
     	at org.odk.collect.entities.javarosa.intance.LocalEntitiesInstanceAdapter.queryEq(LocalEntitiesInstanceAdapter.kt:57) 
     	at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.filter(LocalEntitiesFilterStrategy.kt:46) 
     	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382) 
     	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:377) 
     	at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:343) 
     	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:250) 
     	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:219) 
     	at org.javarosa.xpath.expr.XPathPathExprEval.eval(XPathPathExprEval.java:34) 
     	at org.javarosa.xpath.expr.XPathPathExpr.eval(XPathPathExpr.java:213) 
     	at org.javarosa.xpath.XPathConditional.evalNodeset(XPathConditional.java:94) 
     	at org.javarosa.core.model.ItemsetBinding.getChoices(ItemsetBinding.java:125) 
     	at org.javarosa.form.api.FormEntryPrompt.getSelectChoices(FormEntryPrompt.java:222) 
     	at org.javarosa.form.api.FormEntryPrompt.getAnswerValue(FormEntryPrompt.java:98) 
     	at org.javarosa.form.api.FormEntryPrompt.getAnswerText(FormEntryPrompt.java:154) 
     	at org.odk.collect.android.formhierarchy.QuestionAnswerProcessor.getQuestionAnswer(QuestionAnswerProcessor.kt:28) 
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.refreshView(FormHierarchyActivity.java:672) 
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.refreshView(FormHierarchyActivity.java:591) 
     	at org.odk.collect.android.formhierarchy.FormHierarchyActivity.onCreate(FormHierarchyActivity.java:278) 
     	at android.app.Activity.performCreate(Activity.java:8054) 
     	at android.app.Activity.performCreate(Activity.java:8034) 
     	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688) 
     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
     	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
     	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
     	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
     	at android.os.Handler.dispatchMessage(Handler.java:106) 
     	at android.os.Looper.loopOnce(Looper.java:201) 
     	at android.os.Looper.loop(Looper.java:288) 
     	at android.app.ActivityThread.main(ActivityThread.java:7870) 
     	at java.lang.reflect.Method.invoke(Native Method) 
     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6397

#### Why is this the best possible solution? Were any other approaches considered?

While working on this, I discovered that we'd accidentally disabled StrictMode protection for `DatabaseEntitiesRepository`. Fortunately, it doesn't seem like we'd added any violations as I was able to add it back in without problems (other than the expected ones).

I'd initially thought about removing the blanket protection on the whole repository and just adding custom slow calls to some methods, but I realised I'd have to remove protection on pretty much all the `get...` methods to allow for different kinds of filters in the hierarchy. 

Instead, I've gone for an approach where StrictMode is disabled when the `FormHierarchyActivity` is created and then re-enabled when it is destroyed. This means we get full protection elsewhere, and only the "broken" code will have to change when we fix it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't affect users at all as the crashes/errors were only visible in debug. No need for testing here.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java [hunk 1]
```diff
@@ -924,4 +927,11 @@ public void deleteGroup() {
             goUpLevel();
         }
     }
+
+    @Override
+    protected void onDestroy() {
+        super.onDestroy();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java]: I think it is generally recommended to call `super.onDestroy()` after other operations in onDestroy() and that's what we do in other activities.

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java [hunk 2]
```diff
@@ -924,4 +927,11 @@ public void deleteGroup() {
...
+
+        CollectStrictMode.enable();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: Is this a temporary solution? If so should we file an issue to fix it in the future?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: I've added an issue: https://github.com/getodk/collect/issues/6470

**Review by grzesiek2010 — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java (hunk 2 above)
Comment (GustavoBeretta) [reply collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: Why was this undone in the [refactoring to FormHierarchyFragmentHostActivity](https://github.com/getodk/collect/commit/3a9bc6f02a6342ca48817659322a6d45dc21de59)?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: Not sure that was an intentional change. Although, it's desirable to have `StrictMode` enabled if we can. Are you running into problems with it?

Comment (GustavoBeretta) [reply collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: Yes, the same problem as #6397. This workaround solves it, but I just wanted to check if any issues were found later.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java:933]: Definitely best to avoid using the workaround if possible! That's especially the case if a violation is occurring due to new code (in a fork I'm assuming). Disabling `StrictMode` here was added to handle very old code that we're progressively rewriting, but new code should be written to avoid these issues from the get-go.
