### PR TITLE
Adjust snackbar position when keyboard is shown

### LINKED ISSUE #7184: Toast informing about background location tracking is hidden under keyboard
#### ODK Collect version
the master version 4c16cc8cb93b7acb121c40786d10c907445307f9
(the issue doesn’t occur in the store version 2026.1.2)
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In a form which tracks location in the background toasts informing about the tracking location being enabled/disabled are hidden under the keyboard.

https://github.com/user-attachments/assets/f7b9019b-b4ca-4701-bea5-76e58e085940

#### Steps to reproduce the problem
1. Open the form (if necessary open the form twice if there was location permission dialog – keyboard won’t be dispalyed).
[AuditTest.xml.txt](https://github.com/user-attachments/files/26778551/AuditTest.xml.txt)
2. Check where the toast is.
#### Expected behavior
In the store version the toast is over the keyboard, above action buttons.
#### Other information
You can disable tracking location in the form in the menu. If you reopen the form, there's the second toast (enabled/disabled location tracking).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #7184

#### Why is this the best possible solution? Were any other approaches considered?
The solution is consistent with how we handle bottom bars. There is nothing more to discuss.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should only affect how snackbars are displayed, so we can focus on this aspect. Nothing else should be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form is linked in the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/EdgeToEdge.kt [hunk 1]
```diff
@@ -41,17 +42,26 @@ object EdgeToEdge {
...
+    @JvmStatic
+    fun Snackbar.applyBottomInsets() {
+        ViewCompat.setOnApplyWindowInsetsListener(view) { _, windowInsets ->
+            view.translationY = -windowInsets.keyboardOffset().toFloat()
             windowInsets
         }
+        ViewCompat.requestApplyInsets(view)
+    }
+
+    private fun WindowInsetsCompat.keyboardOffset(): Int {
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/ui/EdgeToEdge.kt:61]: I think it's a little surprising that this also incorporates the system bars. Maybe it could be named `keyboardSafeOffset`?

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- issue #7184 doesn't occur
- the snackbar when tracking location is on and off in the form
- the snackbar with a different keyboards (floating keyboard etc)
- navigation using swipes and buttons and only swipes
- the snackbar in a question which doesn't open keyboard

**Comment by WKobus** [comment]
**tested with success!**

Verified on phone and tablet with Android 16
