### PR TITLE
Use the same location providers in every map engine + some tweaks

### LINKED ISSUE #5633: Maps unable to set location/ loading takes too much time after switching from Mapbox
#### ODK Collect version
2023.1.1, the store version 2023.1.2
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A23
#### Problem description
After switching from Mapbox to any other source of maps the time of searching for location on a map (e.g. in geopoint with map appearance) is too long. I’m not sure what are the factor causing that but the time varies from 30 sec to 5 minutes.
#### Steps to reproduce the problem
1. Google maps are set in project settings
2. Go to All widgets any Geo widget with maps – check if the map zooms to the location (in reasonable time).
3. Go to project settings and change the Basemap source to Mapbox.
4. Go to All widgets any Geo widget with maps – check if the map zooms to the location.
5. Go to project settings and change the Basemap to any other source (Google, OSM, Carto etc.)
6. Go to All widgets any Geo widget with maps – check if the map zooms to the location.
#### Expected behavior
The maps should set location in reasonable time

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5633 

#### What has been done to verify that this works as intended?
I've tested manually the map engines we support.

#### Why is this the best possible solution? Were any other approaches considered?
The fix itself is in the first commit [Use the same location providers in all map engines
](https://github.com/getodk/collect/pull/5636/commits/092075aca098c1ea6a00768286bacc8a7fc92a34). As discussed on slack the problem was that mapbox used its own location engine but google and osm our own providers. As a result, the mapbox engine messed up somehow with our providers (internally). Now all map engines use the same mechanism to retrieve the location and thanks to that mapbox works well and the behavior is consistent.

Other commits are just some improvements that I've identified:
- [Removed duplicated GPS checking](https://github.com/getodk/collect/pull/5636/commits/afeece2b58ad5f21072353a8720c3ce013e39c48) this is something we check before starting maps so it's not needed in every map fragment too
- [Removed duplicated stopLocationUpdates call
](https://github.com/getodk/collect/pull/5636/commits/a2a57b04a6415bee698e11898936ef948d00f57c) `stopLocationUpdates` is already called in `GoogleFusedLocationClient`/`AndroidLocationClient`#stop() 
- [Do not ignore the first received location
](https://github.com/getodk/collect/pull/5636/commits/d6a63e42b76909c7f886d5ee8839f822a59c3fc1) I don't know why the first location was ignored. As a result, zooming to the current location in `GeoPointMapActivity` was slower compared to `GeoPolyActivity` it was an old fragment of code so I believe it is something we do not need anymore.
- [Track if GPS connection fails and why
](https://github.com/getodk/collect/pull/5636/commits/92f036c99d4ceacc11f96561d02bb7c41bdaa3fb) just wanted to check if there are problems with connections and why. Maybe we need to display something ins such a case? We will see. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should solve the problem with switching map engines and also make the behavior across different engines consistent. There is no one particular area of risk but it ould be more about recording locations than drawing lines/shapes/points for example.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java [hunk 1]
```diff
@@ -196,6 +198,7 @@ public void onConnectionSuspended(int cause) {
 
     @Override
     public void onConnectionFailed(@NonNull ConnectionResult connectionResult) {
+        Analytics.log("GoogleFusedLocationClient", "onConnectionFailed", connectionResult.toString());
```
Comment (seadowg) [inline location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java]: We'd need to add `onConnectionFailed` as a custom dimension to events in Firebase for this. I'm also a little worried about logging the `connectionResult` in case it contains a device identifier (or anything that could be PII).

Instead, could we just log a simple event like `GoogleFustLocationClientConnectionFailed`? That said, is this even something we have a question about? I'm not sure we're looking to track this at the moment.

**Review by seadowg — CHANGES_REQUESTED** [review]
So many good changes here! I want to discuss the included analytics, but nothing should block this from going to QA.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:

- Issue #5633 is no longer reproducing; 
- Google Maps, Mapbox, OSM, use offline layer 
- Regression checks on geowidgets, background location
- Screen rotation, minimize app, using backward button

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

File: location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java (hunk 1 above)
Comment (grzesiek2010) [reply location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java]: > I'm also a little worried about logging the connectionResult in case it contains a device identifier

> Instead, could we just log a simple event like GoogleFustLocationClientConnectionFailed? That said, is this even something we have a question about?

I wanted to know not only how often it happens but if the result contains something important to display to a user.

Comment (grzesiek2010) [reply location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java]: but I don't have strong feelings about it so I'm ok with just checking if this takes place at all and then deciding if we need to determine the reason or just display something.

**Review by seadowg — APPROVED** [review]
