### PR TITLE
Reuse the last generated QR Code if the settings have not changed

### LINKED ISSUE #1879: QRCode shouldn't be regenerated if the settings haven't changed
#### Software and hardware versions 
Collect v1.12

#### Problem description
QRCode is generated every time, even if the settings have not changed. 

#### Steps to reproduce the problem
Goto `Admin Settings` > `Import/Export Settings`

#### Expected behavior
The last generated QRCode should be cached in the sd-card and used if the settings have not changed since the last generated time.

@opendatakit-bot claim

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #1879

#### What has been done to verify that this works as intended?
Tried running manually in physical device (android 7.0) and behavior found correct.

#### Why is this the best possible solution? Were any other approaches considered?
This is the only approach I considered.

#### Are there any risks to merging this code? If so, what are they?
Yes, the behavior of import/exporting settings might be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Looking.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 1]
```diff
@@ -148,6 +150,19 @@ public static String getMd5Hash(File file) {
         return getMd5Hash(is);
     }
 
+    public static String getMd5Hash(String message) throws NoSuchAlgorithmException {
+        MessageDigest md = MessageDigest.getInstance("MD5");
+        md.reset();
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: No need to reset here.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 2]
```diff
@@ -504,4 +519,27 @@ public static Bitmap getBitmap(String path, BitmapFactory.Options originalOption
...
+        } catch (IOException e) {
+            Timber.e(e);
+        }
+        return sb.toString();
+    }
+
+    public static void writeToFile(File file, String message, boolean append) {
+        try (FileOutputStream overWrite = new FileOutputStream(file, append)) {
+            overWrite.write(message.getBytes());
+            overWrite.flush();
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: No need for flush right before close

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 3]
```diff
@@ -102,15 +102,12 @@ public static File saveBitmapToCache(Bitmap qrCode) throws IOException {
     }
 
     public static Bitmap generateQRBitMap(Collection<String> keys) {
-        String content;
         try {
-            SharedPreferencesUtils obj = new SharedPreferencesUtils();
-            content = obj.getJSONFromPreferences(keys);
-            String compressedData = CompressionUtils.compress(content);
+            String jsonObject = SharedPreferencesUtils.getJSONFromPreferences(keys);
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: This comment has nothing to do with this line of code. It’s something at the top of the file that I dislike because it adds no value and takes up space. The information it provides is present in version control. I’m bugged that JetBrains created this default template. Here it is:
```
/**
 * Created by shobhit on 13/4/17.
 */
```

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 4]
```diff
@@ -60,21 +59,27 @@
...
-import static org.odk.collect.android.utilities.QRCodeUtils.saveBitmapToCache;
 
 
-public class ShowQRCodeFragment extends Fragment implements View.OnClickListener, QRCodeListener {
+public class ShowQRCodeFragment extends Fragment implements View.OnClickListener {
 
     private static final int SELECT_PHOTO = 111;
-    private boolean[] checkedItems = new boolean[]{true, true};
+    private static final int QR_CODE_WIDTH = 400; // in pixels
+    private static final int QR_CODE_HEIGHT = 400; // in pixels
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: If these are always square, consider making the constant QR_CODE_SIDE_LENGTH, or at least set one of WIDTH and HEIGHT equal to the other, rather than duplicating the 400.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 5]
```diff
@@ -91,50 +87,27 @@ private static BinaryBitmap getBinaryBitmap(Bitmap bitmap) {
...
-            content = obj.getJSONFromPreferences(keys);
-            String compressedData = CompressionUtils.compress(content);
-
-            //Maximum capacity for QR Codes is 4,296 characters (Alphanumeric)
-            if (compressedData.length() > 4000) {
-                ToastUtils.showLongToast(Collect.getInstance().getString(R.string.encoding_max_limit));
-                Timber.e(Collect.getInstance().getString(R.string.encoding_max_limit));
-                return null;
-            }
+    public static Bitmap generateQRBitMap(String data, int width, int height) throws IOException, WriterException {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: Squares don’t need separate width and height, right?

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 6]
```diff
@@ -93,17 +100,83 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
+        compositeDisposable.add(disposable);
+    }
+
+    @Override
+    public void onDestroy() {
+        compositeDisposable.dispose();
+        super.onDestroy();
+    }
+
+    private Observable<Bitmap> getQRCodeGeneratorObservable() {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Am I correct that we want to separate UI code and business logic where we can? Should the large code block be in this class?

File: collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java [hunk 7]
```diff
@@ -43,7 +43,7 @@
 
     private final Context context = Collect.getInstance();
 
-    String getJSONFromPreferences(Collection<String> keys) throws JSONException {
+    public static String getJSONFromPreferences(Collection<String> keys) throws JSONException {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java]: This comment is not related to this PR, but I’ll make it anyway. I don’t like that the `keys` collection (a method parameter) is modified (by having all the general keys added to it). It could have a better name, like “additionalKeys” or “passwordKeys” or something, and its elements could be added to a separate collection created inside the method.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 8]
```diff
@@ -148,6 +150,19 @@ public static String getMd5Hash(File file) {
         return getMd5Hash(is);
     }
 
+    public static String getMd5Hash(String message) throws NoSuchAlgorithmException {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: This method will shorten to:
```
    public static String getMd5Hash(String message) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(message.getBytes());
        StringBuilder builder = new StringBuilder();
        for (byte b : md.digest()) {
            builder.append(String.format("%02x", b));
        }
        return builder.toString();
    }
```

But instead I suggest you consider using the new DigestAlgorithm we just added to JavaRosa.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
This looks like a nice improvement. Here is my first round of comments.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Thank you @dcbriccetti 
Silly me!

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 8 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Thanks for letting us know! I'll try the `DigestAlgorithm` from `Javarosa`.
Btw, I also really liked the reduced `getMd5Hash()` function.

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: The `Encoding` enum in javarosa is not public. So, I cannot use it directly for encoding. I tried out the below line use the javarosa's algorithm. 

```
String md5Hash = DigestAlgorithm.MD5.digest(message, Encoding.HEX);
```

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java (hunk 4 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Makes sense

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java (hunk 5 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: :+1:

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java (hunk 6 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: In QRCodeUtils?

File: collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java (hunk 7 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java]: Does this look fine to you? 

```
public static String getJSONFromPreferences(Collection<String> passwordKeys) throws JSONException {
        Collection<String> keys = new ArrayList<>(GENERAL_KEYS.keySet());
        keys.addAll(passwordKeys);
        JSONObject sharedPrefJson = getModifiedPrefs(keys);
        Timber.i(sharedPrefJson.toString());
        return sharedPrefJson.toString();
    }
```

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 2 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: :+1:

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java (hunk 6 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Maybe so.

File: collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java (hunk 7 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java]: Much better. Thanks. That changes the order from before (adding password keys to general rather than the other way around), but perhaps the order doesn’t matter.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 8 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: I’ve had second thoughts about using JavaRosa for that. I no longer think JavaRosa should share that.

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Yeah I saw your comment on #general channel and currently I'm trying out the apache commons lib

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]:
```
    public static String getMd5Hash(String message) {
        DigestUtils digestUtils = new DigestUtils("MD5");
        StringBuilder builder = new StringBuilder();
        for (byte b : digestUtils.digest(message)) {
            builder.append(String.format("%02x", b));
        }
        return builder.toString();
    }
```

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Doesn’t it have a method to do the hex encoding, too?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Or even just `DigestUtils.md5Hex(message)`

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: That’s what I was thinking of.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 9]
```diff
@@ -504,4 +519,26 @@ public static Bitmap getBitmap(String path, BitmapFactory.Options originalOption
 
         return bitmap;
     }
+
+    public static String readFile(File file) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Did you consider not hex encoding the digests, but simply writing the byte arrays as binary files?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: No I didn't but seems like a great idea! I will definitely try it out

**Comment by shobhitagarwal1612** [comment]
@dcbriccetti Done

**Comment by dcbriccetti** [comment]
Thanks for those changes. I’ll continue with phase 2 probably later today.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 10]
```diff
@@ -520,23 +505,23 @@ public static Bitmap getBitmap(String path, BitmapFactory.Options originalOption
...
-        StringBuilder sb = new StringBuilder();
-        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
-            String line;
-            while ((line = br.readLine()) != null) {
-                sb.append(line).append('\n');
-            }
+    public static byte[] read(File file) {
+        byte[] getBytes = {};
+        try {
+            getBytes = new byte[(int) file.length()];
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: This identifier should be a noun, don’t you think? Maybe `bytes`, or `contents`?

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 11]
```diff
@@ -149,32 +149,26 @@ private void updateShareIntent() {
...
-                Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
-                photoPickerIntent.setType("image/*");
-                startActivityForResult(photoPickerIntent, SELECT_PHOTO);
-                break;
-
-            case R.id.tvPasswordWarning:
-                showAlertDialog();
-                break;
-        }
+    @OnClick(R.id.btnScan)
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: I like removing the switch and cases

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 12]
```diff
@@ -36,48 +37,40 @@
...
+import io.reactivex.Observable;
 import timber.log.Timber;
 
-/**
- * Created by shobhit on 13/4/17.
- */
 
 public class QRCodeUtils {
+    public static final String QR_CODE_FILEPATH = Collect.SETTINGS + File.separator + "collect-settings.jpeg";
+    static final String MD5_CACHE_PATH = Collect.SETTINGS + File.separator + ".md5";
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: Maybe we should have a more descriptive name for the QR Code MD5 hash than “.md5”.

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: How about `.collect-settings-hash`?

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: Works for me.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 13]
```diff
@@ -36,48 +37,40 @@
...
 
+import io.reactivex.Observable;
 import timber.log.Timber;
 
-/**
- * Created by shobhit on 13/4/17.
- */
 
 public class QRCodeUtils {
+    public static final String QR_CODE_FILEPATH = Collect.SETTINGS + File.separator + "collect-settings.jpeg";
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: Are we saving a QR Code image as a JPEG? Is JPEG the right compression format for this type of image? I should think PNG would be better.

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: :+1:

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java (hunk 12 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: :+1:

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 14]
```diff
@@ -91,50 +84,88 @@ private static BinaryBitmap getBinaryBitmap(Bitmap bitmap) {
...
+                // Save the QRCode to disk
+                if (shouldWriteToDisk) {
+                    Timber.i("Saving QR Code to disk... : " + QR_CODE_FILEPATH);
+                    FileUtils.saveBitmapToFile(bitmap, QR_CODE_FILEPATH);
 
-            for (int x = 0; x < width; x++) {
-                for (int y = 0; y < height; y++) {
-                    bmp.setPixel(x, y, bitMatrix.get(x, y) ? Color.BLACK : Color.WHITE);
+                    // update .md5 file
+                    Timber.i("Updated .md5 file contents");
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: When you rename the .md5 file, how about using some constant part of it here, so the file name will always match?

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 15]
```diff
@@ -91,50 +84,88 @@ private static BinaryBitmap getBinaryBitmap(Bitmap bitmap) {
...
+            // If the file is not found in the disk or md5Hash not matched
+            if (bitmap == null) {
+                Timber.i("Generating QRCode...");
+                bitmap = generateQRBitMap(preferencesString, QR_CODE_SIDE_LENGTH);
+                shouldWriteToDisk = true;
+            }
 
-            int width = bitMatrix.getWidth();
-            int height = bitMatrix.getHeight();
+            if (bitmap != null) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: This could be `else`.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java (hunk 13 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: I wonder if these blurry edges are JPEG compression artifacts. Let’s look again after you change to PNG.

screen shot 2018-02-26 at 10 02 15 pm

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 16]
```diff
@@ -91,50 +84,88 @@ private static BinaryBitmap getBinaryBitmap(Bitmap bitmap) {
...
+
+        // Maximum capacity for QR Codes is 4,296 characters (Alphanumeric)
+        if (compressedData.length() > 4000) {
+            throw new IOException(Collect.getInstance().getString(R.string.encoding_max_limit));
+        }
+
+        Map<EncodeHintType, ErrorCorrectionLevel> hints = new HashMap<>();
+        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
+        QRCodeWriter qrCodeWriter = new QRCodeWriter();
+        BitMatrix bitMatrix = qrCodeWriter.encode(compressedData, BarcodeFormat.QR_CODE, sideLength, sideLength, hints);
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java:100]: This takes almost ten seconds on my Nexus 7. Are we doing whatever we can to get good performance?

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 17]
```diff
@@ -117,72 +139,54 @@ private void addPasswordStatusString() {
...
 
-    private void updateShareIntent(Bitmap qrCode) throws IOException {
-
-        // Send an intent to share saved image
+    private void updateShareIntent() {
+        // Initialize the intent to share qr code
         shareIntent = new Intent();
         shareIntent.setAction(Intent.ACTION_SEND);
         shareIntent.setType("image/*");
+        shareIntent.putExtra(Intent.EXTRA_STREAM, Uri.parse("file://" + QR_CODE_FILEPATH));
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: How can we test this?

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 18]
```diff
@@ -117,72 +139,54 @@ private void addPasswordStatusString() {
...
         }
-        editQRCode.setText(status);
+        tvPasswordWarning.setText(status);
     }
 
-    private void updateShareIntent(Bitmap qrCode) throws IOException {
-
-        // Send an intent to share saved image
+    private void updateShareIntent() {
+        // Initialize the intent to share qr code
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: `qr` should probably be `QR`. Interesting that the patent calls it “QR code”, but the Denso web site, http://www.qrcode.com/en/history/, calls it “QR Code”.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
There’s phase 2 of my review. Thanks for addressing everything in phase 1. I’ll have probably one more phase.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java (hunk 16 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java:100]: 1. We are using the lowest  `ErrorCorrectionLevel` while creating the QRBitmap.
2. Preferences are compressed using deflate to reduce the size of content

On Redmi note 4,  it took a few hundred milliseconds for encoding default settings to QR Code

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java:100]: Device : Nexus 5

```
{"general":{"showSplash":true,"metadata_email":"coffee@thing. huh","image_size":"large","instance_sync":false,"map_sdk_behavior":"osmdroid","delete_send":true,"protocol":"google_sheets","metadata_phonenumber":"599","default_completed":false,"map_basemap_behavior":"openmap_cartodb_darkmatter","font_size":"25","navigation":"buttons","app_language":"en","selected_google_account":"snapdragon.tonbo@gmail.com","metadata_username":"can","autosend":"wifi_and_cellular","analytics":false,"high_resolution":false},"admin":{"change_server":false,"change_form_metadata":false,"change_font_size":false,"change_app_language":false,"default_to_finalized":false,"high_resolution":false,"image_size":false,"show_splash_screen":false,"delete_after_send":false,"instance_form_sync":false,"change_autosend":false,"change_navigation":false,"change_constraint_behavior":false,"show_map_sdk":false,"show_map_basemap":false,"analytics":false,"edit_saved":false,"send_finalized":false,"view_sent":false,"get_blank":false,"delete_saved":false,"save_mid":false,"jump_to":false,"change_language":false,"access_settings":false,"save_as":false,"mark_as_finalized":false,"moving_backwards":false,"allow_other_ways_of_editing_form":false}}
```
QR Code generation took : 3487 ms

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 19]
```diff
@@ -143,7 +143,7 @@ private void addPasswordStatusString() {
     }
 
     private void updateShareIntent() {
-        // Initialize the intent to share qr code
+        // Initialize the intent to share QRCode
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Isn’t it QR Code or QR code (with a space)?

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 20]
```diff
@@ -466,20 +466,10 @@ public static void moveMediaFiles(String tempMediaPath, File formMediaPath) thro
     }
 
     public static void saveBitmapToFile(Bitmap bitmap, String path) {
-        FileOutputStream out = null;
-        try {
-            out = new FileOutputStream(path);
+        try (FileOutputStream out = new FileOutputStream(path)) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: That’s nice and clean.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java (hunk 16 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java:100]: OK. Thanks for checking.

File: collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java [hunk 21]
```diff
@@ -55,9 +55,10 @@
 
 
 public class QRCodeUtils {
-    public static final String QR_CODE_FILEPATH = Collect.SETTINGS + File.separator + "collect-settings.jpeg";
-    static final String MD5_CACHE_PATH = Collect.SETTINGS + File.separator + ".md5";
+    public static final String QR_CODE_FILEPATH = Collect.SETTINGS + File.separator + "collect-settings.png";
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: Is it enough to simply change the file extension to “png”?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java]: I am not sure. Let me check this

**Comment by shobhitagarwal1612** [comment]
@dcbriccetti Fixed!

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 22]
```diff
@@ -465,9 +465,14 @@ public static void moveMediaFiles(String tempMediaPath, File formMediaPath) thro
         }
     }
 
-    public static void saveBitmapToFile(Bitmap bitmap, String path) {
+    public static void saveBitmapToFile(Bitmap bitmap, String path, Bitmap.CompressFormat... format) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Sorry I didn’t think of this before. Let’s derive the JPEG or PNG from the filename.

**Comment by dcbriccetti** [comment]
Interesting! I’m still seeing that lack of “crispness” now that we’ve switched from JPEG to PNG. Perhaps it’s not due to JPEG compression, but due to anti-aliasing in the QR Code generation. It’s a moot point: It was still the right thing to do to use PNG.

File: collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java [hunk 23]
```diff
@@ -0,0 +1,138 @@
...
+import static org.junit.Assert.assertNull;
+import static org.junit.Assert.assertTrue;
+import static org.odk.collect.android.utilities.QRCodeUtils.MD5_CACHE_PATH;
+import static org.odk.collect.android.utilities.QRCodeUtils.QR_CODE_FILEPATH;
+
+
+@RunWith(RobolectricTestRunner.class)
+public class QRCodeUtilsTest {
+
+    private final File savedFile = new File(QR_CODE_FILEPATH);
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java]: A more descriptive name? `savedQrCodeImage`, maybe? (Note the lowercase r in Qr. All these types (like `QRCodeUtilsTest`) should contain Qr instead of QR, but I’m not suggesting we change them now.)

File: collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java [hunk 24]
```diff
@@ -0,0 +1,138 @@
...
+    }
+
+    @Test
+    public void generateAndDecodeQRCode() throws IOException, WriterException, DataFormatException, ChecksumException, NotFoundException, FormatException {
+        String data = "Some random text";
+        Bitmap generatedQRBitMap = QRCodeUtils.generateQRBitMap(data, 100);
+        assertQRContains(generatedQRBitMap, data);
+    }
+
+    @Test
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java:54]: May I offer the following, to remove some code duplication?
https://github.com/dcbriccetti/collect/commit/02fb892187e5e5ed6a504172ae7bcd060a9447c5

**Comment by dcbriccetti** [comment]
None of my Android devices seems to consistently capture a QR Code, so I won’t be able to test that part of this. Let’s make sure that capturing a code and pressing save actually sets the correct values in the preferences.

File: collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java (hunk 23 above)
Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java]: Done

File: collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java (hunk 24 above)
Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java:54]: Thanks!

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 22 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: done

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 25]
```diff
@@ -465,10 +465,12 @@ public static void moveMediaFiles(String tempMediaPath, File formMediaPath) thro
...
-    public static void saveBitmapToFile(Bitmap bitmap, String path, Bitmap.CompressFormat... format) {
-        Bitmap.CompressFormat compressFormat = Bitmap.CompressFormat.JPEG;
-        if (format[0] != null) {
-            compressFormat = format[0];
+    public static void saveBitmapToFile(Bitmap bitmap, String path) {
+        Bitmap.CompressFormat compressFormat;
+        if (path.endsWith(".png")) {
+            compressFormat = Bitmap.CompressFormat.PNG;
+        } else {
+            compressFormat = Bitmap.CompressFormat.JPEG;
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: These 5 lines could be on 1 line, and support mixed case in the file extension.
`final Bitmap.CompressFormat compressFormat = path.toLowerCase.endsWith(".png") ? ...`

**Review by dcbriccetti — APPROVED** [review]
I’m unable to verify that photographing a QR Code and pushing Save still correctly updates preferences, but if someone else tests that, I am comfortable with this code.

**Comment by shobhitagarwal1612** [comment]
> I’m unable to verify that photographing a QR Code and pushing Save still correctly updates preferences, but if someone else tests that, I am comfortable with this code.

@dcbriccetti I have added a test to verify that the QrCode updates the shared preferences as expected

**Comment by dcbriccetti** [comment]
Great! Ready for QA testing.

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 
**Regression has been found!**

Android version: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

**Steps to reproduce:** 
1. User choose `Select code from other device`
2. User scans QR code
3. User is moved to `Import/Export settings` view

**Current behavior:**
Settings from scanned QR code are not set.
 
**Expected behavior:**
User is moved to main view and settings are set according to QR code

@opendatakit-bot unlabel "needs testing"

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 Fixed. 
The reason was that I forgot to decompress the string from the scanned QR code image.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

Verified cases: 
* generate QRcode with and without Admin password
* generate QRcode with and without server password
* delete odk/settings folder or content of this folder
* scan code from other device
* select code from SD card
* load saved settings file
* reseting the settings removes the content in odk/settings folder

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
