### PR TITLE
Difference between cascading select loaded from an external file and …

### LINKED ISSUE #350: Difference between cascading select loaded from an external file and cs loaded from a form file
#### Software and hardware versions 
Discovered on Collect v1.4.12, Android v5.0.1, Samsung Galaxy S4

#### Problem description
There is a difference between cascading select loaded from an external file and cs loaded from a form file. 
In first case it works worse. We can't see dividers and user is able to select an option taping on a radio button or text (not on white free space next to a question).

#### Steps to reproduce the problem
1. Use a survey with cascading select (loaded from an external file - eg. https://opendatakit.org/wp-content/uploads/2013/11/external_itemsets_example.zip)
2. Go to second cs screen (on the first screen it works well as the first cs level is always loaded form a form file and then we use SelectOneWidget).

#### Expected behavior
Cs should work the same way in both cases. We should improve ItemsetWidget.

screenshot_2017-01-22-23-48-56

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #350

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java [hunk 1]
```diff
@@ -101,7 +99,7 @@ protected ItemsetWidget(Context context, FormEntryPrompt prompt, boolean readOnl
         // more
         // must include the spaces in indexOf so we don't match words like
         // "land"
-        int andIndex = -1;
+        int andIndex;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java]: I know it's super tempting to restructure some of this code but it makes it harder to review! Plus, in this case, `orIndex` is set up in the same way and I think it's more confusing when they don't match.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java [hunk 2]
```diff
@@ -234,46 +238,68 @@ protected ItemsetWidget(Context context, FormEntryPrompt prompt, boolean readOnl
...
+                        mButtons.add(rb);
+
                         // have to add it to the radiogroup before checking it,
                         // else it lets two buttons be checked...
                         if (currentAnswer != null
                                 && val.compareTo(currentAnswer) == 0) {
                             rb.setChecked(true);
                         }
+
+                        MediaLayout mediaLayout = new MediaLayout(getContext(), mPlayer);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java]: Can this just be a `RelativeLayout` since there is no possible media for now? Even if this must use a `MediaLayout` for some reason, it doesn't make sense to set the audio listener, play text color, etc.

**Review by lognaturel — CHANGES_REQUESTED** [review]
One question inline about `MediaLayout`. Looks good. In general, it's good to keep PRs as focused as possible. If you see some light refactoring you want to do, please do that work in a different branch and submit as a different PR!

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java]: Ok I removed this commit

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java]: Right. FIxed

**Comment by lognaturel** [comment]
Great, thanks! Same comment as on #340, it's more helpful to have the full commit history. I squash and merge when it's a relatively atomic change but having the individual commits really helps with any future troubleshooting that could need to happen.
