### PR TITLE
Make sure screen reloads when preferences are changed

### LINKED ISSUE #4212: Changes in audio recorders in experimental settings are not applied immediately when user sets it in the middle of the form
### Software and hardware versions 
Collect master

#### Problem description
Changes in audio recorders in experimental settings are not applied immediately when user sets it in the middle of the form.

#### Steps to reproduce the problem
1. User starts form
2. User opens audio widget -> external recorder is opened
3. User opens `General Settings` in the middle of form
4. User goes to `Experimenta` settings
5. User unselects using an external app
6. User backs to the form and opens audio widget
7. External recorder is opened -> changes is settings wasn't applied

#### Expected behavior
The internal recorder is visible.
Changes in audio recorders are applied immediately even if user sets it in the middle of the form.

#### Notes
Related to #4190

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4212 

#### What has been done to verify that this works as intended?

New test and verified manually. There is one piece of tested code - comments inline.

#### Why is this the best possible solution? Were any other approaches considered?

I think it made sense to handle this generally rather than worrying about it for any new feature in form entry that can be configured.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The form "screen" will now reload whenever the user navigates to settings and back. It'd be good to check this doesn't create any problems (answers not retained for instance) and that there aren't any significant performance problems introduced.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -762,7 +762,7 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
 
         // If we're coming back from the hierarchy view, the user has either tapped the back
         // button or another question to jump to so we need to rebuild the view.
-        if (requestCode == RequestCodes.HIERARCHY_ACTIVITY) {
+        if (requestCode == RequestCodes.HIERARCHY_ACTIVITY || requestCode == RequestCodes.CHANGE_SETTINGS) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:761]: This isn't tested. I played around with various Espresso tests but couldn't get something that worked nicely and actually drove this out. We still consider `FormEntryActivity` a no-go for Robolectric testing, so I didn't even look at that. 

The new [Activity Result APIs](https://developer.android.com/training/basics/intents/result) are really the answer here I think, but they are still in beta. Once that's stable we should be able to move our activity result code into components (like `FormEntryMenuDelegate`) and test the request and "response" in one place.

Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:761]: Can we do the same for font size? Probably we don't even need adjustFontSize() now if we call onScreenRefresh(); either way. Do you want to confirm? If you are in a hurry with this pr we can file a separate issue to make sure changes in settings are handled in the same way.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:761]: Sounds like a good idea! Just to confirm: you're suggesting we get rid of the code that's dealing with the font size adjustment and see if this new solution works instead?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:761]: Yeah I guess it should because basically it does the same just calling onScreenRefresh();

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Tested on Android 7.0, 8.1, 10.0

Verified cases:
- All settings in `General Settings`
- Theme and language work as before
- Guidance setting works immediately :+1: 
- `Default to finalized` setting is applied even if user opens General settings from last screen :+1:

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 9.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
