### PR TITLE
Guard against multi click when editing a form

### LINKED ISSUE #6740: Multiclicking the pencil icon in edits
#### ODK Collect version
the master version 791154cd7b3b483be01e566ac44a4f47c9efc80e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It's possible to multiclick the pencil icon in edits. If it isn't the latest version than the dialog asking about version to edit is opened e.g. twice. I haven't found a case with a crash or 2 instances created - just the dialog opened more than once.
#### Steps to reproduce the problem
1. Scan QR code user "test1" https://test.getodk.cloud/projects/616/app-users
2. Finalize or send an editable form.
3. Create 1 or 2 edits.
4. Open the edit which isn't the newest.
5. Tap the pencil icon multiple times quickly.
#### Expected behavior
It shouldn't be possible to multiclick the icon.

### PR DESCRIPTION
**Pull request by seadowg**
Closes https://github.com/getodk/collect/issues/6740

I also upped the JVM heap size for the larger machine CI jobs after seeing a heap size error in `build_instrumented`.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java [hunk 1]
```diff
@@ -866,6 +867,10 @@ public void onPrepareMenu(@NonNull Menu menu) {
 
         @Override
         public boolean onMenuItemSelected(@NonNull MenuItem menuItem) {
+            if (!MultiClickGuard.allowClick("formEntryScreen")) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java]: There is a special `screen_names.xml` file for such consts.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified cases:**
- issue #6740 doesn't occur

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on Android 15
