### PR TITLE
Fixed the problem with SelectOneWidget and minimal + search appearance in field-list

### LINKED ISSUE #3180: SelectOneWidget doesn't work with minimal and search appearance if it's in a field-list group
#### Software and hardware versions 
Collect v1.22.4 and older versions

#### Problem description
SelectOneWidget doesn't work with minimal and search appearance if it's in a field-list group.
Originally reported: https://forum.opendatakit.org/t/having-two-minimal-search-name-on-a-group-does-not-work-on-odk/20623/3

#### Steps to reproduce the problem
Try to use this form:
[search_and_select.xlsx](https://github.com/opendatakit/collect/files/3336880/search_and_select.xlsx)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3180

#### What has been done to verify that this works as intended?
I tested the form attached to the issue.

#### Why is this the best possible solution? Were any other approaches considered?
I solved the issue in the first commit https://github.com/opendatakit/collect/commit/62cae799aabdab248a9f8927a582369383cd7c9f
The problem was that the code in `onItemSelected()` was performed even if we set the item programmatically (during initiating the view) so `widgetValueChanged()` was called.
If we use that widget in a `field-list` group and with `search` appearance (https://github.com/opendatakit/collect/commit/086f85263e716b2992fbddfbd4986f110de2e258) it caused that such a widget was recreated every time, and again `onItemSelected()` was called (endless loop).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Changes are related only to that one widget (SelectOneWidget with minimal appearance) so it's not risky and testing the widget would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java [hunk 1]
```diff
@@ -84,12 +87,12 @@ public SpinnerWidget(Context context, FormEntryPrompt prompt, boolean autoAdvanc
             s = ((Selection) prompt.getAnswerValue().getValue()).getValue();
         }
 
-        spinner.setSelection(items.size());
+        programmaticallySetSelection(items.size());
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java]: Is there any case in which this would happen after a user-initiated selection set? If not, I think it might be clearer to just have a flag to keep track of whether it's the first time or not.

**Review by lognaturel — COMMENTED** [review]
Thank you for that cleanup, especially expanding the 1-character names!!

**Comment by lognaturel** [comment]
Oh, how about adding a case in `FieldListUpdateTest`? I gave you write access to [the test form](https://docs.google.com/spreadsheets/d/1YSFgcDyafLI4lqsX4pVspnHEcQ7R893fVtc34nlWgGU/edit#gid=0) so you can easily add to the bottom of it.

File: collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java]: Ok I added such flag instead.

**Comment by grzesiek2010** [comment]
@lognaturel I added one test, you can review and add `needs testing` label if everything is fine.

File: collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java [hunk 2]
```diff
@@ -378,6 +379,19 @@ public void manuallySelectingAValueForMissingExternalApp_ShouldTriggerUpdate() {
         onView(withText("Target14")).check(matches(isDisplayed()));
     }
 
+    @Test
+    public void search_function_in_field_list() throws InterruptedException {
+        jumpToGroupWithText("Search in field-list");
+        onView(withText(startsWith("Source15"))).perform(click());
+        Thread.sleep(1000);
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java:388]: Why are this sleep and the `InterrputedException` throwing needed? Espresso should be able to detect when the UI thread is idle. Is it related to database lookups? `ExternalCsvSearchTest` does something similar so I'm surprised.

File: collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java [hunk 3]
```diff
@@ -83,7 +84,7 @@
                     Manifest.permission.WRITE_EXTERNAL_STORAGE,
                     Manifest.permission.CAMERA)
             )
-            .around(new CopyFormRule(FIELD_LIST_TEST_FORM));
+            .around(new CopyFormRule(FIELD_LIST_TEST_FORM, "", Collections.singletonList("fruits.csv")));
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java:89]: Would you consider using the existing `external-csv-search-produce.csv` data file? I think it would be appropriate to move `fieldlist-updates.xml` to the `forms` subdirectory as well. Not a big deal if you prefer to keep them separate for now.

**Review by lognaturel — COMMENTED** [review]
Up to you whether you want to share the CSV data file. I'm a little more concerned about the sleep/`InterruptedException`.

Either way, these are test-only changes so don't need to be figured out before QA.

File: collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java:388]: It's because the spinner is not clickable immediately and the test didn't work.

**Comment by bognasoldev89** [comment]
*Tested with success*

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases:
- SelectOneWidget with minimal + search appearance search list
- Rotating during testing the form
- Swiping while a mobile phone was vertically
- Closing the app during testing the form
- Minimizing the app during testing the form
- Blocking mobile phones during testing
- Saving changes
- Dismissing changes

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
Thanks for testing, @bognasoldev89! @grzesiek2010, can you please fix the new conflict and merge? We can see if there's another option for the test when someone has a chance to dig deeper.

**Comment by grzesiek2010** [comment]
> can you please fix the new conflict and merge?

FIxed, but I can't merge without at least one approvement.

**Review by lognaturel — APPROVED** [review]
