### PR TITLE
Don't create entities with non-UUID IDs

### LINKED ISSUE #7047: Don't create/update offline entities without UUID `id`
As stated in [the spec](https://getodk.github.io/xforms-spec/entities#declaring-that-a-form-creates-entities):

> Consumers of submissions that create entities MUST fail to create entities that don’t have a UUID id

Currently, Collect will create/update entities with any string.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7047

I've also added an experimental [debug log](https://github.com/getodk/collect/pull/7096#discussion_r2804602630).

#### Why is this the best possible solution? Were any other approaches considered?

I decided to move most of the validation we do for entities to the JavaRosa integration. This reduces the uncertainty we have to deal with in the code that creates offline entities and syncs with the server etc.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

There are no real changes other than to the entity create/update parts of the code, so only checks to those features are relevant

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntitiesExtra.kt [hunk 1]
```diff
@@ -1,3 +1,6 @@
 package org.odk.collect.entities.javarosa.finalization
 
-data class EntitiesExtra(val entities: List<FormEntity>)
+data class EntitiesExtra(
+    val entities: List<FormEntity> = emptyList(),
+    val invalidEntities: List<InvalidEntity> = emptyList()
```
Comment (seadowg) [inline entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntitiesExtra.kt:5]: @lognaturel you've asked for this a few times and I figured this was a good time to give ourselves an API for exposing "invalid" entities. What's the leanest acceptable way you could see these being surfaced to make them useful?

File: entities/src/main/java/org/odk/collect/entities/javarosa/parse/StringExt.kt [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+import java.util.UUID
+import kotlin.contracts.ExperimentalContracts
+import kotlin.contracts.contract
+
+object StringExt {
+
+    @OptIn(ExperimentalContracts::class)
+    fun String?.isV4UUID(): Boolean {
+        contract {
```
Comment (seadowg) [inline entities/src/main/java/org/odk/collect/entities/javarosa/parse/StringExt.kt]: I've not used this before, but it's really cool! It's experimental, but used heavily within Kotlin's lib itself for methods like `isNullOrBlank`.

File: entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntitiesExtra.kt (hunk 1 above)
Comment (lognaturel) [reply entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntitiesExtra.kt:5]: Summary of a brief conversation we had about this:
* Start with exposing errors from debug builds only, maybe just storing in memory
* Log Submission id, date time, path to the entity declaration, dataset, entity uuid if it exists, entity label if it exists
* Longer term: audit log in the `Project management` `Protected` settings
* Standard format for audit items, persisted in db or file
* Send to Central automatically or on demand
* [Brainstorming doc](https://docs.google.com/document/d/1nadRJQpK_L8KCqGO2Kum9XraCXg4lKjZ2_3pzQeuUC0/edit?tab=t.0)

Comment (seadowg) [reply entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntitiesExtra.kt:5]: Ok this will initially write out a log to `debug.log` in the project directory when the app is in debug mode. The line for an invalid entity will be:

```
${timestamp} Entities "Failed to create/update dataset=${it.dataset}, id=${it.id}, label=${it.label}"
```

We can definitely add more detail in, but I think this is a good start.

File: entities/src/test/java/org/odk/collect/entities/javarosa/EntitiesTest.kt [hunk 3]
```diff
@@ -909,12 +952,15 @@ class EntitiesTest {
                                 t("join"),
                                 t(
                                     "meta",
-                                    t("entity dataset=\"members\" create=\"\" id=\"1\"")
+                                    entityNode("members", CREATE, optionalAction = false)
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/EntitiesTest.kt]: `optionalAction` is false by default, so it can be skipped here.

File: entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.kt [hunk 4]
```diff
@@ -84,21 +87,16 @@ class EntityFormFinalizationProcessorTest {
...
-                                    )
-                                )
+                                t("age"),
+                                t("meta", entityNode("people", CREATE))
                             )
                         ),
-                        bind("/data/name").type("string")
-                            .withAttribute("entities", "saveto", "name")
+                        bind("/data/name").type("string"),
+                        bind("/data/age").type("string")
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.kt:95]: Why do we need this additional field? What was wrong about `name` not being relevant?

File: entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+            )
+
+            EntityAction.UPDATE -> t(
+                "entity dataset=\"$dataset\" update=\"$actionValue\" id=\"\"",
+                t("label")
+            )
+        }
+    }
+
+    fun entityLabelBind(ref: String): BindBuilderXFormsElement {
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt:35]: These are not versatile functions, right? They assume entities are used on the root level but with recent changes, it is possible to add entities anywhere - nested in groups/repeats.

File: entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+        return bind("/data/meta/entity/label").type("string").calculate(ref)
+    }
+
+    fun entityIdBind(): BindBuilderXFormsElement {
+        return bind("/data/meta/entity/@id").type("string")
+    }
+
+    fun entityIdSetValue(): XFormsElement {
+        return setvalue("odk-instance-first-load", "/data/meta/entity/@id", "uuid()")
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt:44]: Entity id might also be changed as a result of `odk-new-repeat` event, so the name of the fun should reflect that.

File: entities/src/main/java/org/odk/collect/entities/javarosa/parse/StringExt.kt [hunk 7]
```diff
@@ -0,0 +1,25 @@
+package org.odk.collect.entities.javarosa.parse
+
+import java.util.UUID
+import kotlin.contracts.ExperimentalContracts
+import kotlin.contracts.contract
+
+object StringExt {
+
+    @OptIn(ExperimentalContracts::class)
+    fun String?.isV4UUID(): Boolean {
```
Comment (grzesiek2010) [inline entities/src/main/java/org/odk/collect/entities/javarosa/parse/StringExt.kt]: It could be a top-level fun right? No need to keep the object.

File: entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+import org.hamcrest.Matchers.equalTo
+import org.junit.Test
+import org.odk.collect.entities.javarosa.parse.StringExt.isV4UUID
+import java.util.UUID
+
+class StringExtTest {
+
+    @Test
+    fun `#isV4UUID is false for version 1 UUIDs`() {
+        val v2UUID = "6b5ea8de-9565-11e8-9eb6-529269fb1459"
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt]: This should be `v1UUID`.

File: entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt [hunk 9]
```diff
@@ -0,0 +1,40 @@
+package org.odk.collect.entities.javarosa.parse
+
+import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.equalTo
+import org.junit.Test
+import org.odk.collect.entities.javarosa.parse.StringExt.isV4UUID
+import java.util.UUID
+
+class StringExtTest {
```
Comment (grzesiek2010) [inline entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt:8]: There is no test for an invalid UUID, I mean the case that is caught with an `IllegalArgumentException`. Something like:
```
@Test
fun `#isV4UUID is false for invalid UUID string`() {
    val invalid = "not-a-uuid"
    assertThat(invalid.isV4UUID(), equalTo(false))
}
```

File: entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.kt [hunk 10]
```diff
@@ -19,28 +20,48 @@ class EntityFormFinalizationProcessor : FormEntryFinalizationProcessor {
...
+                val action = EntityFormParser.parseAction(element)
+                val dataset = EntityFormParser.parseDataset(element)!!
+                val id = EntityFormParser.parseId(element)
+                val label = EntityFormParser.parseLabel(element)
 
                 if (action == EntityAction.CREATE || action == EntityAction.UPDATE) {
-                    createEntity(entityElement, dataset, saveTos, mainInstance, action)
+                    val entity = createEntity(
+                        dataset,
+                        EntityFormParser.parseId(element),
```
Comment (grzesiek2010) [inline entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.kt]: `id` and `label` are already parsed, and you can use them.

File: collect_app/src/main/java/org/odk/collect/android/projects/FileDebugLogger.kt [hunk 11]
```diff
@@ -0,0 +1,19 @@
...
+import org.odk.collect.android.BuildConfig
+import org.odk.collect.shared.DebugLogger
+import java.io.File
+
+class FileDebugLogger(private val file: File) : DebugLogger {
+
+    override fun log(tag: String, message: String) {
+        if (enabled) {
+            val line = "${System.currentTimeMillis()} $tag \"$message\""
+            file.appendText(line)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/projects/FileDebugLogger.kt:13]: Without a newline, won’t all logs end up on the same line?

File: collect_app/src/main/java/org/odk/collect/android/projects/FileDebugLogger.kt [hunk 12]
```diff
@@ -0,0 +1,19 @@
...
+
+import org.odk.collect.android.BuildConfig
+import org.odk.collect.shared.DebugLogger
+import java.io.File
+
+class FileDebugLogger(private val file: File) : DebugLogger {
+
+    override fun log(tag: String, message: String) {
+        if (enabled) {
+            val line = "${System.currentTimeMillis()} $tag \"$message\""
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/projects/FileDebugLogger.kt]: `System.currentTimeMillis()` returns milliseconds. Maybe `LocalDateTime.now() `would make more sense here?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.kt (hunk 4 above)
Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.kt:95]: We need a field to use for the entity label. We could just hardcode it, but I'd argue that's pretty surprising and doesn't really trade off the trimming a line or two.

File: entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt (hunk 5 above)
Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt:35]: True, but they could easily be made more vesatile if needed by just pulling out the nodeset as a default param. That's not needed right now though.

File: entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt (hunk 6 above)
Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/support/EntityXFormsElement.kt:44]: Again, we could just pull the event/nodeset out as a default param, but it's not being used in repeat cases right now.

File: entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt (hunk 9 above)
Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/parse/StringExtTest.kt:8]: That's covered by tests in `EntitiesTest`. That said, it does feel like it'd be nice to have the whole thing covered at the unit level given it's so simple.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
If I send a submission of a form which allows entering an ID while creating a form, does this entity get created on Central (even if I was blocked in Collect)?

**Comment by seadowg** [comment]
> If I send a submission of a form which allows entering an ID while creating a form, does this entity get created on Central (even if I was blocked in Collect)?

@dbemke I thought that Central didn't allow non-UUID entities though? That was the reason for this change.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- creating an entity with a random uuid entered in the form
- checking if an entity doesn't get created when expected
- regression checks in entities

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16

**Comment by lognaturel** [comment]
@seadowg I want to make sure you saw https://github.com/getodk/central/issues/1682 -- it was filed on Central but might be that we decide to match the Central behavior here, it's a case we'd forgotten about. For now it's not a big deal to have this discrepancy. I think the history might be that at some early point Entity ids were more likely to have the prefix.

**Comment by seadowg** [comment]
Yup! @dbemke discussed that on Slack and I had asked for the issue to be filed.
