### PR TITLE
Removed redundant logs from AuditEventSaveTask

### LINKED ISSUE #5703: Address or suppress audit header error about null FileWriter
We are currently logging a frequent audit-related error: [Crashlytics](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/e577bff0dbc501d14310b1dfbdbeaf33?time=last-seven-days&sessionEventKey=64DCDF1800D800017A984CE6B483FB31_1846376940478461415) (requires auth).

Since we are in the audit context for this release, I think we should do something about it. If it's not important, we should not log it. I expect it does point to something going wrong.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5703 

#### What has been done to verify that this works as intended?
I've reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
As described in the issue those logs didn't make a lot of sense so it's better to get rid of them.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java [hunk 1]
```diff
@@ -65,8 +65,6 @@ protected Void doInBackground(AuditEvent... params) {
             try {
                 if (fw != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java:66]: Reading the code, I don't think `fw` can ever be `null` here as it is assigned before any exceptions could occur. Does that make sense to you too? If so, we should be able to simplify this even more.

File: collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java [hunk 2]
```diff
@@ -98,13 +96,9 @@ private boolean updateHeaderIfNeeded() {
             try {
                 if (tfw != null) {
                     tfw.close();
-                } else {
-                    Timber.e(new Error("Attempt to close null FileWriter for AuditEventLogger."));
                 }
                 if (br != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java:100]: Same for this. I don't think `br` can ever be `null`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java:66]: It looks like it's rather not possible and that's why I got rid of those additional logs but I didn't have enough bravery to get rid of the null checks too. 
`fw` is null until we call `fw = new FileWriter(file, true);` and `FileWriter` can throw `IOException` there so in such a case it might be null right? Rare but possible.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventSaveTask.java:66]: I had missed that `FileWriter` can throw an `IOException`!

**Review by seadowg — APPROVED** [review]
