### PR TITLE
Prevent crashes when geometry is invalid

### LINKED ISSUE #5075: Handle invalid geometries
#### Software and hardware versions 
Collect v2022.1 and prior

#### Problem description
There are two overlapping problems:
- The `geometry` field is not validated prior to the corresponding choice being rendered. It could contain anything. We've seen crashes because of attempts to use geojson instead of ODK-formatted features, for example
- Mapbox and osmdroid crash when handed geometry that is out of bounds at least in the instance form map and possibly in other map uses. Google Maps appears to wrap around in the case of longitude and render off map in the case of latitude. This one may need to be spun off depending on where the proposed dialog described below is shown from.

#### Steps to reproduce the problem
The easiest is to use the select from map with a [form that has invalid points](https://docs.google.com/spreadsheets/d/1CDGcthyS7KJgnJikmJttLdwFS4xsSysDRuoxdVQS2zQ/edit?usp=sharing). You can also enter incorrect geometry (like `blah`).

#### Expected behavior

Shows a dialog (when points are invalid or geometry is invalid) that reads: "The choice with label <choice label> has invalid geometry (<geometry>)". Clicking OK returns to the form (from the dialog).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5075 

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Just checking that the issue is fixed should be enough here.

#### Do we need any specific form for testing your changes? If so, please attach one.

Any form with select one from map question (and geometry set up to be invalid).

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ErrorDialog.java [hunk 1]
```diff
@@ -24,6 +26,10 @@
 limitations under the License.
  */
 
+/**
+ * @deprecated Should be replaced with {@link MaterialAlertDialogFragment}
+ */
+@Deprecated
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ErrorDialog.java:32]: I would have done the work to replace this instead of deprecating here, but wanted to avoid the extra risk given that this will be going into a hotfix.

File: collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt [hunk 2]
```diff
@@ -103,43 +131,60 @@ internal class SelectChoicesMapData(
...
-                val longitude = geometry.split(" ")[1].toDouble()
+                val latitude: Double
+                val longitude: Double
+
+                try {
+                    latitude = geometry.split(" ")[0].toDouble()
+                    longitude = geometry.split(" ")[1].toDouble()
+
+                    if (latitude.absoluteValue > 90 || longitude.absoluteValue > 180) {
+                        return InvalidGeometry(prompt.getSelectChoiceText(selectChoice), geometry)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt:181]: I'm really not happy with this (and the below) early return but haven't really come up with anything better 🤔

File: collect_app/src/main/java/org/odk/collect/utilities/Result.java [hunk 3]
```diff
@@ -5,7 +5,10 @@
 /**
  * Based on https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/ which is not
  * available to Java.
+ *
+ * @deprecated use {@link org.odk.collect.shared.result.Result} instead
  */
+@Deprecated
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/utilities/Result.java:11]: Again, I would have done the work to replace this instead of deprecating here, but wanted to avoid the extra risk given that this will be going into a hotfix.

**Review by lognaturel — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1 and 8.1

Verified cases:
- Google, Mapbox, OSM (no differences in behavior)
- crashes not visible
- information about invalid geometry visible
- screen rotation, minimize app
- finalize, edit submission
- light/dark mode
- RTL language 

The only concern here is that issue mentions "OK" button on the displayed dialog and it has not been added. It's not a big deal as I am able to hide dialog after tapping outside of dialog, I just want to make sure that it was intentional as we don't really have any dialogs without buttons.

**Comment by lognaturel** [comment]
> make sure that it was intentional as we don't really have any dialogs without buttons

Accidental but as you said, I don’t think it’s a big deal. I think we can go with it for now. 

Edit: @grzesiek2010 will add. I don’t think we’ll need additional verification!

**Comment by srujner** [comment]
**Tested with success!**
Verified on Androids: 10 and 11
