### PR TITLE
Provide user-friendly error message when CSV for search() or external itemsets is not on device

### LINKED ISSUE #3235: Provide user-friendly error message when CSV for search()/pulldata is not on device
The error messages shown when a CSV attachment meant to be used with search()/pulldata are not friendly to users. Moreover, they don't provide any real useful information for developers. See https://github.com/opendatakit/collect/issues/3230 for an example.

Ideally the error message would explicitly name the CSV file that was missing. I'm not sure whether that information is available where the error is thrown, though, so something like "Something went wrong when trying to access the columns [column names here] from a CSV file. Was the CSV file attached?" might be enough. Note that presumably this error could have come from something going wrong in the database creation process so we can't say for sure that it was missing.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3235 

#### What has been done to verify that this works as intended?
I tested the attached forms and added an automated test.

#### Why is this the best possible solution? Were any other approaches considered?
We already handle such a case in case of external itemsets so I decided to use the same code and display the same message.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's not a risky change it's just related with two widgets for which I added sample forms below. Testing them would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
[selectOneExternal.zip](https://github.com/opendatakit/collect/files/3851183/selectOneExternal.zip)
[search.zip](https://github.com/opendatakit/collect/files/3851184/search.zip)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java [hunk 1]
```diff
@@ -205,6 +208,16 @@ public static XPathFuncExpr getSearchXPathExpression(String appearance) {
             }
             return returnedChoices;
         } catch (Exception e) {
+            String fileName = xpathfuncexpr.args[0].eval(null, null) + ".csv";
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java]: At this point the filename hasn't been normalized by `ExternalDataHandlerBase.normalize` so it could include a `.csv` suffix, right? I think you need to check whether it's already there or not before adding it.

**Review by lognaturel — COMMENTED** [review]
It looks like this doesn't do anything for a form with `pulldata`.

I was imagining a dialog but I think this is probably better because it's always visible and matches what happens when an image/audio/video file is missing. 👍

File: collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java]: Right, I thought in search you can use just a file name without .csv but looks like both versions work:
`search('fruits')` and `search('fruits.csv')`
Fixed.

**Comment by grzesiek2010** [comment]
> It looks like this doesn't do anything for a form with pulldata.

`pulldata` is used in calculations so it's difficult then to tell if there are no elements because it should return no elements or if the file is missing.

**Comment by lognaturel** [comment]
> `pulldata` is used in calculations so it's difficult then to tell if there are no elements because it should return no elements or if the file is missing.

Except currently it crashes if no dataset exists, right? What I had in mind was having a special case for when the SQL exception reason is that there is no table of the requested name. That case would show a nice error instead of a big ugly one with SQL info.

Looking at your solution again, are you sure it works every time the form is loaded? The csv files get renamed on import with something like an `.imported` suffix. I suspect that what you have only works the first time the form is loaded.

**Comment by grzesiek2010** [comment]
When it comes to `search` func the message is always displayed even if at first you have your csv file and then you remove those files that are created from your origins csv.
In case of `pulldata` there is no crash just nothing is displayed (no elements).

**Comment by lognaturel** [comment]
> the message is always displayed even if at first you have your csv file and then you remove those files that are created from your origins csv

I don't really understand this but I see now from looking at the code again that the check for the original CSV is only relevant if there's an exception in the first place so that makes sense.

> In case of pulldata there is no crash just nothing is displayed (no elements).

Ah, that's right, that's what we need to improve. It's different so we can file it as a separate issue. The problem is that if there's user input involved it's hard to tell whether there was no match or the file wasn't there.

**Review by lognaturel — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> The problem is that if there's user input involved it's hard to tell whether there was no match or the file wasn't there.

Exactly, moreover in forms like the one attached to [How to pull data from CSV](https://xlsform.org/en/#how-to-pull-data-from-csv) the result is calculated and used in a `note` question so in Collect we don't even now if it's a result of `pulldata()`, so probably it could require changes in javarosa.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.2, 4.4, 5.1, 6.0, 7.1, 8.1, 9.0 and 10.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
