### PR TITLE
3780 restore exif data after rotate or resize

### LINKED ISSUE #3780: EXIF metadata not stored in pictures taken with Android 6.0.1 native camera app
#### Software and hardware versions 
Collect v1.26.2, Android v6.0.1, Nexus 5

#### Problem description
When taking pictures with the native Android Camera app through the [default image widget](https://docs.opendatakit.org/form-question-types/#default-image-widget), the resulting picture has no EXIF metadata.

Taking simultaneously a picture with the same device in the same place with the same app saves the EXIF metadata without any problem

#### Steps to reproduce the problem
- download the "All widgets" form from the ODK Aggregate Demo server
- go to the "Image widget" question
- click on the "take a picture" button, choose the native Android Camera App, and save the picture
- back to ODK collect, save the form
- use an EXIF capable app (e.g [Photo EXIF Editor](https://play.google.com/store/apps/details?id=net.xnano.android.photoexifeditor&hl=en)) to display the EXIF metadata of the picture 
- there's no EXIF information at all there.

#### Expected behavior
the picture should have the EXIF information saved when taking the picture through ODK with the EXIF capable native camera app.

#### Other information 
Other users in my organization faced the same issue with different devices.
Using a different camera app (like Open Camera) fixes the problem.

### PR DESCRIPTION
**Pull request by ItloMd9**
Closes #3780

#### What has been done to verify that this works as intended?
Use a form (with default imagewidget) to "capture image".
Tried with updating image size (for scaling) on settings as well as rotating the phone on capturing images.

Use exif viewer app (ExifTool) to view the exif information or
Submit the form to a server which can parse those exif information

#### Why is this the best possible solution? Were any other approaches considered?

It is simplest.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

It avoids the exif data from being removed.

#### Do we need any specific form for testing your changes? If so, please attach one.

Any form with default image widget is enough as mentioned above.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

No. It's a bug fix. So I dont think we need any documentation

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@ItloMd9 Hello! Thanks for the PR. It looks like you're still working on this (PR template isn't filled in, build failing etc). That's totally fine but if so, are you able to mark it as a Draft? You'll see there is an option to do so under the "Reviewers" section of this page. That just helps us keep track of what is ready for review and what isn't.

**Comment by ItloMd9** [comment]
@racetiger,
PR has been updated,
Could you please kindly review again ?
Thank you very much,

**Comment by racetiger** [comment]
> @racetiger,
> PR has been updated,
> Could you please kindly review again ?
> Thank you very much,

thanks for considering my suggestions. No more comments from my side.

**Review by racetiger — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java [hunk 1]
```diff
@@ -39,9 +39,26 @@
...
+            exif = new ExifInterface(imagePath);
+        } catch (IOException e) {
+            Timber.w(e);
+        }
+
         rotateImageIfNeeded(imagePath);
         scaleDownImageIfNeeded(imagePath, questionWidget, context);
+        
+        try {
+            exif.saveAttributes();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: This might cause NPE. Please add a null check here.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java [hunk 2]
```diff
@@ -39,9 +39,26 @@
     private ImageConverter() {
     }
 
+    /**
+     * Before proceed with scaling or rotating, make sure existing exif information is store/restored.
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: Should be: stored/restored (d missing).

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java [hunk 3]
```diff
@@ -39,9 +39,26 @@
...
+     * @author Khuong Ninh (khuong.ninh@it-development.com)
+     */
     public static void execute(String imagePath, QuestionWidget questionWidget, Context context) {
+        ExifInterface exif = null;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java:47]: Could this maybe align with how you named it in the comment above (store/restore)? I mean this could be in a separate method called `storeExifAttributes()` and the code below also could be in a separate method called `restoreExifAttributes()` then the code would be cleaner.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java (hunk 1 above)
Comment (ItloMd9) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: Thank you, @grzesiek2010 ,

I have updated the code to avoid NPE as you suggested.
Please kindly review

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java (hunk 2 above)
Comment (ItloMd9) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: Comment has been updated, please kindly review

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java (hunk 3 above)
Comment (ItloMd9) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java:47]: For simplicity's sake, I would avoid extra unnecessary methods/functions' overhead which (in this case) only fetch exif from an image path via constructor and then save it back via built-in function (saveAttributes) to the same old path.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java [hunk 4]
```diff
@@ -39,9 +39,28 @@
     private ImageConverter() {
     }
 
+    /**
+     * Before proceed with scaling or rotating, make sure existing exif information is stored/restored.
+     * @author Khuong Ninh (khuong.ninh@it-development.com)
+     */
     public static void execute(String imagePath, QuestionWidget questionWidget, Context context) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java:46]: Would you like to add a test? It should be straightforward because we have this function in `ImageConverterTest`:

```
    private void saveTestBitmap(int width, int height, Integer orientation) {
        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565);
        FileUtils.saveBitmapToFile(bitmap, TEST_IMAGE_PATH);

        if (orientation != null) {
            try {
                ExifInterface exifInterface = new ExifInterface(TEST_IMAGE_PATH);
                exifInterface.setAttribute(ExifInterface.TAG_ORIENTATION, String.valueOf(orientation));
                exifInterface.saveAttributes();
            } catch (IOException e) {
                Timber.w(e);
            }
        }
    }
```

which we use for testing `ImageConverter`.

Comment (ItloMd9) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java:46]: I have added 1 test to check if exif data is removed after ImageConvert.execute() is invoked.
Please kindly review.

File: collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java [hunk 5]
```diff
@@ -382,6 +383,51 @@ public void scaleImageToNewWidthTest() {
         assertEquals(1250, image.getHeight());
     }
 
+    @Test
+    public void keepExifTest1AfterScaleAndRotation() {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java:406]: Does this test work for you locally? I tried on various android versions and the result is:
```
junit.framework.ComparisonFailure: expected:<ApertureValue_value> but was:<null>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at org.odk.collect.android.instrumented.utilities.ImageConverterTest.keepExifTest1AfterScaleAndRotation(ImageConverterTest.java:426)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.odk.collect.android.support.ResetStateRule$ResetStateStatement.evaluate(ResetStateRule.java:71)
```

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java:406]: Not only locally I ran it on firebase test lab and the result is the same.

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java:406]: I'll take a look at it unless you are already fixing the test.

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java:406]: Ok I pushed one commit to your branch with fixes.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java:47]: generally i like more my approach but I'm not going to insist let's keep it as is.

**Review by grzesiek2010 — APPROVED** [review]
Ok I think it's ready for testing. Thanks @ItloMd9

**Review by racetiger — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@ItloMd9, I still see this issue on device with Android 10.

I need to add Location permission to ODK to get location information for the photo. 
This permission is not required in other Android versions (7.0, 8.1).

I consulted this issue with @grzesiek2010 and he suggested that extra changes may be needed.

@getodk-bot unlabel "needs testing"

**Comment by ItloMd9** [comment]
@mmarciniak90 
This fix does not add location information to captured photos.
It just avoid the location information being removed if we rotate or scale the image

**Comment by mmarciniak90** [comment]
@getodk-bot label "needs testing"

**Comment by lognaturel** [comment]
> I need to add Location permission to ODK to get location information for the photo.

This sounds right to me given what I know of Android 10 permissions. Are you and @grzegorz perhaps suggesting we prompt for location permissions when first taking a photo? That’s a good thing to discuss but it would be for a separate issue.

**Comment by grzesiek2010** [comment]
I'm not sure what fix we need, I would need to dig deeper but ok if this pr is only about not removing locations on our side that's ok. We can file a separate issue and investigate what's going on with Android 10.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases 
* attached image with EXIF data to Image widget
* attached image with EXIF data to Annotate widget
* verified all available image size settings (very small, small, medium, large)
* attached rotated image with EXIF data to Image widget
* attached rotated image with EXIF data to Annotate widget

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1, 9.0 and 10.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
