### PR TITLE
Ensure that GPS is turned off on activity pause or exit.

### LINKED ISSUE #3241: Mapbox map fragment does not stop requesting location updates
#### Software and hardware versions 
Collect v1.22+

#### Problem description
After opening a geo widget with a Mapbox basemap, location updates are requested until Collect is quit.

#### Steps to reproduce the problem
- Select a Mapbox basemap from the Maps settings
- Launch a geo widget
- Close the geo widget
- See on `logcat` and in the Android status bar that location updates continue

#### Expected behavior
Location updates should end when the geo widget is closed. Ideally location updates should also stop when Collect is paused or stopped.

### PR DESCRIPTION
**Pull request by zestyping**
Issues: Closes #3241.
Scope: MapFragments
Requested reviewers: @lognaturel 

#### User-visible changes

GPS location tracking is now properly turned off (the location icon disappears from the status bar) when a geo activity is paused or exited.  Previously, in some situations, the GPS would stay on indefinitely.

As an unfortunate side effect, the GPS lock is reset when the screen is rotated.  An existing GPS lock will be lost and the user will need to wait to re-acquire the lock (though usually this only takes a few seconds).  Previously, when the screen was rotated, the GPS lock state was preserved.

#### Internal changes

Previously, each Activity had to turn GPS on and off in its `onStart()` and `onStop()` methods.  Now, it's the `MapFragment`'s responsibility to remember what GPS state the activity wanted, and handle turning the GPS on and off in its own (Fragment) `onStart()` and `onStop()` methods.

Similarly, previously, each Activity had to handle a corner case where the `MapFragment` was detached before calling the `readyListener`.  Each `MapFragment` now avoids this corner case.

All the MapFragments now log a message when they start or stop getting location updates, so it's a little easier to confirm that this is working properly by filtering the logcat on the string `location update`.

#### Verification performed

For each of the cases listed below, I performed the following steps (looking at the GPS icon in the status bar to verify whether GPS is on):
1. Start the activity.  Verify that GPS is on.
2. Press Home.  Verify that GPS is off.
3. Return to Collect by tapping the app icon.  Verify that GPS is on.
4. Repeat 2 & 3 a few times.
5. Press the app switcher button.  Go to another app.  Verify that GPS is off.
6. Return to Collect using the app switcher.  Verify that GPS is on.
7. Repeat 5 & 6 a few times.
8. Rotate the screen several times, quickly.  Verify that GPS is still on.
9. Press Back to quit the activity and return to the form question.  Verify that GPS is off.

Here are all the cases tested:

Select basemap source "Google"
  - Start GeoPoint; perform verification.
  - Start GeoTrace; perform verification.
  - Start GeoShape; perform verification.

Select basemap source "OpenStreetMap"
  - Start GeoPoint; perform verification.
  - Start GeoTrace; perform verification.
  - Start GeoShape; perform verification.

Select basemap source "Mapbox"
  - Start GeoPoint; perform verification.
  - Start GeoTrace; perform verification.
  - Start GeoShape; perform verification.

### CODE REVIEW

**Comment by zestyping** [comment]
I wasn't able to find a good way to preserve the nice feature that we kept the GPS lock during screen rotation.  I suspect there may be a better solution along the lines of keeping a single static LocationClient that enforces that there can only ever be one listener at a time.  I may give that a shot tomorrow if I have time and energy, but for now, at least this works.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Ahh, lifecycle woes. I need to be more consistent about looking for those kinds of issues in code review and I think it would be good to have in the QA checklist as well, at least for cases like location where there is a visible sign that resources haven't been released. It's great that we're fixing this before lots of folks have switched to Mapbox.

> I wasn't able to find a good way to preserve the nice feature that we kept the GPS lock during screen rotation.

An option would be to introduce a really thin [`ViewModel`](https://developer.android.com/topic/libraries/architecture/viewmodel) that just holds the location client for now.

**Comment by zestyping** [comment]
> Ahh, lifecycle woes. I need to be more consistent about looking for those kinds of issues in code review and I think it would be good to have in the QA checklist as well, at least for cases like location where there is a visible sign that resources haven't been released.

Yes, fully agree.  I feel bad that I didn't notice this previously.  I want to add an instrumentation test for this.

**Comment by zestyping** [comment]
See also #2997.

File: collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java [hunk 1]
```diff
@@ -374,6 +361,31 @@
...
     @Override public void onClientStop() { }
 
+    private void enableLocationUpdates(boolean enable) {
+        if (locationClient == null) {
+            locationClient = LocationClients.clientForContext(getActivity());
+            locationClient.setListener(this);
+        }
+        if (enable) {
+            LocationManager locationManager = (LocationManager) getContext().getSystemService(Context.LOCATION_SERVICE);
+            if (locationManager != null && locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:371]: I'm not quite understanding your comment about #2997. This is what causes the discrepancy, right? I think the `enableLocationUpdates` method here could be identical to the one in the GoogleMapsFragment. I'm happy for that to happen now.

Comment (zestyping) [reply collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:371]: Oh, I just meant to connect the issues because I suspect it will make sense to address them together.  Right now Mapbox is the odd one out with its own LocationEngine infrastructure — we'll probably want to unify them all.  (Fortunately, Mapbox provided hooks so we can easily disable their LocationEngine and use our own instead.)

Comment (zestyping) [reply collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:371]: The first part can be identical to the one in GoogleMapFragment, but this one needs extra stuff to enable and disable the location overlay as well.   Am I maybe misunderstanding what you have in mind?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:371]: Ahh, got it. I'm saying that modulo the overlay, this work to check whether the GPS provider is enabled and to show an error otherwise is what results in the discrepancy.

**Comment by lognaturel** [comment]
I took the liberty of fixing the merge conflicts so that QA looks at something merge-ready. I used the GitHub frontend -- @zestyping if that merge commit offends you, feel free to drop it and rebase!

**Comment by zestyping** [comment]
Looks totally good!  Thanks for merging.

**Comment by mmarciniak90** [comment]
**Tested with success**

**Verified on Android:** 4.2, 4.4, 6.0, 7.0, 8.1 - but not all cases

Tested cases:
* GoogleMaps: Geopoint, GeoTrace, GeoShape
* Mapbox: Geopoint, GeoTrace, GeoShape
* USGS: Geopoint, GeoTrace, GeoShape

|without fix|beforeMapbox|
|---|---|
|**with fix**|after|

@opendatakit-bot unlabel "needs testing "
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
