### PR TITLE
Exclude settings not supported by a particular device like Mapbox for example

### LINKED ISSUE #5431: UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize
#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/587fc4abc10b00e36df371da5450a30e?time=last-seven-days&versions=v2022.4.4%20(4565)&types=crash&sessionEventKey=63D63605012600014FDC85ACDCE26103_1772442484238941528

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager) (tried Java_com_mapbox_maps_assets_AssetManagerProvider_initialize and Java_com_mapbox_maps_assets_AssetManagerProvider_initialize__Landroid_content_res_AssetManager_2)
       at com.mapbox.maps.assets.AssetManagerProvider.initialize(AssetManagerProvider.java)
       at com.mapbox.maps.MapController.<init>(MapController.kt:64)
       at com.mapbox.maps.MapView.<init>(MapView.kt:104)
       at com.mapbox.maps.MapView.<init>(MapView.kt:55)
       at com.mapbox.maps.MapView.<init>(MapView.kt:55)
       at org.odk.collect.mapbox.MapboxMapFragment.onCreateView(MapboxMapFragment.kt:143)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:623)
       at org.odk.collect.androidshared.ui.DialogFragmentUtils.showIfNotShowing(DialogFragmentUtils.kt:60)
       at org.odk.collect.androidshared.ui.DialogFragmentUtils.showIfNotShowing(DialogFragmentUtils.kt:40)
       at org.odk.collect.androidshared.ui.DialogFragmentUtils.showIfNotShowing(DialogFragmentUtils.kt:31)
       at org.odk.collect.android.widgets.items.SelectOneFromMapWidget$onCreateAnswerView$1$1.granted(SelectOneFromMapWidget.kt:48)
       at org.odk.collect.permissions.PermissionsProvider$requestEnabledLocationPermissions$1.granted(PermissionsProvider.kt:88)
       at org.odk.collect.permissions.PermissionsProvider$requestPermissions$safePermissionsListener$1.granted(PermissionsProvider.kt:217)
       at org.odk.collect.permissions.DexterRequestPermissionsAPI$createMultiplePermissionsRequest$1.onPermissionsChecked(RequestPermissionsAPI.kt:74)
       at com.karumi.dexter.DexterInstance$1.run(:43)
       at com.karumi.dexter.MainThread.execute(:6)
       at com.karumi.dexter.DexterInstance.checkMultiplePermissions(:71)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5431 

#### What has been done to verify that this works as intended?
I've tested the fix manually and also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I was thinking about importing all settings like before and checking if Mapbox is supported before starting maps but this solution seems to be better/clearer and easier to test automatically.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I've implemented changes in the code responsible for importing new settings so that's the area of risk. The intended change is to only exclude settings unsupported by a particular device we use. At this moment the only setting that might be unsupported is Mapbox.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
> I was thinking about importing all settings like before and checking if Mapbox is supported before starting maps but this solution seems to be better/clearer and easier to test automatically.

I don't think I agree. Would we not be able to just add a `MapboxClassInstanceCreator.isMapboxAvailable()` check in `MapFragmentFactoryImpl` to fix this, and then we wouldn't have to make any changes to settings import? That change would feel simpler to me, as it's much more isolated - settings code doesn't need to care about Mapbox. Granted, that's potentially a little harder to test, but we could convert `MapboxClassInstanceCreator` to an interface we can mock or inject the helper as a function to it simpler to add a test to `MapFragmentFactoryImpl`.

**Comment by grzesiek2010** [comment]
> Would we not be able to just add a MapboxClassInstanceCreator.isMapboxAvailable() check in MapFragmentFactoryImpl to fix this

This would be possible but I still like my solution more:
- I like that we protect users from importing settings that are not supported so that then we don't have to add more checks like `MapboxClassInstanceCreator.isMapboxAvailable()` and we are just safe. 
- I like that we don't have to switch between map providers when we open maps using an unsupported provider.
- I like that it happens in a separate module (`settings`) and testing is easier.
- I like that in the future we might need to exclude other settings too and this approach makes it easy.

Of course, if you strongly disagree we can discuss it.

**Review by seadowg — CHANGES_REQUESTED** [review]
> - I like that it happens in a separate module (`settings`) and testing is easier.
> - I like that in the future we might need to exclude other settings too and this approach makes it easy.

These really sell it for me. I'm convinced!

One thing that feels a little weird is that unsupported settings apply ambiguously over general/admin keys. This isn't a problem right now, as `basemap_source` only exists in `general`, but it seems like it could be a risk in the future (and I think it it would be an easy thing to miss). Could we be a bit more protective here and specify the settings "section" (general, admin or project) as well as the key?

**Comment by grzesiek2010** [comment]
> One thing that feels a little weird is that unsupported settings apply ambiguously over general/admin keys. This isn't a problem right now, as basemap_source only exists in general, but it seems like it could be a risk in the future (and I think it it would be an easy thing to miss). Could we be a bit more protective here and specify the settings "section" (general, admin or project) as well as the key?

Yeah it's a good idea. I've just implemented that.

File: shared/src/main/java/org/odk/collect/shared/collections/CollectionExtensions.kt [hunk 1]
```diff
@@ -8,4 +9,13 @@ object CollectionExtensions {
         val index = abs(any.hashCode()) % this.size
         return this[index]
     }
+
+    fun JSONArray.has(value: Any): Boolean {
```
Comment (seadowg) [inline shared/src/main/java/org/odk/collect/shared/collections/CollectionExtensions.kt:13]: I think this should be `contains` instead to be more consistent with Java's `Collection`.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
I think I've encountered the same error as mentioned in the issue #5431 using physical devices - not sure if it's connected. I'm able to reproduce this error on this PR on on the master version. We verified it on Android 8.1, 10, 13 (unable to verify it on Samsung device because of how "no background processes" work on it - I guess)
#### Steps to reproduce the problem
1. In device settings choose "no background processes".
2. Go to Collect and choose Mapbox as a source of maps.
3. Go to the demo project and open Select one from map form.
4. Go to the second question in the form.
5. Minimize the app and go to a different app.
6. Go back to Collect. The form should open in the hierarchy view.
7. Go to the first question and tap "select place".
After that the app crashes.
noimplementation

**Comment by grzesiek2010** [comment]
Ok, that would mean there are two ways to cause the same exception. You can continue testing because fixing your case can but does not have to be a part of this pull request.

File: shared/src/main/java/org/odk/collect/shared/collections/CollectionExtensions.kt (hunk 1 above)
Comment (grzesiek2010) [reply shared/src/main/java/org/odk/collect/shared/collections/CollectionExtensions.kt:13]: In `JSON` world it's rather `has`, for example, JSONObject has `has` function so I wanted to make it consistent.

**Comment by grzesiek2010** [comment]
@dbemke that crash after returning to the app should be fixed too so please test both ways.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10, emulated Android 13, 7.0

**Verified Cases:**
- issue #5431 and the issue mentioned in the PR are no longer reproducing
- devices with Mapbox and without Mapbox
- don’t keep activities, no background processes settings
- changing project settings (e.g. the sources of maps) and creating a QR code to scan

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 12,13
