### PR TITLE
Fix navigation buttons not showing above keyboard

### LINKED ISSUE #7169: Keyboard covers "Next" and "Back" buttons
#### ODK Collect version
the master version 99c9a577bd664e27c5ce684ba3d895d481143a4e
(the issue doesn’t occur in the store version 2026.1.2)
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In a question which opens the keyboard (e.g. string widget) buttons "Next", "Back" are hidden under the keyboard. The buttons should be displayed above the keyboard.

The screenshot: the store version on the left, the master version on the right.

Image

#### Steps to reproduce the problem
1. Download the demo project and open All question types form.
2. Go the String question (the keyboard is opened).
3. Check where "Back" and "Next" buttons are.
#### Expected behavior
"Back" and "Next" buttons should be displayed above the keyboard.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7169

#### Why is this the best possible solution? Were any other approaches considered?

I just applied the helpers @grzesiek2010 wrote to solve this specific issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Nothing has changed other than the issue hopefully being fixed.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -522,6 +523,8 @@ public void save() {
 
         addMenuProvider(menuProvider, this);
 
+        applyBottomBarInsetMargins(findViewById(R.id.buttonholder));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Was there a specific reason for placing this here? I would expect it to be called right after `setView`, since both perform adjustments using `EdgeToEdge` utilities.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Androids: 8.1, 10 

**Verified cases:**
- issue #7169 doesn't occur
- opening keyboard in questions on a field-list
- position of navigation buttons in Collect when keyboard is opened and there's gesture navigation and 3-button navigation set in the device
- position of navigation buttons in Collect with a floating keyboard, one-handed keyboard and other available options
- position of navigation buttons in Collect when keyboard is being manually moved at the bottom of the screen  and when keyboard size changes
- navigation buttons in portrait and landscape view
- positions of navigation buttons, keyboard and snackbars
- switching to swipe navigation in Collect settings and back

**Comment by WKobus** [comment]
**Tested with success**

Verified on phone and tablet with android 16
