### PR TITLE
Fix collection status not updating

### LINKED ISSUE #7032: Number of points entered is updated with a delay in geoshape and geotrace
#### ODK Collect version
master version 3daae3e6a8e9d697d401de74f90540fdf143cffb
#### Android version
16, 10 
#### Device used
Pixel 6a, Redmi 7
#### Problem description
Number of points entered is updated with a delay in geoshape and geotrace.

Issue does not occur on store version v2025.3.3
#### Steps to reproduce the problem
1. Go to all question types form
2. Go to Geotrace or Geoshape question
3. Add some points
4. Remove some points
#### Expected behavior
Number of points entered should be updated immediately after adding or removing a point

https://github.com/user-attachments/assets/8b7c9ecf-281b-456c-b64a-2afbf5f672b0

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7032

#### Why is this the best possible solution? Were any other approaches considered?

Nothing to discuss here really!

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyFragmentTest.kt [hunk 1]
```diff
@@ -132,6 +134,17 @@ class GeoPolyFragmentTest {
         onView(withId(R.id.record_button)).check(matches(isDisplayed()))
     }
 
+    @Test
+    fun placingPoint_updatesCollectionStatus() {
```
Comment (seadowg) [inline geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyFragmentTest.kt:138]: There's definitely more missing tests for `GeoPolyFragment`. I'm going to do a dedicated piece of work to add tests for the automatic location recording.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10

**Verified cases:**
- issue #7032 doesn't occur

**Comment by srujner** [comment]
**Tested with Success!**

Verified on devices with Android 12

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on devices with Android 16
