### PR TITLE
Remove code causing points to be added on rotate

### LINKED ISSUE #7048: Rotating device in geoshape/geotrace question while automatic location recording is active creates a point
#### ODK Collect version
84779f3f2269065dc5a919f9666e82b7123ae675
#### Android version
16, 10
#### Device used
Pixel 6a, Redmi 7
#### Problem description
Rotating device in geoshape/geotrace question while automatic location recording is active creates a point, I'm not sure if this is other issue or related to this one but sometimes after creating points by rotation on google maps, points are created automatically quicker than interval set, for example every 10-15 sec when interval is set to 30 mins

Issue does not occur on store version v2025.3.3
#### Steps to reproduce the problem
1. Go to demo project
2. Open all question types form
3. Go to geotrace question
4. Set automatic location recording with 30 min interval and accuracy requirement set to none
5. Rotate device while automatic location recording is active
#### Expected behavior
Points should not be added on rotation 

https://github.com/user-attachments/assets/cdc70599-f5a0-45e9-bf4d-5803fe3394ae

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7048

#### Why is this the best possible solution? Were any other approaches considered?

This was just some leftover, untested code causing problems.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Just fixes the bug. No need to test with different maps.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java [hunk 1]
```diff
@@ -459,8 +459,7 @@ public <D extends Page<D>> D pressBackAndDiscardForm(D destination) {
     }
 
     public FormEntryPage assertBackgroundLocationSnackbarShown() {
-        onView(withId(com.google.android.material.R.id.snackbar_text))
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java:462]: This failed for me when running `./gradlew testLab`

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10 

**Verified cases:**
- issue #7048 doesn't occur

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16
