### PR TITLE
Set User-Agent string for osmdroid

### LINKED ISSUE #3248: OpenStreetMap does not display on Androids 5 and higher
#### Software and hardware versions 
Collect v1.23.x, Android v5.1, 6.0, 7.0, and 8.1, device used...

#### Problem description
OpenStreetMap does not display when using Geo widgets.
Screenshot_2019-07-26-11-31-46

#### Steps to reproduce the problem
1. Choose in General Settings Maps/OpenStreetMap
2. Open Geopoint/GeoTrace/GeoShape widget
3. Click on Start button

#### Expected behavior
OpenStreetMap should load.

#### Other information 
Other types of map display correctly on Android 5.1 and higher
Interesting is that it displays correctly on Android 4.4 and lower.

### LINKED ISSUE #3252: Configure osmdroid to provide Collect User-Agent string to tile servers
We are supposed to identify the Collect app to tile servers: https://github.com/osmdroid/osmdroid/wiki/Important-notes-on-using-osmdroid-in-your-app#set-the-http-user-agent-variable

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3252
Closes #3248

I have communicated with OSM and they have advised us to change the User-Agent string.

#### What has been done to verify that this works as intended?
Verified that we follow [the osmdroid instructions](https://github.com/osmdroid/osmdroid/wiki/Important-notes-on-using-osmdroid-in-your-app#set-the-http-user-agent-variable).

Used the [network profiler](https://developer.android.com/studio/profile/network-profiler) to look at the request details while loading an osmdroid-rendered map and verified that the User-Agent header is as expected (Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-T285 Build/LMY47V) org.odk.collect.android/v1.23.0-beta.4-9-g4cb530c69).

#### Why is this the best possible solution? Were any other approaches considered?
I moved the `getUserAgentString` method to the application level so all components that send user agent strings can use a consistent one.

I considered also addressing https://github.com/opendatakit/collect/issues/3253 but since I'm not totally sure it's without risk and it's not really a fix, I figured we can do this for the next release.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

It should not affect users.

It does affect tile servers that we pull from, though, because now they'll be seeing a new User-Agent string. In particular, this will bring back access to OpenStreetMap tiles which violates their terms of service. We should wait until we learn more about #3248 before merging.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java [hunk 1]
```diff
@@ -208,6 +209,19 @@ public String getVersionedAppName() {
         return getString(R.string.app_name) + versionName;
     }
 
+    /**
+     * Get a User-Agent string that provides the platform details followed by the application ID
+     * and application version name: {@code Dalvik/<version> (platform info) org.odk.collect.android/v<version>}.
+     *
+     * This deviates from the recommended format as described in https://github.com/opendatakit/collect/issues/3253.
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/application/Collect.java:216]: Not a big deal, but I like putting the app ID first, at least in the long term.  Did you keep `Dalvik` first because you'd prefer to keep it first, or just to minimize changes for now?

**Review by zestyping — APPROVED** [review]

**Comment by zestyping** [comment]
This looks great!

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:216]: Yes, I do as well. I thought it was nice to have a single place where we generate a User-Agent string. And since changing it for all HTTP requests is more of an enhancement than a fix, I'd rather give a chance for #3253 to get comments and do it after v1.23 is out so it can spend some time in beta. I don't think changing it for osmdroid then will have any repercussions.

**Comment by mmarciniak90** [comment]
@lognaturel this pr does not have assigned version. Do we want to have it in v1.23?

**Comment by lognaturel** [comment]
Sorry about that. Yes, please. I initially wasn't sure it would be a fix for #3248 but it turns out to be.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 6.0, 7.0, 8.1

I confirm cases:
- OpenStreetMap displays correctly
- Offline layers are able to be applied on OpenStreetMap
- Verified GeoPoint, GeoShape, GeoTrace

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
