### PR TITLE
In audit log, only include position predicates for repeats

### LINKED ISSUE #3126: Node position inclusion in audit log path is inconsistent for field lists
#### Software and hardware versions 
Collect v1.22

#### Problem description
With the addition of change tracking for the audit, there are now events logged for questions in field lists that have value changes. When the field list is first logged, the field list node path looks something like `/data/my-field-list`. However, when there are changes to values in the field list, their paths include an index after the group and look like `/data/my-field-list[1]/my-field`.

That's because position predicates are trimmed off terminal nodes but not any others.

In general, it's unexpected to have indexes in the case of anything other than repeats since there can't be two nodes of the same name. It's particularly visible in the case of field lists because of the inconsistency.

#### Steps to reproduce the problem

Fill a form with groups and track changes turned on such as https://docs.google.com/spreadsheets/d/1CItY6bdAeEYPVx8CxB_e4jKF2IkZfrDQ4X3tac94TYQ/edit#gid=0

Notice that all groups have position predicates that look like `[1]` after them. For example: `/audit-group-multiplicity/g1[1]/g2[1]/g3[1]/q3`. However, `/audit-group-multiplicity/g1/g2/g3/q3` would always be sufficient to identify the proper node and is easier for humans to deal with. That's presumably why the final position predicate was trimmed.

The thing that is bothersome is `/audit-group-multiplicity/fl1` followed by `/audit-group-multiplicity/fl1[1]/q6`.

| event           	| node                                           	| start         	| end           	| old-value 	| new-value 	|
|-----------------	|------------------------------------------------	|---------------	|---------------	|-----------	|-----------	|
| form start      	|                                                	| 1559590967376 	|               	|           	|           	|
| question        	| /audit-group-multiplicity/g1[1]/q1             	| 1559590967378 	| 1559590968994 	|           	| Vui       	|
| question        	| /audit-group-multiplicity/g1[1]/g2[1]/q2       	| 1559590968998 	| 1559590970568 	|           	| Vj        	|
| question        	| /audit-group-multiplicity/g1[1]/g2[1]/g3[1]/q3 	| 1559590970570 	| 1559590971800 	|           	| Bi        	|
| add repeat      	| /audit-group-multiplicity/r1[1]                	| 1559590971802 	| 1559590972985 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[1]/q4             	| 1559590972994 	| 1559590974275 	|           	| Gi        	|
| add repeat      	| /audit-group-multiplicity/r1[1]/r2[1]          	| 1559590974276 	| 1559590975623 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[1]/r2[1]/q5       	| 1559590975626 	| 1559590977085 	|           	| Bio       	|
| add repeat      	| /audit-group-multiplicity/r1[1]/r2[2]          	| 1559590977087 	| 1559590978264 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[1]/r2[2]/q5       	| 1559590978266 	| 1559590979469 	|           	| Gi        	|
| add repeat      	| /audit-group-multiplicity/r1[1]/r2[3]          	| 1559590979471 	| 1559590980858 	|           	|           	|
| add repeat      	| /audit-group-multiplicity/r1[2]                	| 1559590980859 	| 1559590981691 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[2]/q4             	| 1559590981694 	| 1559590983047 	|           	| Giyi      	|
| add repeat      	| /audit-group-multiplicity/r1[2]/r2[1]          	| 1559590983048 	| 1559590985743 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[2]/r2[1]/q5       	| 1559590985745 	| 1559590987104 	|           	| Bk        	|
| add repeat      	| /audit-group-multiplicity/r1[2]/r2[2]          	| 1559590987106 	| 1559590988892 	|           	|           	|
| add repeat      	| /audit-group-multiplicity/r1[3]                	| 1559590988893 	| 1559590990349 	|           	|           	|
| question        	| /audit-group-multiplicity/r1[3]/q4             	| 1559590990351 	| 1559590991701 	|           	| O         	|
| add repeat      	| /audit-group-multiplicity/r1[3]/r2[1]          	| 1559590991702 	| 1559590993146 	|           	|           	|
| add repeat      	| /audit-group-multiplicity/r1[4]                	| 1559590993148 	| 1559590994690 	|           	|           	|
| group questions 	| /audit-group-multiplicity/fl1                  	| 1559590994691 	| 1559590998470 	|           	|           	|
| question        	| /audit-group-multiplicity/fl1[1]/q6            	| 1559590994693 	| 1559590998470 	|           	| Fu        	|
| question        	| /audit-group-multiplicity/fl1[1]/q7            	| 1559590994694 	| 1559590998470 	|           	| Fj        	|
| end screen      	|                                                	| 1559590998471 	| 1559590999618 	|           	|           	|
| group questions 	| /audit-group-multiplicity/fl1                  	| 1559590999619 	| 1559591005209 	|           	|           	|
| question        	| /audit-group-multiplicity/fl1[1]/q6            	| 1559590999621 	| 1559591005209 	| Fu        	| Fp        	|
| question        	| /audit-group-multiplicity/fl1[1]/q7            	| 1559590999622 	| 1559591005209 	| Fj        	| Fg        	|
| end screen      	|                                                	| 1559591005210 	| 1559591006270 	|           	|           	|
| form save       	|                                                	| 1559591006270 	|               	|           	|           	|
| form exit       	|                                                	| 1559591006270 	|               	|           	|           	|
| form finalize   	|                                                	| 1559591006271 	|               	|           	|           	|

#### Expected behavior
I'm not sure what, if anything, we should do about this. It has been this way since the audit feature was released. For someone actually using the XPath path to link an audit row to form contents, the two paths are equivalent so it doesn't matter.

For users doing visual inspection, it's just visual noise they can overlook and probably not a big deal.

But for folks who have written scripts to process the audit, changes to the node format would break their tools. Even though the field list inconsistency is bothersome, it's probably easy enough to explain.

I'm inclined not to do anything about this but wanted to think through it and point it out while the release is still fresh.

What do others think? @grzesiek2010 @yanokwa

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3126
Alternative to opendatakit/javarosa#469, builds on #3227

#### What has been done to verify that this works as intended?
Look at audit generated by [nested-repeats-for-audit.xml.txt](https://github.com/opendatakit/collect/files/3423909/nested-repeats-for-audit.xml.txt) which has nesting of groups and repeats.

#### Why is this the best possible solution? Were any other approaches considered?
My first inclination was to modify the `TreeReference.toString` as done in opendatakit/javarosa#469. But as I was reviewing that solution, I saw a number of issues with it:
- clients could be depending on the current `toString` implementation
- `TreeReference`s can be used to represent references in secondary data instances which may have sequences of elements that are not backed by XForms repeats
- `TreeReference`s don't currently have a link to a specific `FormDef`

I didn't realize these subtle issues were there until I thought through it deeply.

My main goal in designing an alternative was not to increase coupling between `TreeReference` and `FormDef`. `FormIndex` actually already bridges the two and `AuditEvent` keeps track of `FormIndex` objects so it seems natural to use them.

`FormIndex` objects are only related to the primary instance and they only have a value other than `-1` for `instanceIndex` at layers that represent repeats.

This solution walks the `FormIndex` linked list to get the position predicates while using the `TreeReference` field to get the names of the nodes. I think it's the simplest possible solution.

I think we'll want to move this into `FormIndex` but it will be easier to review and QA here for now. An unfortunate side effect of making `getXPathPath` a static method is that we end up needing real `FormIndex` objects for tests. I think it's still more sensible than making it an instance method in `AuditEvent` and we can either go back to mocking the toString or perhaps restructure the tests to make the cases clearer when the method moves. `AuditEventSaveTaskTest.getTestFormIndex` is certainly not good because it does a whole bunch of work that is not real Collect code.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Position predicates will only be added to nodes that are backed by repeats. This has the potential to be disruptive depending on the kind of analysis people are doing but it's important to make sure we're spec-compliant.

#### Do we need any specific form for testing your changes? If so, please attach one.
[nested-repeats-for-audit.xml.txt](https://github.com/opendatakit/collect/files/3423909/nested-repeats-for-audit.xml.txt) and [audit-group-multiplicity.xml.txt](https://github.com/opendatakit/collect/files/3423989/audit-group-multiplicity.xml.txt)
[test.xml.txt](https://github.com/opendatakit/javarosa/files/3417581/test.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
https://github.com/opendatakit/xforms-spec/issues/248

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
I hope @grzesiek2010 will be taking it easy and healing tomorrow and not doing too much code review! @kkrawczyk123, @mmarciniak90, would you consider testing without code review since this is so targeted and can easily be swapped out later if a better approach is found? 

Alternately, I know there's a lot of JavaRosa context involved that you probably haven't looked at yet, @seadowg, so I understand if a deep review feels like it's hard to do but perhaps you could evaluate that and review if you feel like you can? I added a bunch of comments to `FormIndex` that hopefully help in making sense of this.

**Comment by seadowg** [comment]
@lognaturel I'm going to have to look at some docs around how this feature works but will have a go.

File: collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java [hunk 1]
```diff
@@ -273,4 +272,35 @@ private String getEscapedValueForCsv(String value) {
...
+     * Differs from {@link TreeReference#toString()} in that position predicates are only
+     * included for repeats. For example, given a group named {@code my-group} that contains a
+     * repeat named {@code my-repeat} which in turn contains a question named {@code my-question},
+     * {@link TreeReference#toString()} would return paths that look like
+     * {@code /my-group[1]/my-repeat[3]/my-question[1]}. In contrast, this method would return
+     * {@code /my-group/my-repeat[3]/my-question}.
+     *
+     * TODO: consider moving to {@link FormIndex}
+     */
+    private static String getXPathPath(FormIndex formIndex) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java:288]: It makes sense me that this should be either a `private` (`static`) method in `AuditEvent` as it doesn't seem to be used outside to the object and it hasn't been tested in isolation. I'm guessing having it `static` is because you plan to move it to `FormIndex`?

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java:288]: Yes, exactly.

**Comment by yanokwa** [comment]
This PR is blocking the beta and hasn't been tested. I think it's important to get the beta out today, so I'm going to merge and ask the testers to try this after the code freeze. If there are issues, those will be filed and fixed before final release.

This is a change in process, but I've confirmed with @lognaturel that this PR is low-risk.

**Comment by mmarciniak90** [comment]
**Tested  with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0

The noticed difference is highlighted in blue.
Groups do not have [...]. Repeat groups contain information in [...].

|Form | 1.22.2 | Master 1.23 |
|---|---|---|
|nested-repeats-for-audit.xml|Screenshot_2019-07-25-12-35-21|Screenshot_2019-07-25-11-33-31|
|test.xml |Screenshot_2019-07-25-15-16-24|Screenshot_2019-07-25-14-16-17|

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
Thank you, @mmarciniak90!
