### PR TITLE
Fixed starting form filling twice

### LINKED ISSUE #5246: Ignoring or saving changes in a form entered by a created shortcut opens a new form if „Don’t keep activities” is on
**Software and hardware versions** 

Collect v2022.1.2, Android probably all

**Problem description**

When in a device settings „Don’t keep activities” is turned on, ignoring or saving the changes in a shortcut for a form from ODK Collect results in unexpected behavior. First, the form closes and immediately after that a new form is opened. 

https://user-images.githubusercontent.com/56479916/184151713-88fb47a1-f9d0-4689-8148-37417b3781cf.mp4

**Steps to reproduce the problem**

1. In device setting turn on „Don’t keep activities”.
2. Create a shortcut for any form from ODK Collect.
3. Go to the form by clicking the shortcut icon.
4. Click device back button.
5. Click „Ignore Changes” or „Save Changes”.

**Expected behavior**

The form should be closed.

**Other information** 

If the user chose „Save changes” the data is not lost.
Collect v2021.2.0 works as expected.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5246 

#### What has been done to verify that this works as intended?
I've verified the fix manually and added automated tests.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This is a change in the code that is responsible for staring forms not directly from the list of forms in the app but from shortcuts or external apps (see: https://github.com/grzesiek2010/collectTester)

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt [hunk 1]
```diff
@@ -49,13 +55,16 @@ class FormUriActivity : ComponentActivity() {
             logAnalytics(uriProjectId)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Do you think we should move the analytics call so that it doesn't fire twice if the activity is recreated? Not a huge deal, but it does taint the numbers.

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Yeah why not. Done.

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt [hunk 2]
```diff
@@ -46,16 +52,19 @@ class FormUriActivity : ComponentActivity() {
...
             if (projectId == currentProjectProvider.getCurrentProject().uuid) {
-                openForm.launch(
-                    Intent(this, FormEntryActivity::class.java).also {
-                        it.action = intent.action
-                        it.data = uri
-                        intent.extras?.let { sourceExtras -> it.putExtras(sourceExtras) }
-                    },
-                )
+                if (!formFillingAlreadyStarted) {
+                    logAnalytics(uriProjectId)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: I don't think moving this here is correct, `logAnalytics` was being called in the case where `projectId` did not equal `currentProjectProvider.getCurrentProject().uuid` before. It might be that you just want to split out the different events in `logAnalytics` into individual calls.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Yes but if I put it in that else block I would also need to make sure to log it only once not like now. Plus i'm wondering if we need it there... in that case we just display a dialog and that's it maybe we should have those logs only for cases where form filling is really started?

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 8.1, 11 (unable to create a shortcut on Xiaomi Redmi 9T Android 10)

**Verified cases:**

- issue #5246 is no longer reproducing
- saving and ignoring changes in forms from shortcuts
- filling forms from shortcuts from different projects saving/finalizing/ignoring changes
- editing forms saved from shortcuts and saving/ignoring changes
- opening forms form shortcuts when ODK Collect is switched to different project
- resuming a form from a shortcut after closing it by killing the app
- changing project settings while filling a form from a shortcut and going back to the form
- starting a form from an external app: ODK Collect Intents Tester (checked also on Android 10)
- don’t keep activities enabled/disabled

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Yeah actually, now I think about it, I'm not sure if I particularly care about those analytics events any longer. All three events have fired 1000s of times, so there's no "dead code" and I don't think we're close to being able (or needing) to deprecate form URI actions without project IDs. Can we just kill analytics here rather than reworking the code for it @lognaturel?

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android: 13 (On Emulator)

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: @lognaturel said that we can get rid of it so I will do that.

**Review by seadowg — APPROVED** [review]
