### PR TITLE
Fixed the 'Reset app' dialog

### LINKED ISSUE #4979: White progress dialog is visible when reset settings in dark mode
#### Software and hardware versions 
Collect v2022.1 Android vx.x.x, device used...

#### Problem description
I have noticed a small regression issue connected to the progress bar dialog displayed when reset settings in dark mode, it's white. See gif:
ezgif com-gif-maker (19)_2022

the same case from v2021.3:
ezgif com-gif-maker (19)2021

#### Steps to reproduce the problem
1. Set dark mode
2. Reset settings 

#### Expected behavior
Progress dialog should not be white when dark mode is selected.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4979

#### What has been done to verify that this works as intended?
I tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
I replaced android progress dialog with our ProgressDialogFragment which works well with themes and is used in many other places.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue and has no side effects.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java [hunk 1]
```diff
@@ -143,10 +143,11 @@ protected void onPostExecute(List<Integer> failedResetActions) {
     }
 
     private void showProgressDialog() {
-        progressDialog = ProgressDialog.show(context,
-                        context.getString(R.string.please_wait),
-                        context.getString(R.string.reset_in_progress),
-                        true);
+        progressDialog = new ProgressDialogFragment();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java]: Keeping references to Fragments can be dangerous/flakey - if the host Activity is recreated, the Fragments will be as well, and we might end up with a reference to one of multiple fragments or no reference at all when we come to call `hideProgressDialog`.

We should switch to using `DialogFragmentUtils.showIfNotShowing`/`DialogFragmentUtils.dismiss` here for managing the dialog. That might mean pulling out a new subclass (see `FormLoadingDialogFragment`) or we could add a new overload to `DialogFragmentUtils` that lets us pass a tag in (as it currently always uses the class to calculate the tag).

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java]: It was my firs solution but I ended up with some test failing on Firebase that I wasn't able to reproduce locally. Surprisingly this solution doesn't cause problems. I will give it another try maybe I missed something obvious since yesterday I also felt under the weather after getting my booster dose.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java]: Ok I was able to make it work so looks like I was affected by booster does indeed :smile:

File: collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialogTest.kt [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+            assertThat((it.dialog!! as AlertDialog).getButton((AlertDialog.BUTTON_POSITIVE)).visibility, `is`(View.GONE))
+
+            // Button neutral
+            assertThat((it.dialog!! as AlertDialog).getButton((AlertDialog.BUTTON_NEUTRAL)).visibility, `is`(View.GONE))
+
+            // Button negative
+            assertThat((it.dialog!! as AlertDialog).getButton((AlertDialog.BUTTON_NEGATIVE)).visibility, `is`(View.GONE))
+
+            // Title
+            val titleId: Int = context.resources.getIdentifier("alertTitle", "id", context.packageName)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialogTest.kt]: We could make it much easier to test `ProgressDialogFragment` implementations by simply adding getters for title and message - these being rendered properly is tested in `ProgressDialogFragmentTest`. Let's add them now. I think given that we're testing that this is a correctly configured `ProgressDialogFragment` we also don't need to test the buttons (as they wouldn't be there by default).

**Review by seadowg — CHANGES_REQUESTED** [review]
Looks good. Just a tweak to testing so will pass this to QA.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 8.1 and 10.

Verified cases:
- reset in dark mode
- reset in light mode
- other progress dialogs: send, delete, download form

File: collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialogTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialogTest.kt]: You mean adding getters for `title` and `message` to `ProgressDialogFragmentTest` so that we can use it in all implementations of `ProgressDialogFragmentTest`?

**Comment by srujner** [comment]
**Tested with success!**
Verified on Android 11.

**Review by seadowg — APPROVED** [review]
