### PR TITLE
Fixed using navigation buttons in tests

### LINKED ISSUE #6044: Fix `whenNavigationSettingsChangeChangesShouldBeReflectedInFormFilling`
This test failed on CI twice in a row:

- https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/8685708115223106461/details?stepId=bs.19e0c10ec17e4029&testCaseId=5&query=et.415e1b661c2b0ba7&deeplink=true
- https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/5205486052397516976/details?stepId=bs.12b8f9760166c555&testCaseId=5&query=et.415e1b661c2b0ba7&deeplink=true

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6044 

#### Why is this the best possible solution? Were any other approaches considered?
It looks like the issue here is caused by the keyboard. The form we use in that test has two questions (one text and one number question). When we navigate between them, the keyboard is automatically displayed but it changes its type (text to number and the other way around). Those two types of keyboards have different sizes and as a result, the navigation buttons that are displayed above the keyboard jump slightly. If that move takes place when in tests we try to click one of those buttons it can fail.

To test that it works well I've copied the test 50 times and run it on firebase.
 
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java [hunk 1]
```diff
@@ -196,16 +196,19 @@ public FormEntryPage deleteGroup(String questionText) {
     }
 
     public FormEntryPage clickForwardButton() {
+        waitForSoftKeyboardToSettle();
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java]: Could we close the keyboard here instead of using a `Thread.sleep`? I'm also wondering if here's some other condition we could wait for (like what's on the keyboard), but that'd be different for different kinds of questions I guess.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java]: No, closing the keyboard would also move the buttons and it would also require some delay to wait for this action to finish.

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java]: Right, but looking at `CloseKeyboardAction`, it seems like it already has code to handle the waiting (with `IdlingResource` it looks like).

Another alternative here would be to use a new custom action that does a `performClick` directly on the view. `ViewActions.click()` sends a tap event to the coordinates of the view (which I guess is the problem here if the view jumps) where as it a direct `performClick()` should still work.

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6060/files#r1567071187

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java]: Hmm now I'm playing with closing the keyboard again and it seems to work well... I can swear I've tried it before. Never mind, let's fix it in this way.

**Review by seadowg — APPROVED** [review]
