### PR TITLE
Make sure Automatic Download setting makes sense for Form Update mode

### LINKED ISSUE #3982: Automatic download checkbox should be disabled for Never periodic form update check
#### Software and hardware versions 
Collect v1.28.- current master, Android all device used...

#### Problem description
Automatic download checkbox is now enabled for default choice: Never in Periodic form updates check, see screenshots:
| master v1.28.0 | store version 1.27.3 |
| --------- | ---------|
| Screenshot (Jul 23, 2020 9_02_13 AM) | Screenshot_20200723-090551 |

#### Steps to reproduce the problem
1. Go to General Settings/ Form Management
2. Click on Automatic download checkbox without changing Periodic form updates check

#### Expected behavior
User should not be able to select automatic download checkbox when periodic form updates check is set to Never.

#### Other information 
It works well on the store version: 1.27.3, so it is a recently introduced regression issue.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #3982

#### What has been done to verify that this works as intended?

Played around with it manually and added new tests

#### Why is this the best possible solution? Were any other approaches considered?

I also considered trying to make the setting just display correctly rather than changing it when the form update changes. This seemed like it was going to end up being pretty complex though, so I just went with the path of least resistance.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the bug! Good to double check how the settings change when the form update mode changes makes sense to everyone else.

This shouldn't skip QA like the other Match Exactly PRs.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Maybe add a test for scheduled updates being canceled if the protocol changes to Google Drive?

**Comment by seadowg** [comment]
@lognaturel good call

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java [hunk 1]
```diff
@@ -90,4 +75,14 @@ public void selectingGoogleAccount_showsGoogleAccountSettings() {
...
                 .assertText(R.string.google_sheets_url);
     }
+
+    @Test
+    public void selectingGoogleAccount_disablesAutomaticUpdates() {
+        MainMenuPage mainMenu = new MainMenuPage(rule).assertOnPage()
+                .enablePreviouslyDownloadedOnlyUpdates();
+        assertThat(testDependencies.scheduler.getDeferredTasks().size(), is(1));
+
+        mainMenu.setGoogleDriveAccount("steph@curry.basket");
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java:85]: How very American.

**Review by lognaturel — APPROVED** [review]
I like the changes that came out of adding that test. 👍

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java (hunk 1 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java:85]: Heh. I'm enjoying the NBA restart but missing my team.

**Comment by seadowg** [comment]
I realized I've introduced a weird problem here where updates will be scheduled when the user changes any setting. Will revise and then request a re-review.

File: collect_app/src/main/java/org/odk/collect/android/configure/SettingsImporter.java [hunk 2]
```diff
@@ -62,7 +62,13 @@ public boolean fromJSON(@NonNull String json) {
         loadDefaults(generalSharedPrefs, generalDefaults);
         loadDefaults(adminSharedPrefs, adminDefaults);
 
-        settingsChangedHandler.onSettingsChanged();
+        for (String key: generalSharedPrefs.getAll().keySet()) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/configure/SettingsImporter.java:65]: Iterating through *ALL* the keys is future proofing really but it felt weird for `SettingsImporter` to just pass one through knowing it would do the right thing.

File: collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java [hunk 3]
```diff
@@ -77,40 +84,59 @@ public void onCreate(Bundle savedInstanceState) {
         setupFormUpdateMode();
     }
 
+    @Override
+    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) {
+        super.onSharedPreferenceChanged(sharedPreferences, key);
+
+        if (key.equals(KEY_FORM_UPDATE_MODE) || key.equals(KEY_PERIODIC_FORM_UPDATES_CHECK)) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java:91]: This is where I was getting confused when we were talking about the most recent changes. I think the split you're making is things that need to happen any time that a preference is updated even if the user is not anywhere near preferences in the app go to the custom handler which is always called by the base preference fragment. On the other hand, changes that only need to happen if the user is sitting in preferences at the moment are locally handled. Typically it would just be inline like with guidance hints but in this case since there are two keys that do the same thing, that ends up in `onSharedPreferenceChanged`. Does that sound right? I probably would have introduced a method to wrap the work that happens when either `KEY_FORM_UPDATE_MODE` or `KEY_PERIODIC_FORM_UPDATES_CHECK` changes and also defined handlers for those inline to avoid overriding `onSharedPreferenceChanged` but this is ok too.

Now that this structure is in place, I think there are things we should move from inline handlers to `CollectSettingsChangeHandler` like sending an analytics event for a server URL change, for example. Something to file an issue for v1.29 about?

File: collect_app/src/main/java/org/odk/collect/android/configure/SettingsImporter.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/configure/SettingsImporter.java:65]: One weirdness about this is that the behavior will be different depending on how the form update settings are ordered relative to the server URL and credential settings in the key set. Perhaps this can be considered at the same time as #4011.

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java:91]: Yeah I think we could use this for a lot more. Analytics is a great shout as it would let us capture more from the imports. I'd like to take a proper pass over some of these preference screens again as I was avoiding too many changes due to the AndroidX stuff being in flight. I'll add a note to my project backlog.

As to the split feeling a little weird: I agree. It might be that local changes like that are just better handles using the individual preference listeners.

**Comment by mmarciniak90** [comment]
I tried to look at this PR more comprehensively because the reported issue is no longer valid.

I noticed that:
:heavy_check_mark: Automatic download is unselected as default 
:heavy_check_mark: Automatic download is unselected as default and inactive for `Manually` mode
:heavy_check_mark: Automatic download is selected as default and inactive for `Exactly match server` mode
:heavy_check_mark: Automatic download is unselected as default and active for `Previously downloaded forms only` mode
:heavy_check_mark: First run -> user changed server to Google Drive -> `Manually` mode is set and Automatic download is unselected; all options are inactive

:heavy_check_mark: Another mode than `Manually` was selected and `Automatic download` was selected -> then user set `Manually` mode -> Automatic download is **unselected**
:warning: Aggregate server was set -> Another mode than `Manually` was selected and `Automatic download` was selected ->  then user changed server to Google Drive -> **This time, Automatic download is selected but not editable**

@seadowg, do you think that you can improve with this one marked case?

**Comment by seadowg** [comment]
@mmarciniak90 yeah that can be improved. Could you add it to #4007? I was looking at some related stuff there so would be easier to fix as part of that rather than coming back for it here if that's ok?

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
