### PR TITLE
Fixed newlines visible in submission name

### LINKED ISSUE #2913: Newlines are visible in submission name
#### Software and hardware versions 
Collect v1.20

#### Problem description
Newlines are visible in submission name

#### Steps to reproduce the problem
**Use case 1**
1. User fills form [instance_name_example.xml.txt](https://github.com/opendatakit/collect/files/2899296/instance_name_example.xml.txt)
2. User adds newlines 
3. User goes to the end view
screenshot_2019-02-25-08-04-41

**Use case 2**
1. User opens a random form.
2. User goes to the last page of the form
3. User tries to input enter/newline
4. User pastes content of the clipboard into instance name field.

#### Expected behavior
Newlines are replaced with spaces

#### Other information 
Related to #2653

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2913 #2656 

#### What has been done to verify that this works as intended?
I tested saving forms using the form attached to the issue and ordinary forms.

#### Why is this the best possible solution? Were any other approaches considered?
It's partly caused by this pr https://github.com/opendatakit/collect/pull/2653
The approach there is wrong - it should remove all newline chars but [here](https://github.com/opendatakit/collect/pull/2653/files#diff-03ff45091550285dd88b56927010c457R1155) a null value is always returned
Newline chars were not visible at the end of the form because the EditText we used had 
`android:inputType="text"`
but they were visible in the list of saved forms.

I changed it in https://github.com/grzesiek2010/collect/commit/95bbc24785400e0b6e3ff99a0e974082a6392838 and it revealed the issue.

This pr fixes the issue and now all new lines are properly replaced. They are not visible at the end of the form nor in the list of saved forms.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's not very risky but saving forms should be tested carefully. The change is related only to form names - it removes newline chars.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue which generates a name and any ordinary form where we can add any name.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/logic/FormController.java [hunk 1]
```diff
@@ -109,7 +109,9 @@
 
         public InstanceMetadata(String instanceId, String instanceName, AuditConfig auditConfig) {
             this.instanceId = instanceId;
-            this.instanceName = instanceName;
+            this.instanceName = instanceName != null
+                    ? instanceName.replaceAll("[\\p{Cntrl}]", " ")
```
Comment (cooperka) [inline collect_app/src/main/java/org/odk/collect/android/logic/FormController.java]: Let's make `"[\\p{Cntrl}]"` a constant to DRY things up -- or even better make the whole thing a TextUtils function.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 2]
```diff
@@ -1218,17 +1217,12 @@ private View createView(int event, boolean advancingPage) {
...
-                        return newText.matches(invalidCharRegex)
-                                ? newText.replaceAll(invalidCharRegex, " ")
-                                : null;
-                    }
+                InputFilter returnFilter = (source, start, end, dest, dstart, dend) -> {
+                    String newText = source.toString().substring(start, end);
+                    String invalidCharRegex = "[\\p{Cntrl}]";
+
+                    // Replace invalid characters, only modifying the string if necessary.
+                    return newText.replaceAll(invalidCharRegex, " ");
```
Comment (cooperka) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I don't understand why this logic needed to change, returning `null` here signifies that the string should be unmodified. This change seems like it would hurt performance without actually changing the behavior. Can you give more context for why this works please?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Your code almost always returned null because you used `newText.matches(invalidCharRegex)`
If you paste a text eg. `123\nfghgfh` it doesn't match `[\\p{Cntrl}]` of course, the same if the form name is created based on answers like in the sample form.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: So newlines were never returned it looked like it's in the same line because we use single line EditText.

Comment (cooperka) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Oh weird, [apparently](https://stackoverflow.com/a/8923446/763231) Java has a non-standard implementation of regex matchers. It should be `invalidCharRegex = ".*[\\p{Cntrl}].*"`. What do you think about updating the regex and keeping the `return null` performance improvement around?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: It won't work. You will be able to copy\paste a string with newline chars as a form name.

Comment (cooperka) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: All I'm suggesting is that `returnFilter` should return `null` if `invalidCharRegex` doesn't match `newText`. If it doesn't match, then of course `newText.replaceAll(invalidCharRegex)` will have no effect because there will be no replacements. It shouldn't change the behavior right?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I understand what you mean but the REGEX you mentioned is wrong:
If I have a string with one new line char eg: `aaa\naaaa` mathces() returns true but if I have two new line chars eg `aaa\n\naaa` it returns false. I could improve it, this one seems to work well `.*[\\p{Cntrl}]{1,}.*` but do you really think it's that faster? I think my approach - trying to replace newline chars every time is safer and clearer in this case.

Comment (cooperka) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Damn 🤦‍♂️ Java is a nightmare sometimes. I tried again (here's [my working example code](https://repl.it/repls/GrimyUncomfortablePlane) using an online REPL) and got a much better solution that actually works.

It does make a big impact on performance; string **matching** is quick but string **assignment** is not, so returning an unchanged string from this method causes the UI to block on unnecessary string assignments. Not a big deal most of the time, but type quickly and you'll get lag after every character you type for large strings.

My updated proposal is basically this:

```java
    Pattern p = Pattern.compile("[\\p{Cntrl}]", Pattern.MULTILINE);
    Matcher m = p.matcher(newText);
    return m.find() ? m.replaceAll(" ") : null;
```

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Ok done, but I don't think we need that second parameter `Pattern.MULTILINE` am I wrong?

**Review by cooperka — COMMENTED** [review]
I'm happy with the performance now but there's still logic duplication -- can the pattern `Pattern.compile(NEW_LINE_CHAR_REGEX)` be moved to `ApplicationConstants` along with a new method somewhere e.g. `normalizeFormName(String name)`?

I feel bad being picky like this but it seems likely that we'll eventually want to normalize the name elsewhere, or add additional logic to the normalization.

Might also be worth documenting that it matches **all** control characters not just newlines.

**Comment by grzesiek2010** [comment]
@cooperka I hope the current solution will satisfy you.

**Review by cooperka — APPROVED** [review]
Awesome 🎉

**Comment by cooperka** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
The number of spaces depends on the number of new lines. There are as many spaces as new lines.

Verified cases:
* case 1 from 2913
* case 2 from 2913
* saved form on `Edit Saved Form` list, `Send Finalized Form` list, `Delete Saved Form` list
* horizontal and vertical device orientation
* `Jump to` screen 
* long title without spaces

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by shobhitagarwal1612 — APPROVED** [review]
