### PR TITLE
Set usesEntities to true if there is an entityList attachment in the manifest

### LINKED ISSUE #6493: "usesEntities" in forms.db after upgrading Collect
#### ODK Collect version
the master version 1a10357ec4ed3f2b38ba93b4080d577404044c2c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that setting "true" in "usesEntities" column in forms.db doesn't work as expected after upgrading Collect. 
After upgrading the version of Collect only publishing new versions of forms changes the value to "true". Manually refreshing the list of blank forms (with a change in the dataset or not) doesn't set "true". Details and differences in types of forms are described in steps below.
#### Steps to reproduce the problem
1. Install the store version of Collect.
2. Scan user "trees” Qr code (with old entities spec forms and entities in the dataset). 
https://test.getodk.cloud/#/projects/576/app-users
3. Upgrade to the current master version (the apk is on Slack).
4. Go to the db files and check forms.db column "usesEntities” (the values are "null").
5. Go to "Start new form” and tap the arrow to refresh the list of blank forms.
6. Go to the db files and check forms.db column "usesEntities” (the values are "null").
7. In Central add a new entity, then go to "Start new form” and tap the arrow to refresh the list of blank forms.
8. Go to the db files and check forms.db column "usesEntities” ( follow-up form gets "false”, registration is "null").
#### Expected behavior
After upgrading the value should change to "true" in forms using entities.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6493 

#### Why is this the best possible solution? Were any other approaches considered?
As discussed in the comments and the issue, we need to mark forms downloaded before the upgrade as using entities if they indeed rely on entities. Doing this when new entities arrive seems to be the simplest and most effective approach.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This update modifies the database (specifically the useEntities column) when new entities are being downloaded to ensure that forms using entities are correctly marked, even if they existed prior to the introduction of this column. I don’t foresee any particular risks or areas needing additional careful testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java [hunk 1]
```diff
@@ -818,6 +818,59 @@ public void whenFormLacksEntityAttachmentsAndEntityBlock_downloadsAndSavesFormAs
...
+        ServerFormDetails serverFormDetailsUpdatedMediaFile = new ServerFormDetails(
+                "Form",
+                "http://downloadUrl",
+                "id",
+                "version",
+                Md5.getMd5Hash(new ByteArrayInputStream(xform.getBytes())),
+                false,
+                false,
+                new ManifestFile("", List.of(
+                        new MediaFile("file1", Md5.getMd5Hash(new ByteArrayInputStream("contents-updated".getBytes())), "http://file1", true)
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: The contents don't necessarily need to be updated! It looks like when processing an update, if `type=entityList` is seen in the manifest, the list is processed to a database even when the contents haven't changed.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: Whenever the branch at https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt#L108 is hit, the form should be marked as entity-related.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: I briefly thought that an alternative might be to move the check for an Entity List up so that it only happens if the media file contents have changed but actually we can't do that right now because the md5 hash will never match the manifest hash. We're relying on HTTP caching to not duplicate downloads. This will be improved as part of broader form download improvements.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: Ah, I looked at the details of how and where `entityAttachmentsDetected` is set and I believe that will work as desired. The test should be updated to make it clear that a content change is not necessary.

Too bad there are two passes over the manifest but we can likely improve that as part of download improvements as well.

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: > Ah, I looked at the details of how and where entityAttachmentsDetected is set and I believe that will work as desired. The test should be updated to make it clear that a content change is not necessary.

The logic needs to be updated as well if it should work in this way.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: Got it, that makes sense. I see that you've now added a special branch just for having detected any Entity List which matches https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt#L108

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java]: > Too bad there are two passes over the manifest but we can likely improve that as part of download improvements as well.

Now there is one see: https://github.com/getodk/collect/pull/6494/commits/1d92ec3d160c4624dacfc9a7684a2dbcee3c51df

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
We need to test upgrades to verify the issue- do we need the released master apk or some other apk might work?

**Comment by lognaturel** [comment]
It would be best to use a master release APK. I’ll make one as soon as I can. Unfortunately I think it will be in a couple of hours.

**Comment by dbemke** [comment]
> It would be best to use a master release APK. I’ll make one as soon as I can. Unfortunately I think it will be in a couple of hours.

Thank you. We'll test other PRs and this one probably tomorrow

**Comment by dbemke** [comment]
I'm not sure if registration form (with an old entity spec) works as expected after upgrading.
**Steps to reproduce:**
1. Install the store version of Collect.
2. Scan user "trees” Qr code (with old entities spec forms and entities in the dataset).
https://test.getodk.cloud/#/projects/576/app-users
3. Upgrade to the current master version.
4. Go to the db files and check forms.db column "usesEntities” (values: follow-up "true",  registration- "null").
5. Go to "Start new form” and tap the arrow to refresh the list of blank forms.
6. Go to the db files and check forms.db column "usesEntities” (values: follow-up "true", registration- "null").
7. In Central add a new entity, then go to "Start new form” and tap the arrow to refresh the list of blank forms.
8. Go to the db files and check forms.db column "usesEntities” (values: follow-up "true", registration- "null").

When I add a new entity and refresh the list of blank forms only follow-up form gets updated, registration form doesn't get updated cause for that form nothing changed because of the new entity so this means that in case of registration forms publishing the new version of the form would change value to "true".

**Comment by lognaturel** [comment]
The `usesEntities` values look as I expect them to. 

As you said, we're not going to detect that a form that only creates/updates Entities is entity-related until we get an update to the form itself. That's ok because forms with the old spec version don't have any offline effects. The only way to get offline effects is to update the Entity spec version. At that point, `usesEntities` should be set to `true`.

This PR only targets Entity List attachments. If you think there might be an issue with pure registration forms that don't have Entity List attachments, please file another issue.

**Comment by seadowg** [comment]
> As you said, we're not going to detect that a form that only creates/updates Entities is entity-related until we get an update to the form itself. That's ok because forms with the old spec version don't have any offline effects. The only way to get offline effects is to update the Entity spec version. At that point, usesEntities should be set to true.

The only crack in that I can see is if someone has a newer spec entity form on their device in v2024.2 and then updates to v2024.3. I think that form wouldn't have opened in v20242 so it's a pretty out there scenario, but I want to acknowledge that in that situation their form wouldn't be blocked during updates until they updated the form itself.

**Comment by lognaturel** [comment]
> I think that form wouldn't have opened in v20242 so it's a pretty out there scenario

That's a good point! This is one of the reasons we want to leave at least a month between the Collect and Central releases -- it will reduce the chance of this happening.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- #6493 works as expected
- upgrades from the store version and beta bersion

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 15
