### PR TITLE
Call media player release

### LINKED ISSUE #1639: Memory leak of FormEntryActivity because MediaPlayers are not released
#### Software and hardware versions 
Collect v1.11.0

#### Problem description
QuestionWidgets include MediaPlayers, and they are never released, causing a memory leak

#### Steps to reproduce the problem
Edit a form with a string field. Change the value. Save the form. Look for the Leak Canary message alerting you to the leak.

#### Expected behavior
Leak free-ness

### PR DESCRIPTION
**Pull request by dcbriccetti**
Android and Collect experts, please weigh in. (I am neither.)

Closes #1639 

#### What has been done to verify that this works as intended?
I filled and edited several forms and saw that no memory leaks are detected.

#### Why is this the best possible solution? Were any other approaches considered?
Being more dynamic about the use of MediaPlayers is another approach, but this one is simpler.

#### Are there any risks to merging this code? If so, what are they?
Let’s evaluate that together. Experts?

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with a string field should do.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public static QuestionWidget createWidgetFromPrompt(FormEntryPrompt fep, Context
         // for now, all appearance tags are in english...
         appearance = appearance.toLowerCase(Locale.ENGLISH);
 
-        QuestionWidget questionWidget = new StringWidget(context, fep, readOnlyOverride);
+        final QuestionWidget questionWidget;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:51]: I'm confused about the difference here. Does the scope not end up being the same?

File: collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java [hunk 2]
```diff
@@ -229,9 +232,16 @@ public static QuestionWidget createWidgetFromPrompt(FormEntryPrompt fep, Context
                     case Constants.DATATYPE_DECIMAL:
                         questionWidget = new RangeDecimalWidget(context, fep);
                         break;
+                    default:
+                        questionWidget = new StringWidget(context, fep, readOnlyOverride);
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:236]: Can't we assume `questionWidget = new StringWidget(context, fep, readOnlyOverride);` at the beginning instead of using many defaults where in all cases we use the same?

File: collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java (hunk 1 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:51]: The trouble is that if it is not used, the one created here is simply garbage collected without `release` being called on its media player.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:51]: Yep. Just realized that as I was looking at it again. 😅 Thanks!

File: collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:236]: See the conversation above!

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java (hunk 2 above)
Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:236]: Other than that problem, @grzesiek2010, I do love that you wanted to remove the duplication. I might have done the same.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:236]: It's kind of subtle. I got tripped up too because I kept thinking about the release of the `StringWidget` itself but the whole point is that the problem is with its **resources**, not itself.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java:236]: Yes, I sometimes miss C++ destructors.
