### PR TITLE
Escape markdown characters using backslashes

### LINKED ISSUE #2002: Two kinds of cursive font are visible on hints - Andoroid 4.1
#### Software and hardware versions 
Collect v1.13.2 and older 
Android 4.1

#### Steps to reproduce the problem
1. User opens `All Widget` form from demo server
2. User sees hints

screenshot_2018-03-12-15-02-44
screenshot_2018-03-12-15-03-14

#### Expected behavior
* Cursive font is the same for all text in hints

### LINKED ISSUE #2018: Markdown: escaping, newlines, paragraphs
Hi there,

We've made some non-controversial tweaks to Markdown support in Enketo that may be interesting to adopt in Collect:

* support for escaping \* and \_ and \#
* fixed various subtle header bugs
* make a distinction between paragraphs (2 or more newline chars)and simple single newline chars to fix subtle bugs

updated regexes:
https://github.com/enketo/enketo-transformer/blob/master/src/markdown.js

updated tests:
https://github.com/enketo/enketo-transformer/blob/master/test/markdown.spec.js

### PR DESCRIPTION
**Pull request by didicodes**
… Fixed #2018 "

Closes #2018  

#### Do we need any specific form for testing your changes? Yes. All Widgets.xml

### CODE REVIEW

**Comment by lognaturel** [comment]
Yes! You got the idea. I think some extra `gm,`s got in there, maybe because of replace all errors? That makes several of the tests fail. You can run the tests individually in Android Studio by clicking on the green play symbol to the left of the test header.

You also should not need any commas after `gm`. As you find the issues, you can commit them to the same branch and push to update the pull request. Thanks!

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java [hunk 1]
```diff
@@ -71,26 +71,32 @@ private TextUtils() {
...
         // links
-        text = text.replaceAll("(?s)\\[([^\\]]*)\\]\\(([^\\)]+)\\)",
+        text = text.replaceAll("/\\[([^\\]]*)\\]\\(([^)]+)\\)/gm,",
                 "<a href=\"$2\" target=\"_blank\">$1</a>");
         // headers - requires ^ or breaks <font color="#f58a1f">color</font>
         text = ReplaceCallback.replace("(?s)^(#+)([^\n]*)$", text, createHeader);
         // paragraphs
         text = ReplaceCallback.replace("(?s)([^\n]+)\n", text, createParagraph);
 
+        // escape characters for * , _
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: This comment doesn't match the code below!

Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Yeah I have been working on the tests today and I have fixed every other test apart from the @Test
    public void markDownToHtml_EscapesLessThan() which is challenging. I will make a PR when all the tests work properly.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Great! No need to make a new PR, you can simply push more commits to this same branch.

Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Okay. Thank you

**Comment by didicodes** [comment]
hello @lognaturel all the tests are working now. I have pushed the commits.

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 2]
```diff
@@ -22,22 +22,44 @@ public void textToHtml_BouncesNullInput() {
         Assert.assertNull(observed);
     }
 
+
+
+    @Test
+    public void markDownToHtmlEscapesBacklash() {
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: I like the idea of escaping backlash (a strong and adverse reaction), but this should probably be back**s**lash.

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java [hunk 3]
```diff
@@ -69,28 +69,34 @@ private TextUtils() {
...
         text = ReplaceCallback.replace("(?s)^(#+)([^\n]*)$", text, createHeader);
         // paragraphs
         text = ReplaceCallback.replace("(?s)([^\n]+)\n", text, createParagraph);
 
+        // "\" will be used as escape character for *, _
+        text = text.replaceAll(" /&/gm", "'&amp;'");
+        text = text.replaceAll("/\\\\/gm", "'&92;'");
+        text = text.replaceAll(" /\\\\*/gm", "'&42;'");
+        text = text.replaceAll(" /\\_/gm", "'&95;'");
+        text = text.replaceAll(" /\\#/gm", "'&35;'");
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: You can improve readability with this:

```
text = text
  .replaceAll(" /&/gm", "'&amp;'")
  .replaceAll("/\\\\/gm", "'&92;'")
  .replaceAll(" /\\\\*/gm", "'&42;'")
  .replaceAll(" /\\_/gm", "'&95;'")
  .replaceAll(" /\\#/gm", "'&35;'");
```

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java (hunk 2 above)
Comment (didicodes) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: oh yeah! exactly. Thank you

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java (hunk 3 above)
Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Okay. I will make the changes immediately, commit the changes and push. Thank you @dcbriccetti

**Comment by didicodes** [comment]
Hello @dcbriccetti please review.

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 4]
```diff
@@ -22,22 +22,44 @@ public void textToHtml_BouncesNullInput() {
         Assert.assertNull(observed);
     }
 
+
+
+    @Test
+    public void markDownToHtmlEscapesBackSlash() {
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: Backslash appears in the dictionary as _backslash_ (no capital s)

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 5]
```diff
@@ -22,22 +22,44 @@ public void textToHtml_BouncesNullInput() {
...
+                {"< 1/>", "&gm; 1/>"},
+                {"test < 1/>", "test &gm; 1/>"},
+                {"test < 1/>", "test &gm; 1/>"}
         };
+
         for (String[] testCase: tests) {
             Assert.assertEquals(testCase[1], TextUtils.markdownToHtml(testCase[0]));
         }
+
+
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: We probably don’t want these blank lines.

Comment (didicodes) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: Hello @dcbriccetti  I will make updates to that immediately.

**Comment by didicodes** [comment]
@dcbriccetti please review I have made changes. Thank you

**Review by dcbriccetti — COMMENTED** [review]
I’m assuming @lognaturel will be back with a final approval. I approve the implementations of the changes I requested. Thanks, @edyasikpo.

**Comment by didicodes** [comment]
oh, Okay. Thank you @dcbriccetti for your help so far. You're an amazing reviewer . 
Yes @lognaturel will make the final approval hopefully. *Fingers Crossed*

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java [hunk 6]
```diff
@@ -69,28 +69,35 @@ private TextUtils() {
...
         // headers - requires ^ or breaks <font color="#f58a1f">color</font>
         text = ReplaceCallback.replace("(?s)^(#+)([^\n]*)$", text, createHeader);
         // paragraphs
         text = ReplaceCallback.replace("(?s)([^\n]+)\n", text, createParagraph);
 
+        // "\" will be used as escape character for *, _
+        text = text
+                .replaceAll(" /&/gm", "'&amp;'")
+                .replaceAll("/\\\\/gm", "'&92;'")
+                .replaceAll(" /\\\\*/gm", "'&42;'")
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: This doesn’t look right — a single backslash should be use for the escape. Can you please add tests for this and the two escape sequences above?

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 7]
```diff
@@ -22,17 +22,34 @@ public void textToHtml_BouncesNullInput() {
...
     }
 
+    @Test
+    public void markDownToHtmlEscapesBackslash() {
+        String[][] tests = {
+                {"A\\_B\\_C", "A_B_C"},
+                {"_A\\_B\\_C_", "<em>A_B_C</em>"},
+                {"A_B\\_C", "A_B_C"},
+                {"A\\_B_C", "A_B_C"},
+                {"\\__AB\\__", "_<em>AB_</em"},
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: Looks like a > is missing.

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 8]
```diff
@@ -55,12 +72,12 @@ public void markDownToHtml_SupportsHtml() {
     @Test
     public void textToHtml_SupportsEscapedLt() {
         String[] tests = {
-                "<1",
+                ":gm; 1",
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: Can you please explain this change and the related changes to the code? :gm; is not a valid character. The desired output is indeed `&lt;`

**Review by lognaturel — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java (hunk 7 above)
Comment (didicodes) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: oh, my bad. I will make add the missing > to the code

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: I wonder how this test passed without it. Please do double check that it is indeed being run!

Comment (didicodes) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: My thoughts exactly

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java (hunk 8 above)
Comment (didicodes) [reply collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: That was suppose to be  `"&gm; 1"` not `":gm; 1"` . The reason why I made those changes was because I changed the  `text = text.replaceAll("<([^a-zA-Z/])", "&lt;$1");` from that to this ` text = text.replaceAll("<([^a-zA-Z/])", "&gm;$1");` and because of that I also had to change all the `&lt; `to &gm; to make the tests run successfully.

After studying the codes again I realized that this method public void textToHtml_SupportsEscapedLt() in the TextUtilsTest.java class is for escaping `lt;` and not `gm;`
I have modified the codes now. Please review! @lognaturel

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java (hunk 6 above)
Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Hello @lognaturel using `http://www.vogella.com/tutorials/JavaRegularExpressions/article.html#backslashes-in-java` has a proof(number 3.7. Backslashes in Java to be specific) In Java when you want to add a single backslash `\` it is done with four `\\\\` backslashes. So the codes above actually mean `.replace("/\/gm", "'&92'"`). I have added tests to proof this for the last and second to the last code above, made a commit and pushed to Git. 
But for the first line of codes is there for the theoretical case that the original string contains e.g. `"&92;"` or `"&42;"` or another internally used escape character. These strings would be converted in the subsequent lines when they shouldn't be. Martijn explained it better here `https://github.com/enketo/enketo-transformer/commit/52c60b7ad20da035661ead3ea782480ff6e40ede`
Please review

File: collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java [hunk 9]
```diff
@@ -22,17 +22,37 @@ public void textToHtml_BouncesNullInput() {
...
-            {"< 1", "&lt; 1"},
-            {"< 1/>", "&lt; 1/>"},
-            {"test< 1/>", "test&lt; 1/>"},
-            {"test < 1/>", "test &lt; 1/>"}
+                {"<1", "&lt;1"},
+                {"<1>", "&lt;1>"},
+                {"< span>", "&lt; span>"},
+                {"< 1", "&lt; 1"},
+                {"< 1/>", "&lt; 1/>"},
+                {"test < 1/>", "test &lt; 1/>"},
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java]: This test shouldn't be changed. You've now made it identical to the one below.

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java (hunk 6 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Thanks for that reference, that makes sense! That means the ones below are the ones that are wrong.

Can you please start by reverting all changes not directly related to the escape sequences? The lines before this escape block and in the `markDownToHtml_EscapesLessThan()` test should not be changed. Changing them breaks the desired markdown behavior and introduces unnecessary risk to this pull request which should be focused only on the escape sequences. Keep in mind that Enketo is written in Javascript which has slightly different regex syntax.

Second, your test isn't right which explains why it was passing even with the issues that exist. You should be comparing `testCase[1]` to `TextUtils.markdownToHtml(testCase[0])`.

The tests from Enketo were provided to make sure the implementations are exactly the same. Please include all those tests:
```
                {"A\\_B\\_C", "A_B_C"},
                {"_A\\_B\\_C_", "<em>A_B_C</em>"},
                {"A_B\\_C", "A_B_C" },
                {"A\\_B_C", "A_B_C"},
                {"A_B_C", "A<em>B</em>C"},
                {"\\__AB\\__", "_<em>AB_</em>"},
                {"\\\\_AB\\_\\\\_", "\\<em>AB_\\</em>"},
                {"A\\*B\\*C", "A*B*C"},
                {"*A\\*B\\*C*", "<em>A*B*C</em>"},
                {"A*B\\*C", "A*B*C"},
                {"A*B*C", "A<em>B</em>C"},
                {"\\**AB\\**", "*<em>AB*</em>"},
                {"\\\\*AB\\*\\\\*", "\\<em>AB*\\</em>"},
                {"\\a\\ b\\*c\\d\\_e", "\\a\\ b*c\\d_e"},
                {"\\#1", "#1"},
                {"\\#\\# 2", "## 2"},
                {"works \\#when not required too", "works #when not required too"},
                {"\\", "\\"},
                {"\\\\", "\\"},
                {"\\\\\\", "\\\\"}
```

Finally, you're handling escape sequences after markdown has already been interpreted -- it's too late. If there was an underscore in there, it already got turned to an `<em></em>` sequence.

I hope all these comments make sense. Once you revert the breaking changes and get your test working, I think you will be able to see more clearly how to approach this.

**Review by lognaturel — CHANGES_REQUESTED** [review]

**Comment by didicodes** [comment]
Hello @lognaturel I have been carefully following the suggestions you made and I've been doing a lot of research concerning the markdown sequences. So I have basically just been working on the regex and the tests and today I wanted to push the changes to my phone and see if it was still working well (clicked on the Get Blank Form) when I clicked on the form I realized that the contents of what I was trying to solve has been changed to some extent because of the end-of-the-month release.  

screenshot_2018-04-01-16-49-41
In the first picture everything looks fine here
screenshot_2018-04-01-16-49-22
but in this one there are two quotation marks and the selectone and selectmultiple still doesnt look this way `select_one` and `select_multiple`.
So my question is should I work on fixing this new issue or continue the previous one?
PS: I have been working on the issue everyday and I have learned a lot and understand regular expressions better although its a little more complicated in java and I get improvements on daily basis on the tests and its remaining just two now. I didn't want to disturb you about the updates everyday. Thank You.

**Comment by lognaturel** [comment]
Great to hear you've been learning a lot while making good progress! I think it might be worth taking a step back to make sure the overall goal is clear. You're right that the text in the All Widgets form has changed slightly but that doesn't change anything as far as escape sequences go.

The first thing to make sure is clear is that underscores, *, etc are used to style text in forms. You can see examples of that in the excellent form shared at https://forum.opendatakit.org/t/how-can-i-add-styling-like-font-color-italics-etc-to-my-forms/12542. That's what the regex currently in `TextUtils` accomplish -- when they see a matching pair of underscores, they wrap with `<em></em>`, etc.

When a form has text like `select_one and select_multiple`, the two underscores are interpreted as markdown. What we'd like to be able to do instead is change the form text to `select\_one and select\_multiple` to indicate that the underscores should not be interpreted as markdown. That escaping has to happen before the markdown interpretation.

The goal is to maintain markdown support but to allow for escaping markdown. I recommend focusing on just the emphasis (underscore) case and making sure you get that one exactly right before adding in the other ones.

Note that adding support for escaping markdown will NOT change what the All Widgets form looks like currently. We'll need to edit that form to change `select_one and select_multiple` to `select\_one and select\_multiple` to see the desired output.

**Comment by didicodes** [comment]
Hello @lognaturel First of all I **reverted** all the changes I made to codes that didn't have anything to do with the escape sequence to its original codes so it wont break the desired markdown behavior like you said in your previous comments. I noticed that trying to make text emphasis messes things up since underscore may at times mean other things depending on the context. From MartijnR codes which are written in JavaScript the markdown method he used  worked on those cases where underscore and asterisks mean something else before trying to emphasize any text but java didn't understand this.
So I had to use symbols that were not markdown to replace those cases where underscore and asterisk have another meaning aside from emphasis before applying the emphasis on it then replace those symbols with the correct ones. I've used the previous `All Widgets.xml` file and tested the codes, I added a single backslash to `select_one and select_multiple` pushed it to my phone and it worked correctly. I also pulled the latest version of the `All Widgets.xml` file and its also working well too.
**Please review**

screenshot_2018-04-02-16-09-57

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java [hunk 10]
```diff
@@ -69,20 +69,31 @@ private TextUtils() {
...
 
         text = text.replaceAll("<([^a-zA-Z/])", "&lt;$1");
         // https://github.com/enketo/enketo-transformer/blob/master/src/markdown.js
 
         // span - replaced &lt; and &gt; with <>
         text = ReplaceCallback.replace("(?s)<\\s?span([^\\/\n]*)>((?:(?!<\\/).)+)<\\/\\s?span\\s?>",
                 text, createSpan);
+
+        //intermediary replacements keys for special characters, N/B: These symbols are not meant to be interpreted as markdown
+        text = text.replaceAll("(?s)\\\\#", "==");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Now this looks like the right place for those replacements! You should be able to change them directly to their HTML escape sequences (https://www.w3.org/MarkUp/html-spec/html-spec_13.html). Using these intermediary replacement keys works but it means that those character sequences now can't be used in a form. Going straight to HTML sequences means no new characters need special meaning.

Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: Okay.
On it

**Comment by didicodes** [comment]
Made the changes and I've tested too.
screenshot_2018-04-02-20-24-52
please review @lognaturel

File: collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java [hunk 11]
```diff
@@ -69,20 +69,31 @@ private TextUtils() {
...
 
         text = text.replaceAll("<([^a-zA-Z/])", "&lt;$1");
         // https://github.com/enketo/enketo-transformer/blob/master/src/markdown.js
 
         // span - replaced &lt; and &gt; with <>
         text = ReplaceCallback.replace("(?s)<\\s?span([^\\/\n]*)>((?:(?!<\\/).)+)<\\/\\s?span\\s?>",
                 text, createSpan);
+
+        //intermediary replacements keys for special characters, N/B: These symbols are not meant to be interpreted as markdown
+        text = text.replaceAll("(?s)\\\\#", "&#61;");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: You can go straight to `&#35;` for `#`, `&#92;` for `\`, `&#95;` for `_` and `&#42;` for `*`. Otherwise you are making the intermediary characters into special characters.

Once you make those immediate changes, you should not need the two new regex for emphasis below. Then you can change back the change to `markDownToHtml_EscapesLessThan()` and change `markdownToHtml` back to `protected` and I think we'll be ready to go!

Comment (edyasikpo) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: I dont understand this part of your comment Then you can change back the change to markDownToHtml_EscapesLessThan()

Comment (didicodes) [reply collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java]: DONE @lognaturel

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Great, thanks, @edyasikpo! I'm tagging as "needs testing" so it can go through a round of quality assurance before merging.

**Comment by didicodes** [comment]
Okay. 
You have such a calm and polite way of correcting people. :smiley: 
Thank you.

**Comment by lognaturel** [comment]
😊 We're all learning together, @edyasikpo! Thanks for your patience in getting this just right.

**Comment by kkrawczyk123** [comment]
### Tested with success!
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks @edyasikpo, great to see this merged and ready to ship!!
