### PR TITLE
User is able to open more than one dialog when user quickly clicks the button several times

### LINKED ISSUE #1624: User is able to open more than one dialog when user quickly clicks the button several times
#### Software and hardware versions 
Verified on Collect v1.11.1

#### Problem description
User is able to open more than one dialog when user quickly clicks the button several times 

#### Steps to reproduce the problem
1. User quickly clicks the 'Select date' button several times 
   * Problem could also be related to other widgets.
2. Dialog appears
3. User selects date and clicks OK 
4. User sees that additional dialog is visible with default date
   * If user clicks OK on this dialog, date value will be changed

dialog

#### Expected behavior
User is not able to open two dialogs

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1624 

#### What has been done to verify that this works as intended?
I've reproduced the issue and then I tried to reproduce the issue using this branch and the attached form.

#### Why is this the best possible solution? Were any other approaches considered?
I can't see any better solution but we should wait and merge #1576 first then I should add the same fix to the coptic widget.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
[Collect1624.xml.txt](https://github.com/opendatakit/collect/files/1467314/Collect1624.xml.txt)

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Problem is still visible on widgets:
* Image widget
* Selfie widget
* Audio widget : Record Sound , Choose Sound, Play Sound
* Video widget : Record Video, Choose Video, Play Video
* Geopoint widgets
* Geoshape widgets
* Spinner widget

I verified this on Nexus 5X

**Comment by grzesiek2010** [comment]
Ok I assumed it's related to dialogs only since I was able to reproduce only this case using my device. I'm going to fix it better.

**Comment by grzesiek2010** [comment]
So the problem was more complex I thought and it required more changes but it's ready.

**Comment by mmarciniak90** [comment]
Tested with success
Verified on Android 8.0, 7.0, 4.4
- Image widget :white_check_mark:
- Selfie widget :white_check_mark:
- Audio widget : Record Sound , Choose Sound, Play Sound :white_check_mark:
- Video widget : Record Video, Choose Video, Play Video :white_check_mark:
- Geopoint widgets :white_check_mark:
- Geoshape widgets :white_check_mark: 
- Spinner widget :white_check_mark:

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Looks good to me. @jknightco would be good to get your review since you've been in that code. Also I haven't been able to run the tests against it because of the bearing issue!

File: collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java [hunk 1]
```diff
@@ -336,4 +273,71 @@ public void cancelLongPress() {
             imageView.cancelLongPress();
         }
     }
+
+    @Override
+    public void onButtonClick(int buttonId) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java:278]: Much better structure than before, thanks for moving it to this.

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java [hunk 2]
```diff
@@ -443,13 +456,28 @@ protected ImageView getAnswerImageView(Bitmap bitmap) {
...
+                    }
                 }
             }
         });
         return imageView;
     }
 
+    // This method is used to avoid opening more than one dialog or activity when user quickly clicks the button several times:
+    // https://github.com/opendatakit/collect/issues/1624
+    protected void disableViewForOneSecond(final View view) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: Is this the best way to do this? There's no way to disable input until the Dialog pops up? I'm super wary of anything time based.

**Review by heyjamesknight — APPROVED** [review]
Really like the structure changes, much easier to maintain moving forward. Would've preferred to see the refactors in a separate PR from the dialog button change—it took me a bit to figure out that the majority of the changes didn't deal with the related issue.

Approved, pending discussion around the time-based solution. If its really the best/only way to handle disabling input then we're good to go.

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: It's not related to Dialogs only. it refers to activities too. I was thinking about RxBinding https://code.tutsplus.com/tutorials/rxjava-for-android-apps-introducing-rxbinding-and-rxlifecycle--cms-28565 there is an example:

RxView.clicks(button)
    .debounce(500, TimeUnit.MILLISECONDS)
    .subscribe(aVoid -> {
      Toast.makeText(MainActivity.this, "RxView.clicks", Toast.LENGTH_SHORT).show();
    });

But I think it would be more helpful when it comes to https://github.com/opendatakit/collect/issues/1624 and then I'll investigate it deeper. I mean maybe it's not worth to add another dependency just for this case but I can refactor it and use here too if we need this (rxBinding) in https://github.com/opendatakit/collect/issues/1624

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: The RxBinding approach you're looking at there is basically the same code written a different way, right @grzesiek2010? In other words, it's still time-based. 

I think alternatives would be things like disabling the clickable thing until whatever needs to happen (dialog popup, etc) completes either with a global boolean or with code in callbacks.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: Yes RXBinding it's almost the same but it will be more convenient to use if we need to protect lots of buttons etc (in this case we protect all buttons but everything is in one place in QuestionWidget class).
That's why I said RXBinding might be a better solution for #1624.

I think your idea would be really difficult and complex and I'm not in favor of it.  

"until whatever needs to happen"
then we would have to remember about it and set such a global value in lots o different places. I think my solution is better since everything is in on onClick() method.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: I agree that the timing approach is simpler and less error-prone than anything else I'm seeing. @jknightco any other ideas to explore?

How about making the debounce time 500ms so it's less likely to block a user from real, intentional interaction.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java:477]: 500ms should be enough too. But I need to check it and confirm.

**Comment by lognaturel** [comment]
Status here is:
- @jknightco will see if he can come up with a non-time-based strategy
- if we're sticking with a time-based strategy, @grzesiek2010 will try out 500ms and rebase on master

**Comment by grzesiek2010** [comment]
> if we're sticking with a time-based strategy, @grzesiek2010 will try out 500ms and rebase on master

Done. 0.5s is enough.

**Review by lognaturel — APPROVED** [review]
