### PR TITLE
Google account validation dialog

### LINKED ISSUE #2464: Improve behavior when the user selects Google Sheet as a server but the user does not add Google Account
#### Problem description
Improve case when the user selects Google Sheet as a server but the user does not add Google Account

#### Steps to reproduce the problem
1. The user selects Google sheets as a server
2. The user does not set Google Account
3. User tries to send submissions
4. Pop up with Google accounts appears

|Step 1, 2 | Step 3 | Step 4|
|---|---|---|
|screenshot_20180809-131241|screenshot_20180809-131346|screenshot_20180809-131353|

#### Expected behavior
In discussion under #2459 was suggested that we should improve this behavior.
The expected result need to be defined.

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes #2464

#### What has been done to verify that this works as intended?

- Google Sheets was selected as the transport mechanism and no account was selected. When I tried to navigate away from the Server settings page dialog popped up asking for the account to be chosen or the transport to be changed.

- When the transport is changed the dialog no longer shows.

- Once an account has been selected the dialog no longer shows as well.

#### Why is this the best possible solution? Were any other approaches considered?
This solution was used because a similar approach was taken in #2472 

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No. 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java [hunk 1]
```diff
@@ -453,8 +456,27 @@ private void runSmsPhoneNumberValidation() {
...
+    }
+
+    private void runGoogleAccountValidation() {
+        String account = (String) GeneralSharedPreferences.getInstance().get(KEY_SELECTED_GOOGLE_ACCOUNT);
+        String protocol = (String) GeneralSharedPreferences.getInstance().get(KEY_PROTOCOL);
+
+        if (TextUtils.isEmpty(account) && protocol.equals(getString(R.string.protocol_google_sheets))) {
+
+            AlertDialog alertDialog = new AlertDialog.Builder(getActivity())
+                    .setIcon(android.R.drawable.ic_dialog_info)
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java:473]: I think for new dialogs that get added we can do away with the icon -- it doesn't look so modern! We should probably start building a design guidelines document.

File: collect_app/src/main/res/values-cs/strings.xml [hunk 2]
```diff
@@ -438,7 +438,6 @@
   <string name="sort_by_status_asc">Stav, dokončen první</string>
   <string name="sort_by_status_desc">Stav, nedokončen první</string>
   <string name="sort_the_list">Řazení seznamu</string>
-  <string name="request_permissions_google_account">ODK Collect potřebuje přístup k vašemu účtu Google, aby získal prázdné formuláře a odeslal vyplněné formuláře.</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values-cs/strings.xml]: What's the reason behind this change? It doesn't seem like it should be here!

File: collect_app/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -654,4 +654,6 @@
     <string name="image_not_saved">The image can not be saved because of a problem with the corresponding instance file.</string>
     <string name="loading_form_failed">An error occurred while loading the form. Please try again.</string>
     <string name="sms_invalid_phone_number_description">Set a destination phone number for SMS submissions or change your transport type.</string>
+    <string name="google_invalid_account_title">Google account missing!</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: No exclamation mark. I know we have some in other text but should probably reduce them because it's not something many apps tend to do.

File: collect_app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -654,4 +654,6 @@
...
+    <string name="google_invalid_account_description">Please select a Google account or change your transport type.</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: "transport type" -> "server type"

File: collect_app/src/main/res/values-cs/strings.xml (hunk 2 above)
Comment (jd-alexander) [reply collect_app/src/main/res/values-cs/strings.xml]: It doesn't! Not sure how it slipped into master but every time lint is run it fails due to it. I should have just sent it in as another PR so it could be merged in quickly.

File: collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java (hunk 1 above)
Comment (jd-alexander) [reply collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java:473]: Yeah true! That document could help. I used it for consistent reasons so when do that document we could have some more modern choices and then just create an issue where all of them could be changed.

**Comment by lognaturel** [comment]
@jd-alexander can you please also rebase this one on top of master and force push so the build goes green?

**Comment by kkrawczyk123** [comment]
@jd-alexander, in general, it works like described but I have found one case in which I can cheat on this dialog. To reproduce:
1. Choose Google Drive, Google Sheets as a server type
2. Minimize app
3. Kill an app
4. Open again and try to send finalized form - dialog to choose Google account displays. 

@opendatakit-bot unlabel "needs testing"

**Comment by jd-alexander** [comment]
@kkrawczyk123 Yes, that's the expected behaviour for the time being. When #2483 gets merged in they won't be able to select the account from the send finalized screen anymore.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Good catch, @kkrawczyk123. That was a test to make sure you're paying attention. 😁

More seriously, I think it was good to split the two parts as @jd-alexander between here and #2483 so we're sure to get some clean history.

**Comment by kkrawczyk123** [comment]
Good that I passed the test ;D
As it is expected, success then.
Verified on Androids: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 and 8.1
@opendatakit-bot label "behavior verified"
