### PR TITLE
Fix multi select widget with no-buttons appearance

### LINKED ISSUE #5821: Questions are not updated if select_multiple used with no-buttons appearance on a field-list
#### ODK Collect version

v2023.2.4

#### Problem description
The issue has been originally reported on the forum: https://forum.getodk.org/t/relevance-from-select-multiple-answers-not-triggering-while-inside-field-list-group/43627

If there is a `select_multiple` question used with `no-buttons` appearance and it's placed on a `field-list` so that the visibility of other questions depend on that first question, then other questions are not updated automatically.

#### Steps to reproduce the problem
Test the form from the forum:
[sample.xlsx](https://github.com/getodk/collect/files/13264277/sample.xlsx)
1. Navigate to the second question
2. Select one of the options
3. Other questions should appear/disappear based on the selected option

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5821

#### Why is this the best possible solution? Were any other approaches considered?

All widget implementations need to call `widgetValueChanged()` whenever their state changes for things like field list calculations to work and the call was simply missing in this case.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't change anything other than fixing the issue! It'd be good to have a quick poke around with other appearance combos for widgets in general to see if we can find any other problematic ones.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java [hunk 1]
```diff
@@ -226,6 +207,66 @@ public void whenSpacesInUnderlyingValuesExist_shouldAppropriateWarningBeDisplaye
         assertThat(warningTv.getText(), is("Warning: underlying values a a, b b have spaces"));
     }
 
+    @Test
+    public void checkingCheckboxOnItem_callsValueChangedListener() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java:211]: It would be good to add the same tests for `SelectOneWidgetTest`. That widget worked well but I think we don't have such tests there to make sure everything will be fine in the future.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
Should the answer be saved after I uncheck and check again?

https://github.com/getodk/collect/assets/85225519/7ed4ff2d-a45a-4b75-910e-9d699fdc63bc

**Comment by seadowg** [comment]
> Should the answer be saved after I uncheck and check again?

Good question? What's the behaviour like in older versions?

**Comment by dbemke** [comment]
> What's the behaviour like in older versions?

Select with no buttons didn't work in previous version (can't compare) but I changed the form so that there are buttons and compared it with this - the hidden answer is present until saving the form, after saving the form if the question was hidden the answer isn't saved... so it's the same I guess

**Comment by seadowg** [comment]
> but I changed the form so that there are buttons and compared it with this - the hidden answer is present until saving the form, after saving the form if the question was hidden the answer isn't saved... so it's the same I guess

I think if the behaviour is consistent we're ok here. As long as the question is properly irrelevant, it shouldn't matter that the answer is "remembered". I guess in some cases that would actually be really useful!

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified Cases:**
- issue #5821 isn’t reproducible
- selects on a field-list with/without buttons in a required and not required questions
- don’t keep activities enabled/disabled
- adding, removing answers and minimizing the screen
- saving, editing, sending a form with select no buttons on a field-list

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13
