### PR TITLE
Fixed getFileExtensionFromUri() method

### LINKED ISSUE #4056: The dot between name and file extension is not visible for choosed file on hierarchy view
#### Software and hardware versions 
Collect v1.27.3 (older versions were not verified)
Android: 7.0, 8.1

#### Problem description
The dot between name and file extension is not visible for choosed file on hierarchy view

#### Steps to reproduce the problem
1. User adds audio/video file from existing files on device
2. User opens hierarchy view
3. The dot between name and file extension is not visible
Screenshot_20200828-172556

#### Expected behavior
The dot between name and file extension is visible

#### Other information 
Problem is not visible for recorded files

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4056 

The problem was that in [one case](https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4056?expand=1#diff-e6929594f15505b42123fc05d98b17dcR85) getFileExtensionFromUri() returned values with dots but in [other cases](https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4056?expand=1#diff-e6929594f15505b42123fc05d98b17dcR87) without dots and that's why sometimes we had doubled dots but sometimes no dots at all.

#### What has been done to verify that this works as intended?
I tested implemented changes manually.

#### Why is this the best possible solution? Were any other approaches considered?
It's juts a bug fix so there is no other solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should be a safe change that will just fix the bug, nothing else should be affected so testing attaching and capturing media files would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media widgets like the AllWidgets form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java [hunk 1]
```diff
@@ -18,14 +18,14 @@
...
 import android.webkit.MimeTypeMap;
 
 import org.odk.collect.android.application.Collect;
 import org.odk.collect.android.logic.FormInfo;
 import org.odk.collect.android.provider.FormsProviderAPI.FormsColumns;
 import org.odk.collect.android.provider.InstanceProviderAPI.InstanceColumns;
 import org.odk.collect.android.storage.StoragePathProvider;
+import org.odk.collect.android.utilities.MediaUtils;
 
 public final class ContentResolverHelper {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java:30]: I think it'd be nice to change the name here to `...Utils` as that seems to have become idiomatic for static method buckets.

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java:30]: You mean ContentResolverUtils? What about the package then? It's in helpers package along with other classes that use helper suffixes.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java:30]: Hmmm good point. I'd be up for moving those out into `utils` (or more appropriate packages) but now is maybe not the time.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 7.0, 8.1, 10.0

| 1.27.3 | PR|
|---|---|
Screenshot_20200930-121543|Screenshot_20200930-121255|

Verified cases:
* record sound -> open hierarchy view -> one dot is visible before file extension
* add a record from existing files (select `Open from Audio` option) -> open hierarchy view -> one dot is visible before file extension
* record video -> open hierarchy view -> one dot is visible before file extension
* add a video from existing files (select `Open from Video` option) -> open hierarchy view -> one dot is visible before file extension
* remove reponse
* read only
* minimize
* light/dark mode
* RTL language

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 9.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
