### PR TITLE
Fixed downloading forms with media files

### LINKED ISSUE #3682: Unable to download form with external secondary CSV instance for the second time.
#### Software and hardware versions 
Collect current master, Android probably all, device used...

#### Problem description
When testing #3666 I have noticed one special case when a form with external CSV file becomes unuseable after trying to download it for the second time. 

#### Steps to reproduce the problem
1. Scan the code with Central access (same as attached in #3666 :
75826614-b566a980-5d5c-11ea-8e00-1071faf90336
2. Download Form with external CSV files.xml
3. You should be able to fill it
4. Go to Get Blank Form and download the same form again - you will see error message: 
Screenshot_20200305-142548
5. If you go to Fill Blank Form and try to open it you will see:
Screenshot_20200305-143824

#### Expected behavior
The User should be able to download that form more than once, as he can do with other forms. 

#### Other information 
I am aware that it is not a very common scenario - but possible especially when using Select All option on Get Blank Form view. I wasn't able to reproduce it for other forms with external CSV files.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3682

#### What has been done to verify that this works as intended?
Reproduced the scenario mentioned in the issue and confirmed it seems to be fixed.

#### Why is this the best possible solution? Were any other approaches considered?
It's the solution we agreed in the issue. There is no need to build `FormDef` if the xml file is not changed.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It changes a bit the method responsible for downloading forms and media files so it would be good to perform some regression testings in this area.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java [hunk 1]
```diff
@@ -341,8 +345,7 @@ private Uri saveNewForm(Map<String, String> formInfo, File formFile, String medi
      * Takes the formName and the URL and attempts to download the specified file. Returns a file
      * object representing the downloaded file.
      */
-    FileResult downloadXform(String formName, String url)
-            throws IOException, TaskCancelledException, Exception {
+    FileResult downloadXform(String formName, String url) throws Exception {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java:348]: This is not ideal but fine for now. It'd be better to actually enumerate the specific exceptions that can occur but `downloadFile` throws a generic `Exception` so we can't.

**Review by lognaturel — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
but let's wait for @mmarciniak90 
verified on Andorids 5.1 and 10.

tested scenarios:
- download form a few times from Central
- download form a few times from Google Drive
- fill downloaded form
- send filled submissions
- download other forms with external files for few times

**Comment by mmarciniak90** [comment]
Tested also on Android 6.0, 7.0, 8.1, 9.0

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
