### PR TITLE
Make sure external recording is blocked when internal recording in progress

### LINKED ISSUE #4285: Audio widgets are not blocked while the internal recorder is recording if the external app is set as default
#### Software and hardware versions 
Collect master

#### Problem description
Audio widgets are not blocked while the internal recorder is recording if the external app is set as default

#### Steps to reproduce the problem
1. External app for recording is used as a default
2. User starts form where audio quality is set
3. User records audio with audio quality defined
4. Other audio widgets are not blocked

ezgif com-video-to-gif(1)

#### Expected behavior
All audio widgets are blocked

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4285 

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to just check the issue is fixed and that external and internal recording still behave as expected.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java [hunk 1]
```diff
@@ -24,13 +27,24 @@
...
         this.activityAvailability = activityAvailability;
         this.waitingForDataRegistry = waitingForDataRegistry;
         this.formEntryViewModel = formEntryViewModel;
+        this.audioRecorderViewModel = audioRecorderViewModel;
+        this.lifecycleOwner = lifecycleOwner;
+    }
+
+    @Override
+    public void onIsRecordingBlocked(Consumer<Boolean> isRecordingBlockedListener) {
+        audioRecorderViewModel.getCurrentSession().observe(lifecycleOwner, session -> {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java:45]: I did consider creating an abstract class that both `Internal...` and `External...` could extend from with this implementation. However, I feel like the code here **happens** to be the same as opposed to being the same. It could very well be that internal recordings are blocked for different reasons than external ones down the line.

Could totally understand if that seems wrong though!

**Comment by lognaturel** [comment]
This seems like enough of an edge case that maybe we can bump to 1.30? I think it's important to get the release out as soon as possible so there's as much time to react to issues before we head out for end of year breaks.

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java:45]: I'm not sure we're likely to add conditions but the principle makes sense to me and there isn't much more complexity one way or the other.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
How about this -- I'll take out of the milestone for now so it doesn't look urgent. If @getodk/testers are able to finish regression testing before the end of one of their days, they can verify this one. But we should not extend the QA period just for it.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 9.0, 10.0

Verified cases
- all audio widgets are blocked while the internal recorder is recording if the external app is set
- all audio widgets are blocked while the internal recorder is recording if the internal app is set
- delete recorded audio while the internal recorder is recording - audio widget is blocked
- minimization
- lock screen
- rotation

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
