### PR TITLE
Replace existing form with matching formid and version

### LINKED ISSUE #1693: Problem with two forms with the same id and form version
#### Software and hardware versions 
Collect v1.11.1

#### Steps to reproduce the problem
1. Download any form from Aggregate
2. Delete that form from Aggregate
3. Edit the form (without changing form id or form version) and upload again
4. Download the form again

#### Problem description
I can see two forms with the same id and version number on your device. We can't use both of in that case:
screenshot_2017-12-08-17-44-26

#### Expected behavior
An older form should be removed automatically.

any thoughts?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1693 

#### What has been done to verify that this works as intended?
I've tested the fix manually and also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is what we have discussed. As I said:

> I think the best option (short and safe) is to insert new forms like now even if they are duplicate but collect and then remove pre-existing forms with the same id and version at the end of the process of downloading a form
Thanks to the functionality that copies media files from other forms with the same id we won't need to download them again and at the same time we won't end up with abandoned media files. So it seems like a win-win solution

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should fix the problem with duplicate forms with the same id and version. We can reproduce it using central drafts. I aslo implemented changes in syncing forms from disc. The issue I solved will be difficult to reproduce:

> I was also able to find one possible scenario when users might end up with duplicate forms.... if forms are being synchronized with the server (match exactly) we first download an xml file and then save a new row in database. If between those two steps we trigger our FormSyncTask (by opening the list of forms), then it might detect that xml file and try to add it to database too.

so please focus on regression testing to make sure that functionality works as expected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java [hunk 1]
```diff
@@ -63,8 +65,8 @@ public void downloadForm(ServerFormDetails form, @Nullable ProgressReporter prog
                 formsRepository.restore(formOnDevice.getDbId());
             }
         } else {
-            List<Form> allSameFormIdVersion = formsRepository.getAllByFormIdAndVersion(form.getFormId(), form.getFormVersion());
-            if (!allSameFormIdVersion.isEmpty() && !form.getDownloadUrl().contains("/draft.xml")) {
+            preExistingFormsWithSameIdAndVersion = formsRepository.getAllByFormIdAndVersion(form.getFormId(), form.getFormVersion());
+            if (!preExistingFormsWithSameIdAndVersion.isEmpty() && !form.getDownloadUrl().contains("/draft.xml")) {
                 analytics.logEventWithParam(DOWNLOAD_SAME_FORMID_VERSION_DIFFERENT_HASH, "form", AnalyticsUtils.getFormHash(form.getFormId(), form.getFormName()));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java:70]: I think this log doesn't make much sense now. I mean it would be good to know if it happens for central users somehow (we can't rule out that there is a bug in central too) but here we don't have that knowledge. We log the event only if it's not central draft but it might very well be any other compatible server like ONA where replacing forms and adding new ones with the same `id` and `version` is perfectly fine and we shouldn't care. Should I just get rid of it or you want to try to determine if it's central? @lognaturel @seadowg

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1 and 8.1

Verified cases:
- Central draft testing: upload the same version with some change, upload exactly the same form, fill submissions, send, upload another version as draft, able to fill and send both versions
- aggregate: upload the same version with some change, upload exactly the same form, fill submissions, send, upload another version, able to fill and send both versions
- regression check on match exactly
- regression check and form update: blank form, previously downloaded form, automatic download 
- regression checks done for Central and Aggregate both

**Comment by srujner** [comment]
**Tested with success!**
Verified on Androids: 10 and 11

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java:70]: I've been thinking about this and can't come up with a use for the analytics. So yes, please remove.
