### PR TITLE
In Match Exactly mode, retry form download requests before showing failure notification

### LINKED ISSUE #4787: Improve Match Exactly notification experience
Match Exactly notifications currently have two problems we've identified:

1. Clicking a failure notification will open the "Fill Blank Form" screen for the current project, which might not be the project that experienced the error
2. Failures happen pretty frequently - just under 20% syncs will result in an failure notification ([here](https://console.firebase.google.com/u/0/project/api-project-322300403941/analytics/app/android:org.odk.collect.android/events/~2Freport~2FMatchExactlySyncCompleted%3Ft%3D1628690834457&fpn%3D322300403941&swu%3D1&sgu%3D1&sus%3Dupgraded&params%3D_u..pageSize%253D25%2526_r..eventId%253DMatchExactlySyncCompleted&cs%3Dapp.m.events.detail&r%3Ddefault&g%3D1))

To alleviate these, we should make the following changes:

- [x] The notification should specify the project that failed to sync (clicking it should still just take the user to "Fill Blank Form" for now) in the subtext (fixed in https://github.com/getodk/collect/pull/4929)
- [x] Instead of showing a notification immediately, a failure (from any request, including form downloads) should result in a limited number of retries which is limited to a certain number of retries (most likely using `WorkManager`'s [Retry and Backoff](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work#retry_and_backoff_policy) and `WorkerParameters#getRunAttemptCount`) followed by a failure notification if the sync still hasn't succeeded
- [x] Update analytics calls to only measure failures that the user sees

We're not doing a lot to fix problem **1** here, but my thinking is we try and fix problem **2** as much as possible to make **1** less of a common experience. If we're right in that thinking, we should see the proportion of **visible** failures drop.

This can definitely be solved as multiple PRs.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4787

Going through the commits form the first to the last one should be a good way to understand the changes.

#### What has been done to verify that this works as intended?
I tested the app manually using `Background task inspector` in Android studio and also I added new automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is a result of what we have discussed in https://github.com/getodk/collect/issues/4787.
I used `EXPONENTIAL` BackoffPolicy with 60s delay that means:
- if the first attempt fails we retry after 60s
- if it fails again we retry after 120s (after the second attempt)
- if it fails we retry after 240s (after the third attempt)

in total we have 4 attempts (the original one + 3 retries) and it takes 7 minutes

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test `matchexactly` since it is about this feature but also it would be good to test two other tasks that uses [Workmanager](https://developer.android.com/topic/libraries/architecture/workmanager) (`autodownload` and `autoupload`).

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt [hunk 1]
```diff
@@ -46,10 +49,24 @@ class SyncFormsTaskSpecTest {
     }
 
     @Test
-    fun `calls synchronize with projectId`() {
+    fun `getTask calls synchronize with projectId`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: This is a little misleading. Maybe just `task calls synchronize with projectId` (and the same change for the other test)?

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt [hunk 2]
```diff
@@ -46,10 +49,24 @@ class SyncFormsTaskSpecTest {
...
         val inputData = HashMap<String, String>()
         inputData[SyncFormsTaskSpec.DATA_PROJECT_ID] = "projectId"
         SyncFormsTaskSpec().getTask(ApplicationProvider.getApplicationContext(), inputData).get()
         verify(formsUpdater).matchFormsWithServer("projectId")
     }
+
+    @Test
+    fun `getTask returns proper result value`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: `...returns result from FormUpdater`

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt [hunk 3]
```diff
@@ -64,4 +66,9 @@ class AutoSendTaskSpecTest {
         AutoSendTaskSpec().getTask(ApplicationProvider.getApplicationContext(), inputData).get()
         verify(instanceAutoSender).autoSendInstances(projectId)
     }
+
+    @Test
+    fun `numberOfRetries should not be limited`() {
+        assertThat(AutoSendTaskSpec().numberOfRetries, `is`(-1))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Could we make `numberOfRetries` a `Int?` instead of giving negative numbers a special meaning? Maybe the field name could be `maxRetries` instead also?

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+
+    @Test
+    fun `when task returns true should work succeed`() {
+        whenever(spec.getTask(any(), any())).thenReturn(Supplier { true })
+
+        assertThat(workerAdapter.doWork(), `is`(ListenableWorker.Result.success()))
+    }
+
+    @Test
+    fun `when task returns false should work retry if numberOfRetries not specified`() {
```
Comment (seadowg) [inline async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: `when task returns false retries if numberOfRetries not specified` - same pattern for the tests below

File: async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker [hunk 5]
```diff
@@ -0,0 +1 @@
+mock-maker-inline
```
Comment (seadowg) [inline async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker]: What's this?

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+import org.hamcrest.MatcherAssert.assertThat
+import org.junit.Before
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.mockito.kotlin.any
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.whenever
+import java.util.function.Supplier
+
+@RunWith(AndroidJUnit4::class)
```
Comment (seadowg) [inline async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt:23]: Does this test need Robolectric? I'm guessing something explodes without it?

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt [hunk 7]
```diff
@@ -17,4 +17,8 @@ interface TaskSpec {
      * WorkManager framework
      */
     fun getWorkManagerAdapter(): Class<out WorkerAdapter>
+
+    companion object {
+        const val DATA_PROJECT_ID = "projectId"
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/TaskSpec.kt]: I think this should move back or live in a shared object in `collect_app`. `async` doesn't need to know about Projects, and we very well might add a task that doesn't care about them.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt [hunk 8]
```diff
@@ -18,9 +18,12 @@ class SyncFormsTaskSpec : TaskSpec {
     override fun getTask(context: Context, inputData: Map<String, String>): Supplier<Boolean> {
         DaggerUtils.getComponent(context).inject(this)
         return Supplier {
-            formsUpdater.matchFormsWithServer(
-                inputData[TaskSpec.DATA_PROJECT_ID]!!
-            )
+            val projectId = inputData[TaskSpec.DATA_PROJECT_ID]
+            if (projectId != null) {
+                return@Supplier formsUpdater.matchFormsWithServer(projectId)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt]: You can just omit the `return` here so you don't need the whole `@Supplier` thing.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt [hunk 9]
```diff
@@ -20,5 +20,6 @@ interface TaskSpec {
 
     companion object {
         const val DATA_PROJECT_ID = "projectId"
+        const val LAST_UNIQUE_ATTEMPT = "lastAttempt"
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/TaskSpec.kt]: This could potentially get passed as a param on `TaskSpec#getTask` rather than as part of the `inputData` leaving that to the extending classes. I'm not sure though. What do you think?

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt [hunk 10]
```diff
@@ -50,19 +50,30 @@ class SyncFormsTaskSpecTest {
     }
 
     @Test
-    fun `getTask calls synchronize with projectId`() {
+    fun `when LAST_UNIQUE_ATTEMPT equals true getTask calls synchronize with proper data`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: Instead of `proper data` in these tests it could be `with/without notify` or `with notify true/false`

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt [hunk 11]
```diff
@@ -69,6 +75,63 @@ class WorkerAdapterTest {
...
+                mapOf(
+                    TaskSpec.DATA_PROJECT_ID to "123",
+                    TaskSpec.LAST_UNIQUE_ATTEMPT to "true"
+                )
+            )
+        )
+    }
+
+    @Test
+    fun `when numberOfRetries is specified and it is higher than runAttemptCount, should data contain LAST_UNIQUE_ATTEMPT equal false`() {
```
Comment (seadowg) [inline async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Again these tests don't need `should` in them really. Could just be `..runAttemptCount, data contains...`

File: async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt [hunk 12]
```diff
@@ -49,6 +50,10 @@ open class CoroutineScheduler(private val foregroundContext: CoroutineContext, p
         throw UnsupportedOperationException()
     }
 
+    override fun networkDeferred(tag: String, spec: TaskSpec, repeatPeriod: Long, backoffPolicy: BackoffPolicy, backoffDelay: Long, inputData: Map<String, String>) {
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt]: Maybe these should live on the `TaskSpec` rather than here? I remember having the same debate with myself about `repeatPeriod`...

Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt]: Either way I'm not sure we need them yet. Right now we could use the same backoff policy and backoff delay for any task that specifies a number of retries (as only match exactly does).

**Review by seadowg — CHANGES_REQUESTED** [review]
Really liking the direction of this. There are a couple of tweaks and also some things about the general `async` API that would be good for us to discuss here that I've left comments for inline.

File: async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 5 above)
Comment (grzesiek2010) [reply async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker]: It enables mocking final classes. I use it in `WorkerAdapterTest` where I mock `WorkerParameters` which is a final class.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt:23]: Yes I create an instance of `WorkerAdapter` in this test.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: Fixed.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: Fixed.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 4 above)
Comment (grzesiek2010) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Fixed.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 11 above)
Comment (grzesiek2010) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Fixed.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt (hunk 10 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt]: Fixed.

File: async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt (hunk 12 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt]: But the existing `networkDeferred` is used by `autoupdate`. I didn't want to affect that task (it wouldn't have limited retries of course but it would change it's default `backoffPolicy` and default `backoffDelay`.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt (hunk 8 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt]: Right, fixed.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: I renamed `numberOfRetries` to `maxRetries` but I'm not sure if I understand the fist part correctly. You added this comment ins a commit. The final version doe not have that raw -1 but it's represented by a const `UNLIMITED_NUMBER_OF_RETRIES`. Is there anything else you would like to change here?

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt (hunk 9 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/TaskSpec.kt]: `TaskSpec#getTask` has `inputData: Map<String, String>` so using it was a natural choice to me. The same question you could ask about `projectId` - why not to pass it as a parameter?

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Sorry maybe that ended up being unclear. What I mean is using an optional type (`Int?`) instead of a non-optional and then having `null` denote "no retries". Then the check can be `if (spec.maxRetries == null...` and there'd be no need for a special constant. I know using `-1` is pretty common in Java, but I feel like having safe nullables in Kotlin gives us a clearer way of dealing with that kind of "optional" value.

File: async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 5 above)
Comment (seadowg) [reply async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker]: Urgh yeah I remember this : `WorkerParameters` is `final` and has a restricted constructor. I think it'd be good to have an experiment with the worker manager testing tools (https://developer.android.com/topic/libraries/architecture/workmanager/how-to/testing-worker-impl) to see if we can use that instead of introducing `final` mocking to the module.

File: async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt (hunk 12 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt]: I was just meaning on `TaskSpec` we could define the fields optionally (like I'm suggesting for `maxRetries`):

```kotlin
interface TaskSpec {
    val backoffPolicy: BackoffPolicy? = null
    val backoffDelay: BackoffDelay? = null
}
```

Then a task can override the value if it wants, and otherwise we just use the default.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Ah I see but making `maxRetries` nullable would make using it a bit more difficult even in kotlin for example in `WorkerAdapter` instead of:
```
this[TaskSpec.DATA_LAST_UNIQUE_EXECUTION] = (runAttemptCount >= spec.maxRetries).toString()
```
I would need to check if `maxRetries` is not null first (and it's not the only place like that).
Of course I could use this for example:
```
this[TaskSpec.DATA_LAST_UNIQUE_EXECUTION] = (spec.maxRetries?.let { runAttemptCount >= it }).toString()
```
but it makes the code less readable to me.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Yeah, I mean I think this is getting into personal preference, but I prefer the latter to the former there. The first example relies on knowledge that a negative number is being used to denote "no retries" whereas I'd argue that the second example makes it clearer that there is no last unique execution if there is no `maxRetries`.  The first example also relies on a bit of a "trick": a negative number is always lower than the run attempt count which is concise, but I don't personally feel it's clearer.

The other problem (and probably the more important one) I have with using negative numbers, is that it brings in more risk of writing buggy code. For instance, this code works with any negative value, but it'd be easy to write code that relies on `-1` specifically and have a value like `-2` cause problems. 

I think if you feel strongly that the negative number is better, then let's keep it - it's just stylistic peeve of mine.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt (hunk 9 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/TaskSpec.kt]: Agreed it could go in either. `projectId` is different as not every `TaskSpec` would (or should) care about Projects (also mentioned [here](https://github.com/getodk/collect/pull/5024#discussion_r805332832)). I do think it'd be better as a parameter as it gives you the simplicity of knowing for sure that the value is present over it being in a map which introduces uncertainty (complexity). I guess which comparing these kinds of things (which feel pretty equal) I'd try to go with more certainty over less, even it's pretty minor.

File: async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt (hunk 12 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/CoroutineScheduler.kt]: Ok, done.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt (hunk 9 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/TaskSpec.kt]: Ok, done.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Ok we can do that like that, done.

File: async/src/main/java/org/odk/collect/async/TaskSpec.kt (hunk 7 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/TaskSpec.kt]: Done.

File: async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 5 above)
Comment (grzesiek2010) [reply async/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker]: Yeah we can use it. Done.

File: async/build.gradle [hunk 13]
```diff
@@ -47,4 +47,8 @@ dependencies {
     implementation Dependencies.androidx_work_runtime
 
     testImplementation Dependencies.hamcrest
+    testImplementation Dependencies.robolectric
```
Comment (seadowg) [inline async/build.gradle:50]: This **should** work without Robolectric - the AndroidX Test stuff should be enough as you're not referencing Robolectric explicitly in the test. However, if I try and remove Robolectric, everything compiles, but I get the following error:

```java
Caused by: java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
	at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
	at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.createRunnerParams(AndroidJUnit4ClassRunner.java:53)
	at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:48)
```

I'm going to quickly dig into what's happening here as it's confusing.

Comment (seadowg) [reply async/build.gradle:50]: Ok yeah it's just that the docs are all wrong or everything is broken (standard): https://issuetracker.google.com/issues/219885372. Robolectric needs to be included to get AndroidX Test to work with "local tests".

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt [hunk 14]
```diff
@@ -42,13 +42,16 @@ class CoroutineAndWorkManagerScheduler(foregroundContext: CoroutineContext, back
...
-        val workRequest = PeriodicWorkRequest.Builder(worker, repeatPeriod, TimeUnit.MILLISECONDS)
+        val builder = PeriodicWorkRequest.Builder(worker, repeatPeriod, TimeUnit.MILLISECONDS)
             .addTag(tag)
             .setInputData(workManagerInputData)
             .setConstraints(constraints)
-            .build()
 
-        workManager.enqueueUniquePeriodicWork(tag, ExistingPeriodicWorkPolicy.REPLACE, workRequest)
+        if (spec.backoffPolicy != null && spec.backoffDelay != null) {
+            builder.setBackoffCriteria(spec.backoffPolicy!!, spec.backoffDelay!!, TimeUnit.MILLISECONDS)
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt]: We can avoid the `!!` with a nested `?.let`:

```kotlin
spec.backoffPolicy?.let { backoffPolicy ->
    spec.backoffDelay?.let { backoffDelay ->
    
    }
}

```

...or by using passing both optionals to a `Pair` and then using `.let`  with destructuring:

```kotlin
Pair(spec.backoffPolicy, spec.backoffDelay).let { (policy, delay) ->
}
```

Another option is just to create a `Backoff` type (probably an inner type of `TaskSpec` that holds both so the whole thing is one optional and both values are non-optional.

File: async/src/main/java/org/odk/collect/async/Scheduler.kt [hunk 15]
```diff
@@ -54,6 +55,27 @@ interface Scheduler {
...
+     *
+     * @param tag used to identify this task in future. Previously scheduled tasks using the same
+     * tag will be replaced
+     * @param spec defines the task to be run
+     * @param repeatPeriod the period between each run of the task
+     * @param backoffPolicy the BackoffPolicy to use when increasing backoff time
+     * @param backoffDelay the time to wait before retrying the work
+     * @param inputData a map of input data that can be accessed by the task
+     */
+    fun networkDeferred(
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/Scheduler.kt]: I think this is unused now?

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt [hunk 16]
```diff
@@ -0,0 +1,119 @@
...
+        whenever(spec.getTask(any(), any(), any())).thenReturn(Supplier { false })
+        whenever(spec.maxRetries).thenReturn(3)
+
+        assertThat(worker.doWork(), `is`(ListenableWorker.Result.retry()))
+    }
+
+    @Test
+    fun `when task returns false, fails if maxRetries is specified and is equal to runAttemptCount`() {
+        whenever(spec.getTask(any(), any(), any())).thenReturn(Supplier { false })
+        whenever(spec.maxRetries).thenReturn(1)
```
Comment (seadowg) [inline async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Not sure if I understand this. If `maxRetries` is `1` it should allow a single retry right? So 2 total runs?

File: async/src/main/java/org/odk/collect/async/WorkerAdapter.kt [hunk 17]
```diff
@@ -12,12 +12,16 @@ abstract class WorkerAdapter(
 
     override fun doWork(): Result {
         val stringInputData = inputData.keyValueMap.mapValues { it.value.toString() }
-        val completed = spec.getTask(applicationContext, stringInputData).get()
+        val completed = spec.getTask(applicationContext, stringInputData, isLastUniqueExecution()).get()
 
         return if (completed) {
             Result.success()
-        } else {
+        } else if (spec.maxRetries == null || runAttemptCount < spec.maxRetries!!) {
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/WorkerAdapter.kt]: I think this should potentially be `runAttemptCount <= spec.maxRetries` (I've left a comment on the test about that). Also, this could avoid `!!` with `spec.maxRetries.let {}` around the `if`.

File: testshared/build.gradle [hunk 18]
```diff
@@ -40,6 +40,7 @@ dependencies {
     implementation Dependencies.androidx_recyclerview
     implementation Dependencies.kotlin_stdlib
     implementation Dependencies.androidx_core_ktx
+    implementation Dependencies.androidx_work_runtime
```
Comment (seadowg) [inline testshared/build.gradle:43]: I think this is only needed because of the unused `networkDeferred` overload.

**Review by seadowg — CHANGES_REQUESTED** [review]
Thanks for indulging my nitpicking here. Probably being extra sensitive as we build out these micro frameworks for ourselves, but hopefully it'll pay off in the future.

Just a couple of tweaks I think we should look at, and I'm also confused about how many retries we end up with. Comments inline.

File: testshared/build.gradle (hunk 18 above)
Comment (grzesiek2010) [reply testshared/build.gradle:43]: No, it is used in other places too.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 16 above)
Comment (grzesiek2010) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: In tests attempts are counted starting from 1 but in normal life from 0 I don't know why...

File: async/src/main/java/org/odk/collect/async/WorkerAdapter.kt (hunk 17 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/WorkerAdapter.kt]: First runAttemp is marked as 0 (in tests 1 as I said above) so if our maxRetries is 3 it's like:
0 < 3 - retry
1 < 3 - retry
2 < 3 - retry
3 < 3 - fail

in total we have 3 reties as we expected. If I used your syntax <= we would have one additional.

Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/WorkerAdapter.kt]: > Also, this could avoid !! with spec.maxRetries.let {} around the if.

Could you share the whole construction. I'm not sure if I can use anything like that here.

File: async/src/main/java/org/odk/collect/async/Scheduler.kt (hunk 15 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/Scheduler.kt]: Right, fixed.

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt (hunk 14 above)
Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt]: Done.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 16 above)
Comment (seadowg) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Ah looks like you can pass `runAttemptCount` to `TestWorkerBuilder` to make this clearer: https://developer.android.com/topic/libraries/architecture/workmanager/how-to/testing-worker-impl#testing-workers

File: async/src/main/java/org/odk/collect/async/WorkerAdapter.kt (hunk 17 above)
Comment (seadowg) [reply async/src/main/java/org/odk/collect/async/WorkerAdapter.kt]:
```kotlin
return spec.maxRetries.let { maxRetries ->
    if (completed) {
        Result.success()
    } else if (maxRetries != null && runAttemptCount < maxRetries) {
        Result.retry()
    } else {
        Result.failure()
    }
}
```

Alternatively, you can just pull out the value:

```kotlin
val maxRetries = spec.maxRetries
return if (completed) {
    Result.success()
} else if (maxRetries == null || runAttemptCount < maxRetries) {
    Result.retry()
} else {
    Result.failure()
}
```

Comment (grzesiek2010) [reply async/src/main/java/org/odk/collect/async/WorkerAdapter.kt]: Right, I like the second option, done.

File: async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt (hunk 16 above)
Comment (grzesiek2010) [reply async/src/test/java/org/odk/collect/async/WorkerAdapterTest.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1 and 8.1

Verified cases:
- match exactly and the invalid url - wait for failure: ~6-7min
- match exactly and not existing project - wait for failure: ~6-7min
- relaunch match exactly manually - failure notification displayed immediately 
- wait 15min after failure notification 
- failure notification from not currently used project
- turn on match exactly in 2 projects in the same time 
- after 1st fail, update URL to valid and wait for an update - successful update
- turn off internet connection, notification after connection is restored.
- turn on airplane mode
- previously downloaded form notification
- previously download form automatic update
- regression check on autosend: settings and defined in form
- fail notification on autosend

**Comment by srujner** [comment]
**Tested with success!**
Verified on Androids: 10 and 11
