### PR TITLE
 Use query to get latest versions of forms

### LINKED ISSUE #2686: ODK Collect crashes when user changes device orientation on the list with blank forms
#### Software and hardware versions 
Collect current master

#### Problem description
ODK Collect crashes when a user changes device orientation on the list with blank forms

#### Steps to reproduce the problem
1. User clicks on `Fill Blank Form`
2. User sees a list of blank forms
3. User changes device orientation
4. App crashes

#### Expected behavior
Collect should not crash

#### Other information 
12:00:47.433  3686  4008 D MdnieScenarioControlService:  packageName : org.odk.collect.android    className : org.odk.collect.android.activities.MainMenuActivity
10-25 12:00:47.438 17285 17285 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-25 12:00:47.445  4962  5017 D ContactsProvider_EventLog: contents_sample_state: [ contacts(11) data(56) accounts({vnd.sec.contact.phone (1)=2, com.google (15)=10}) accounts deleted({}) calls([logtype:100 cnt:12, logtype:300 cnt:27]) countryIso(PL) userId(0)  ]
10-25 12:00:47.445  4962  5017 D ContactsProvider_EventLog: contents_sample_state: [ agr({[1]=1, [15]=9, [1 ,15]=1})  ]
10-25 12:00:47.445  4962  5017 D ContactsProvider_EventLog: contents_sample_state: [ actCnt({android.process.acore=1})  ]
10-25 12:00:47.448  4962  5017 E ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 0Kb duration : 2ms lastUpdatedAfter : 60100 ms mFlush_time_threasold : 2000 mCurrentSize : 368
10-25 12:00:47.455 17285 17285 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
10-25 12:00:47.455 17285 17285 I art     :   at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
10-25 12:00:47.455 17285 17285 I art     :   at void org.odk.collect.android.activities.MainMenuActivity.onCreate(android.os.Bundle) (MainMenuActivity.java:113)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6912)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1126)
10-25 12:00:47.455 17285 17285 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2877)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2985)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.-wrap14(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1635)
10-25 12:00:47.455 17285 17285 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-25 12:00:47.455 17285 17285 I art     :   at void android.os.Looper.loop() (Looper.java:154)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
10-25 12:00:47.455 17285 17285 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-25 12:00:47.455 17285 17285 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
10-25 12:00:47.455 17285 17285 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
10-25 12:00:47.455 17285 17285 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/org.odk.collect.android-1/base.apk"],nativeLibraryDirectories=[/data/app/org.odk.collect.android-1/lib/arm64, /system/lib64, /vendor/lib64]]
10-25 12:00:47.455 17285 17285 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-25 12:00:47.455 17285 17285 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-25 12:00:47.455 17285 17285 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
10-25 12:00:47.455 17285 17285 I art     :   at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
10-25 12:00:47.455 17285 17285 I art     :   at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
10-25 12:00:47.455 17285 17285 I art     :   at void org.odk.collect.android.activities.MainMenuActivity.onCreate(android.os.Bundle) (MainMenuActivity.java:113)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6912)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1126)
10-25 12:00:47.455 17285 17285 I art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2877)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2985)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.-wrap14(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1635)
10-25 12:00:47.455 17285 17285 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-25 12:00:47.455 17285 17285 I art     :   at void android.os.Looper.loop() (Looper.java:154)
10-25 12:00:47.455 17285 17285 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
10-25 12:00:47.455 17285 17285 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-25 12:00:47.455 17285 17285 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
10-25 12:00:47.455 17285 17285 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
10-25 12:00:47.455 17285 17285 I art     : 
10-25 12:00:47.463 17285 17285 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
10-25 12:00:47.477 17285 17285 D TextView: setTypeface with style : 0
10-25 12:00:47.485 17285 17285 D TextView: setTypeface with style : 0
10-25 12:00:47.486 17285 17285 D TextView: setTypeface with style : 0

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #2686

**Feedback wanted:**
- Is the `content://org.odk.collect.android.provider.odk.forms/uniqueFormsByFormId` content URI reasonable? Can you think of a better name?
- Are you ok with that new content URI only being available for `query` and `type`? I made that decision because it limits the public API and I can't imagine a use for deleting, updating, inserting specifically in the filtered list.

#### What has been done to verify that this works as intended?
Downloaded 3 different versions of a form. Unchecked option to hide old forms and verified all 3 versions show. Checked option to hide old forms and verified only 1 version shows. While the option to hide old forms was checked, downloaded a second version of another form. Verified that only one version shows for both forms that have multiple versions. Unchecked option to hide old forms and verified both versions of the newly downloaded form show. Tried all the sort options and search with option checked and unchecked. Rotated the screen.

One risk is that when there is only one version of the form shown, it is not the latest. To verify that the filter actually picks the latest form version, I changed the query from `MAX(date)` to `MIN(date)` and verified that the oldest form version was shown instead.

#### Why is this the best possible solution? Were any other approaches considered?
Prior to #2216, `FormsDao.getFormsFromCursor` and `InstancesDao.getInstancesFromCursor` both closed the cursor they were passed. In #2216, a method to build a filtered cursor from a form cursor was introduced [here](https://github.com/opendatakit/collect/pull/2216/files#diff-b25c7fc4ac3ef115916a013aa93b55a0R39). This method was called after loading the cursor [here](https://github.com/opendatakit/collect/pull/2216/files#diff-af25ce4b576502ac52785c5d4cd8a844R251) and because it was a cursor used by the adapter, it was reused. For that reason, the `FormsDao.getFormsFromCursor` method was made to leave the cursor open.

This alternate solution does the filtering at the query level as we had discussed [here](https://github.com/opendatakit/collect/pull/2216#issuecomment-390812121). That means it's more efficient, better fits the cursor loader pattern and doesn't require using the `FormsDao.getFormsFromCursor` method on a cursor that needs to stay open. This lets `FormsDao.getFormsFromCursor` be a higher-level abstraction that doesn't require the user to think about cursor closing. Ideally, there would be a way to get `Form` objects without having to think about cursors on the input, either.

I attempted to use a query-based solution without introducing a new content URI for `FormsProvider` but because there is no groupby functionality, I don't believe there is a way to do that. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This should not affect users other than to fix rotation on Fill Blank Form. Loading a filtered form list should also be more efficient but it's likely not visible to users unless they have huge numbers of forms.

The risks are centered around the Fill Blank Form screen because it is the only one that makes use of the modified `getFormsCursorLoader` method and the new content URI. There are risks around sorting, searching and applying/disabling the setting to hide older forms.

This also expands the public API of the app by introducing the `content://org.odk.collect.android.provider.odk.forms/uniqueFormsByFormId` content URI. This will be one more thing to maintain for the future. I made the decision to only support `type` and `query` to limit that to directly useful functionality.

#### Do we need any specific form for testing your changes? If so, please attach one.
No, any form can be uploaded to Aggregate with one version, downloaded to Collect, then updated to a newer version, downloaded to Collect, etc.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java [hunk 1]
```diff
@@ -222,16 +221,15 @@ public void onClick(DialogInterface dialog, int i) {
...
     }
 
     @Override
     public void onLoadFinished(@NonNull Loader<Cursor> loader, Cursor cursor) {
         hideProgressBarIfAllowed();
-        listAdapter.changeCursor(
-                GeneralSharedPreferences.getInstance().getBoolean(PreferenceKeys.KEY_HIDE_OLD_FORM_VERSIONS, false)
-                        ? FormUtils.removeOldForms(cursor)
-                        : cursor);
+        listAdapter.swapCursor(cursor);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java:232]: The [documentation for `onLoadFinished`](https://developer.android.com/reference/android/support/v4/app/LoaderManager.LoaderCallbacks#onLoadFinished(android.support.v4.content.Loader%3CD%3E,%20D)) says: "if the Cursor is being placed in a CursorAdapter, you should use the swapCursor(android.database.Cursor) method so that the old Cursor is not closed."

Was there a particular reason to use `changeCursor` instead?

File: collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java [hunk 2]
```diff
@@ -96,23 +99,32 @@ public Cursor query(@NonNull Uri uri, String[] projection, String selection,
...
+                    break;
+
+                case FORM_ID:
+                    qb.appendWhere(FormsColumns._ID + "="
+                            + uri.getPathSegments().get(1));
+                    break;
+
+                // Only include the latest form that was downloaded with each form_id
+                case UNIQUE_FORMS_BY_FORM_ID:
+                    Map<String, String> filteredProjectionMap = new HashMap<>(sFormsProjectionMap);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java:117]: This is a little bit unusual -- I map the date column name to the desired max function. Alternately, I could add a new name to the map and make that part of the `projection` but the approach I took seems easier to understand to me.

Note that since I'm reusing the key name, it's really important that this is a copy and not modifying the static projection map directly because the static map gets reused.

File: collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java [hunk 3]
```diff
@@ -96,23 +99,32 @@ public Cursor query(@NonNull Uri uri, String[] projection, String selection,
...
+                    filteredProjectionMap.put(FormsColumns.DATE, "MAX(" + FormsColumns.DATE + ")");
+
+                    qb.setProjectionMap(filteredProjectionMap);
+                    groupBy = FormsColumns.JR_FORM_ID;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java:121]: More on how group by works: http://www.sqlitetutorial.net/sqlite-group-by/

**Review by grzesiek2010 — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java:232]: I have no idea what the reason was.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
I haven't noticed anything suspicious.
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.1 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
