### PR TITLE
Fixed: EDIT action for forms will crash if there are no projects

### LINKED ISSUE #4743: EDIT action for forms will crash if there are no projects
#### Software and hardware versions 
Collect v2021.2

#### Problem description

Trying to open a form from a URI or shortcut when there are no projects causes a crash.

#### Steps to reproduce the problem

1. Create a shortcut for a form
2. Delete all the projects in Collect
3. Click on shortcut

#### Expected behavior

Collect should a warning dialog and then close when the dialog is dismissed.

#### Other information 

Crashlytics report: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7abd65245bbd49ab8e4cd8acb06ad287?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=61012C22032C00010321849F7FC5E726_1568363353904663998

Stacktrace:

```
Caused by java.util.NoSuchElementException: List is empty.
       at kotlin.collections.CollectionsKt___CollectionsKt.first(CollectionsKt___CollectionsKt.java:212)
       at kotlin.collections.CollectionsKt.first(CollectionsKt.java)
       at org.odk.collect.android.external.FormUriActivity.onCreate(FormUriActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:7895)
       at android.app.Activity.performCreate(Activity.java:7883)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3491)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4743 

#### What has been done to verify that this works as intended?
I tested the fix manually and also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It's just a fix so this seems to be the only solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue and do not affect anything else so please focus on the scenario described in the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/external/FormEditActionTest.kt [hunk 1]
```diff
@@ -36,61 +32,4 @@ class FormEditActionTest {
         val intent = Intent(Intent.ACTION_EDIT).also { it.data = uri }
         rule.launch(intent, FormEntryPage("One Question"))
     }
-
-    @Test
-    fun whenFormIsNotCurrentProject_showsWarningAndExits() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/external/FormEditActionTest.kt:41]: Just wanted to talk through the test restructuring here before reviewing. Is the idea that `FormEditActionTest` checks the "happy path" or simplest case (and most importantly that the intent filter is set up correctly) and that the `FormUriActivityTest` checks the more detailed cases (missing project etc)? It looks like a sort of "feature and component test" breakdown but just wanted to check we were on the same page!

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/external/FormEditActionTest.kt:41]: `FormEditActionTest` covered the same cases like the new `FormUriActivityTest`. I think `FormEditActionTest` was created as a UI test that requires android emulator because we weren't able to test implicit intents using activity scenario https://github.com/android/android-test/issues/496 that issue will be solved soon.

I kept that one test in `FormEditActionTest` for two reasons:
1. What I mentioned above - currently in `FormUriActivityTest` we only test explicit intents so it's nice to keep one that odes that in an implicit way.
2. It's nice to have one UI test for that scenario (simple scenario) but all the other cases should be tested using activity scenario.

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/external/FormEditActionTest.kt:41]: Right that all makes sense!

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+                projectsRepository: ProjectsRepository?
+            ): CurrentProjectProvider {
+                return currentProjectProvider
+            }
+        })
+    }
+
+    @Test
+    fun `When there are no projects then display alert dialog`() {
+        projectsRepository.deleteAll()
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt]: Personally I'd find these tests easier to read if the projects were added at the start of the test rather than in `setup`. Then, the state of the world (the "given") can be seen next to the actions and assertions (the "when" and "then").

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+
+        ActivityScenario.launch<FormUriActivity>(getIntent())
+
+        Intents.intended(hasComponent(FormEntryActivity::class.java.name))
+
+        Intents.release()
+    }
+
+    @Test
+    fun `When everything is fine form filling is started with given data`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt]: Is this not the same as `When there is project id specified in uri and it matches current project id then start form filling`?

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+import org.odk.collect.android.preferences.source.SettingsProvider
+import org.odk.collect.android.projects.CurrentProjectProvider
+import org.odk.collect.android.support.CollectHelpers
+import org.odk.collect.projects.InMemProjectsRepository
+import org.odk.collect.projects.Project
+import org.odk.collect.projects.ProjectsRepository
+import org.odk.collect.shared.strings.UUIDGenerator
+
+@RunWith(AndroidJUnit4::class)
+class FormUriActivityTest {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:43]: I think you could use `RecordedIntentsRule` to avoid all the setup and teardown steps in this test.

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+        Intents.release()
+    }
+
+    @Test
+    fun `When there is no project id specified in uri and first available project id does not match current project id then display alert dialog`() {
+        whenever(currentProjectProvider.getCurrentProject()).thenReturn(secondProject)
+
+        val scenario = ActivityScenario.launch<FormUriActivity>(getIntent())
+
+        onView(withText(R.string.wrong_project_selected_for_form)).inRoot(isDialog()).check(matches(isDisplayed()))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt]: I did not know that we could use matchers on dialogs in Robolectric. That's definitely useful.

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 6]
```diff
@@ -0,0 +1,158 @@
...
+        assertThat(scenario.result.resultCode, `is`(Activity.RESULT_CANCELED))
+    }
+
+    @Test
+    fun `When there is project id specified in uri and it matches current project id then start form filling`() {
+        Intents.init()
+
+        ActivityScenario.launch<FormUriActivity>(getIntent(firstProject.uuid))
+
+        Intents.intended(hasComponent(FormEntryActivity::class.java.name))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:104]: We should probably check the intent details whenever we launch `FormEntryActivity` (like you do in `When everything is fine form filling is started with given data`).

File: strings/src/main/res/values/strings.xml [hunk 7]
```diff
@@ -1111,6 +1111,8 @@
 
     <!-- Error shown when a user tries to open a form that's in a different project -->
     <string name="wrong_project_selected_for_form">To open this form, you must first open ODK Collect and switch to the project that contains it.</string>
+    <!-- Error shown when a user tries to open a form when there are no projects -->
+    <string name="no_projects_detected">No projects detected.</string>
```
Comment (seadowg) [inline strings/src/main/res/values/strings.xml]: This is a weird one because it means the shortcut/URI will never work right? If there are no projects, they'd need to add one and the form would end up with a different ID (probably).

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt [hunk 8]
```diff
@@ -28,26 +28,37 @@ class FormUriActivity : Activity() {
...
+
+            if (projectId == currentProjectProvider.getCurrentProject().uuid) {
+                startActivity(
+                    Intent(this, FormEntryActivity::class.java).also {
+                        it.data = uri
+                        intent.extras?.let { sourceExtras -> it.putExtras(sourceExtras) }
+                    }
+                )
+            } else {
+                AlertDialog.Builder(this)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Dialogs should use `MaterialAlertDialogBuilder` as per #4914.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt]: Kind of but this one is focused on testings passed data and extras. [EDIT]: Done

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:104]: Every time check data and extras?

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:104]: Yeah I think so! Just to make sure we're definitely sending the right stuff through in each case.

File: strings/src/main/res/values/strings.xml (hunk 7 above)
Comment (grzesiek2010) [reply strings/src/main/res/values/strings.xml]: Yes it would work in case of demo projects but other projects will have unique ids.

File: collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt (hunk 8 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt]: Fixed.

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:104]: Ok, done.

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:43]: Done.

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt]: Done.

File: strings/src/main/res/values/strings.xml (hunk 7 above)
Comment (seadowg) [reply strings/src/main/res/values/strings.xml]: Ok how about: 

```
"ODK Collect has not been configured. Try to open ODK Collect and configure it.\n\nIf you tapped on a shortcut, you might need to recreate it after configuring ODK Collect."
```

Comment (grzesiek2010) [reply strings/src/main/res/values/strings.xml]: I agree it's better, done.

File: strings/src/main/res/values/strings.xml [hunk 9]
```diff
@@ -1111,6 +1111,8 @@
 
     <!-- Error shown when a user tries to open a form that's in a different project -->
     <string name="wrong_project_selected_for_form">To open this form, you must first open ODK Collect and switch to the project that contains it.</string>
+    <!-- Error shown when a user tries to open a form when there are no projects -->
+    <string name="app_not_configured">ODK Collect has not been configured. Try to open ODK Collect and configure it.\n\nIf you tapped on a shortcut, you might need to recreate it after configuring ODK Collect.</string>
```
Comment (seadowg) [inline strings/src/main/res/values/strings.xml:1115]: @lognaturel would appreciate a sanity check on this copywriting.

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010 I noticed one unexpected case:

1. create DEMO project and download forms
2. add shortcuts to one of the form, e.g. _All widgets_
3. remove project
4. click on shortcuts and there is no crash 
5. open Collect and re-create DEMO project 
6. try to download forms -> connecting to server never ends

**Comment by grzesiek2010** [comment]
Reproducing your steps I get `SQLiteReadOnlyDatabaseException`:

```
Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
        at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1729)
        at org.odk.collect.android.database.forms.DatabaseFormsRepository.deleteForms(DatabaseFormsRepository.java:239)
        at org.odk.collect.android.database.forms.DatabaseFormsRepository.delete(DatabaseFormsRepository.java:164)
        at org.odk.collect.android.utilities.FormsDirDiskFormsSynchronizer.synchronizeAndReturnError(FormsDirDiskFormsSynchronizer.java:101)
        at org.odk.collect.android.utilities.FormsDirDiskFormsSynchronizer.synchronize(FormsDirDiskFormsSynchronizer.java:44)
        at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.fetchFormDetails(ServerFormsDetailsFetcher.kt:51)
        at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:63)
        at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:39)
```

I'm pretty sure it's not my fault because I'm able to reproduce the same exception on master too:
1. Crete Demo project
2. Download one form
3. Delete the project
4. Create Demo project again
5. Try to download forms.

Could you confirm? If I'm right we should create a separate issue.

File: strings/src/main/res/values/strings.xml (hunk 9 above)
Comment (lognaturel) [reply strings/src/main/res/values/strings.xml:1115]: I think it’s ok! This only happens when there are 0 projects, right? Not also when a deleted project is referenced? If it also includes the case where a deleted project is referenced thrn I’d want to edit it a bit.

Comment (seadowg) [reply strings/src/main/res/values/strings.xml:1115]: Yeah, you're right: at the moment this only shows for the 0 projects case.

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 lets confirm whether the problem here is a regression or not so we can move on with testing for this

**Comment by kkrawczyk123** [comment]
@seadowg It's a little weird, I am able to reproduce the issue on both store version and master but with slightly different results. On master, I see infinite load on connecting to server dialog but on store version at the same step I see a crash. It's not connected to changes from this PR.

**Comment by grzesiek2010** [comment]
Yes I can confirm that the result is different as @kkrawczyk123 said but logs are the same so it's not something introduced by this issue.
Let's continue testing and I will report it in a separate issue.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 5.1 and 8.1

Verified cases:
- use form shortcut
- scenario form issue
- information dialog visible 
- use shortcut after downloading form again 
- fill form

I have noticed that I am not able to create shortcut on Xiaomi devices (I have tried on 2 separate devices and also older versions of Collect). I am not sure if I should report it and if we can even do something with that on Collect side. @grzesiek2010 @seadowg what do you think?

**Comment by seadowg** [comment]
> I am not sure if I should report it and if we can even do something with that on Collect side. @grzesiek2010 @seadowg what do you think?

@kkrawczyk123 I'd report that as a new issue, and we can investigate. There might be something we're doing that they don't support.

**Comment by srujner** [comment]
**Tested with success!**

Verified on Androids 10 and 11

I also noticed not being able to create shortcut on Xiaomi
