### PR TITLE
WebView Activity Added for devices having no browser

### LINKED ISSUE #1813: Visiting ODK website crashes the application if no browser is installed
#### Software and hardware versions 
Collect v1.12.2 
Android 6.0.1

#### Problem description
Devices that don't have chrome installed on it.
#### Steps to reproduce the problem
User Device that doesn't have Chrome/Any other browser installed on it.

1. User goes to Main Menu Screen
2. Opens the Overflow menu
3. Opens 'About' Activity
4. User clicks on either 'Visit the ODK Website' or 'Join the ODK forum'

#### Expected behaviour
Url should be opened in Webview
#### Other information 
Found while working on #1755 
The issue can be fixed by adding a check before opening a ChromeCustomTabs whether Chrome support is there or not on device then handling it by either webview or by opening it in browser.

```
01-27 12:55:13.954 16330-16330/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.odk.collect.android, PID: 16330
                                                   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://opendatakit.org/... }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3963)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3924)
                                                       at android.app.Activity.startActivity(Activity.java:4247)
                                                       at android.app.Activity.startActivity(Activity.java:4215)
                                                       at org.odk.collect.android.utilities.CustomTabHelper.openUri(CustomTabHelper.java:97)
                                                       at org.odk.collect.android.preferences.AboutPreferencesFragment.onPreferenceClick(AboutPreferencesFragment.java:85)
                                                       at android.preference.Preference.performClick(Preference.java:996)
                                                       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                       at android.widget.AbsListView.onTouchUp(AbsListView.java:3915)
                                                       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3680)
                                                       at android.view.View.dispatchTouchEvent(View.java:9311)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                       at android.view.View.dispatchPointerEvent(View.java:9531)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4283)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4098)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3789)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3846)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5975)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5949)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5910)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6078)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                   	at android.os.Looper.loop(Loop

```

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Closes #1813

#### What has been done to verify that this works as intended?
Tried on Physical Device (Android 5.0 and 6.0) and behaviour found correct

#### Why is this the best possible solution? Were any other approaches considered?
Other approaches could be to show Toast to user that no browser is installed.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No

ezgif com-video-to-gif

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lakshyagupta21 did you reproduced the issue using a real device or an emulator? I wonder how it is possible. I've never seen a real device without any browser and as I know it's not even possible to uninstall a default browser. Maybe it's possible but it's not like settings-> all apps ... -> uninstall so it's not easy.

**Comment by lakshyagupta21** [comment]
@grzesiek2010 I found this issue on real device. First I thought of testing this in devices having no chrome. Then by looking at the code I found that if ChromeCustomTabs is not supported, it looks for other browser to open the url.
The device I am using doesn't have any default browser.

**Comment by grzesiek2010** [comment]
> The device I am using doesn't have any default browser.

That's strange, as said I've never seen such a device but it's not the first issue that shows me everything is possible when there is such a wide range of devices with Android OS.

File: collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+    protected void onCreate(Bundle savedInstanceState) {
+        super.onCreate(savedInstanceState);
+        setContentView(R.layout.activity_web_view);
+
+        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
+        setSupportActionBar(toolbar);
+        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
+        getSupportActionBar().setHomeAsUpIndicator(R.drawable.ic_close);
+
+        String url = getIntent().getStringExtra("url");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java]: It would be good to add a static filed for this string then you can use such a field in both places (both places you use "url") which is safer.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java [hunk 2]
```diff
@@ -93,8 +95,10 @@ public void openUri(Context context, Uri uri) {
             customTabsIntent.intent.setPackage(getPackageName(context).get(0));
             customTabsIntent.launchUrl(context, uri);
         } else {
-            //open in an external browser
-            context.startActivity(new Intent(Intent.ACTION_VIEW, uri));
+            //open in webview
+            Intent intent = new Intent(context, WebViewActivity.class);
+            intent.putExtra("url",uri.toString());
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java]: There is no checkstyle for that? I mean it should be a space before `uri.toString() `. Please fix.

Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java]: There is no checkstyle for that, I tried running it but it didn't show any such issue.
But will make the changes.

**Comment by grzesiek2010** [comment]
@lakshyagupta21 so now it works in that way:
Use chrome custom tabs if available otherwise use your webView. Am I right? Why do we skip a default browser at all? Couldn't it work in that way?:
Use chrome custom tabs if available otherwise use a default browser if available otherwise use your webView.

**Comment by lakshyagupta21** [comment]
I think it would be preferable to not to move user focus from app to other browser.
What do you think?

**Comment by grzesiek2010** [comment]
> What do you think?

I'm not sure I expected your fix only for that last case but hmmmm... I think it depends. It should be tested using various devices and then we will know whether it works well, faster, slower etc. 

@lognaturel what is your opinion?

**Comment by grzesiek2010** [comment]
@lakshyagupta21 
I would also recommend removing zoom buttons. We agreed [here](https://github.com/opendatakit/collect/pull/1807) they don't look good. Zooming should be possible of course but only using fingers.

**Comment by mmarciniak90** [comment]
**Bug has been found!**

1. User  loads a ODK webside
2. User do not see zoom buttons
3. User zooms using fingers
4. Zoom buttons appear

**Comment by mmarciniak90** [comment]
@lognaturel @lakshyagupta21 

* I was able to reproduce this problem only on 2 devices : Android 6.0 and 8.0, because I was able to disable a Chrome browser. **There is no option to uninstall it.**

| Chrome | Standard Browser |
| ------------- | ------------- |
|  |  |


* Other 5 devices has standard browser which could not be disabled : Android 4.1, 4.2, 4.4, 5.1, 7.0
* Crash do not occur which is great but in my opinion external browser works faster. WebView reloads page when user changes device orientation. Page is zoomed as default.
* I agree with @grzesiek2010, Collect should opens additional browser if available, otherwise use a default browser if available, otherwise use WebView.



| External browser | Internal browser |
| ------------- | ------------- |
| screenshot_20180207-152821 | screenshot_20180207-152733 |

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "needs discussion"

**Comment by lakshyagupta21** [comment]
I agree with @mmarciniak90 that external browser works faster than `WebView`.
[Link](https://medium.com/google-developers/best-practices-for-custom-tabs-5700e55143ee)

Even I agree with @grzesiek2010 that we should check for default browser first if available then go for  WebView if we take performance into consideration.

File: collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
+package org.odk.collect.android.activities;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java:15]: Please add a license header with your name in it https://github.com/opendatakit/collect/blob/master/LICENSE.md#appendix-how-to-apply-the-apache-license-to-your-work

File: collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java [hunk 4]
```diff
@@ -93,8 +96,10 @@ public void openUri(Context context, Uri uri) {
             customTabsIntent.intent.setPackage(getPackageName(context).get(0));
             customTabsIntent.launchUrl(context, uri);
         } else {
-            //open in an external browser
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java:96]: As suggested by @grzesiek2010 and @mmarciniak90, please use an external browser when available.

**Review by lognaturel — CHANGES_REQUESTED** [review]

**Review by lognaturel — APPROVED** [review]
