### PR TITLE
Fixed starting scanning codes

### LINKED ISSUE #5266: Unable to scan configuration QR code after granting camera permission via open settings option
**Software and hardware versions** 

Collect v2022.1.0,  Android probably all

**Problem description**

When the user denies access to camera while trying to add a project via QR code and then grants permission to camera by opening the app settings, the QR code scanner is available but not able to scan a QR code. If the user rotates the screen, the scanner works as expected.

**Steps to reproduce the problem**

1. Deny ODK Collect app access to camera in device settings permissions (if the camera permission was allowed before).
2. Go to ODK Collect app.
3. Click add project via QR code.
4. In the dialog asking to allow taking pictures choose deny/don’t allow.
5. In the next camera permission dialog choose open settings.
6. Allow ODK Collect to access the camera.
7. Go back to scanning a QR code.

**Expected behavior**

The user is be able to scan a QR code after granting the permission.

**Other information**

In Collect v2021.3.4 in the second dialog asking to grant camera permission there isn’t open settings option so I wasn’t able to reproduce it by following the same steps.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5266

#### What has been done to verify that this works as intended?
I've verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
I've just move starting scanning to a method that is called when a fragment becomes visible to make sure it's called when a user comes back from settings.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please just verify that the issue is fixed I can't think of any other areas that could be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt [hunk 1]
```diff
@@ -144,6 +148,13 @@ class QrCodeProjectCreatorDialog :
             dismiss()
         }
         beepManager = BeepManager(requireActivity())
+
+        return binding.root
+    }
+
+    override fun onStart() {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt:153]: Moving `startScanning` to `onStart` needs a test.

File: collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt [hunk 2]
```diff
@@ -0,0 +1,15 @@
+package org.odk.collect.android.fragments
+
+import com.google.zxing.integration.android.IntentIntegrator
+import com.journeyapps.barcodescanner.BarcodeResult
+import org.odk.collect.externalapp.ExternalAppUtils.returnSingleValue
+
+class BarcodeWidgetScannerFragment : BarCodeScannerFragment() {
+    override fun getSupportedCodeFormats(): Collection<String>? {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt:8]: Guessing this shouldn't be nullable?

File: collect_app/src/main/java/org/odk/collect/android/views/BarcodeViewDecoder.kt [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+
+import androidx.lifecycle.LiveData
+import androidx.lifecycle.MutableLiveData
+import com.journeyapps.barcodescanner.BarcodeResult
+import com.journeyapps.barcodescanner.DecoratedBarcodeView
+
+open class BarcodeViewDecoder {
+    open fun waitForBarcode(view: DecoratedBarcodeView): LiveData<BarcodeResult> {
+        val liveData = MutableLiveData<BarcodeResult>()
+
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/views/BarcodeViewDecoder.kt]: This can probable just be a single line `return` with an `also` now.

**Review by seadowg — CHANGES_REQUESTED** [review]
Just a couple of tweaks needed but looks good. I don't quite understand why the shift to `onStart` works? Does `onStart` get called when returning to the Activity, but `onCreateView` doesn't? I would have thought you'd need to move to `onResume`.

File: collect_app/src/main/java/org/odk/collect/android/views/BarcodeViewDecoder.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/views/BarcodeViewDecoder.kt]: Done.

File: collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt:8]: Done.

File: collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt:153]: Done.

**Review by seadowg — APPROVED** [review]

File: collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt [hunk 4]
```diff
@@ -72,6 +73,22 @@ class QrCodeProjectCreatorDialogTest {
         }
     }
 
+    // https://github.com/getodk/collect/issues/5266
+    @Test
+    fun `requestCameraPermission() should be called in onStart() to make sure it is called after returning to the dialog`() {
+        val scenario = launcherRule.launch(QrCodeProjectCreatorDialog::class.java)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt]: I just remembered that `FragmentScenarion` can have a specified initial state but our `FragmentScenarioLauncher#launch` doesn't support it yet. You could add that in here (see `FragmentScenarioLauncher#launchInContainer` for reference) and then you could just test that camera permissions are requested when moving to `STARTED` and not need to call `moveToState`. You'd also be able to just test that the permission is requested and that could be recorded with a boolean rather than a count which might be a bit nicer to read at the assertion points.

**Comment by srujner** [comment]
**Problem Description**
ODK app crashes after clicking on the "Get barcode" button.
On Master [3189736](https://github.com/getodk/collect/commit/31897362c00974e7df889ef685337244f0ac5604) and Store version 2022.3.5 issue is not reproducing

**Steps to Reproduce:**

1. Open all widgets form;
2. Navigate to the Media Widgets -> Barcode Widget;
3. Click "Get barcode" button;
4. App will crash

**Comment by grzesiek2010** [comment]
@srujner ok It's fixed. @seadowg it turns out that  `override fun getSupportedCodeFormats(): Collection<String>?`  must be nullable because `IntentIntegrator.ALL_CODE_TYPES` is null.

File: collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt]: Ok I've just added some improvements.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android: 10

**Verified cases:**
- issue #5266 and the issue from the PR are no longer reproducing
- scanning QR code via „add project”
- reconfiguring a project with QR code
- barcode widget
- allowing/ denying camera access
- opening device settings and allowing/ denying camera access
- rotating, minimizing, locking screen

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android: 13
