### PR TITLE
Fix: Handle image chooser intent

### LINKED ISSUE #1932: Fail gracefully when a device doesn't have an app to handle an image pick intent
#### Software and hardware versions 
Collect v1.13.0 and prior

#### Problem description
If a device doesn't have an app to pick an image and the user attempts to select a QR code, Collect hard crashes.

#### Steps to reproduce the problem
Don't have any app that can pick an image. Go to Admin Settings > Import/Export settings and then tap "Select code".

#### Expected behavior
Graceful failure, for example with a toast that no image picking application is on the device.

#### Other information 
```
android.content.ActivityNotFoundException: 
  at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:1632)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1541)
  at android.app.Activity.startActivityFromFragment (Activity.java:4001)
  at android.app.Fragment.startActivityForResult (Fragment.java:1089)
  at android.app.Fragment.startActivityForResult (Fragment.java:1073)
  at org.odk.collect.android.fragments.ShowQRCodeFragment.onClick (ShowQRCodeFragment.java:152)
  at android.view.View.performClick (View.java:4461)
  at android.view.View$PerformClick.run (View.java:18540)
  at android.os.Handler.handleCallback (Handler.java:733)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5164)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:790)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:606)
  at dalvik.system.NativeStart.main (Native Method)```

### PR DESCRIPTION
**Pull request by sashank27**
Closes #1932 

#### Why is this the best possible solution? Were any other approaches considered?
It handles check for the `packageManager()` , an ideal solution

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

@lognaturel please review

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 1]
```diff
@@ -149,7 +149,12 @@ public void onClick(View v) {
             case R.id.btnSelect:
                 Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
                 photoPickerIntent.setType("image/*");
-                startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                if (photoPickerIntent.resolveActivity(getActivity().getPackageManager()) != null) {
+                    startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                } else {
+                    ToastUtils.showShortToast(getString(R.string.no_image_chooser));
+                    Timber.e(getString(R.string.no_image_chooser));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: It should be `Timber.w` it's not our fault that user doesn't have any external app to capture images.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -576,4 +576,5 @@
     <string name="newer_version_of_a_form_info">This is an updated version of a form you already have!</string>
     <string name="svg_file_does_not_exist">SVG file does not exist!</string>
     <string name="svg_not_supported_device">ImageMap widget requires Android 5 (Lollipop) or newer. Your device is not supported!</string>
+    <string name="no_image_chooser"> No suitable application to handle this request</string>
```
Comment (grzesiek2010) [inline collect_app/src/main/res/values/strings.xml]: Please remove that space at the beginning and I would add something more. Users should know that it's about camera apps.

Comment (sashank27) [reply collect_app/src/main/res/values/strings.xml]: @grzesiek2010 could you please suggest something?

Comment (grzesiek2010) [reply collect_app/src/main/res/values/strings.xml]: The same we use in all other similar cases. Here is an example https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L194 instead of `image capture` you can put `QR code scan`

Comment (sashank27) [reply collect_app/src/main/res/values/strings.xml]: @grzesiek2010 this PR addresses the issue of not having an image chooser application (like, gallery).
I have modified the string. Please have a look.

Comment (grzesiek2010) [reply collect_app/src/main/res/values/strings.xml]: ahh I missed it so I think you can use exactly this one https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L213

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 3]
```diff
@@ -149,7 +149,12 @@ public void onClick(View v) {
             case R.id.btnSelect:
                 Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
                 photoPickerIntent.setType("image/*");
-                startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                if (photoPickerIntent.resolveActivity(getActivity().getPackageManager()) != null) {
+                    startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                } else {
+                    ToastUtils.showShortToast(getString(R.string.activity_not_found));
+                    Timber.w(getString(R.string.activity_not_found));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: But you should use as it is in this example `choose image` argument as well (in both cases) https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L213

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 4]
```diff
@@ -149,7 +150,14 @@ public void onClick(View v) {
...
                 Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
                 photoPickerIntent.setType("image/*");
-                startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                if (photoPickerIntent.resolveActivity(getActivity().getPackageManager()) != null) {
+                    startActivityForResult(photoPickerIntent, SELECT_PHOTO);
+                } else {
+                    Toast.makeText(getActivity(),
+                            getString(R.string.activity_not_found, "select image"),
+                            Toast.LENGTH_SHORT).show();
+                    Timber.w(getString(R.string.activity_not_found, "select image"));
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java]: Is `getString` required in Timber? I guess this will also work
`Timber.w(R.string.activity_not_found, "select image");`

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android:
* I was able to reproduce problem on Android **4.1, 4.4, 6.0, 8.0**. On apk with fix user sees toast:

screenshot_2018-02-28-15-16-58

* I was not able to disable the gallery app on Android **4.2, 5.1, 7.0**. I did not notice regression.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks very much, @sashank27, @grzesiek2010!
