### PR TITLE
Fixed regression in GeopointWidget with placement-map appearance

### LINKED ISSUE #2457: GeoPointWidget with placement-map appearance doesn't work
#### Software and hardware versions 
Collect v1.16.0 and v1.16.1

#### Problem description
The issue has been originally reported on the forum https://forum.opendatakit.org/t/odk-collect-v1-16-x-problem-with-geopoint-placement-map/14418
I was able to reproduce the issue.

#### Steps to reproduce the problem
1. Open GeoPointWidget with placement-map appearance (eg. from `All widgets` form available on the demo server)
2. Try to select any location.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2457 

#### What has been done to verify that this works as intended?
I tested GeopointWidget with `placement-map` appearance and confirmed that everything works well like in v1.15.0.

#### Why is this the best possible solution? Were any other approaches considered?
It's just a fix of regression. The problem has been introduced in https://github.com/opendatakit/collect/issues/2291
GeopointWIdget didn't work because `locationClient.start();` was called before `locationClient.setListener(this);` - race condition.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
btw. that shows even a small change (like #2291) should be tested by our QAs.

**Review by jd-alexander — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java [hunk 1]
```diff
@@ -139,17 +139,10 @@ public void onCreate(Bundle savedInstanceState) {
...
             setupMap(googleMap);
             locationClient.setListener(this);
+            locationClient.start();
         });
     }
 
-    @Override
-    protected void onStart() {
-        super.onStart();
-        Collect.getInstance().getActivityLogger().logOnStart(this);
```
Comment (yanokwa) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java:148]: I think it's fine to remove this line because we are removing the ActivityLogger, but it'd be good to get this separate commit next time.

**Comment by mmarciniak90** [comment]
**Tested with success!** 

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Verified cases:
* GeopointWidget with placement-map appearance
* Other geo widgets in All Widgets form
* Google maps
* OSM maps

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by lognaturel** [comment]
Agreed, thanks for the reminder, @grzesiek2010!

@mmarciniak90 do you now have a case that covers this kind of situation for release testing?

**Comment by mmarciniak90** [comment]
@lognaturel yes, now we have a separate test case for Geopoint Widget with the placement-map appearance
