### PR TITLE
Fixed displaying valid and invalid drafts on a map

### LINKED ISSUE #5783: In the form map geopoints saved as drafts are points (not pins)
#### ODK Collect version
v2023.3.x 07d46881077671ad8ff893c8a9509581510f93e3
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
In the form map geopoints saved as drafts are points (not pins). 
The issue doesn't occur in finalized or sent forms.
The issue doesn’t occur in the store version.
formmap

#### Steps to reproduce the problem
1. Go to All widgets form and add a geopoint.
2. Save the form as draft.
3. Go to the All widgets form map.
#### Expected behavior
The saved geopoint should be a pin on the form map.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5783

#### Why is this the best possible solution? Were any other approaches considered?
I've updated the method responsible for returning map icons based on the status. Both `valid` and `invalid` drafts are displayed in the same way like `incomplete` ones before (with a blue icon).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This is a small change so testing the scenario described in the issue should be enough. However, there might be also other similar issues caused by introducing new instance statuses (`valid` and `invalid`) so be careful.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt [hunk 1]
```diff
@@ -194,7 +194,7 @@ class FormMapViewModel(
 
     private fun getDrawableIdForStatus(status: String, enlarged: Boolean): Int {
         return when (status) {
-            Instance.STATUS_INCOMPLETE -> if (enlarged) R.drawable.ic_room_form_state_incomplete_48dp else R.drawable.ic_room_form_state_incomplete_24dp
+            Instance.STATUS_INCOMPLETE, Instance.STATUS_VALID, Instance.STATUS_INVALID -> if (enlarged) R.drawable.ic_room_form_state_incomplete_48dp else R.drawable.ic_room_form_state_incomplete_24dp
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt:197]: We might want to distinguish somehow `valid` and `invalid` instances (by displaying different icons/info) but that's something for a separate issue that could be a part of v2023.4 @lognaturel what do you think?

**Review by lognaturel — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

Verified cases:
- issue #5783 is no longer reproducible
- geopoints with different status in the form map
- saving, editing, sending geopoints
- encrypted geopoints
- changing status of a geopoint form finalized to draft

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13
