### PR TITLE
Fix bad queries after adding new propreties to entity list

### LINKED ISSUE #6396: Mismatch error after finalizing forms, adding property in Central and refreshing list of blank forms
#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Galaxy m23
#### Problem description 1
There's an error after finalizing a registration form, adding a property via Central and opening the update form after refreshing the list of blank forms
PropertyAdded

#### Steps to reproduce
1. Download user cacti https://staging.getodk.cloud/#/projects/101/app-users
2. Set auto send to "off”
3. Fill and finalize the cactus registration form.
4. Go to Central and add a property.
5. In Collect refresh the list of blank forms
6. Open the cactus monitoring form.

#### Problem description 2
I encounter a mismatch error after the steps described below. It occurs in also in other entities update forms but with  different mismatch error (same steps). I wasn't able to reproduce it on Pixel 7a (Android 14). It might be connected with entities forms
 with spec 2024.1.0
 mismatch

#### Steps to reproduce the problem
1. Download user cacti https://staging.getodk.cloud/#/projects/101/app-users to Collect.
2. Set auto send to "off".
3. Fill and finalize the cactus registration form.
4. Go to Cactus monitoring form and update the created entity. Finalize the form.
5. Go to Cactus monitoring form and update the same entity again. Finalize the form.
6.  In Central add a new property (+new).
addProperty
7. In Collect refresh the list of blank forms.
8. Open the cactus monitoring form.

#### Other information
If apk from #6376 is used to reproduce the steps the error doesn't occur after the steps above.
A mismatch error occurs if you follow steps 1-8 and after that 
go to"Ready to send" and send all forms
Go to "Start new form" and refresh the list of blank forms
Open the cactus monitoring form
sentRefresh

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6396

#### Why is this the best possible solution? Were any other approaches considered?

As per the discussion in #6396, the conclusion was eventually made that the root cause was due to `ALTER TABLE` statements being executed in a shared database connection (`SqlLiteOpenHelper`). The solution here is to reset that connection (using a new `DatabaseConnetion#reset` method) so that follow-up queries do not end up getting incorrect/state data or data structures.

I've also added a new `SynchronizedDatabaseConnection` class that allows us to interact with `DatabaseConnection` in a synchornized way to stop prevent any problems that might come up from concurrent access combined with `reset()`. The reason for this is described in a comment on `reset()`:

```kotlin
/**
 * Closes the underlying connection and clears state so that subsequent accesses will create
 * a new connection.
 *
 * This can be dangerous if the database is being access by multiple threads as the connection
 * might be closed while a transaction is running or while another thread is using a
 * [SQLiteDatabase] instance obtained via [writeableDatabase] or [readableDatabase]. Using
 * [SynchronizedDatabaseConnection] is recommended in those scenarios.
 */
```

Using synchornized access for `DatabaseConnection` in `DatabaseEntitiesRepository` will theoretically have performance implications as two threads will not be able to simultaneously read from the DB. To some level this was already not possible (as `SqlLiteOpenHelper` serializes calls to the actual underlying database), but it will certainly expand the amount of "blocking" code. The real world impact for entities is basically non-existent as we're planning to remove concurrent form entry/form updates anyway in #6232 which would be the only situation that would benefit as far as I can tell. I think adding this lower level protection is important to reduce the risk of adding race conditions down the road.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This should just fix the bug. Checking entity form downloads and form entry would be good here as this is a fairly low level change that could always have unforeseen consequences.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by dbemke** [comment]
I'm not able to reproduce the issue #6396 (error doesn't occur) and I haven't found any errors connected with adding properties in Central so it seems that it's fixed

File: db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+    /**
+     * Runs a transaction and then calls [DatabaseConnection.reset]. Useful for transactions
+     * that will mutate the DB schema.
+     */
+    fun <T> resetTransaction(
+        body: SQLiteDatabase.() -> T
+    ) {
+        transaction(body)
+        databaseConnection.reset()
```
Comment (seadowg) [inline db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt:44]: I'd been unable to write a Robolectric test that would drive out adding this `reset()` with the existing implementation. I'm guessing that it may have been possible to write one in an instrumentation test. 

However, now if you remove `reset()`, a few tests fail in the existing `DatabaseEntitiesRepository`. This is because the change to looking up columns to determine which to add (using `ALTER TABLE`) is much more sensitive to the problem than the previous implementation that used a `try-catch` to just "fire and forget" add columns. I'm leaning towards not bothering with a new instrumentation test as it feels unlikely that anyone would go back to the old hacky implementation, but happy to debate that!

File: db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import androidx.core.database.sqlite.transaction
+
+class SynchronizedDatabaseConnection(
+    context: Context,
+    path: String,
+    name: String,
+    migrator: DatabaseMigrator,
+    databaseVersion: Int
+) {
+    private val databaseConnection = DatabaseConnection(
```
Comment (grzesiek2010) [inline db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt:14]: `SynchronizedDatabaseConnection` could just extend `DatabaseConnection`. Wouldn't that be clearer? Then `withSynchronizedConnection` which is only used in `SynchronizedDatabaseConnection` could be moved from `DatabaseConnection` to `SynchronizedDatabaseConnection`.

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt [hunk 3]
```diff
@@ -121,32 +119,34 @@ class DatabaseEntitiesRepository(context: Context, dbPath: String) : EntitiesRep
...
     override fun updateListHash(list: String, hash: String) {
         val contentValues = ContentValues().also {
             it.put(ListsTable.COLUMN_HASH, hash)
         }
 
-        databaseConnection
-            .writeableDatabase
-            .update(
+        databaseConnection.withConnection {
+            writeableDatabase.update(
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: I've just spotted that there is a typo here it should be `writableDatabase`.

File: db/src/main/java/org/odk/collect/db/sqlite/DatabaseConnection.kt [hunk 4]
```diff
@@ -40,30 +42,60 @@ open class DatabaseConnection @JvmOverloads constructor(
...
+
+    /**
+     * Access the database in a synchronized manner. This is not usually required, but should be
+     * used if a calls to [reset] will be made.
+     *
+     * Does not guarantee synchronized access if this or another [DatabaseConnection] for the
+     * same `.db` file uses [writeableDatabase] or [readableDatabase].
+     * [SynchronizedDatabaseConnection] can be used to ensure synchronized writes/reads to the
+     * underlying DB.
+     *
```
Comment (grzesiek2010) [inline db/src/main/java/org/odk/collect/db/sqlite/DatabaseConnection.kt]: We don't need this empty line in the comment.

File: db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt (hunk 2 above)
Comment (grzesiek2010) [reply db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt:14]: Hmm I'm wondering if haveing a separate class like `SynchronizedDatabaseConnection` makes sense at all, maybe we should just keep everything in `DatabaseConnection`?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt (hunk 2 above)
Comment (seadowg) [reply db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt:14]: My thinking here is that "wrapping" the type rather than extending it (or expanding it) means that we ensure you can't call `writeableDatabase` or `readableDatabase` from `DatabaseEntitiesRepository`. One option would be to use extension but flip the hierarchy so that the stricter interface (`SynchronizedDatabaseConnection`) would be the super type of the more permissive one (`DatabaseConnection`). I think I prefer the wrapping though. What do you think?

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: English is the worst!

File: db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt (hunk 2 above)
Comment (grzesiek2010) [reply db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt:14]: Ok makes sense.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
There are still some occurrences of `writeable` in `DatabaseFormsRepository` please fix them as well.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue #6396 doesn't occur
- exploratory testing with adding properties via Central and in forms

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14
