### PR TITLE
Fixed deleting entities from lists with special characters

### LINKED ISSUE #6559: Crash when updating entities for list with special characters
From [this crash report](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/a1a0cc7321a992cf90a86f21d329e3e7?versions=v2024.3.3%20(5025)&time=last-ninety-days&types=crash&sessionEventKey=677E418F017A000113417B0F4DBDF82C_2035916633464756732).

If an entity is removed on the server, Collect will crash when the form (and therefore the entity list) is updated if the list contains special characters like `-`.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6559 

#### Why is this the best possible solution? Were any other approaches considered?
We need to quote the list name to make it possible to use special characters in table names in SQL. It's not the first issue like that so this approach is the same as it was before in the case of similar problems.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We’ve encountered issues with handling special characters in entities in other areas before, so this isn’t a new problem. Please test it as described in the issue (deleting entities), but keep in mind that this might not be the last case we’ll need to address.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with entities where lists contain special characters like `.` or `-`.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
This should target `v2024.3.x` instead of `master` as we want to put it out as a hotfix.

**Comment by grzesiek2010** [comment]
> This should target v2024.3.x instead of master as we want to put it out as a hotfix.

Fixed.

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt [hunk 1]
```diff
@@ -428,6 +428,27 @@ abstract class EntitiesRepositoryTest {
...
+    @Test
+    fun `#delete supports list names with dots and dashes`() {
+        val repository = buildSubject()
+
+        val leoville = Entity.New("1", "Léoville Barton 2008")
+
+        repository.save("wines.x", leoville)
+        repository.save("wines-x", leoville)
+
+        repository.delete("1")
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt:440]: This makes me realize that `delete` should probably take a list as an arg as well, but that's for another time!

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt [hunk 2]
```diff
@@ -198,7 +198,7 @@ class DatabaseEntitiesRepository(context: Context, dbPath: String) : EntitiesRep
         databaseConnection.withConnection {
             getLists().forEach {
                 writableDatabase.delete(
-                    it,
+                    "`$it`",
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: Is there a reason to use backticks here instead of quotes like in the rest of the file?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: No, it looks like we can use both.

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt:440]: Right: https://github.com/getodk/collect/issues/6566

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: Ok let's make it consistent. Maybe we should introduce a `quote` method?

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6561#discussion_r1918140076

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt]: Oh weird I said: `No, it looks like we can use both.` and at the same time made it consistent but it looks like I didn't push the changes...

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10 and 12 (by Szymon) 

**Verified cases:**
- issue #6569 doesn't occur
- deleting entities
- form with different names of dataset (special characters)

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 15
