### PR TITLE
Remove option to save geotrace as polygon

### LINKED ISSUE #1028: Geotrace widget should only capture lines, not polygons
#### Software and hardware versions 
Collect v1.6.1

#### Problem description
The geotrace widget is not implemented as documented in the specs.  According to the documentation available here:
https://opendatakit.github.io/xforms-spec/
http://xlsform.org/

According to the specs, geotrace is for lines, and geoshape is for polygons.  In ODK Collect, geotrace allows you to collect lines or polygons.  

#### Steps to reproduce the problem
Create a form with a geotrace widget and launch in ODK Collect.  Collect a geotrace in the widget and click the save button, which prompts you to "Save as polygon" or "save as polyline"

#### Expected behavior
Geotrace should be used to collect lines only.

#### Other information 
Geotrace and geoshape should both allow you to use your current position, a timed interval, OR a long press, to draw a vertex.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #1028, at long last. This simply removes the dialog which @zestyping has nicely isolated and commented as being destined for removal.

The meaningful changes are all in [GeoPolyActivity](https://github.com/opendatakit/collect/pull/3078/files#diff-f621fd09c7f2ba5014d28c79def7b386). The other changes are for removing unused resources.

#### What has been done to verify that this works as intended?
From the All Widgets form, launched geotrace and verified that:
- saving a blank trace still results in a blank value being written to the form instance
- tapping the save button doesn't display a dialog, whether or not there are points to save
- tapping the save button after entering a single point shows a toast error
- tapping the save button after entering points saves that number of points
- the first and last point saved are different

From the All Widgets form, launched geoshape and verified that:
- saving a blank shape still results in a blank value being written to the form instance
- tapping the save button doesn't display a dialog, whether or not there are points to save
- tapping the save button after entering one or two points shows a toast error
- tapping the save button after entering points saves that number of points
- the first and last point saved are the same

#### Why is this the best possible solution? Were any other approaches considered?
This is a surgical removal so there aren't any real alternatives.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This fully removes the ability to save a polygon using the geotrace widget. This means that users who rely on their enumerators picking trace or shape will need to redeploy their forms or block updates as described [on the forum](https://forum.opendatakit.org/t/warning-collect-removing-save-as-polygon-from-geotrace/18277).

Although the intent is just to modify geotrace, code is shared between geotrace and geoshape so both are at risk of regressions. There's no risk that the change affects different Android versions differently so verification on one Android version should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
All Widgets

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
https://github.com/opendatakit/docs/issues/968

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java [hunk 1]
```diff
@@ -29,6 +27,8 @@
 import android.widget.Spinner;
 import android.widget.TextView;
 
+import androidx.annotation.VisibleForTesting;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java:30]: This got reordered automatically by Android Studio because it went from an `android.` package to an `androidx.` package.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

| Case | GeoTrace | GeoShape |
|---|---|---|
| saving a blank trace/shape still results in a blank value being written to the form instance|:heavy_check_mark:|:heavy_check_mark:|
| tapping the save button doesn't display a dialog, whether or not there are points to save | :heavy_check_mark:|:heavy_check_mark:|
| tapping the save button after entering a single (Geotrace) point OR one or two points (GeoShape) shows a toast error| :heavy_check_mark:| :heavy_check_mark:|
| tapping the save button after entering points saves that number of points | :heavy_check_mark:|:heavy_check_mark:|
| the first and last point saved are different |:heavy_check_mark:| - |
| the first and last point saved are the same | - |:heavy_check_mark:|

Verified also:
- removing response
- removing single point
- removing all points
- update previously saved points
- three methods of recording location

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "behavior verified"
