### PR TITLE
Clicking an image used as a choice does not select that option

### LINKED ISSUE #1510: Clicking an image used as a choice does not select that option
#### Software and hardware versions 
Collect v1.10.2, Android v4.4.2, Samsung S4 mini (GT-I9190)

#### Problem description
I have a yes/no question, and have added thumbs-up / thumbs-down images to the choices.
Tapping on the images does not select yes/no - the user has to tap on the actual "Yes" or "No" text, which is not intuitive, especially when the image is significantly larger than the text.

#### Steps to reproduce the problem
Create a single-select question with an `image` column in the choices sheet, and provide images for the choices.

#### Expected behavior
Tapping the image should select the corresponding option

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1510 

#### What has been done to verify that this works as intended?
I've tested attached form which contains Select One Question and Select Multiple Question (both witch images)

#### Why is this the best possible solution? Were any other approaches considered?
In this case there is only one solution - checking/unchecking buttons after clicking on images too.

#### Are there any risks to merging this code? If so, what are they?
I've changed this line https://github.com/opendatakit/collect/compare/master...grzesiek2010:COLLECT-1510?expand=1#diff-8a96509b41b463c22daa03b8c26a6637L171 in order to be able to click on the empty space after image too. I tested it and everything is ok but it would be good to check it on various devices to be sure images are in the same places as before and they look like before.

#### Do we need any specific form for testing your changes? If so, please attach one.
Yes. Here you go: 
[form.zip](https://github.com/opendatakit/collect/files/1358733/form.zip)

Just to clarify. We should be able to select an answer by clicking on an image only if `big-image` attribute is not specified, otherwise if you click on that image you should be able to see it in gallery (full screen). Attached form contains that case.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Tested with success.
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0
User is able to click on image to select answer if this attribute is added 
`<value form="image">jr://images/a.png</value>`

In case when those attributes are added 
`<value form="image">jr://images/a.png</value>`
`<value form="big-image">jr://images/a.png</value>`
image opens in gallery or other app selected by user.

This solution works for single select widget and multi select widget.

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java [hunk 1]
```diff
@@ -232,32 +232,41 @@ public void onClick(View v) {
...
-                        if (bigImageURI != null) {
-                            imageView.setOnClickListener(new OnClickListener() {
-                                String bigImageFilename = ReferenceManager.instance()
-                                        .DeriveReference(bigImageURI).getLocalURI();
-                                File bigImage = new File(bigImageFilename);
-
+                        imageView.setOnClickListener(new OnClickListener() {
+                            @Override
+                            public void onClick(View v) {
+                                Collect.getInstance().getActivityLogger().logInstanceAction(
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java]: I know we really need to deprecate this but in the mean time, to preserve semantics, I think it should go in the `bigImageURI != null` block.

**Review by lognaturel — COMMENTED** [review]
Thank you for the super detailed pull request description and great testing form!

**Review by lognaturel — APPROVED** [review]
Love those images! 😊

**Comment by acawood777** [comment]
Thanks @grzesiek2010 for the speedy fix!
