### PR TITLE
Application Start bug Fix

### LINKED ISSUE #466: java Null Pointer Exception on getVersionedAppName() method thus causing app to crash
#### Software and hardware versions 
Collect v1.x.x, Android v5.1.1, device used...

#### Problem description
App Crashes as soon as it installs.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by Ishmeetsingh97**
Fixes #466

### CODE REVIEW

**Comment by yanokwa** [comment]
@grzesiek2010 can you take a look at this one?

**Comment by Ishmeetsingh97** [comment]
Hi, @lognaturel Can you please review this ?

**Comment by grzesiek2010** [comment]
@yanokwa @Ishmeetsingh97 I can confirm that this solution works well but [attached explanation](https://github.com/opendatakit/collect/issues/466#issuecomment-287609660) is wrong to me.

> the context of getPackageManager() method is null

You are wrong it isn't. We get null when we call [versionName](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/application/Collect.java#L178).

Looks like @Ishmeetsingh97's solution is good because `BuildConfig.VERSION_NAME` doesn't return null it's just empty string when git is missing so we get an empty string instead of null (like using our current approach) and everything is ok. I like this solution and I think it's enough for us.

@Ishmeetsingh97 Thanks!

**Comment by Ishmeetsingh97** [comment]
@grzesiek2010 Thanks. Looking forward for more contribution to ODK Collect. 
@yanokwa Can you please review ?

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java [hunk 1]
```diff
@@ -172,15 +172,8 @@ public void setExternalDataManager(ExternalDataManager externalDataManager) {
 
     public String getVersionedAppName() {
         String versionName = "";
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: Please remove this as it's unnecessary.

Comment (Ishmeetsingh97) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: I did not understand, What should i remove ?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: You can just keep:

> String versionName = BuildConfig.VERSION_NAME;
        versionName = " " + versionName.replaceFirst("-", "\n");

Am I wrong?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: You can replace the three starting lines of the method with `String versionName = BuildConfig.VERSION_NAME.replaceFirst("-", "\n");`

Comment (Ishmeetsingh97) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: Okay, I'll Update it.

**Comment by Ishmeetsingh97** [comment]
I've done the changes. Please review @lognaturel @yanokwa @grzesiek2010

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java [hunk 2]
```diff
@@ -171,16 +171,7 @@ public void setExternalDataManager(ExternalDataManager externalDataManager) {
     }
 
     public String getVersionedAppName() {
-        String versionName = "";
-        try {
-            versionName = getPackageManager()
-                    .getPackageInfo(getPackageName(), 0)
-                    .versionName;
-            versionName = " " + versionName.replaceFirst("-", "\n");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: This space is important so please add that to your solution too.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Yes, sorry, you'll need to add the space in the string you return.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Please make sure to run it and verify the behavior to make sure it is unchanged, @Ishmeetsingh97!

Comment (Ishmeetsingh97) [inline collect_app/src/main/java/org/odk/collect/android/application/Collect.java]:
```
 String versionName = BuildConfig.VERSION_NAME
                .replaceFirst("-", "\n");
```
Is this approach okay ?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Yes. Just make sure that there is eventually a space put between the app name and the version name. You can run it to see why that's important.

Comment (Ishmeetsingh97) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: I've updated the same. Please review.
I've tried the application is working fine.

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: I think you need to test this without having git in your path. I think if git is not in your path, the `getVersionName` in the build.gradle will return null (it will go to the catch section). And then null.replaceFirst() will throw NPE in this code.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Did you verify this, @nribeka? The idea is that `BuildConfig.VERSION_NAME` will return an empty String.

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Let me see which vm doesn't have git in them and try this. I thought `VERSION_NAME` comes from whatever value assigned in the `versionName` in build.gradle.

Comment (Ishmeetsingh97) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Hi, Even after deleting the .git folder this solution works. I've tried and tested the same.

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: @lognaturel tried and it's returning empty String now. So this seems to be working correctly without git.

What I did:
* Change the case statement in gradle config to prevent it matching my os (changed 'unix' to 'unixx').
* The `getVersionName` execute the catch section and return null.
* Check the BuildConfig class and see the VERSION_NAME showing "".
* Run the application and it's starts fine.

Good enough to allow user without git in their path to run the app?

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: @Ishmeetsingh97 removing the .git folder will remove all the git record for your fork of the project (you shouldn't do that as you might lose your changes record). What I mean is remove git from your path or you can follow the step above.

Comment (Ishmeetsingh97) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java:179]: Actually I have 2 copies of the project for testing purposes. 
Thanks for the response.
Glad working with the community.
