### PR TITLE
Fix forms not being deletable

### LINKED ISSUE #6338: Not possible to delete drafts and sent instances of form that create or update entity
#### ODK Collect version
the master version 740f1a6e32873f91cccc297e4da0ff02697b54fb

#### Android version
10, 14 

#### Device used
Redmi 7, Galaxy M23

#### Problem description
Instances do not show up in delete forms - saved form, due to this it is not possible to delete drafts and sent instances of form that create or update entity.

#### Steps to reproduce the problem
1. Open Tree registration form
[trees_registration.xlsx](https://github.com/user-attachments/files/16597088/trees_registration.xlsx)
2. Fill form and send it
3. Go to Delete form - Saved forms
---
1. Open all question types form
2. Fill form and save it as draft
3. Go to Delete form - Saved forms

#### Expected behavior
It should be possible to delete drafts and sent instance of form that create or update entity

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6338

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot to discuss! The problem was just that `Instance` objects created via `Instance.Builder` had the wrong default value.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This should just fix the issue. It'll be good to check that forms can be deleted when expected.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package org.odk.collect.forms.instances
+
+import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.equalTo
+import org.junit.Test
+
+class InstanceTest {
+
+    @Test
+    fun `canDeleteBeforeSend is true by default`() {
```
Comment (grzesiek2010) [inline forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt:10]: We have that test `whenFormHasCreatedEntity_doesNotAppearInListToDelete`:
1. Please clarify what `created entity` means. You can add a comment or change the test name to make it clear that it takes place on finalizing.
2. I think it would be good to have a test in the same class where we just save a form as a draft and test if it can be deleted.

File: forms/src/main/java/org/odk/collect/forms/instances/Instance.java [hunk 2]
```diff
@@ -83,7 +83,7 @@ public static class Builder {
         private String geometry;
 
         private Long dbId;
-        private boolean canDeleteBeforeSend;
+        private boolean canDeleteBeforeSend = true;
```
Comment (grzesiek2010) [inline forms/src/main/java/org/odk/collect/forms/instances/Instance.java:86]: Is it handled correctly when forms are synced from disk and should be finalized?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: forms/src/main/java/org/odk/collect/forms/instances/Instance.java (hunk 2 above)
Comment (seadowg) [reply forms/src/main/java/org/odk/collect/forms/instances/Instance.java:86]: Do you mean if a form has an entity? We don't currently support local entity creation/updates for synced instances. Otherwise, every `Instance` should now be deletable.

File: forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt (hunk 1 above)
Comment (seadowg) [reply forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt:10]: > I think it would be good to have a test in the same class where we just save a form as a draft and test if it can be deleted.

I'd thought about that (I actually wrote that test then deleted it), but I realized we already had a test for finalized forms and felt like adding this unit test was simpler than testing all the possible states that saved forms could be in.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
Sent instances of forms that create or update entity still can't be deleted, those instances do not appear in delete form - saved forms.
Sent instances of non entity forms work correctly and those appear in saved forms - delete forms.
@seadowg

**Comment by seadowg** [comment]
> Sent instances of forms that create or update entity still can't be deleted, those instances do not appear in delete form - saved forms.
Sent instances of non entity forms work correctly and those appear in saved forms - delete forms.

Could you file an issue? As far as I can tell, we should be OK to delete sent forms that create/update entities. We can discuss over at the issue though.

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14

**Verified cases:**
- Deleting drafts, finalized and sent instances of forms that create or update entity
- Deleting drafts, finalized and sent instances of non entity forms
- Forms with auto delete

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
