### PR TITLE
Fixed updating index

### LINKED ISSUE #5939: The error outline disappears after clicking "Check for errors”
#### ODK Collect version
the master version
#### Android version
10
#### Device used
Redmi 9T
#### Problem description
The error outline disappears after clicking "Check for errors”. I’m not able to reproduce it each time I follow these steps but every few times it happens.
#### Steps to reproduce the problem
1. Open All widgets form with required questions.
[Allwidgetsrequired.xml.txt](https://github.com/getodk/collect/files/14084925/Allwidgetsrequired.xml.txt)
2. Fill answers in questions until you get to the Ex string widget.
3. Swipe to the next question so that the error outline appears.
4. Tap "Launch” so that the field to enter values appears.
5. Click three dots and "Check for errors”.
6. Click three dots and "Check for errors” again.

Video of related fail during tests [here](https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/5129211050557104413/executions/bs.bb94d9db0dde9a2e/testcases/11/video)

#### Expected behavior
The error outline shouldn’t disappear.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5939 

#### Why is this the best possible solution? Were any other approaches considered?
It was a race condition. The problem was that we always updated the index after validating answers which caused building a new widget. As a result, sometimes errors were displayed before creating a new widget and not displayed again after rebuilding the widget.

My first implementation was different: https://github.com/getodk/collect/pull/6005 but we have discussed it and decided that reworking the way errors are propagated would be better (see the conversation https://github.com/getodk/collect/pull/6005#discussion_r1522963425) to make sure questions are first created (if needed) and only then we display errors (also if needed).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
These changes should only fix the issue without bringing any additional changes. However, the way we display errors (the red outline) changed (it looks the same but the code changed) so please verify there is no regression when triggering errors in different ways:
- navigating between questions
- finalizing a form with errors
- validating forms

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with required questions or constraints.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -559,8 +559,15 @@ private void setupViewModels(FormEntryViewModelFactory formEntryViewModelFactory
         formEntryViewModel = viewModelProvider.get(FormEntryViewModel.class);
         printerWidgetViewModel = viewModelProvider.get(PrinterWidgetViewModel.class);
 
-        formEntryViewModel.getCurrentIndex().observe(this, index -> {
-            formIndexAnimationHandler.handle(index);
+        formEntryViewModel.getCurrentIndex().observe(this, indexAndValidationResult -> {
+            if (indexAndValidationResult != null) {
+                FormIndex formIndex = indexAndValidationResult.component1();
+                ValidationResult validationResult = indexAndValidationResult.component2();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:565]: This should be a `FailedValidationResult` strictly.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 2]
```diff
@@ -581,16 +588,7 @@ private void setupViewModels(FormEntryViewModelFactory formEntryViewModelFactory
...
-                String errorMessage = failedValidationResult.getCustomErrorMessage();
-                if (errorMessage == null) {
-                    errorMessage = getString(failedValidationResult.getDefaultErrorMessage());
-                }
-                getCurrentViewIfODKView().setErrorForQuestionWithIndex(failedValidationResult.getIndex(), errorMessage);
-                swipeHandler.setBeenSwiped(false);
-            } else if (validationResult instanceof SuccessValidationResult) {
-                SnackbarUtils.showLongSnackbar(findViewById(R.id.llParent), getString(org.odk.collect.strings.R.string.success_form_validation), findViewById(R.id.buttonholder));
-            }
+            handleValidationResult(validationResult);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:591]: I think we can potentially revise this now so that instead of `#getValidationResult`, all failed validations go through `#getCurrentIndex` and then we just need to expose the "success" notifications (that come out of `#validate`). That would also make the logic in `FormFillingActivity` simpler as we would always know if we're dealing with a success or a failure (unlike now where we have to account for both in `handleValidationResult`).

I know you're away next week, so that can totally be a follow-up if it doesn't seem like there's time. For the moment, maybe just deprecate `#getValidationResult` with a comment so it's clear we want to change that.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**
Verified on a device with Android 10
**Verified Cases:**
- issue #5939 doesn't occur
- regression checks in forms with constraints and required questions
- regression checks in audit logs
- don't keep activities enabled/disabled
- customized error messages

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14
