### PR TITLE
Fixes the leaked ServiceConnection error

### LINKED ISSUE #1288: Exception in logs when closing the activity using chrome custom tabs
Closing the activities using a chrome custom tab like the `AboutPreferencesActivity` throws an exception 

```
 Activity org.odk.collect.android.preferences.AboutPreferencesActivity has leaked ServiceConnection org.odk.collect.android.utilities.CustomTabHelper$1@1ad1eae that was originally bound here
                                                                         android.app.ServiceConnectionLeaked: Activity org.odk.collect.android.preferences.AboutPreferencesActivity has leaked ServiceConnection org.odk.collect.android.utilities.CustomTabHelper$1@1ad1eae that was originally bound here
                                                                             at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                             at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                             at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                             at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                             at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                             at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:70)
                                                                             at org.odk.collect.android.utilities.CustomTabHelper.bindCustomTabsService(CustomTabHelper.java:45)
                                                                             at org.odk.collect.android.preferences.AboutPreferencesFragment.onStart(AboutPreferencesFragment.java:67)
                                                                             at android.app.Fragment.performStart(Fragment.java:2379)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                                                                             at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2044)
                                                                             at android.app.FragmentController.dispatchStart(FragmentController.java:187)
                                                                             at android.app.Activity.performStart(Activity.java:6702)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
In reference to resolve #1288

### CODE REVIEW

**Comment by lognaturel** [comment]
I haven't done a thorough review yet but one thing comes to mind immediately -- is a similar fix needed in the URL widget?

**Comment by shobhitagarwal1612** [comment]
Yes. I tried using the same approach in the url widget as well but I can't override the onDestroy in the url widget.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
You need to override onDestroy method in FormEntryActivity and then try to call urlWidget if an existed widget is urlWidget.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 @lognaturel  I have moved the `customTabHelper` from `urlWidget` to `FormEntryActivity` so that the service can be binded and unbinded on activity's `onStart()` and `onDestroy()`. 
 Is this the correct approach?

**Comment by grzesiek2010** [comment]
I'm not a fun of this approach as FormEntryActivity is already really big class and is going to explode :). I would prefer the approach I described is it impossible?

**Comment by shobhitagarwal1612** [comment]
I agree with your point but it was not obvious to me how to implement your suggestion. Can you please give me some more hint in order to achieve that?

**Comment by grzesiek2010** [comment]
https://github.com/grzesiek2010/collect/commit/934d1b77abf7905f67fe75b33d11db80c0c11fcf
or even
https://github.com/grzesiek2010/collect/commit/977a322cebeb9634e41084c3812a262676ca3f66

**Comment by shobhitagarwal1612** [comment]
I tried the suggestions that you gave but it does not solve the problem. It did reach the `onDestroy` method in `UrlWidget ` but I got the following stack trace: 

```
Activity org.odk.collect.android.activities.FormEntryActivity has leaked ServiceConnection org.odk.collect.android.utilities.CustomTabHelper$1@ad34a17 that was originally bound here
                                                                       android.app.ServiceConnectionLeaked: Activity org.odk.collect.android.activities.FormEntryActivity has leaked ServiceConnection org.odk.collect.android.utilities.CustomTabHelper$1@ad34a17 that was originally bound here
                                                                           at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                           at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                           at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                           at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                           at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                           at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:70)
                                                                           at org.odk.collect.android.utilities.CustomTabHelper.bindCustomTabsService(CustomTabHelper.java:52)
                                                                           at org.odk.collect.android.widgets.UrlWidget.<init>(UrlWidget.java:53)
                                                                           at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:109)
                                                                           at org.odk.collect.android.views.ODKView.<init>(ODKView.java:198)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1239)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.refreshCurrentView(FormEntryActivity.java:854)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.onActivityResult(FormEntryActivity.java:777)
                                                                           at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                           at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                           at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 really strange... does it mean the same code called from FormEntryActivity work perfectly but it doesn't if it's placed in the URLWidget ?

**Comment by shobhitagarwal1612** [comment]
> @shobhitagarwal1612 really strange... does it mean the same code called from FormEntryActivity work perfectly but it doesn't if it's placed in the URLWidget ?

@grzesiek2010 Yes. 

While I was looking out for the reason for the leaked service error, I got to know that some prefer to solve it by using `Weak References` as a last resort. Maybe you know something more about it and know how/when to use it.

**Comment by grzesiek2010** [comment]
weird... I'll try to investigate it deeper.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 here is a solution https://github.com/grzesiek2010/collect/commit/74a79127d80f70d0d3a5f19a0f57254aa3bb8dfc

It's almost the same as I added above. As I understand the problem was that a widget constructor is called two times (don't know why I didn't investigate it much). 
So You can debugg it:
1. Click on the "Open Url" button
2. Go back to the widget
3. [this](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java#L97) is called two times

or just change your device orientation... never mind, now [bindCustomTabsService](https://github.com/grzesiek2010/collect/commit/74a79127d80f70d0d3a5f19a0f57254aa3bb8dfc#diff-a5c152dc7425469015c19b7a29b8da07R66) is called when you click on the button (only once).

**Comment by shobhitagarwal1612** [comment]
Thanks, @grzesiek2010! I have to leave for now but will surely look at this soon.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 I have made the changes as proposed by you and it's working fine. Thank you for the great solution.
@lognaturel Please review

File: collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java [hunk 1]
```diff
@@ -69,32 +68,23 @@ public void onStart() {
     }
 
     @Override
+    public void onDestroy() {
+        getActivity().unbindService(websiteTabHelper.getServiceConnection());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java]: There is a chance that `getActivity()` returns `null`, we should null check here.

File: collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java [hunk 2]
```diff
@@ -94,19 +90,11 @@ public void onClick(View v) {
...
-            customTabsIntent.intent.setPackage(customTabHelper.getPackageName(getContext()).get(0));
-            customTabsIntent.launchUrl(getContext(), uri);
-        } else {
-            Intent intent = new Intent(Intent.ACTION_VIEW);
-            intent.setData(uri);
-            getContext().startActivity(intent);
-        }
+    private boolean isUrlEmpty(TextView stringAnswer) {
+        return stringAnswer == null || stringAnswer.getText() == null
+                || "".equals(stringAnswer.getText().toString());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: Any particular reason for the backwards comparison here?

File: collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java [hunk 3]
```diff
@@ -69,32 +68,23 @@ public void onStart() {
...
-                if (websiteTabHelper.getPackageName(getActivity()).size() != 0) {
-                    CustomTabsIntent customTabsIntent =
-                            new CustomTabsIntent.Builder()
-                                    .build();
-                    customTabsIntent.intent.setPackage(websiteTabHelper.getPackageName(getActivity()).get(0));
-                    customTabsIntent.launchUrl(getActivity(), websiteUri);
-                } else {
-                    startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(ODK_WEBSITE)));
-                }
+                websiteTabHelper.openUri(getActivity(), websiteUri);
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java:85]: Great job cleaning this up, this is much nicer.

File: collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java [hunk 4]
```diff
@@ -44,13 +41,13 @@
...
-    private CustomTabHelper customTabHelper;
-    private Uri uri;
 
+    private Uri uri;
     private Button openUrlButton;
     private TextView stringAnswer;
+    private CustomTabHelper customTabHelper;
 
-    public UrlWidget(Context context, FormEntryPrompt prompt) {
+    public UrlWidget(final Context context, FormEntryPrompt prompt) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: Any reason why this is final?

**Review by heyjamesknight — APPROVED** [review]
Looks great @shobhitagarwal1612! Added some minor comments. Only one that matters is the getActivity null check.

File: collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: I would also prefer this to be `stringAnswer.getText().toString().equals("")`. http://blue-walrus.com/2010/11/reverse-equals-in-java-a-dangerous-technique/

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: I think `stringAnswer.getText().isEmpty()` can also be used

File: collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java (hunk 4 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: No reason. This can be safely removed.

File: collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java (hunk 3 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java:85]: 😄

File: collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: I'm not sure that method exists but maybe [TextUtils.isEmpty](https://developer.android.com/reference/android/text/TextUtils.html#isEmpty%28java.lang.CharSequence%29)?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java]: https://developer.android.com/reference/java/lang/String.html#isEmpty()

**Review by lognaturel — APPROVED** [review]
