### PR TITLE
Catch null formPath

### LINKED ISSUE #3019: NullPointerException in FormEntryModel.java:448
#### Software and hardware versions 
Collect v1.21.1 and older versions

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b0d80d16007d59fcd4e8285?time=last-seven-days&sessionId=5CB06F0D024D00016E62D903AC2F64F9_DNE_1_v2

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.javarosa.core.model.FormIndex.isInForm()' on a null object reference
       at org.javarosa.form.api.FormEntryModel.createModelIfNecessary(FormEntryModel.java:448)
       at org.javarosa.form.api.FormEntryModel.setQuestionIndex(FormEntryModel.java:288)
       at org.javarosa.form.api.FormEntryController.jumpToIndex(FormEntryController.java:226)
       at org.odk.collect.android.logic.FormController.jumpToIndex(FormController.java:842)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:209)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:70)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:780)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3019 

#### What has been done to verify that this works as intended?
I hardcoded null value to check what happens - a form is just closed in a safe way.

#### Why is this the best possible solution? Were any other approaches considered?
The crash takes place if `formPath` is null so I just added a null check. If that happens the form is closed. It's a rare crash up to 10 appearances per each version and has something to do with reloading forms so it's very difficult to reproduce. Closing the form and letting a user open it again seems fine.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's just a null check no other changes so I think testing is not required, just code review.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java [hunk 1]
```diff
@@ -121,6 +121,11 @@ protected FECWrapper doInBackground(String... path) {
         errorMsg = null;
 
         final String formPath = path[0];
+        if (formPath == null) {
+            Timber.e("formPath is null");
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:125]: @grzesiek2010 Do you think it would be useful to set the value of `errorMsg` to `formPath is null` as well. Because if not provided, then the message would appear to be `Sorry, unable to parse form.`

As you said that it occurs rarely so I am assuming that this is a recoverable exception. If we keep the message different, maybe someone in the future would attempt to fix it rather than just leaving it as is.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:125]: Sounds like a good plan to me. You could even consider something like "formPath is null, please post on the forum with a description of what you were doing when this happened." Note that errorMsg values are deliberately not translated since they aren't expected to show up often.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:125]: Thanks, done!

**Review by lognaturel — APPROVED** [review]
