### PR TITLE
Catch QueryException in PullDataFunctionHandler

### LINKED ISSUE #6796: Error on opening form when pulldata uses non existing property
#### ODK Collect version
master version 8d69e34793d67764c353c4e19da0505172149c57, store version 2025.2.0
#### Android version
10, 15 
#### Device used
Redmi 7 Pixel 6a
#### Problem description
Error on opening form with pulldata using non existing property
#### Steps to reproduce the problem
1. Go to https://test.getodk.cloud/projects/591/app-users
2. Scan user "sp"
3. In collect open entity pulldata form

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6796 

#### Why is this the best possible solution? Were any other approaches considered?
If we try to use a non-existent property, an error is thrown, which we should catch similarly to how it works for a non-entities dataset:
https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/dynamicpreload/handler/ExternalDataHandlerPull.java#L108

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change is safe, so we can focus on testing the scenario described in the issue. Nothing else should be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
The one from the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt [hunk 1]
```diff
@@ -101,4 +101,44 @@ class PullDataFunctionHandlerTest {
...
+                        mainInstance(
+                            t(
+                                "data id=\"pull-data-form\"",
+                                t("question"),
+                                t("calculate")
+                            )
+                        ),
+                        bind("/data/question").type("string"),
+                        bind("/data/calculate").type("string")
+                            .calculate("pulldata('things', 'label', 'property', 'value')")
```
Comment (seadowg) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: I think we need to have different behaviour for the case where you do 

```
pulldata('things', 'label', 'property', '')
```

That should just return the first item in the data set right? In that case you'd effectively be doing `label = ''` which would be true for every item if `label` doesn't exist.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: That's not how `pulldata` behaved in the past (before entities), so why would we need to change it now?

Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: Is it not? I couldn't find docs on it. If I had a normal choice filter with `label = ''` in this scenario (where `label` doesn't exist), I'd get back the whole data set so it seems like for `pulldata` should just return the first item (as it looks like it does with other multiple match scenarios).

Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: Let me check again

Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: Yes, I can confirm It used to return nothing, so the behavior is consistent.

Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandlerTest.kt:128]: Interesting! Could you add a test for that just so it's locked in/documented?

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6804#discussion_r2200405138

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6796 doesn't occur
- non-existing property when the db table is created locally (empty dataset + locally created entity) 
- finalizing/ sending a form with non-existing property

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15

**Comment by srujner** [comment]
**Tested with success**

Verified on device with Android 14
