### PR TITLE
Fixed scrolling to the edited question in a list of questions

### LINKED ISSUE #5963: Text field in field list snaps under keyboard when tapped to focus
#### ODK Collect version
[92ad4fc](https://github.com/getodk/collect/commit/92ad4fc400795d11857d819ef650d6890f5cdb4a)

#### Android version
13

#### Device used
Samsung Galaxy

#### Problem description
| now | before             |
|----------|-------------------------------------------------------------------------------------------------------------------|
|  https://github.com/getodk/collect/assets/967540/3bec34d8-5664-4f34-983d-9f5452417ead | https://github.com/getodk/collect/assets/967540/7aebf4a4-3faf-46c1-850e-14382dc1dc0f |

#### Steps to reproduce the problem

Load the [WHO VA](https://github.com/SwissTPH/WHO-VA) form. In the first screen, tap to set the interviewer ID.

#### Expected behavior
Question that's getting focus snaps above keyboard, not below.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5963 

#### Why is this the best possible solution? Were any other approaches considered?
As discussed in the issue the problem was that in order to perform scrolling to the edited question in a field list we used `OnLayoutChangeListener`. This listener is called not only if we really update the list of questions but also for example when the keyboard is shown/hidden.
Initially, I thought that I could just remove that listener and perform scrolling immediately after updating the list of questions but it seems like it would be too early after updating the view (it's the same issue we have in other parts of the app https://github.com/getodk/collect/issues/5853) so I needed to the use `post` method.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue but... it's a type of change that might work in a different way on different devices so please test this pr on all the devices you have.
It's also important to test cases with multiple questions on one screen to make sure everything is fine when questions appear/disappear when they depend on each other and that scrolling to questions with new answers or errors works well etc.
And also be careful and observant because other weird cases like this one can also occur somewhere.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue. 

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java [hunk 1]
```diff
@@ -391,6 +391,18 @@ public void searchMinimalInFieldList() {
                 .assertSelectMinimalDialogAnswer("Strawberries");
     }
 
+    @Test
+    public void listOfQuestionsShouldNotBeScrolledToTheLastEditedQuestionAfterUpdatingTheLayout() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java]: I'm not sure about the name here - it kind of describes what's happening "under the hood" rather than the behaviour. Could it be `listOfQuestionsShouldNotBeScrolledToTheLastEditedQuestionAfterClickingOnAQuestion`?

File: test-forms/src/main/resources/forms/fieldlist-updates.xml [hunk 2]
```diff
@@ -160,6 +160,17 @@
             <source15/>
             <target15/>
           </search_in_field_list_group>
+          <long_list_of_questions>
```
Comment (seadowg) [inline test-forms/src/main/resources/forms/fieldlist-updates.xml:163]: This test relies on the not all questions being able to fit on screen right? I think if that's the case we should make this list absurdly long to prevent false positives on bigger devices. Maybe 100 questions? I think we should also add a comment that the list is designed to be longer than the screen so that's clear.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Comment by dbemke** [comment]
I'm not sure what is the expected result after changes. If there are many question in a field-list should the cursor stay at the last question filled (the screen shouldn't move to a different question)? e.g. I fill All widgets field-list and when I get to draw widget and save changes in the widget I'm moved to Decimal widget which is the last question with a field to enter values with a keyboard.

**Comment by dbemke** [comment]
Is this case the expected result?

https://github.com/getodk/collect/assets/56479916/d513aee9-9d78-4929-9125-53919e4f90c0

**Comment by grzesiek2010** [comment]
This is not perfect because if you move to a non-text question and answer it, we should not only hide the keyboard but also remove focus from that last. However, I think it always worked like that. If I' right and it's not regression we can skip it for now.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java]: Yeah it can be `listOfQuestionsShouldNotBeScrolledToTheLastEditedQuestionAfterClickingOnAQuestion`, done.

File: test-forms/src/main/resources/forms/fieldlist-updates.xml (hunk 2 above)
Comment (grzesiek2010) [reply test-forms/src/main/resources/forms/fieldlist-updates.xml:163]: > This test relies on the not all questions being able to fit on screen right?

Right.

I've just made the list longer (20 questions). I don't think we need more especially now as every question takes more space vertically compared to v2023.3.1.

**Comment by srujner** [comment]
Tested with success

Verified on devices with Android 12,13,14

Verified cases:
- Issue #5963 is no longer reproducing;
- Regression check on forms with Fieldlists;
- Different widgets in forms with Fieldlist;
- Single/Multiple questions on one screen;
- Minimize the app, rotate the screen;
- Other found issues will be filled separately

**Comment by dbemke** [comment]
**Tested with success**

Verified on: Nexus 5x Android 8.1, Redmi 9T Android 10, Samsung Galaxy M12 Android 11, Pixel 7a Android 14

**Review by seadowg — APPROVED** [review]
