### PR TITLE
Catch NullPointerException in QRCodeUtils.getBinaryBitmap(QRCodeUtils.java:78)

### LINKED ISSUE #3015: NullPointerException in QRCodeUtils.getBinaryBitmap(QRCodeUtils.java:78)
#### Software and hardware versions 
Collect v1.21.1 and older versions

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5beda62bf8b88c29631095e3?time=last-seven-days&sessionId=5CADA569027800015BB532B734DFBA7D_DNE_0_v2

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at org.odk.collect.android.utilities.QRCodeUtils.getBinaryBitmap(QRCodeUtils.java:78)
       at org.odk.collect.android.utilities.QRCodeUtils.decodeFromBitmap(QRCodeUtils.java:72)
       at org.odk.collect.android.fragments.ShowQRCodeFragment.onActivityResult(ShowQRCodeFragment.java:243)
       at android.app.Activity.dispatchActivityResult(Activity.java:7426)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4463)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4511)
       at android.app.ActivityThread.-wrap21(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6792)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3015 

#### What has been done to verify that this works as intended?
Nothing just reviewed implemented changes since it's pretty simple but the problem really difficult to reproduce.

#### Why is this the best possible solution? Were any other approaches considered?
Just added null check to avoid crashing. The problem is not our fault so it's the only thing we can do.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I just added null checks so I don't think it requires testing. Code review should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by shobhitagarwal1612 — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java [hunk 1]
```diff
@@ -236,17 +236,25 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
...
-                    final Bitmap bitmap = BitmapFactory.decodeStream(imageStream);
-                    String response = QRCodeUtils.decodeFromBitmap(bitmap);
-                    if (response != null) {
-                        applySettings(response);
+                    if (imageUri != null) {
+                        final InputStream imageStream = getActivity().getContentResolver()
+                                .openInputStream(imageUri);
+
+                        final Bitmap bitmap = BitmapFactory.decodeStream(imageStream);
+                        if (bitmap != null) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java:245]: We should also display a toast message if this condition is not met (in `else` block for this `if`) to notify the user that they need to select the QRCode again

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java:245]: Fixed.

**Comment by mmarciniak90** [comment]
**Tested with success**

I was not able to reproduce the crash. 
I checked that manually added translation to `qr_code_not_found` text is correctly displayed.
I did not notice regression.

Verified on Andriod: 4.2, 4.4, 6.0, 7.0, 8.1

@grzesiek2010 let me know if I can do something more to verify this issue.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
