### PR TITLE
Google drive dynamic search bar

### LINKED ISSUE #1944: The dynamic search bar should be available on `Get Blank Form` view for Google Drive
#### Software and hardware versions 
Collect v1.13 and earlier

#### Problem description
The search bar on Google Drive should be similar to search bar when user uses Aggregate.
The dynamic search bar should be available to Google Drive because it is more user friendly.
Searching when user clicks the magnifying glass icon causes a lot of issues.

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User tries to search a form, he adds text
4. User need to click on magnifying glass icon to search
5. When user removes a part of added text, search bar shows empty view
6. When user removes a whole text, he need to click magnifying glass icon -> confusing toast appears and all forms are visible

#### Expected behavior
* Search bar should work in the same way as search bar for Aggregate server.
* Searching is performed when user adds or removes a letter. 
* It is not necessary to click on search icon

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Closes #1944 

#### What has been done to verify that this works as intended?
Tested on physical device Android 7.1
#### Why is this the best possible solution? Were any other approaches considered?
Search works in the same way when we use Aggregate Server. And search field is removed from the layout file so that the UI of both GoogleDrive and Aggregate looks similar.
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No

ezgif com-video-to-gif

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Did you consider extending `AppListActivity` and reusing the code from there?

**Comment by lakshyagupta21** [comment]
> Did you consider extending AppListActivity and reusing the code from there?

I tried extending it but in that case, we need to change adapter implementation. Because both use different adapter implementation. What do you say will it be good if we change adapter implemenation?

**Comment by shobhitagarwal1612** [comment]
> if we change adapter implemenation?

Yes, let's try that

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 I've modified the adapter, both sort and search works.


ezgif com-video-to-gif

**Comment by shobhitagarwal1612** [comment]
@lakshyagupta21 I just did a quick review and noticed that there is no progress bar to show loading status when the data is being loaded from API. But other than that, everything looks great! I will do a more thorough review soon

**Comment by lakshyagupta21** [comment]
> no progress bar to show loading status

Were you able to see it before?  Because I am not able to see on Android 7.1

**Comment by shobhitagarwal1612** [comment]
I totally forgot that there was no progress bar in this activity. I opened the activity and because of the slow internet, the files took some time to load. But it would be really helpful for users if there was a loading progress indicator. Since you are already in that code, can you please add that as well?

In this [PR#1769](https://github.com/opendatakit/collect/pull/1769), I have added a progress bar in the toolbar to show loading status for each of the activity except the `GoogleDriveActivity`.

**Comment by lognaturel** [comment]
> But it would be really helpful for users if there was a loading progress indicator. Since you are already in that code, can you please add that as well?

That sounds fine but please file a separate issue and do it in another PR! Let's get this targeted improvement reviewed and merged first. 😊

**Comment by shobhitagarwal1612** [comment]
Device used: Redmi Note 4 (Android 7.0)

I noticed one change from the master branch. The folders and xml forms are not grouped together by type.
image

**Comment by lakshyagupta21** [comment]
> The folders and xml forms are not grouped together by type

This is because of sort. I've applied sorting on names of folders and filenames.

Previously it was adding folders first and then forms.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 1]
```diff
@@ -352,6 +287,63 @@ private void getFiles() {
...
+        listView.clearChoices();
+        for (int i = 0; i < listView.getCount(); i++) {
+            DriveListItem item = (DriveListItem) listView.getAdapter().getItem(i);
+            if (toDownload.contains(item)) {
+                listView.setItemChecked(i, true);
+            }
+        }
+    }
+
+    private void sortList() {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:328]: After sorting the items according to name, you can try adding the sort by type to group the folders and XML forms together.

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 2]
```diff
@@ -352,6 +287,68 @@ private void getFiles() {
...
+        Collections.sort(filteredList, new Comparator<DriveListItem>() {
+            @Override
+            public int compare(DriveListItem lhs, DriveListItem rhs) {
+                if (lhs.getType() != rhs.getType()) {
+                    if (lhs.getType() == DriveListItem.DIR) {
+                        return -1;
+                    } else {
+                        return 1;
+                    }
+                } else if (getSortingOrder().equals(SORT_BY_NAME_ASC)) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]:
```
if (lhs.getType() == DriveListItem.DIR) {
                        return -1;
                    } else {
                        return 1;
                    }
```

Above 5 lines can be written in a single line
`return lhs.getType() == DriveListItem.DIR ? -1 : 1;`

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Or maybe something like this:

```
if (lhs.getType() != rhs.getType()) {
                    return lhs.getType() == DriveListItem.DIR ? -1 : 1;
                } else {
                    int compareName = lhs.getName().compareToIgnoreCase(rhs.getName());
                    return getSortingOrder().equals(SORT_BY_NAME_ASC) ? compareName : -compareName;
                }
```

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 3]
```diff
@@ -31,57 +31,47 @@
...
-import java.util.Collections;
-import java.util.Comparator;
 import java.util.Date;
 import java.util.List;
 import java.util.Locale;
 
-public class FileArrayAdapter extends RecyclerView.Adapter<FileArrayAdapter.ViewHolder> {
+import io.reactivex.annotations.NonNull;
+
+public class FileArrayAdapter extends ArrayAdapter {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Please add the generic type: 
`public class FileArrayAdapter extends ArrayAdapter<DriveListItem>`

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 4]
```diff
@@ -31,57 +31,47 @@
...
 
 import java.text.SimpleDateFormat;
-import java.util.Collections;
-import java.util.Comparator;
 import java.util.Date;
 import java.util.List;
 import java.util.Locale;
 
-public class FileArrayAdapter extends RecyclerView.Adapter<FileArrayAdapter.ViewHolder> {
+import io.reactivex.annotations.NonNull;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: @NonNull should be imported from `import android.support.annotation.NonNull;`

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 5]
```diff
@@ -31,57 +31,47 @@
...
-    @Override
-    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
-        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.two_item_image, parent, false);
-        return new ViewHolder(v);
-    }
-
-    @Override
-    public void onBindViewHolder(ViewHolder holder, int position) {
-        holder.bind(items.get(position), listener);
+    public View getView(int position, View convertView, @NonNull ViewGroup parent) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Please annotate the method as `@NonNull` as the overridden method is annotated as `@NonNull`

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 6]
```diff
@@ -31,57 +31,47 @@
...
-    @Override
-    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
-        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.two_item_image, parent, false);
-        return new ViewHolder(v);
-    }
-
-    @Override
-    public void onBindViewHolder(ViewHolder holder, int position) {
-        holder.bind(items.get(position), listener);
+    public @NonNull View getView(int position, View convertView, @NonNull ViewGroup parent) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: `getView` method's responsibility should be only to return the view for the current position. Hence, all the logic related to binding view with data should be held within the view holder class. It is not a rule but a good practice. Something similar to this :

```
@NonNull
    public View getView(int position, View convertView, @NonNull ViewGroup parent) {
        final ViewHolder holder;
        if (convertView == null) {
            View view = LayoutInflater.from(getContext()).inflate(R.layout.two_item_image, parent, false);
            holder = new ViewHolder(view);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        holder.onBind(items.get(position));
        return holder.itemView;
    }
```

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Then binding of the views can be done in the constructor of the ViewHolder and all the logic related to updating the UI of the view for the current item can be done using `onBind` or some other method rather than exposing the variables

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]:
```
void onBind(DriveListItem item) {
            setName(item.getName());
            setImage(item.getType());
            setModifiedTime(item.getDate());
            setCheckbox(item);
        }
```

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: The advantage is that, if the listview is replaced by recycler view then the same ViewHolder can be reused as it just a normal java class

Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]:
``` 
private class ViewHolder {
        ImageView imageView;
        TextView text1;
        TextView text2;
        CheckBox checkBox;

        ViewHolder (View view) {
            imageView = view.findViewById(R.id.image);
            text1 = view.findViewById(R.id.text1);
            text2 = view.findViewById(R.id.text2);
            checkBox = view.findViewById(R.id.checkbox);
        }

        void onBind (DriveListItem item) {
            String dateModified = null;
            if (item.getDate() != null) {
                dateModified = new SimpleDateFormat(context.getString(
                        R.string.modified_on_date_at_time), Locale.getDefault())
                        .format(new Date(item.getDate().getValue()));
            }
            // updating the UI elements
       }
}
```
@shobhitagarwal1612 What do you say about this?  Is it required to check whether DriveListItem is null or not?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: No, it's not

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 7]
```diff
@@ -54,59 +54,61 @@ public FileArrayAdapter(Context context, List<DriveListItem> filteredDriveList)
...
                 Drawable d = ContextCompat.getDrawable(context, R.drawable.ic_folder);
-                holder.imageView.setImageDrawable(d);
-                holder.checkBox.setVisibility(View.GONE);
+                imageView.setImageDrawable(d);
+                checkBox.setVisibility(View.GONE);
             }
 
-            if (holder.text1 != null) {
-                holder.text1.setText(o.getName());
+            if (text1 != null) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: This null check is also not required as `text1` can't be null since it's a reference to the textview

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 8]
```diff
@@ -54,59 +54,61 @@ public FileArrayAdapter(Context context, List<DriveListItem> filteredDriveList)
...
+                text1.setText(item.getName());
             }
-            if (holder.text2 != null) {
-                holder.text2.setText(dateModified);
+            if (text2 != null) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Same as above, this null check is not required

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 9]
```diff
@@ -54,59 +54,61 @@ public FileArrayAdapter(Context context, List<DriveListItem> filteredDriveList)
...
+                text2.setText(dateModified);
             }
 
             //in some cases, it will prevent unwanted situations
-            holder.checkBox.setOnCheckedChangeListener(null);
+            checkBox.setOnCheckedChangeListener(null);
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: The comment says that it will prevent unwanted situations but I don't see any use of adding this.
I tried removing it and everything worked fine as it should. What do you think?

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 10]
```diff
@@ -54,59 +54,61 @@ public FileArrayAdapter(Context context, List<DriveListItem> filteredDriveList)
...
             //if true, your checkbox will be selected, else unselected
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Please remove this comment as the functionality of `setChecked` method is clear

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java (hunk 9 above)
Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: I didn't change much in the previous adapter implementation. Even I'm not sure why this stmt is added. 
Will remove it.

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 11]
```diff
@@ -31,113 +31,84 @@
...
-    public interface OnItemClickListener {
-        void onItemClick(View v, DriveListItem item);
-    }
-
-    private final OnItemClickListener listener;
 
-    public FileArrayAdapter(Context context, List<DriveListItem> objects, OnItemClickListener listener) {
+    public FileArrayAdapter(Context context, List<DriveListItem> filteredDriveList) {
+        super(context, R.layout.two_item_image, filteredDriveList);
         this.context = context;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: This global variable `context` can be removed and `getContext()` can be used in its place wherever required

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java (hunk 9 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: :+1:

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot needs testing

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

This PR  does not cause that `Get Blank Form` for Google Drive will look and work the same as for Aggregate. This PR focuses on search bar.

**Verified on Android**: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

**Verified cases**:
* searching on My Drive
* searching on Shared with Me
* sorting by name A-Z / Z-A
* add/remove letters in search bar
* clear search bar
* close search bar

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by shobhitagarwal1612** [comment]
Thank you @lakshyagupta21 for working on this :tada: :tada:
