### PR TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference

### LINKED ISSUE #1737: Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
#### Software and hardware versions 
Collect v1.12.0

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/7e0343c8?reportTypes=REPORT_TYPE_UNSPECIFIED&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/1b4f7f56?reportTypes=REPORT_TYPE_UNSPECIFIED&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/9c7d60d2?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/f8bc9527?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

#### Steps to reproduce the problem
1. Download a form with media files like `All Widgets` form
2. Remove media folder manually
3. Open the list of available forms

#### Expected behavior
You can see the list and you can see that a newer version of `All Widgets` form is available

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1737 

#### What has been done to verify that this works as intended?
I tested the case mentioned in #1737 

#### Why is this the best possible solution? Were any other approaches considered?
I just made the solution simple and solved the bug.

#### Are there any risks to merging this code? If so, what are they?
Now the solution is simpler we just get list of file and check for null https://github.com/opendatakit/collect/compare/master...grzesiek2010:COLLECT-1737?expand=1#diff-10d77d66d8d1d9f9edc5c6e5c1706489R410

The problem before was that I tried to add that null to a collection https://github.com/opendatakit/collect/compare/master...grzesiek2010:COLLECT-1737?expand=1#diff-7f825a8c77110cae6eb54336627d425fL505

So in y opinion now this part of code is really safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media files.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java [hunk 1]
```diff
@@ -405,24 +405,22 @@ private boolean isNewerFormVersionAvailable(String md5Hash) {
     }
 
     private boolean areNewerMediaFilesAvailable(String formId, String formVersion, List<MediaFile> newMediaFiles) {
-        if (newMediaFiles != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:408]: I just removed a double null check since we check it here https://github.com/opendatakit/collect/pull/1738/files#diff-10d77d66d8d1d9f9edc5c6e5c1706489R236

**Comment by grzesiek2010** [comment]
@lognaturel 

unfortunately, we need to release v1.12.1

Apart from the bug, the problem is we can't see reports from beta versions in Firebase. It was also not visible on GPC. I could have fixed such a bug before.

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Verified cases:
* folder with media is removed
* .xls/.png/.3gp/.mp3 fle is removed

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:408]: I would have tended to keep the null-check in the method. This requires all method clients to remember it or to suffer a crash. A `@NotNull` annotation could help.
