### PR TITLE
Fix handling of numbers in SQLite query arguments

### LINKED ISSUE #6617: Crash during filling filter choice expressions form
**ODK Collect version**
master version: 572b3269cd3dfcbefeca6d766c7bce34f0b2ff9a 

**Android version**
10, 12, 15

**Device used**
Alcatel 1B, Google Pixel 3a, Google Pixel 6a

**Problem description**
Caught during testing: https://github.com/getodk/collect/pull/6601
I found a crash in the app during regression check on filter expressions. 
It's not reproducing on store version (2024.3.6) so it might be a regression. 
The strange thing is that during regression testing we checked this case but with form without super nested example in filters. 

Even stranger, I copied these forms and pasted them into another project on central and the crash did not occur so it looks like it is something with that project? 
Let me know if you need more info

https://github.com/user-attachments/assets/78a59fd6-db2b-41c8-b5f1-c54b03d16db8

**Steps to Reproduce:**

1. Scan the QR code: https://test.getodk.cloud/#/projects/590/app-users
2. Open People form and navigate to hierarchy view or try to save the form -> crash in tooltip
3. Click next until the "Female from France younger than 30" question -> Crash in the app
4. Open People update super nested form -> Form won't open, soft crash

**Expected behavior:**
- The app does not crash

**Other information**

[people.xlsx](https://github.com/user-attachments/files/18887585/people.xlsx)

[people update super nested(1).xlsx](https://github.com/user-attachments/files/18887615/people.update.super.nested.1.xlsx)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6617 

#### Why is this the best possible solution? Were any other approaches considered?
When filters include numeric values like `age=25`, JavaRosa represents the number as a Double (`25.0`). However, SQLite requires arguments to be strings. To ensure correct comparisons in the database, we need to check if the Double value has a `.0` fractional part. If it does, we should first convert it to an Int and then to a String, resulting in `25` instead of `25.0`. This prevents issues caused by the redundant decimal part during value comparisons.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test filters with numbers like `age=25`. The form that is attached to the issue contains such a filter and that was the cause of the crash.

#### Do we need any specific form for testing your changes? If so, please attach one.
The from that is attached to the issue can be used.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt [hunk 1]
```diff
@@ -87,7 +87,13 @@ class LocalEntitiesFilterStrategy(entitiesRepository: EntitiesRepository) :
 
         return if (candidate != null) {
             val child = candidate.nodeSide.steps[0].name.name
-            val value = candidate.evalContextSide(sourceInstance, evaluationContext) as String
+            var value = candidate.evalContextSide(sourceInstance, evaluationContext)
```
Comment (lognaturel) [inline entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: Where does the type of `value` come from? Could it also be any other type like maybe a date type or boolean?

Comment (grzesiek2010) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: In the filter it is just a number like `age=25` but JR keeps numbers as doubles so it is `25.0`. Before converting it to string we need to get rid of that `.0` which I described above.

Comment (grzesiek2010) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: > Could it also be any other type like maybe

Yes I was thinking about dates as well. I'm going to check that.

Comment (lognaturel) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: Great, thanks. My recollection is that this was addressed for the simple expression case. I would have expected the same tests related to that to catch this. Is there branching between the simple expression and complex expression (with and/or) case? Am I remembering incorrectly about those tests?

Comment (seadowg) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: > My recollection is that this was addressed for the simple expression case. I would have expected the same tests related to that to catch this. Is there branching between the simple expression and complex expression (with and/or) case? Am I remembering incorrectly about those tests?

It's not clear to me what you're referring to here @lognaturel. What's the simple expression case?

File: entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt [hunk 2]
```diff
@@ -87,7 +87,13 @@ class LocalEntitiesFilterStrategy(entitiesRepository: EntitiesRepository) :
...
+
+            value = if (value is Double && value % 1 == 0.0) {
+                value.toInt().toString()
```
Comment (seadowg) [inline entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: I don't believe this would work correctly if the expression was `age = 25.0` and the value of age was `"25.0"`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt [hunk 3]
```diff
@@ -9,8 +9,20 @@ data class SqlQuery(
 
 fun Query.toSql(): SqlQuery {
     return when (this) {
-        is Query.Eq -> SqlQuery("$column = ?", arrayOf(value))
-        is Query.NotEq -> SqlQuery("$column != ?", arrayOf(value))
+        is Query.Eq -> {
+            if (value.toDoubleOrNull() != null) {
```
Comment (seadowg) [inline db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt]: The general approach here is that if we have a "numeric" (a String that looks like an Int or a Double) value for the query, we convert both to double so we end up with essentially `Double = Double` right? 

One thing that feels off to me is that we'll explicitly have the type (an Int or a Double) in `LocalEntitiyFilterStrategy` and then we're "erasing" it by converting to a String and then reconverting based on a heuristic. Instead could we add `DoubleEq` and `DoubleNotEq` types to `Query` (I guess the existing ones would be `StringEq`)? Then we'd just lift `Int` to Double when creating a `Query` and `toSql` wouldn't have to make any guesses.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt (hunk 3 above)
Comment (seadowg) [reply db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt]: The test case to write to drive out the above I'm realizing is a filter expression like `id = '1234'`. This implementation would match an `id` value of `'1234.0'` (as both get converted to doubles) whereas only the exact string `'1234'` should match.

File: entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt (hunk 1 above)
Comment (lognaturel) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: I distinctly remember a conversation you and I had about doubles when you were first writing support for expressions without and/or. I thought this class of problems was addressed there but I see that the form crashes in v2024.3.x too so maybe not?

Comment (seadowg) [reply entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt]: > I distinctly remember a conversation you and I had about doubles when you were first writing support for expressions without and/or. I thought this class of problems was addressed there but I see that the form crashes in v2024.3.x too so maybe not?

Yeah, I don't remember considering it at this level sadly!

File: db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt (hunk 3 above)
Comment (grzesiek2010) [reply db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt]: Done.

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt [hunk 4]
```diff
@@ -367,6 +367,59 @@ class LocalEntitiesFilterStrategyTest {
...
+                            )
+                        ),
+                        t("instance id=\"things\" src=\"jr://file-csv/things.csv\""),
+                        bind("/data/question").type("string")
+                    )
+                ),
+                body(
+                    select1Dynamic(
+                        "/data/question",
+                        "instance('things')/root/item[age=25]",
```
Comment (seadowg) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:409]: I was a little concerned about only having one test here as my instinct was that we need to consider cases for both `Double` and `Int`. However, as far as I can see, JavaRosa **always** treats numbers as `Double` types for the purposes of evaluation:

1. `IntegerData` carries an `Int` around, but when a path expression is unpacked (using `#unpack`) for evaluation it gets converted to a `Double`
2. `XPathNumericLiteral` carries a `Double` around so integer literals never end up as `Int`

I was aware of 2, but 1 surprised me. Does this blanket statement around not needing to worry about `Int` seem true @lognaturel? If so, the nice thing is this single test is enough as all "numeric" data will have the same type.

File: db/src/test/java/org/odk/collect/db/sqlite/SqlQueryTest.kt [hunk 5]
```diff
@@ -8,24 +8,24 @@ import org.odk.collect.shared.Query
 class SqlQueryTest {
```
Comment (seadowg) [inline db/src/test/java/org/odk/collect/db/sqlite/SqlQueryTest.kt:8]: I'm thinking that this test should really be more of an "integration" one and check queries against a temp SQLite DB. That's a change we can follow up with.

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt [hunk 6]
```diff
@@ -879,6 +879,56 @@ abstract class EntitiesRepositoryTest {
         val repository = buildSubject()
         repository.save("wines", Entity.New("1", "Léoville Barton 2008",))
 
-        repository.query("wines", Query.Eq("score", "92"))
+        repository.query("wines", Query.StringEq("score", "92"))
+    }
+
+    @Test
+    fun `#query returns matching entities with numeric eq selection arguments`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt]: I'd like to split these 2 tests into 4 so we have individual ones for int and decimal property values.

**Review by seadowg — CHANGES_REQUESTED** [review]
Liking this! There's one point I'd like to discuss, but I think we're ok on (the assumption that everything is a `Double), and I think we should make one test tweak. This is definitely ready to hit QA though so I'll add "needs testing".

**Comment by seadowg** [comment]
Just as a note for testing: I think looking at filters that use numbers (both int and decimal) is obviously the first thing to check, but I think checking other "unusual" types like dates would be a good idea as well.

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt (hunk 4 above)
Comment (seadowg) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:409]: This doesn't confirm that the above is correct, but I also realized I could check Crashlytics to see if we've ever had a cash casting `Int` to `String` in `LocalEntitiesFilterStrategy` and it looks like we're clear there.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6617 doesn't occur
- integer filters on decimal and integer values
- decimal filters  on decimal and integer values

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 15

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt]: It won't work:
1. `Query.NumericEq` and `Query.NumericNotEq` take a double, so I always have to put a double there,e no matter if I want to test integers or doubles.
2. In properties, it's also worth to mix integers and doubles to make sure eg, the ones with `5` will be returned if I have `5.0` in the filter.

File: db/src/test/java/org/odk/collect/db/sqlite/SqlQueryTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply db/src/test/java/org/odk/collect/db/sqlite/SqlQueryTest.kt:8]: `EntitiesRepositoryTest` does that, and `SqlQueryTest` verifies only converting queries to sqlite.

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt (hunk 6 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt]: I was meant splitting for the property values themselves rather than the queries like:

```kotlin
@Test
fun `#query returns matching entities with numeric eq selection arguments for decimal values`() {
    val repository = buildSubject()

    val dows = Entity.New(
        "3",
        "Dow's 1983",
        properties = listOf("score" to "7.5")
    )

    repository.save("wines", dows)
    val wines = repository.query("wines", Query.NumericEq("score", 7.5))
    assertThat(wines, containsInAnyOrder(sameEntityAs(dows)))
}

@Test
fun `#query returns matching entities with numeric eq selection arguments for int values`() {
    val repository = buildSubject()

    val leoville = Entity.New(
        "1",
        "Léoville Barton 2008",
        properties = listOf("score" to "5")
    )

    repository.save("wines", leoville)

    val wines = repository.query("wines", Query.NumericEq("score", 5.0))
    assertThat(wines, containsInAnyOrder(sameEntityAs(leoville)))
}
```

Otherwise, one of the important parts here (that we match against both) is hidden in the test data which someone could easily change.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]
