### PR TITLE
Fix crash previously fixed in d14ed91. Fixes #2270

### LINKED ISSUE #998: Crash when accessing jump menu
Stack trace from Firebase Crash. Happens across API levels.

```
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.android.activities.FormHierarchyActivity}: java.lang.NullPointerException
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2436)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2498)
android.app.ActivityThread.access$900 (ActivityThread.java:179)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1324)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:146)
android.app.ActivityThread.main (ActivityThread.java:5641)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1288)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1104)
dalvik.system.NativeStart.main (NativeStart.java)

Caused by java.lang.NullPointerException:
org.odk.collect.android.activities.FormHierarchyActivity.onCreate (FormHierarchyActivity.java:74)
android.app.Activity.performCreate (Activity.java:5484)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1093)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2400)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2498)
android.app.ActivityThread.access$900 (ActivityThread.java:179)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1324)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:146)
android.app.ActivityThread.main (ActivityThread.java:5641)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1288)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1104)
dalvik.system.NativeStart.main (NativeStart.java)
```

### LINKED ISSUE #2270: stepToOuterScreenEvent() invoked on null reference
#### Software and hardware versions 
Collect v1.15, all Android versions

#### Problem description
Stack trace from Crashlytics ([link](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b0d4fa96007d59fcd4a967c?time=last-seven-days&sessionId=5B16CC710393000176FCE3336351F200_DNE_0_v2) requires credentials):

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int org.odk.collect.android.logic.FormController.stepToOuterScreenEvent()' on a null object reference
arrow_right
org.odk.collect.android.activities.ViewFormHierarchyActivity.onCreate (ViewFormHierarchyActivity.java:43)
android.app.Activity.performCreate (Activity.java:6675)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1119)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2732)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2844)
android.app.ActivityThread.-wrap12 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1572)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:203)
android.app.ActivityThread.main (ActivityThread.java:6361)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
```

#### Expected behavior
No crash.

#### Other information 
Marked as high priority because it has affected relatively many users.

### PR DESCRIPTION
**Pull request by bartekfi**
Closes #2270 

#### What has been done to verify that this works as intended?

I was not able to reproduce it. The only verification is the logical analysis of the code. I will test the solution once I understand the steps @grzesiek2010 performed to fix https://github.com/opendatakit/collect/issues/998

#### Why is this the best possible solution? Were any other approaches considered?

This is an unverified fix based on assumptions from changes made first in:
https://github.com/opendatakit/collect/issues/998 to fix an issue, 
and then in:
https://github.com/opendatakit/collect/pull/1038
that probably caused the issue to reemerge. 

The changes in #998 introduced a null check to make sure the `FormHierarchyActivity` is closed when FormController is null. 

#1038 created a subclass of `FormHierarchyActivity` -> `ViewFormHierarchyActivity`. This caused a reintroduction of the bug fixed in #998, as the subclass does not recheck for null in the onCreate() method.

When the same situation that caused crash fixed in #998 occurs in the ViewFormHierarchyActivity following steps will happen:

1. ViewFormHierarchyActivity will start with calling [super.onCreate()](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java#L38)
2. A null check in `super.onCreate()` parent class [FormHierarchyActivity::onCreate ](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java#L81) will call shortcut the `onCreate()` method by calling return, and call `finish()` on activity. 
3. `finish()` will be scheduled to close the activity asynchronously after the `onCreate()` is finished
4. `super.onCreate()` is done, the rest of the `onCreate()` method in ViewFormHierarchyActivity will be called. The shortcut only affected stopping `super.onCraete()`, the `onCreate()` is still called.
5. `Collect.getInstance().getFormController()` will still be null. It needs to be to be shortcut again. No need to call finish() this time, as it was already called in the `super.onCreate()`.

#### Are there any risks to merging this code? If so, what are they?

No changes to business logic. The activity silently finishes instead of throwing a Null Pointer Exception. 

#### Do we need any specific form for testing your changes? If so, please attach one.

The issue should be reproduced by the same steps as described in https://github.com/opendatakit/collect/issues/998

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.

### CODE REVIEW

**Comment by bartekfi** [comment]
@grzesiek2010 Can you describe the steps you took to fix issue #998 - I think the two cases the same bug but reintroduced.

**Comment by grzesiek2010** [comment]
It's not even the same bug in those two cases but in many different cases. I started an investigation here https://github.com/opendatakit/collect/issues/1533

When it comes to #998 I described steps I used to reproduce the problem.

> Got it! It takes place when we close the app (when the FormHierarchyActivity is opened) using a physical button and leave the app for a long time (in my case it's at least 30 minutes), then if we open the app again the app crashes.

Unfortunately, as I said the problem occurs under various different circumstances and only sometimes we are able to reproduce it, so the only solution, for now, is just checking if our `FormController` object is null.

File: collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java [hunk 1]
```diff
@@ -37,7 +38,11 @@
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
 
-        Collect.getInstance().getFormController().stepToOuterScreenEvent();
+        FormController formController = Collect.getInstance().getFormController();
+        if (formController == null) {
+            return;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java]: I don't think `return` is enough here, that means you just stop onCreate() method but the activity is still displayed, probably we should finish in such a case.

File: collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java [hunk 2]
```diff
@@ -37,7 +38,11 @@
...
+        }
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java]: please add `else` clause and log the issue, the same reason like here https://github.com/opendatakit/collect/pull/2277#issuecomment-395383314

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java (hunk 1 above)
Comment (bartekfi) [reply collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java]: I see how this is confusing. Finish is actually called in the super class based on the same condition. 

What I can do instead, is check here if the activity is actually finishing, by calling `isFinished()`. This will reduce code duplication and rely on the finishing condition.

File: collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java (hunk 2 above)
Comment (bartekfi) [reply collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java]: Makes sense. I'll add logging in the parent class, as this should be the single point of checking for this error. Thanks for pointing that out.

File: collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java]: Ohh I get it so `return` seems fine.

**Comment by bartekfi** [comment]
@grzesiek2010 I've updated the flow to look at the finish instead of FormController. I think this way we don't duplicate the same check, and expose the mechanism that caused this issue to reemerge - that is not respecting finish() called in parent class. I've also added logging.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you, @bartoszfilipowicz! I like your grim commit comment. 💀 Going to give @grzesiek2010 a chance to review.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
It looks good.
