### PR TITLE
Workaround paused recording Android bug

### LINKED ISSUE #4364: Stopping recording while paused causes a crash when using `voice-only` quality
#### Software and hardware versions 
Collect v1.29.4, Android < 10

#### Problem description

Hitting the stop button (⏹) while recording while paused causes the app to hang before being killed by the system. This is due to an underlying issue in Android (logged [here](https://issuetracker.google.com/issues/178630865)).

This also causes the mic to be blocked, forcing the user to restart the device if they want to retry the recording.

#### Steps to reproduce the problem

1. Open a form with an audio question (using `voice-only`) and navigate to it
2. Start recording
3. Pause recording
4. Stop recording

The app will freeze and then Android will offer to kill it.

#### Expected behavior

Stop should work when paused.

### PR DESCRIPTION
**Pull request by seadowg**
Hot fix for #4364

#### What has been done to verify that this works as intended?

Checked manually and wrote new tests.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only change here is to `voice-only` recordings, so we should focus any testing there. Good to check recording, pausing recordings etc on a few different devices if possible. We are now "resuming" recording before stopping for `voice-only` so it'd also be good to check that this doesn't introduce any artifacts into the recorded audio.

#### Do we need any specific form for testing your changes? If so, please attach one.

The `internal-audio-question.xml` form with a change to `voice-only` should do.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt [hunk 1]
```diff
@@ -22,13 +23,15 @@ internal abstract class MediaRecorderRecordingResource(private val mediaRecorder
     }
 
     override fun pause() {
-        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
+        @SuppressLint("NewApi")
```
Comment (seadowg) [inline audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt:26]: The IDE warns us about this otherwise (even though we are performing the check).

File: audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt [hunk 2]
```diff
@@ -66,4 +69,9 @@ internal class AMRRecordingResource(mediaRecorder: MediaRecorder) : MediaRecorde
         mediaRecorder.setAudioSamplingRate(8000)
         mediaRecorder.setAudioEncodingBitRate(12200)
     }
+
+    override fun stop() {
+        resume()
```
Comment (seadowg) [inline audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt:74]: As far as I can tell from docs and playing around calling `resume()` is safe (even when the recording isn't paused).

File: audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+    /**
+     * Calls to stop() while paused hang which appears to be a problem in the Android
+     * framework. Resuming and the stopping does work however.
+     *
+     * @see <a href="https://gist.github.com/seadowg/e6cbab21e032fe2fcd9afb9b4f458ab9">Gist</a> for
+     * test demonstrating the issue in Android.
+     */
+    @Test
+    fun whenPaused_stop_callsResumeThenStopOnMediaRecorder() {
```
Comment (grzesiek2010) [inline audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt]: Don't we need another test but for lower android api?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt (hunk 3 above)
Comment (seadowg) [reply audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt]: Do you mean for when `resume` isn't supported (below API 24)? I didn't need a test to drive out the change but I think you're right that it's important to check we don't call `MediaRecorder#resume` directly here - that would explode! I'll add the test.

Comment (grzesiek2010) [reply audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt]: Yes that's what I meant.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg I'm able to reproduce this issue only on Android 8.1. I can confirm that this fix works and crash doesn't longer occur.
During regression check, I noticed another crash related to `voice-only` quality - again, only Android 8.1.
App crashes when I click on stop and pause at the same time while recording. I'm going to create a separate issue for this.

Tested on Android versions: 8.1 (where the crash was repeatable), 7.0, 10.0

Verified cases:
- pause -> stop case
- voice-only quality
- normal quality
- low quality
- rotation
- click on notification -> pause -> stop
- stop recording before changing screen dialog:
   * swipe next/prev
   * click next/prev
   * new repeat group
   * jump screen
   * general settings
- blocking other audio widgets on the page
- light/dark mode

**Comment by kkrawczyk123** [comment]
Verified on Android 7.1 and 9.0 and also did a regression check on Android 5.1. 
@seadowg I have also seen the crash that @mmarciniak90 mentioned but only on Android 7.1 device but not in all my tries.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
