### PR TITLE
Fix Google Drive banner and server switching

### LINKED ISSUE #5499: Changing in settings the type of a server (from Aggregate to Google Drive), creates a project showing some parts of Aggregate and Google Drive
#### ODK Collect version
v2022.4.4, v2023.1 Beta 4
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
If a user changes in settings the type of a server (from Aggregate to Google Drive), the created project shows some parts of Aggregate and Google Drive.
agggd

#### Steps to reproduce the problem
1. Manually enter project details to add an Aggregate project (don’t add a username and a password)
2. Go to Settings→ Form Management→ Blank form update mode
3. Choose "match exactly”.
4. Go to Settings → Server.
5.  Change type to Google Drive
6. Add a google account.
7. Go back to the Main Menu.
8. Tap "Fill Blank Form”

Dialog asking for credentials to Aggregate appears.
#### Expected behavior
The server changes should be applied.

### LINKED ISSUE #5500: Prompt information about Google Drive does not disappear after changing the Server type to Aggregate
**ODK Collect version**
2023.1 Beta 4

**Android version**
10, 13

**Device used**
Redmi 9T, Pixel 6a

**Problem description**

After changing Server settings from Aggregate to Google Drive and then back to Aggregate, the Prompt information about Google Drive is still visible

**Steps to reproduce the problem**

- Manually enter project details to add an Aggregate project (don’t add a username and a password);
- Go to Settings→ Server→ Change server Type to Google Drive;
- Add Google Account;
- Go to the Home screen;
- Move back to the Settings→ Server→ Change server Type back to ODK and navigate to the home screen.
- Information about Google Drive will still be visible

**Expected behavior**
- Information about Google Drive should disappear after changing the Server Type to other then Google Drive

**Other Information:**
Screenshot_20230317-112116

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5499
Closes #5500

These issues ended up not being related, but I fixed them on one branch thinking they might be. To summarize the fixes:

* #5499: we needed to clear the state we keep track of for the "last sync" of a match exactly project when changing server/protocol so that we don't see sync errors in Fill Blank Form for the old settings
* #5500: we needed to hide the Google Drive deprecation prompt if Google Drive was no longer the protocol

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

As well as checking that the mentioned issues are fixed, I've refactored some code related to Exactly Match Server so that feature set is worth looking at.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/matchexactly/SyncStatusAppState.kt [hunk 1]
```diff
@@ -4,14 +4,10 @@ import android.content.Context
...
+import org.odk.collect.androidshared.data.AppState
 import org.odk.collect.forms.FormSourceException
-import javax.inject.Singleton
 
-@Singleton
-class SyncStatusAppState(private val context: Context) {
-
-    private val syncing = mutableMapOf<String, MutableLiveData<Boolean>>()
-    private val lastSyncFailure = mutableMapOf<String, MutableLiveData<FormSourceException?>>()
+class SyncStatusAppState(private val appState: AppState, private val context: Context) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/matchexactly/SyncStatusAppState.kt:10]: We've been replacing our usages of `@Singleton` with `AppState`, so I did that here seeing as I was touching the class.

Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/matchexactly/SyncStatusAppState.kt:10]: We've talked a few times about doing some more work to make classes like this, `InstancesAppState` and probably `FormsUpdater` into a more formal layer that sits between our `ViewModel` classes and our repos, http clients etc. I was very tempted to play around with that change here, but didn't want to add a potentially massive amount of refactoring. I'll maybe look at that as a follow-up now it's in my head.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**|

**Verified on device with Android 13**

**Verified Cases:**
- Issue #5499 is no longer reproducing;
- Issue #5500 is no longer reproducing;
- Regression check on the Match Exactly;
- Form version and media updates; 
- Match exactly and Failed match exactly;
- Adding project through QR code;
- Switching between projects, adding duplicated projects;
- Update settings from older version;
- Changing media files on Aggregate – uploading a new media file and a changed file

**Comment by dbemke** [comment]
**Tested with Success!|**

Verified on device with Android 10
