### PR TITLE
Checked for bad url in manually added forms and removed, and notified user

### LINKED ISSUE #709: Bad submission_url causes crash on submission
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
Form with bad submission url crashes Collect on submission.

```
AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
AndroidRuntime: Process: org.odk.collect.android, PID: 3533
AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Host name may not be null
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.util.Args.containsNoBlanks(Args.java:81)
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.HttpHost.<init>(HttpHost.java:80)
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.HttpHost.<init>(HttpHost.java:135)
AndroidRuntime: 	at org.odk.collect.android.utilities.WebUtils.enablePreemptiveBasicAuth(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.uploadOneSubmission(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.doInBackground(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.doInBackground(
AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AndroidRuntime: 	... 3 more
ActivityManager:   Force finishing activity es.InstanceUploaderActivity
ActivityManager:   Force finishing activity org.odk.collect.android/.activities.InstanceUploaderList
```

#### Steps to reproduce the problem
Create a form with a bad URL (e.g., `https:/server.com` instead of `https://server.com`). Fill out form and submit. To reproduce, try these forms:
* [bug.xlsx](https://github.com/opendatakit/collect/files/853365/bug.xlsx)
* [bug.xml.txt](https://github.com/opendatakit/collect/files/853366/bug.xml.txt)

If you'd like to make your own forms, for XLSForm (put a `submission_url` header with the value below in the `settings` sheet). For XForm, 
```
<model>
  <submission action="https:/server.com/submission" method="form-data-post"/>
  <instance>
```

#### Expected behavior
Users should be alerted as soon as possible when the submission URL is bad. 

#### Proposed fix
One potential fix is that `DiskSyncTask.java` should check the submission url and make sure it's valid. Validity should match to what we do when saving server preferences (see #175 for more). If a URL is valid, great. If it's not, then it should alert the user and rename it to `form.xml.bad` (or just delete it).

### PR DESCRIPTION
**Pull request by pratikmjoshi**
Fixes #709 
When filling a blank form, when forms are scanned, the prescence of bad url throws illegalargumentexception and the user is notified that it has a bad url.

@yanokwa Could you please verify this pr?

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java [hunk 1]
```diff
@@ -301,7 +305,11 @@ public ContentValues buildContentValues(File formDefFile) throws IllegalArgument
             updateValues.put(FormsColumns.JR_VERSION, version);
         }
         if (submission != null) {
-            updateValues.put(FormsColumns.SUBMISSION_URI, submission);
+            if(checkValidSubmissionURI(submission)) {
+                updateValues.put(FormsColumns.SUBMISSION_URI, submission);
+            } else {
+                throw new IllegalArgumentException(formDefFile.getName() + " :: bad url");
```
Comment (yanokwa) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java]: This message should be put into strings.xml so it can be localized. Might be easier to just refer to `url_error`.

File: collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java [hunk 2]
```diff
@@ -326,4 +334,7 @@ protected void onPostExecute(String result) {
         }
     }
 
+    public boolean checkValidSubmissionURI(String submissionURI) {
```
Comment (yanokwa) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java]: Use UrlUtils.isValidUrl so we have one implementation.

File: collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java]: Note that this is not required for all exception text. It's just that this particular exception text gets shown in the UI!

File: collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java]: I think what @yanokwa is suggesting is that instead of creating this new method, it would be preferable to just use `UrlUtils.isValidUrl` in the code. It turns out that both do about the same check. Both allow a lot that doesn't actually end up working in this case so we should investigate whether we can improve on that implementation.

**Comment by yanokwa** [comment]
This does a good job of catching if a bad form is put on the SD card, but it doesn't catch the problem if the bad form is downloaded from a server. I'm not sure where the best place in the code to do this. `DownloadFormsTask.java` might be a good place to start.

**Comment by pratikmjoshi** [comment]
@yanokwa @lognaturel Sorry for the delay.I've made the changes requested. 
Also, if I use UrlUtils.isValidUrl, then the bad form from server is not removed. However, when I used Patterns.WEB_URL.matcher() function, bad forms from server are also removed once downloaded. So I've removed the method, but I've not used UrlUtils.
I placed the bug.xml file in my google drive and downloaded it. It got removed as soon as I clicked "Fill Blank Form" and I was notified. I don't think there's a need to make any changes to DownloadFormsTask, because DiscSyncTask runs for all unparsed files, and any form downloaded from the server will get removed if it has a bad url.

**Comment by yanokwa** [comment]
@pratikmjoshi I think we are making good progress! 

I have added a test form on https://nafundi-test.appspot.com. This form has a bad URL (e.g., `not-a-url`). Once this form is downloaded, I can fill it out, submit it, and it'll fail submission with Client Protocol Exception. This happens with your PR.

**Comment by pratikmjoshi** [comment]
@yanokwa Yes I tried it out and got the same problem. When I try to access the odk/forms directory(on my phone) through my laptop, the form xmls are not visible. However, when I view the directory through the file manager on my phone, they are visible. Why is this so?

**Comment by yanokwa** [comment]
@pratikmjoshi The computer-android file browsing tools are terrible. I'd recommend you use `adb shell` and navigate that way.

**Comment by lognaturel** [comment]
@pratikmjoshi @yanokwa I'm not clear on the status of this PR! Please update me, @yanokwa are you asking for a change?

**Comment by pratikmjoshi** [comment]
@lognaturel The current PR solves the problem of removing manually added bad forms, as well as bad forms downloaded from google drive. However, it doesn't remove bad forms downloaded from the server.

**Comment by lognaturel** [comment]
@yanokwa Can you please clarify whether this is sufficient for this pull request or whether behavior needs to be added?

**Comment by yanokwa** [comment]
@pratikmjoshi I'm very sorry I wasn't able to get to this sooner. And because I let this sit so long, I had to do something I rarely do, I pushed the changes I'd like to see into your branch so we can merge it. The changes are:
* Using UrlUtils.isValidUrl() so we have consistent validation
* Removed unnessary logging and imports
* Reused xform_parse_error string

**Comment by yanokwa** [comment]
As to the issue of the bad forms not working in Aggregate, I've filed that separately at https://github.com/opendatakit/collect/issues/873. Perhaps you can work on it there? I'll do my best to get that code reviewed quickly. ✨Thanks again for your contribution!✨
