### PR TITLE
Fixed the RangePicker widget

### LINKED ISSUE #5284: Range with picker appearance adds extra digit
Version: 2022.3 but said to have existed previously. 

From @mathieubossaert:
> When we choose a value and then change it, an extra digit is added to the value. This happens for values <= 10.

https://forum.getodk.org/t/display-bug-for-range-question-with-picker-appearence/38980

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5284 

#### What has been done to verify that this works as intended?
I've added automated tests and tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
As we agreed in the issue to avoid the bug in `NumberPicker` we should display all elements in the ascending order. It is the easiest solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test [range widgets](https://docs.getodk.org/form-question-types/#range-widget-with-picker) (integer and decimal) with `picker` appearance. There is a lot of refactoring that might spoil something. Other widgets are safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
This for example: [rangePickerWidget.xlsx](https://github.com/getodk/collect/files/10180451/rangePickerWidget.xlsx)
but be creative.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.kt [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+import androidx.fragment.app.DialogFragment
+import com.google.android.material.dialog.MaterialAlertDialogBuilder
+import org.odk.collect.android.R
+
+class NumberPickerDialog : DialogFragment() {
+    interface NumberPickerListener {
+        fun onNumberPickerValueSelected(widgetId: Int, value: Int)
+    }
+
+    private lateinit var listener: NumberPickerListener
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.kt]: This can just be nullable and then called with `?`

File: collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerDecimalWidgetTest.kt [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+
+    @Test
+    fun `list of numbers should contain only rangeStart when range has equal start and end`() {
+        rangeQuestion.rangeStart = BigDecimal(5.0)
+        rangeQuestion.rangeEnd = BigDecimal(5.0)
+        rangeQuestion.rangeStep = BigDecimal(1.0)
+
+        val widget = createWidget(QuestionWidgetHelpers.promptWithQuestionDefAndAnswer(rangeQuestion, null))
+
+        assertThat(widget.displayedValuesForNumberPicker, equalTo(arrayOf("5.0")))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerDecimalWidgetTest.kt]: Instead of needing to expose a private field from `RangePickerXWidget`, could we just have these tests targeting the `NumberPickerDialog` and pass it the start, end and step? Alternatively, I'd also be happy with just testing `RangePickerWidgetUtils.getNumbersFromRangeAsc` directly.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.kt]: Yes, done.

File: collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerDecimalWidgetTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerDecimalWidgetTest.kt]: Ok, I implemented it in that second way.

File: collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtilsTest.kt [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+        val rangeStep = BigDecimal(1)
+
+        assertThat(
+            RangePickerWidgetUtils.getNumbersFromRangeAsc(rangeStart, rangeStep, rangeEnd, true),
+            equalTo(arrayOf("-5", "-4", "-3", "-2", "-1", "0", "1", "2", "3", "4", "5"))
+        )
+    }
+
+    @Test
+    fun `list of numbers should contain numbers in ascending order when range is decreasing and step is -1,5`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtilsTest.kt]: Is this test there to check we can increment/decrement decimal values? If so, I think the test name should read "...step is decimal". At the moment, it looks like 1.5 is a special case.

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtilsTest.kt]: I think in this case the goal was more to make sure that when the range is decreasing like 10 to 1 as a step we can use 1 but also -1. So maybe the title should be: `list of numbers should contain numbers in ascending order when range is decreasing and step is a negative number`?

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtilsTest.kt]: Yeah that seems better!

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtilsTest.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10

**Verified cases:**
- issue #5284 is no longer reproducing
- range picker with ascending/descending values set in a form (with different steps)
- range picker with integers, negatives values, decimals
- RTL
- rotating, minimizing, locking the screen
- regression checks on range widgets

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Androids: 5.1 and 13
