### PR TITLE
Fix disappearing entity lists

### LINKED ISSUE #6160: An entity list that doesn't exist in any form in a project disappears from entity list in experimental settings
#### ODK Collect version
the master version edcffccf3e5d5793e4ace510c88d16585e8cd075
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
An entity list that doesn't exist in any form in a project disappears from entity list in experimental settings after refreshing the list of bank forms.
#### Steps to reproduce the problem
1. In experimental settings enable local entities.
2. Go to entity lists.
3. Tap the three dots – Add entity list.
4. Enter a name of a entity list that doesn’t exist in any form in the device (e.g. "abc”) and tap "add”.
5. Tap the three dots – Add entity list.
6. Enter a name of a entity list that exists in a form in the device (e.g. "trees”) and tap "add”.
7. Go to Start new form and refresh the list of forms.
8. Go to experimental settings and check if  "abc” is in the entity list
#### Other information
If I add just an entity list that doesn't exist in forms (so it's the first and only entity list in experimental settings) and refresh the list of blank forms, then the issue doesn't occur (entity list doesn't disappear).

### LINKED ISSUE #6163: Manually added second dataset/entity list is removed after refreshing the list of blank forms
#### ODK Collect version
the master version d67e55a75cc20d31fdd9468f575ed2c2aa239dac
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that after manually adding a dataset in experimental offline entities the first dataset shows the list of entities after refreshing the list of blank form but repeating it for another dataset results in removing the dataset form the list of entity list in experimental setting.
If I create an offline entity after adding the entity list, the entity list won't disappear even if it's the second entity list/dataset.
#### Steps to reproduce the problem
1. Create a project which contains 3 different datasets (entity lists)
2. In experimental settings enable local entities.
3. Go to view entity lists.
4. Tap the three dots – Add entity list.
5. Refresh the list of blank forms.
6. Go to view entity list and check if the first entity list is there (the dataset exists and you can see entities in it).
7. Tap the three dots – Add entity list and enter the name of the second dataset (entity list).
8. Refresh the list of blank forms.
9. Go to view entity list and check if the second entity list is there.
10. Repeat steps 3-6 for the third dataset.

### LINKED ISSUE #6262: Adding entity lists and sending a registration form removes other entity lists from experimental settings
#### ODK Collect version
the master version edcffccf3e5d5793e4ace510c88d16585e8cd075
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After adding entity lists (in experimental settings) and sending a registration form, the entity list with the submission stays on the list but other entity lists get removed.
I tried to eliminate some factors causing it – the issue won’t occur:
- if you save the form as draft
- if you refresh the list of blank forms before sending the registration form
#### Steps to reproduce the problem
1. Add a project with 2 or 3 entity lists in forms. (e.g. user "entities” in https://test.getodk.cloud/#/projects/436/app-users)
2. Go to experimental settings and enable local entities.
3. Tap "view entity lists”.
4. Add 3 entity list (that are in forms e.g. basic, children, trees).
5. Go to "Start new form” and send a submission of a registration form.
6. Go to experimental settings and check which entity list there is.
#### Expected behavior
Entity lists shouldn’t be removed after sending forms.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6262
Closes #6163
Closes #6160

#### Why is this the best possible solution? Were any other approaches considered?

The solution itself is a little hacky, but the current entities storage implementation (`JsonFileEntitiesRepository`) is about to go away, and the most important thing here in my opinion is to get a test in to verify correct behaviour in the new implementation.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Checking entity forms/projects here is probably the most important thing.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt [hunk 1]
```diff
@@ -57,7 +57,7 @@ abstract class EntitiesRepositoryTest {
     }
 
     @Test
-    fun `#save updates existing entity with matching id in different list`() {
+    fun `#save creates entity with matching id in different list`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt:60]: This behaviour isn't something we have an opinion as far as I'm aware - we don't expect this to happen in real life, and if it did either behaviour feels reasonable.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on devices with Android: 10, 14

**Verified Cases:**
- Registration / update forms
- Offline entities
- Multiple entity lists in one project
