### PR TITLE
Fix change reason behaviour after minimizing app [master]

### LINKED ISSUE #5291: Missing events/answers in audit log for track changes reason form if the form was minimized and the changes where made on the reopened page
#### ODK Collect version
v2022.3.0
#### Android version
probably all
#### Device used
Samsung M12, Redmi 9T, 12(on the emulator), 13 (on the emulator)
#### Problem description
If a user starts filling a form with audit and tracking changes and minimizes it and goes back to filling the same page(without swiping to next page) and changes the answers, there is a difference between answers visible in "View Sent Form” and audit.csv file. The changed answers are not in audit.csv file. If the submission is viewed on Central or via Enketo all the answers are visible.

For forms with `track-changes-reason` (like in the steps below), the user is able to bypass the change reason prompt with this flow.

#### Steps to reproduce the problem
1. Go to Track Changes Reason form.
[track-changes-reason-on-edit.xml.txt](https://github.com/getodk/collect/files/9624044/track-changes-reason-on-edit.xml.txt)
2. Start filling the form.
3. Minimize the form while on page with "What’s up?” question.
4. Go back to the form and don’t swipe to the previous/following page.
5. Add something to the answer on the page which was opened after going back to the form.
6. Finalize and exit the form.
7. Go to audit log and go to "View Sent Form” and compare the final answers. 

#### Expected behavior

The answers added in step 5 should be visible in audit log.

#### Other information 
If the user clicks next and then back, the changed answers will be in audit log.
I haven’t checked earlier versions than v2022.3.0
If don't keep activities is on, all the answers are in the audit log.

### LINKED ISSUE #5301: No modal asking the user to enter the reason for changes when the Track Reason Changes form was killed while editing it
#### ODK Collect version
v2021.3.4, v2022.1.0, the store version (2022.3.5), master version 31897362c00974e7df889ef685337244f0ac5604
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6A
#### Problem description
After killing the Track Changes Reason form there is no modal asking the user to enter the reason for changes when the form was killed while editing it.
#### Steps to reproduce the problem
1. Go to "Fill Blank Form".
2. Go to Track Changes Reason form.
[track-changes-reason-on-edit.xml.txt](https://github.com/getodk/collect/files/9746996/track-changes-reason-on-edit.xml.txt)
3. Fill the first question.
4. Save and exit the form.
5. Go to "Edit Saved Form".
6. Open the filled form.
7. Add something in the filled answer.
8. Minimize and kill the app.
9. Go back to the same form in "Edit Saved Form".
10. Go to end,  save and exit the form.

#### Expected behavior
The user should be asked to enter a reason for changes. The `question` event with the changed answer should also be present (this is true in v2022.3.5 but not in other versions).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5291
Closes #5301

I managed to get to a simpler change than the one we made with #5300 here - comments inline on that.

As discussed in #5301, I've also made changes so that a change reason prompt/event will happen when a form that is being edited (finalized or not) is saved **regardless** of if the user has changed anything or not.

#### What has been done to verify that this works as intended?

Still wasn't able to come up with a good test for this. Minimizing seems to be a blind spot so a good one for @getodk/testers to continue to prod. I think we could do with pulling out the code that deals with save points in `onSaveInstanceState` to a use case with its own unit tests, but I'd like to see this get through QA before doing that. If it fits in, I can add those tests before merging.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

As stated in the description, the change reason feature is now more aggressive and the user will see a prompt when saving a form that's being edited (rather than filled in for the first time). As well as just change reason specifically (paying close attention to the new behaviour), it'd be good to check the audit log feature in general. Minimizing, killing the app etc are all good tricks to deploy here.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt [hunk 1]
```diff
@@ -252,7 +252,7 @@ abstract class Page<T : Page<T>> {
     }
 
     fun <D : Page<D>?> rotateToLandscape(destination: D): D {
-        currentActivity!!.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
+        onView(isRoot()).perform(rotateToLandscape())
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt:255]: I'd seen a couple of flakes on this (related to #5325) and wanted to make sure we were using consistent rotation actions here.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 2]
```diff
@@ -1882,17 +1894,6 @@ protected void onPause() {
...
         backgroundLocationViewModel.activityHidden();
 
-        FormController formController = getFormController();
-
-        // make sure we're not already saving to disk. if we are, currentPrompt
-        // is getting constantly updated
-        if (!formSaveViewModel.isSaving()) {
-            if (currentView != null && formController != null
-                    && formController.currentPromptIsQuestion()) {
-                formEntryViewModel.updateAnswersForScreen(getAnswers());
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:1892]: As far as I can tell, we only need to do this to make sure the save point created in `onSaveInstanceState` will have to update answers. If that's the case, we can move the call from here to `onSaveInstanceState` ~~so it will only happen on recreation rather than when minimizing the app or switching screens~~.

Edit: **NOPE**. I'm not sure what got into me, `onSaveInstanceState` gets called basically whenever `onPause` is called. I still think this move is good as it's clearer that we're saving the form data as part of the Activity's "state".

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> As discussed in https://github.com/getodk/collect/issues/5301, I've also made changes so that a change reason prompt/event will happen when a form that is being edited (finalized or not) is saved regardless of if the user has changed anything or not.

@lognaturel I wanted to make sure you are aware of this change and have nothing against. You didn't respond in the issue so it looks like @seadowg had that discussion with himself only :smile:

**Comment by lognaturel** [comment]
I love a good conversation with one's self! We discussed at a Tues meeting, you might have been out and I should have updated the issue! All good from my end. It's a slightly worse user experience but on the other hand we found out that we weren't detecting possible calculate changes so it will be more accurate.

We do want to highlight the change in beta release notes and see if there's any feedback. Good to try to get this one QAed as soon as possible.

**Comment by srujner** [comment]
Hi @lognaturel @seadowg We're a little bit confused by this PR. At this state only issue #5301 is no longer reproducing. We're able to reproduce #5291 and the crash from the 5301 comment. Is it expected behavior for now?
If not I think this should not have the "needs testing" label yet. Let us know!

**Comment by seadowg** [comment]
@srujner I'd definitely intended for it to fix #5291, so I'll need to look at that. I should have been clearer in that comment that the crash is a separate issue - the crash should not result in the user being able to skip the change reason, however. I'll update that there.

**Comment by seadowg** [comment]
@srujner trying the steps out for #5291, I'm no longer seeing the problem where the change reason dialog (and event) are missing after minimizing. However, the `question` event is there but is missing the new answer. So as an example, when editing the form I see a log like this:

```
form resume,,1668180215814,,,,
jump,,1668180215816,1668180228468,,,
question,/data/what_up,1668180217931,1668180228468,,,
end screen,,1668180235557,1668180236275,,,
change reason,,1668180260353,,,,blah
form save,,1668180260653,,,,
form exit,,1668180260653,,,,
form finalize,,1668180260654,,,,
```

Is that what you're seeing as well? If so, it looks like I've fixed part of the issue (the change reason dialog and event not showing), but the `question` event is still broken.

**Comment by dbemke** [comment]
Looking at your audit log I’m not sure if you filled something in the question and if you combined steps from issue #5291 and #5301. What are the steps to reproduce that?
Steps from the issue #5291 don’t involve editing (going to "Edit Saved Form”) so should there be a dialog with changing reason? The answer added after minimizing is still missing.
minimizing

If I follow the steps from issue #5301 (with editing the form and killing the app), there is the dialog about changing reason and the added answer in the question is visible in the audit log.
trackaudit

**Comment by seadowg** [comment]
> Steps from the issue https://github.com/getodk/collect/issues/5291 don’t involve editing (going to "Edit Saved Form”) so should there be a dialog with changing reason?

Ah sorry, I'd misread and was confusing myself by thinking that issue was concerned with the edit step. There should probably be another issue for the change reason dialog not showing when the form is being edited, and you use the same "minimize before answering" trick, but that's now fixed.

Back to #5291: I'm going to use the same solution that I used in #5300. I'd really have liked to spend more time building a test harnesses for audits with minimizing or killing tasks (and how that all interacts with save points etc), but we'd need to do a lot of work to get there, and I don't think we should push back the release for it. I've created an issue (https://github.com/getodk/collect/issues/5338) for adding that testing and that'll hopefully give us the confidence to do more restructuring in this area.

**Comment by seadowg** [comment]
@dbemke @srujner both issues should actually be fixed now (I just tried out #5291, and it seems to be working correctly).

**Comment by dbemke** [comment]
issue #5291 works as expected, but after steps from issue #5301 the added answer before killing the app (while edited) disappeared from the audit log
appkill

**Comment by seadowg** [comment]
@dbemke right good find. That question event is also missing in v2022.2 releases (and previous) as well right? I'm guessing it's also the behaviour we see in v2022.3.6? We made that compromise there and think we'll have to here as well. Without adding a bunch of automated testing, I don't feel confident making the changes needed to get that question event working. @lognaturel we should discuss this.

**Comment by dbemke** [comment]
@seadowg 
Previous commit worked as expected ( the event question and added answer before killing the app while edited were in the audit log), it disappeared with the new commit in the PR
in Collect v 2022.2.0 it was missing.

**Comment by seadowg** [comment]
> it disappeared with the new commit in the PR

Yup that makes sense. As in #5300, the fix for #5291 reintroduces that problem. At the time, we decided that fixing the change reason behaviour was more important than the lost `question` event data (as we don't have a good solution to fixing both problems). But I'd like to discuss that again for this release. For the moment, let's continue testing this PR as-is.

**Comment by dbemke** [comment]
@seadowg Does it mean that this scenario is also ok in this PR? 
There is an event missing (question) when the user goes from filling the form to project settings and then finishes filling the same form. On the master version the events were in the audit log.

**Steps to reproduce:**
1. Go to Fill Blank Form.
2. Go to Track Changes Reason form.
3. Fill something in.
4. Tap on three dots to go to settings.
5. Change the theme to a different one (e.g. light to dark mode).
6. Go to Fill Blank Form.
7. Go to Track Changes Reason form.
8. Go to end.
9. Save and Exit the form
(After those steps the user sees the dialog asking to enter reason for the change)

**Comment by seadowg** [comment]
> Does it mean that this scenario is also ok in this PR?

Yeah I'm thinking that's fine as long as that's also how it behaves in v2022.2. We should still create issues for these missing events after merging this PR though. Just to be very clear, the reason I'm ok with these problems is that they've existed for a long time, and we accidentally fixed them in v2022.3 but introduced worse (which is subjective of course) problems by doing so.

**Comment by dbemke** [comment]
> Yeah I'm thinking that's fine as long as that's also how it behaves in v2022.2.<

Yes.It is the same in v2022.2. I'll file a separate issue for that.

**Comment by dbemke** [comment]
If don’t keep activities is enabled, the reason given by the user while saving changes with the save button (floppy disk) is not shown in other save options if the user tries to save the changes after going to the hierarchy view.

https://user-images.githubusercontent.com/56479916/201884936-dbfe2dbc-695c-49bd-b1d0-c54a24b7250d.mp4



**Steps to reproduce:**
1. Don’t keep activities is enabled in device’s settings.
2. Go to Fill Blank Form.
3. Fill and save Track Changes Reason form.
[track-changes-reason-on-edit.xml.txt](https://github.com/getodk/collect/files/10011324/track-changes-reason-on-edit.xml.txt)
4. Go to Edit Saved Form
5. Choose the form.
6. Tap the save button (floppy disk) and enter reason for change.
7. Go to the hierarchy view.
8. Tap on any question.
9. Go to end and save the form/ Tap device back button and choose save.

**Expected result:**
In every save option the user should see the previously entered reason for change.

**Comment by seadowg** [comment]
> If don’t keep activities is enabled, the reason given by the user while saving changes with the save button (floppy disk) is not shown in other save options if the user tries to save the changes after going to the hierarchy view.

@dbemke I'm not sure if I understand this. Using the video as an example, are you saying that you expect the second change reason prompt (after coming back from hierarchy) to have "Reason" prefilled with "floppy"? There's no problem with the audit log or when the prompt shows here right?

**Comment by dbemke** [comment]
>  the second change reason prompt (after coming back from hierarchy) to have "Reason" prefilled with "floppy"? There's no problem with the audit log or when the prompt shows here right?

In other cases when don't keep activities in not enabled in the second (or following ones) reason prompt the user sees the reason which was entered in the first (or following) prompt ("floppy"). Audit log looks fine as reasons are in the audit log.  A video just to show an example how it works in other cases.

https://user-images.githubusercontent.com/56479916/201889123-cd9dc78b-2f93-40dc-ade0-74f6bd687a90.mp4

**Comment by seadowg** [comment]
@dbemke right I see. The PR behaviour is consistent with v2022.3 (and v2022.2 I imagine) though right? I don't think we've ever supported prefilling the change reason in that scenario ("Don't Keep Activities" and moving to and from hierarchy). It's a good find and would be a nice thing to add, but I don't imagine it's something we'd look at any time soon. I could see us actually changing the implementation of how hierarchy works down the line in a way that would "accidentally" fix this.

**Comment by dbemke** [comment]
@seadowg yes. It worked the same in v2022.2. It was the last thing I could find so I think we finished testing the PR.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10, 13

**Verified Cases:**
- issue #5291 and the missing change reason dialog in the issue #5301 (except from missing quesion in the audit log) are no longer reproducing
- entering reason for a change in a form after killing the app, going to settings
- entering a reason for change in an edited form by clicking the save button, save and exit button, device back button+save changes
- entering a reason for change in an edited form after killing the app, going to settings, minimizing, rotating, locking the screen, going to the hierarchy view
- entering a reason for change when a question in a form was changed or wasn’t changed
- adding something to an answer after minimizing the app, locking the screen, rotating, going to hierarchy view
- checking audit logs, swiping/not swiping to the next question
- killing the app while on a question, the hierarchy view
- don’t keep activities enabled/disabled
- dark/light mode
- different Form Management settings

**Review by grzesiek2010 — APPROVED** [review]
