### PR TITLE
Removed redundant logs from Appearances

### LINKED ISSUE #5376: Improve error handling and code flow for columns appearance on selects
There's a form that seems to have the appearance "columnscolumns-" and is causing a lot of Crashlytics noise: https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4bc6ee671a837984b0bc1fdd21792763?time=last-seven-days&versions=v2022.4.1%20(4543)&sessionEventKey=6393045A000000015B78CB196337837E_1753531330254806919

Let's stop logging that exception and also take a quick look at the flow around that area to see whether it can be simplified.

To be explicit, I think silently ignoring unsupported appearances is the right behavior. It's up to users to test their forms and make sure they're getting the look that they're going for.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5376 

#### What has been done to verify that this works as intended?
I've improved automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I've just removed logs that we no longer need. Additionally, I converted related classes to kotlin what we usually do.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt [hunk 1]
```diff
@@ -138,10 +134,10 @@ object Appearances {
                         }
                     }
                 } catch (e: Exception) {
-                    Timber.e(Error(EXCEPTION_PARSING_COLUMNS + columnsAppearance))
+                    // ignore
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt]: While here, could you look to simplify this a bit? There's no point to the inner try/catch, right?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt]: Right, done.

**Review by seadowg — APPROVED** [review]
