### PR TITLE
fix: Added a progress dialog while deleting the forms.

### LINKED ISSUE #1258: User should see progress dialog during deleting saved forms
#### Software and hardware versions 
Android 6.0, Sony Z3

#### Problem description
Progress of delete forms is not visible
 
#### Steps to reproduce the problem
1. User has many saved forms (eg. 1000)
2. User wants to delete all saved forms 
3. User clicks on 'Select All' and then 'Delete Selected'
screenshot_20170718-104714
4. User is not informed about a progress in removing forms
- deleting about 1000 forms takes about *1m30s*
- additionally user can goes to other views - that can cause other problems

#### Expected behavior
User sees similar dialog to 'Sending Form'
screenshot_20170718-104544

#### Other information 
Noticed during testing [Caused by android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1) #1249](https://github.com/opendatakit/collect/pull/1249)

### PR DESCRIPTION
**Pull request by dr0pdb**
FIX #1258

Although the recommended way of obtaining this result is to create the ```ProgressDialog``` in the ```AsyncTask's``` ```onPreExecute``` method but I wasn't able to get the right ```Context``` for the ```ProgressDialog```. Hence I created the ```ProgressDialog``` in the ```DataManagerList``` class itself.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @srv-twry! I've tagged it as `needs testing` so we can get a couple of people to try it out and verify the behavior. In the future, please make sure to follow the provided template for pull requests! 😊

It looks like `checkstyle` is currently failing. You can see the issues by clicking on Details next to the circleci check notice or by running `./gradlew checkstyle` locally.

File: collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java [hunk 1]
```diff
@@ -230,12 +242,16 @@ public void deleteComplete(int deletedInstances) {
...
         }
+
         deleteInstancesTask = null;
         getListView().clearChoices(); // doesn't unset the checkboxes
         for (int i = 0; i < getListView().getCount(); ++i) {
             getListView().setItemChecked(i, false);
         }
         deleteButton.setEnabled(false);
+
+        //Dismiss the progress dialog.
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java]: This comment isn't necessary as it's obvious that `progressDialog.dismiss()` dismiss the progress dialog :)

File: collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java [hunk 2]
```diff
@@ -199,6 +200,17 @@ public void onClick(DialogInterface dialog, int i) {
      */
     private void deleteSelectedInstances() {
         if (deleteInstancesTask == null) {
+
+            /*
+            * For solving #1258.
+            * Create the progress dialog before starting the background task.
+            * Could have been done in the DeleteInstancesTask's onPreExecute() but was unable to get the context correctly.
+            * */
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java]: I would get rid of this comment too as it's pretty obvious what we do here. We should add comments only if something is hard to understand, tricky or fixes some strange issue. If you want to keep the code clear a better solution is to move this part of code to a separate method.

File: collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java [hunk 3]
```diff
@@ -199,6 +200,17 @@ public void onClick(DialogInterface dialog, int i) {
...
+            progressDialog = new ProgressDialog(getContext());
+            progressDialog.setMessage("Deleting selected forms...");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java]: it shouldn't be hardcoded, you should place it in strings.xml file

**Comment by grzesiek2010** [comment]
Don't know if this pr makes a sense since it doesn't use [DialogFragment](https://developer.android.com/reference/android/app/DialogFragment.html). @srv-twry you may don't know but we have started work on replacing all our dialogs using DialogFragment:
https://github.com/opendatakit/collect/issues/541
https://github.com/opendatakit/collect/pull/1269
https://github.com/opendatakit/collect/pull/1275

**Comment by yurilaguta** [comment]
@srv-twry maybe for consistency and better user experience it should be similar to the screen shot attached showing progress with amount of files that has been already deleted, because if it takes 1.5 minute people will leave application or even worse go back. If you post progress inside DeleteInstancesTask, it shouldn't be to much effort but will be great UX.

**Comment by dr0pdb** [comment]
@Yurii-Laguta I had initially planned to implement it the same way that you are suggesting , but i was unable to get the ```Context``` in the ```AsyncTask``` for the ```ProgressDialog``` hence had to implement it inside the ```Fragment``` itself which means i don't have access to the variables which can be used to display the progress since they are inside the ```AsyncTask``` only.  
Any suggestion on how to get the ```Context``` inside the ```AsyncTask``` would be very helpful. Then i would  do it again for better User experience.

**Comment by lognaturel** [comment]
I think it's appropriate to match what `InstanceUploaderActivity` does using a `ProgressDialog` for now. This solves the immediate problem in a consistent way and all `ProgressDialog`s can be replaced together at some later date. I do agree that it would be better if the count could be updated so perhaps @srv-twry and @Yurii-Laguta you can do some brainstorming in #collect-code and others with ideas can also jump in.

The progress indicator is choppy on my device, it doesn't spin smoothly. Is there processing happening on the UI thread that shouldn't be by any chance?

**Comment by dr0pdb** [comment]
@lognaturel @grzesiek2010 @Yurii-Laguta Kindly review this PR. I added an interface method which would update the dialog from time to time using the ```PublishProgress``` method inside the ```AsyncTask```. The ```ProgressDialog``` now shows the progress of the task as well. Finally ! :smile:

File: collect_app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -507,4 +507,7 @@
     <string name="not_supported_offline_layer_format">Selected offline layer file uses the PBF format which is not supported!</string>
     <string name="sort_by">Sort by</string>
     <string name="server">Server</string>
+    <string name="form_delete_message">Deleting selected forms</string>
+    <string name="deleting_form_dialog_first">Deleting form:\u0020</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: The dialog message should be a single string and should take in the current and total number of forms as parameters. This is important because not all languages are left-to-right and translators must have the option of repositioning the two form counts relative to each other.

**Comment by lognaturel** [comment]
Nicely done, that looks like the right approach. I made a quick comment about the string.

Any ideas about the choppiness of the dialog? I noticed that it has to do with the number of forms there are to delete. If there are 1000 forms, the status indicator is really slow but as the number to delete goes down the status spinner speeds up. That seems fishy to me. It doesn't need to be handled in this PR but would be good to investigate.

**Comment by dr0pdb** [comment]
@lognaturel I have changed the ```String``` resource as suggested.
I don't think i have any idea about the choppiness of the dialog. Maybe someone else can come up with the  possible explaination. :smile:

**Comment by yurilaguta** [comment]
Looks great, one minor formatting related comment. I'm surprised it's not picked up by checkstyle.

**Comment by shobhitagarwal1612** [comment]
I got the following stacktrace in debugger, although no crashes:

```
08-19 03:24:08.080 5281-5281/org.odk.collect.android E/WindowManager: android.view.WindowLeaked: Activity org.odk.collect.android.activities.InstanceUploaderActivity has leaked window DecorView@44c68a0[Upload Results] that was originally added here
                                                                          at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                          at android.app.Dialog.show(Dialog.java:322)
                                                                          at org.odk.collect.android.activities.InstanceUploaderActivity.createAlertDialog(InstanceUploaderActivity.java:402)
                                                                          at org.odk.collect.android.activities.InstanceUploaderActivity.uploadingComplete(InstanceUploaderActivity.java:278)
                                                                          at org.odk.collect.android.tasks.InstanceUploader.onPostExecute(InstanceUploader.java:51)
                                                                          at org.odk.collect.android.tasks.InstanceUploader.onPostExecute(InstanceUploader.java:40)
                                                                          at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                          at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                          at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Steps to reproduce -

1. Select multiple instances and click the `send selected` button
2. Minimize the app
3. Keep a track on debugger to know when all instances have been uploaded
4. After all of the  instances have been uploaded, reopen the app

Possible solution: Dismiss the progress dialog when the activity gets paused and redisplay it on resuming the activity.

**Comment by dr0pdb** [comment]
@shobhitagarwal1612 I think the stacktrace is related to Uploading the saved forms i.e. the ```InstanceUploaderActivity``` , while my PR is about deleting the saved forms.
Although if you want me to fix this issue in this PR itself ,i can do that.

**Comment by lognaturel** [comment]
Interesting one, @shobhitagarwal1612! @srv-twry is absolutely right that this should be its own issue -- could you please file it?

**Comment by shobhitagarwal1612** [comment]
@srv-twry This should be fixed separately. I must have been confused at the time of reporting this. Thanks for noticing it.
@lognaturel Sure

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
Issue verified on Android: 4.1, 4.4, 5.1, 6.0, 7.0.
User sees dialog :
screenshot_20170906-113755

User is informed that some action is in progress, which is great. 

I have only doubts about the appearance of this dialog.
I expected to see a 'dialog name' like eg. Deleting Form.
This would be consistent with other dialogs such as:
28311697-c281fd54-6bb0-11e7-9f56-6fc8d090a54b
Additionally, when user send forms he sees gray background under the dialog.
@lognaturel Should we take care of those appearance details?

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
