### PR TITLE
Ensure Cursors don't cause crashes by being processed after a close() call

### LINKED ISSUE #6889: Occasional crash loading entities in form
There appears to be a [crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/34caabea0b5ff1536cc7b406752211fa?time=last-ninety-days&types=crash&sessionEventKey=68C36B5C03B800015D8365510A56E41A_2127441175925622369) that can happen when loading entities in a form.

This is likely a race condition. We reset database connections when performing some queries against the entity database to account for the magic we do to get row numbers to work. Because of this, we synchronize access to the DB, but it looks like we allow `Cursor` instances to be returned from that synchronized access which could cause this crash.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6889

#### Why is this the best possible solution? Were any other approaches considered?

My guess is that the crash is caused by the `Cursor` returned by `rawQueryWithRowNumber` being accessed after another access to the DB closes the connection. This problem here is that returning a `Cursor` from `withSynchronizedConnection` breaks the guarantees of the method as `Cursor` needs the connection to still be open to be used. The fix here is to protect from that scenario in `withSynchronizedConnection` and then update callees to work around that.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

We'll want to check entity update forms in particular here, but nothing should actually have changed. There's no definite way to reproduce the crash.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: db/src/test/java/org/odk/collect/db/sqlite/DatabaseConnectionTest.kt [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+import androidx.test.core.app.ApplicationProvider
+import androidx.test.ext.junit.runners.AndroidJUnit4
+import org.junit.Assert.fail
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.odk.collect.db.sqlite.support.NoopMigrator
+import org.odk.collect.shared.TempFiles
+
+@RunWith(AndroidJUnit4::class)
+class DatabaseConnectionTest {
```
Comment (grzesiek2010) [inline db/src/test/java/org/odk/collect/db/sqlite/DatabaseConnectionTest.kt:16]: There is another `DatabaseConnectionTest` in our project. Can we merge them?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with  Android 10 (Dominika), 16 (Wiktor)

**Verified cases:**
- all regression test cases connected with entities
