### PR TITLE
choice-name not working with a dynamic choice-list is accessed from csv

### LINKED ISSUE #179: choice-name not working with a dynamic choice-list is accessed from csv
<a href="https://github.com/mitchellsundt"></img></a> **Issue by [mitchellsundt](https://github.com/mitchellsundt)**
_Thursday Jul 09, 2015 at 19:46 GMT_
_Originally opened as https://github.com/opendatakit/opendatakit/issues/1154 (1 comment(s))_

---

Originally reported on Google Code with ID 1153

```
Reported by Andrew <acawood777@gmail.com>
-------------------
Hi all,

I am having problems using choice-name() within a repeat-group when data has been loaded
from a csv:

First I load data from a csv to populate a multi-select.
Once selections have been made I have a repeat-group which repeats for each selection
(e.g. 3 items selected = 3 repeats)
Each repeat needs to display the corresponding name and label that was selected, in
order to request further info on each.

For the name I use selected-at() and this works.
       selected-at(${catch_specie},position(..)-1)

For the label I use choice-name():
        jr:choice-name(selected-at(${catch_specie},position(..)-1), '${catch_specie}')
This gives a blank result.
It does work correctly when my multi-select options are listed under the choices tab
(I use XLSForm), instead of being loaded from .csv file.

Files showing both are attached.

Does anyone know why this is happening? Is it a bug, or expected behaviour?

I would appreciate any suggestions for a workaround.

Thanks!
Andrew
```

Reported by `mitchellsundt` on 2015-06-29 19:33:01

<hr>
- _Attachment: [choice-name-csv-bug.zip](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-1153/comment-0/choice-name-csv-bug.zip)_

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #179 

#### What has been done to verify that this works as intended?
I tested the attached form and select questions from `AllWidgets` form.

#### Why is this the best possible solution? Were any other approaches considered?
We read external choices in Collect (all classes are in `org.odk.collect.android.external`). That mean s Javarosa doesn't know about them and can't read their names. I chnged it by injecting choices we read into javarosa.+

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pr is a bit risky because it reactors many widgets. All select widgets should be tested to avoid regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
Yes, I prepared a special form that contains different questions which use items:

- SelectOneWidget
- RankWidget
- ItemsetWidget
- SelectOneWidget external

[selectTest.zip](https://github.com/opendatakit/collect/files/2822875/selectTest.zip)

Btw. The form shows that the issue still occurs when it comes to `ItemsetWidget` but it's a separate issue which would need changes on the Javarosa's side so I didn't fix it in this pr.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by cooperka** [comment]
@yanokwa this isn't in the 1.20 milestone but I'm requested for review, what's the priority? Planning to tackle 1.20 stuff first.

**Comment by yanokwa** [comment]
Thanks for asking! I think we should bump it to v1.21 since it's been an issue for a while and it's risky.

**Comment by cooperka** [comment]
@shobhitagarwal1612 or @zestyping do you have time to review this if I hand it off? I'm trying to prioritize a few other PRs on my plate.

**Comment by lognaturel** [comment]
This relates to the `search()` appearance/function which is not part of the ODK XForms spec and not available across the ecosystem (e.g. Enketo will never support it). This is one of two client-only approaches to external data.

 Pulling out the code that identifies the appearance and handles it is definitely a great idea ([this](https://github.com/opendatakit/collect/pull/2845/files#diff-eec37af0756d64f5a0aa3028d084e69cR38)). It's also a great opportunity to add more context to what's going on. Specifically, I think it should be abundantly clear how `ItemsWidget` and `ItemsetWidget` relate to each other (they're different implementations of the same thing).

 When it comes to the actual fix, I would tend not to make `search()` easier to use or more complete but I guess I'm generally grumpy. Was there any discussion about whether it's a good thing to do? 

 That said, it does provide user value so @grzesiek2010 is probably right to do it. @grzesiek2010, did you get a chance to check performance? My expectation would be that it just means roughly doubling the memory needed for items which is probably not noticeable. Does that sound right? It's a little hacky because `addSelectChoice` really should be private and only isn't because of Java's bad encapsulation but given that the whole feature is hacky, it's not a big deal. I don't think `QuestionDef.setChoices(choices)` should be added, though.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsWidget.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import android.content.Context;
+
+import org.javarosa.core.model.SelectChoice;
+import org.javarosa.form.api.FormEntryPrompt;
+import org.javarosa.xpath.expr.XPathFuncExpr;
+import org.odk.collect.android.external.ExternalDataUtil;
+
+import java.util.List;
+
+public abstract class ItemsWidget extends QuestionWidget {
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ItemsWidget.java:35]: Could you add a Javadoc comment (`/** ... */`) to this class describing its purpose?  There should be enough detail in the description so that a person reading it would know whether a class should be derived from `ItemsWidget` or not.

**Comment by grzesiek2010** [comment]
> did you get a chance to check performance? My expectation would be that it just means roughly doubling the memory needed for items which is probably not noticeable. Does that sound right?

I didn't measure the time carefully but I tested a bigger form with 1k items and didn't notice any difference using Samsung Galaxy S4 Android 5 so not a super fast device. That code is called when you create the widget for the first time and after that, if you navigate through the form it's not called anymore and values are read from a formEntryPrompt so if there is a small difference it's just when you create the widget for the first time..

> I don't think QuestionDef.setChoices(choices) should be added, though.

I removed that comment.

> Was there any discussion about whether it's a good thing to do?

it was just that old issue #179. It was a long-standing issue so I understand that for some people it might be not important and refactoring might be a more valuable part of this pr.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ItemsWidget.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ItemsWidget.java:35]: Done.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases:
* selectTest form; value next to `SelectOneWidget external:` is visible

| without fix | with fix|
|---|---|
|Screenshot_20190403-090457|Screenshot_20190403-090357|

* verified also all widgets from `All widgets` form; regression was not noticed
* light/dark mode
* readOnly widgets

As Grzegorz mentioned, this fix is a bit risky, so it will be good to merge it to have more time to notice potential regressions.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
