### PR TITLE
Small design tweaks

### LINKED ISSUE #6713: Improve end of form messaging for editing
Building on [#6686 ](https://github.com/getodk/collect/issues/6686 )

We got feedback that it's not immediately obvious when you **can** or **can't edit** a form because they are both long blocks of text.

To improve this slightly, we want to:

- Change the colour for both states
- Shorten the title 

[Figma ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-Collect?node-id=7873-110102&t=VdVZdFgBgVWSJrsN-1)

 ----- 

**Later**

- Think about shortening it to just the title, but we will need to reconsider the layout of the page given it will be pretty sparse. 
- Potentially think about showing the summary at the end?

### LINKED ISSUE #7103: Too little space between the question and the answer in the hierarchy view
#### ODK Collect version
the master version 00ae167cfe72237fead4e5980cd062e5663b376f
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that there is too little space between the question and the answer in the hierarchy view in e.g video widget.
It isn't easy to tap the question in the hierarchy view to go back to the question (tapping the video opens the video).

Image

#### Steps to reproduce the problem
1. Go to All question types form in the demo project.
2. Go to the video widget and add a video.
3. Go to the hierarchy view.
4. Try to go back to the question by tapping the question in the hierarchy view.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7103
Closes #6713

This also makes general improvements to the spacing in the hierarchy (answers are not indented any more) and converts the form end UI to Compose.

#### Why is this the best possible solution? Were any other approaches considered?

I'll leave comments inline on anything that needs highlighted.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just make the changes described in the issues and only those parts of the app are affected.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@alyblenkin let me know what you think of the form end view. I wasn't sure which theme color to use from looking at figma, so I've used "error container" and "on error container" for now - that can be updated if it doesn't work for you.

**Comment by alyblenkin** [comment]
I think it's going in the right direction! However, the error colour makes it look like something is wrong. Can we try the colour I have in [figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-Collect?node-id=7873-110107&t=ZLDg1ji9wP5m7ta1-1)? I'm using one of the material theme state colourrs - Opacity 0.12 #6E2F2C.

**Comment by seadowg** [comment]
> I'm using one of the material theme state colourrs - Opacity 0.12 #6E2F2C.

Are you referring to [these](https://m3.material.io/foundations/interaction/states/state-layers)?

**Comment by alyblenkin** [comment]
@seadowg yes, does that work?

**Comment by seadowg** [comment]
As far as I can see, that system is for highlighting element control states like disabled, hovered etc. Happy to use that color, but I think we want to define it as something else so it fits into the Material color roles. Maybe one of the ["add-on" colors](https://m3.material.io/styles/color/roles#19e75989-7485-4f5b-a769-940c4e4364bc)? My assumption is that the intention here is to highlight the box in the "can't edit" cases and let it be less obtrusive in others, so we could also use primary and surface colors for that.

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt [hunk 1]
```diff
@@ -0,0 +1,334 @@
...
+                formTitle = "blah",
+                isEditableAfterFinalization = false,
+                shouldBeSentAutomatically = false,
+                saveAsDraftEnabled = true,
+                finalizeEnabled = true
+            )
+        }
+
+        composeTestRule
+            .onNodeWithTag(EditWarningSemantics.TAG)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:199]: @grzesiek2010 interested to see what you think of testing like this. I discussed this style of custom content description with @alyblenkin, so I'm confident that part is a good approach, but I'm less sure about the custom semantics. I keep flip-flopping in my head about whether I like them or not!

Custom semantics are documented [here](https://developer.android.com/develop/ui/compose/testing/common-patterns#custom-semantics-properties), but I haven't seen any real examples of them being used at scale. I decided to wrap them in an object to attempt to have them be discoverable without ending up with a massive global namespace where it's not clear which semantics are supported by which composables.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+            )
+        }
+
+        Row(
+            modifier = Modifier
+                .fillMaxWidth()
+                .padding(top = 64.dp),
+            horizontalArrangement = Arrangement.spacedBy(16.dp)
+        ) {
+            val screeName = stringResource(org.odk.collect.android.R.string.form_end_screen)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt]: `screeName` -> `screenName`

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt [hunk 3]
```diff
@@ -0,0 +1,268 @@
...
+                message = message,
+                errorBackground = !isEditableAfterFinalization
+            )
+        }
+
+        Row(
+            modifier = Modifier
+                .fillMaxWidth()
+                .padding(top = 64.dp),
+            horizontalArrangement = Arrangement.spacedBy(16.dp)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt]: This should use `margin_standard`.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt [hunk 4]
```diff
@@ -0,0 +1,268 @@
...
+                    modifier = Modifier.weight(1f),
+                    onClick = {
+                        if (MultiClickGuard.allowClick(screeName)) {
+                            onSave(false)
+                        }
+                    }
+                ) {
+                    Row(verticalAlignment = Alignment.CenterVertically) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_save_menu_24),
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt]: Can we use compose material icons like `Icons.Default.Save`?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt [hunk 5]
```diff
@@ -0,0 +1,268 @@
...
+                    modifier = Modifier.weight(1f),
+                    onClick = {
+                        if (MultiClickGuard.allowClick(screeName)) {
+                            onSave(true)
+                        }
+                    }
+                ) {
+                    Row(verticalAlignment = Alignment.CenterVertically) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_send_24),
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt]: Same as in https://github.com/getodk/collect/pull/7153/changes#r3027761725

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt [hunk 6]
```diff
@@ -0,0 +1,268 @@
...
+
+private fun getWarning(
+    isEditableAfterFinalization: Boolean,
+    shouldBeSentAutomatically: Boolean,
+    saveAsDraftEnabled: Boolean
+): Triple<Int, Int, Int?> {
+    return if (isEditableAfterFinalization) {
+        if (shouldBeSentAutomatically) {
+            Triple(
+                R.drawable.ic_edit_24,
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEnd.kt]: Same as in https://github.com/getodk/collect/pull/7153/changes#r3027761725

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt [hunk 7]
```diff
@@ -0,0 +1,334 @@
...
+import org.junit.Rule
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.verify
+import org.odk.collect.android.R.drawable
+import org.odk.collect.strings.R.string
+
+@RunWith(AndroidJUnit4::class)
+class FormEndTest {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:27]: There are some unused imports here.

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt [hunk 8]
```diff
@@ -0,0 +1,334 @@
...
+
+        composeTestRule
+            .onNodeWithText(application.getString(string.finalize))
+            .performClick()
+
+        verify(onSave).invoke(true)
+    }
+
+    @Test
+    fun `when form should be sent automatically then 'Send' button should be displayed`() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:166]: There is no test for the case when it shouldn't be displayed. `Finalize` has both.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSaveTest.kt [hunk 9]
```diff
@@ -10,15 +10,12 @@ import org.odk.collect.android.support.rules.PageComposeRule
 import org.odk.collect.android.support.rules.TestRuleChain
 
 class FormSaveTest {
-    private val pageComposeRule = PageComposeRule()
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSaveTest.kt:13]: Can we remove this from other tests now, as well, since it exists in `TestRuleChain`?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt (hunk 8 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:166]: I'm not understanding. Could you elaborate on the cases or give me examples of the tests you think are missing?

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSaveTest.kt (hunk 9 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSaveTest.kt:13]: Ah, I thought I'd done that, but it looks like I missed it in a few places.

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt (hunk 8 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:166]: There is
`when finalizing forms is enabled in settings should 'Finalize' button be visible`
and 
`when finalizing forms is disabled in settings should 'Finalize' button be hidden`
so if here you have 
`when form should be sent automatically then 'Send' button should be displayed`
there should also be something like
`when form should not be sent automatically then 'Send' button should be hidden`

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/7153#discussion_r3029985663

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:199]: It looks good. I have nothing against it.

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt (hunk 8 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormEndTest.kt:166]: Ah, I see! I've added extra assertions to the tests that check those buttons to check the other one is not displayed.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
On the end page box with information about edit and "Save as draft" button have gray color but on figma box with information about edit is on light blue background and "Save as draft" button has blue color as on previous collect version, are those expected changes?

**On the left is old end page and on the right new one**

oldendpage
newendpage

**Comment by seadowg** [comment]
@WKobus good spots! I think these are OK: the icon being an "on surface" instead of primary is good because it means that it doesn't present itself as the most important thing on the screen. Same goes for "Save as draft". Let me know if you disagree @alyblenkin and I'll create an issue.

**Comment by alyblenkin** [comment]
Agreed, we made some changes to have stronger contrast between the primary and secondary colours.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10

**Verified cases:**
- #7103, #6713 works as expected
- the hierarchy view: question labels, answers, repeats, groups
- styling and markdown in the hierarchy view
- the end page with all auto send options (set in Collect and in forms)
- the end page and different Access control settings
- the end page in editing finalized
- the end page: light/dark mode, landscape/portrait view, RTL, long names of forms

**Comment by WKobus** [comment]
**tested with success**

Verified on phone and tablet with android 16
