### PR TITLE
Stop repeat dialog closing when app is backgrounded

### LINKED ISSUE #3322: Repeat group dialog disappears after locking phone
This started on the [forum](https://forum.opendatakit.org/t/add-new-prompt-desappears-after-unlocking-the-screen/21564).

#### Software and hardware versions 

Collect v1.23.3

#### Problem description

When prompted to add a repeat group, locking your phone (or navigating to another app) and then returning to the app shows a blank screen without the dialog prompt. You can swipe back and forward to be reprompted.

#### Steps to reproduce the problem

1. Start filling out a blank form with a repeat (an example: [why.xlsx](https://github.com/opendatakit/collect/files/3546228/why.xlsx))
2. When the repeat group prompt ("Add one more group?") appears press the home button or lock the phone
3. Return to the app

You'll just see a blank screen.

#### Expected behavior

I'd expect to still be prompted to add a repeat group (or not). The current situation could be very confusing, especially if you had locked the phone to deal with something else and then come back to it a few minutes later.

#### Other information 

It looks like the offending line of code is [here](https://github.com/opendatakit/collect/blob/4a8d2990cf5788e0b471455d5b192ca1cf68c377/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L2104). It would be intersting to know why we dismiss dialogs and if this weirdness could potentially be addressed with a redesign (I've noticed a discussion happened around this in #809).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #3322. Depends on #3576.

This removes code in `FormEntryActivity` that was dismissing dialogs in `onPause`. As far as I can see there was no reason for that to happen but if someone needed that code speak now!

As well as fixing the issues this PR:
* Removes the use of `showDialog`/`dismissDialog` from `FormEntryActivity`
* Use our `ProgressDialogFragment` for form loading and saving

#### What has been done to verify that this works as intended?

Played around with repeats and backgrounding. I wasn't able to write a test for this as it requires backgrounding the app which we can't do with Espresso and a Robolectric test for `FormEntryActivity` isn't really feasable right now.

#### Why is this the best possible solution? Were any other approaches considered?

As long as the code I deleted wasn't needed in someway then it's certainly the simplest solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue. Good to test repeats, form loading and saving as the dialogs have all had code changes in someway. Would also be good to investigate any other dialog involving scenarios during form entry to check that the code I've removed wasn't needed for something.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Now that #3576 is merged, is this ready for review?

**Comment by seadowg** [comment]
@lognaturel I need to rebase to kill the extra commits as it was dependent on #3576

**Comment by seadowg** [comment]
@lognaturel ok that's good to go now!

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -1640,18 +1636,6 @@ public void showView(View next, AnimationType from) {
         }
     }
 
-    // Hopefully someday we can use managed dialogs when the bugs are fixed
-    /*
-     * Ideally, we'd like to use Android to manage dialogs with onCreateDialog()
-     * and onPrepareDialog(), but dialogs with dynamic content are broken in 1.5
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:1648]: Mm. Nice to see this comment gone.

**Review by lognaturel — APPROVED** [review]
I can't reproduce the issue on `master` anymore so I'm not sure that the `onPause` code was the actual culprit.

That said, it's good that this pulls code out of `FormEntryActivity`, that it moves towards standardizing how dialogs are used in that activity, and that it adds tests. I also can't think of a reason to dismiss all dialogs on pause and like I said in the issue, I suspect it's boilerplate.

@opendatakit/testers this affects any dialog that is shown while filling a form. It would be good to try weird things like backgrounding the app while a large form is loading and coming back to it.

**Comment by seadowg** [comment]
Fixed conflicts!

**Comment by kkrawczyk123** [comment]
**Tested with success!** 
Verified on Androids: 4.2, 4.4, 5.1, 7.1, 9.0 and 10.

**Verified cases:**

add group dialog on a few different forms with repeats:
- extinguish the screen
- minimize an app
- devices rotation
- don't keep activities

remove group dialogs:
- extinguish the screen
- minimize an app

remove this response dialog:
- extinguish the screen
- minimize an app

exit form dialog:
- extinguish the screen
- minimize an app

large form loading dialog:
- minimize an app: dialog restored from the background, the form was able to load
- extinguish the screen: the same result, the form was able to load

spinner widget, select multiple dialog:
- extinguish the screen
- minimize an app

bearing widget dialog:
- extinguish the screen
- minimize an app

range picker integer widget dialog:
- extinguish the screen
- minimize an app

date widgets dialogs:
- extinguish the screen
- minimize an app

rank widget: I have noticed crashes but also on master so I have reported as a separate issue in #3615 . 

sorry, location providers are disabled dialog:
- extinguish the screen
- minimize an app

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
