### PR TITLE
Resolve issue with audio autoplay on first question

### LINKED ISSUE #6819: Audio in the first question isn’t autoplayed
#### ODK Collect version
the store version 2025.2.1, the master version 83b67fd1b39fd41a92f22092d52d2f858f2aa35e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Audio in the first question isn’t autoplayed.
#### Steps to reproduce the problem
1. Open the form.
[audioAutoplay.xlsx.txt](https://github.com/user-attachments/files/21404415/audioAutoplay.xlsx.txt)
audio: https://drive.google.com/drive/u/1/folders/1IeuxQZU8Sw90PAOnTRlMToB3Wp_LuCoN
2. Check if audio is playing
#### Expected behavior
Audio should be autoplayed

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6819

#### Why is this the best possible solution? Were any other approaches considered?
We automatically play audio when navigating forward to a question that contains it. This behavior is controlled by passing the `advancingPage` boolean flag to `ODKView` when creating the view. We pass `false` when navigating back, and `true` when navigating forward, which works well in those cases. However, there is a third case when we create `ODKView`, refreshing the screen - for example, when opening the form and displaying the first question. In this situation, we need to determine if it’s the start of the form in order to pass `true`. This is the approach I implemented in: https://github.com/getodk/collect/pull/6850/commits/cc47a3752d66c17405a5d1c08be4122360b81ce8

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test with audio files that should start automatically (not just those in the first question) to ensure there are no regressions. Other than that, I believe this is a relatively safe change.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form that was attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
I'd be interested in small rework to the structure here: making `AudioPlayer` the one interface that both `FormFillingActivity` and `QuestionWidget` interact with. This feels more fitting given we're now setting it as a "boundary" in our UI tests and would allow us to swap out the implementation for something with a foreground service. To elaborate, instead of `AudioPlayerFactory` would handle the detail around a ViewModel being involved:

```kotlin
class ViewModelAudioPlayerFactory(private val scheduler: Scheduler) : AudioPlayerFactory {
    override fun create(
        activity: ComponentActivity,
        lifecycleOwner: LifecycleOwner
    ): AudioPlayer {
        val factory = AudioClipViewModel.Factory(MediaPlayer::new, scheduler)
        val viewModel = ViewModelProvider(this, factory).get(AudioClipViewModel::class.java)
        return ViewModelAudioPlayer(viewModel, lifecycleOwner)
    }
}
```

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -1131,13 +1126,12 @@ private SwipeHandler.View createView(int event, boolean advancingPage) {
     private ODKView createODKView(boolean advancingPage, FormEntryPrompt[] prompts, FormEntryCaption[] groups) {
         odkViewLifecycle = new ControllableLifecyleOwner();
         odkViewLifecycle.start();
+        AudioPlayer audioPlayer = audioPlayerFactory.create(this, odkViewLifecycle);
+        audioPlayer.isLoading().observe(this, (isLoading) -> {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Does this need to observe with the `odkViewLifecycle` instead?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: It wasn't using it https://github.com/getodk/collect/pull/6850/files#diff-0bf62cb249d6cb5715c94f28798547065602dc39e890993332bb6ed5fb42d88cL638, but yeah, I think it can now.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 16

**Verified cases:**
- Issue #6819 does not occur
- Autoplay in selects
- Autoplay with missing audio file 
- Repeats with autoplay
- Autoplay with big audio file
- Regression check on audio
- Required audio questions

**Comment by srujner** [comment]
**Tested with success**

Verified on device with Android 14

**Comment by dbemke** [comment]
**Tested with success**

Verified on device with Android 10
