### PR TITLE
Try using the package manager  to get a launch intent for external apps, support string uris for binary external widgets

### LINKED ISSUE #4194: External app launch features only works for apps that specify the DEFAULT category in their intent filter
#### Software and hardware versions 
Collect v1.28 and previous

#### Problem description
External app launch features only works for apps that specify the DEFAULT category in their LAUNCHER intent filter.

#### Steps to reproduce the problem
Try to launch one of the apps mentioned in https://forum.getodk.org/t/launch-a-scanner-app-and-attach-a-pdf-from-collect/19061 from a form. For example, for https://printerplus.rcti.es/:

type | name | label | appearance
-- | -- | -- | --
integer | test | Test | ex:es.rcti.printerplus()

#### Expected behavior
The application should launch.

#### Other information 
https://stackoverflow.com/questions/54492708/why-is-no-activity-found-to-handle-intent/54552362#54552362

https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30/62856745#62856745

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #4194

#### What has been done to verify that this works as intended?
Tried launching external applications that were previously failing with both a single question and in an intent field list.

#### Why is this the best possible solution? Were any other approaches considered?
I don't fully understand the intent rules. From my reading, it seems that trying both `new Intent(intentName)` and `getLaunchIntentForPackage(intentName)` gives us the biggest chance of success. I couldn't find any other good alternatives.

I also broadened the allowable types for binary widgets. I realized that in our initial spec we weren't explicit about types and so users might be providing the URIs as strings. The change here is the simplest way I can find to support both.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Since these are additive, the regression risk is low. Only binary widgets and binary questions in intent field-lists are at any risk.

#### Do we need any specific form for testing your changes? If so, please attach one.
See forum post linked from issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java [hunk 1]
```diff
@@ -405,48 +405,49 @@ private void addIntentLaunchButton(Context context, FormEntryPrompt[] questionPr
...
-                                    break;
-                            }
+        launchIntentButton.setOnClickListener(view -> {
+            String intentName = ExternalAppsUtils.extractIntentName(intentString);
+            Map<String, String> parameters = ExternalAppsUtils.extractParameters(intentString);
+
+            Intent i = new Intent(intentName);
+            if (i.resolveActivity(Collect.getInstance().getPackageManager()) == null) {
+                i = Collect.getInstance().getPackageManager().getLaunchIntentForPackage(intentName);
+                i.setFlags(0);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: I can't remember the details of why this is needed but can try to pull it up again if needed. There are flags set by default when doing `getLaunchIntentForPackage` and they suppress something, maybe returning a result.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: I tested the fix without the flag (not here but using external widgets) and it seems to work so would be good if you could double check it.

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java [hunk 2]
```diff
@@ -405,48 +405,49 @@ private void addIntentLaunchButton(Context context, FormEntryPrompt[] questionPr
...
-                                            (Serializable) value);
-                                    break;
-                            }
+        launchIntentButton.setOnClickListener(view -> {
+            String intentName = ExternalAppsUtils.extractIntentName(intentString);
+            Map<String, String> parameters = ExternalAppsUtils.extractParameters(intentString);
+
+            Intent i = new Intent(intentName);
+            if (i.resolveActivity(Collect.getInstance().getPackageManager()) == null) {
+                i = Collect.getInstance().getPackageManager().getLaunchIntentForPackage(intentName);
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: getLaunchIntentForPackage() might return null so wee need some null check now I think.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: YES, thank you.

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: Now I remember that at some point I got into a state where the OpenRDT app was immediately returning its result rather than first going through its UI flow and then returning. That led me to [this Stackoverflow post](https://stackoverflow.com/a/24312398/137744). The OpenRDT examples I was sent (not public, unfortunately) do use `setFlags(0)`.

>  getLaunchIntentForPackage("com.your.package.here") would create an intent with Intent.FLAG_ACTIVITY_NEW_TASK added by default, so call: in.setFlags(0);

Always creating the target activity and avoiding the `FLAG_ACTIVITY_NEW_TASK` flag seems like the way to go to me. There are differences in Android versions with how the other launch modes work and their behavior will also depend on whether or not an activity is already in memory.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: Is it just me or are the docs around this particularly bad?

**Comment by lognaturel** [comment]
Thanks for the review, @grzesiek2010, and especially for catching the null issue. I verified that trying to launch an app not on the device now gives the expected toast instead of crashing.

I tried to explain the flags both in https://github.com/getodk/collect/pull/4208#discussion_r520016609 and in a code comment. Let me know if you still have questions.

**Comment by lognaturel** [comment]
Another thing. It would be good to have tests for things like if an implicit intent can't be resolved, the explicit intent path is attempted or if nothing can be resolved, the toast is shown. I'm hoping that when you come back to this to add single-question external binary functionality you'll be able to consolidate some of the code and add some testing, @grzesiek2010. It feels like things are still going to move with that change so I didn't want to spend too much time on it.

File: collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java]: Ok this is confusing but makes more sense now thanks!

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases:
- launch HP Smart app
- launch Printer+ app
- launch Tacho Center app
- jump from hierarchy
- open saved form
- rotation
- minimization
- RTL language
- light / dark mode

**Comment by kkrawczyk123** [comment]
Verified on Androids 5.1, 7.1 and 9.0.
I was not able to install HP Smart app as it supports Androids 7+.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
