### PR TITLE
Don't rotate images for display, instead preserve and use EXIF tag

### LINKED ISSUE #4571: Incorrect rotation or EXIF orientation of portrait photos captured with collect app
#### Software and hardware versions 
ODK Collect v1.30.1
Android 9
Xiaomi Mi A1

#### Problem description

Photos captured in portrait format with ODK Collect are not saved or rendred in the right direction. 

Portrait format with ODK Collect:
Portrait_ODK_Collect

Portrait format with camera app:
Portrait_Camera app

Landscape format with ODK Collect:
Landscape_ODK_Collect

Landscape format with camera app:
Landscape_Camera app

#### Steps to reproduce the problem

1. Create a simple form containing a photo uploader
2. Using ODK Collect, take a photo on a device that produces an EXIF Orientation tag for portrait photos and upload it via the form
3. Download the photo from KoBoToolbox or access the file directly in the folder : "Internal/Android/data/org.odk.collect.android/files/instances/<instance directory>/" 
4. Open on any system that understands EXIF Orientation and notice that landscape photos render correctly, but portrait photos are sideways
5. Compare with the same photo taken directly with the camera app of the device where portrait photos are displayed vertical as expected

#### Other information 

This issue was initially posted on : 
https://github.com/kobotoolbox/kobocat/issues/707

### PR DESCRIPTION
**Pull request by abhishekab**
- Remove rotation methods from ImageConvertor
  (Don't apply explicit rotation if EXIF rotation present)
- Copy image after applying EXIF rotation for Annotate Widget
- Remove ImageConvertor rotate tests
- Add FileUtils rotate tests

Closes #4571 

#### What has been done to verify that this works as intended?
           
Manual Testing done. And unit tests added
#### Why is this the best possible solution? Were any other approaches considered?
There were two main approaches to solve this:
- Remove the explicit bitmap transformation which rotates the image, and preserve EXIF orientation. And make the ImageView displaying the image in ImageWidget sensitive to EXIF just for presentation.

- Let the explicit bitmap transformation as it is and let it rotate the image, and at the same time remove the orientation from EXIF before saving the transformed image.
Got inclined toward the former one, as using EXIF as it's supposed to be used and not rewriting the image seemed more apt.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
N/A
#### Do we need any specific form for testing your changes? If so, please attach one.
N/A
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
N/A

#### Before submitting this PR, please make sure you have:

- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@abhishekab sorry for the delay in a review. We're putting together a Collect release at the moment, but after that someone should be able to take a look!

**Comment by abhishekab** [comment]
No worries :)

File: collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java [hunk 1]
```diff
@@ -69,6 +77,7 @@
     private final MediaUtils mediaUtils;
     protected final String tmpImageFilePath;
 
+
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java]: Please remove this doubled empty line.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 2]
```diff
@@ -174,6 +180,51 @@ public static Bitmap getBitmapScaledToDisplay(File file, int screenHeight, int s
         return bitmap;
     }
 
+
+    /**
+     * While copying the file, apply the exif rotation of sourceFile to destinationFile
+     * so that sourceFile with EXIF has same orientation as destinationFile without EXIF
+     */
+    public static void copyImageAndApplyExifRotation(File sourceFile, File destFile) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: `FileUtils` is growing maybe it would be better to have `ImageFileUtils` for utility methods that operate only on images and then `GeneralFileUtils`? We don't need to add it here but maybe in a separate pr.

File: collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java [hunk 3]
```diff
@@ -419,7 +338,7 @@ public void scaleImageToNewWidthTest() {
     }
 
     @Test
-    public void keepExifTest1AfterScaleAndRotation() {
+    public void keepExifTest1AfterScaling() {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java]: A better name would be just `keepExifAfterScaling`

File: collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java [hunk 4]
```diff
@@ -123,45 +117,6 @@ public void whenReadOnlyOverrideOptionIsUsed_shouldAllClickableElementsBeDisable
         assertThat(getSpyWidget().annotateButton.getVisibility(), is(View.GONE));
     }
 
-    @Test
-    public void whenPromptHasDefaultAnswer_showsInImageView() throws Exception {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: Why did you remove these tests?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java (hunk 4 above)
Comment (abhishek-wiai) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: So these tests were relevant when the answer images were being loaded synchronously via code, now that we are using Glide to load the image into imageView, I am not sure if we need them.

Comment (abhishekab) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: So these tests were relevant when the answer images were being loaded synchronously via code, now that we are using Glide to load the image into imageView, I am not sure if we need them.

File: collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java (hunk 3 above)
Comment (abhishekab) [reply collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java]: Ah ok, I just reused the naming convention how it was. Will fix this

File: collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java (hunk 1 above)
Comment (abhishekab) [reply collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java]: Will do.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 2 above)
Comment (abhishekab) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Agreed. Will create a separate issue followed by a PR after this one.

**Comment by seadowg** [comment]
@abhishekab are you still planning to work on this?

**Comment by abhishekab** [comment]
yes, yes. Sorry was a little occupied will update the PR in couple of days

**Comment by seadowg** [comment]
@abhishekab no worries! Thanks so much for looking at it.

File: collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: Those tests were added to verify that adding [default answers](https://docs.getodk.org/form-logic/#static-defaults) (even like in this case default media answers works well) and the fact that we use Glide or not has nothing to do here. So I think we should keep them.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
Some relevant tests were removed.

**Comment by grzesiek2010** [comment]
@abhishekab what do you think about those tests? As I said I am pretty sure they are still needed.

File: collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java (hunk 4 above)
Comment (abhishekab) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: Sorry for my limited understanding, but isn't the getFile() function in BaseImageWidget responsible for returning the file path for default answer, do we need to test this explicitly in an integrated manner to check that the default image is loaded into the image view in this scenario?

Comment (abhishekab) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: If yes, may be if you could guide me if I should explore [this](https://lcdsmao.dev/synchronize-glide-loading-in-test-with-idlingresource/) to synchronize loading to ensure the test passes, or if you can suggest any other methodology

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: > but isn't the getFile() function in BaseImageWidget responsible for returning the file path for default answer

yes but we need test to make sure the image is really displayed.

> If yes, may be if you could guide me if I should explore this to synchronize loading to ensure the test passes, or if you can suggest any other methodology

ahh so that's the issue... maybe you could try to implement abstraction something like described here https://stackoverflow.com/a/46286760
the goal would be to use Glide in production code but in tests load images like before.

**Comment by seadowg** [comment]
Going to close this for the moment but feel free to reopen if you get a chance to come back to it @abhishekab!

**Comment by grzesiek2010** [comment]
@abhishekab could you reopen the pull request but keep the fix only and remove the part with switching to Glide what caused problems with our tests? If you don't have time let us know.

File: collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java:127]: I reverted that change with using Glide for now and added the tests back.

**Comment by grzesiek2010** [comment]
@seadowg please take a look.

File: collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java [hunk 5]
```diff
@@ -461,6 +380,18 @@ public void keepExifTest1AfterScaleAndRotation() {
         }
     }
 
+    @Test
+    public void verifyNoRotationAppliedForExifRotation() {
+        Map<String, String> attributes = new HashMap<>();
+        attributes.put(ExifInterface.TAG_ORIENTATION, String.valueOf(ExifInterface.ORIENTATION_ROTATE_90));
+        saveTestBitmap(3000, 4000, attributes);
+        ImageConverter.execute(testImagePath, getTestImageWidget(), Collect.getInstance(), IMAGE_SIZE_ORIGINAL);
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java]: We can use `ApplicationProvier.getApplication()` here instead of `Collect.getInstance()`

File: collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+    }
+
+    @Test
+    fun copyAndRotateImageOneEighty() {
+        attributes[ExifInterface.TAG_ORIENTATION] = ExifInterface.ORIENTATION_ROTATE_180.toString()
+        saveTestBitmapToFile(sourceFile.absolutePath, 3000, 4000, attributes)
+        FileUtils.copyImageAndApplyExifRotation(sourceFile, destinationFile)
+        val image = FileUtils.getBitmap(destinationFile.absolutePath, BitmapFactory.Options())
+
+        assertEquals(3000, image.width)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt]: This test still passes if I change the `ORIENTATION_ROTATE_180` branch in the implementation to perform a rotation of `0` - 180 is annoying as the image dimensions end up the same. We technically have a similar problem for 90 and 270 as they could be flipped and the tests would still pass. 

Are we able to verify these by creating a Bitmap with a single filled pixel and checking where it ends up? I can imagine that might not be worth it wanted to discuss. Maybe there is a better way that you can think of.

File: collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+import org.junit.Assert.assertEquals
+import org.junit.Before
+import org.junit.Test
+import org.junit.runner.RunWith
+import timber.log.Timber
+import java.io.File
+import java.io.IOException
+
+@RunWith(AndroidJUnit4::class)
+class CopyImageAndApplyExifRotationTest {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt]: I think we should have these tests in `FileUtilsTest` or in a file prefixed with `FileUtils`. Otherwise, tools like IntelliJ's "switch to test" won't be able to find the test from the implementation and vice versa.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Comment by seadowg** [comment]
Marking this as "needs testing" as all requested changes are in tests.

File: collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java]: Done.

File: collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt]: I agree and I improved that test. It required moving it to `androidTest` because when you create/open bitmaps in unit test it returns empty bitmaps (the size is correct but its empty/transparent).

File: collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt (hunk 7 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/CopyImageAndApplyExifRotationTest.kt]: I factored out `ImageUtils` class because `FileUtils` was big already, then I rename that class to `ImageUtilsTest` and merged with `BitmapScaledToDisplayTest` which also tested only methods from the same class.

**Review by seadowg — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@kkrawczyk123 I was able to find a camera app whcih you can use to reproduce the issue: https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree&gl=PL

Unfortunately there is one problem... images are saved correctly in the storage but they are displayed incorrectly (rotated) in Collect. It would be confusing for users that use app like the one mentioned above (that provides orientation attribute in exif) so I think we need to improve the solution. Seems like using glide is a must here.

**Comment by grzesiek2010** [comment]
Ok I fixed that problem so it's ready for testing. I need to disable a few tests that were broken because of Glide and I will try to bring them back after merging https://github.com/getodk/collect/pull/4957 or even as a part of that pr since that pr introduces a new module fro loading images and doing that should be easier then.

**Comment by seadowg** [comment]
@grzesiek2010 what's motivating the change to Glide here? This probably need re-reviewed right?

**Comment by grzesiek2010** [comment]
> what's motivating the change to Glide here

Glide handles orientations in EXIF correctly without this images displayed in Collect might be rotated, saved correctly but rotated in our app.

> what's motivating the change to Glide here

It's not a big change but if you want yeah but just 2 last commits.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 8.1 and 5.1

@grzesiek2010 thanks for sharing this app, it helped me with reproducing the issue!

Verified cases:
- take a picture, verify image attached to an instance
- choose image, verify image attached to an instance
- check orientation using Photo exif app
- image, annotate, selfie widgets
- display images in collect
- add big image
- add small image 
- add image from internal storage
- add image from Google Drive

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with success!**
Verified on Androids 10 and 11

**Review by grzesiek2010 — APPROVED** [review]
