### PR TITLE
Fixed toast on Android 8.1 and refactored the code using ToastUtils class

### LINKED ISSUE #2100: Constraint and required messages are almost invisible on Android 8.1
#### Software and hardware versions 
Collect v1.14.0, Android v8.1.0, Nexus 5X

#### Problem description
Constraint and required messages appear on a very light background with white font, making them close to invisible. See screenshot:

image

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2100

#### What has been done to verify that this works as intended?
I tested toasts on Android 8.1 and older versions.

#### Why is this the best possible solution? Were any other approaches considered?
It's the best solution because it keeps default Android behavior and now all toast are created using `ToastUtils` class.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java [hunk 1]
```diff
@@ -1,37 +1,61 @@
...
+    public static void showLongToastCentered(int messageResource) {
+        showToast(messageResource, Toast.LENGTH_LONG, true);
     }
 
-    private static void showToast(String message, int duration) {
-        Toast.makeText(Collect.getInstance(), message, duration).show();
+    private static void showToast(String message, int duration, boolean centered) {
+        Toast toast = Toast.makeText(Collect.getInstance(), message, duration);
+        if (centered) {
+            toast.setGravity(Gravity.CENTER, 0, 0);
```
Comment (huangyz0918) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java]: Try adding this to modify the font size:
```Java
    ViewGroup group = (ViewGroup) toast.getView();
    TextView message = (TextView) group.getChildAt(0);
    message.setTextSize(**size you want**);
```
And set this a parameter in method `showToast()`, setting a default value is good in case we don’t want to change the text size.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java [hunk 2]
```diff
@@ -1,37 +1,61 @@
...
-        showToast(message, Toast.LENGTH_LONG);
+        showToast(message, Toast.LENGTH_LONG, false);
     }
 
     public static void showLongToast(int messageResource) {
-        showToast(messageResource, Toast.LENGTH_LONG);
+        showToast(messageResource, Toast.LENGTH_LONG, false);
+    }
+
+    public static void showShortToastCentered(String message) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java]: What's special about these isn't so much that they're horizontally centered which is what "centered" implies but that they're vertically centered. How about calling these `showxxxInMiddle`.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java]: Agreed that the text should be larger for the toasts that happen in the form filling context (middle toasts).

**Review by lognaturel — COMMENTED** [review]
Couple of small things to update in line, @grzesiek2010. When you get those done, please let @huangyz0918 know. @huangyz0918 if you have a moment to review and tag with "needs testing" once the behavior is right, that would be wonderful! (I'll be asleep by the time you both get up. ODK is a 24hr operation!! 🕚 🕦 🕐)

**Comment by huangyz0918** [comment]
Fine, thank you @grzesiek2010 and @lognaturel  ! I will close PR #2103 .
I'm preparing for my TOEFL exam but I'll certainly do a review. So please `ping` me when you are ready @grzesiek2010

**Comment by lognaturel** [comment]
Good luck with your studying, @huangyz0918! Sending you lots of good English vibes. 😊

**Comment by grzesiek2010** [comment]
@lognaturel @huangyz0918 I think it's ready.

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs testing"

**Review by huangyz0918 — APPROVED** [review]

**Review by lognaturel — COMMENTED** [review]
I'm happy to see that `showToastInMiddle` has become its own method. In general, I do think it's best to avoid boolean flags with special cases.

Why not make the parameters `messageResource` and `duration`? That seems clearer than passing in the toast.

**Comment by grzesiek2010** [comment]
> Why not make the parameters messageResource and duration? That seems clearer than passing in the toast.

sorry but I don't understand your idea/question. Could you explain?

File: collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java [hunk 3]
```diff
@@ -34,4 +37,29 @@ private static void showToast(String message, int duration) {
...
+    public static void showShortToastInMiddle(String message) {
+        showToastInMiddle(Toast.makeText(Collect.getInstance(), message, Toast.LENGTH_SHORT));
+    }
+
+    @SuppressLint("ShowToast")
+    public static void showLongToastInMiddle(int messageResource) {
+        showToastInMiddle(Toast.makeText(Collect.getInstance(), Collect.getInstance().getString(messageResource), Toast.LENGTH_LONG));
+    }
+
+    private static void showToastInMiddle(Toast toast) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java]: Getting a `Toast` in here is unexpected. I was suggesting 

```java
    public static void showShortToastInMiddle(int messageResource) {
        showToastInMiddle(Collect.getInstance().getString(messageResource), Toast.LENGTH_SHORT);
    }

    public static void showShortToastInMiddle(String message) {
        showToastInMiddle(message, Toast.LENGTH_SHORT);
    }

    public static void showLongToastInMiddle(int messageResource) {
        showToastInMiddle(Collect.getInstance().getString(messageResource), Toast.LENGTH_LONG);
    }

    private static void showToastInMiddle(String message, int duration) {
        Toast toast = Toast.makeText(Collect.getInstance(), message, duration);
        ViewGroup group = (ViewGroup) toast.getView();
        TextView messageTextView = (TextView) group.getChildAt(0);
        messageTextView.setTextSize(21);
        messageTextView.setGravity(Gravity.CENTER);

        toast.setGravity(Gravity.CENTER, 0, 0);
        toast.show();
    }
```

That way you don't need to suppress a lint check and the method name better matches what it does. You also have less nesting and shorter lines which makes the code overall easier to understand.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java]: Ok I see. Thanks for your explanation!

**Review by lognaturel — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
### Tested with success! 
Verified on 8.1 and also checked on 4.1, 4.2, 4.4, 6.0 and 7.0 if there is any regression.

@opendatakit-bot unlabel "needs testing"
