### PR TITLE
Do not log it as error if uri can not be accessed on Huawei devices

### LINKED ISSUE #5012: IllegalArgumentException: Huawei devices are unsupported for Android N
#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/80e757abd296ef6a142434027b8af268?time=last-seven-days&versions=v2022.1.0%20(4359)&types=crash&sessionEventKey=61F79C340127000108A370A69753A00F_1637728606934207344

```
Fatal Exception: java.lang.IllegalArgumentException: Huawei devices are unsupported for Android N
       at org.odk.collect.android.utilities.ContentUriProvider.getUriForFile(ContentUriProvider.java:51)
       at org.odk.collect.android.utilities.MediaUtils.openFile(MediaUtils.kt:51)
       at org.odk.collect.android.widgets.BaseImageWidget$ViewImageClickHandler.clickImage(BaseImageWidget.java:207)
       at org.odk.collect.android.widgets.BaseImageWidget$1.lambda$onResourceReady$0(BaseImageWidget.java:163)
       at org.odk.collect.android.widgets.BaseImageWidget$1.$r8$lambda$zVSJ-WvlKfbhAxcFToevCnSMVlE(BaseImageWidget.java)
       at org.odk.collect.android.widgets.BaseImageWidget$1$$InternalSyntheticLambda$0$34ac18033ab6bf75fe5d4233ae7f4f0e4177bd81f2ed02e415f588461ef91aed$0.onClick(BaseImageWidget.java:2)
       at android.view.View.performClick(View.java:6367)
       at android.view.View$PerformClick.run(View.java:25040)
       at android.os.Handler.handleCallback(Handler.java:795)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:166)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5012

#### What has been done to verify that this works as intended?
I've improved test and reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
It looks like we can't fix that problem with some Huawei devices so I decided to at least improve the code a bit and stop lgging it as error plus display a toast instead of just throwing en exception.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt [hunk 1]
```diff
@@ -54,6 +54,11 @@ class MediaUtils(private val intentLauncher: IntentLauncher, private val content
             file
         )
 
+        if (contentUri == null) {
+            ToastUtils.showLongToast(context, "Can't' open file!")
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt]: There's an extra ' in "Can't'". How about giving a little more detail? Maybe "Can't open file. If you are on a Huawei device, this is expected and will not be fixed."

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt]: Ok fixed.

**Review by lognaturel — APPROVED** [review]
