### PR TITLE
Fix reading form metadata in forms containing multiple meta sections

### LINKED ISSUE #7138: Saved forms with entities ignore dynamic instance names defined by the instance_name column in the settings sheet
#### Problem description
When a form contains entities, saved forms display the form title instead of the instance name defined using the `instance_name` column in the settings sheet.

#### Steps to reproduce the problem
Test the forms attached in https://forum.getodk.org/t/entity-submission-draft-shown-with-form-title-rather-than-instance-name-in-collect/57858/1

#### Expected behavior
Saved forms should display the dynamic instance name defined in the instance_name column in the settings sheet.

#### Other information 
The issue was originally reported on the forum: https://forum.getodk.org/t/entity-submission-draft-shown-with-form-title-rather-than-instance-name-in-collect/57858/1

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #7138 

#### Why is this the best possible solution? Were any other approaches considered?
This ensures the correct for metadata is always read from the top-level `<meta>`, avoiding using other `<meta> `sections that only contain entity information.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should only fix the issue. I can't think of any bigger risk here.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form from https://forum.getodk.org/t/entity-submission-draft-shown-with-form-title-rather-than-instance-name-in-collect/57858

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java [hunk 1]
```diff
@@ -1010,76 +1010,41 @@ public ByteArrayPayload getSubmissionXml() throws IOException {
...
-        return null;
-    }
-
     public InstanceMetadata getSubmissionMetadata() {
         FormDef formDef = formEntryController.getModel().getForm();
         TreeElement rootElement = formDef.getInstance().getRoot();
-
-        TreeElement trueSubmissionElement;
-        // Determine the information about the submission...
-        SubmissionProfile p = formDef.getSubmissionProfile();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: Was this needed here in any way? I can’t really imagine a use case, but maybe I’m missing something.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: To make the change here very explicit, Collect previously allowed [the "meta block"](https://getodk.github.io/xforms-spec/#metadata) to be defined anywhere within [the primary instance](https://getodk.github.io/xforms-spec/#primary-instance). This PR changes that so that it's only supported if it is a direct child of the primary instance. Is that your understanding @grzesiek2010?

As far as I can see, the spec is actually a little ambiguous on where the meta block should live. All the examples show it as a direct child, but that requirement isn't really stated explicitly. The closes we get to that is probably:

> The primary instance also includes a special type of nodes for metadata inside the <meta> block. See the [Metadata](https://getodk.github.io/xforms-spec/#metadata) section

"contains" isn't really specific enough to make this change, but I suspect the intention in the spec is that the meta block should be a direct child. I'd like to get second opinions from @lindsay-stevens or @lognaturel.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: > This PR changes that so that it's only supported if it is a direct child of the primary instance. Is that your understanding @grzesiek2010?

Kind of, I mean yes, and that's why I got rid of `findDepthFirst` function, but here the question was more about using `SubmissionProfile`. Whether it was needed for something or not.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: > As far as I can see, the spec is actually a little ambiguous on where the meta block should live. All the examples show it as a direct child, but that requirement isn't really stated explicitly. 

This PR is not the first where we assume the main meta block (with `instanceId`, `instanceName`, `audit`) is the direct child, see:
https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formmanagement/finalization/EditedFormFinalizationProcessor.kt#L23

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: Good point! Ok so if there is a problem with that, it will already exist. I'd still like to hear from others (so we can at least make the spec clearer), but this is good to go.

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: Very interesting, I'd never noticed that ambiguity. I assume the original intent was indeed the direct `meta` child, that's certainly an important assumption for the whole way the multiple Entity declaration spec works. I think we should make the spec more specific.

Comment (lindsay-stevens) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: I think pyxform is currently doing as expected but I've filed https://github.com/XLSForm/pyxform/issues/831 to improve test coverage. The spec examples show the main meta element being a child of the primary data instance root element (usually `data`), but it wouldn't hurt to also say that in the text, and perhaps also that any other meta elements (expected for entities) must only have entities in them (though `meta` isn't currently a reserved name so that might be a stretch).

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:1038]: Great! I can get a PR up for the spec then.

**Comment by dbemke** [comment]
I reproduced the issue using the store version of Collect (2026.1.1) and forms from the forum issue. There's a difference in results when I use test.getodk.cloud and staging.getodk.cloud
(staging on the left; test on the right)
stagingVStest
 user "instancename"
 https://test.getodk.cloud/projects/629/app-users
 https://staging.getodk.cloud/projects/215/app-users
 Should it be tested with the newest changes on Central (staging) or the test instance or both?

**Comment by seadowg** [comment]
@dbemke it shouldn't matter, but I'd definitely not expect the behaviour you're seeing on test. What are the reproduction steps to get in that state with test.getodk.cloud?

**Comment by dbemke** [comment]
> What are the reproduction steps to get in that state with test.getodk.cloud?

**Steps to reproduce:**
1. Fill forms (form 1 and form2).
2. Save it as drafts.

There are links (above) to user "instancename" both on staging and test.

**Comment by grzesiek2010** [comment]
`test.getodk.cloud` has xml with the format that allows reproducing the issue:

```
<instance>
                <data id="formtest2" version="20260314170716">
                    <today/>
                    <page1>
                        <lbl1/>
                        <lbl2/>
                        <meta>
                            <entity dataset="entity_test" create="1" id="">
                                <label/>
                            </entity>
                        </meta>
                    </page1>
                    <meta>
                        <instanceID/>
                        <instanceName/>
                    </meta>
                </data>
            </instance>
```

but `staging.getodk.cloud` doesn't:

```
            <instance>
                <data id="formtest2" version="20260314170716">
                    <today/>
                    <page1>
                        <lbl1/>
                        <lbl2/>
                    </page1>
                    <meta>
                        <entity dataset="entity_test" create="1" id="">
                            <label/>
                        </entity>
                        <instanceID/>
                        <instanceName/>
                    </meta>
                </data>
            </instance>
```

I don't know what changes these two servers contain, but it's ok to test this PR only with `test.getodk.cloud`.

**Comment by seadowg** [comment]
@grzesiek2010 @dbemke ah ok my guess is that it's changes to XLSForm that generate a different XForm from the example. @grzesiek2010 could you share the full XForm that should be used for testing just so there's no confusion? 

@dbemke it'd be worth double-checking that this is indeed an expected change by downloading the XForm you get from the example `.xlsx` (from the forum) when uploading to each version of Central, and share them with the Central team on Slack.

**Comment by grzesiek2010** [comment]
> could you share the full XForm that should be used for testing just so there's no confusion?

I've downloaded the one from `test.getodk.cloud`: 
[formtest2.xml](https://github.com/user-attachments/files/26084898/formtest2.xml)

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16

- Issue #7138 does not occur
- Calculation for instance name inside and outside group
- Comparing results between test and staging servers

**Comment by dbemke** [comment]
**Tested with success**

Verified on Android 10
