### PR TITLE
Get blank forms from Google Drive using API v3

### LINKED ISSUE #650: Get Blank Form with Google Sheets should allow user to add account
#### Software and hardware versions 
Collect v1.4.16-104-g14bd3426
 
#### Problem description
When no Google account is selected in general settings and the protocol is "Google Drive, Google Sheets", tapping on "Get Blank Form" pops up an informational dialog rather than allowing the user to add an account as when sending a form.

#### Steps to reproduce the problem
1. Change the protocol to "Google Drive, Google Sheets", don't select an account
1. Tap "Get Blank Form"

#### Expected behavior
1. Change the protocol to "Google Drive, Google Sheets", don't select an account
1. Fill out and finalize any form
1. Tap "Send Finalized Form"
1. Select a form
1. Tap "Send Selected"
You will be given an opportunity to configure a Google account.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
In continuation of #713
Also fixes #650

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
Before we had to click on "My Drive" button to see files now I can see all files automatically is it an 
expected behaviour?

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Earlier, we used to click the button to get the drive files even after going into the `Get blank forms`. So I called the api as soon as the user enters the activity, saving one click of the user whenever trying to reach this section of the app. 
I'll revert it back if this doesn't seems ok.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 1]
```diff
@@ -56,104 +59,83 @@
...
 import java.util.Iterator;
 import java.util.List;
 import java.util.Stack;
 
-public class GoogleDriveActivity extends ListActivity implements GoogleApiClient.OnConnectionFailedListener,
-        TaskListener, GoogleDriveFormDownloadListener {
+import pub.devrel.easypermissions.AfterPermissionGranted;
+import pub.devrel.easypermissions.EasyPermissions;
+
+//import com.google.api.services.drive.model.ParentList;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: This can simply be removed.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 2]
```diff
@@ -315,14 +244,145 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
...
+        getResultsFromApi();
+    }
+
+    /*
+     * Attempt to call the API, after verifying that all the preconditions are
+     * satisfied. The preconditions are: Google Play Services installed, an
+     * account was selected and the device currently has online access. If any
+     * of the preconditions are not satisfied, the app will prompt the user as
+     * appropriate.
+     */
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Would be good to have a quick link to https://developers.google.com/drive/v3/web/quickstart/android like you put in other places.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 3]
```diff
@@ -526,82 +618,238 @@ public Object onRetainNonConfigurationInstance() {
...
+        Collect.getInstance().getActivityLogger().logOnStart(this);
+    }
+
+    @Override
+    protected void onStop() {
+        Collect.getInstance().getActivityLogger().logOnStop(this);
+        super.onStop();
+    }
+
+    private boolean testNetwork() {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: `isDeviceOnline` appears to be a slightly cleaner implementation of the same thing so this method and corresponding calls should be replaced.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 4]
```diff
@@ -526,82 +618,238 @@ public Object onRetainNonConfigurationInstance() {
...
+            try {
+                rootId = mDriveService.files()
+                        .get("root")
+                        .setFields("id")
+                        .execute().getId();
+            } catch (UserRecoverableAuthIOException e) {
+                startActivityForResult(e.getIntent(), COMPLETE_AUTHORIZATION_REQUEST_CODE);
+                return null;
+            } catch (IOException e) {
+                e.printStackTrace();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: We are trying to move away from using `e.printStackTrace()` since it always gets lost. Can you please replace it with `Log.e` throughout the code (and it will be in turned replaced by `Timber.e` soon).

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 5]
```diff
@@ -315,14 +244,145 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
...
+                // Start a dialog from which the user can choose an account
+                startActivityForResult(
+                        mCredential.newChooseAccountIntent(),
+                        GoogleSheetsTask.REQUEST_ACCOUNT_PICKER);
+            }
+        } else {
+            // Request the GET_ACCOUNTS permission via a user dialog
+            EasyPermissions.requestPermissions(
+                    this,
+                    "This app needs to access your Google account (via Contacts).",
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: I think this is going to end up in the user interface, right? It should be in `strings.xml` so it can be translated. I also think the message should be a bit more specific. Perhaps "ODK Collect needs access to your Google account to get blank forms and submit filled forms."

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 6]
```diff
@@ -525,14 +525,18 @@ public void authRequest(Uri url, HashMap<String, String> doneSoFar) {
...
-            GoogleSheetsAbstractUploader<Long, Integer, HashMap<String, String>> {
+            GoogleSheetsAbstractUploader {
 
         GoogleSheetsInstanceUploaderTask(GoogleAccountCredential credential) {
             HttpTransport transport = AndroidHttp.newCompatibleTransport();
             JsonFactory jsonFactory = JacksonFactory.getDefaultInstance();
-            mService = new com.google.api.services.sheets.v4.Sheets.Builder(
+            mSheetsService = new com.google.api.services.sheets.v4.Sheets.Builder(
+                    transport, jsonFactory, credential)
+                    .setApplicationName("ODK-Collect-Sheets")
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: These application names are used in the User Agent header, I believe. I think it makes sense to have a consistent one for all services. Was there a particular reason you used different ones?

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 7]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                String[] selectionArgs = {
+                        filename
+                };
+                Cursor c = Collect.getInstance().getContentResolver()
+                        .query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, null, selection
+                                , selectionArgs, null);
+                if (c.getCount() != 1) {
+                    c.close();
+                    try {
+                        throw new FileNotFoundException(drive_fail + Collect.getInstance()
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I realize you just followed the structure of the previous code but I think `drive_fail` can and should be removed completely from here and from GoogleDriveActivity. It breaks translations and doesn't add any meaningful information.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 8]
```diff
@@ -56,104 +59,83 @@
...
+    private static final String PATH_KEY = "path";
+    private static final String DRIVE_ITEMS_KEY = "drive_list";
+    private static final String PARENT_KEY = "parent";
+    private static final String ALERT_MSG_KEY = "alertmsg";
+    private static final String ALERT_SHOWING_KEY = "alertshowing";
+    private static final String ROOT_KEY = "root";
+    private static final String FILE_LIST_KEY = "fileList";
+    private static final String PARENT_ID_KEY = "parentId";
+    private static final String CURRENT_ID_KEY = "currentDir";
+    private static final String drive_fail = "Media Error: ";
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: This and the following constant are never used.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 9]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
             }
         }
 
-        // if we have any photos to upload,
-        // get the picasa album or create a new one
-        // then upload the photos
+
+        /*  # NOTE #
+         *  Media files are uploaded to Google Drive of user
+         *  All media files are currently saved under folder "odk-uploads"
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: `Open Data Kit/Submissions/formID/`

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 10]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                    try {
+                        throw new FileNotFoundException(drive_fail + Collect.getInstance()
+                                .getString(R.string.media_upload_error, filename));
+                    } catch (FileNotFoundException e) {
+                        e.printStackTrace();
+                    }
+                }
+                c.close();
+
+                // try to get root folder "Open Data Kit"
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Can you do this folder resolving and potential creation once outside the loop over photos to upload instead of doing it for each item?

You also have exactly the same code for the root folder, the `Submissions` subfolder and the `jrformId` folder. I would recommend creating a series of methods for that called something like `getIDOfFolderWithName(name, inFolder)` and `createAndGetIDOfFolderWithName`.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 11]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                } catch (IOException e) {
+                    e.printStackTrace();
+                    mResults.put(id, form_fail + e.getMessage());
+                    return false;
+                }
+
+                com.google.api.services.drive.model.File folder = null;
+
+                for (com.google.api.services.drive.model.File file : files) {
+                    if (folder == null) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Is it possible for `files` to contain a null file? If not, this loop is equivalent to just setting folder equal to the first file, right?

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 12]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                }
+
+                //checking if file was successfully uploaded
+                if (uploadedFileId == null) {
+                    mResults.put(id, form_fail + "Unable to upload the media files. Try again");
+                    return false;
+                }
+
+                // uploadedPhotos keeps track of the uploaded URL
+                // relative to the path
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: This doesn't look like a relative URL.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 13]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                uploadedPhotos.put(key, "https://drive.google.com/open?id=" + uploadedFileId);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: URL should be in a constant.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 14]
```diff
@@ -565,117 +684,83 @@ else if (columnNames.contains(path)) { // if column present in sheet
...
-                    for (PhotoEntry photo : albumFeed.photos) {
-                        if (picasa_id.equals(photo.id)) {
-                            // already in picasa, no need to upload
-                            inPicasa = true;
-                            picasaPhoto = photo;
-                        }
-                    }
-                }
-            }
+    private String uploadFileToDrive(HashMap<String, String> photosToUpload, String key, com.google.api.services.drive.model.File folder, File toUpload) throws IOException {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: This parameter list is a bit confusing. There's no reason to pass in the full map of photos to upload since you only need the name of the file. You also don't need a reference to `folder`, only its ID. I think a better set of params would be `File toUpload, String mediaName, String destinationFolderID`

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 15]
```diff
@@ -565,117 +684,83 @@ else if (columnNames.contains(path)) { // if column present in sheet
...
-                String[] whereArgs = {
-                        toUpload.getAbsolutePath()
-                };
-                Collect.getInstance().getContentResolver()
-                        .update(Images.Media.EXTERNAL_CONTENT_URI, cv, where, whereArgs);
-            }
+        //adding meta-data to the file
+        com.google.api.services.drive.model.File fileMetadata =
+                new com.google.api.services.drive.model.File()
+                        .setName(photosToUpload.get(key))
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I'm not seeing the name when I look at the file details in GDrive. Am I supposed to?

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 16]
```diff
@@ -565,117 +684,83 @@ else if (columnNames.contains(path)) { // if column present in sheet
...
+                        .setViewersCanCopyContent(true)
+                        .setParents(Collections.singletonList(folder.getId()));
 
-            // uploadedPhotos keeps track of the uploaded URL
-            // relative to the path
-            uploaded.put(key, picasaPhoto);
-        }
+        FileContent mediaContent = new FileContent("image/jpeg", toUpload);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I thought this would fail for pngs but in fact, it looks like PNGs are transferred and given a .jpg extension. That doesn't seem right!

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 17]
```diff
@@ -231,31 +220,163 @@ private boolean uploadOneSubmission(String id, String instanceFilePath, String j
...
+                }
+
+                String uploadedFileId;
+
+                // file is ready to be uploaded
+                try {
+                    uploadedFileId = uploadFileToDrive(photosToUpload, key, folder, toUpload);
+                } catch (IOException e) {
+                    e.printStackTrace();
+                    mResults.put(id, form_fail + e.getMessage());
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I think this `form_fail` constant can also be removed. You can do that in a separate pull request if you'd prefer to do a separate cleanup pass for things you left the same as previous code.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java [hunk 18]
```diff
@@ -565,117 +684,83 @@ else if (columnNames.contains(path)) { // if column present in sheet
...
+                        .setQ("name = '" + folderName + "' and " +
+                                "mimeType = 'application/vnd.google-apps.folder'" +
+                                " and '" + parentId + "' in parents" +
+                                " and trashed=false")
+                        .execute();
+            }
+            for (com.google.api.services.drive.model.File file : fileList.getFiles()) {
+                files.add(file);
+            }
+            pageToken = fileList.getNextPageToken();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java:694]: At some point we should probably actually use the paging to not block when getting a big list of files. It's ok to leave this for now but would be good to have an issue.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java [hunk 19]
```diff
@@ -58,7 +59,7 @@ protected String authenticate(Context context, String mGoogleUserName) throws IO
         // use google auth utils to get oauth2 token
         String scope =
                 "https://picasaweb.google.com/data/";
-        String token = null;
+        String token;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java]: This whole authenticate method is now outdated, right?

**Review by lognaturel — CHANGES_REQUESTED** [review]
Thanks for taking on this very important project and doing it so well, @shobhitagarwal1612! I've made some comments inline to improve code quality a bit.

I also noticed a few behavior oddities:
- In the Google Drive activity, on rotate, we go from My Drive to Shared With Me or vice-versa.

- Tapping Back in Google Drive goes all the way back to the root.

- When I try to submit to a sheet I don't have access to, the dialog I get has some ugly json. We don't have to do this now but it would be good to think of the top errors users are likely to hit and provide more useful error messages. For example, here's what I see:
screen shot 2017-03-21 at 4 41 40 pm
That should be replaced by something like "You don't have access to the submission sheet. Please make sure your survey administrator has given you edit privileges."


- The same image with the same filename can be created multiple times. I attempted to submit to a form I did not have write permissions to, it failed, but the media still got uploaded. Then when my submission succeeded, I ended up with the same image duplicated. <strike>I think perhaps the media should be only be uploaded if the form itself can be submitted? This is a change to existing structure, though, so we can also do that as a separate issue.</strike> The media needs to be uploaded first to get the media url in the sheet. It could be possible to double check the permissions on the sheet first but probably overkill.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 15 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I'm sorry, of course I see the name. I forgot it would be the timestamp name.

**Comment by yanokwa** [comment]
This is looking really great, @shobhitagarwal1612! 

I have weird behavior on a Google account where Collect doesn't have OAuth permissions. When I submit the first time, I get some a few dialogs about the form not being uploaded, then the Auth dialog, then there seems to be a delay before the Send Finalized Form is updated. It ends up feeling strange. Can this behavior be improved?

mar-21-2017 21-20-16

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 20]
```diff
@@ -56,104 +59,83 @@
...
-
     private Button mDownloadButton;
-
     private ImageButton mSearchButton;
-
     private EditText mSearchText;
-
-    private Stack<String> mCurrentPath = new Stack<String>();
-
+    private Stack<String> mCurrentPath = new Stack<>();
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:122]: I think this will fail on version lower than Java 8, right?

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:122]: Is there a minimum Java version in the building how to or readme?

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Done

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 8 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Removed

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 2 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Is there any other place too where the reference link should be added?

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 5 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Done

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 3 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Replaced

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 4 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Sure

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java (hunk 6 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: I agree with you. I do think it makes more sense to keep only the application name in the User Agent Header. No, there wasn't any particular reason for naming it like this. Just thought it would be better to name differently to detect problem in any particular service during the development. I'll change both of them to "ODK-Collect". Does that sound ok?

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 9 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Done

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 7 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Done

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 11 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: The reason behind doing this looping was to verify that only one instance of the folder exists. If multiple folders are found then it throws an error message eg. "2 folders found". Is this the correct approach?

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 17 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: I guess I can make this small change in this PR as well

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Done

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 12 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Sorry. I will remove this unnecessary comment

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 14 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Done. Thanks for noticing that

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 10 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Sure

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 18 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java:694]: In current scenario, if the user has a large number of files, then it iterates over all the pages and displays all the file in a single list. Are we sure that we want to remove this?
Moreover, it is not affecting the performance if the number of files are less.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java (hunk 19 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java]: Yes it is

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java]: I think I missed updating the code for auto upload feature!!!

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsTask.java]: confirmed

**Comment by shobhitagarwal1612** [comment]
@yanokwa Thanks for noticing such a potential bug. I'll fix it soon

**Comment by shobhitagarwal1612** [comment]
@lognaturel Added a check to confirm if user has write permissions before uploading photos and redundant API calls for  fetching sheetId and sheetName for multiple uploading of forms. 
Also made the necessary code refactoring to improve code quality.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Hmm, I thought it would be helpful with some of the OAuth stuff but I wasn't finding the best reference to it. It was just coming up on a generic "set up an Android project" page. If you have a page with the code samples and some explanation, that would be a good link to have. I think you may already have linked to something like that in the sheets feature.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java (hunk 6 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: Thanks!

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 17 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Oops, I should have moved that suggestion up to the first time I saw something like this! Ah well, it's fine in this PR.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 11 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java]: Interesting, I suppose that is what this does. I would have done something like if the size of `files` is exactly one, set `folder` to its first value. else if it's greater than one, add the error. The loop implies there's some reason to go through individual items.

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 18 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java:694]: Let's not do anything now.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 20 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:122]: Take a look at the Gradle file -- it uses Java 7 which is the recommendation for Android. Generics type inference was introduced in Java 7 - http://docs.oracle.com/javase/7/docs/technotes/guides/language/type-inference-generic-instance-creation.html

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 21]
```diff
@@ -210,7 +178,7 @@ public void onCreate(Bundle savedInstanceState) {
 
             MyDrive = false;
 
-            if (testNetwork()) {
+            if (isDeviceOnline()) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:181]: 😢😢 this should just be `!isDeviceOnline()`. If you want to do a separate pull request to clean up some of these things that you may have seen while going through the code, feel free.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 22]
```diff
@@ -315,14 +238,149 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
...
+        // Initialize credentials and service object.
+        mCredential = GoogleAccountCredential.usingOAuth2(
+                getApplicationContext(), Collections.singletonList(DriveScopes.DRIVE))
+                .setBackOff(new ExponentialBackOff());
+
+        HttpTransport transport = AndroidHttp.newCompatibleTransport();
+        JsonFactory jsonFactory = JacksonFactory.getDefaultInstance();
+        mDriveService = new com.google.api.services.drive.Drive.Builder(
+                transport, jsonFactory, mCredential)
+                .setApplicationName("ODK-Collect-Drive")
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Remove "Drive"

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 23]
```diff
@@ -550,18 +558,23 @@ public void authRequest(Uri url, HashMap<String, String> doneSoFar) {
...
                 GoogleAuthUtil.invalidateToken(GoogleSheetsUploaderActivity.this, token);
 
+                getIDOfFolderWithName(GOOGLE_DRIVE_ROOT_FOLDER, null);
                 uploadInstances(selection, selectionArgs, token);
             } catch (UserRecoverableAuthException e) {
+                mResults = null;
                 startActivityForResult(e.getIntent(), REQUEST_AUTHORIZATION);
             } catch (IOException | GoogleAuthException e) {
+            } catch (MultipleFoldersFoundException e) {
+                e.printStackTrace();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: Replace with `Log`

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 24]
```diff
@@ -302,7 +306,7 @@ public void onRequestPermissionsResult(int requestCode,
      */
     @Override
     public void onPermissionsGranted(int requestCode, List<String> list) {
-        // Do nothing.
+//        getResultsFromApi();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: Were these things you were trying? Better not to leave comments like this unless there's an explanation with them!

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 25]
```diff
@@ -550,18 +558,23 @@ public void authRequest(Uri url, HashMap<String, String> doneSoFar) {
...
             }
+            String token;
             try {
-                String token = mCredential.getToken();
-
+                token = mCredential.getToken();
                 //Immediately invalidate so we get a differnet one if we have to try again
                 GoogleAuthUtil.invalidateToken(GoogleSheetsUploaderActivity.this, token);
 
+                getIDOfFolderWithName(GOOGLE_DRIVE_ROOT_FOLDER, null);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java]: I believe this could result in some exceptions being thrown and they should be handled. But I think it makes sense to do all the folder getting and creation together in `uploadOneSubmission`. You don't really gain anything by doing it here.

**Comment by lognaturel** [comment]
It looks like 3a8ae33 breaks form upload for me. I'm now always getting the following error from `GoogleSheetsAbstractUploader.java`:160:
```
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Must specify at least one request.",
    "reason" : "badRequest"
  } ],
  "message" : "Must specify at least one request.",
  "status" : "INVALID_ARGUMENT"
}
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Must specify at least one request.",
    "reason" : "badRequest"
  } ],
  "message" : "Must specify at least one request.",
  "status" : "INVALID_ARGUMENT"
}
```

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java (hunk 21 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:181]: I am pretty sure it should be `isDeviceOnline()`. 
```
/**
     * Checks whether the device currently has a network connection.
     *
     * @return true if the device has a network connection, false otherwise.
     */
    private boolean isDeviceOnline() {
        ConnectivityManager connMgr =
                (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();
        return (networkInfo != null && networkInfo.isConnected());
    }
```
I have tested on device too and it's working as it should. Can you please recheck if its not working or not on your device a well?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:181]: The code works as it is. I was just feeling sad about the empty `if` branch!

**Comment by lognaturel** [comment]
@shobhitagarwal1612 This seems to be working very well now. I think that if you fix that merge conflict, we can merge now. There are a couple small things I'll file as separate issues and it's possible we'll find other small issues as we test for the release but that's totally ok -- it's what code freezes are for!

**Comment by nribeka** [comment]
Yay for decreasing the codebase by removing all those "picasa" classes 👍

File: collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java (hunk 18 above)
Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java:694]: :+1:

**Comment by shobhitagarwal1612** [comment]
@yanokwa Is the behaviour improved?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
👏👏 @shobhitagarwal1612 👏👏 Getting this upgrade/fix in is a big deal!

I'll let @yanokwa take a look at the oauth permission glitch and file an issue if needed.

**Comment by shobhitagarwal1612** [comment]
:smile: It's a pleasure working with all of you 
#ODK
