### PR TITLE
Fix OOM crashes when viewing saved forms

### LINKED ISSUE #6483: Memory leak when viewing saved form
~~Blocked by #5420~~ 

#### ODK Collect version

v2024.3

#### Problem description

Viewing and then exiting a saved form causes a memory leak as the in memory representation of the form is not cleared away on exit.

#### Steps to reproduce the problem

1. Finalize a form
2. Open the form in Ready to Send
3. Exit the form

The memory usage of the app will increase each time you repeat 2 and 3 (even after garbage collection).

#### Expected behavior

The memory increase after viewing a form should be cleaned up by garbage collection.

#### Other information 

This happens because when we open a form to view we start `ViewOnlyHierarchyActivity` and finish `FormFillingActivity` immediately without calling `exit()` which cleans up the form session in `FormSessionRepository`. This means that the `FormController` (and other form data) are held in memory indefinitely.

We could potentially fix this easily by just clearing the form session when exiting `ViewOnlyHierarchyActivity`.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6483 

#### Why is this the best possible solution? Were any other approaches considered?

This is just a revised version of https://github.com/getodk/collect/pull/6497 with changes for the hierarchy being a fragment.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only area of the app affected is viewing submissions.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java [hunk 1]
```diff
@@ -142,11 +142,17 @@ public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceStat
                 new OnBackPressedCallback(true) {
                     @Override
                     public void handleOnBackPressed() {
-                        FormController formController = formEntryViewModel.getFormController();
-                        if (formController != null) {
-                            formController.getAuditEventLogger().flush();
-                            navigateToTheLastRelevantIndex(formController);
+                        if (viewOnly) {
+                            formEntryViewModel.exit();
+
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java]: Please remove this empty line.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15

**Verified cases:**

- Drafts, sent and finalized forms
- Big forms

**Comment by dbemke** [comment]
**Tested with success**

Verified on device with Android 10
