### PR TITLE
Block settings that restart the app when in form entry

### LINKED ISSUE #6482: Changing language/theme during form entry blocks both match exactly and opening the form
#### ODK Collect version
the master version 2e63b33407128e7e17ca46241683945dd749c48f
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Changing language/theme during form entry blocks match exactly and blocks opening the form. After that the user tries to open the form and sees info that "The form can’t be used” but at the same time there isn’t a progress bar in "Start new form”. 
#### Steps to reproduce the problem
1. Download user "trees” https://test.getodk.cloud/#/projects/575/app-users
2. Go to ABC registration form.
3. Fill the form, tap the three dots to go to settings and change the theme of the app (to create a savepoint).
4. Wait for match exactly to run.
5. Try to open the form.
#### Expected behavior
Both form entry and updates should be possible after changing language/theme during form entry.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6482

I've also cleaned up a couple of cases in `FormFillingActivity` that would return to the main menu in rare states.

#### Why is this the best possible solution? Were any other approaches considered?

As discussed in the issue and elsewhere, we decided to go with blocking these settings during form entry for now as reworking locking would be better to after #5420.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The main things to check here are that the user is not able to access settings that reproduce the bug.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -1792,23 +1791,12 @@ protected void onResume() {
...
                 } else {
-                    DialogFragmentUtils.dismissDialog(FormLoadingDialogFragment.class, getSupportFragmentManager());
-                    FormLoaderTask t = formLoaderTask;
-                    formLoaderTask = null;
-                    t.cancel();
-                    t.destroy();
-                    // there is no formController -- fire MainMenu activity?
-                    Timber.w("Starting MainMenuActivity because formController is null/formLoaderTask not null");
-                    startActivity(new Intent(this, MainMenuActivity.class));
+                    throw new IllegalStateException("Null formController!");
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:1794]: This (and the below case) don't have tests and as far as I'm aware, we don't know how they happen. Crashing means we don't have to deal with form session/lock clean up, and I actually think it's a better experience now that we show the crash message on the next relaunch than mysteriously returning to the Main Menu without warning.

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt [hunk 2]
```diff
@@ -68,14 +69,26 @@ class ProjectPreferencesFragment :
         findPreference<Preference>(CHANGE_ADMIN_PASSWORD_PREFERENCE_KEY)!!.onPreferenceClickListener = this
         findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)!!.onPreferenceClickListener = this
         findPreference<Preference>(ACCESS_CONTROL_PREFERENCE_KEY)!!.onPreferenceClickListener = this
+
+        if (inFormEntry) {
+            findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)!!.also {
+                it.isEnabled = false
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt:74]: Could it be made clearer that these settings are disabled? The visual effect feels off - the title isn't grayed out, only the summary, which makes it hard to notice the difference at first glance.

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt [hunk 3]
```diff
@@ -68,14 +69,26 @@ class ProjectPreferencesFragment :
         findPreference<Preference>(CHANGE_ADMIN_PASSWORD_PREFERENCE_KEY)!!.onPreferenceClickListener = this
         findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)!!.onPreferenceClickListener = this
         findPreference<Preference>(ACCESS_CONTROL_PREFERENCE_KEY)!!.onPreferenceClickListener = this
+
+        if (inFormEntry) {
+            findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)!!.also {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt]: You can avoid calling `findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)` twice here and a few lines above by combining those two cases:
```
findPreference<Preference>(PROJECT_MANAGEMENT_PREFERENCE_KEY)!!.also {
            it.onPreferenceClickListener = this
            if (inFormEntry) {
                it.isEnabled = false
                it.setSummary(org.odk.collect.strings.R.string.setting_not_available_during_form_entry)
            }
        }
```

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt [hunk 4]
```diff
@@ -68,14 +69,26 @@ class ProjectPreferencesFragment :
...
 
     override fun onPreferenceClick(preference: Preference): Boolean {
         if (MultiClickGuard.allowClick(javaClass.name)) {
             when (preference.key) {
                 PROTOCOL_PREFERENCE_KEY -> displayPreferences(ServerPreferencesFragment())
                 PROJECT_DISPLAY_PREFERENCE_KEY -> displayPreferences(ProjectDisplayPreferencesFragment())
-                USER_INTERFACE_PREFERENCE_KEY -> displayPreferences(UserInterfacePreferencesFragment())
+                USER_INTERFACE_PREFERENCE_KEY -> {
+                    val fragment = UserInterfacePreferencesFragment()
+                    fragment.arguments =
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt:87]: Why here do you use args and in the case above you pass the value via constructor using fragmentfactory?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt:74]: Totally agree! We can tweak that if we need, so I'd vote we go with this for now and follow up if we're still unhappy with it.

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt:87]: I've used the constructor in the case where the Fragment is declared in the XML layout and an arg in the case where the Fragment is created programmatically. I didn't want to rework the Fragment in the latter case to use a `FragmentFactory` as it felt like beyond the scope of fixing this bug.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
Should "project management" (in settings) also be blocked during form entry?

**Comment by seadowg** [comment]
> Should "project management" (in settings) also be blocked during form entry?

Yes. Any settings that allow you to return to the main menu should. In project management you can reset the project, reconfigure with QR code etc which all return to the main menu.

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 15

**Verified cases:**
- Issues #6482 does not occur
- Check on settings during form entry
- Check on settings when not in form entry
- Changing language in form by "Choose language" option
- Changing theme/language in phone settings during form entry

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
