### PR TITLE
Show form version and form id when deleting blank forms #2173

### LINKED ISSUE #2173: Show form version and form id when deleting blank forms
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Under Delete Saved Form > Blank Forms, the form list should also show the form version and form ID, similar to what Fill Blank Form and Get Blank Form does. To be precise, I expect the UI to look like...

>**Form title**
Version: 123456 ID: form-title

#### Steps to reproduce the problem
Download a form with a version (e.g., All Widgets from opendatakit.appspot.com)

#### Other information 

**delete blank forms**
screen shot 2018-05-07 at 14 14 04

**fill blank form**
screen shot 2018-05-07 at 14 15 29

**get blank form**
screen shot 2018-05-07 at 14 17 19

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2173 

#### What has been done to verify that this works as intended?
I tested it.

#### Why is this the best possible solution? Were any other approaches considered?
I used VersionHidingCursorAdapter instead of using SimpleCursorAdapter and incorporated a small piece of code for showing ID number of forms. As VersionHidinCursorAdapter is working fine for Fill Blank Form page, it must work out fine here too.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
The forms which have both version and id like All Widgets form, CascadingSelect Form, Cascading Triple Select Form

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Aha, now the diff is looking good, thank you!

File: collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java [hunk 1]
```diff
@@ -50,12 +50,23 @@ public boolean setViewValue(View view, Cursor cursor,
...
-                        v.setVisibility(View.GONE);
+                        v.append("");
+                    }
+                    if (from.length > 3) {
+                        int idColumnIndex = cursor.getColumnIndex(from[3]);
+                        String id = cursor.getString(idColumnIndex);
+                        if (id != null) {
+                            v.append(String.format(ctxt.getString(R.string.id_number), id));
+                            v.setVisibility(View.VISIBLE);
+                        } else {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java]: Same question as above.

File: collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java [hunk 2]
```diff
@@ -50,12 +50,23 @@ public boolean setViewValue(View view, Cursor cursor,
...
+                    v.setText("");
+                    v.setVisibility(View.GONE);
                     if (version != null) {
-                        v.setText(String.format(ctxt.getString(R.string.version_number), version));
+                        v.append(String.format(ctxt.getString(R.string.version_number), version));
                         v.setVisibility(View.VISIBLE);
                     } else {
-                        v.setText(null);
-                        v.setVisibility(View.GONE);
+                        v.append("");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java]: Is this `else` necessary? Appending `""` should have no effect.

**Review by lognaturel — COMMENTED** [review]
Can you tell me a bit more about how you verified this? I go to Delete Forms and then the Delete Blank Forms tab and I'm not seeing version or ID. Also, I'm not seeing any code changes that suggest the form ID is pulled from the DB.

File: collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java (hunk 2 above)
Comment (SaumiaSinghal) [reply collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java]: Yes @lognaturel, I also thought the same but since it was there in the original code so i just included it in my code too. Thanks for pointing it out. I'll fix it.

**Comment by SaumiaSinghal** [comment]
Yep @lognaturel, while fixing the diff, i forgot to include the TextView in .xml file for displaying the version and id of deleted forms. Maybe the previous version of code was running on emulator.  I've fixed that and checked it on my emulator as well.

 Please review again! thanks.





screenshot_1527657560

**Review by lognaturel — APPROVED** [review]

**Comment by SaumiaSinghal** [comment]
Hie @lognaturel, is it fine..or do I need to make some changes in it ..?

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Verified cases:
* form with few versions
* sorting

|before fix|after fix|
|---|---|
|screenshot_2018-06-05-15-08-54|screenshot_2018-06-05-15-18-17

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
Woohoo, thanks @SaumiaSinghal!

We always do a quality assurance pass after code review to make sure there are no strange issues on specific Android version or other edge cases that we may not have thought of looking at the code. @mmarciniak90 catches a lot of good problems that way!

**Comment by SaumiaSinghal** [comment]
Thank you @lognaturel, It feels great to have my first PR merged into ODK Collect...:)
