### PR TITLE
Prevent resetting finalized forms that modify entities

### LINKED ISSUE #6435: Entities from finalized registration and update forms after resetting "saved forms and entities"
#### ODK Collect version
the master version ce00913a7cd87d3f5b2472e834ac6a9974d1906c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
I’m not sure what should happen with entities from finalized registration and update forms after resetting "saved forms and entities" in Collect setting. 
After resetting saved forms there aren’t any entities/rows in the db files. Afterwards, if a user finalizes an update to an entity (in the update form), the finalized entity doesn’t appear on the list in the update form (I guess it isn’t created locally/offline – no new rows in db files). If a user finalizes the registration form, in the update form other entities are removed form the list and there’s only the new entity (registration form creates a row in db files). So there are 2 different scenarios what appears in the update form depending on what a user finalizes after resetting saved forms.
I guess it means that after resetting saved forms local entities are enabled again only after refreshing the list of blank forms (or downloading them manually).
Is it ok for the time being or finalizing an entity form should trigger local entities (after resetting) ? 
#### Steps to reproduce the problem
1. Download a project with entities registration form, follow-up form and update form with some existing entities (e.g. trees registration, follow- up, update with the new entity spec  user "one" in https://staging.getodk.cloud/#/projects/101/app-users). 
2. Go to Settings- Project management- Reset, select "Saved forms and entities” and tap "Reset”.
3. Go to Settings- Form management- Auto send and set "off”.
4. Go to the update form, select an entity an finalize the form.
5. Go to the update form and check with version of the entity updated in step 4 is on the list (there is the version without the update + other entities are on the list).
6. Go to the registration form and create an entity.
7. Go to the update form and check which entities are on the list (there’s only the new entity, other entities aren’t on the list).

#### Expected behavior

Instead of being able to reset Saved Forms and entities, users should only be able to reset Saved Forms (like before). Additionally, forms that create/update entities (determinable via `Instance#canDeleteBeforeSend`) should not be reset. This makes reset and manual delete consistent - users currently can't delete forms that create/update forms.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6435

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot to discuss here! I just piggy backed on the existing helpers added to determine whether a form can safely be deleted and added a new use case for resetting entities now the logic is more complex than just deleting everything.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Just affects the saved form reset flow.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt [hunk 1]
```diff
@@ -41,16 +40,12 @@ class ResetProjectTest {
     }
 
     @Test
-    fun canResetSavedFormsAndEntities() {
-        testDependencies.server.addForm("one-question-entity-registration.xml")
-        testDependencies.server.addForm(
-            "one-question-entity-update.xml",
-            listOf(EntityListItem("people.csv"))
-        )
+    fun canResetSavedForms() {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt:43]: Don't you think it would be good to have a test to make sure saved forms with entities can't be deleted here? We have one in `LocalInstanceUseCasesTest` but it is not guaranteed anywhere that `LocalInstanceUseCases` is used in `InstancesDataService`. You can remove it (or call `deleteAll` like before) and all tests will pass.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt (hunk 1 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt:43]: Yeah I agree. I generally feel like a combination of feature level tests and focused unit tests gets us pretty good security around regressions, but I think you're right here that the simplest code to write (`deleteAll`) would be a really easy mistake to make and wouldn't get caught by tests.

How about I just revert [edc8e78ee033a7f8fa17721d2834955a17eb3046](https://github.com/getodk/collect/pull/6460/commits/edc8e78ee033a7f8fa17721d2834955a17eb3046)?

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt:43]: Sounds good.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 15

**Verified cases:**

- Issue #6435 does not occur
- Resetting drafts, finalized and sent forms
- Resetting entity and non-entity forms
- Form reset after an app upgrade

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
