### PR TITLE
Fixed highlighting line color for selected tab in Delete Saved Form

### LINKED ISSUE #3759: Color of the line under the `Saved Forms` and `Blank Forms` on Delete Saved Form view is blue instead of the consistent color for a color scheme on dark mode
#### Problem description
Color of the line under the `Saved Forms` and `Blank Forms` on Delete Saved Form view is blue instead of the consistent color for a color scheme on dark mode

#### Steps to reproduce the problem
1. User sets dark mode
2. User goes to `Delete Saved Form`
3. The line under `Saved Forms` and `Blank Forms` is blue in dark mode 

Screenshot_2020-04-02-20-50-20-091_org odk collect android

#### Expected behavior
Color of the line under the `Saved Forms` and `Blank Forms` is consistent  with the color scheme on dark mode

Noticed during testing #3750

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #3759 

#### What has been done to verify that this works as intended?
I tested it.

WhatsApp Image 2020-04-03 at 06 19 03

#### Why is this the best possible solution? Were any other approaches considered?
I set the color of the highlighting line as the color of activated control link in case of dark theme.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regression risks

#### Do we need any specific form for testing your changes? If so, please attach one.
No specific forms

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
You adjusted the color visible in dark mode but the one from light mode is also not our `secondaryColor`
Our secondaryColor: #2196F3
the one visible now: #33B5E5

I think there is a much easier solution you could just add one line fix in [FileManagerTabs](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FileManagerTabs.java#L62) like:
`slidingTabLayout.setCustomTabColorizer(position -> new ThemeUtils(FileManagerTabs.this).getColorSecondary());`

`getColorSecondary()` does not exist so you would need to create it in `ThemeUtils` but it would be similar to `getColorOnSurface()` so not a big deal.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java [hunk 1]
```diff
@@ -125,4 +125,12 @@ public int getIconColor() {
     public int getRankItemColor() {
         return getAttributeValue(R.attr.rankItemColor);
     }
+
+    /**
+     * @return Secondary color for the current {@link android.content.res.Resources.Theme}
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java]: I'm not a fan of such obvious comments. Comments should be used only if it's required to explain something. Could you remove them from the entire file?

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java (hunk 1 above)
Comment (SaumiaSinghal) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java]: Yes sure @grzesiek2010!

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Tested on Android 6.0, 7.0, 8.1, 9.0
Tested on an emulator with Android 5.1

Verified cases:
* dark mode - the color of the line under the `Saved Forms` and `Blank Forms`  have a consistent color for a color scheme on dark mode
* no changes on light mode
* English/Spanish language

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
@seadowg I think this should be ok to merge before repeat add, right?
