### PR TITLE
Don't attempt to stop location updates if GoogleAPIClient is not already connected

### LINKED ISSUE #4155: Crash on attempt to stop location updates when GoogleApiClient is not yet connected
#### Software and hardware versions 
Collect v1.28

#### Problem description
```
Caused by java.lang.IllegalStateException
GoogleApiClient is not connected yet.
com.google.android.gms.common.api.internal.zaat.execute (zaat.java:12)
com.google.android.gms.internal.location.zzq.removeLocationUpdates (zzq.java:5)
org.odk.collect.android.location.client.GoogleFusedLocationClient.stopLocationUpdates (GoogleFusedLocationClient.java:135)
org.odk.collect.android.location.client.GoogleFusedLocationClient.stop (GoogleFusedLocationClient.java:107)
org.odk.collect.android.activities.GeoPointActivity.onStop (GeoPointActivity.java:163)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1473)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4155 

#### What has been done to verify that this works as intended?
I tested the app with hardcoded disconnecting GoogleApiClient and added tests. 

#### Why is this the best possible solution? Were any other approaches considered?
We just need to check if the client is connected before performing some operations.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing since it's difficult to reproduce.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java [hunk 1]
```diff
@@ -141,7 +141,7 @@ public void stopLocationUpdates() {
     public Location getLastLocation() {
         // We need to block if the Client isn't already connected:
         if (!googleApiClient.isConnected()) {
-            googleApiClient.blockingConnect();
+            new Thread(googleApiClient::blockingConnect).start();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: This is a fix for another issue https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8bf1ac2f771699358e0237615316760d?time=last-seven-days&versions=v1.28.1%20(3923)&sessionEventKey=5F7C02C1035300012FE4B899DA981953_1458846445087682870

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: I'm a little concerned about this. If the client isn't connected, and we spin up a new thread to connect could that cause problems for the call to `getLastLocation` (as it might happen before the client is connected)?

Also, it's likely the testing of this in `GoogleFusedLocationClientTest` (using a `timeout`) will be flakey as the call to `blockingConnect` is now async (and make the behaviour of the method indeterminate). 

Could we maybe pull this fix out of the PR and look at it as a part of a different PR?

**Review by seadowg — CHANGES_REQUESTED** [review]
Just concerned about the other fix bundled into this PR but happy with the fix for the issue!

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: I tested it hardcoding `googleApiClient.disconnect();` just before `if (!googleApiClient.isConnected()) {` and it didn't cause any crashes. @lognaturel what do you think should we exclude this fix?

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java [hunk 2]
```diff
@@ -120,15 +120,15 @@ public void stop() {
...
+        if (!isMonitoringLocation() && googleApiClient.isConnected()) {
             fusedLocationProviderApi.requestLocationUpdates(googleApiClient, createLocationRequest(), this);
         }
 
         this.locationListener = locationListener;
     }
 
     public void stopLocationUpdates() {
-        if (!isMonitoringLocation()) {
+        if (!isMonitoringLocation() || !googleApiClient.isConnected()) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: I think it's possible for a `locationListener` to be set and `googleApiClient` not to be connected. In that case, `locationListener` would not be set to `null`. I think that's not a good state to be in. Just to be safe, I'd wrap only the `removeLocationUpdates` call.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: Ah you mean that locationListener won't be cleared in such a case?

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: If we can't block the UI thread, then this code structure doesn't makes sense. That is, like @seadowg says, if you're doing it in a different thread, that thread is blocked, but you still attempt to `getLastLocation` on the UI thread which could fail if the connection isn't instant. I think you could use `CoroutineAndWorkManagerScheduler.immediate(background, foreground)`. Splitting it off to another PR sounds best to me.

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: Whoops, missed this. Yes, exactly. That means `isMonitoringLocation()` would evaluate to `true` even after `stopLocationUpdates` has been called. I don't know if that really matters currently because I think we only `stopLocationUpdates` when we're closing out activities but I'd rather not risk it.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: Fixed.

File: collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/location/client/GoogleFusedLocationClient.java]: Ok I revoked that change.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Ooh, I can't merge! @seadowg you'll need to accept and merge.

**Review by seadowg — APPROVED** [review]
