### PR TITLE
Fixed clearing features

### LINKED ISSUE #5127: Selected map layer is not displayed automatically in OpenStreetMaps
#### Problem description
Selected map layer is not displayed automatically in OpenStreetMap

#### Steps to reproduce the problem
1. Install ODK Collect and download the All Widgets form from the demo server
2. Add any map layer to layers directory on your device
3. In settings select OpenStreetMap and your layer 
4. Go to Fill Blank Form and click on the map button

#### Expected behavior
The selected layer should be displayed automatically.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5127 

#### What has been done to verify that this works as intended?
I've tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
My thoughts are in comments below so I'm not going to repeat them here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Apart from verifying the fix itself please test geo widgets with OpenStreetMap (adding/removing points) to make sure everything works fine. Additionally please take a look at Leak Canary to check if there are maybe new leaks caused by maps.

#### Do we need any specific form for testing your changes? If so, please attach one.
The `All Widgets` form from the demo server.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java [hunk 1]
```diff
@@ -381,10 +381,11 @@ public void removeFeature(int featureId) {
 
     @Override
     public void clearFeatures() {
-        map.getOverlays().clear();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:384]: I don't know why it was implemented in this way... clearing everything not just features like it is in google and mapbox and like I implemented it now.

File: collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java [hunk 2]
```diff
@@ -175,12 +175,6 @@ public void onStop() {
         super.onStop();
     }
 
-    @Override
-    public void onDestroy() {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java:179]: I had to remove that because it caused NPEs in OSM I don;t think it's needed, at least I'm not seeing any leaks.

File: collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java [hunk 3]
```diff
@@ -381,10 +381,11 @@ public void removeFeature(int featureId) {
 
     @Override
     public void clearFeatures() {
-        map.getOverlays().clear();
-        addAttributionAndMapEventsOverlays();
-        map.getOverlays().add(myLocationOverlay);
-        map.invalidate();
+        if (map != null) {  // during Robolectric tests, map will be null
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java]: Do we need this check here? We don't have any Robolectric tests for this class as far as I'm aware.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java]: Yes if we have tests that require checks like that it's probably only for Google maps so here it's not needed. Fixed.

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
I have noticed a delay with showing/deleting single points from geopoint widget with map appearance when adding point by placement on map and when delete point using delete button. I was comparing with store version and I can see delays like 2-6s on both my devices. @grzesiek2010 Could you please take a look?

**Comment by grzesiek2010** [comment]
> Could you please take a look?

ok I'm on it.

**Comment by grzesiek2010** [comment]
Ok the problem has been fixed. Please continue testing.

**Comment by srujner** [comment]
**Tested with Success!**
Verified on android 10 and 11

Verified Cases:
- #5127 is no longer reproducing;
- Regression checks on Geowidgets using OSM layer;
- Offline layers;
- Adding/Removing single points;
- Zero leaks at Canary Leaks app;
- screen rotation, minimize app, using backward button

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1 and 8.1
