### PR TITLE
Geopoint tweaks

### LINKED ISSUE #4962: NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getAccuracy()' on a null object reference
#### Software and hardware versions 
Collect v2022.1-beta.0

#### Problem description
https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/0e474160d58f47246060bec728b583c3?time=last-seven-days&versions=v2022.1-beta.0%20(4342)&sessionEventKey=61DEB0BD0366000111F2F8A684B9554F_1630718692977095893

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getAccuracy()' on a null object reference
       at org.odk.collect.geo.GeoPointActivity.logSavePointManual(GeoPointActivity.java:232)
       at org.odk.collect.geo.GeoPointActivity.lambda$setupLocationDialog$0(GeoPointActivity.java:208)
       at org.odk.collect.geo.GeoPointActivity.$r8$lambda$9fPPLIJZceZ6GhevPMP1YYDbTrU(GeoPointActivity.java)
       at org.odk.collect.geo.GeoPointActivity$$InternalSyntheticLambda$0$20b2cb98c1124a1e4175c17f5deb4b7587b70f00d17be8c332623ecb8a973893$0.onClick(GeoPointActivity.java:2)
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
```

### PR DESCRIPTION
**Pull request by seadowg**
Work towards #4960
Closes #4962

Changes made:
* Adds scrolling to the dialog
* Dialog has translucent background on API 30+
* Satellite info appears again
* Removes experimental setting

#### What has been done to verify that this works as intended?

New and existing tests, played with it briefly in the wild.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Not a lot of changes here (it's mostly additive) so maybe worth skipping QA given we'll be doing regression testing soon.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: geo/src/main/java/org/odk/collect/geo/GeoPointActivity.kt [hunk 1]
```diff
@@ -10,13 +13,19 @@ import org.odk.collect.geo.analytics.AnalyticsEvents
...
-class GeoPointActivityNew : LocalizedActivity(), GeoPointDialogFragment.Listener {
+class GeoPointActivity : LocalizedActivity(), GeoPointDialogFragment.Listener {
 
     @Inject
     lateinit var geoPointViewModelFactory: GeoPointViewModelFactory
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
+
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
```
Comment (seadowg) [inline geo/src/main/java/org/odk/collect/geo/GeoPointActivity.kt:24]: It seems like we can't do this on older versions (without using reflection to call private methods). Alternative methods involve messing around with themes and I think that'll add more complexity than it's worth.

File: location/src/main/java/org/odk/collect/location/satellites/GpsStatusSatelliteInfoClient.kt [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+class GpsStatusSatelliteInfoClient(private val locationManager: LocationManager) :
+    SatelliteInfoClient {
+
+    override val satellitesUsedInLastFix: NonNullLiveData<Int>
+        get() = GpsStatusSatellitesLiveData(locationManager)
+}
+
+@SuppressLint("MissingPermission")
+@Suppress("deprecation")
```
Comment (seadowg) [inline location/src/main/java/org/odk/collect/location/satellites/GpsStatusSatelliteInfoClient.kt:17]: The deprecated API has been replaced by a new one that is only available in API 24 and up. We probably want to come back here and either use `LocationManagerCompat` or just switch between two different `LiveData` implementations based on OS. I'm thinking that can just be an issue we schedule for the next release rather than blocking this one?

**Review by lognaturel — APPROVED** [review]

**Comment by seadowg** [comment]
Merging this but QA can continue on `master`.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 5.1 and 8.1.

Verified cases:
- screen rotation
- scroll down the dialog 
- satelites are visible
- light/dark mode
- experimental settings have been removed

**Comment by srujner** [comment]
*Tested with success!*
Verified on Androids 10 and 11
Verified cases:

- screen rotation
- scroll down the dialog
- satelites are visible
- light/dark mode
- experimental settings have been removed

@seadowg I noticed a slight difference on Android 11 with the Geopoint screen, after clicking the "Start GeoPoint" button the background of the app is still visible.
Screenshot_20220118-105719(1)

The same screen on Android 10 and others for comparison: 
Screenshot_2022-01-18-10-57-11-694_org odk collect android

Is this the intended action and both versions are correct or is Android 11 missing something?

**Comment by seadowg** [comment]
@srujner yup that's intentional! You'll see in the description that I wrote "Dialog has translucent background on API 30+". I should have written "Android 11/API 30+" - Android annoyingly has multiple names for each version. We're unable to do the transparent background on older versions.

**Comment by srujner** [comment]
@seadowg Indeed! I missed this information, then everything else is fine ;)
