### PR TITLE
Check if selected map layer file exists before using it

### LINKED ISSUE #3771: SQLiteCantOpenDatabaseException in GoogleMapsMapBoxOfflineTileProvider.java:58
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4c9e1ca129c3e23cf5f18163fff762b9?time=last-seven-days&sessionId=5E8D51A7006700016A9E079441654C90_DNE_0_v2

#### Problem description
`Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14 SQLITE_CANTOPEN): Could not open database, (OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:552)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:213)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:202)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:958)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:942)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:843)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:791)
       at org.odk.collect.android.geo.GoogleMapsMapBoxOfflineTileProvider.<init>(GoogleMapsMapBoxOfflineTileProvider.java:58)
       at org.odk.collect.android.geo.GoogleMapsMapBoxOfflineTileProvider.<init>(GoogleMapsMapBoxOfflineTileProvider.java:53)
       at org.odk.collect.android.geo.GoogleMapFragment.loadReferenceOverlay(GoogleMapFragment.java:475)
       at org.odk.collect.android.geo.GoogleMapFragment.lambda$addTo$0(GoogleMapFragment.java:137)
       at org.odk.collect.android.geo.-$$Lambda$GoogleMapFragment$Bab84yBjF8hGnCxdMTDDMyzjnsA.onMapReady(-.java:6)
       at com.google.android.gms.maps.zzak.zza(zzak.java:2)
       at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(zzaq.java:12)
       at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:12)
       at android.os.Binder.transact(Binder.java:675)
       at cg.b(cg.java:2)
       at com.google.maps.api.android.lib6.impl.be.run(be.java:2)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3771

#### What has been done to verify that this works as intended?
I was able to reproduce the issue following the steps described below and confirmed this pr fixes the issue.

#### Why is this the best possible solution? Were any other approaches considered?
I was able to reproduce the issue reported in #3771. Steps are:
1. Download any offline map layer and paste it to layers/ dir.
2. Select the downloaded layer in the map settings.
3. Go to any geo widget which uses maps.
4. Remove the offline map layer from layers dir
5. Open the map view from the geo widget.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change is safe, we just need to confirm the crash mentioned in the issue doesn't exist anymore using the steps I described above.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with geo widgets.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java [hunk 1]
```diff
@@ -206,4 +209,11 @@ void addTo(
     interface FeatureListener {
         void onFeature(int featureId);
     }
+
+    default File getReferenceLayerFile(Bundle config) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java]: It feels to me like this could be static util helper method (that probably takes a `StoragePathProvider` and `Bundle` as args). I'd generally think about a default implementation adding something to the external interface where as this seems more like a helper for the `MapFragment` implementations. What do you think?

Either way I think this piece of logic should have a test to drive out that it checks for file existance as well as grabbing the layer path.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java]: Ok I moved getReferenceLayerFile() to GeoUtils. When it comes to tests... getAbsoluteOfflineMapLayerPath() has its own tests so does that make sense to write a test just to check the return statement (file existence):
```
return path != null && new File(path).exists()
                ? new File(path)
                : null;
```
?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java]: Yeah it's a small decision but it's an important one so good to have a test to make sure it stays in place.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java]: Ok done, I added tests.

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 6.0, 7.0, 8.1, 9.0
Default map view is visible 

Verified cases:
- map view opened from Fill Blank Form list
- map from Geo widget
- restore a deleted offline map
- Google Map, Mapbox, OSM
- old ODK directory 
- ODK directory after migration

@kkrawczyk123 take a look at that issue because I can't use Mapbox on emulator

**Comment by kkrawczyk123** [comment]
Verified on Androids 5.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
