### PR TITLE
Fixes Issue#2158: Collect crashes when user changes device orientation during loading image to any of Image Widget

### LINKED ISSUE #2158: Collect crashes when user changes device orientation during loading image to any of Image Widget
#### Software and hardware versions 
Collect master

#### Problem description
App crashes when the user changes device orientation during loading image

#### Steps to reproduce the problem
1. The user starts a form with images
2. The user chooses some image
3. The user sees dialog `please wait a few moments.`
screenshot_20180427-095359
4. User changes device orientation
5. App crashes

#### Expected behavior
* ODK Collect does not crash
* Image is loaded

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2158 

#### What has been done to verify that this works as intended?
I tested it on Android 5.1.

#### Why is this the best possible solution? Were any other approaches considered?
It uses DialogFragment and it is definitely better than my last approach of solving this issue by fixing device orientation.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form having Image widget.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for digging deeper into this, @SaumiaSinghal. I love how you're always taking on tricky issues and getting to the bottom of them!

This is a very promising approach that does avoid the crash. I believe that it won't load the image if the orientation is changed though, is that right? What happens if you select an image in portrait and then rotate to landscape when the progress dialog is shown? I believe it hangs on the progress dialog forever.

**Comment by SaumiaSinghal** [comment]
Thanks @lognaturel for reviewing, You are definitely right. This fix does avoid the crash. But, in the event of loading a large size image, and then changing the device orientaion, the image takes forever to load, and also the progress dialog won't go off.

**Comment by SaumiaSinghal** [comment]
Previously, I noticed that there was a crash even if I am selecting a small sized image from my gallery and changing device orientation there itself, and then, going back to Collect UI in new orientaion. My PR, does fix that, but not the case you talked about.

**Comment by lognaturel** [comment]
Ok! Would you like to explore how to make sure the image is loaded even after an orientation change? A fix to #2158 does need to make that possible.

**Comment by SaumiaSinghal** [comment]
Yes @lognaturel, it would be a great help if you can guide me to what I'm doing wrong..

**Comment by SaumiaSinghal** [comment]
Or @lognaturel, I am gonna add more commits to solve this problem, just tell me whether it is the best approach or not.

**Comment by lognaturel** [comment]
@SaumiaSinghal When the orientation changes, the whole activity gets killed and recreated. In this case, you need to save enough state to know that a file save was in progress and to be able to react to changes in that task. I think http://code.hootsuite.com/orientation-changes-on-android/ should give you some useful ideas.

**Comment by SaumiaSinghal** [comment]
I have fixed that error, @lognaturel, can you please review again?

**Comment by lognaturel** [comment]
This approach looks good to me, @SaumiaSinghal! The only change I see as a must is the naming -- "upload" suggests there's a data transfer going. Maybe instead of `imageUploading` it could be `imageLoading` or `imageAttaching` or `imageChoosing`?

I'd also like to get @grzesiek2010 review on this one since he's looked at the problem and had some good thoughts on it.

**Comment by grzesiek2010** [comment]
I agree with @lognaturel about naming.

the approach with adding a fragment looks strange https://github.com/opendatakit/collect/pull/2482/files#diff-03ff45091550285dd88b56927010c457R300
could you explain it to me? Why such a solution?

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010, Thanks for reviewing my PR. 
I searched about it, and found that using retained fragments is the best option (according to some blogs).
https://github.com/opendatakit/collect/pull/2482/files#diff-03ff45091550285dd88b56927010c457R300
Here, I am trying to check whether the activity is created for the first time or not. If it is, then, a new `imageUploadingFragment` is created, otherwise, it just searches for the already existing fragment.

**Comment by SaumiaSinghal** [comment]
Yes, I'll surely change the name of the fragment and AsyncTask. It looks misleading to me too.

**Comment by lognaturel** [comment]
I think this seems weird because the `Fragment` has no UI, right, @grzesiek2010? I think it is an appropriate use of retained fragments but @SaumiaSinghal would be good to see your sources. I'm seeing things like https://stackoverflow.com/questions/21335796/android-non-ui-fragment-usage.

**Comment by grzesiek2010** [comment]
It's not easy to reproduce but once i goth this crash (after changing device orientation):
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList org.odk.collect.android.views.ODKView.getWidgets()' on a null object reference
        at org.odk.collect.android.activities.FormEntryActivity.getWidgetWaitingForBinaryData(FormEntryActivity.java:936)
        at org.odk.collect.android.tasks.ImageUploadingTask.doInBackground(ImageUploadingTask.java:51)
        at org.odk.collect.android.tasks.ImageUploadingTask.doInBackground(ImageUploadingTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+import org.odk.collect.android.utilities.MediaUtils;
+import org.odk.collect.android.utilities.ToastUtils;
+
+import java.io.File;
+
+import timber.log.Timber;
+
+public class ImageUploadingTask extends AsyncTask<Uri, Void, File> {
+
+    private FormEntryActivity formEntryActivity;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java]: You probably should use `WeakReference` here to avoid memory leaks, there is even a prompt in Android Studio.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+
+    public ImageUploadingTask(FormEntryActivity formEntryActivity) {
+        onAttach(formEntryActivity);
+    }
+
+    public void onAttach(FormEntryActivity formEntryActivity) {
+        this.formEntryActivity = (FormEntryActivity) formEntryActivity;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java]: You don't need to cast here.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    }
+
+    public void onDetach() {
+        this.formEntryActivity = null;
+    }
+
+    @Override
+    protected File doInBackground(Uri... uris) {
+        File instanceFile = formEntryActivity.getFormController().getInstanceFile();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java]: please add a null check here (formController object may be null) we had lot's off related crashes.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+        Fragment prev = formEntryActivity.getSupportFragmentManager().findFragmentByTag(ProgressDialogFragment.COLLECT_PROGRESS_DIALOG_TAG);
+        if (prev != null) {
+            DialogFragment df = (DialogFragment) prev;
+            df.dismiss();
+        }
+
+        if (formEntryActivity.getCurrentViewIfODKView() != null) {
+            formEntryActivity.getCurrentViewIfODKView().setBinaryData(result);
+        }
+        formEntryActivity.saveAnswersForCurrentScreen(formEntryActivity.DO_NOT_EVALUATE_CONSTRAINTS);
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java]: `FormEntryActivity#DO_NOT_EVALUATE_CONSTRAINTS` is static so you don't need to use the object here you can just call `FormEntryActivity.DO_NOT_EVALUATE_CONSTRAINTS` instead.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+        }
+
+    }
+
+    @Override
+    protected void onPostExecute(File result) {
+        Fragment prev = formEntryActivity.getSupportFragmentManager().findFragmentByTag(ProgressDialogFragment.COLLECT_PROGRESS_DIALOG_TAG);
+        if (prev != null) {
+            DialogFragment df = (DialogFragment) prev;
+            df.dismiss();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageUploadingTask.java]: I would use just `((DialogFragment) prev).dismiss();`
There is no point in creating an object just to use it once.

**Comment by SaumiaSinghal** [comment]
@grzesiek2010, I have made the required changes. Can you please review again?

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+        this.formEntryActivity = null;
+    }
+
+    @Override
+    protected File doInBackground(Uri... uris) {
+
+        File instanceFile = null;
+
+        if (formEntryActivity.get().getFormController() != null) {
+            instanceFile = formEntryActivity.get().getFormController().getInstanceFile();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: it's better to create a FormController object and use it in both places than getting it from formEntryActivity twice.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+        }
+
+        if (instanceFile != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: You can move this if statement inside the one above.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+            String instanceFolder1 = instanceFile.getParent();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: Could you refactor this naming (just remove `1`)

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 9]
```diff
@@ -563,7 +576,7 @@ private void nonblockingCreateSavePointData() {
     }
 
     @Nullable
-    private FormController getFormController() {
+    public FormController getFormController() {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I think it's better to leave this method private and just use `Collect.getInstance().getFormController()` wherever you need.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 10]
```diff
@@ -292,6 +297,14 @@ public void onCreate(Bundle savedInstanceState) {
             showPreviousView();
         });
 
+        if (savedInstanceState == null) {
+            imageLoadingFragment = new ImageLoadingFragment();
+            getFragmentManager().beginTransaction().add(imageLoadingFragment, TAG_IMAGE_LOADING_FRAGMENT).commit();
+        } else {
+            FragmentManager fm = getFragmentManager();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: There is no need to create this object since we use it only once you can directly use `getFragmentManager()` instead.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 11]
```diff
@@ -755,9 +768,10 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
                  * Android 1.6) we want to handle images the audio and video
                  */
 
-                showDialog(SAVING_IMAGE_DIALOG);
-                Runnable runnable = () -> saveChosenImage(intent.getData());
-                new Thread(runnable).start();
+                ProgressDialogFragment progressDialog = ProgressDialogFragment.newInstance(getString(R.string.please_wait));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: The same here you can just call show on a result of `ProgressDialogFragment.newInstance()` instead of creating an object you use only once.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 12]
```diff
@@ -0,0 +1,93 @@
...
+    public ImageLoadingTask(FormEntryActivity formEntryActivity) {
+        onAttach(formEntryActivity);
+    }
+
+    public void onAttach(FormEntryActivity formEntryActivity) {
+        this.formEntryActivity = new WeakReference<>(formEntryActivity);
+    }
+
+    public void onDetach() {
+        this.formEntryActivity = null;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: `this.` is not needed here.

**Comment by grzesiek2010** [comment]
Generally looks good to me, just a couple of code improvements.
Did you try to reproduce the crash I ran into?

**Comment by SaumiaSinghal** [comment]
Yes @grzesiek2010, I tested it again. However, I didn't encounter the crash. It may not occur all the times.

**Comment by SaumiaSinghal** [comment]
It was related to NPE, for now, I think adding a null check should suffice.

**Comment by grzesiek2010** [comment]
> It was related to NPE, for now, I think adding a null check should suffice.

Yes I would check if `((ODKView) currentView)` is null before calling `getWidgets()`
https://github.com/opendatakit/collect/blob/03f1f9e8af9dfc19751b4ad92405b860e4c451e5/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L936

that would be enough. Maybe add a Timber log.

**Comment by SaumiaSinghal** [comment]
Okay @grzesiek2010, yes I will add a Timber log too.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 13]
```diff
@@ -959,14 +930,20 @@ private String getFileExtensionFromUri(Uri fileUri) {
...
     }
 
-    private QuestionWidget getWidgetWaitingForBinaryData() {
+    public QuestionWidget getWidgetWaitingForBinaryData() {
         QuestionWidget questionWidget = null;
-        for (QuestionWidget qw : ((ODKView) currentView).getWidgets()) {
-            if (qw.isWaitingForData()) {
-                questionWidget = qw;
+
+        if (currentView != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I think it would be better to check for null after casting, I mean:
```
ODKView odkView = (ODKView) currentView;
if (odkView != null) {
...
}
```

Comment (SaumiaSinghal) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Okay @grzesiek2010, I will make that change. Thanks for guiding me:)

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 14]
```diff
@@ -0,0 +1,96 @@
...
+    }
+
+    @Override
+    protected void onPostExecute(File result) {
+        Fragment prev = formEntryActivity.get().getSupportFragmentManager().findFragmentByTag(ProgressDialogFragment.COLLECT_PROGRESS_DIALOG_TAG);
+        if (prev != null) {
+            ((DialogFragment) prev).dismiss();
+        }
+
+        if (formEntryActivity.get().getCurrentViewIfODKView() != null) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: Please create here an object to call `formEntryActivity.get().getCurrentViewIfODKView()` only once and then use taht object in both places.

File: collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java [hunk 15]
```diff
@@ -0,0 +1,98 @@
...
+            }
+        }
+        return null;
+
+    }
+
+    @Override
+    protected void onPostExecute(File result) {
+        Fragment prev = formEntryActivity.get().getSupportFragmentManager().findFragmentByTag(ProgressDialogFragment.COLLECT_PROGRESS_DIALOG_TAG);
+        ODKView odkView = formEntryActivity.get().getCurrentViewIfODKView();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java]: You should create an object where it's used so in this case, it's a few lines below.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by SaumiaSinghal** [comment]
Yes @grzesiek2010, That's a nice piece of advice. Thank you:)

**Comment by grzesiek2010** [comment]
Ok thanks, I can approve it. @lognaturel please add `needs testing` label if you don't have any questions/concerns.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thanks so much @SaumiaSinghal for getting to a good solution on this one. 😊
