### PR TITLE
Fix error occurred when user adds file from SD card

### LINKED ISSUE #2652: Error occurs when user adds file to File widget from SD card
#### Software and hardware versions 
Verified Collect v1.16.4 and v1.17.2
Device with Internal Storage and **SD card**

#### Problem description
Error occurs when user adds file to File widget from SD card

#### Steps to reproduce the problem
1. The user uses a device with  Internal Storage and **SD card**
2. User want to add a file from SD card
screenshot_2018-10-16-16-21-31

3. User sees error
screenshot_2018-10-16-16-23-05

#### Expected behavior
Adding files from SD card is allowed

### PR DESCRIPTION
**Pull request by nshestiuk**
Closes #2652 

#### What has been done to verify that this works as intended?
Issue was reproduced and fix was manually tested on Moto G4 play API 25 and Nexus 5x API 21 (emulator).
#### Why is this the best possible solution? Were any other approaches considered?
I didn't find official solution for transforming content URI to the file path which supports external SD cards on all API levels. 
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Without this fix users are not able to upload files from external SD card.
#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with file picker can be used.
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java [hunk 1]
```diff
@@ -476,12 +476,11 @@ public static String getPath(final Context context, final Uri uri) {
                 final String[] split = docId.split(":");
                 final String type = split[0];
 
-                if ("primary".equalsIgnoreCase(type)) {
-                    return Environment.getExternalStorageDirectory() + "/"
-                            + split[1];
```
Comment (nshestiuk) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java:481]: I experimentally confirmed that `return Environment.getExternalStorageDirectory() + "/" + split[1];`  works not only for primary type. Since we don't have any fallback for non-primary volumes (see removed TODO below), even just removing of wrapping `if ("primary".equalsIgnoreCase(type))` condition will significantly reduce number of devices affected by the issue.  

`Environment.getExternalStorageDirectory()` usually returns value like `/storage/sdcard/`, which works for most of cases I've tested.
 
On some devices path can look like `/storage/4A50-B543/path/to/file/on/sd/card/file.jpg`, where `4A50-B543` is the value of `type` variable, parsed from the initial URI.  `Environment.getExternalStorageDirectory()` doesn't return valid value for such case and there is no utility method which returns/builds such path. 
So I decided to detect such devices by checking that `new File("/storage/4A50-B543").exists()` and build path manually.

**Comment by lognaturel** [comment]
Thanks for the detailed explanation and comment, @nshestiuk, and welcome to ODK! 

The next step in our process is to do a QA pass. If you haven't already, I invite you to read about the review process [here](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#the-review-process).

**Comment by kkrawczyk123** [comment]
@lognaturel, I didn't see any errors which is good but my testing results are not super clear too. On Android 6.0 - two separate devices I was able to add any file from SD card. On Android 4.4 and Samsung Galaxy J1 SM-J100H I was able to open file manager choose a file form the SD card but it wasn't added to the widget. I was able to add files from Drive and internal storage. I tried to reproduce it on some other Android 4.4 device but it didn't recognize the SD card at all. I tried with Android 5.1 and 4.2 and they did not see SD card too. I can't even try on newer devices like 7.0 and 8.1 as they do not have a place to put SD card inside. So I run out of devices.

@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thank you @kkrawczyk123! I'm not super surprised that this is inconsistent --as @nshestiuk described, there doesn't seem to be a single official solution that works on all API levels.

> On Android 4.4 and Samsung Galaxy J1 SM-J100H I was able to open file manager choose a file form the SD card but it wasn't added to the widget.

@nshestiuk This sounds to me like that device or API level uses a different mount point, does that sound right to you?

Since there are no regressions and it does help several devices, I suggest we merge this and keep the issue open with devices that we know aren't supported in case someone else has additional ideas.

**Comment by nshestiuk** [comment]
Thank you for testing @kkrawczyk123!


>>On Android 4.4 and Samsung Galaxy J1 SM-J100H I was able to open file manager choose a file form the SD card but it wasn't added to the widget.
>
>@nshestiuk This sounds to me like that device or API level uses a different mount point, does that sound right to you?

@lognaturel, that sounds right to me.  Android 4.4 is on API 19, so [it uses new code](https://github.com/opendatakit/collect/blob/d3f067f0a852792cfe6619cf9525257633038300/collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java#L468-L471), but mount point path cannot be built neither with old or new convention.   

I agree that it's better to merge than not to merge PR. Fix should reduce number of affected devices. 

Since I don't have device to debug the problem, I'll probably not find better solution. But we may improve user experience by showing meaningful error message, e.q.:
_"We can't load file from external SD card on this phone. Please try to load file from the internal memory."_

Let me know if you want me updating the PR with this (or another) error message.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Let's start with this. It's not something a user has run into as far as we know and I think sdcards are less common these days.

**Comment by lognaturel** [comment]
To make my thinking explicit -- I hesitate to add error messages for pretty uncommon states because it adds burden to [our translators](https://transifex.com/opendatakit/).

And I think this improvement goes a long way to making it even less likely a user experiences the issue!
