### PR TITLE
Fixed detecting form updates

### LINKED ISSUE #4895: Attempt to invoke virtual method 'java.lang.String org.odk.collect.forms.Form.getFormMediaPath()' on a null object reference
#### Software and hardware versions 
Collect v2021.3.0

#### Problem description
https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/be730c9d272352bd5b8685ab0d197899?time=last-seven-days&versions=v2021.3.0%20(4316)&sessionEventKey=6184E33F02B600015883C970B2D53C78_1605436904284051748

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.odk.collect.forms.Form.getFormMediaPath()' on a null object reference
       at org.odk.collect.android.utilities.FormUtils.getMediaFiles(FormUtils.java:20)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.areNewerMediaFilesAvailable(ServerFormsDetailsFetcher.java:130)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.fetchFormDetails(ServerFormsDetailsFetcher.java:86)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:63)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:39)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

#### Steps to reproduce the problem
1. Upload a simple form with media files to Central and download it in Collect
2. Update the form bumping its version and download in Collect
3. Fill one form and save it
4. Delete the newer version of the form
5. Try to open the list of forms to download

The app doesn't crash but loads and loads and in logs I get the same NPE

If you have a form but without media files and you do the same, then there is no crash or infinitive loading
but the message that an update is available is not visible what is also a bug.

I used this form: [formTest.zip](https://github.com/getodk/collect/files/7485591/formTest.zip)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4895

#### What has been done to verify that this works as intended?
I added automated tests and verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
The bug was in this line https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4895?expand=1#diff-d241c237e50a73d5233d52f1d174193cc3692fe2aa977b654ac5e02ff39f13d7L126

we took all forms from database by hash but we should skip those soft deleted.

So when we had two versions of the same form and the newest one was soft deleted (deleted but still present in our database because there are instances of that form) `getOneByMd5Hash` would return that deleted form and it would be treated as a form we already have.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should just fix the issue and have no side effects so please focus on the reproduction steps. If you have some other ideas (and time) it would be of course good to play with form updates to make sure we don't have more hidden bugs. 

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media files like the one I attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: forms/src/main/java/org/odk/collect/forms/FormsRepository.java [hunk 1]
```diff
@@ -19,6 +19,9 @@
     @Nullable
     Form getOneByMd5Hash(@NotNull String hash);
 
+    @Nullable
+    Form getOneNotDeletedByMd5Hash(@NotNull String hash);
```
Comment (seadowg) [inline forms/src/main/java/org/odk/collect/forms/FormsRepository.java]: I think we could just check the `Form#isDeleted` on the returned value of `getOneByMd5Hash` instead of introducing this function. That would mean we aren't increasing the surface area of the `FormsRepository` (and the number of tests required). What do you think?

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.kt [hunk 2]
```diff
@@ -0,0 +1,64 @@
+package org.odk.collect.android.utilities
+
+import org.javarosa.core.reference.ReferenceManager
+import org.javarosa.core.reference.RootTranslator
+import org.odk.collect.android.logic.FileReferenceFactory
+import org.odk.collect.android.storage.StoragePathProvider
+import org.odk.collect.forms.Form
+import java.io.File
+
+object FormUtils {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.kt]: Is there a reason we needed to do this in this PR? Maybe we can pull it out of the branch if not just so there's no extra risk added. If there's an advantage for the fix I'm missing I'm happy for it to stay in though!

**Review by seadowg — CHANGES_REQUESTED** [review]

File: forms/src/main/java/org/odk/collect/forms/FormsRepository.java (hunk 1 above)
Comment (grzesiek2010) [reply forms/src/main/java/org/odk/collect/forms/FormsRepository.java]: Yeah we can do that like that too.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.kt]: No it's not crucial so I removed that change.

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 9 and 11

Tested cases:
- scenario from issue
- finalize/save form
- update form version for few times
- download the same form more than once
- automatic form update, previously downloaded form
- match exactly server 
- Central, Aggregate 
- form update regression checks
- try with different forms with media 
- do not hide all form versions
- fill different versions of forms 
- send different versions to Central

**Comment by mmarciniak90** [comment]
Tested with success on Android 8.1 and 10.0.
