### PR TITLE
Make finalized form edits opt-in

### LINKED ISSUE #6592: Make finalized form edits opt-in
~~Blocked by [form spec](https://forum.getodk.org/t/spec-proposal-editable-submissions/53577)~~
~~Blocked by #6591~~

The form spec proposal for this is [here](https://forum.getodk.org/t/spec-proposal-editable-submissions/53577/8).

## Acceptance

- [ ] Given a form opts-in to finalized edits
And I have filled out and finalized a submission
When I view the submission via "Ready to send"
Then I see the ✏️ icon
And I can edit the submission

- [ ] Given a form does not opt-in to finalized edits
And I have filled out and finalized a submission
When I view the submission via "Ready to send"
Then I do not see the ✏️ icon
And I cannot edit the submission

### LINKED ISSUE #6681: Return to the main menu after editing a finalized instance
## Acceptance

- [ ] Given I've filled out and finalized a form
When I open that submission to view it from "Ready to send"
And I click on the ✏️ icon in the app bar
And I make changes and finalize
Then I am returned to the main menu

### LINKED ISSUE #6692: Instance name (in the directory) contains wrong time zone
#### ODK Collect version
the master version 2c5d4148bb1a71ee3112cbe221e65a7d31c3c84c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In the file directory in instances folder the time in the name of the instance shows a different time zone.
In the screenshot there’s 13:30 but in the instance name there's 11:30 (-2h from the real time the instance was saved).

Image

The issue doesn’t occur in the store version 2025.1.4
#### Steps to reproduce the problem
1. Save a draft.
2. Go to the file directory to the instances folder and check the time in the instance name.
#### Expected behavior
Time in the instance name should be consistent with the time zone of the device.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6592
Closes #6681 
Closes #6692 

#### Why is this the best possible solution? Were any other approaches considered?
#6692 I just fixed an issue where the timezone was being set to UTC in the production code to make the tests pass, instead of setting it in the tests themselves.
#6592 The initial implementation was consistent with how we handle other submission attributes, such as auto-send or auto-delete. However, as the discussion below shows, we can rely on a simpler solution by reading it directly from the form definition.
#6681  Previously, opening a form from the `Ready to send` list and then closing it (regardless of whether any edits were made) would return the user to the `Ready to send` list. This behavior was inconsistent with all other form lists:
- Opening and closing a form from `Blank forms` returns the user to the main menu.  
- Opening and closing a form from `Drafts` returns the user to the main menu.  
- Opening and closing a form from `Sent` returns the user to the main menu.  

To maintain consistency, the behavior for `Ready to send` should match these other cases by returning the user to the main menu as well.

Let me know if you want a version written in a more technical or changelog-style format.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
#6592 as outlined in the issue, only forms that explicitly opt-in can be editable. Please ensure that different values for the `client-editable` attribute are handled correctly.
The other two issues addressed by this pull request are straightforward, and I don’t have any additional comments on them at this time.

#### Do we need any specific form for testing your changes? If so, please attach one.
It's not possible to create an XLS form with `client-editable` attribute but we can edit XML form and add it manually. See: https://github.com/getodk/collect/pull/6690/files#diff-6ef5def9f7159de63970468c76a70f5bb66cf6637408f5e75a13b954707220bfR19

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Yes: https://github.com/getodk/docs/issues/1941

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt [hunk 1]
```diff
@@ -171,6 +172,7 @@ class FormMetadataParserTest {
                                 action="foo" 
                                 orx:auto-send="bar" 
                                 orx:auto-delete="baz" 
+                                orx:client-editable="qux"
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt]: `client-editable` uses the `odk` namespace: https://forum.getodk.org/t/spec-proposal-editable-submissions/53577/8.

We should also make sure to add a test that `client-editable` using a different name space is not parsed (it looks like the implementation is namespace agnostic right now).

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt [hunk 2]
```diff
@@ -30,6 +30,7 @@ object FormMetadataParser {
         val base64RsaPublicKey = submission?.getAttributeValue(null, "base64RsaPublicKey")
         val autoDelete = submission?.getAttributeValue(null, "auto-delete")
         val autoSend = submission?.getAttributeValue(null, "auto-send")
+        val clientEditable = submission?.getAttributeValue(null, "client-editable")
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt]: I think we should convert from a String to a Boolean here (`true` if "true", `false` otherwise) which allows it to be passed around as a `Boolean` instead of a `String?` and should simplify usages.

**Review by seadowg — CHANGES_REQUESTED** [review]
I've just had a quick look at the opt-in part and left a couple of comments (the navigation changes look good), but I also had a broader question: did you consider making the "is editable" concept "in-mem" rather than persisted? Maybe I'm wrong, but I don't think there's currently a reason to have that available outside form entry, so we could just use a `ParseProcessor` and a `FormDef` extra like we do with pulldata/search (see `DynamicPreloadParseProcessor`).

**Comment by grzesiek2010** [comment]
> I've just had a quick look at the opt-in part and left a couple of comments (the navigation changes look good), but I also had a broader question: did you consider making the "is editable" concept "in-mem" rather than persisted? Maybe I'm wrong, but I don't think there's currently a reason to have that available outside form entry, so we could just use a ParseProcessor and a FormDef extra like we do with pulldata/search (see DynamicPreloadParseProcessor).

Yes, that would be possible, but I'm not sure it's the better option. I can see pros and cons for both approaches. let me think out loud:

If we store it in the database, we treat all submission attributes consistently. On the other hand, you're right that this particular flag is a bit different, since we currently don't use it outside of form entry.

However, we could use it elsewhere in the future, and my solution would be more versatile in that case.

With your approach, we avoid increasing the size of the forms database, but we introduce an additional step that would be executed every time a form is opened.

Is growing the forms DB really a problem? I’d say it’s more of a concern for the instances DB, which can get large. The forms DB rarely becomes big enough for that to matter.

So, although we don’t currently need this flag outside form entry, I think I prefer storing it. It saves the value once and doesn’t add another step to every form opening.

Do you agree with my thinking?

File: collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt]: Fixed.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt]: In the database, we store values like `autoDelete`, `autoSend`, and `clientEditable` as strings. They're parsed into booleans after being read from the database. 

In this case, we don’t even need it to be a boolean, since its only purpose is to help build the form that will eventually be saved to the database and as I mentioned, it needs to be a string at that point anyway.

**Review by seadowg — CHANGES_REQUESTED** [review]
> Do you agree with my thinking?

Yes, I totally agree with this analysis: both routes will work and have a relatively similar amount of complexity so choosing the more "future-proof" one (the DB offering more versatility) is a good call.

However, I (annoyingly) just thought of a reason that would push us to use a form parse based approach: opt-in forms being downloaded in older versions of Collect. With the implementation we've got right now, if an opt-in form was downloaded in a currently released version of Collect, instances of it wouldn't be editable after Collect was upgraded until the form is updated. Given that, I do think we should be parsing this flag on form load rather than at form download (and then persisting it).

As an aside: writing the above makes me realize that the more general disadvantage of storing these flags in the DB for things like this is that we of course introduce a second "source of truth" (as opposed to checking the form definition at load).

**Comment by grzesiek2010** [comment]
> With the implementation we've got right now, if an opt-in form was downloaded in a currently released version of Collect, instances of it wouldn't be editable after Collect was upgraded until the form is updated.

That's a good point.

I'm still torn @lognaturel what do you think about those two approaches?

**Comment by grzesiek2010** [comment]
@seadowg it looks like I don't even need to implement any processor I can read submission attributes thanks to `SubmissionProfile`:
image

image

That might make sense, as it removes the concern I mentioned - adding yet another step that would be performed when the form opens. What do you think?

**Comment by seadowg** [comment]
> What do you think?

Ah so we already parse that in JavaRosa Yeah looks good to me!

**Comment by grzesiek2010** [comment]
@seadowg the only problem with this approach is that it ignores namespaces but I think we can file an issue in JR to support that right?

**Comment by seadowg** [comment]
> @seadowg the only problem with this approach is that it ignores namespaces but I think we can file an issue in JR to support that right?

Yeah, that feels like an ok trade-off.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt [hunk 3]
```diff
@@ -30,6 +30,7 @@ object FormMetadataParser {
         val base64RsaPublicKey = submission?.getAttributeValue(null, "base64RsaPublicKey")
         val autoDelete = submission?.getAttributeValue(null, "auto-delete")
         val autoSend = submission?.getAttributeValue(null, "auto-send")
+        val clientEditable = submission?.getAttributeValue("http://www.opendatakit.org/xforms", "client-editable")
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt]: I think the changes to `FormMetadataParser`, `FormMetadata` and their tests can be removed

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java [hunk 4]
```diff
@@ -381,6 +381,7 @@ public void onItemClick(AdapterView<?> parent, View view, int position, long row
             long instanceId = c.getLong(c.getColumnIndex(DatabaseInstanceColumns._ID));
             Intent intent = FormFillingIntentFactory.editDraftFormIntent(this, projectsDataService.requireCurrentProject().getUuid(), instanceId);
             startActivity(intent);
+            finish();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java:384]: This will also return the user to the main menu after viewing a form which is a change in behaviour. I can imagine this being annoying in a flow where you want quickly check forms before you send them, and I don't think we should mess with it.

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt [hunk 5]
```diff
@@ -27,10 +31,15 @@ class LocalInstancesUseCasesTest {
         val instanceDir = File(instancesDirPath + File.separator + "Cool form name_1990-04-24_00-00-00")
         assertThat(instanceDir.exists(), equalTo(true))
         assertThat(instanceDir.isDirectory, equalTo(true))
+
+        TimeZone.setDefault(originalTimeZone)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt]: This clean up won't happen if the test fails. You need to use a `@Before`/`@After` combo or `TestRule` to do this kind of static state manipulation. 

I think an even better approach would be to have the time provider passed to `createInstanceFile` to return a type with a timezone, or have it return a `Pair<Long, Timezone>` so the timezone can be used in the formatter. This is a pretty classic case of the test demonstrating that we need to invert a dependency (time).

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java:384]: As mentioned in the description, when you open a form from the list of sent forms and then close it, you're taken back to the main menu. So why not apply the same behavior to the list of forms to send? It makes the experience more consistent.

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt]: > I think an even better approach would be to have the time provider passed to createInstanceFile to return a type with a timezone, or have it return a Pair<Long, Timezone> so the timezone can be used in the formatter. This is a pretty classic case of the test demonstrating that we need to invert a dependency (time).

I think it would be too much of a balancing act (overkill) for just two tests.

I wrapped the code into try-finally block but we have similar tests without it and they have been working well for years so I don't think it would be a problem.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java:384]: I'm happy to go with it at the moment, and we can always fix it before release if we need to. I'll make sure we've got a discussion item around it.

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt (hunk 5 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt]: > I think it would be too much of a balancing act (overkill) for just two tests.

I do think the test being a bit "awkward" here is a good example of that being a sign that the design of the thing under test could be improved. And, I'd argue that a small change to the design of `createInstanceFile` can remove quite a few lines and complexity from the tests here. For example if we add a `timezone` argument to the function:

```kotlin
fun createInstanceFile(
    formName: String,
    instancesDir: String,
    timezone: TimeZone = TimeZone.getDefault(),
    clock: () -> Long = { System.currentTimeMillis() }
): File? {
    val sanitizedFormName = FormNameUtils.formatFilenameFromFormName(formName)

    val timestamp = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.ENGLISH).also {
        it.timeZone = timezone
    }.format(Date(clock()))

    val instanceDir = instancesDir + File.separator + sanitizedFormName + "_" + timestamp

    if (FileUtils.createFolder(instanceDir)) {
        return File(instanceDir + File.separator + sanitizedFormName + "_" + timestamp + ".xml")
    } else {
        Timber.e(Error("Error creating form instance file"))
        return null
    }
}
```

...then the test doesn't need to care about any static state setup or clean up (or needing to wrap any of it in a `try-finally`):

```kotlin
@Test
fun `#createInstanceFile creates directory based on sanitized form name and current time in instances directory`() {
    val instancesDirPath = TempFiles.createTempDir().absolutePath

    LocalInstancesUseCases.createInstanceFile(
        "Cool form  name:",
        instancesDirPath,
        TimeZone.getTimeZone("UTC")
    ) { 640915200000 }

    val instanceDir = File(instancesDirPath + File.separator + "Cool form name_1990-04-24_00-00-00")
    assertThat(instanceDir.exists(), equalTo(true))
    assertThat(instanceDir.isDirectory, equalTo(true))
}
```

Other than making the test simpler, there are two key advantages to the new design of the implementation here:

1. The function is now idempotent - it will always return the same outputs for the same inputs. Before the use a static `TimeZone` meant that this wasn't the case.
2. The function no longer violates the [dependency inversion principle ](https://en.wikipedia.org/wiki/SOLID) - we're not coupled to the system's default timezone now that timezone is an input (or an explicit dependency).

Of course, this is just small part of our code, and so it's not like this has a huge impact, but I think aiming for focused and modular components at this level helps keep those principles at higher levels where those components get combined.

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6690#discussion_r2041997946

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15

**Verified cases:**

- Different forms with client-editable attribute
- Using different values for client-editable attribute
- client-editable attribute combined with auto send / auto delete
- Listed issues no longer occur:
#6692 
#6681
- Quick regression check on editing finalized forms

**Comment by dbemke** [comment]
**Tested with success**

Verified on device with Android 10
