### PR TITLE
Fixed memory leaks

### LINKED ISSUE #5777: Out of memory, Collect isn't reponding while editing a big form
#### ODK Collect version
the store version 2023.2.4, the master version
#### Android version
8.1, 10, 11, 13
#### Device used
Nexus 5X, Redmi 9T, Samsung M12, Pixel 6a
#### Problem description
Editing a big form with external CSV causes the "Out of memory” crash or "Collect isn’t responding”.  
The results may be a bit different for each reproduction but in general:
- it happens while the form is edited (rather older devices), when the form is saved as draft or finalized (in a form and bulk finalized)
- on Nexus and Redmi (older devices) "Collect isn’t responding” appears almost every time
- on Redmi there was "Out of memory” crash
- on Pixel 6a (Android 13) after repeating steps 4-6 four times there "out of memory” error
- almost on all devices while editing the screen goes white/black for a moment
#### Steps to reproduce the problem
1. In settings auto send  is off.
2. Open Kobo test form.
[Kobo_Test.xlsx.txt](https://github.com/getodk/collect/files/12879412/Kobo_Test.xlsx.txt)
[places.csv.txt](https://github.com/getodk/collect/files/12879415/places.csv.txt)
3. Don’t fill answers, go to the hierarchy view, go to end and save as draft.
4. Go to Drafts and fill the answers.
5. Finalize the form.
6. Edit the finalized form (change all the answers) and finalize again.

If necessary repeat steps 4 – 6. The form can be finalized or saved as draft.

Android 10    and    Android 13
ouofmemory

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5777 

#### Why is this the best possible solution? Were any other approaches considered?
There was a problem with clearing form sessions. Nullifying objects was not enough and somehow garbage collector was not able to get rid of those objects. In the case of big forms (especially those with thousands of choices) the result was that every time we started a new form more and more memory was used:
SelectOneFromFileMaster
with the fix the chart is flat:
Screenshot from 2023-10-16 21-25-59

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This is rather a safe change so testing if the issue does not occur anymore should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
I've used 3 forms. Each with just one select one question with 50k items. The difference between the forms was just the source of choices:
- choices from form XML file [SelectOne.xlsx](https://github.com/getodk/collect/files/12921128/SelectOne.xlsx)
- choices from an external csv file using `select_one_from_file` question [SelectOneFromFile.zip](https://github.com/getodk/collect/files/12921133/SelectOneFromFile.zip)
- choices from an external csv file using `select_one` question with the search function [SelectOneSearch.zip](https://github.com/getodk/collect/files/12921126/SelectOneSearch.zip)

The two first forms caused memory leaks.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt [hunk 1]
```diff
@@ -37,8 +39,16 @@ class AppStateFormSessionRepository(application: Application) : FormSessionRepos
         getLiveData(id).value = FormSession(formController, form, instance)
     }
 
+    /**
+     * Ensure the object gets completely removed. Simply nullifying it might cause memory leaks.
+     * See: https://github.com/getodk/collect/issues/5777
+     */
     override fun clear(id: String) {
-        getLiveData(id).value = null
+        appState.clear(getKey(id))
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: I don't have a lot of experience with garbage collection but this seems like a bug to me... with the old way of removing objects (by nullifying them), the session object (the main object) was garbage collected but not the properties inside eg. not the `formController` which in this case is the object that consumes a lot of memory. But if we remove the object from the map at all, then everything is fine.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: Great find! I guess the big difference here will be that setting the old version `getLiveData(id).value = null` would set the `LiveData` in the map to `null` which would propagate the value to any observers, but the `LiveData` itself wouldn't be garbage collected. The new code will remove the `LiveData` from the map meaning that it can be garbage collected.

My hunch would be that there is an observer that wasn't getting unregistered somehow. That would mean that it would be referenced by the `LiveData` and so if the `LiveData` wasn't garbage collected it wouldn't be. It'd be good to find the offender here so we can make sure we've fixed any other potential memory leaks from an observer hanging around.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: Ah! Looks like it could be `FormSaveViewModel`: https://github.com/getodk/collect/blob/3d66ab17f4d2724326fda3c94e251394bb1735bd/collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java#L106

We never unregister that observation, so the `FormSaveViewModel` will continue to be referenced by the `LiveData`. We do the correct clean up in `BackgroundAudioViewModel` (unregistering the observation in `onCleared`). I wonder if you can fix that and the memory leak will go away?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: `ViewModel` should be destroyed after closing the activity so isn't it cleared automatically? I will test it but even if it's true it's very error-prone because it's easy to forget about clearing livedata...
I think in this case probably we should first call:
`getLiveData(id).value = null`
so that as you said null value is propagated and then
`appState.clear(getKey(id))`
to avoid memory leaks

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: > ViewModel should be destroyed after closing the activity so isn't it cleared automatically?

Yes, but the `LiveData` will have a reference to the ViewModel (as an observer) and the `LiveData` still lives in `AppState` so it won't be cleared out. `onCleared` gets called when the Activity is destroyed to give you a chance to clean things like that up (as we do in `BackgroundAudioViewModel`).

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: AppState (in this case) stores a map of `MutableLiveData<FormSession>` for given key. With the old way of clearing it we assigned null to that key. Shouldn't that be enough for GC to clear everything? If we nullify the livedata the observers should be gone too. The only change I implemented is removing livedata from the map instead of nullifying it. I'm not saying that your theory is wrong but still is that behavior ok because it still seems to me like a bug.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: Maybe it's because of the fact that `getLiveData(id).value = null` does not nullify the livedata directly but assigns null to the key that the livedata was represented by in the map... but still, such a livedata is then not used anywhere (apart from the ViewModel which should be destroyed after closing its activity) then so GC should be able to get rid of it?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: I think from GC perspective I don't really get the difference between removing livedata from the map by setting the value to null vs removing it from the map completely. In both cases, we do not nullify the livedata directly but as I discovered in this pr the latter works well.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: > Maybe it's because of the fact that getLiveData(id).value = null does not nullify the livedata directly but assigns null to the key that the livedata was represented by in the map... but still, such a livedata is then not used anywhere (apart from the ViewModel which should be destroyed after closing its activity) then so GC should be able to get rid of it?

With `getLiveData(id).value = null` we still end up with the map referencing the `LiveData` instance, it's just that the **value** of that `LiveData` is `null`. Given `AppState` is referenced by the `Application` instance (an instance of `Collect`), that `LiveData` will not be garbage collected. If there's an observer registered to the `LiveData`, we'd end up with a reference chain like this:


```
Collect -> AppState -> (via the map) LiveData -> Observer
```


If the `Observer` is a `ViewModel`, you're right that it'll get destroyed when the Activity is destroyed, but only in the sense that the Activity will call `onCleared` and stop referencing it - the `ViewModel` would still be referenced by the `LiveData` which means that it wouldn't get garbage collected. It's Android "destruction" vs actual destruction in memory.

My hunch is that when you changed the line to `appState.clear(getKey(id))` you changed it so that the chain to `ViewModel` after Activity destruction would just be:

```
LiveData -> Observer
```

As nothing references the `LiveData` anymore, we have an "orphaned" graph that can be garbage collected. 

I could definitely be wrong about all this, but I think it's worth experimenting with an `onCleared` in `FormSaveViewModel` that unregisters it as an observer and seeing if that would also fix the memory leak. 

The current fix changes the behaviour of `FormStateRepository` subtly as `clear` now means that any subsequent calls to `get`/`set` with the same ID would deal with a different `LiveData` instance (meaning observations before the `clear` call wouldn't get updates).

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt:46]: Ah right after calling `getLiveData(id).value = null` it's still livedata but with a null value, I assumed that it nullifies the whole livedata in the map ok so it's clear...
So probably it can't be garbage collected because despite the fact that the livedata has a null value it has an observer in the view model and that view model keeps a reference to formControler and it can't be removed.
It's very easy to make such mistakes.

**Comment by grzesiek2010** [comment]
This issue was introduced a year ago so it took us some time to spot it. Taking into account that in Firebase we see many crashes caused by the lack of memory I think we should consider the next steps to avoid issues like this one in the future:
- we should test other big forms (especially using the profiler available in Android Studio)
- we should verify that the LeakCanary app works as expected (I haven't seen any reports recently and also this one seems like something that could be caught)
- we should consider choosing for example 2 forms and testing them (with the profiler) before each release to make sure there are no leaks like this one

@lognaturel what do you think?

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt [hunk 2]
```diff
@@ -51,8 +51,11 @@ abstract class FormSessionRepositoryTest {
         val formController = mock<FormController>()
         val form = mock<Form>()
         formSessionRepository.set(id, formController, form)
+        assertThat(formSessionRepository.has(id), equalTo(true))
+        val liveData = formSessionRepository.get(id)
 
         formSessionRepository.clear(id)
-        assertThat(formSessionRepository.get(id).getOrAwaitValue(), equalTo(null))
+        assertThat(liveData.getOrAwaitValue(), equalTo(null))
+        assertThat(formSessionRepository.has(id), equalTo(false))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt]: I think instead of adding `has`, you could test that the `LiveData` obtained after `clear` is different from the one before. That's a change in behaviour I think we should make sure is specified in a test because it's a subtle - an observation set up for a form session will no longer work after a `clear` call (which makes sense I think).

**Review by seadowg — CHANGES_REQUESTED** [review]
> we should verify that the LeakCanary app works as expected (I haven't seen any reports recently and also this one seems like something that could be caught)


It looks like it doesn't:

Screenshot 2023-10-18 at 09 05 24

I think that's worth trying to fix here.

We should also verify that we get Leak Canary in the builds that QA use (`selfSignedRelease`).

File: collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt]: Done.

**Comment by seadowg** [comment]
@grzesiek2010 I've changed the base branch of the PR, but you'll need to rebase your commits onto `v2023.3.x`

**Comment by grzesiek2010** [comment]
> @grzesiek2010 I've changed the base branch of the PR, but you'll need to rebase your commits onto v2023.3.x

Done. I will try to take a look at LeakCanary but this should not block this issue so I think we can start testing.

**Review by seadowg — APPROVED** [review]

**Comment by lognaturel** [comment]
> @lognaturel what do you think?

I think I love the plan! @seadowg and I have also talked about doing some memory profiling to make sure we didn't underestimate the memory impact of https://github.com/getodk/javarosa/pull/715 as we extend the pattern to selects. Maybe we combine these two profiling tasks into a single issue? I don't think there is one yet.

> we should consider choosing for example 2 forms and testing them (with the profiler) before each release to make sure there are no leaks like this one

Do you see this as something dev or QA would do? I think it's a good idea, at least when we touch code related to form loading.

**Comment by grzesiek2010** [comment]
> Maybe we combine these two profiling tasks into a single issue? I don't think there is one yet.

sounds good.

> Do you see this as something dev or QA would do?

I would rather say it's more for devs... I think the QA team would also be able to do that if we teach them how it works but during regression testing, they already have a lot of work so maybe it's better not to add anything for them.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 5.1, 12, 13

Verified cases:
- Issue #5777 is no longer reproducing;
- Regression check on other Big Forms;
- Checked forms from Issue: [SelectOne.xlsx](https://github.com/getodk/collect/files/12921128/SelectOne.xlsx), [SelectOneFromFile.zip](https://github.com/getodk/collect/files/12921133/SelectOneFromFile.zip), [SelectOneSearch.zip](https://github.com/getodk/collect/files/12921126/SelectOneSearch.zip);

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 8.1, 10
