### PR TITLE
Throw an exception when there is an attempt to access file outside of Collect directory

### LINKED ISSUE #6364: Guard against incorrect paths
#### Problem description
In [PR #6340](https://github.com/getodk/collect/pull/6340), we introduced a check to determine if paths were pointing to locations within the provided `dirPath`. This was further refined in [PR #6357](https://github.com/getodk/collect/pull/6357), and eventually, in [PR #6363](https://github.com/getodk/collect/pull/6363), the check was partially disabled, logging a non-fatal event instead of throwing an exception.

Thanks to [PR #6363](https://github.com/getodk/collect/pull/6363), we identified an issue with the original path comparison. Occasionally, after calling `getCanonicalPath`, the case of some letters in the path would change, such as:
`/storage/emulated/0/android/data/org.odk.collect.android/files/projects/`
instead of `/storage/emulated/0/Android/data/org.odk.collect.android/files/projects/`.

#### What we need to do
1. Revert the code from the `androidshared` module back to the `shared` module: https://github.com/getodk/collect/pull/6363/commits/8f05e2813bf24faf00606ea79104fd7b4a533d4f
2. Reintroduce the `SecurityException` throw: https://github.com/getodk/collect/pull/6363/commits/f9377c42ca43ebd1f4ad243393aa2d448ce996de#diff-a8a1c2c9a690d0a3c02bd93865b8ee78dc4fea28e39dc1b59adf60437c71257eL14
3. Enhance path comparisons by making them case-insensitive: https://github.com/getodk/collect/pull/6363/commits/f9377c42ca43ebd1f4ad243393aa2d448ce996de#diff-a8a1c2c9a690d0a3c02bd93865b8ee78dc4fea28e39dc1b59adf60437c71257eR14

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6364 

#### Why is this the best possible solution? Were any other approaches considered?
It seems that sanitizing paths the way we currently do is sufficient, as we haven't seen any new reports in v2024.3.x.
Given this, we can reintroduce crashing the app in cases where paths don't match, indicating an attempt to access a file outside of the Collect directory.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: shared/src/main/java/org/odk/collect/shared/PathUtils.kt [hunk 1]
```diff
@@ -10,4 +13,16 @@ object PathUtils {
     // https://stackoverflow.com/questions/2679699/what-characters-allowed-in-file-names-on-android
     @JvmStatic
     fun getPathSafeFileName(fileName: String) = fileName.replace("[\"*/:<>?\\\\|]".toRegex(), "_")
```
Comment (seadowg) [inline shared/src/main/java/org/odk/collect/shared/PathUtils.kt:15]: I think we should lock this behaviour in with a test if we're confident about it now.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Comment by seadowg** [comment]
@lognaturel tagging you in on a review here as well as I was away when a lot of the discussions about this happened.

File: shared/src/main/java/org/odk/collect/shared/PathUtils.kt (hunk 1 above)
Comment (grzesiek2010) [reply shared/src/main/java/org/odk/collect/shared/PathUtils.kt:15]: What do you mean? This method has nothing to do with the issue we had with paths.

Comment (seadowg) [reply shared/src/main/java/org/odk/collect/shared/PathUtils.kt:15]: Sorry! I meant to comment on `getAbsoluteFilePath`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: shared/src/main/java/org/odk/collect/shared/PathUtils.kt (hunk 1 above)
Comment (grzesiek2010) [reply shared/src/main/java/org/odk/collect/shared/PathUtils.kt:15]: This wouldn't be easy. We have tests for `#sanitizedCanonicalPath` we can't write the same tests for `#getAbsoluteFilePath` because the values we pass to `#getAbsoluteFilePath` are not broken. The problem was with `#canonicalPath` called by `#getAbsoluteFilePath` (then broken paths ocurred), so I replaced it with `#sanitizedCanonicalPath` and that one is covered with tests.

**Review by seadowg — APPROVED** [review]

**Review by lognaturel — APPROVED** [review]
I've verified that the `getAbsoluteFilePath` function in the new location does the same tests as the old one. I verified that `sanitizedCanonicalPath` does what I expect.
