### PR TITLE
Replace asynctask uploader with viewmodel

### LINKED ISSUE #6827: A form doesn’t get auto deleted after canceling sending a finalized form and opening it
#### ODK Collect version
the store version 2025.2.1, 2025.3.0 beta 1, the master version 83b67fd1b39fd41a92f22092d52d2f858f2aa35e and 9589d050bb4cb676a727367b297aa0825400ae06
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
A form doesn’t get auto deleted after canceling sending a finalized form and opening it. The submission is sent to the server. I managed to eliminate some steps/factors, but I'm still not sure if all of the steps are necessary.

#### Steps to reproduce the problem
1. Download a project with All widgets form.
2. In Settings- form management set Auto send to off and enable delete after send.
3. Finalize 3 all widgets forms with a big attachment (so that sending takes more time).
4. Go to "Ready to send" and tap select all, send selected.
5. Cancel sending the first form (when there sending 1 out of 3).
6. In "ready to send" open the form which sending was canceled, exit the form. <- OR Go to Main menu and reopen "ready to send"
7. Tap select all, send selected.
8. Cancel sending the second form (when there sending 2 out of 3)
9. Go to "Sent" and check if the form was deleted.
#### Expected behavior
The form should be auto deleted

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6827 

#### Why is this the best possible solution? Were any other approaches considered?
The issue itself was not significant and could be fixed without major changes. However, it was based on a long-deprecated `AsyncTask`, so it was a good opportunity to replace it with modern architecture components, which I did while also ensuring the issue was properly addressed.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to carefully test the entire process of manually uploading finalized forms (from the list of forms to send), as this functionality has been refactored.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploader.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package org.odk.collect.android.instancemanagement.send
+
+import org.odk.collect.forms.instances.Instance
+
+interface InstanceUploader {
+    @Throws(FormUploadException::class)
+    fun uploadOneSubmission(instance: Instance, urlString: String): String?
+
+    fun getUrlToSubmitTo(instance: Instance, deviceId: String?, overrideURL: String?): String
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploader.kt]: It's strange that this is exposed because the return value is always used as the `urlString` parameter for `uploadOneSubmission` and nothing else. I think this should just be internal to the implementation and then the values needed should be passed in to `uploadOneSubmission`.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderActivity.java [hunk 2]
```diff
@@ -167,48 +228,32 @@ private void init(Bundle savedInstanceState) {
...
-        if (instanceUploaderTask == null) {
-            // set up dialog and upload task
-            showDialog(PROGRESS_DIALOG);
-            instanceUploaderTask = new InstanceUploaderTask();
+        showDialog(PROGRESS_DIALOG);
 
-            if (url != null) {
-                instanceUploaderTask.setCompleteDestinationUrl(url + OpenRosaConstants.SUBMISSION, getReferrerUri(), true);
+        if (url != null) {
+            instanceUploaderViewModel.setCompleteDestinationUrl(url + OpenRosaConstants.SUBMISSION, getReferrerUri(), true);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderActivity.java]: I think all this setup could just happen in the constructor of `InstanceUploadViewModel` right? Then we wouldn't have to have any of that state be mutable.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderActivity.java [hunk 3]
```diff
@@ -368,19 +396,15 @@ private void createUploadInstancesResultDialog(String message) {
     @Override
     public void updatedCredentials() {
         showDialog(PROGRESS_DIALOG);
-        instanceUploaderTask = new InstanceUploaderTask();
 
-        // register this activity with the new uploader task
-        instanceUploaderTask.setUploaderListener(this);
         // In the case of credentials set via intent extras, the credentials are stored in the
         // global WebCredentialsUtils but the task also needs to know what server to set to
         // TODO: is this really needed here? When would the task not have gotten a server set in
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderActivity.java]: I agree with this comment! Let's just get rid of this and see if QA can break anything there. It doesn't make sense that we need to reset the server URL here.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+                    } catch (e: FormUploadException) {
+                        results[instance.dbId.toString()] = e.message
+                    }
+                }
+            } finally {
+                deleteInstances(results)
+            }
+
+            clearTemporaryCredentials()
+            instancesDataService.update(projectId)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt:74]: Could we move most of this method into the `InstanceDataService`? I'm wondering if `sendInstances` could just be adapted to provided progress updates, auth failure etc via callbacks.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt:74]: Yes, there was a mess there...
Here we used `InstanceUploader` directly, but to send instances automatically, it was `InstanceDataService` -> `InstanceSubmitter` -> `InstanceUploader`. I've refactored the code so that now in both cases it's the same approach `InstanceDataService` -> `InstanceSubmitter` -> `InstanceUploader`.

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java [hunk 5]
```diff
@@ -237,8 +237,8 @@ public void setComponent(AppDependencyComponent applicationComponent) {
      * @param formVersion version of a form
      * @return md5 hash of the form title, a space, the form ID
      */
-    public static String getFormIdentifierHash(String formId, String formVersion) {
-        Form form = new FormsRepositoryProvider(Collect.getInstance()).create().getLatestByFormIdAndVersion(formId, formVersion);
+    public static String getFormIdentifierHash(FormsRepository formsRepository, String formId, String formVersion) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: I think we should rework the logging here slightly to make it more consistent with how we do events now. We can remove this method and replace the logging call with `AnalyticsUtils.logFormEvent`. 

Then, instead of tracking auto/manual through a key/value we can just have "SubmissionAuto" and "SubmissionManual" events (these can always be added up to get the total). Alternatively, we could just remove that detail @lognaturel? 

To track HTTP/HTTPS usage (which is definitely going to be useful with upcoming network security changes to Android), we should use a user property that gets set to `true` if a non-HTTPS submission ever happens (like with `HasEntityListCollision`).

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceSubmitter.kt [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+import org.odk.collect.shared.settings.Settings
+import timber.log.Timber
+
+class InstanceSubmitter(
+    private val instanceUploader: InstanceUploader,
+    private val projectDependencyFactory: ProjectDependencyFactory<ProjectDependencyModule>,
+    private val propertyManager: PropertyManager
+) {
+
+    suspend fun submitInstances(
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceSubmitter.kt]: Is there any reason for this to be a `suspend` function other than `ensureActive`? In both cases it's called the concurrency is being handled at the call site. I think we could remove any concept of concurrency and the complexity that comes with it here by just passing an optional `ensureActive` block. That block could then be passed through from the `ViewModel` that's actually in charge of the concurrent operation and neither the data service nor the use case need to care.

**Review by seadowg — CHANGES_REQUESTED** [review]
Just posting another structural change I think would be good here!

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceSubmitter.kt (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceSubmitter.kt]: > Is there any reason for this to be a suspend function other than ensureActive?

Yes.

> I think we could remove any concept of concurrency and the complexity that comes with it here by just passing an optional ensureActive block. 

Done.

File: collect_app/src/main/java/org/odk/collect/android/application/Collect.java (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: > I think we should rework the logging here slightly to make it more consistent with how we do events now. We can remove this method and replace the logging call with AnalyticsUtils.logFormEvent.

Done.

When it comes to the second part of the comment, let's wait for @lognaturel to respond. We can also do that in a separate PR, so it shouldn't block this one.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: The only reason I'd want to keep things the same is to get a sense of historical context but unfortunately it looks to me like neither the send method info nor the server hash is correctly being set right now. I see `(not set)` for most submissions.

I don't think we need to track auto vs manual submission anymore. I can't think of an action we would take based on those numbers right now.

Unless I'm misremembering, I don't think we tracked HTTP vs HTTPS, just HTTP vs sheets. We don't send sheets anymore. So maybe we remove that as well? Or we change it to track HTTP vs HTTPS to get a sense of the impact of the upcoming change.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/application/Collect.java]: I've updated logging to include HTTP vs HTTPS.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+        setTemporaryCredentials()
+    }
+
+    fun upload(instanceIdsToUpload: List<Long>) {
+        if (_state.value !is UploadState.Idle && _state.value !is UploadState.AuthRequired) {
+            return
+        }
+        _state.value = UploadState.Starting
+
+        uploadJob = viewModelScope.launch(dispatcher) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: I think we should use this to make a decision about the future when it comes to using coroutines directly vs `Scheduler`. Currently, `Scheduler`'s main advantage is that it can be used from Java and Kotlin meaning the async approach being used is consistent. As far as I can see, testing seems pretty similar between the two at this point. There are obviously many advantages to just using coroutines directly.

I'm going to assume from you using coroutines directly here that you think we should ditch using scheduler for "immediate" async work in Kotlin?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: I wouldn’t say I’m strongly leaning toward one option over the other. Right now, Scheduler is mainly used for starting background tasks, and in this case I needed more control, especially the ability to cancel the work.

Of course, we could probably extend Scheduler to support that as well. But in this PR we already introduced quite a bit of refactoring beyond just fixing the issue, so I think it makes sense to draw the line somewhere.

What's your opinion?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: > What's your opinion?

The other advantage to `Scheduler` is that it protects our code from async framework changes. Here you're using a mixture of Kotin language features (basically `suspend` functions) and an async framework (`CoroutineScope`, `CoroutineDispatcher` and `Job` from `kotlinx.coroutines`). 

If we want to continue with that advantage but also use `suspend` functions more directly and get good cancellation features, we could add `suspend` support to `Scheduler` and return the `Cancellable` abstraction we already have. Something like:

```kotlin
fun <T> immediate(work: (isCancelled: Boolean) -> Unit): Cancellable
```

We'd need to add even more abstraction to deal with `viewModelScope` though. I'm not sure it's worth it: it seems pretty overprotective to try and avoid `kotlinx.coroutines` at this point. I'm leaning towards saying that we deprecate the "foreground" parts of `Scheduler` and just embrace `kotlinx.coroutines`. How does that sound?

**Review by seadowg — COMMENTED** [review]
https://github.com/getodk/collect/pull/7008#discussion_r2989074772

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt (hunk 7 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: One thing I think is worth calling out explicitly is what we lose on the testing side. With `Scheduler` (and especially `FakeScheduler`) we currently have very fine-grained, deterministic control over execution — we can decide exactly when background and foreground work runs (e.g. `flush()`, `runFirstBackground()`, etc.) and assert intermediate states very precisely.

With coroutines, we’d be moving to `TestDispatcher`/`runTest`/`advanceUntilIdle()`, which works well but gives us less direct control over execution order and scheduling. In most cases this is probably an acceptable tradeoff, but it does change how we write and reason about tests.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: > One thing I think is worth calling out explicitly is what we lose on the testing side. With Scheduler (and especially FakeScheduler) we currently have very fine-grained, deterministic control over execution — we can decide exactly when background and foreground work runs (e.g. flush(), runFirstBackground(), etc.) and assert intermediate states very precisely.

Interesting. I'd thought we had the same level of control from looking at your test code here. Is there an example test somewhere that we would have a hard time writing with the test dispatcher setup?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: With `FakeScheduler`, we can control execution **step by step**, separating background and foreground work. For example:

```kotlin
class MyViewModel(
    private val scheduler: Scheduler,
    private val repo: MyRepository
) : ViewModel() {

    val state = MutableLiveData<String>("Idle")

    init {
        scheduler.immediate(
            background = Supplier {
                state.postValue("Loading")         // background step
                repo.getData()                     // fetch data
            },
            foreground = Consumer { data ->
                state.postValue("Loaded: $data")  // foreground step
            }
        )
    }
}
```

```kotlin
// ViewModel using FakeScheduler
val vm = MyViewModel(FakeScheduler(), repo)
assertEquals("Idle", vm.state.value)           // before any task runs

fakeScheduler.runFirstBackground()             // only background task
assertEquals("Loading", vm.state.value)        // intermediate state

fakeScheduler.runForeground()                  // run everything on foreground
assertEquals("Loaded: hello", vm.state.value)  // final state
```

This lets us assert **intermediate states** very precisely.

With coroutines and `TestDispatcher` / `advanceUntilIdle()`, we can still test the final outcome:

```kotlin
class MyViewModel2(
    private val repo: MyRepository,
    private val dispatcher: CoroutineDispatcher
) : ViewModel() {

    val state = MutableLiveData<String>("Idle")

    init {
        viewModelScope.launch(dispatcher) {
            state.value = "Loading"           
            val data = repo.getData()        
            state.value = "Loaded: $data"     
        }
    }
}
```

```kotlin
val vm = MyViewModel2(StandardTestDispatcher(testScheduler), repo)
assertEquals("Idle", vm.state.value)

advanceUntilIdle()                             // runs everything
assertEquals("Loaded: hello", vm.state.value)  // final state
```

…but it’s harder to observe or control **partial execution steps**, because background and foreground updates run together when the dispatcher is advanced.

For most cases, this is probably fine and coroutines give us simpler, more native async handling. But for scenarios where we want fine-grained control over intermediate states (like tasks that update state in multiple steps), `FakeScheduler` still offers advantages.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: So I just wanted to point out that in some cases, testing might be harder, but that should be fine.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: Right I see what you're getting at. I don't think your examples are quite the same though - the concurrency models/behaviour are different. We're only able to test the intermediate state with `FakeScheduler` because the code under test splits the work into "background" and "foreground" work whereas the coroutine based implementation is just running everything as a single `suspend` block that is executed as a unit by the passed `dispatcher`. The coroutine code should look more like this for it to be equivalent to the `Scheduler` example:

```kotlin
class MyViewModel2(
    private val repo: MyRepository,
    private val foregroundDispatcher: CoroutineDispatcher,
    private val backgroundDispatcher: CoroutineDispatcher
) : ViewModel() {

    val state = MutableLiveData<String>("Idle")

    init {
        viewModelScope.launch(foregroundDispatcher) {
            state.value = "Loading"
            val data = withContext(backgroundDispatcher) {
                repo.getData()
            }
        
            state.value = "Loaded: $data"     
        }
    }
}
```

This is essentially the same as how we implement `Scheduler` with coroutines (in `CoroutineTaskRunner`). 

As far as I can tell, we'd be able to write the equivalent test for this code by passing separate test dispatchers that we can control independently as `foregroundDispatcher` and `backgroundDispatcher`. Does that work? Or, is there still things that would make the testing more awkward that I'm missing?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: Ahh, ok that would work. Cool! But I’m not entirely sure we shouldn’t extend our scheduler to support provided scopes. It’s not that complex, and it still might be nice to inject a single scheduler instead of two dispatchers when testing. What do you think? See https://github.com/getodk/collect/pull/7008/changes/6bf0b9693c09da9db9da31d27d27a6735a0aa07f

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: > But I’m not entirely sure we shouldn’t extend our scheduler to support provided scopes.

This goes back to my earlier comment:

> The other advantage to Scheduler is that it protects our code from async framework changes. Here you're using a mixture of Kotin language features (basically suspend functions) and an async framework (CoroutineScope, CoroutineDispatcher and Job from kotlinx.coroutines).

Adding support for `CoroutineScope` (and returning `Job`) to `Scheduler` means that the interface now depends on `kotlinx.coroutines`. Given that, I'm not sure it's worth wrapping really? To make injection easier we could just add our own `DispatcherProvider` interface that provides a foreground and background dispatcher, and then we can just use all the `kotlinx.coroutines` stuff directly. That also lets us do things like collect a `Flow` without "breaking" our encapsulation rules.

**Review by seadowg — COMMENTED** [review]
https://github.com/getodk/collect/pull/7008#discussion_r3000529461

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt (hunk 7 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderViewModel.kt]: Ok, let’s continue with the `DispatcherProvider` interface.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt [hunk 8]
```diff
@@ -214,17 +213,32 @@ class InstancesDataService(
...
-        val projectDependencyModule =
-            projectDependencyModuleFactory.create(projectId)
-
-        val instanceSubmitter = InstanceSubmitter(
-            projectDependencyModule.formsRepository,
-            projectDependencyModule.generalSettings,
-            propertyManager,
-            httpInterface,
-            projectDependencyModule.instancesRepository
+    fun sendInstances(
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt:216]: I think this probably needs protection with the instances lock right?

**Review by seadowg — CHANGES_REQUESTED** [review]
Could you also update the `STATE.md` with decision around using coroutines in Kotlin code?

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt (hunk 8 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt:216]: Done.

File: docs/STATE.md [hunk 9]
```diff
@@ -42,7 +43,7 @@ The purpose of this document is to give anyone who reads it a quick overview  of
 * Moving towards a ["data services"](data_services_architecture.pdf) oriented architecture that has emerged over time
 * Writing new code using a [multi-module approach](CODE-GUIDELINES.md#gradle-sub-modules) (feature modules, mini frameworks etc) and breaking old code out into modules when opportunities come up
 * Trying to remove technical debt flagged with `@Deprecated`
-* Replacing async work such as `AsyncTask` with `Flow` (converted to `LiveData` in UI code) + `Scheduler` abstraction
+* Replacing async work such as `AsyncTask` with `Flow` (converted to `LiveData` in UI code) and replacing the previous `Scheduler` abstraction with lifecycle-aware coroutines (such as `viewModelScope`)
```
Comment (seadowg) [inline docs/STATE.md:46]: Should we deprecate the "immediate..." methods on `Scheduler` as well do you think?

**Review by seadowg — APPROVED** [review]

File: docs/STATE.md (hunk 9 above)
Comment (grzesiek2010) [reply docs/STATE.md:46]: Yeah we can do that too.

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16 

**Verified cases:**

- issue #6827 does not occur
- Sending and finalizing forms
- Different auto send settings
- Forms with auto send true and false
- Different blank form update settings
- Finalizing forms on import on/off

**Comment by dbemke** [comment]
**Tested with success**

Verified on Android 10
