### PR TITLE
Cancel Geopoint dialog when pressing back

### LINKED ISSUE #5018: Back button doesn't close Geopoint dialog
#### Software and hardware versions 

Collect v2022.1.0

#### Problem description

The back button doesn't do anything while the Geopoint dialog is up.

#### Steps to reproduce the problem

1. Open a form with a `geopoint` question
2. Navigate to the question and hit "Start GeoPoint"
3. Press back

#### Expected behavior

The back button should return to the form.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5018 

#### What has been done to verify that this works as intended?

New tests and verified manually.

#### Why is this the best possible solution? Were any other approaches considered?

Comment inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to check using (and cancelling/dismissing) the Geopoint dialog but nothing else has been touched.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/OnBackPressedKeyListener.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package org.odk.collect.androidshared.ui
+
+import android.content.DialogInterface
+import android.view.KeyEvent
+
+class OnBackPressedKeyListener(private val onBackPressed: () -> Unit) : DialogInterface.OnKeyListener {
+    override fun onKey(dialog: DialogInterface?, keyCode: Int, event: KeyEvent?): Boolean {
+        event?.let {
+            if (it.action == KeyEvent.ACTION_DOWN && it.keyCode == KeyEvent.KEYCODE_BACK) {
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/ui/OnBackPressedKeyListener.kt:9]: This (surprisingly) feels like the cleanest way to achieve what we want here. The only other option I could think of is to use `setCanceledOnTouchOutside` and `setOnCancelListener` but we that's much more awkward to test ("canceledOnTouchOutside" isn't exposed as state anywhere).

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**
Verified on Android 10 and 11

Verified cases:
- Using "Back button" after starting geopoint;
- Regression tests on geopoint widgets;
- Minimazing and blocking the app, rotating the screen;
- Light and dark theme.

**Comment by kkrawczyk123** [comment]
**Tested also on Androids 5.1 and 8.1**
