### PR TITLE
Friendly error message when submissions closed.

### LINKED ISSUE #3428: Improve error message when "Accept submissions" is disabled
#### Software and hardware versions 
Collect v1.24.1
Android v8.1.0

#### Problem description
When a form is not marked to "Accept submissions" under Forms Management --> Forms List on the ODK aggregate server, attempting to fill out and send the form on ODK Collect displays a dialog with a cryptic error message with technical information.
accept submissions error

#### Steps to reproduce the problem
**ODK Aggregate**
1. Create a form (or reuse an existing form), marking it to not "Accept submissions" (make sure the checkbox is unchecked)

**ODK Collect**
1. Select "Get Blank Form" and select the form you created above.
2. Select "Fill Blank Form", fill in the form, and mark the form as finalized
3. Select "Send Finalized Form", select the form, and send
4. The error message shown above should be displayed

#### Expected behavior
The app should recognize that the form is not marked to accept submissions, and inform the user.
If recognizing that status of the "Accept submissions" form is difficult, the app should offer a helpful hint to the user, with something like
> Failed to upload (name of form)
> Please make sure (name of form) is configured to accept submissions on the server

### PR DESCRIPTION
**Pull request by rajkumaar23**
Signed-off-by: Rajkumar S <rajkumaar2304@icloud.com>

Closes #3428 

#### What has been done to verify that this works as intended?
- A form was created on ODK aggregate and tried to submit from ODK collect, it works. 
- The same form was turned off for submissions, and then a friendly error message pops up. 

image

#### Why is this the best possible solution? Were any other approaches considered?
- Changing the error message like this was the best solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
- It lets the users get a more human-friendly feedback.

#### Do we need any specific form for testing your changes? If so, please attach one.
- No, any form that is turned off for submissions is good to test.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
- No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@lognaturel I'm not quite sure why the unit tests fail. Is there something I can do ?

**Comment by seadowg** [comment]
~~@rajkumaar23 did the tests all pass locally for you?~~

@rajkumaar23 looks like it was an error on Circle CI. I'll move on with a review!

File: collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java [hunk 1]
```diff
@@ -205,8 +205,8 @@ public String uploadOneSubmission(Instance instance, String urlString) throws Up
                     if (messageParser.isValid()) {
                         exception = new UploadException(FAIL + messageParser.getMessageResponse());
                     } else {
-                        exception = new UploadException(FAIL + postResult.getReasonPhrase()
-                                + " (" + responseCode + ") at " + urlString);
+                        Timber.i(FAIL + postResult.getReasonPhrase() + " (" + responseCode + ") at " + urlString);
+                        exception = new UploadException("Failed to upload. Please make sure the form is configured to accept submissions on the server");
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: I'd imagine there are other errors that can happen here. Would you be able to investigate and see if you can find how to "detect" that we are seeing a "submission closed" error? Potentially the HTTP response code is a way for us to make that decision. Once we have that I think we'd want to have a test that for the decision in place. Happy to chat about the best way to do that 😁

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java (hunk 1 above)
Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Well, so a `400` always tells us submission closed in this case ?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Hmm I don't think so as it's just the generic [Bad Request status](https://www.flickr.com/photos/girliemac/6540669737/in/album-72157628409467125/). Maybe something more interesting comes back in the response body?

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Will check that! :+1:

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: So, this is what is coming in the body : 
```html
<body>
    <h1>HTTP Status 400 – Bad Request</h1>
    <hr class="line" />
    <p><b>Type</b> Status Report</p>
    <p><b>Message</b> Submissions have been disallowed on this form</p>
    <p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p>
    <hr class="line" />
    <h3>Apache Tomcat/8.5.39 (Ubuntu)</h3>
</body>
```
We can use the **Message** to identify. But how do I check that ?

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: What way would you suggest other than this?
image

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Hmmm it's surprising to me that Aggregate errors don't come back in an `OpenRosaResponse` format (Open Rosa is the standard for the different servers that Collect can speak to) but looking at the [docs](https://docs.opendatakit.org/openrosa-form-submission/#form-submission) I'm not sure that's actually expected. 

@lognaturel are you able to chime in here? Has there been previous though about how to support errors coming back from Open Rosa servers that are more specific than HTTP status codes or is it generally uncharted waters? If so maybe we should be using a more specific response code in Aggregate here (401/403 for example) and then have Collect have error messages closer to the errors [here](https://docs.opendatakit.org/openrosa-form-submission/#server-status-codes).

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: What can I possibly do now ?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Sorry @rajkumaar23. There's a very small team of people working on all the ODK tools and we're mostly in different timezones so discussions can move pretty slowly! If you'd like to look at some other issues to contribute to I'd check the ["good first issue"](https://github.com/opendatakit/collect/labels/good%20first%20issue) tag. If you do want to look at something else let me know and we can close this PR for the moment and move discussion to the issue.

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: @seadowg No problem. Let's wait for @lognaturel to reply :)

Comment (rajkumaar23) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: @lognaturel Could you please help?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java:209]: Thanks for taking this on and apologies for the delay in getting back to you, @rajkumaar23.

The first part of the `if` on line 205 displays an `OpenRosa` response if there is one. I wasn't completely sure that was done here but it is and it's just that Aggregate doesn't send a helpful response. Since Aggregate is no longer in active development (https://github.com/getodk/central is the replacement), I think we should handle it here.

I propose that we use the message you put in, @rajkumaar23, but that we do it in a branch just for 400. That is, if there's a custom message, show the custom message (existing behavior), else if the response code is 400, use the special text you've added, for any other response code, use the reason phrase (existing behavior).

**Comment by rajkumaar23** [comment]
@lognaturel I have made changes as per the suggestions. :+1:

**Comment by seadowg** [comment]
@rajkumaar23 looks like the build is failing. Make sure to run `./gradlew checkAll` before marking changes ready for review please!

**Comment by rajkumaar23** [comment]
> @rajkumaar23 looks like the build is failing. Make sure to run `./gradlew checkAll` before marking changes ready for review please!

@seadowg Sorry for that! Have fixed the issues now.

**Review by lognaturel — APPROVED** [review]
This looks great to me! Thanks for doing the exploration work on this to figure out what actually needed to be done and for bearing with reviewer delay, @rajkumaar23!

A quick note for other reviewers: I know it's tempting to request translations for this and/or to wordsmith the message. Since this is mostly to give a hint to existing users of Aggregate, I think this is good enough.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 6.0, 7.0, 8.1, 9.0.
Verified on an emulator with Android 5.1.

Upload Result with an error 400 has a more friendly message.



I was able to reproduce this error as described in issue when **Accept Submissions** is unselected and when I tried to send a **different version** of an existing form. In both cases, I noticed a new message.

Other errors, like 403, 404 or 500 are unchanged

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Review by seadowg — APPROVED** [review]
