### PR TITLE
Use separate (more meaningful) messages when an audio file is missing/invalid

### LINKED ISSUE #3374: Corrupt/invalid audio file results in "file missing" toast
#### Software and hardware versions 
master (seen in https://github.com/opendatakit/collect/pull/3358); haven't tried to reproduce on v1.23

#### Problem description
When a corrupt or invalid audio file is set as a form attachment and there's an attempt to play that file, a toast that says the file is missing is displayed. This is confusing and could lead a user down the wrong troubleshooting path.

#### Steps to reproduce the problem
1. Use a form with media such as [gridwidget.zip](https://github.com/opendatakit/collect/files/3691137/gridwidget.zip)
1. Instead of the wav in the zip, put a text file with a wav extension in the `-media` folder
1. Try to play audio

#### Expected behavior
The error message should indicate that the file exists but can't be played. I think using the existing `file_invalid` text would be fine.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3374 

#### What has been done to verify that this works as intended?
I tested the attached form.

#### Why is this the best possible solution? Were any other approaches considered?
It's the simplest solution that improves `PlaybackFailedException` setting the message based on the cause.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's not a risky change, testing the attached form should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/audio/PlaybackFailedException.java [hunk 1]
```diff
@@ -2,18 +2,32 @@
...
         this.uri = uri;
+        this.exceptionMessage = setUpExceptionMessage();
     }
 
     public String getURI() {
         return uri;
     }
 
+    private int setUpExceptionMessage() {
+        return new File(uri).exists() ? R.string.file_invalid : R.string.file_missing;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/audio/PlaybackFailedException.java]: I think it would be nicer for this decision to be made inside `AudioPlayerViewModel` where the error occurs. That way we don't need to care about reading the file in `ODKView`. What do you think?

Edit: in that world we'd also be able to write a test around the different scenarios and what error comes out of `AudioPlayerViewModel`.

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.2, 4.4, 5.1, 6.0, 7.1 8.1 and 9.0.

verified cases:
- invalid file
- missing file
- one invalid, one missing
- both invalid
- both missing
- select multi with invalid and missing files
- autoplay with invalid and missing files

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
