### PR TITLE
Fix various memory leaks in Geo activities by detaching listeners and using WeakReferences.

### LINKED ISSUE #3441: MemoryLeak in GeoPointActivity
#### Problem description
Screenshot_1573244675

`Instance of android.location.LocationManager$GnssStatusListenerTransport
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$ifTable = java.lang.Object[6]@1880885848 (0x701c0a58)
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$classSize = 260
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$componentType = null
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$numReferenceInstanceFields = 7
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$name = "android.location.LocationManager$GnssStatusListenerTransport"
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$vtable = null
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$referenceInstanceOffsets = 2035
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$numReferenceStaticFields = 0
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$status = -536870912
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$virtualMethodsOffset = 13
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$objectSize = 52
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $classOverhead = byte[132]@1882941545 (0x703b6869)
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$classFlags = 0
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$shadow$_monitor_ = 536870912
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$copiedMethodsOffset = 18
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$dexCache = java.lang.DexCache@1880727784 (0x7019a0e8)
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$dexClassDefIndex = 6105
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$shadow$_klass_ = java.lang.Class
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$extData = null
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$dexTypeIndex = 4145
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$accessFlags = 524288
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static NMEA_RECEIVED = 1000
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$methods = 1887716816
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$sFields = 1885872588
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$clinitThreadId = 0
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$superClass = android.location.IGnssStatusListener$Stub
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$objectSizeAllocFastPath = 56
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$primitiveType = 131072
2019-11-08 21:23:29.892 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$iFields = 1885872608
2019-11-08 21:23:29.893 8628-8662/org.odk.collect.android:leakcanary D/LeakCanary: |   static $class$classLoader = null`

#### Steps to reproduce the problem
1. Open any form with GeoPointWidget
2. Start recording location
3. Cancel it or accept.

### LINKED ISSUE #3446: MapFragment memory leaks
mapbox-leak
google-leak
osmdroid-leak

### PR DESCRIPTION
**Pull request by zestyping**
Closes #3441.  Closes #3446.

Sorry @grzesiek2010, I hope this doesn't collide with your work!  The LeakCanary notifications were just bothering me too much and I figured it wouldn't be too hard to fix.

#### What has been done to verify that this works as intended?

I ran the app without this change and LeakCanary showed memory leaks of various kinds shown in #3441 and #3446 (lingering references from the LocationClient and LocationEngine, lingering references from the LocationManager to a listener, and lingering references from map markers).  In each case, I only needed to open the GeoPointActivity, GeoPointMapActivity, or GeoPolyActivity and close it three times, and a leak would occur.  I changed the Maps settings in order to test all three map implementations (GoogleMapFragment, MapboxMapFragment, and OsmDroidMapFragment) and the leaks in GeoPointMapActivity and GeoPolyActivity would occur for all three.

I ran the app again with this change, and again tested GeoPointActivity.  I opened and closed the activity at least 10 times.  I also tested GeoPointMapActivity and GeoPolyActivity, opening and closing the activity at least 10 times, for all three map implementations, and no memory leaks have been reported by LeakCanary.

#### Why is this the best possible solution? Were any other approaches considered?

- For MapboxMapFragment, the WeakReference solution is recommended in the Mapbox documentation: https://docs.mapbox.com/android/core/overview/#requesting-location-updates

- The pattern of the memory leak looked identical in GoogleMapFragment, except involving LocationClientListener instead of Mapbox's LocationEngineCallback.  Both GoogleMapFragment and OsmDroidMapFragment use the LocationClientListener in the same way, so I implemented the same solution for those two classes as well.

- Rather than setting up the WeakReference in the MapFragment, I decided to make it the responsibility of the LocationClient implementations to hold only a WeakReference.  This is a little nicer because there is less code to change and because it is clear from looking at the members of the LocationClient that it cannot hold a strong reference to the listener in question.

- Separately, there was another leak due to a reference held by the Android LocationManager.  I fixed this with a call to removeGpsStatusListener.

- There was another leak due to map markers holding references to the OsmDroid map.  I fixed this by clearing the markers when the OsmDroid map is destroyed.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This change has no impact on the user experience.

#### Do we need any specific form for testing your changes? If so, please attach one.

Any form with geo questions will do.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by zestyping** [comment]
Okay, this fix now covers all the leaks I've seen, including both #3441 and #3446.

@lognaturel This has been refactored a bit—sorry to change it after your review!

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@zestyping I still see leaks. I'm not sure that I'm doing something incorrectly.
Maybe it is something different. Please take a look and let me know.

| | | |
|---|---|---|
|Screenshot_2019-11-13-15-48-51|Screenshot_2019-11-13-15-47-41-792_org odk collect android|Screenshot_20191113-154820|
|Screenshot_20191113-155514|Screenshot_20191113-155503|Screenshot_2019-11-13-15-55-09-408_org odk collect android|

**Comment by zestyping** [comment]
Yikes!  So odd that this is still coming up—it doesn't happen on my phone any more.  I think the next thing to do is to try this on a few different phones or Android versions.  Once you can replicate these memory leaks, you could try setting breakpoints on the mechanisms added in this PR to see if they are working properly.

@lognaturel is taking over this PR as well in my absence.  Thanks Hélène!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java [hunk 1]
```diff
@@ -192,7 +192,11 @@ public void onClientStartFailure() {
 
     @Override
     public void onClientStop() {
-
+        locationClient.stopLocationUpdates();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java:195]: This method (`onClientStop()`) is called from `AndroidLocationClient.stop()` which also calls `stopLocationUpdates()`, so this line here seems to be redundant (we call it twice).

**Comment by grzesiek2010** [comment]
I investigated those leaks related to `LocationManager` but I have no idea what might be wrong... everything seems fine.

**Comment by lognaturel** [comment]
I've finally had the time to look at this more deeply. All of the changes are well-reasoned and explained in the PR description. I think that as @grzesiek2010 pointed out [above](https://github.com/opendatakit/collect/pull/3445#pullrequestreview-326940585), we should remove the redundant call on `locationClient.stopLocationUpdates()`, do a QA regression check for the three mapping engines and then merge this. Even if it somehow doesn't make LeakCanary systematically happy, it all seems like changes we should make. We can then come back to remaining leaks as we may have time.

**EDIT**: As I looked more deeply into removing that call, I started thinking we'd be better off keeping it in. See https://github.com/opendatakit/collect/pull/3445#discussion_r365984540

I've marked as `needs testing`. @opendatakit/testers, please do a basic regression check on the geotrace activity with mapbox, osm and Google map providers. As you do that, please note where you still see LeakCanary problems and we can update the issues with that information. Is it all Android versions/devices? Is it all the leaks?

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java:195]: You are correct in the common case but it looks like `onClientStop` can get called directly in some cases (`GoogleLocationClient.onConnectionSuspended` in particular for when we restore using Fused provider). I'd rather keep this call explicitly here since it's very cheap. Does that seem ok, @grzesiek2010?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java:195]: Yes that's right.

**Comment by mmarciniak90** [comment]
**Google Maps**
Case 1
1. User clicks on `Start GeoTrace` 
2. View with map is opened (User can add location, input method does not matter. Adding a location is not required)
3. **User leaves map view**
4. User waits a moment - leak is recorded

Leak on Android: 4.2, 4.4, 5.1, 6.0, 8.1, 9.0, 10.0 
**Leak does not appear on Android 7.0!**



Androids 8.1, 9.0, 10.0  have additionally this leak. Both leaks appear together.



----

**OSM**

The same situation as in Google Maps.

----

**Mapbox**

I did not observe leaks

**Comment by lognaturel** [comment]
Thanks so much for looking at this, @mmarciniak90. Since it improves things and doesn't cause regressions, let's merge for now. I have re-opened https://github.com/opendatakit/collect/issues/3446. Please update it with the leaks you are still seeing.

When we spoke, you pointed out that there's also a specialized change for geopoint that I forgot about. Please verify that one and update #3441 as needed. Thanks!

**Comment by mmarciniak90** [comment]
I added a comment with test results to the mentioned issues.

@opendatakit-bot unlabel "needs testing"
