### PR TITLE
Lock Jackson version to prevent problems with older Android APIs

### LINKED ISSUE #5458: Geojson file causes an error in Android 7.0
#### ODK Collect version
master 8e633bfa351375aa841eefd54c7204764a687ab0
#### Android version
emulated 7.0
#### Problem description
There is an error on opening All widgets form and Select one from map in the demo project on Android 7.0 and 5.1. I think that the forms in which error occurs use geojson file.
Things noticed:
- All widgets forms works as expected in different projects Central/ Aggregate- probably older version of All widgets without select one from map (with geojson)
- In the demo project it is possible to open the map form of All widgets form
- in other projects forms work as expected but there is an error on geojson form

#### Steps to reproduce the problem
1. Open the demo project.
2. Go to Fill Blank Form.
3. Open All widgets/ Select one from map

#### Other information 
The issue doesn’t occur on the store version 2022.4.4

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5458

Newer versions of Jackson that weren't compatible with Android API 24 and under were ending up being used by JavaRosa because both it and `json-schema-validator` use it as a dependency. Gradle will go with the ["highest" (or newest) version](https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:resolution-strategy) to resolve version conflicts, which in this case meant the latter's version (which includes the incompatibilities) was always used. I've set a forced version for Jackson to prevent this from happening.

#### What has been done to verify that this works as intended?

Verified manually. I think it'd be good to think about some automated testing strategies that might catch something like this in future, but I'll leave that for the moment, and we can discuss later as a team.

#### Why is this the best possible solution? Were any other approaches considered?

An alternative would have been to exclude Jackson as a transitive dependency from `json-schema-validator`, but given how popular it is, it felt safer to force a known "safe" version for all dependencies.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the crash in forms with GeoJSON select one from map questions.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: buildSrc/src/main/java/dependencies/Dependencies.kt [hunk 1]
```diff
@@ -67,7 +67,7 @@ object Dependencies {
     const val slf4j_api = "org.slf4j:slf4j-api:2.0.6"
     const val slf4j_timber = "com.arcao:slf4j-timber:3.1@aar"
     const val emoji_java = "com.vdurmont:emoji-java:5.1.1"
-    const val json_schema_validator = "com.networknt:json-schema-validator:1.0.75"
+    const val json_schema_validator = "com.networknt:json-schema-validator:1.0.72"
```
Comment (grzesiek2010) [inline buildSrc/src/main/java/dependencies/Dependencies.kt]: I would prefer to have that comment about not upgrading the dependency here like in the case of `commons_io` for example. It's well visible and when I go through the list of dependencies at the beginning of every release cycle it's clear that we shouldn't touch it.

File: collect_app/build.gradle [hunk 2]
```diff
@@ -228,6 +228,9 @@ configurations.all {
         cacheChangingModulesFor(0, 'seconds')
 
         force 'org.objenesis:objenesis:2.6'
+
+        // Newer Jackson versions cannot be ued until Collect minSDK >= 26 (https://github.com/FasterXML/jackson-databind#android)
+        force 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
```
Comment (grzesiek2010) [inline collect_app/build.gradle:233]: If we had that comment I mentioned above do we need this too? To me, it would be enough not to touch that dependency.

File: buildSrc/src/main/java/dependencies/Dependencies.kt (hunk 1 above)
Comment (seadowg) [reply buildSrc/src/main/java/dependencies/Dependencies.kt]: Right, I see what you mean. I guess my worry was that another dependency could cause the same problem by depending on a newer Jackson (given it's such a popular library). I do see that it seems strange to downgrade `json_schema_validator` **AND** lock Jackson though. I'll remove this version change so that we're just locking Jackon.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10, emulated Android 6.0, 7.0, 7.1

**Verified Cases:**
- issue #5458 is no longer reproducing
- forms with geojson attachment
- Google maps, Mapbox, OSM
- offline layers
- quick checks in Geo widgets

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 5.1
