### PR TITLE
fix: Selected text invisible for empty selections

### LINKED ISSUE #1838: `Selected:` text is visible below the button in Select multiple question with `minimal` appearance even if nothing selected
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Problem description
`Selected:` text is visible below the button in Select multiple question with `minimal` appearance even if nothing selected.
It disappears after removing response.

#### Steps to reproduce the problem
You can use All Widgets form available on the aggregate demo server.
1. Go to Select multiple question with `minimal` appearance
2. `Selected:` is visible below the button.
3. Add any answer
4. Remove response

#### Expected behavior
That text should be visible only if any option is selected.

### PR DESCRIPTION
**Pull request by dr0pdb**
Closes #1838 

#### What has been done to verify that this works as intended?
Verified manually.
videotogif_2018 02 08_05 51 43

#### Why is this the best possible solution? Were any other approaches considered?
It's a simple bug that can easily be solved using an ```if``` statement. No other approaches considered.

#### Are there any risks to merging this code? If so, what are they?
None

#### Do we need any specific form for testing your changes? If so, please attach one.
All widgets form.

### CODE REVIEW

**Comment by dr0pdb** [comment]
It's building locally. I can't understand the error on circle ci.

**Comment by yanokwa** [comment]
CircleCI sometimes fails on Android builds. I'm re-running it. Let's see if it passes.

File: collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java [hunk 1]
```diff
@@ -220,4 +214,14 @@ public void onClick(DialogInterface dialog, int which,
         AlertDialog alert = alertBuilder.create();
         alert.show();
     }
+
+    private void showSelectedValues(List<String> selectedValues) {
+        if (selectedValues.size() > 0) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: How about if (....**isEmpty()**) clearAnswer() else the other

Comment (dr0pdb) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: That will also do, but i don't think it will be an improvement. The call to the ```size()``` method is also ```O(1)```.  
Any reason why calling ```isEmpty``` is preferable ? For readability ?

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: https://stackoverflow.com/questions/1508975/why-is-list-size0-slower-than-list-isempty-in-java#1508993

Comment (dr0pdb) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: Thank you :+1:

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: I was gonna give another reason, but it’s already in the page @shobhitagarwal1612 linked to:
>isEmpty is a clearer definition of what it is you actually care about and are testing, and so makes your code a bit more easily understandable.

Also, `size() == 0` is 6 tokens (for the human to parse) and `isEmpty()` is 3.

(Scala adds `nonEmpty()` which I use quite a lot.)

File: collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java [hunk 2]
```diff
@@ -216,12 +216,12 @@ public void onClick(DialogInterface dialog, int which,
     }
 
     private void showSelectedValues(List<String> selectedValues) {
-        if (selectedValues.size() > 0) {
+        if (selectedValues.isEmpty()) {
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java]: Thanks! I find this much easier to read.

**Review by yanokwa — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "behavior verified"
