### PR TITLE
Fixed TriggerWidget

### LINKED ISSUE #5523: The acknowledge mark gets deselected if don’t keep activities is on and the user minimizes the app
#### ODK Collect version
2022.4.4, 2023.1 Beta 5
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
I reproduced the case mentioned https://forum.getodk.org/t/entered-odk-collect-data-gets-lost-after-a-while/40518.
The acknowledge marks gets deselected when don’t keep activities is on and the user minimizes the app.
#### Steps to reproduce the problem
Scenario 1:
1. In device settings enable "don’t keep activities”.
2. In Collect go to Diary App GOLIAT form.
[ODK Diary App_GOLIAT_07022023.xlsx.txt](https://github.com/getodk/collect/files/11077420/ODK.Diary.App_GOLIAT_07022023.xlsx.txt)
3. Select "OK. Please Continue” in Start Measuring part (don’t select both).
DappGoliat
4. Minimize the app, switch to a different app and go back to Collect.

In this case the answer will get deselected.

Scenario 2:
1. In device settings enable "don’t keep activities”.
2. In Collect go to Diary App GOLIAT form.
3. Select "OK. Please Continue” in Finish Measuring part (don’t select both).
4. Minimize the app, switch to a different app and go back to Collect.

In this case after going back to the app, both parts (Start and Finish) will be selected.

#### Expected behavior
Answers shouldn’t change.
#### Other information 
If the user adds a repeat and then follows the steps, the answers that get selected/deselected after minimizing the app are in the current repeat opened (selected answers in previous repeats will stay as the user chose).
If the user selects both in Start and Finish Measuring then after minimizing both stay selected.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5523 

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
`Checkboxes` need to have their own unique ids (just like `EditTexts`) otherwise because of android internal mechanism of restoring their state bugs like this one might occur.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
For now, we can focus on testing the scenario described in the issue but it would be good if we don't have similar problems with other widgets.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java [hunk 1]
```diff
@@ -58,4 +59,16 @@ public void guidanceIcons_ShouldBeCollapsed() {
                 .swipeToEndScreen()
                 .clickFinalize();
     }
+
+    @Test // https://github.com/getodk/collect/issues/5523
+    public void whenTwoTriggerWidgetsPlacedOnOneScreen_keepProperAnswersOnScreenRotation() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java]: How would you feel about replacing this with a unit test for `TriggerWidget` that checks that the checkbox gets a new ID each time?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java]: Yes, that's a good idea. Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- issue #5523 is no longer reproducing
- All widgets – trigger widget
- don’t keep activities enabled/disabled
- no background processes setting
- rotating, minimizing, locking the screen

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13
