### PR TITLE
Expression tree too large error - resolved

### LINKED ISSUE #558: Expression tree is too large error after uploading large number of files
Large number of files submissions (>1000) result into `Expression tree is too large` error , it is happening in `                results = new InstancesDao().getInstancesCursor(selection.toString(), selectionArgs);
`  of  uploadingComplete method in InstanceUploaderActivity.  This error is probably because of building long SELECT statement.

```
03-09 20:27:50.588 30674-30921/org.odk.collect.android I/InstanceUploaderTask: Issuing POST request for 1997 to: https://nafundi-test.appspot.com/submission
03-09 20:27:51.959 30674-30921/org.odk.collect.android I/InstanceUploaderTask: Response code:201
03-09 20:27:52.048 30674-30921/org.odk.collect.android I/InstanceUploaderTask: Using Uri remap for submission 1998. Now: https://nafundi-test.appspot.com/submission
03-09 20:27:52.059 30674-30921/org.odk.collect.android I/InstanceUploaderTask: added xml_submission_file: basic_2017-03-06_10-39-48_999.xml
03-09 20:27:52.062 30674-30921/org.odk.collect.android I/InstanceUploaderTask: Issuing POST request for 1998 to: https://nafundi-test.appspot.com/submission
03-09 20:27:53.590 30674-30921/org.odk.collect.android I/InstanceUploaderTask: Response code:201
03-09 20:27:53.711 30674-30674/org.odk.collect.android I/InstanceUploaderActiv: uploadingComplete: Processing results (1998) from upload of 1998 instances!
03-09 20:27:53.755 30674-30674/org.odk.collect.android E/SQLiteLog: (1) Expression tree is too large (maximum depth 1000)
03-09 20:27:53.763 30674-30674/org.odk.collect.android E/EXCEPTION: android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1): , while compiling: SELECT canEditWhenComplete, deletedDate, status, jrVersion, jrFormId, instanceFilePath, date, submissionUri, displayName, _id, displaySubtext FROM instances WHERE (_id=? or _id=? or _id=? or _id=? or _id=? or _id=? or _id=? or _id=? or _id=? or _id=? or _i
```
One thing that can be used to resolve this issue is that by using SELECT statment for each 999 ids so that it will not result into expression tree is too large error as the expected limit to be around 1000 so it will be better if we run query for each 999. 

 I am currently working on it. 

Any suggestions ?

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Tested for the folder provided in [this](https://github.com/opendatakit/collect/issues/518) issue.
Fixes #558

### CODE REVIEW

**Comment by lognaturel** [comment]
@nribeka Can you please take a first look?

I think the `SQLITE_MAXIMUM_QUERY_LIMIT` constant should be the same one in `InstanceUploaderTask` and `InstanceUploaderActivity` Perhaps it could go in `ApplicationConstants`. I do like this name and I think @nribeka's comment in `InstanceUploaderTask` should go with it wherever it ends up being defined..

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 1]
```diff
@@ -51,6 +52,7 @@
     private final static String TAG = "InstanceUploaderActiv";
     private final static int PROGRESS_DIALOG = 1;
     private final static int AUTH_DIALOG = 2;
+    private static final int SQLITE_MAXIMUM_QUERY_LIMIT = 999;
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: I agree, this one need to go the constants class.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 2]
```diff
@@ -237,18 +256,21 @@ public void uploadingComplete(HashMap<String, String> result) {
...
                                         results.getColumnIndex(InstanceColumns.DISPLAY_NAME));
                         String id = results.getString(results.getColumnIndex(InstanceColumns._ID));
-                        message.append(name + " - " + result.get(id) + "\n\n");
+                        queryMessage.append(name + "-" + result.get(id) + "\n\n");
                     }
-                } else {
-                    message.append(getString(R.string.no_forms_uploaded));
                 }
+            } catch (SQLException e) {
+                Log.e(TAG, e.getMessage());
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Pass the throwable e to the Log.e method.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 3]
```diff
@@ -237,18 +256,21 @@ public void uploadingComplete(HashMap<String, String> result) {
...
                     results.close();
-                }
             }
+            message.append(queryMessage.toString());
         }
-
+        if (message.length() == 0) {
+            message.append(getString(R.string.no_forms_uploaded));
+        }
+        Log.d(TAG,message.toString());
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Space between params.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 4]
```diff
@@ -210,25 +212,42 @@ public void uploadingComplete(HashMap<String, String> result) {
...
-        }
 
-        StringBuilder message = new StringBuilder();
-        {
+            selection = new StringBuilder();
+            selectionArgs = new String[parLen];
+            selection.append(InstanceColumns._ID + " IN (");
+
+            int i = 0;
+            while (it.hasNext() && i < parLen) {
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: I think you can use parLen here instead of using i to do the counting right? And I would rename the parLen to something else @lognaturel usually have good suggestion 👍

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 5]
```diff
@@ -210,25 +212,42 @@ public void uploadingComplete(HashMap<String, String> result) {
...
+                String id = it.next();
+                selectionArgs[i] = id;
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: You could simplify this by just doing the assignment instead of introducing temp var id I think.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 6]
```diff
@@ -210,25 +212,42 @@ public void uploadingComplete(HashMap<String, String> result) {
...
+                if (i != parLen - 1) {
+                    selection.append("?,");
+                } else {
+                    selection.append("? )");
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: And I think you can simplify this by always adding '?', and adding ',' only when parLen > 0 (the last '?' won't get a ','), and then outside of the of the while add the ')'. I think it's more readable that way. But that could be just  my preference.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 7]
```diff
@@ -210,25 +212,42 @@ public void uploadingComplete(HashMap<String, String> result) {
...
+                }
+                i++;
+                count--;
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Instead of looping and decreasing the count, you can safely decrease the count by parLen.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 8]
```diff
@@ -210,25 +212,42 @@ public void uploadingComplete(HashMap<String, String> result) {
...
+            }
+
+            StringBuilder queryMessage = new StringBuilder();
             Cursor results = null;
             try {
+                Log.e(TAG, selection.toString());
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: I don't think Log.e is appropriate here since this part is not an error.

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 9]
```diff
@@ -641,52 +643,74 @@ protected void onPostExecute(Outcome outcome) {
...
-                                    PreferenceKeys.KEY_DELETE_AFTER_SEND, false);
-                            if (deleteFlag) {
-                                DeleteInstancesTask dit = new DeleteInstancesTask();
-                                dit.setContentResolver(Collect.getInstance().getContentResolver());
-                                dit.execute(toDelete);
-                            }
+                        selection.append(InstanceColumns._ID + " IN (");
+                        int i = 0;
+
+                        while (it.hasNext() && i < parLen){
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: I think we can apply the same approach with my previous comments?

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 10]
```diff
@@ -641,52 +643,74 @@ protected void onPostExecute(Outcome outcome) {
...
+                                if (deleteFlag) {
+                                    DeleteInstancesTask dit = new DeleteInstancesTask();
+                                    dit.setContentResolver(
+                                            Collect.getInstance().getContentResolver());
+                                    dit.execute(toDelete);
+                                }
+
+                            }
+                        } catch (SQLException e){
+                            Log.e(t,e.getMessage());
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: Pass the e to the Log.e method.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java (hunk 3 above)
Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Ohh sorry i forgot to remove this it was for debugging purpose. And yes there must be some space between params.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java [hunk 11]
```diff
@@ -17,6 +17,8 @@
 
 public class ApplicationConstants {
 
+    public static final int SQLITE_MAXIMUM_QUERY_LIMIT = 999;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java]: Please add `// based on http://www.sqlite.org/limits.html` above so we have context for this constant.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 12]
```diff
@@ -210,23 +212,40 @@ public void uploadingComplete(HashMap<String, String> result) {
             // tried to close a dialog not open. don't care.
         }
 
-        StringBuilder selection = new StringBuilder();
+        StringBuilder selection = null;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: `selection` is only used within the while loop and should be declared with the tightest scope possible. There is no advantage to reusing the variable, especially since you are creating new objects anyway on each iteration.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 13]
```diff
@@ -210,23 +212,40 @@ public void uploadingComplete(HashMap<String, String> result) {
...
-            selection.append(InstanceColumns._ID + "=?");
-            selectionArgs[i++] = id;
-            if (i != keys.size()) {
-                selection.append(" or ");
+        String[] selectionArgs = null;
+        StringBuilder message = new StringBuilder();
+        int count = keys.size();
+
+        while (count != 0) {
+
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Remove extra blank line

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 14]
```diff
@@ -210,23 +212,40 @@ public void uploadingComplete(HashMap<String, String> result) {
...
+            if (count > ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT) {
+                selectionArgs = new String[ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT];
+            } else{
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: Add space after `else`

File: collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java (hunk 11 above)
Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java]: Comment added.

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 15]
```diff
@@ -641,52 +640,74 @@ protected void onPostExecute(Outcome outcome) {
                 } else {
                     mStateListener.uploadingComplete(outcome.mResults);
 
-                    StringBuilder selection = new StringBuilder();
+                    StringBuilder selection = null;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: Same comment as above, `selection` should be declared when it is initialized.

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 16]
```diff
@@ -641,52 +640,74 @@ protected void onPostExecute(Outcome outcome) {
...
-                        if (i != keys.size()) {
-                            selection.append(" or ");
+                    String[] selectionArgs = null;
+                    int count = keys.size();
+
+                    while(count != 0){
+                        if(count > ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT - 1) {
+                            selectionArgs = new String[
+                                    ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT];
+                        }else {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: Space before `else`.

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 17]
```diff
@@ -641,52 +640,74 @@ protected void onPostExecute(Outcome outcome) {
...
+                            selection.append("?");
 
-                            boolean deleteFlag = PreferenceManager.getDefaultSharedPreferences(
-                                    Collect.getInstance().getApplicationContext()).getBoolean(
-                                    PreferenceKeys.KEY_DELETE_AFTER_SEND, false);
-                            if (deleteFlag) {
-                                DeleteInstancesTask dit = new DeleteInstancesTask();
-                                dit.setContentResolver(Collect.getInstance().getContentResolver());
-                                dit.execute(toDelete);
+                            if(i != selectionArgs.length - 2) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: Space after `if`.

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java [hunk 18]
```diff
@@ -210,23 +212,40 @@ public void uploadingComplete(HashMap<String, String> result) {
...
-            String id = it.next();
-            selection.append(InstanceColumns._ID + "=?");
-            selectionArgs[i++] = id;
-            if (i != keys.size()) {
-                selection.append(" or ");
+        String[] selectionArgs = null;
+        StringBuilder message = new StringBuilder();
+        int count = keys.size();
+
+        while (count != 0) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java]: As @nribeka pointed out, this would conceptually be better as a test on `> 0`. It captures the scenario a bit better and ensures that if ever `count` accidentally became negative, the loop would still stop.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Small, mostly stylistic changes. Thank you!

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks for taking the time to get it just right, @lakshyagupta21!

**Comment by lognaturel** [comment]
PS - @lakshyagupta21 are you dexter21 on Slack? @nribeka and I were wondering! 😄
