### PR TITLE
Fixed automatic location recording

### LINKED ISSUE #3984: The automatic location recording method does not work as expected
#### Software and hardware versions 
Collect master

#### Problem description
The automatic location recording method does not work as expected

#### Steps to reproduce the problem
1. User opens GeoTrace or GeoShape widgets
2. User tries to add points via Automatic location recording method

#### Expected behavior
* The first point is collected immediately for automatic mode
* It's possible to add points with interval 1 second with Accuracy 20m or other
* It's possible to add points with Accuracy None
* It's possible to clear previously added points and add new points with other parameters. New parameters appear on black footer without delay.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3984

#### What has been done to verify that this works as intended?
I tested implemented changes manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is a bug fix and the only solution. The problem was that we tried to start recording first after clicking Start button and then in `onDestroy` method we set properties we need to start the process. It should work the other way around.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's just a bug fix so I find it pretty safe. I think that testing recording locations would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with GeoTrace/GeoShape widgets like the all widgets form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java [hunk 1]
```diff
@@ -35,7 +36,7 @@
     private int accuracyThresholdIndex = -1;
 
     @Override
-    public void onAttach(Context context) {
+    public void onAttach(@NotNull Context context) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java]: How I wish these annotations were more standardized! Since this is an android class, we should use `NonNull` which is already imported here. I think it makes sense to use this one for classes that are not related to android at all.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Good catch and fix.

File: collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java]: Oh right, fixed.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 7.0, 8.1, 9.0

Verified cases:
* GeoTrace and GeoShape
   * The first point is collected immediately for automatic mode
   * It's possible to add points with interval 1 second with Accuracy 20m or other
   * It's possible to add points with Accuracy None
   * It's possible to clear previously added points and add new points with other parameters. New parameters appear on the black footer without delay
* quick check `Manual location recording` method 
* removing response
* light / dark mode
* RTL language
* change device orientation

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
