### PR TITLE
Fixed clearing errors

### LINKED ISSUE #6508: An already filled required question in a field-list with a question with constraint "gets” the constraint message after screen rotation
#### ODK Collect version
the store version 2024.2.4, 2024.3.0 Beta 8
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
An already filled required question in a field-list with a question with constraint "gets” the constraint message after screen rotation.

reqConstFieldlist

#### Steps to reproduce the problem
1. Open a form with a required question and a question with constrain in a field-list.
[RequiredAndConstraint.xlsx.txt](https://github.com/user-attachments/files/17732274/RequiredAndConstraint.xlsx.txt)

2. Go to question on a field-list (required and constraint questions)
3. In a required question enter some values.
4. In constraint question enter 3 numbers (e.g. 555).
5. Swipe to the next question (the red outline and text appears in the constraint question).
6. Rotate the device (there’s the constraint message text in the filled required question).
#### Expected behavior
The already filled required question shouldn’t be marked as having errors. The wrong message shouldn’t appear.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6508 

#### Why is this the best possible solution? Were any other approaches considered?
It seems that Android might be retaining the error, possibly through the text field ID, and keeps it displayed after the view is recreated. To resolve this, we need to programmatically clear the error during the view creation process.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue but please make sure errors are displayed and cleared correctly in text questions.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form from the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt [hunk 1]
```diff
@@ -44,6 +45,17 @@ class RequiredQuestionTest {
...
     }
 
+    @Test
+    fun errorMessageDisappearsAfterActivityRecreation() {
+        rule.startAtMainMenu()
+            .copyForm("required_question_with_custom_error_message.xml")
+            .startBlankForm("required_question_with_custom_error_message")
+            .swipeToNextQuestionWithConstraintViolation("Custom message")
+            .rotateToLandscape(FormEntryPage("required_question_with_custom_error_message"))
+            .rotateToPortrait(FormEntryPage("required_question_with_custom_error_message"))
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt]: I think we could just rotate once here right?

File: collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt [hunk 2]
```diff
@@ -166,7 +167,9 @@ class WidgetAnswerText(context: Context, attrs: AttributeSet?) : FrameLayout(con
     }
 
     fun setError(error: String?) {
-        binding.textInputLayout.error = error
+        binding.textInputLayout.post {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt:170]: Why the `post` here?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt:55]: If we rotate to landscape the edit text will be displayed in that full-screen mode and there will be no error no matter if the bug is fixed or not.

File: collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt:170]: This new scenario needs some delay to clear the error after recreating the view.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6508 doesn’t occur
- regression checks in required questions and questions with constraints, check for errors
- validate upon forward swipe, defer validation until finalized
- don’t keep activities enabled/ disabled + rotating and minimizing the app

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 15
