### PR TITLE
Removed duplicated call notifyDataSetChanged

### LINKED ISSUE #2928: Fatal Exception: java.lang.IndexOutOfBoundsException
#### Software and hardware versions 
Collect v1.20.0 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b58da6f6007d59fcdbf0172?time=last-seven-days&sessionId=5C78DC2F01F8000134CAA0ADC5D0C786_DNE_4_v2

```
Fatal Exception: java.lang.IndexOutOfBoundsException
Invalid index 30, size is 0
keyboard_arrow_up
java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:255)
java.util.ArrayList.get (ArrayList.java:308)
arrow_right
org.odk.collect.android.adapters.FileArrayAdapter.getView (FileArrayAdapter.java:97)
android.widget.AbsListView.obtainView (AbsListView.java:2937)
android.widget.ListView.makeAndAddView (ListView.java:1945)
android.widget.ListView.fillUp (ListView.java:755)

```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2928 

#### What has been done to verify that this works as intended?
I tested the GD list manual to confirm it works well.

#### Why is this the best possible solution? Were any other approaches considered?
It's a long-standing issue. unfortunately, I wasn't able to reproduce it but my gut says it has something to do with calling `notifyDataSetChanged()` two times (it's called https://github.com/opendatakit/collect/compare/master...grzesiek2010:COLLECT-2928?expand=1#diff-4843e9d988e60283c4c8967d83b05c0bR299 and that's enough).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's rather not risky. The line I removed was redundant but to be sure we can perform some manual testing as well.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 1]
```diff
@@ -299,7 +299,6 @@ protected void updateAdapter() {
             adapter.notifyDataSetChanged();
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:299]: Shouldn't we remove this else block instead?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:299]: Why? notifyDataSetChanged() should be called only then - if the adapter is updated, it doesn't make sense to do that when a new object is created.

Comment (shobhitagarwal1612) [reply collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:299]: You're absolutely correct, my bad

**Comment by shobhitagarwal1612** [comment]
I think this is an improvement but I am still unable to understand as to how this fixes issue #2928

**Comment by grzesiek2010** [comment]
As I said it's a long-standing issue which I'm not able to reproduce. I'm not sure if it's the real cause it's just my gut so I would like to try, if not we can reopen.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Please check the comment https://github.com/opendatakit/collect/issues/2928#issuecomment-469315865

**Comment by grzesiek2010** [comment]
@mmarciniak90 I merged it but you can confirm GD list works without any changes.

**Comment by mmarciniak90** [comment]
**Tested with success**

I did not notice any change in `Get Blank Form` view when GD is selected as a server.
Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases:
* navigating via buttons Go back / My Drive / Shared with Me
* downloading forms with media
* scrolling - selected forms are not mixed
* searching forms
* rotating
* locking the screen

@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by yanokwa** [comment]
Process reminder: Don't merge before the code is tested unless it's an emergency (e.g., tweak to fix the build).
