### PR TITLE
Fix : Error logs in code segments

### LINKED ISSUE #1956: Log problems that aren't due to issues in Collect code at a log level lower than error
#### Software and hardware versions 
Collect v1.13.0

#### Problem description
There are a number of issues logged with `Timber.e` that aren't related to Collect code problems. For example if a `ActivityNotFoundException` when an external intent is used, that's because the user is missing a particular application. In that case, the user should be notified through the UI. If an error is logged, it should be through `Timber.d` so it doesn't log remotely in production. 

Similarly, `JavaRosaException`s or `FileNotFoundException`s or `InvalidSyntaxException` in `ExternalDataUtil` are not ones we can change code to handle.

#### Expected behavior
`Timber.d` or `Timber.i` should be used for logging errors related to user input or device state.

### PR DESCRIPTION
**Pull request by sashank27**
Closes #1956

#### Why is this the best possible solution? Were any other approaches considered?
Uses `Timber.d` and `Timber.i` in place of `Timber.e`.
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No

@lognaturel @grzesiek2010 please review

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/location/client/AndroidLocationClient.java [hunk 1]
```diff
@@ -134,13 +134,13 @@ public boolean canSetUpdateIntervals() {
     @Override
     public void setUpdateIntervals(long updateInterval, long fastestUpdateInterval) {
         // Do nothing.
-        Timber.e("Can't set updateInterval on AndroidLocationClient. You should check canSetUpdateIntervals before calling this method.");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/location/client/AndroidLocationClient.java]: Calling `setUpdateIntervals` would actually be an error in Collect code so this should be logged at level `e`.

**Review by lognaturel — CHANGES_REQUESTED** [review]
One quick change and the rest looks good to me!

**Comment by sashank27** [comment]
did the changes @lognaturel . Please review

**Review by lognaturel — APPROVED** [review]
