### PR TITLE
Prevent "Check for errors" result snackbar from reappearing on rotation

### LINKED ISSUE #5678: "No errors found.." snackbar reappears after rotation
#### ODK Collect version
the store version 2023.2.2, the master version fdf5e79e5367099cd1298b10f5ba4322e885c001
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
After checking for errors in a form, the snackbar appears after each screen rotation.
#### Steps to reproduce the problem
1. Open any form.
2. Tap the three dots→ Check for errors.
3. Wait until the snackbar about no errors disappears.
4. (Optional step) Go to the next question.
5. Rotate the device.
#### Expected behavior
The snackbar shouldn’t reappear after the rotation.

### PR DESCRIPTION
**Pull request by dimwight**
Closes #5678?

#### What has been done to verify that this works as intended?

Tested manually.

#### Why is this the best possible solution? Were any other approaches considered?

Seems to be "the simplest thing that could possibly work". More elegant alternatives could be to change the signature of `FormEntryViewModel.getValidationResult` to reflect the actual class; or completely encapsulate with something like `resetValidationResult`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Behaviour is now as expected. Doesn't break any tests.

#### Do we need any specific form for testing your changes? If so, please attach one.
No?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
* [x]  run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
* [x]  verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
* [x]  verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @dimwight, and it's nice to see you again! I know we haven't always been very good at responding to your PRs and I'm going to make an effort to stay on top of it. That said, I'm not very deep in Collect code these days so I'm going to need a double check from others.

Conceptually, it does feel like the view code should be clearing out the validation result. I agree `resetValidationResult` on the `ViewModel` would be more elegant. I'd tend to go in that direction but I also feel like this is pragmatic. @seadowg, we must have solved this problem elsewhere in the codebase, is there a set pattern used for that?

For whatever it's worth, [others do this kind of casting too](https://gist.github.com/humblehacker/0eb6458b1df6cf3049e031f36f0615f5?permalink_comment_id=4234115#gistcomment-4234115).

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -562,6 +566,7 @@ private void setupViewModels(FormEntryViewModelFactory formEntryViewModelFactory
                 swipeHandler.setBeenSwiped(false);
             } else if (validationResult instanceof SuccessValidationResult) {
                 SnackbarUtils.showLongSnackbar(findViewById(R.id.llParent), getString(org.odk.collect.strings.R.string.success_form_validation), findViewById(R.id.buttonholder));
+                ((MutableLiveData) validation).setValue(null);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: I'm not a fan of casting here as it breaks the encapsulation of `FormEntryViewModel` - `FormFillingActivity` is making an assumption about the return type of `getValidationResult` that the type information itself doesn't back up.

We do have a way of dealing with these "single fire events" when using `LiveData`: [`Consumable`](https://github.com/getodk/collect/blob/b6c65fc4ee5f02e282e4aa70ea3c96fae0bc3b28/androidshared/src/main/java/org/odk/collect/androidshared/data/Consumable.kt). There's an example of this in use in [`ProjectPreferencesFragment`](https://github.com/getodk/collect/blob/b6c65fc4ee5f02e282e4aa70ea3c96fae0bc3b28/collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt#L48).

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (dimwight) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Thanks for the tip, a bit advanced for me but I got it to work after some puzzling. 

I've also tested with a dummy`FailedValidationResult`. 

And thanks @lognaturel for the kind welcome, it's nice to be back.

**Review by seadowg — APPROVED** [review]
Great!

We'd usually want a test for this, but it's currently a bit of a headache to add unit tests for `FormFillingActivity` and this regressing wouldn't be a major enough problem to make that effort worth it at the moment.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13

Verified cases:

- Issue #5678 is no longer reproducing;
- Don't keep activities enabled/disabled;
- Rotate the screen, minimize the app during Check for error dialog;
- Quick check on Audit files
