### PR TITLE
Fix deprecated methods in FormEntryPage

### LINKED ISSUE #4983: Fix deprecated methods in FormEntryPage
#### Problem description
In `FormEntryPage` we have deprecated methods like:
- swipeToNextQuestion
- swipeToPreviousQuestion
- clickOnDoNotAddGroup
- clickOnDoNotAddGroupEndingForm
- clickOnAddGroup

Every method has its own description so it should be clear what we want to use instead.

### PR DESCRIPTION
**Pull request by dczerwinski**
Closes #4983 

#### What has been done to verify that this works as intended?
Gradle task "checkTests" is running successfully.

#### Why is this the best possible solution? Were any other approaches considered?
The methods I removed were deprecated and have been replaced by the methods mentioned in the comments.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should not affect users.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [X] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [X] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [X] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@dczerwinski @grzesiek2010 I pushed a commit adding some extra strength to a flakey (unrelated to these changes) test that I ran into when doing a Test Lab check on the PR. I'm happy with this but will let someone else review now I've got code checked in.

**Comment by grzesiek2010** [comment]
> I pushed a commit adding some extra strength to a flakey (unrelated to these changes) test that I ran into when doing a Test Lab check on the PR. I'm happy with this but will let someone else review now I've got code checked in.

Ok I will review once we merge https://github.com/getodk/collect/pull/4971 since that pr might cause conflicts.

**Comment by grzesiek2010** [comment]
@dczerwinski please resolve conflicts.

**Comment by grzesiek2010** [comment]
@dczerwinski It looks like you accidentally got rid of the commit @seadowg pushed. Maybe you can find that branch in his repo https://github.com/seadowg/collect/branches if not @seadowg could you push again?

**Comment by dczerwinski** [comment]
> @dczerwinski It looks like you accidentally got rid of the commit @seadowg pushed. Maybe you can find that branch in his repo https://github.com/seadowg/collect/branches if not @seadowg could you push again?

Ahh yeah I actually accidentally deleted this commit, didn't have it pulled locally and thus forgot about it. Unfortunately, I can't find it in the @seadowg repo.

**Comment by grzesiek2010** [comment]
ok so @seadowg please push it again.

**Comment by seadowg** [comment]
@grzesiek2010 done!

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java [hunk 1]
```diff
@@ -332,7 +333,7 @@ public void values_ShouldBeRandom() {
         for (int i = 1; i <= 3; i++) {
             FormEntryPage formEntryPage = new MainMenuPage().startBlankForm("random");
             firstQuestionAnswers.add(getQuestionText());
-            formEntryPage.swipeToNextQuestion();
+            formEntryPage.swipeToNextQuestion("random");
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Here question text is `Your random once value:`

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java [hunk 2]
```diff
@@ -350,7 +351,7 @@ public void values_ShouldBeRandom() {
         for (int i = 1; i <= 3; i++) {
             FormEntryPage formEntryPage = new MainMenuPage().startBlankForm("random test");
             formEntryPage.inputText("3");
-            formEntryPage.swipeToNextQuestion();
+            formEntryPage.swipeToNextQuestion("random test");
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Here question text is `Your random number was`

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java [hunk 3]
```diff
@@ -606,11 +607,13 @@ public void missingFileMessage_shouldBeDisplayedIfExternalFIleIsMissing() {
...
                 .startBlankForm("cascading select test")
                 .clickOnText("Texas")
-                .swipeToNextQuestion()
+                .swipeToNextQuestion("-")
                 .assertText("File: " + formsDirPath + "/select_one_external-media/itemsets.csv is missing.")
-                .swipeToNextQuestion()
+                .swipeToNextQuestion("-")
                 .assertText("File: " + formsDirPath + "/select_one_external-media/itemsets.csv is missing.")
-                .swipeToNextQuestion(3)
+                .swipeToNextQuestion("-")
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: This form should be fixed. Please do that as a part of this pull request. I think it's a form from https://xlsform.org/en/#cascading-selects or very similar so questions should be like:
`Select state`
`Select county`
`Select city`

**Review by grzesiek2010 — DISMISSED** [review]

**Comment by grzesiek2010** [comment]
@dczerwinski and also please fix conflicts.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 3 above)
Comment (dczerwinski) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: I'm not sure but I think it's correct behaviour, because test is about missing .csv file. In case if there is missing .csv file there is "-" instead of question and red text "File xyz.csv is missing" under it.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 1 above)
Comment (dczerwinski) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Yes, I see it but when I changed question text to `Your random once value:` I get `NoMatchingViewException`. I'm not sure why.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 2 above)
Comment (dczerwinski) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Same here, when I changed text, then I get `NoMatchingViewException`.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Yes but csv file contain only choices (options to select) and questions should be specified in the xml file but we just have `-` there.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Oh that's because the question label is dynamically generated by adding random value:
```
		<input ref="/random/rand_note">
			<label>Your random value: 
				<output value=" /random/rand "/></label>
		</input>
```
It would be good to handle this somehow.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Ok I've fixed this.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: Ok I've fixed this.

File: collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java]: I've fixed this in https://github.com/getodk/collect/pull/4985/commits/38be1b2b95b09e26ed007ff2a66f9213693e7c8b
introducing:
```
private void assertQuestionText(String text) {
        onView(withIndex(withId(R.id.text_label), 0)).check(matches(withText(containsString(text))));
    }
```

so that now we are sure we test question label and we can verify dynamic labels passing just a part of its text.

**Comment by grzesiek2010** [comment]
@seadowg 
I've added some final changes so now you may want to review.

**Review by seadowg — APPROVED** [review]
