### PR TITLE
Only treat _ as markdown if separated by white space

### LINKED ISSUE #5508: Only treat _ as markdown if separated by white space
Every once in a while we get a question on the forum from someone who has select choices that look like `SEA_774_BOB` and are surprised to see them rendered as SEA<i>774</i>BOB. I'd always thought we had to live with this but @eyelidlessness pointed out that Markdown is kind of loose and maybe it doesn't have to be that way.

Github only interprets _ as markdown if they are separated by whitespace: 
* `SEA_774_BOB`: SEA_774_BOB
* `SEA _774_BOB`: SEA _774_BOB
* `SEA_774_ BOB`: SEA_774_ BOB
* `SEA _774_ BOB`: SEA _774_ BOB

Daring Fireball does say Emphasis can be used in the middle of a word:

`un*frigging*believable`: un*frigging*believable
`un_frigging_believable`: un_frigging_believable

Oh and look at that, Github has an exception just for _. That feels like the ideal behavior. We should decide and then make sure it's consistent across Enketo and Collect.

### LINKED ISSUE #5580: Rename Access control > Form Entry Settings > Save Form
The existing "Save Form" setting is in a section called "Uncheck to hide from Form Entry". Unchecking it hides the save button from the top bar and the "Save as draft" button from the form exit modal.

It's really not clear what to expect this setting to do, especially now that the setting after it is called "Save as draft".

I propose the following changes:

1) Rename "Save Form" to "Save as draft" and add subtext "Save icon in top bar and "Save as draft" button when exiting form"
2) Add a section header below it called "Uncheck to hide from Form End". That will contain "Save as draft" and "Finalize"

This reinforces the new language and matches the new code structure where form end and form entry are more separate.

~~A further change we could consider is separating the two concepts that are currently linked: we could have "Save icon" and "Save as draft" with subtext "In dialog when exiting form". We could migrate the existing "Save Form" setting to uncheck both settings if it's unchecked.~~

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5508 

#### What has been done to verify that this works as intended?
I've improved automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is what we discussed in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test styling with underscores `_` https://docs.getodk.org/form-styling/#emphasis. Other types of styling should rather be intact. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java [hunk 1]
```diff
@@ -77,32 +77,40 @@ static String markdownToHtml(String text) {
...
         text = text.replaceAll("(?s)\\*\\*(.*?)\\*\\*", "<strong>$1</strong>");
 
-        // emphasis
-        text = text.replaceAll("(?s)_([^\\s][^_\n]*)_", "<em>$1</em>");
-        text = text.replaceAll("(?s)\\*([^\\s][^\\*\n]*)\\*", "<em>$1</em>");
+        // emphasis using underscore
+        text = text.replaceAll("\\s_([^\\s][^_\n]*)_\\s", " <em>$1</em> ");
+        text = text.replaceAll("^_([^\\s][^_\n]*)_$", "<em>$1</em>");
+        text = text.replaceAll("^_([^\\s][^_\n]*)_\\s", "<em>$1</em> ");
+        text = text.replaceAll("\\s_([^\\s][^_\n]*)_$", " <em>$1</em>");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java:93]: Maybe it's possible to have one regex for all those 4 cases I don't know I'm not a master of regex. But even if it's possible I think this way is better because it's clear and such a one regex for all cases would be complicated.

File: collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java [hunk 2]
```diff
@@ -77,32 +77,40 @@ static String markdownToHtml(String text) {
                 text, createSpan);
 
         //intermediary replacements keys for special characters, N/B: These symbols are not meant to be interpreted as markdown
-        text = text.replaceAll("(?s)\\\\#", "&#35;");
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java:80]: `(?s)` in regex is called a  dot-all mode.
In the default mode (without (?s)), the dot (.) character in a regex pattern matches any character except a newline (\n). However, when (?s) is used, the dot (.) matches any character, including newline characters.
so it's about using dots but the lines I updated by removing `(?s)` didn't contain any.

File: collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java [hunk 3]
```diff
@@ -77,32 +77,40 @@ static String markdownToHtml(String text) {
...
-        text = text.replaceAll("(?s)_([^\\s][^_\n]*)_", "<em>$1</em>");
-        text = text.replaceAll("(?s)\\*([^\\s][^\\*\n]*)\\*", "<em>$1</em>");
+        // emphasis using underscore
+        text = text.replaceAll("\\s_([^\\s][^_\n]*)_\\s", " <em>$1</em> ");
+        text = text.replaceAll("^_([^\\s][^_\n]*)_$", "<em>$1</em>");
+        text = text.replaceAll("^_([^\\s][^_\n]*)_\\s", "<em>$1</em> ");
+        text = text.replaceAll("\\s_([^\\s][^_\n]*)_$", " <em>$1</em>");
+
+        // emphasis using asterisk
+        text = text.replaceAll("\\s\\*([^\\s][^\\*\n]*)\\*\\s", " <em>$1</em> ");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java]: I think we actually want to keep `*` the same. There's no practical use of `*` surrounded by text that I can think of. This is why Github makes the space special behavior only for `_`:

`un*frigging*believable`: un*frigging*believable
`un_frigging_believable`: un_frigging_believable

File: collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java [hunk 4]
```diff
@@ -31,15 +31,13 @@ public void markDownToHtmlEscapesBackslash() {
                 {"_A\\_B\\_C_", "<em>A_B_C</em>"},
                 {"A_B\\_C", "A_B_C"},
                 {"A\\_B_C", "A_B_C"},
-                {"A_B_C", "A<em>B</em>C"},
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java:34]: I think it would be helpful to keep the existing test cases with the new behavior so it's easier to see what changed. The new cases you added are helpful too so I suggest keeping both.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Sorry this took me forever to get to! Regex take a lot of concentration for me to read.

The behavior for `_` looks like what I would expect. I think we should revert the change to `*`.

File: collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java]: Ok I've reverted that change.

File: collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java:34]: Fixed.

**Review by lognaturel — APPROVED** [review]
Sweet!!

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:

- Issue #5508 is no longer reproducing;
- Checked different styling option in form e.g. white spaces before words, after words, in the middle of sentences;
- Regression check on other Styling options;
- Light and Dark mode;
- Rotate the screen, minimize the app;
