### PR TITLE
Fixed setting up the sort menu

### LINKED ISSUE #5856: Crash on the Sort by button in the Delete Form
I found this issue during testing #5829, so far I was able to reproduce it only in the Delete Tab, but on Master and Play store version 

#### ODK Collect version
master version 21e150b21eeb27f01177d17e70ced9634cc92e1e and play store version: 2023.3.0
#### Android version
13
#### Device used
Pixel 6a
#### Problem description
Crash occurs when rotating the screen and clicking on the Sort by button 
#### Steps to reproduce the problem

1. Configure a Demo project
2. Go to the Delete Form
3. In the Saved Form tab Click on the Sort By button
4. Close the sort tab and move to the Blank Forms tab
5. Rotate the screen
6. Click on the Sort by button
7. Close the sort tab, move to the Blank Forms tab and click on the Sort by button once again
8. The crash occurs
#### Expected behavior
There should be no crashes
#### Other information 

https://github.com/getodk/collect/assets/85225519/5d8ebbff-1cf0-4aa3-b9ec-369ae9abc504

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5856

#### Why is this the best possible solution? Were any other approaches considered?
We should use `getSelectedSortingOrder()` method to make sure the returned value is not null instead of directly accessing `selectedSortingOrder` field.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe and isolated change so we can focus on verifying that the problem described in the issue is fixed. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/DeleteSavedFormTest.java [hunk 1]
```diff
@@ -36,4 +38,18 @@ public void deletingAForm_removesFormFromFinalizedForms() {
                 .pressBack(new MainMenuPage())
                 .assertNumberOfFinalizedForms(0);
     }
+
+    @Test
+    public void accessingSortMenuInDeleteSavedInstancesShouldNotCrashTheAppAfterRotatingTheDevice() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/DeleteSavedFormTest.java:43]: I was hoping I could say "this could be a test for `XFragment`, but deleting a saved form still uses `AppListFragment` sadly! Hopefully this kind of test can be moved down to a Fragment level when we make the same changes we made for deleting blank forms (creating `DeleteBlankFormFragment` for example).

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 12,13

Verified cases;
- Issue #5856 is no longer reproducing;
- Sort Buttons;
- Don't keep activities enabled/disabled;
- Rotate the screen,minimize the app.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10
