### PR TITLE
Media files are lost when user changes them but then ignores the changes

### LINKED ISSUE #2049: Media files are lost when user changes them but then ignores the changes.
#### Software and hardware versions 
Collect v1.11.1, 1.14.0

#### Problem description
Media files are lost when user changes them but then ignores the changes.

#### Steps to reproduce the problem
1. User fills form and adds some media : video, photo, audio
screenshot_20180323-100230
2. User saves form
3. User edits form and update media
screenshot_20180323-100319
screenshot_20180323-100329
4. User ignore last changes 
screenshot_20180323-100336
5. User opens form again
screenshot_20180323-100354
6. Media is not available
screenshot_20180323-100419
screenshot_20180323-100424

#### Expected behavior
Media files are not removed from device when user clicks on change it but when user saves form.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2049 

#### What has been done to verify that this works as intended?
I tested mentioned scenario.

#### Why is this the best possible solution? Were any other approaches considered?
My second idea was to just get rid of removing media files at all during filling a form and then at the end check all answers and remove unused media files but it might be too complex (too much time needed) when a form is really big or user changed media files many times, so I decided to implement such a singleton.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media questions

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    }
+
+    public static MediaManager getInstance() {
+        if (singleton == null) {
+            singleton = new MediaManager();
+        }
+        return singleton;
+    }
+
+    public void markOriginalFileOrDelete(String index, String fileName) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java]: `questionIndex` would help make this a little more explicit.

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+        if (originalFiles.containsKey(index)) {
+            MediaUtils.deleteImageFileFromMediaProvider(fileName);
+        } else {
+            originalFiles.put(index, fileName);
+        }
+    }
+
+    public void markRecentFile(String index, String fileName) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java]: It's not clear from the name that this may also delete a file. Maybe something like `replaceRecentFileForQuestion`?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java]: Or is it really `replaceCurrentFileForQuestion`?

File: collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.odk.collect.android.utilities;
+
+import java.util.HashMap;
+import java.util.Map;
+
+public class MediaManager {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java]: It would be very helpful to have a comment on this class.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Some commenting and naming changes would help make this clearer but looks good overall!

**Comment by lognaturel** [comment]
Marking for testing since none of the changes modify behavior.

**Comment by kkrawczyk123** [comment]
### Tested with success!
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]
