### PR TITLE
Google account dialog no longer visible on send screen & account removal crash resolved

### LINKED ISSUE #2479: Google sheets upload crashes if account was removed from device
#### Software and hardware versions 
Collect v1.16.1, Android v7.0.0, Android 4.4.2, Google Nexus 6, Samsung Galaxy Tab Pro

#### Problem description
ODK Collect crashes when you attempt to do an upload via Google Sheets when you are using an account that has been removed from the device. 

#### Steps to reproduce the problem

1. Set your transport to Google Sheets and then select a Google account. 
2. Go to your device's settings and then navigate to the Google account manager.
3. Remove the account that you set for the Google Sheets upload.
4. Attempt to make a submission without changing the account.

#### Expected behavior
A dialog should remind you that the account was removed and it no longer exists so that you can go to the Settings and re-configure. #2464

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes #2479

#### What has been done to verify that this works as intended?

- Now when the account was set and then removed and you go to send a form it shows you the account selection dialog instead of crashing. 

- I turned the Wifi on and off so that a network event could be triggered that could cause the auto-send functionality to start and when it began and found there was no longer an account associated with the username that was stored it just stopped. 

- Now when an account is removed and you go to the Server settings instead of seeing the account listed the field is now blank since once the account has been removed and Collect is ran, it erases the value and returns an empty username. 

- Once you set an active account the functionality returns to normal and submissions can be made.

#### Why is this the best possible solution? Were any other approaches considered?
This is the best solution since it targets the main method that returning the user account and ensures the account exists before passing it off to the rest of the app.

#### Are there any risks to merging this code? If so, what are they?
No. We just have to verify that the functionality works as intended and there's no regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
No. 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks good to me! You do have an unused import, though (see PMD report). Do make sure to either run pmd locally and see results or wait to see if the CircleCI build passes before checking the box in the PR template!

**Comment by jd-alexander** [comment]
Yes, will do. I always run it locally. Gonna double check from now on!

**Comment by jd-alexander** [comment]
I'm gonna be refactoring some tests that were broken due to these changes and then I make a push for a review!

**Comment by jd-alexander** [comment]
@lognaturel quick question! I did a rebase to amend a commit message and the history got duplicated from the point of modification. Is that okay? I see a lot of discussions about preserving commit history but in this case since the PR hasn't been merged would it be good for me to find a way to get in without the duplicates?

**Comment by lognaturel** [comment]
> history got duplicated from the point of modification

I'm sorry, I'm not sure what that means! I don't see any duplicated commits. Could you link to a duplicated pair? What I do see are merge conflicts that will need to be resolve.

What I'd probably do is squash commits 6a59172 to 4ae7984 since the compound change is easy to understand. I'd call that something like `Fix crash when Google account is deleted` (notice it's short so the summary which truncates at 70 chars will be completely shown on one line) and with the explanation you have at 6a59172. I would keep d030263 and ac8db95 but shorten the message for ac8db95 to something like `Test getSelectedAccount when Google account deleted` to avoid the wrapping.

> I see a lot of discussions about preserving commit history but in this case since the PR hasn't been merged would it be good for me to find a way to get in without the duplicates?

That's really important for `master` and for branches that are being collaborated on. This is up to some debate but I personally think it's totally ok to rebase and force push in an in-progress branch like this. Otherwise, once there are too many noisy commits like 37f4f84 or 4ae7984 then I have a tendency to squash the whole PR which is too bad.

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 1]
```diff
@@ -170,7 +178,42 @@ public boolean checkAccountPermission() {
     }
 
     public String getSelectedAccount() {
-        return (String) preferences.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT);
+        Account[] googleAccounts = credential.getAllAccounts();
+        String account = (String) preferences.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT);
+
+        if (account == null) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: This condition is always `false`. The default value for this key is "" (blank) and not null
Line 106 : `PreferencesKeys.java`

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 2]
```diff
@@ -170,7 +178,42 @@ public boolean checkAccountPermission() {
...
+        }
+
+        if (googleAccounts != null && googleAccounts.length > 0) {
+            for (Account googleAccount : googleAccounts) {
+                if (googleAccount.name.equals(account)) {
+                    return account;
+                }
+            }
+
+            preferences.save(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT, null);
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: Instead of saving `null`, we can reset this preference using the `reset` method in `GeneralSharedPreferences`. That way it will never be equal to null

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 3]
```diff
@@ -170,7 +178,42 @@ public boolean checkAccountPermission() {
...
+
+            return null;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: redundant return statement

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 4]
```diff
@@ -170,7 +178,42 @@ public boolean checkAccountPermission() {
     }
 
     public String getSelectedAccount() {
-        return (String) preferences.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT);
+        Account[] googleAccounts = credential.getAllAccounts();
+        String account = (String) preferences.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT);
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: This can be moved within the `if-block` which asserts that `googleAccounts` are available

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java [hunk 5]
```diff
@@ -66,24 +69,34 @@ private void stubAccountPermission(boolean permission) {
...
+    }
+
+    private void stubAccount(String name) {
+        Account account = mock(Account.class);
+        Whitebox.setInternalState(account, "name", name);
+        doReturn(new Account[]{account}).when(mockedCredential).getAllAccounts();
+    }
+
+    private void removeAccounts() {
+        doReturn(new Account[]{}).when(mockedCredential).getAllAccounts();
```
Comment (shobhitagarwal1612) [inline collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java]: Method comment of `getAllAccounts()` says that 
```
 Returns all Google accounts or {@code null} for none. 
```

Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java]: So, returning null would be better in that case

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 6]
```diff
@@ -170,7 +178,42 @@ public boolean checkAccountPermission() {
...
+                    return account;
+                }
+            }
+
+            preferences.save(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT, null);
+
+            return null;
+        }
+
+        return null;
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: We should return `""` here

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java [hunk 7]
```diff
@@ -58,6 +60,7 @@
 
     private void stubSavedAccount(String accountName) {
         when(mockPreferences.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT)).thenReturn(accountName);
+        stubAccount(accountName);
```
Comment (shobhitagarwal1612) [inline collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: This stub can be removed as it is redundant and causes `credentials` to return blank account names which will never happen

Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: Okay, I get your point. The reason I had to add this here is that the tests were failing when the `credentials` didn't contain the account being checked for within the `getSelectedAccount` method fix I implemented.

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java (hunk 2 above)
Comment (jd-alexander) [reply collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: Oh awesome! Never knew about that method.

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 5 above)
Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java]: Yeah! Best to match the signature for sure.

File: collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java [hunk 8]
```diff
@@ -132,22 +141,53 @@ public void granted() {
...
-            showAccountPickerDialog();
+            if (fragment != null && fragment instanceof ServerPreferencesFragment) {
+                showAccountPickerDialog();
+            } else if (activity != null) {
+                showSettingsDialog();
+            }
         }
     }
 
     public String getSelectedAccount() {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java]: This function can be annotated with NonNull

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 7 above)
Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: Which test case is failing?

Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: These tests were failing. 



Yes, so mocking the `getAllAccounts` call allowed me to verify the new functionality adding in this PR and also verified that all the test cases relying on `getSelectedAccount` passed.

Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: Also when I merged in the new permissions code #2474 it broke most of the tests so I had to figure out a way to mock the way how the action on the listener was called when the permission is granted.

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java [hunk 9]
```diff
@@ -56,38 +66,51 @@
...
+        doReturn(new Account[]{account}).when(mockedCredential).getAllAccounts();
+    }
+
+    private void removeAccounts() {
+        doReturn(null).when(mockedCredential).getAllAccounts();
+    }
+
+    private void mockPermissionUtils() {
+        mockStatic(PermissionUtils.class, invocation -> {
+            Whitebox.invokeMethod(googleAccountsManager, "chooseAccount");
```
Comment (jd-alexander) [inline collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:91]: This was done because some of the approaches I was trying to utilize to invoke the direct `requestGetAccountsPermission` weren't working and I just decided that within this context the only function of the `PermissionsUtil` that we care about is this one so it's okay if an `Answer` just invokes the method that follows the permission being granted.

**Comment by jd-alexander** [comment]
@shobhitagarwal1612 ready for another review when you are! So we can get this merged in!

File: collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java [hunk 10]
```diff
@@ -134,14 +134,16 @@ private void uploadForms(Context context, boolean isFormAutoSendOptionEnabled) {
             String protocol = (String) settings.get(PreferenceKeys.KEY_PROTOCOL);
 
             if (protocol.equals(context.getString(R.string.protocol_google_sheets))) {
+
                 if (PermissionUtils.checkIfGetAccountsPermissionGranted(context)) {
-                    String googleUsername = (String) settings.get(PreferenceKeys.KEY_SELECTED_GOOGLE_ACCOUNT);
+                    GoogleAccountsManager accountsManager = new GoogleAccountsManager(Collect.getInstance());
+
+                    String googleUsername = accountsManager.getSelectedAccount();
                     if (googleUsername == null || googleUsername.isEmpty()) {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java]: Null check can be eliminated

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 9 above)
Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:91]: Directly invoking the intended method smells like coupled code to me. What if `GoogleAccountManager` implements `PermissionListener` and then instead of invoking the method using reflection, we do,
```
PermissionListener permissionListener = googleAccountsManager();
permissionListener.onGranted()
```

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 7 above)
Comment (shobhitagarwal1612) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: The new changes look good. But to ensure that credentials never return a blank account we should remove all `stubSavedAccount("");` from the test cases

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 9 above)
Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:91]: Thats true! The reason why it had to be done like this is `PermissionUtils` contain static methods that encapsulate the permissions management provided by the `Dexter` library. The listeners aren't directly implemented on calling component so I am not able to get a referene to it as you described so that's the reason this approach was taken.

Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:91]: The design decisions around the permissions code made it easy to replicate the changes across the codebase in a simpler manner without having the calling being tangled to the permissions logic. That was the idea behind it.

File: collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java (hunk 10 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java]: @jd-alexander can you please remove this `null` check if it really isn't needed and then we should be ok to go to testing?

Agreed with @shobhitagarwal1612 we may want to rethink some of the way permissions are handled but I think we should do it elsewhere.

Comment (jd-alexander) [reply collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java]: Yes, I thought I did this. Removing now. 

> Agreed with @shobhitagarwal1612 we may want to rethink some of the way permissions are handled but I think we should do it elsewhere.

Sure.

File: collect_app/src/main/res/values/strings.xml [hunk 11]
```diff
@@ -653,6 +651,8 @@
     <string name="rank_items">Rank items</string>
     <string name="image_not_saved">The image can not be saved because of a problem with the corresponding instance file.</string>
     <string name="loading_form_failed">An error occurred while loading the form. Please try again.</string>
+    <string name="missing_google_account_dialog_title">Google account not set</string>
+    <string name="missing_google_account_dialog_desc">To submit forms via Google Sheets you have to setup your Google account in the Server settings.</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: "setup" is a noun. In this case, we'd like the verb form which is "set up."

But it would be even better to reuse `google_invalid_account_title` and `google_invalid_account_description`. In general, we should be really careful about only adding new strings when absolutely necessary because they add a reading burden for enumerators and a translation burden for translators.

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 7 above)
Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: @jd-alexander there are still several `stubSavedAccount("");` in the tests. It would probably be best to change those to use a dummy account name, right?

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: Actually, now I'm not so sure. It seems all those cases have to do with actually setting a blank account so it seems ok to me.

File: collect_app/src/main/res/values/strings.xml (hunk 11 above)
Comment (jd-alexander) [reply collect_app/src/main/res/values/strings.xml]: > because they add a reading burden for enumerators and a translation burden for translators.

That's a really good point. Will definitely keep that in mind when creating strings.

File: collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java (hunk 7 above)
Comment (jd-alexander) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: I just did a check and I realized that it's not necessary to set the blank account since `getSelectedAccount` is returning an empty string so the tests are able to verify functionality without utilizing a blank account which would be the opposite of how the underlying `GooogleAccountCredential' API operates so I am removing them and pushing as we speak.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java:69]: Ahhh, thank you, that makes sense. 😊

**Comment by mmarciniak90** [comment]
Hi @jd-alexander  
I was able to reproduce the crash on all devices.
The main case works as expected. The crash does not occur and the dialog appears.
Tested on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

But I noticed one small case which could be improved:
1. User sees dialog 'Google account not set'
2. User clicks on device back button
3. The dialog is closed but the user is not moved to the previous screen but sees an empty view. The user needs to clicks on device back button once more to backs to ODK. I feel that clicking on OK and device back button should cause the same effect in this case.

**Comment by jd-alexander** [comment]
@mmarciniak90 thanks for spotting this! Gonna take a look!

**Comment by jd-alexander** [comment]
@mmarciniak90  I resolved the issue and ran several tests myself and it's working great now. You can do a check and let me know if all is well.

**Comment by mmarciniak90** [comment]
@jd-alexander thanks for the quick fix! 

**Tested with success!**

Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
* ODK Collect does not crash when Google Account is not longer available
* The dialog appears:


@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Comment by jd-alexander** [comment]
Awesome!

**Review by lognaturel — APPROVED** [review]
