### PR TITLE
Do not log REPEATS_IN_FIELD_LIST as errors

### LINKED ISSUE #4760: Exception: java.net.MalformedURLException: no protocol: /formList
#### Software and hardware versions 
Collect v1.30.0+

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/0eb21b2826f841ac4546edde025cef48?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=6102F10300F000011AF48BD27C5DA83F_1568862901923153964

```
Non-fatal Exception: java.net.MalformedURLException: no protocol: /formList
       at java.net.URL.<init>(URL.java:590)
       at java.net.URL.<init>(URL.java:487)
       at java.net.URL.<init>(URL.java:436)
       at org.odk.collect.android.openrosa.OpenRosaXmlFetcher.fetch(OpenRosaXmlFetcher.java:93)
       at org.odk.collect.android.openrosa.OpenRosaXmlFetcher.getXML(OpenRosaXmlFetcher.java:54)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.lambda$fetchFormList$0(OpenRosaFormSource.java:42)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.lambda$fetchFormList$0$OpenRosaFormSource(OpenRosaFormSource.java)
       at org.odk.collect.android.openrosa.-$$Lambda$OpenRosaFormSource$oHfwyAcGQVxhQTD7_HASB3hwlMU.call(-.java:2)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.mapException(OpenRosaFormSource.java:130)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.fetchFormList(OpenRosaFormSource.java:42)
```

### LINKED ISSUE #4765: Repeats in 'field-list' groups are not supported
#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/44e210b9709c05e63a7a9b8906186ff0?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=6102364401A700014F16018A0C782435_1568721843148212031

```
Non-fatal Exception: java.lang.RuntimeException: Repeats in 'field-list' groups are not supported. Please update the form design to remove the following repeat from a field list: /data/g2/g03/c06
       at org.odk.collect.android.formentry.audit.AuditUtils.logCurrentScreen(AuditUtils.java:28)
       at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1108)
       at org.odk.collect.android.activities.FormEntryActivity.animateToNextView(FormEntryActivity.java:1384)
       at org.odk.collect.android.activities.FormEntryActivity.onScreenChange(FormEntryActivity.java:1350)
       at org.odk.collect.android.formentry.FormIndexAnimationHandler.handle(FormIndexAnimationHandler.java:34)
       at org.odk.collect.android.activities.FormEntryActivity$3$1.lambda$run$0(FormEntryActivity.java:1623)
       at org.odk.collect.android.activities.FormEntryActivity$3$1.lambda$run$0$FormEntryActivity$3$1(FormEntryActivity.java)
       at org.odk.collect.android.activities.-$$Lambda$FormEntryActivity$3$1$90F3IbGPo_zO8Zgl29VDQyPAMYI.run(-.java:2)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4765

#### What has been done to verify that this works as intended?
I reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
The implementation is consistent with what we agreed on in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java [hunk 1]
```diff
@@ -250,4 +250,9 @@ private AnalyticsEvents() {
      * Tracks how often form details with null or empty hashes are provided by a server
      */
     public static final String NULL_OR_EMPTY_FORM_HASH = "NullOrEmptyFormHash";
+
+    /**
+     * Tracks how often repeat groups are used in field-list groups
+     */
+    public static final String REPEATS_IN_FILED_LIST = "RepeatsInFieldListException";
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java]: I don't think we need to track analytics for this because I don't think it will change our behavior. We know it's something some people try to do. At some point in some future we know we might want to have a table or otherwise condensed view of a repeat. Maybe that view will be used if a repeat is in a field-list or maybe that will still not be allowed. We know that's a fairly big project that we won't be prioritizing soon.

**Review by lognaturel — DISMISSED** [review]
Looks good but I think we can remove analytics!

File: collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java]: If we do choose to keep analytics, the constant name should be updated FILED -> FIELD

**Comment by seadowg** [comment]
@grzesiek2010 as discussed in #4765, let's just go ahead and remove any logging of this.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 as discussed in #4765, let's just go ahead and remove any logging of this.

done.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
Going to merge this assuming @lognaturel will be happy given we've just removed the analytics.

**Comment by lognaturel** [comment]
Thanks! I get overwhelmed when there are too many analytics events being tracked so I think this is the right move. We're not great about keeping up with the things we already do want to keep an eye on.
