### PR TITLE
Match exactly errors

### LINKED ISSUE #3959: Add error handling to Match Exactly sync
**Acceptance**

- [x] Given I've set up Match Exactly and have navigated to Fill Blank Forms
And my server is down/not available (`UnknownHostException`)
When I tap ♻️ (refresh)
Then I see an error notification
When I click on the notification
Then it takes me to Fill Blank Form
And I see an error badge on the refresh button

- [x] Given I've set up Match Exactly and have navigated to Fill Blank Forms
And my credentials have been revoked/changed (a `401`)
When I tap ♻️ (refresh)
Then I see an error notification
When I click on the notification
Then it takes me to Fill Blank Form
And I see a prompt to fix credentials (like Get Blank Forms)
And I see an error badge on the refresh button

- [x] Given I've set up Match Exactly and have navigated to Fill Blank Forms
When I tap ♻️ (refresh)
And then **ANY** (includes form list, manifest or download) of the network requests fail
Then I see an error notification
When I click on the notification
Then it takes me to Fill Blank Form
And I see an error badge on the refresh button

- [x] Given I've set up Match Exactly and have navigated to Fill Blank Forms
When I tap ♻️ (refresh)
And then there is file system error
Then I see an error notification
When I click on the notification
Then it takes me to Fill Blank Form
And I see an error badge on the refresh button

- [x] Given I've had an error
When I navigate to Fill Blank Forms
When I tap ♻️ (refresh)
And the sync succeeds
Then the error state disappears

- [x] Given I've set up Match Exactly and have navigated to Fill Blank Forms
And the server returns bad form list and or manifest responses
When I tap ♻️ (refresh)
Then I see an error notification
When I click on the notification
Then it takes me to Fill Blank Form
And I see an error badge on the refresh button

- [x] All errors while syncing in the background should result in same notification and error badge

### PR DESCRIPTION
**Pull request by seadowg**
Closes #3959

Although the intention of the issue is just to add errors for Match Exactly mode we talked back and forth about how possible it would be to also improve other error messages in the app. In the end only really Get Blank Form's initial form list fetch had improvements along with Match Exactly. I think any further changes would require us to spec out what we want to see for each flow. Plus, this PR was big enough already.

#### What has been done to verify that this works as intended?

Played around with the app and also added a lot of new tests (including back fills for existing flows)

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Again, keeping track of this for QA. I'd be tempted to say we should start playing with some of the features on master after we merge this as the core UI flows are now all in.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java [hunk 1]
```diff
@@ -73,6 +77,56 @@ public void whenMatchExactlyEnabled_getsLatestFormsFromServer_automaticallyAndRe
                 .assertTextDoesNotExist("Two Question");
     }
 
+    @Test
+    public void whenMatchExactlyEnabled_andThereIsAnErrorDuringUpdate_clickingErrorNotification_goesToFillBlankForm() throws Exception {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java:81]: The positive case for this is currently in `GetAndSubmitFormsTest`

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    public CollectTestRule rule = new CollectTestRule();
+
+    final TestDependencies testDependencies = new TestDependencies();
+
+    @Rule
+    public RuleChain copyFormChain = TestRuleChain.chain(testDependencies)
+            .around(rule);
+
+    @Test
+    public void whenThereIsAnAuthenticationErrorFetchingFormList_allowsUserToReenterCredentials() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java:27]: The positive test case for this is currently in `GetAndSubmitFormsTest`

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java [hunk 3]
```diff
@@ -597,33 +572,55 @@ public void formListDownloadingComplete(HashMap<String, ServerFormDetails> resul
             toggleButtonLabel(toggleButton, listView);
 
             if (viewModel.isDownloadOnlyMode()) {
-                //1. First check if all form IDS could be found on the server - Register forms that could not be found
+                performDownloadModeDownload();
+            }
+        } else {
+            switch (exception.getType()) {
+                case FETCH_ERROR:
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java:579]: We could also use the new less granular/more human errors for form download as well, but we'd need to discuss how that works. Collect is currently really verbose and outputs the failure/success status for each form so it's not as simple as just switching out the text.

I think writing up an issue/feature for how errors should look on Get Blank Form would be ideal.

File: async/src/main/java/org/odk/collect/async/WorkerAdapter.kt [hunk 4]
```diff
@@ -7,7 +7,12 @@ import androidx.work.WorkerParameters
 abstract class WorkerAdapter(private val spec: TaskSpec, context: Context, workerParams: WorkerParameters) : Worker(context, workerParams) {
 
     override fun doWork(): Result {
-        spec.getTask(applicationContext).run()
-        return Result.success()
+        val completed = spec.getTask(applicationContext).get()
+
+        return if (completed) {
+            Result.success()
```
Comment (seadowg) [inline async/src/main/java/org/odk/collect/async/WorkerAdapter.kt:13]: We don't care about `Result.failure()` as the only thing it does is give let us inspect failure counts in following work which we're not doing.

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java [hunk 5]
```diff
@@ -73,4 +128,13 @@ private boolean allFormsDownloadedSuccessfully(Context context, HashMap<ServerFo
         }
         return true;
     }
+
+    // The application context will give us the system's locale
+    private Resources getLocalizedResources(Context context) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java:134]: I think there are still a few strings in both the auto send and auto download flows that may end up not translated. This is an existing issue however, so I didn't want to dedicate too much time to restructuring everything to fix it. I reckon we just create an issue for this?

File: collect_app/src/main/java/org/odk/collect/android/openrosa/api/FormListApi.java [hunk 6]
```diff
@@ -1,10 +1,15 @@
...
+import java.io.InputStream;
 import java.util.List;
 
 public interface FormListApi {
 
     List<FormListItem> fetchFormList() throws FormApiException;
 
     ManifestFile fetchManifest(String manifestURL) throws FormApiException;
+
+    InputStream fetchForm(String formURL) throws FormApiException;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/openrosa/api/FormListApi.java:12]: `fetchForm` and `fetchMediaFile` happen to have the same implementation but it felt keeping the separate was the right thing to do™️ as the call sites don't really know or care that they involve the same work.

File: collect_app/src/main/java/org/odk/collect/android/utilities/MultiFormDownloader.java [hunk 7]
```diff
@@ -44,42 +44,29 @@
...
-
 import timber.log.Timber;
 
 import static org.odk.collect.android.utilities.FileUtils.LAST_SAVED_FILENAME;
 import static org.odk.collect.android.utilities.FileUtils.STUB_XML;
 import static org.odk.collect.android.utilities.FileUtils.write;
 
-public class MultiFormDownloader implements FormDownloader {
+@Deprecated
+public class MultiFormDownloader {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/MultiFormDownloader.java:58]: I had a good go at chipping away at this but there is far more to be done. I think we need to get to a point where we're not calling this anywhere but `ServerFormDownloader` to really start tearing it apart. There is a lot of logic around task cancellation in here that needs to get the hell out.

File: collect_app/src/main/res/drawable/ic_baseline_refresh_error_24.xml [hunk 8]
```diff
@@ -0,0 +1,10 @@
+<vector xmlns:android="http://schemas.android.com/apk/res/android"
```
Comment (seadowg) [inline collect_app/src/main/res/drawable/ic_baseline_refresh_error_24.xml:1]: This is just showing the same refresh button in the error color right now. I think ultimately we want a "badge" but if everyone can live with this initially it'll save time faffing around with the new beta badging API (or in creating a new icon).

File: collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java [hunk 9]
```diff
@@ -27,23 +30,43 @@
     private final String serverURL;
     private final String formListPath;
 
-    public OpenRosaFormListApi(OpenRosaXmlFetcher openRosaXMLFetcher, String serverURL, String formListPath) {
-        this.openRosaXMLFetcher = openRosaXMLFetcher;
+    public OpenRosaFormListApi(String serverURL, String formListPath, OpenRosaHttpInterface openRosaHttpInterface, WebCredentialsUtils webCredentialsUtils) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java:33]: I killed all the error messages coming out of here and pretty much all the error logging. Most of it isn't needed to show the errors we're trying to show. Good to check and see if any of it feels like something we'd need to keep.

File: collect_app/src/main/AndroidManifest.xml [hunk 10]
```diff
@@ -113,7 +113,7 @@ the specific language governing permissions and limitations under the License.
             android:configChanges="orientation|screenSize"
             android:windowSoftInputMode="stateHidden" />
         <activity android:name=".activities.InstanceChooserList" />
-        <activity android:name=".activities.FormChooserListActivity" />
+        <activity android:name=".activities.FillBlankFormActivity" />
```
Comment (lognaturel) [inline collect_app/src/main/AndroidManifest.xml:116]: Hah. I held back from asking for this in the last PR. Makes so much more sense.

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java (hunk 5 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java:133]: Yes, please.

File: collect_app/src/main/res/values/strings.xml [hunk 11]
```diff
@@ -150,11 +147,6 @@
     <string name="submission_url">Submission path</string>
     <string name="font_size">Text font size</string>
     <string name="change_font_size">Text font size</string>
-    <string name="access_error">Error while accessing %s: </string>
-    <string name="manifest_server_error">Manifest reply does not report an OpenRosa version — bad server?</string>
-    <string name="root_element_error">Root element is not &lt;manifest\&gt; — was %s</string>
-    <string name="root_namespace_error">Root element Namespace is incorrect: %s</string>
-    <string name="manifest_tag_error">Manifest entry %s is missing one or more tags: filename, hash, or downloadUrl</string>
     <string name="form_download_progress">%1$s. Getting media files: %2$s of %3$s</string>
     <string name="fetching_manifest">%s. Getting manifest </string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml:151]: This one can also be rolled into a generic error, I think.

**Review by lognaturel — COMMENTED** [review]
I unfortunately haven’t yet had as much time with this as I wanted. 

I think coming back to messages that are displayed for individual forms is fine. I was thinking we’d reuse the exact same strings and possibly end up with redundant messages but it’s not urgent and it’s not worth growing the scope. I agree with getting QA involved as soon as this is merged. The change in delete behavior will hopefully be relatively isolated. 

Nothing else jumps at me.

File: collect_app/src/main/res/values/strings.xml (hunk 11 above)
Comment (seadowg) [reply collect_app/src/main/res/values/strings.xml:151]: I'm pretty sure this string is just used for progress updates. Not sure what you mean.

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java (hunk 5 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java:134]: Issue at #3988

File: collect_app/src/main/res/values/strings.xml (hunk 11 above)
Comment (lognaturel) [reply collect_app/src/main/res/values/strings.xml:151]: More of a note to self to check how it’s used. The user should not see the word manifest anywhere.

Comment (seadowg) [reply collect_app/src/main/res/values/strings.xml:151]: Yeah I think a lot of the progress updates in the app are things we could get rid of now. A lot of detail that doesn't help anyone!

File: async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt [hunk 12]
```diff
@@ -17,6 +17,19 @@ class CoroutineAndWorkManagerScheduler(private val foreground: CoroutineContext,
         }
     }
 
+    override fun networkDeferred(tag: String, spec: TaskSpec) {
```
Comment (lognaturel) [inline async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt:20]: Nit: could this be grouped with the other variant?

File: collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java [hunk 13]
```diff
@@ -207,8 +206,7 @@ void init() {
      * Updates whether an auto-send job is ongoing.
      */
     private void updateAutoSendStatus() {
-        LiveData<List<WorkInfo>> statuses = WorkManager.getInstance().getWorkInfosForUniqueWorkLiveData(AutoSendWorker.TAG);
-
+        LiveData<List<WorkInfo>> statuses = WorkManager.getInstance().getWorkInfosForUniqueWorkLiveData("AutoSendWorker");
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java]: Seems better to use `AUTO_SEND_TAG`?

File: collect_app/src/main/res/values/strings.xml [hunk 14]
```diff
@@ -710,4 +702,7 @@
     <string name="form_update_mode_title">Blank form update mode</string>
     <string name="previously_downloaded_only">Previously downloaded forms only</string>
     <string name="form_update_frequency_title">Automatic update frequency</string>
+    <string name="form_update_error">Form update failed</string>
+    <string name="generic_network_error">If you keep having this problem, report it to the person who asked you to collect data.</string>
```
Comment (lognaturel) [inline collect_app/src/main/res/values/strings.xml]: I think we're going to use this in more places including where form design might be the issue. Let's call the resource something like `report_to_project_lead`.

File: collect_app/src/main/java/org/odk/collect/android/preferences/ServerAuthDialogFragment.java [hunk 15]
```diff
@@ -0,0 +1,59 @@
...
+        ServerAuthDialogBinding binding = ServerAuthDialogBinding.inflate(requireActivity().getLayoutInflater());
+        dialogView = binding.getRoot();
+
+        SharedPreferences generalSharedPreferences = preferencesProvider.getGeneralSharedPreferences();
+        binding.usernameEdit.setText(generalSharedPreferences.getString(GeneralKeys.KEY_USERNAME, ""));
+        binding.passwordEdit.setText(generalSharedPreferences.getString(GeneralKeys.KEY_PASSWORD, ""));
+
+
+        return new AlertDialog.Builder(requireContext())
+                .setTitle(R.string.server_requires_auth)
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/preferences/ServerAuthDialogFragment.java:44]: Like for the manual update case, this should also include the string `server_auth_credentials` because that indicates what server needs credentials.

File: collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java (hunk 9 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java:33]: Yup, looks good to me.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java [hunk 16]
```diff
@@ -0,0 +1,30 @@
...
+
+import org.odk.collect.android.R;
+import org.odk.collect.android.application.Collect;
+import org.odk.collect.android.utilities.MultiFormDownloader;
+
+import java.util.Collections;
+import java.util.HashMap;
+
+/**
+ * Provides a sarcophagus for {@link org.odk.collect.android.utilities.MultiFormDownloader} so it
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java:11]: Hah. Never seen sarcophagus used that way but it makes so much sense.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java [hunk 17]
```diff
@@ -0,0 +1,23 @@
...
+
+    private final Resources resources;
+
+    public FormApiExceptionMapper(Resources resources) {
+        this.resources = resources;
+    }
+
+    public String getMessage(FormApiException exception) {
+        if (exception.getType() == FormApiException.Type.UNKNOWN_HOST) {
+            return resources.getString(R.string.unknown_host_error, exception.getServerUrl());
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java]: In this case we ALSO want to include the "if it keeps happening, talk to the person who asked you to collect data" message. I think just concatenating the two with a space would be fine (and concat does the right thing with LTR languages, I believe)

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java [hunk 18]
```diff
@@ -597,33 +572,55 @@ public void formListDownloadingComplete(HashMap<String, ServerFormDetails> resul
...
+                case UNKNOWN_HOST:
+                    String dialogMessage = new FormApiExceptionMapper(getResources()).getMessage(exception);
+                    String dialogTitle = getString(R.string.load_remote_form_error);
+
+                    if (viewModel.isDownloadOnlyMode()) {
+                        setReturnResult(false, getString(R.string.load_remote_form_error), viewModel.getFormResults());
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java]: Why not `dialogMessage`? That seems a lot more useful.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Leak Canary reports leaks of `ServerAuthDialogFragment` and `RefreshFormListDialogFragment`

Ideally the auth required case would pop the dialog up on Fill Blank Form when update is manually triggered. That's not necessarily an error -- the user may just not want Collect to manage their password. Bumping that to a future version is fine because it's not likely to be common.

**Comment by seadowg** [comment]
@lognaturel thanks for the comments. I hadn't noticed the leaks but I'll investigate and then get started on the tweaks you suggested.

**Comment by seadowg** [comment]
@lognaturel I wasn't able to reproduce the leak with `ServerAuthDialog` but did see the `RefreshFormListDialogFragment`. Could you post the steps you took to get to the leak?

With the `RefreshFormListDialogFragment` I'm see a third party library leak. It looks like it is leaked by a `HandlerThread` in some way and as far as I can see there isn't much we can do about it. Were you seeing the same thing?

Screenshot_1596010817

File: collect_app/src/main/res/values/strings.xml (hunk 14 above)
Comment (seadowg) [reply collect_app/src/main/res/values/strings.xml]: Good call.

File: collect_app/src/main/java/org/odk/collect/android/preferences/ServerAuthDialogFragment.java (hunk 15 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/preferences/ServerAuthDialogFragment.java:44]: Done!

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java (hunk 18 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java]: Good point. Will change.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java (hunk 16 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java:11]: It's great terminology. I like that it implies it is protecting both the thing in the "sarcophagus" and the things outside.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java (hunk 17 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java]: Right that makes sense.

File: collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java [hunk 19]
```diff
@@ -84,10 +84,11 @@ public void onUpdatesDownloaded(HashMap<ServerFormDetails, String> result) {
     @Override
     public void onSyncFailure(FormApiException exception) {
         Intent intent = new Intent(application, FillBlankFormActivity.class);
+        intent.putExtra(FillBlankFormActivity.EXTRA_AUTH_REQUIRED, true);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java:87]: This needs to be reverted.

**Comment by lognaturel** [comment]
Thanks! Some testing changes stuck around and need to be reverted. Another problem I noticed is that tapping on a form sync notification launches the Fill Blank Form activity, regardless of whether it's already at the top of the stack or not. So you can end up with lots of them stacked. I hope this won't be too big of a deal to address. If it's a lot of changes, perhaps we should merge before to avoid painful conflicts with #3992.

> I wasn't able to reproduce the leak with ServerAuthDialog but did see the RefreshFormListDialogFragment. Could you post the steps you took to get to the leak?

It could be something Android 5.1 specific. I'm not seeing it on my emulator. Let's see if QA sees it too.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@getodk-bot label "needs testing"

**Comment by mmarciniak90** [comment]
@seadowg could you describe the repro steps to 2 errors mentioned in comment: https://github.com/getodk/collect/issues/3959#issuecomment-662100479

* "Form update failed. Please try again." only for form update issues.
* "Form download failed. Please try again." only for get blank form issues.

**Comment by seadowg** [comment]
@mmarciniak90 ah sorry I don't think you'll ever see the second one ("Form download failed. Please try again."). Match exactly errors always use that first wording.

**Comment by mmarciniak90** [comment]
Tested as a part of Match exactly feature verification

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
