### PR TITLE
Fixed the trash button logic in GeoWidget, Fix #2633

### LINKED ISSUE #2633: Incorrect disable and enabled logic of Geobuttons
#### Software and hardware versions 
geo widgets on Android 4.4, 5.1, 6.0, 7.0, 8.1

#### Problem description
The logic of disabled and enabled geo buttons is incorrect, and you can see more details in this [comment](https://github.com/opendatakit/collect/pull/2276#issuecomment-428568004).

Trash button has a logic problem in:
- geopoint type with placement-map appearance
- geopoint type with map appearance
- geoshape type with no appearance

Zoom button has a logic problem in:
- geoshape type with no appearance

#### Steps to reproduce the problem
- open the geo widget.
- see the whether the button is active or disabled in different cases.

#### Expected behavior
- Buttons should be correct.

#### Other information 
@zestyping If you would like to fix these in your refactor about geo widget, you can claim this issue and please let me know, or I will sent a PR recently. :)

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #2633 

#### What has been done to verify that this works as intended?
I have tested in my android emulator (Api 25) and Huawei Nexus 6P (Api 26).

#### Why is this the best possible solution? Were any other approaches considered?
Added some judgements about the trash button, it's quite simple but needs lots a detailed test.
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regression risks.
#### Do we need any specific form for testing your changes? If so, please attach one.
GeoWidgets.
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
N/A
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by huangyz0918** [comment]
- [x] The trash button in Geopoint Widget
- [ ] The trash button in Geoshape Widget
- [ ] The zoom button in Geoshape Widget

**Comment by huangyz0918** [comment]
I cannot reproduce the issue with trash button and zoom button in geo shape widget, which was mentioned at [here](https://github.com/opendatakit/collect/pull/2276#issuecomment-428568004). Do you mean disabling the GPS before entering the map view? 

Is this issue was fixed by other commits or PRs? @mmarciniak90 @lognaturel 

I fixed the issues in Geo Point Widgets but I can't see any downsides in Geo Trace or Geo Shape. So I'd  like to remove the `WIP` and make this PR prepared.

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java [hunk 1]
```diff
@@ -496,6 +504,14 @@ private void showGPSDisabledAlertToUser() {
         errorDialog.show();
     }
 
+    private void resetTrashButton() {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java]: If the trash button has to be modified whenever `marker` is updated, so then they should sit close to each other. That means, `marker` should be modified only from a single method which should also contain the logic to update the `trash` icon along with it every time. This will remove the overhead of updating the state of trash icon from all of the places. 
What are your thoughts?

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java [hunk 2]
```diff
@@ -545,6 +553,14 @@ public void run() {
         }
     }
 
+    private void resetTrashButton() {
```
Comment (shobhitagarwal1612) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java]: Same as above

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java (hunk 1 above)
Comment (huangyz0918) [reply collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java]: I understand what you mean, let me take a look at it.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
I went through all issues from https://github.com/opendatakit/collect/pull/2276#issuecomment-428568004 and verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
This looks good to me! Beyond the behavior improvement, grouping the statements that are executed when there's a change in markers seems like a good thing. I would recommend adding a comment on the new methods, @huangyz0918, so that it's easier for the next person that comes along to know how to use them and exactly what their side effects are.

@zestyping, you're in this code as well so do you want to give a quick sanity check?

**Comment by zestyping** [comment]
Given that every line of `changeMarker` does different things depending on whether `isAdd` is true or false, it seems like it's really two different methods, one for adding the marker and one for removing it.  So I would suggest to split it into two methods with appropriate names so that there's no need to guess what `isAdd` means.

I second the suggestion to add a comment to the new method (or methods) so that it's clear what the intended purpose is.

Otherwise, this looks fine!

**Comment by huangyz0918** [comment]
Done with little code refactoring. 
@lognaturel @zestyping Thanks for your suggestions!

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
🎉 Thanks, @huangyz0918!

**Comment by lognaturel** [comment]
Oh, for next time, javadoc-style comments are always nice because they make it into auto-generated docs and can be easily accessed through IDEs. 👍

**Comment by huangyz0918** [comment]
Sure, roger that .😸
