### PR TITLE
Use API 30 for instrumentation tests

### LINKED ISSUE #4874: Use API 30 for instrumentation tests
We should be using our target API with Firebase, so we catch problems on the newest (and often strictest) OS.

## Notes

I did a quick recce on this and found there are a bunch of failures (in the 20s) after moving to an API 30 device. It looks like they are all related to these problems:

- [x] Toast assertions don't work (https://github.com/android/android-test/issues/803)
- [x]  Middle toasts show as dialogs and need to be closed before moving on (`FormValidationTest`)
- [x]  Not permitted to create temp files (`IntentGroupTest`)
- [x] UIAutomator notification assertions are potentially flakey?

### LINKED ISSUE #5374: Use a rear camera in image/video selfie widgets if there is no front camera
#### Problem description
If an Image Selfie or Video Selfie widget is used and there is no front camera a reare one should be used.

#### Steps to reproduce the problem
1. Find a device without a front camera
2. Open any form with an Image Selfie or Video Selfie widget
3. Try to use such a widget 

#### Expected behavior
A user should not be blocked and a rear camera should be used.

#### Other information 
We agreed on this in https://github.com/getodk/collect/pull/5367#discussion_r1036967346

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4874 
Closes #5374 

#### What has been done to verify that this works as intended?
I've run automated tests using Pixel 3 API 30,

#### Why is this the best possible solution? Were any other approaches considered?
Nothing to discuss here we just need to update API level used to run tests. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
I have some randomly failing tests Very often those are tests form `InstanceEditActionTest` but I can't reproduce locally at all. Logs unfortunately also do not tell a lot... @seadowg you have worked more with fixing weird problems like that so maybe you have some ideas? My last attempt was this one https://console.firebase.google.com/u/1/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/7520911014417365904/details?stepId=bs.524c6f08bbbf0857&testCaseId=1

**Comment by seadowg** [comment]
Hmmm. I'll take a look and see if there's anything that sticks out to me. ~~For the moment, I've just added a commit that removes our custom `NestedScrollToAction` as Espresso 3.5.0 now supports `NestedScrollView`.~~

EDIT: CircleCI is really unhappy with me adding a commit and I don't fancy spending the rest of my day wrestling with it. We can come back to removing `NestedScrollToAction` another time.

**Comment by grzesiek2010** [comment]
> EDIT: CircleCI is really unhappy with me adding a commit and I don't fancy spending the rest of my day wrestling with it. We can come back to removing NestedScrollToAction another time.

I did that and it looks fine.

**Comment by seadowg** [comment]
Playing around with this some more, it seems to me that we want to switch to using one of the `.arm` devices as they're the only virtual devices that support APIs over 30. It looks like they might have their own set of problems (like not having a front camera), but I'll give solving those a go.

**Comment by seadowg** [comment]
I think this is ready to go now. A couple of notes:

* I ended up fixing #5374 as it was easier than making the tests work around there being no front camera
* I removed a test in https://github.com/getodk/collect/pull/5344/commits/ad0e5c2f3c17205e6f8db9d74bb461c1662382fd. This test was added as part of solving https://github.com/getodk/collect/issues/4819, but it seems like it's hard to get a dependable automated test for the issue working. @getodk/testers could we add a manual regression for that issue please?

**Comment by srujner** [comment]
@seadowg Of course, we'll add it.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt [hunk 1]
```diff
@@ -99,6 +99,12 @@ class NotificationDrawer {
             // "Clear all" doesn't exist because there are notifications to clear - just press back
             pressBack()
         }
+
+        // Exit with back if "Clear all" didn't take care of it
+        if (device.findObject(By.text("Notifications")) != null) {
+            device.findObject(By.text("Clear all"))
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: We do the same above so why do we need this here?

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt]: Oh no. I had meant this to call `pressBack` in the `if`, but I made a mistake, and somehow it solved the problem I was having. Potentially the extra element look-ups delay other assertions long enough to fix something. I'll investigate further.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java [hunk 2]
```diff
@@ -88,14 +87,6 @@ protected void setUpLayout() {
 
         hideButtonsIfNeeded(appearance);
         errorTextView.setVisibility(View.GONE);
-
-        if (selfie) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:92]: Don't we need this?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:92]: Ah, now I see we wanted do use the front one in this case.

**Comment by grzesiek2010** [comment]
> Playing around with this some more, it seems to me that we want to switch to using one of the .arm devices as they're the only virtual devices that support APIs over 30.

Could you tell more about it? We don't need API 31+ now so why can't we use a pixel device like before? Are those arm devices more reliable somehow?

**Comment by seadowg** [comment]
@grzesiek2010 the Firebase docs seem to be really pushing them, and I noticed that they had not added support for > API 30 on the Pixel devices. I found that the tests were a bit faster (and also seemed more stable) on the `.arm` devices I had a play with as well.

**Comment by grzesiek2010** [comment]
I can't approve it because it's my pull request but I've reviewed your changes @seadowg and you have my approval so you can merge.

**Comment by grzesiek2010** [comment]
or maybe we should rather test it since it addresses https://github.com/getodk/collect/issues/5374 too...

**Comment by srujner** [comment]
> I think this is ready to go now. A couple of notes:
> 
>     * I ended up fixing [Use a rear camera in image/video selfie widgets if there is no front camera #5374](https://github.com/getodk/collect/issues/5374) as it was easier than making the tests work around there being no front camera
> 
>     * I removed a test in [ad0e5c2](https://github.com/getodk/collect/commit/ad0e5c2f3c17205e6f8db9d74bb461c1662382fd). This test was added as part of solving [Unable to add gif as picture to image widgets  #4819](https://github.com/getodk/collect/issues/4819), but it seems like it's hard to get a dependable automated test for the issue working. @getodk/testers could we add a manual regression for that issue please?

Hi @seadowg are you sure that #4819 was fixed? We are able to reproduce it both on master and this PR right now.

**Comment by grzesiek2010** [comment]
> Hi @seadowg are you sure that https://github.com/getodk/collect/issues/4819 was fixed? We are able to reproduce it both on master and this PR right now.

Callum has just removed the test that verified adding gifs. He didn't change anything around so if there is something wrong on both the master branch and this pr please file a separate issue.

**Comment by grzesiek2010** [comment]
@srujner @dbemke I've noticed a bug in this pr (if the front camera was not available then still our CameraX implementation was used instead of the default camera app). It's fixed, please pull the newest changes.

**Comment by dbemke** [comment]
I've checked on the emulator camera settings: front set to webcam, back set to webcam and front set to none, back set to webcam. The selfie widget works as expected but in selfie video widget with both settings there is a crash.
 I've also noticed that I'm not able to record a video in video widget but this is also present on the master version - should I file an issue for the video widget used on the emulator?

**Comment by srujner** [comment]
> > Hi @seadowg are you sure that #4819 was fixed? We are able to reproduce it both on master and this PR right now.
> 
> Callum has just removed the test that verified adding gifs. He didn't change anything around so if there is something wrong on both the master branch and this pr please file a separate issue.

Separate issue for gif:
https://github.com/getodk/collect/issues/5435

**Comment by grzesiek2010** [comment]
> The selfie widget works as expected but in selfie video widget with both settings there is a crash

so probably it happens on master too?

**Comment by dbemke** [comment]
Selfie video widget on master (with front camera set to webcam or none) the camera is not available
masterselfievideo
In the previous commit to the PR selfie video widget camera (with front camera set to webcam or none) opened and was able to record videos,

File: collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java [hunk 3]
```diff
@@ -141,7 +142,7 @@ private void hideButtonsIfNeeded(String appearance) {
 
     private void captureImage() {
         errorTextView.setVisibility(View.GONE);
-        if (selfie) {
+        if (selfie && new CameraUtils().isFrontCameraAvailable(getContext())) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:145]: I'm confused. You shouldn't need to do this because of the changes made in https://github.com/getodk/collect/pull/5344/commits/6bd11f65062b82184fc8b7c0ae23ed7c3bc59116 right?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:145]: Ah wait, I see: you're just using the default camera app rather than my solution of falling back to the back camera in our custom implementation. That's much better. Maybe we should just revert the `CameraXCamera` changes in https://github.com/getodk/collect/commit/6bd11f65062b82184fc8b7c0ae23ed7c3bc59116?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:145]: Why revert? If you do that then we will be blocked if the front camera is not available again. My change just complements yours. You removed blocking starting the camera when the front one is not present but there is `selfie` appearance and I improved that by using the default camera app instead of our implementation of CameraX.

**Comment by grzesiek2010** [comment]
@dbemke I can't reproduce those problems with the selfie video widget. Please pull the newest changes and try again.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:145]: Sorry I don't think I was clear. I just meant removing the code [here](https://github.com/getodk/collect/blob/6bd11f65062b82184fc8b7c0ae23ed7c3bc59116/selfie-camera/src/main/java/org/odk/collect/selfiecamera/CameraXCamera.kt#L43) that falls back to the back camera if there's no front facing camera when we're using our custom implementation. As far as I can tell, we'll never be in that situation now that we use the device's camera app if there's no front camera.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java:145]: Ah ok I see. Yes we can remove it what I've just done.

**Comment by grzesiek2010** [comment]
Ok, I was finally able to reproduce that problem with recording videos.
1. There is no difference between this pr and the master branch.
2. The problem might very well be a problem that happens only on emulators when the front camera is disabled.
3. We don't see any crashlytics reports like that so it's probably not a real problem

Taking all of that into account I think we can ignore that problem and finish testing.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on emulated Pixel 3a (Android 12), Pixel 4 (Android 13)

**Verified Cases:**
- selfie image works as expected as mentioned in the issue #5374 
- setting the front camera to none and checking selfie image and selfie video widgets
- quick checks of image and media widgets on physical devices with both cameras available

**Comment by srujner** [comment]
**Tested with Success!**

Verified on emulated Pixel 5a (Android 11), Nexus (Android 13)

**Review by seadowg — APPROVED** [review]
