### PR TITLE
Load select choices off the UI thread

### LINKED ISSUE #5229: Show loading state when calculating select choices
Like for form saves (#5162), we want to show a loading state in form entry while select choices are loading/calculated. We should show the same loading state as form saves (which uses the `TransparentProgressScreen` in the `form_entry.xml` layout) and should be shown while the choices are loaded.

This loading state should be visible for any kind of widget that needs to load choices. This means anything that calls `FormEntryPrompt#getSelectChoices` or loads choices using "fast external itemsets" or "pull data".

An example of the problems caused here would be [this ANR](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/17ef3e50444d4e36d4959333e3edec7b?time=last-seven-days&sessionEventKey=6541FF6101E50001252171458C8A1D19_1874840294361923375).

## Notes

One possible approach for this is to create a `getChoices` method on `FormEntryViewModel` that returns choices as a reactive value (like `LiveData`). This would allow easy integration of `FormEntryViewModel#isLoading`. This might mean loading choices outside the widget as using `LiveData` would require access to lifecycle at the call site of the `getChoices` method.

### LINKED ISSUE #5263: Allow logging to audit log from background threads
Currently, using `AuditEventLogger` to log events from a background thread is dangerous as it could cause a `ConcurrentModificationException` due to the underlying `ArrayList` that events are stored in. After #5259, logging from a background thread will be protected by restricting logging to the UI thread (similar to how IO explodes when it runs on the UI thread in Android).

We might want to look at making our audit logging "thread safe" to prevent these kinds of problems. By that I mean:

1. Events end up in the log in the order that `AuditEventLogger#logEvent/flush` is called
2. Events added by `AuditEventLogger#logEvent/flush` always end up in the log (none are dropped/lost)

Additionally, we want to avoid the UI thread having to wait for another `AuditEventLogger#logEvent/finalize` call to complete.

As I'm writing this out, it does strike me that we may not actually want to ever call `AuditEventLogger#logEvent/flush` from a background thread: even if condition **1** is true, if we're calling from a background thread we will lose control of the order in which `logEvent/finalize` is called. We might simply be passing the concurrency problem up the call stack by doing this. If that's the case, it might be worth keeping the UI thread check we have and potentially just adding async writes so that we don't block the UI thread when logging/flushing like we do now.

Either way, this would be good to discuss!

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5229
Closes #5263

This makes changes to how we load select choices so that some screen's won't have select choices loaded on the UI thread. This does not include field list screens as choice lists on those screens can change based on answers on the same screen - recalculating these lists asynchronously requires larger (and more fundamental) changes to form entry so we're punting on it for the moment (https://github.com/getodk/collect/issues/5841).

I had to make changes to audit logging for this to work which eventually meant doing some audit logging off the UI thread (solving #5263). I'd hope we can expand on this in the future, as audit logging can (and often) involves file IO and is not something we should be blocking the UI thread with.

#### Why is this the best possible solution? Were any other approaches considered?

I did experiment with going down a an alternative path which got us closer to something not unlike "unidirectional data flow" where we'd refresh the screen (asynchronously) on any widget change. This would allow us to safely preload choice lists for field list questions, but sadly still involved a lot more work to get everything working performantly. I have some hopes that that is a path we can go down soon, but that can wait until #5841.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Nothing should have changed obviously from a user perspective although forms with slower choice lists should now show a loading screen for longer rather than appearing to "freeze" (or crash). It's worth testing forms with normal selects as well as `select_one_external` and `search` selects on both single question screens and field lists though to check that none of the changes I've made introduce any problems.

There's also some risk to the audit log as a few log calls have been moved around. It would be good to check forms with the log enabled.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@lognaturel and I discussed this and decided that the cases we want to fix here are:
- The ANR example when logging the current screen
- Possible ANRs (and the stutter) when moving back or forwards in the form

We won't look at fixing potential ANRs/stutters that could happen when loading selects in a field list as it looks like the requires a larger rework of how Collect renders question pages that would look more like the "unidirectional data flow" models used by React/Redux apps. That's something we'll hopefully be able to evolve over the next few releases. I'll pull out a separate issue.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 1]
```diff
@@ -284,9 +306,50 @@ protected void onCleared() {
...
+                    preloadSelectChoices();
+                }
+            } catch (RepeatsInFieldListException | XPathSyntaxException |
+                     FileNotFoundException e) {
+                // Ignored
+            }
+
+            AuditUtils.logCurrentScreen(formController, formController.getAuditEventLogger(), clock.get());
+
+            if (Looper.getMainLooper().getThread() == Thread.currentThread()) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Do you need this if check? Can't you always use `postValue`?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 2]
```diff
@@ -275,7 +290,14 @@ public void answerQuestion(FormIndex index, IAnswerData answer) {
     @NonNull
     @Override
     public List<SelectChoice> loadSelectChoices(@NonNull FormEntryPrompt prompt) throws FileNotFoundException, XPathSyntaxException, ExternalDataException {
-        return SelectChoiceUtils.loadSelectChoices(prompt, formController);
+        List<SelectChoice> selectChoices = choices.get(prompt.getIndex());
+
+        if (selectChoices != null) {
+            return selectChoices;
+        } else {
+            // Not all select choices are loaded preemptively yet
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: What does `all` mean in this case? it sounds like it's possible that some choices are loaded but not all... I believe it's not possible right?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 3]
```diff
@@ -305,18 +367,29 @@ public void validate() {
...
                     validationResult.setValue(new Consumable<>(result));
                 }
         );
     }
 
+    private void preloadSelectChoices() throws RepeatsInFieldListException, FileNotFoundException, XPathSyntaxException {
+        int event = formController.getEvent();
+        if (event == FormEntryController.EVENT_QUESTION) {
+            FormEntryPrompt[] prompts = formController.getQuestionPrompts();
+            for (FormEntryPrompt prompt : prompts) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: If this method is used only for a single question it's confusing that you call `getQuestionPrompts` and then loop through the list. In fact, the list will always contain one element o can't you call `getQuestionPrompt` instead?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 4]
```diff
@@ -305,18 +367,29 @@ public void validate() {
...
                     }
+
+                    return result;
+                }, result -> {
                     validationResult.setValue(new Consumable<>(result));
                 }
         );
     }
 
+    private void preloadSelectChoices() throws RepeatsInFieldListException, FileNotFoundException, XPathSyntaxException {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:380]: Do we need this method at all? Can't you use `loadSelectChoices` instead and there populate the `choices` list?

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 5]
```diff
@@ -1239,7 +1216,27 @@ private ODKView createODKView(boolean advancingPage, FormEntryPrompt[] prompts,
                 odkViewLifecycle
         );
 
-        return new ODKView(this, prompts, groups, advancingPage, formSaveViewModel, waitingForDataRegistry, viewModelAudioPlayer, audioRecorder, formEntryViewModel, internalRecordingRequester, externalAppRecordingRequester, audioHelperFactory.create(this));
+        ODKView view = new ODKView(this, prompts, groups, advancingPage, formSaveViewModel, waitingForDataRegistry, viewModelAudioPlayer, audioRecorder, formEntryViewModel, internalRecordingRequester, externalAppRecordingRequester, audioHelperFactory.create(this));
+
+        formEntryViewModel.getValidationResult().observe(this, consumable -> {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: What's the purpose of this change? Instead of calling this once in `onCreate`, this will now be called every time we display a new question.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 6]
```diff
@@ -182,45 +200,42 @@ public void moveForward(HashMap<FormIndex, IAnswerData> answers) {
...
                 }
 
-                formController.getAuditEventLogger().flush(); // Close events waiting for an end time
-                refresh();
+                updateIndex();
             }
+
+            return null;
+        }, ignored -> {
+            formController.getAuditEventLogger().flush(); // Close events waiting for an end time
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Before, it was called only if the result was `success` and now we don't check it (we still do in `moveForward` but not here). Is this an intended change?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 7]
```diff
@@ -125,42 +137,48 @@ public void addRepeat() {
...
-                error.setValue(new FormError.NonFatal(exception.getCause().getMessage()));
+        worker.immediate((Supplier<Void>) () -> {
+            if (jumpBackIndex != null) {
+                formController.jumpToIndex(jumpBackIndex);
+                jumpBackIndex = null;
+            } else {
+                try {
+                    this.formController.stepToNextScreenEvent();
+                } catch (JavaRosaException exception) {
+                    error.setValue(new FormError.NonFatal(exception.getCause().getMessage()));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Shouldn't this be `postValue` if it's called in the background?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 8]
```diff
@@ -182,45 +200,42 @@ public void moveForward(HashMap<FormIndex, IAnswerData> answers) {
...
-        }, updateSuccess -> {
-            isLoading.setValue(false);
-
+        worker.immediate((Supplier<Void>) () -> {
+            boolean updateSuccess = saveScreenAnswersToFormController(answers, false);
             if (updateSuccess) {
                 try {
                     formController.stepToPreviousScreenEvent();
                 } catch (JavaRosaException e) {
                     error.setValue(new FormError.NonFatal(e.getCause().getMessage()));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Shouldn't this be `postValue` if it's called in the background?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 9]
```diff
@@ -284,9 +306,50 @@ protected void onCleared() {
...
+    private void updateIndex() {
+        choices.clear();
+
         if (formController != null) {
-            currentIndex.setValue(formController.getFormIndex());
+            if (formController.getEvent() == FormEntryController.EVENT_BEGINNING_OF_FORM) {
+                try {
+                    formController.stepToNextScreenEvent();
+                } catch (JavaRosaException e) {
+                    error.setValue(new FormError.NonFatal(e.getCause() != null ? e.getCause().getMessage() : e.getMessage()));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Below you check if it's the main thread or not so why not here too?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 10]
```diff
@@ -125,42 +137,48 @@ public void addRepeat() {
...
+        worker.immediate((Supplier<Void>) () -> {
+            jumpBackIndex = null;
 
-        if (!formController.indexIsInFieldList()) {
             try {
-                formController.stepToNextScreenEvent();
-            } catch (JavaRosaException e) {
+                formController.newRepeat();
+            } catch (RuntimeException e) {
                 error.setValue(new FormError.NonFatal(e.getCause() != null ? e.getCause().getMessage() : e.getMessage()));
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Shouldn't this be `postValue` if it's called in the background?

File: collect_app/src/main/java/org/odk/collect/android/async/ViewModelWorker.kt [hunk 11]
```diff
@@ -0,0 +1,21 @@
+package org.odk.collect.android.async
+
+import org.odk.collect.androidshared.livedata.MutableNonNullLiveData
+import org.odk.collect.androidshared.livedata.NonNullLiveData
+import org.odk.collect.async.Scheduler
+import java.util.function.Consumer
+import java.util.function.Supplier
+
+class ViewModelWorker(private val scheduler: Scheduler) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/async/ViewModelWorker.kt]: You came up with this idea to use it in a view model but generally, it's not something only for viewmodels? Maybe we should change its name to something more general and move to the `androidshared` module?

File: test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt [hunk 12]
```diff
@@ -72,15 +77,16 @@ class FakeScheduler : Scheduler {
...
-            backgroundTasks.removeFirst()
+        while (backgroundTasks.isNotEmpty()) {
+            backgroundTasks.remove().run()
         }
     }
 
     fun flush() {
-        runBackground()
-        runForeground()
+        while (backgroundTasks.isNotEmpty() || foregroundTasks.isNotEmpty()) {
```
Comment (grzesiek2010) [inline test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt:86]: Does it make sense to use `while` here? If you call `runBackground` it already uses `while` to run all tasks and the same with `runForeground`. So I believe this `while` has only one loop right?

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java [hunk 13]
```diff
@@ -284,9 +306,50 @@ protected void onCleared() {
...
+                */
+                if (!formController.indexIsInFieldList()) {
+                    preloadSelectChoices();
+                }
+            } catch (RepeatsInFieldListException | XPathSyntaxException |
+                     FileNotFoundException e) {
+                // Ignored
+            }
+
+            AuditUtils.logCurrentScreen(formController, formController.getAuditEventLogger(), clock.get());
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:349]: Isn't this called more often now as it has been moved here (compared to `createView` where it was placed before)? what can cause some problems.

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java [hunk 14]
```diff
@@ -158,93 +151,6 @@ public void whenFormSaverFinishes_saved_setsSaveResultState_toSaved() {
         assertThat(saveResult.getValue().getState(), equalTo(SAVED));
     }
 
-    @Test
-    public void whenFormSaverFinishes_saved_andFormIsCurrentlyOnQuestion_logsSaveAndQuestionAuditEventsAfterFlush() throws RepeatsInFieldListException {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:162]: Don't we need all those tests anymore?

File: collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FakeFormController.java [hunk 15]
```diff
@@ -0,0 +1,197 @@
...
+import org.odk.collect.android.exception.JavaRosaException;
+import org.odk.collect.android.formentry.audit.AuditEventLogger;
+import org.odk.collect.android.utilities.StubFormController;
+
+import java.util.HashMap;
+import java.util.LinkedList;
+import java.util.List;
+import java.util.Map;
+
+public class FakeFormController extends StubFormController {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FakeFormController.java:21]: Kotlin? :smile:

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 1 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: Apparently we can! I'd initially run into problems with that (failing tests in `SavePointTest`) and needed to use `setValue` for the `refreshSync` calls, but I must have accidentally fixed it - no tests fail when I switch to always using `postValue` now.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java]: I mean "choices from all kinds of questions" really. I'll update the comment.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:380]: `preloadSelectChoices` loads the choices into the `choices` "cache" so that they don't need to be loaded again (and are only ever loaded off the UI thread).

File: test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt (hunk 12 above)
Comment (seadowg) [reply test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt:86]: It's to account for background tasks scheduling foreground ones and vice versa. We could run all the background and then foreground tasks and end up with another background task to run for instance.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 13 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:349]: I think it should be the same as `createView` was called whenever the index was updated right? There might be a slight difference but all our current audit log tests are passing. I've added a note to the PR description to make sure QA know to investigate audit log forms.

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java (hunk 14 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:162]: They're covered by the new tests in `AuditLogTest`

File: collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FakeFormController.java (hunk 15 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FakeFormController.java:21]: I gave it a quick go, but there's a bunch of nullable code that needs to be revised. Let's hold that for now given the scale of other changes here?

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java (hunk 14 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:162]: Where? I can't find any class like that.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:380]: > preloadSelectChoices loads the choices into the choices "cache"

Yes, my idea was that this could happen in `loadSelectChoices` so that we don't need that `preloadSelectChoices` which calls `loadSelectChoices`. Something like: https://github.com/getodk/collect/commit/f372fda8b6a3f40e22585e5caca41bc6ef6f342f

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
Some additional comments

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:380]: Ah I see. Hmmm, I'm not sure which one I prefer. I like that that your version isolates the use of the `choices` map (and also reduces total lines of code), but it does feel like we end up with less "command/query separation" - the "preload" is far less explicit now and calling `loadSelectChoices` and not using the result looks a little weird to me. Do you have a strong preference for the one method?

File: collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java (hunk 14 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java:162]: Sorry it's just `AuditTest`: https://github.com/getodk/collect/blob/master/collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java:380]: > Do you have a strong preference for the one method?

No, it's not a strong preference so let's keep it as it is if you are not sure.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
I noticed that choosing an answer and swiping to the next question in Kobo test form (with a csv attachment) got slower. I compared the same form on the store version (going to the next question was a bit quicker) to the master version ee016ccddd023ed4ed3d825d83c642011e6e85c7. On the master version even on Android 13 after choosing an answer and swiping to the next question the screen is a bit grayed out and there's a progress bar so going to the next question seems slower.
form: 
[Kobo_Test(1).xlsx.txt](https://github.com/getodk/collect/files/13861772/Kobo_Test.1.xlsx.txt)
[places.csv.txt](https://github.com/getodk/collect/files/13861779/places.csv.txt)

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:
- Works toward issues #5229 and #5263;
- Big forms;
- Regression check on Audit logs;
- Regression check on forms with Select and Select_one_external
- Forms with search;
- Rotate the screen, minimize the app;
- Don't keep activities enabled/disabled.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10
