### PR TITLE
Fail encrypted form finalization if form does not specify instanceID

### LINKED ISSUE #3264: Don't finalize encrypted form if definition has no instanceID and show explanation to user
#### Software and hardware versions 
Collect v1.23.0 and prior

#### Problem description
When a form definition does not include an instanceID, it can't be encrypted because an instanceID is necessary to identify the record in the submission manifest. Currently, encryption just silently fails and the submission is still saved as finalized. A user may not realize that their data is not encrypted and could reveal sensitive information.

This was discovered when implementing encryption in Central.

#### Steps to reproduce the problem
1. Load a form with an encryption key but no instanceID such as [Birds-encrypted.xml.txt](https://github.com/opendatakit/collect/files/3449217/Birds-encrypted.xml.txt)
1. Fill out the form
1. Save as finalized
1. Edit saved form -- if it were encrypted, it should not be possible to edit.

#### Expected behavior
When the user attempts to save as finalized, a toast is displayed saying "This form does not specify an instanceID. You must specify one to enable encryption." The form is not saved as finalized.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3264

Note: this is an unlikely case because all known form builders add an `instanceID`. That's why the error message is not translated. I did move it to the top, though, since it feels like an invariant.

I changed logging from `e` to `d` where the error is caused by the form or device configuration since there's nothing that ODK developers can do about those -- they're not software defects.

#### What has been done to verify that this works as intended?
Filled form from issue, verified that finalization is disabled and that a toast is shown.

#### Why is this the best possible solution? Were any other approaches considered?
This uses the existing infrastructure to stop finalization and present an error to the user. I considered keeping the Timber log but it's not a software error so there's no point in logging it to Crashlytics.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The user will be unable to finalize forms with encryption keys and no instanceIDs. No regression risk that I can think of.

#### Do we need any specific form for testing your changes? If so, please attach one.
[Birds-encrypted.xml.txt](https://github.com/opendatakit/collect/files/3449331/Birds-encrypted.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java [hunk 1]
```diff
@@ -355,8 +356,7 @@ public static EncryptedFormInformation getEncryptedFormInformation(Uri uri,
         // submission must have an OpenRosa metadata block with a non-null
         // instanceID value.
         if (instanceMetadata.instanceId == null) {
-            Timber.e("No OpenRosa metadata block or no instanceId defined in that block");
-            return null;
+            throw new EncryptionException("This form does not specify an instanceID. You must specify one to enable encryption.", null);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java]: I think we should probably have that string in `string.xml`

**Review by seadowg — CHANGES_REQUESTED** [review]
I think it'd be good to have test of at least `getEncryptedFormInformation` to drive out this case. Eventually it would be nice to have some coverage of the infrastructure that results in the `Toast` being shown but given we've chatted about moving the Task tests I don't think right now is a good time for that particular backfill.

File: collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java]: Putting strings in `string.xml` is not "free" in the sense that it adds more work for translators. I think that for edge cases like this one, it's preferable to avoid having it translated. This is extremely unlikely since pyxform and Build add instanceID. It's really only likely when someone comes across a really old form definition (generally used for testing).

I've added 557a826 to explain the exception and hopefully you find it reasonable.

**Comment by lognaturel** [comment]
@seadowg I hope that you will find my test sufficient. It's not ambitious but this is mostly for developers who have old test forms lying around so I don't want to spend too much time here.

**Review by seadowg — APPROVED** [review]
I like it! Simple.

**Comment by bognasoldev89** [comment]
*Tested with success*

Verified on Android: 
4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0

Verified cases:
- Filling, saving and finalizing attached form

On all of the Androids user is not able to finalize encrypted form if definitions has no instanceID. Form is saved and visible in Edit Saved Form. Toast is displayed after marking form as finalized, saying “This form does not specify an instanceID. You must specify one to enable encryption. Form has not been saved as finalized.”

Screenshot_2019-09-13-12-35-29


@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
