### PR TITLE
Fix crashes editing geopoly questions

### LINKED ISSUE #7002: No background processes in geoshape and geotrace
#### ODK Collect version
the master version cba0e5aca791438d0a8813c89f414db94f579910, also #6998
(the issue doesn’t occur in the store version 2025.3.3)
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
When no background processes is set in the device switching to a different app while adding a geotrace or a geoshape removes the trace/shape. If there was an already saved trace/shape and the user opens the map again, switching to a different app crashes Collect after trying to reopen the map.
After the crash it's impossible to use a geoshape or a geotrace again - it crashes again.

#### Steps to reproduce the problem
1. Download All question types form.
2. Set no background processes in the device.
3. Open the map in geotrace or geoshape and add some points.
4. Minimize the app and go to a different app and back to Collect.
5. From the hierarchy view go to the question and open the map (there isn't the trace/shape).
6. Add a trace/shape and save it.
7. Open the map again and e.g. move one point.
8. Minimize the app and go to a different app and back to Collect.
9. From the hierarchy view go to the question and open the map (there's a crash).
10. Try to recover the savepoint and open a geotrace/shape map (there's a crash). 

Image

### LINKED ISSUE #7003: Impossible to open the map view in a geoshape/trace in a draft if there's a saved tace/shape - crash.
#### ODK Collect version
the master version cba0e5aca791438d0a8813c89f414db94f579910, also #6998
(the issue doesn’t occur in the store version 2025.3.3)
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's a crash after tapping "View or change line/polygon" in a draft - it isn't possible to open the map view in a geoshape/trace in a draft if there's a saved tace/shape.
Image

#### Steps to reproduce the problem
1. Download All question types form,
2. Save a geoshape or a geotrace and save the form as draft (the way you save the draft doesn't matter).
3. Go to "Drafts" and open the form.
4. Go to the saved shape/trace and open the map.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7002
Closes #7003
~~Blocked by https://github.com/getodk/javarosa/pull/840~~

#### Why is this the best possible solution? Were any other approaches considered?

The cause of the crashes was just that the underlying types being used for geoshape/trace answers was inconsistent: sometimes it was a string (`StringData`) and sometimes it was geo data (`GeoShapeData`/`GeoTraceData`). I could have updated the code to treat everything as strings, but instead I chose to use the geo specific data types throughout.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issues! Nothing is affected other than the geoshape/trace questions.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 1]
```diff
@@ -20,35 +21,39 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
...
-
         val retainMockAccuracy =
             FormEntryPromptUtils.getBindAttribute(prompt, ALLOW_MOCK_ACCURACY).toBoolean()
 
-        val answer = prompt.answerValue
-        val inputPolygon = GeoPolyUtils.parseGeometry(answer?.value as String?)
+        val inputPolygon = when (val answer = prompt.answerValue) {
+            is GeoTraceData -> answer.points.map { it.toMapPoint() }
+            is GeoShapeData -> answer.points.map { it.toMapPoint() }
+            null -> emptyList()
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:55]: Why do we need this?

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 2]
```diff
@@ -20,35 +21,39 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
...
-        val outputMode = when (prompt.dataType) {
-            Constants.DATATYPE_GEOSHAPE -> OutputMode.GEOSHAPE
-            else -> OutputMode.GEOTRACE
-        }
-
         val retainMockAccuracy =
             FormEntryPromptUtils.getBindAttribute(prompt, ALLOW_MOCK_ACCURACY).toBoolean()
 
-        val answer = prompt.answerValue
-        val inputPolygon = GeoPolyUtils.parseGeometry(answer?.value as String?)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:51]: Don't we need to use `GeoPolyUtils.parseGeometry` anymore?

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java [hunk 3]
```diff
@@ -296,8 +298,9 @@ private Pair<String, String> extractGeometryContentValues(FormInstance instance,
     private JSONObject toGeoJson(GeoPointData data) throws JSONException {
         // For a GeoPointData object, the four fields exposed by getPart() are
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java]: I think we can remove this comment now.

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 4]
```diff
@@ -20,35 +21,39 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
     ) {
 
     override fun onCreateFragment(prompt: FormEntryPrompt): GeoPolyFragment {
+        val incremental = FormEntryPromptUtils.getAdditionalAttribute(prompt, INCREMENTAL)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt]: This is needed only if `geopolyChange != null` so we can move it there.

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 5]
```diff
@@ -20,35 +21,39 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
...
+        val outputMode = when (prompt.dataType) {
+            Constants.DATATYPE_GEOSHAPE -> OutputMode.GEOSHAPE
+            else -> OutputMode.GEOTRACE
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt]: To be consistent with what we do building `inputPolygon` below I think here we should explicitly check for `DATATYPE_GEOTRACE` and add in the else branch throw an exception.

File: collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt [hunk 6]
```diff
@@ -163,7 +164,7 @@ class GeoPolyDialogFragmentTest {
     }
 
     @Test
-    fun `configures GeoPolyFragment inputPolgyon with existing answer`() {
+    fun `configures GeoPolyFragment inputPolygon with existing answer`() {
         prompt = MockFormEntryPromptBuilder(prompt)
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt:173]: You don’t need this, because you’re not setting anything beyond what’s already done when the object is declared above. The same in other tests.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt (hunk 1 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:55]: Because the answer might be `null` and in that case we just pass through an empty list.

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:51]: It wouldn't make sense because `answer` now expected to be `GeoTraceData` or `GeoShapeData`. Is there a scenario you're thinking of where we still need to use it?

File: collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt (hunk 6 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt:173]: I don't follow. Could you elaborate?

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt:173]: Here, you’re just recreating this prompt without adding any additional parameters. It’s already handled at the top level, where it’s declared and defined.

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt:173]: Ah sorry I see! The git diff highlighting mad me think the comment was on the line above. Agreed, but that's no longer true after https://github.com/getodk/collect/pull/7006/changes/290556a9fe3737aad806c28268cacc200ce85653.

File: collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt [hunk 7]
```diff
@@ -174,24 +181,34 @@ class GeoPolyDialogFragmentTest {
...
         ) {
-            assertThat(
-                it.inputPolygon,
-                equalTo(listOf(MapPoint(0.0, 0.0, 1.0, 1.0), MapPoint(0.0, 1.0, 1.0, 1.0)))
-            )
+            assertThat(it.inputPolygon, equalTo(points))
+        }
+
+        prompt = MockFormEntryPromptBuilder(prompt)
+            .withAnswer(geoShapeOf(points))
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt:199]: Here the data type should be changed to `DATATYPE_GEOSHAPE`

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:51]: > Is there a scenario you're thinking of where we still need to use it?

No I was just wondering.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified cases:**
- issues #7003, #7003 don't occur
- saving and opening question with geometry
- quick regression check in select one from map
- filed issue #7012

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16
