### PR TITLE
Removed auto-populating phone numbers

### LINKED ISSUE #5482: The device's phone number can't be read
#### Problem description
The device's phone number can't be read. If we set the phone number in settings on our own it works well.

#### Steps to reproduce the problem
1. Install a fresh version of ODK Collect
2. Go to Settings -> User and device identity -> Form metadata
3. Phone number should be displayed but we have `Not available` instead.

1. Open the attached form: 
[metadata.xlsx](https://github.com/getodk/collect/files/10935126/metadata.xlsx)
2. Phone number should be displayed in `phonenumber` question.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5482 

#### What has been done to verify that this works as intended?
I've added automated tests and tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
Please test metadata using the form attached to the issue. There was a lot of refactoring there so everything related to it might have been affected.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I've implemented a lot of refactoring so please test all [metadata](https://docs.getodk.org/form-question-types/#metadata) questions. Please also read the automated test because it might be helpful.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Yes https://github.com/getodk/docs/pull/1596

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataSettingsTest.kt [hunk 1]
```diff
@@ -40,30 +40,67 @@ class FormMetadataSettingsTest {
         .around(rule)
 
     @Test
-    fun settingMetadata_letsThemBeIncludedInAForm() {
+    fun metadataShouldBeDisplayedInPreferences() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataSettingsTest.kt:39]: @grzesiek2010 it looks to me like this test fails if I add it on `master`. I'm guessing that's expected (as it looks like it verifies the original problem), but just wanted to check?

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataSettingsTest.kt:39]: Yes you are right.

File: metadata/src/main/java/org/odk/collect/metadata/InstallIDProvider.kt [hunk 2]
```diff
@@ -0,0 +1,29 @@
+package org.odk.collect.metadata
+
+import org.odk.collect.shared.settings.Settings
+import org.odk.collect.shared.strings.RandomString
+
+interface InstallIDProvider {
+    val installID: String
+}
+
+class CollectInstallIDProvider(
```
Comment (seadowg) [inline metadata/src/main/java/org/odk/collect/metadata/InstallIDProvider.kt]: Could this be called `SettingsInstallIDProvider` instead?

File: metadata/build.gradle.kts [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    implementation(project(":settings"))
+    implementation(project(":shared"))
+
+    implementation(Dependencies.javarosa) {
+        exclude(group = "joda-time")
+        exclude(group = "org.hamcrest", module = "hamcrest-all")
+    }
+    implementation(Dependencies.timber)
+
+    testImplementation(Dependencies.androidx_test_ext_junit)
```
Comment (seadowg) [inline metadata/build.gradle.kts]: I think you can replace with `junit` and `hamcrest`.

File: metadata/src/main/java/org/odk/collect/metadata/PropertyManager.kt [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+
+    override fun getSingularProperty(propertyName: String): String {
+        if (propertyName.equals(PROPMGR_PHONE_NUMBER, ignoreCase = true) && !permissionsProvider.isReadPhoneStatePermissionGranted) {
+            isPhoneStateRequired = true
+        }
+
+        return properties[propertyName.lowercase()] ?: ""
+    }
+
+    override fun getProperty(propertyName: String): List<String> = emptyList()
```
Comment (seadowg) [inline metadata/src/main/java/org/odk/collect/metadata/PropertyManager.kt:49]: It looks like this returned `null` in the Java implementation

File: metadata/src/test/java/org/odk/collect/metadata/PropertyManagerTest.kt [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    }
+
+    @Test
+    fun `getSingularProperty should return empty string for undefined properties`() {
+        assertThat(propertyManager.getSingularProperty("blah"), equalTo(""))
+    }
+
+    @Test
+    fun `getSingularProperty should require phone state permission for phone number property only`() {
+        propertyManager.reload()
```
Comment (seadowg) [inline metadata/src/test/java/org/odk/collect/metadata/PropertyManagerTest.kt]: I don't think this `reload()` is needed?

File: permissions/src/test/java/org/odk/collect/permissions/PermissionsProviderTest.kt [hunk 6]
```diff
@@ -269,22 +272,22 @@ class PermissionsProviderTest {
...
+    fun `isReadPhoneStatePermissionGranted() when read phone numbers permission is not granted returns false`() {
+        whenever(permissionsChecker.isPermissionGranted(Manifest.permission.READ_PHONE_NUMBERS)).thenReturn(false)
 
         assertThat(permissionsProvider.isReadPhoneStatePermissionGranted, `is`(false))
     }
 
     @Test
-    fun `requestReadPhoneStatePermission() when read phone state permission is granted calls PermissionListener#granted`() {
-        permissionsApi.setGrantedPermission(Manifest.permission.READ_PHONE_STATE)
+    fun `requestReadPhoneStatePermission() when read phone numbers permission is granted calls PermissionListener#granted`() {
```
Comment (seadowg) [inline permissions/src/test/java/org/odk/collect/permissions/PermissionsProviderTest.kt]: You can add a test for the lower API levels using `@Config(sdk = x)` here. Probably also best to add `@Config` to these tests so that it's explicit which API level is being used.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: metadata/src/main/java/org/odk/collect/metadata/PropertyManager.kt (hunk 4 above)
Comment (grzesiek2010) [reply metadata/src/main/java/org/odk/collect/metadata/PropertyManager.kt:49]: Right, but this method is unused so it doesn't matter if we return null or an empty list.

File: permissions/src/test/java/org/odk/collect/permissions/PermissionsProviderTest.kt (hunk 6 above)
Comment (grzesiek2010) [reply permissions/src/test/java/org/odk/collect/permissions/PermissionsProviderTest.kt]: I removed the commit with the fix for https://github.com/getodk/collect/issues/4838 and it was a part of that commit.

File: metadata/build.gradle.kts (hunk 3 above)
Comment (grzesiek2010) [reply metadata/build.gradle.kts]: Right, done.

File: metadata/src/test/java/org/odk/collect/metadata/PropertyManagerTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply metadata/src/test/java/org/odk/collect/metadata/PropertyManagerTest.kt]: Right, fixed.

File: metadata/src/main/java/org/odk/collect/metadata/InstallIDProvider.kt (hunk 2 above)
Comment (grzesiek2010) [reply metadata/src/main/java/org/odk/collect/metadata/InstallIDProvider.kt]: Hmm it could and I've added that change but now I'm not sure if I like it maybe `MetaInstallIDProvider` would be better?

Comment (seadowg) [reply metadata/src/main/java/org/odk/collect/metadata/InstallIDProvider.kt]: I guess this class doesn't really care that it's "meta" `Settings`. That's just what Collect passes it, but I could see it either way (the field mentions "meta"). Happy for you to choose here.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
I checked it on Android 10, 11, 13 (with a sim card) and in settings(user and device identity) and metadata form the phone number isn't visible.

**Comment by grzesiek2010** [comment]
Wow, I've tested it on emulators so everything was fine but I can confirm it's not always the case with real devices. One problem is that on newer devices an exception might be thrown which I could handle with the fix we already have in https://github.com/getodk/collect/pull/5483.
But even if I do that an empty string is returned instead of the number I want. I've tried the current implementation with `TelephonyManager`, and also another one with `SubscriptionManager` and it's the same.
Browsing StackOverflow I see that people claim there is no one perfect and reliable solution to read a phone number.
Taking that into account and the fact that it has been broken for more than 2 years and no one has complained, maybe we should remove that at all and just let users enter their numbers manually? @lognaturel @seadowg what do you think?

**Comment by seadowg** [comment]
I'm going to move the issue over to v2023.2 and make this PR a draft. We can move the discussion over to the issue.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
If the user fills the user-defined metadata values in settings and later on removes them, the values are still present in the metadata form opened after removing the values. If the user kills the app, the values won’t be visible in the metadata form any more.
The issue is not present on the master version.

**Steps to reproduce:**
1. Go to settings→ user and device identity→ form metadata.
2. Fill the username, phone number, email address
3. Remove the filled values so that they are "Not set”.
4. Go to the metadata form and check if the user data is not set.
[Metadata new.xlsx.txt](https://github.com/getodk/collect/files/11178623/Metadata.new.xlsx.txt)

**Comment by grzesiek2010** [comment]
Good catch. The issue has been fixed.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 8.1, 10

Verified cases:
- issue #5482
- checking metadata in an xml file of a saved form
- checking metadata displayed in a fieldlist in the metadata form
- adding/ removing user-defined form metadata
- setting a username in server settings and form metadata settings
- validating an email address
- background location in a form with metadata
- regression checks in User and Device identity
- dial number form

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 12 and 13

**Comment by srujner** [comment]
Read phone state permission appeared again.
The issue is present on device with Android 13 also on the Master version

**Steps to reproduce:**

1. Install ODK application;
2. Open ODK app;
3. Go to the metadata form;
    [Metadata new.xlsx.txt](https://github.com/getodk/collect/files/11178623/Metadata.new.xlsx.txt)
4. Phone permission will appear.
Screenshot_20230411-170615
5. Click Don't allow.
Screenshot_20230411-170622

**Comment by grzesiek2010** [comment]
This seems impossible, I've checked Android 13... I think it was an installation error and you ended up testing the master branch thinking it's this branch. Please uninstall the app completly and do everything again.

**Comment by srujner** [comment]
Correct, something was wrong with my branch. False alarm ;)

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 8.1, 10

Verified cases:
- issue #5482
- checking metadata in an xml file of a saved form
- checking metadata displayed in a fieldlist in the metadata form
- adding/ removing user-defined form metadata
- setting a username in server settings and form metadata settings
- validating an email address
- background location in a form with metadata
- regression checks in User and Device identity
- dial number form

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 12, 13
