### PR TITLE
Revise notification behaviour for Match Exactly

### LINKED ISSUE #3999: Fill Blank Form can appear multiple times on back stack and auth dialog should be displayed immediately
#### Software and hardware versions 
`master`

#### Problem description
These are two related issues connected to @seadowg's match exactly work.

First, if the user receives a notification related to "match exactly" work happening and taps it, that always adds a new instance of Fill Blank Form on the back stack. However, Fill Blank Form may already be on the back stack. This is particularly noticeable when the user manually triggers a form update because s/he is already in Fill Blank Form and tapping a notification always creates a new instance of it.

Second, if the server requires auth and the user manually triggers a form update from Fill Blank Form, the user will receive a notification and have to tap that notification to get the auth prompt. Since this case is user-recoverable, it would be better if the dialog could immediately be shown to the user rather than s/he having to tap through a notification.

These are likely related because it may be easier to solve the second issue first and not have to deal with the case where Fill Blank Form is displayed without the auth dialog, a update attempt fails with a `401`, and the user needs to tap the notification to get that dialog.

#### Steps to reproduce the problem
1. Turn on match exactly
1. Configure a server that requires auth and don't provide credentials
1. Manually trigger a server update from Fill Blank Form
1. Tap on the notification to get the auth dialog (and note that it would be better if the dialog just appeared)
1. Dismiss the dialog
1. Tap back and notice that you're still in Fill Blank Form

#### Expected behavior
Auth dialog appears in the foreground if match exactly fails with 401 and Fill Blank Form is displayed. Tapping on a match exactly notification uses the existing instance of Fill Blank Form if it exists. There is never more than one instance of Fill Blank Form.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #3999. ~~Blocked by #3992.~~

In addition to the problems described in the issue I also made it so error notifications are cleared/cancelled when a sync succeeds.

#### What has been done to verify that this works as intended?

New/revised tests and was able to verify manually

#### Why is this the best possible solution? Were any other approaches considered?

I've left some comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to just check the issue is fixed and that Match Exactly notifications behave as expected.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java [hunk 1]
```diff
@@ -53,40 +52,14 @@ public void whenMatchExactlyEnabled_clickingFillBlankForm_andClickingRefresh_get
     }
 
     @Test
-    public void whenMatchExactlyEnabled_getsLatestFormsFromServer_automaticallyAndRepeatedly() throws Exception {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java:56]: I decided to revise how the tests are written to drive out the new behaviour rather than just adding more. Along with the changed/new unit tests everything was TDD'd out and I'm pretty sure we didn't lose anything.

File: collect_app/src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -113,7 +113,7 @@ the specific language governing permissions and limitations under the License.
             android:configChanges="orientation|screenSize"
             android:windowSoftInputMode="stateHidden" />
         <activity android:name=".activities.InstanceChooserList" />
-        <activity android:name=".activities.FillBlankFormActivity" />
+        <activity android:name=".activities.FillBlankFormActivity" android:launchMode="singleTop"/>
```
Comment (seadowg) [inline collect_app/src/main/AndroidManifest.xml:116]: Not a fan of changes here but at least it's driven out by a test in Espresso

**Review by lognaturel — APPROVED** [review]
