### PR TITLE
Record first point when starting automatic recording

### LINKED ISSUE #7041: Automatic location recording in geoshape/trace seems slower on some devices
#### ODK Collect version
the master version f02792da6cc5214e909cbfbf0a8a943f090d3bb0
(The issue doesn’t occur in the store version 2025.3.3)
#### Android version
10
#### Device used
Redmi 9T
#### Problem description
I decided to file the issue although I don't know which factor causes it. It seems that on some devices it takes more time to add a point in the automatic location recording in the geoshape and geotrace.
To be able to compare the results we measured the time between starting the automatic location recording (set to 1 second and accuracy set to "none") and adding the first point.
There is no visible difference in most devices but all 3 Android 10 devices got slower. On my Redmi 9t I need to wait about 8 seconds before the first point is added (although accuracy is set to "none"). On other Android 10 devices it takes from 3 seconds to 10 seconds.
I checked Android 8.1 and it seems to work fine.
An interesting thing on my Redmi 9t is that it takes as much time to record the point if the accuracy requirement is set to 20m as set to "none".
In the store version the first point gets added the moment you start recording points.
#### Steps to reproduce the problem
1. Download All question types form.
2. Open the map in a geoshape or geotrace.
3. Wait until the map loads.
4. Set automatic location recording - recording interval 1 sec, accuracy requirement none.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7041
~~Blocked by #7043~~

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

One note: I've avoided adding tests for the fix as I'll plan to follow up with changes to the `LocationTracker` detailed at https://github.com/getodk/collect/pull/7045#discussion_r2720441332 and add tests for the more ideal setup there.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue! Not a large change here - does not need tested with different map engines.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt [hunk 1]
```diff
@@ -339,8 +346,8 @@ class GeoPolyFragment @JvmOverloads constructor(
     override fun startInput() {
         inputActive = true
         if (recordingEnabled && recordingAutomatic) {
+            locationTracker.warm(map!!.getGpsLocation()?.toLocation())
```
Comment (seadowg) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt:349]: I'd initially thought about entirely replacing the use of the `MapFragment` GPS integration with `LocationTracker` in `GeoPolyFragment`. To do that there are a few things we'd need to add to `LocationTracker`:

1. It would need to be pausable to prevent background GPS system usage when not using automatic recording
2. We'd need to be able to speed up/slow down the update interval to adapt to different automatic recording intervals
3. There'd ideally be a smart way to switch between running as a background and foreground service: if the service can be paused, there's no need for it to be running as a foreground service all the time

For the moment, I think adding a way to "warm" the `LocationTracker` and deprecating the `MapFragment` GPS methods (so that it's clear we want to move away from them) gets us parity with the last release without take time away from further invalid polygon work.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10

**Verified cases:**
- issue #7041 doesn't occur

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16
