### PR TITLE
Block deleting saved forms if some of them are being sent

### LINKED ISSUE #5800: Deleting a form that is being sent
#### ODK Collect version
the store version 2023.2.4, v2023.3 Beta 0
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
Probably this option was always available but in the older version it was possible to delete a finalized forms while being sent when e.g. auto send option triggered sending (In case of sending form Ready to send the user needs to wait until sees sending success dialog). After introducing option to bulk finalize it gets easier to delete forms that are being sent. If I do it really quickly in 2023.3 Beta 0 I’m able to delete all forms that were suppossed to be sent (while sending them).
I think it’s an edge case but maybe there’s something possible to introduce for forms that are being sent (or in the queue waiting to be send) so that they cannot be deleted.
I was thinking about a situation in which a user finalizes all drafts (sending is triggered) and goes to Delete forms to remove some forms and by mistake removes the form that was supposed to be send.
#### Steps to reproduce the problem
1. Save as draft a few forms with a big attachment.
2. Go to Drafts and finalize all drafts.
3. While the forms are being sent, go to Delete form (Saved forms), select all and delete selected.

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### Why is this the best possible solution? Were any other approaches considered?
As I said in the issue I've considered adding a new status for forms that are being sent but this would require more changes and would be riskier. `ChangeLock` is something we already use in other places of the app to block accessing databases. 
The difference between using  `ChangeLock` and introducing a new status is that with a new status, we would be able to block deleting particular forms but with  `ChangeLock` we block deleting all existing saved forms but I think that's ok.

I think this pr is enough for now because it protects users from losing data but we should consider some UI improvements to somehow let users know that sending forms is taking place in the background and deleting them is not possible. Maybe we should gray out and disable the list of saved forms (that we can use to delete them), or maybe something else. @alyblenkin COuld you think it through and file a new issue?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Deleting saved forms (all of them) should be blocked when at least one of them is being sent. That means we can't delete them from the `Main menu -> Delete form` or by resetting saved forms in protected settings).
It's possible that we have let's say 10 saved forms but only one of them will be sent automatically because only one has auto-send enabled on a form level. In such a case according to what I said above deleting those other 9 forms should also be blocked. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@grzesiek2010 I think we should include this in v2024.1. It'd be good to prevent any weirdness that might arise from someone deleting a saved form while it's being sent. Go ahead and mark this as ready for review and request a review if you think this is good to go!

File: collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt [hunk 1]
```diff
@@ -65,14 +68,20 @@ class SavedFormListViewModel(
 
     fun deleteForms(databaseIds: LongArray): LiveData<Consumable<Int>?> {
         val result = MutableLiveData<Consumable<Int>?>(null)
-        worker.immediate(
-            background = {
-                databaseIds.forEach { instancesDataService.deleteInstance(it) }
-            },
-            foreground = {
-                result.value = Consumable(databaseIds.count())
+        changeLockProvider.getInstanceLock(projectId).withLock { acquiredLock: Boolean ->
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt]: I feel like this check would make more sense in `InstancesDataService#deleteInstance` (maybe in a modified method that takes a list of IDs rather just one). Then, the other places that delete instances can just call that and we'll only have to handle the check in one place.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt]: Done.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt [hunk 2]
```diff
@@ -127,12 +129,23 @@ class InstancesDataService(
...
+    fun deleteInstances(instanceIds: LongArray): Boolean {
+        return changeLockProvider.getInstanceLock(projectsDataService.getCurrentProject().uuid).withLock { acquiredLock: Boolean ->
+            if (acquiredLock) {
+                instanceIds.forEach { instanceId ->
+                    InstanceDeleter(instancesRepositoryProvider.get(), formsRepositoryProvider.get()).delete(
+                        instanceId
+                    )
 
-        update()
+                    update()
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt]: Why do we need this `update`?

File: collect_app/src/main/java/org/odk/collect/android/utilities/ProjectResetter.kt [hunk 3]
```diff
@@ -62,10 +64,18 @@ class ProjectResetter(
     }
 
     private fun resetInstances() {
-        instancesRepositoryProvider.get().deleteAll()
+        changeLockProvider.getInstanceLock(projectId).withLock { acquiredLock: Boolean ->
+            if (acquiredLock) {
+                instancesRepositoryProvider.get().deleteAll()
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ProjectResetter.kt]: Is there a reason not to use `InstancesDataService` here instead?

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 4]
```diff
@@ -1,80 +1,139 @@
...
+        } else {
+            isFormAutoDeleteOptionEnabled = settingsProvider.getUnprotectedSettings().getBoolean(ProjectKeys.KEY_DELETE_AFTER_SEND);
+        }
+
+        Stream<Instance> instancesToDelete = instanceIds.stream()
+                .map(id -> new InstancesRepositoryProvider(Collect.getInstance()).get().get(Long.parseLong(id)))
+                .filter(instance -> instance.getStatus().equals(Instance.STATUS_SUBMITTED))
+                .filter(instance -> InstanceAutoDeleteChecker.shouldInstanceBeDeleted(formsRepository, isFormAutoDeleteOptionEnabled, instance));
+
+        InstanceDeleter instanceDeleter = new InstanceDeleter(instancesRepository, formsRepository);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java:133]: I'd prefer the `InstancesDataService` here, but I'm guessing we end up in a weird state where we've locked the `ChangeLock` so can't then call `deleteInstances`? If so, I guess down the line we can probably have a `InstancesDataService#submitInstances` that covers submission and the clean up. That will probably make sense once we rework the upload UI.

File: collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt [hunk 5]
```diff
@@ -179,6 +180,26 @@ class SavedFormListViewModelTest {
...
     }
 
+    @Test
+    fun `deleteForms should return 0 if instances can not be deleted`() {
+        val viewModel = SavedFormListViewModel(scheduler, settings, instancesDataService)
+        whenever(instancesDataService.deleteInstances(any())).thenReturn(false)
+
+        val result = viewModel.deleteForms(longArrayOf(1))
+        scheduler.flush()
+        assertThat(result.value!!.value, equalTo(0))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt]: You can use `getOrAwaitValue()` here (and in the other test) instead of needing the `!!`.

**Review by seadowg — CHANGES_REQUESTED** [review]
Just a few tweaks!

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt]: We don't, good catch.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ProjectResetter.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ProjectResetter.kt]: We can do that. Done.

File: collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt]: Yes, I can but still will need `!!` as the value the livedata stores is Consumable and I need to unpack it see: https://github.com/getodk/collect/pull/5929/commits/85a69baa31e1a815cb3a2197c1113798219786bd

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java:133]: > I'd prefer the InstancesDataService here, but I'm guessing we end up in a weird state where we've locked the ChangeLock so can't then call deleteInstances?

Correct.

>If so, I guess down the line we can probably have a InstancesDataService#submitInstances that covers submission and the clean up. That will probably make sense once we rework the upload UI. 

Yeah makes sens we also need to rework the whole task since it's still android AsyncTask. Let's do that in a separate pr.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
@grzesiek2010 @seadowg we tried testing the PR but because of the issue #6017 we're having a hard time verifying what forms and how many forms are really deleted. We would like to wait for that issue to be fixed and then test it together, cause this issue makes a half of our tests unreliable. Would it be ok to wait with testing till the fix for you, too?

**Comment by seadowg** [comment]
@dbemke yeah that's fine!

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- trying to delete a form/ forms while being sent
- forms with big attachments, auto send sent to true and false
- different auto send options
- don't keep activities enabled/ disabled
- deleting saved forms and blank forms
- reported issue https://github.com/getodk/collect/issues/6125

**Comment by srujner** [comment]
**Tested with Success!**

Verified on a device with Android 13

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14
