### PR TITLE
Shorten sheet title if it's too long

### LINKED ISSUE #2918: The sheet name cannot be greater than 100 characters
#### Software and hardware versions 
Collect v1.19.0 and older versions

#### Problem description
The sheet name cannot be greater than 100 characters, what might cause problems if a form contains groups with long names or many nested group.

#### Steps to reproduce the problem
Try to fill and send the attached form:
[sheetTitleTest.xml.txt](https://github.com/opendatakit/collect/files/2905761/sheetTitleTest.xml.txt)
Result:
screenshot_2019-02-26-14-54-14

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2918 

#### What has been done to verify that this works as intended?
I tested the form attached to the issue.

#### Why is this the best possible solution? Were any other approaches considered?
Google just doesn't allow to create sheets with longer names so we need that fix to be able to send data, there is no other solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's not very risky but sending forms to GS should be tested to confirm the problem is solved and there is no regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java [hunk 1]
```diff
@@ -338,20 +338,26 @@ private void createSheetsIfNeeded(TreeElement element) throws UploadException {
...
             }
         }
         return sheetTitles;
     }
 
+    private String shortenSheetTitleIfTooLong(String sheetTitle) {
+        return sheetTitle.length() <= 100
+                ? sheetTitle
+                : "..." + sheetTitle.substring(sheetTitle.length() - 97, sheetTitle.length());
+    }
```
Comment (cooperka) [inline collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java]: Can we make this a more generic TextUtils method that takes a string and a length (e.g. `ellipsizeBeginning`)? This would also be really easy to unit test so I think we should do that.

**Review by cooperka — CHANGES_REQUESTED** [review]
Looks good, just some suggestions to generify it.

**Comment by grzesiek2010** [comment]
@cooperka I improved the solution you can take a look.

**Review by cooperka — APPROVED** [review]
👍

**Comment by cooperka** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Verified new filled submission
Verified a submission which was previously failed on apk without a fix.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by shobhitagarwal1612 — APPROVED** [review]
