### PR TITLE
Fixed saving background recording after deleting initial audio file

### LINKED ISSUE #4398: Background recording created in edit after deleting initial audio file is unusable
#### Software and hardware versions 
Collect v1.29.x, Android vx.x.x, device used...

#### Problem description
When testing #4390 I have noticed a case when audio seems to be recorded but in fact, it doesn't work. 

#### Steps to reproduce the problem
1. Fill submission with background recording
2. Go to instance folder and delete the recording
3. Open edit Saved Form and edit submission
4. Open instance folder - see that new recording has been created
5. Try to play the audio file - it doesn't work
ezgif com-video-to-gif (52)

#### Expected behavior
- New audio should be recorded and independent of previously recorded and deleted one. 
- User should be able to open the recording 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4398

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It's a bug fix and there is no other solution. We just need to check if a file that is supposed to exist really exist, otherwise we need to create a new one.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be a save fix without any side effects. Please verify that it works well playing with background recording.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with background recording like the one available on the demo server.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java [hunk 1]
```diff
@@ -42,6 +48,33 @@ public class RecordingHandlerTest {
...
+        }, newRecording, 0, 0, false);
+
+        recordingHandler.handle(formController, recordingSession, success -> {
+        });
+
+        ArgumentCaptor<StringData> dataAc = ArgumentCaptor.forClass(StringData.class);
+        ArgumentCaptor<TreeReference> refAc = ArgumentCaptor.forClass(TreeReference.class);
+        ArgumentCaptor<Boolean> midSurveyAc = ArgumentCaptor.forClass(Boolean.class);
+
+        verify(formDef).setValue(dataAc.capture(), refAc.capture(), midSurveyAc.capture());
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java]: I think you can just pass the expected values here or use `eq` rather than needing `ArgumentCaptor`? Am I missing something?

File: collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java [hunk 2]
```diff
@@ -34,6 +39,7 @@ public class RecordingHandlerTest {
 
     private final FakeQuestionMediaManager questionMediaManager = new FakeQuestionMediaManager();
     private final FormController formController = mock(FormController.class);
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java]: It feels like we really want `FormController` to be an interface we can create a fake for. Do you fancy pulling out that out and renaming our implementation to `JavaRosaFormController` as a follow-up PR? If we had a structure like that, you could have just created a fake that lets you pull out the value for an answer rather than needing Mockito. That'd definitely be useful in a bunch of places and I do remember feeling like there was too much mocking needed for this test when I was working on the feautre.

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13

Verified cases:
- Issue [#4398](https://github.com/getodk/collect/issues/4398) is no longer reproducing
- scenario from the issue with don't keep activities enabled
- scenario from the issue with don't keep activities disabled
- background recording form
- background recording with audit form
- external recording is not selected
- use an external recording app
- use forms with audio widget
- change recording settings in the middle of filling the form
- light and dark mode
- Rotate the screen, minimize the app
- regression check on background recording in general
- Killing the app in the middle of recording

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

File: collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java]: Right, fixed.

File: collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formentry/RecordingHandlerTest.java]: Ok I've implemented such an interface. Please take a look and merge if everything is fine.

File: collect_app/src/main/java/org/odk/collect/android/gdrive/InstanceGoogleSheetsUploader.java [hunk 3]
```diff
@@ -14,7 +14,7 @@
 
 package org.odk.collect.android.gdrive;
 
-import static org.odk.collect.android.javarosawrapper.FormController.INSTANCE_ID;
+import static org.odk.collect.android.javarosawrapper.JavaRosaFormController.INSTANCE_ID;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/gdrive/InstanceGoogleSheetsUploader.java:17]: I think it'd be good to get not need to depend on `JavaRosaFormController` to grab these constants, but we can look at rearranging that another time. Adding the interface is a great change for the moment!

**Review by seadowg — APPROVED** [review]
