### PR TITLE
Fixed the disabled GeoWidget ImageButtons in Api21+.

### LINKED ISSUE #2262: Problem with visibility of inactive icons on Geo Widgets
#### Software and hardware versions 
Collect v1.15.0

#### Problem description
 Problem with visibility of inactive icons on Geo Widgets

#### Steps to reproduce the problem

**Use case 1: Google Maps**
1. The user opens Geo widgets
2. Inactive icons look like active on all Android version

**Use case 1: OpenStreetMap**
1. The user opens Geo widgets
2. Inactive icons look like active on Android 5.1, 6.0, 7.0, 8.1

|Android 5.1|screenshot_2018-05-30-15-43-30|screenshot_2018-05-30-15-42-25|screenshot_2018-05-30-15-22-56|
|---|---|---|---|
|Android 4.4|screenshot_2018-05-30-15-43-20|screenshot_2018-05-30-15-42-21|screenshot_2018-05-30-15-23-06|

#### Expected behavior
Icons look like active only when they are active

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #2262 #2143 

#### What has been done to verify that this works as intended?
I have tested in Android 4.4 and Android 6.0.

#### Why is this the best possible solution? Were any other approaches considered?
At first, I wanted to address this issue via `theme.xml`  using `style="@style/Widget.AppCompat.Button.Colored"`, but we have two themes, we can only set one `AccentColor` in this case. So I implemented a `GeoImageButton` and refactored the code.

Dark | Light
---- | ---
 | 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by huangyz0918** [comment]
Interesting, I used my friend’s computer and she has became a participant too. 😸

File: collect_app/src/main/java/org/odk/collect/android/views/GeoImageButton.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ */
+
+package org.odk.collect.android.views;
+
+import android.content.Context;
+import android.support.v7.widget.AppCompatImageButton;
+import android.util.AttributeSet;
+
+
+public class GeoImageButton extends AppCompatImageButton {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/views/GeoImageButton.java]: I would change this name. It's now used only by GeoButtons but generally, it could be used in other places also right? Maybe in navigation buttons? SO I would recommend something more generall. CustomImageButton?

Comment (huangyz0918) [reply collect_app/src/main/java/org/odk/collect/android/views/GeoImageButton.java]: Good idea. 👍

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by shobhitagarwal1612** [comment]
@huangyz0918 Thanks for working on this issue. I think there is a better way to indicate that the button is disabled without changing the alpha which makes the button almost go disappear instead of showing as just being disabled. The reason for the issue is because right now we have fixed the color of the icon to a fixed value. I was able to fix this by supplying a different color for different states of the icon using the color list resource.

Please have a look at this [commit](https://github.com/shobhitagarwal1612/collect/commit/c7728bc22e7195b63a9f27732577d224f5daadeb)

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by huangyz0918** [comment]
Cool @shobhitagarwal1612 , I will update this PR as you proposed. 👍

**Comment by huangyz0918** [comment]
@shobhitagarwal1612 I think the reason here is the material design theme introduced by android 5.0+. So if you only change the icon's color, there will be an inconsistency between Api21+ and Api21- (The background in Api21- has changed its alpha). I think we should still build a custom ImageButton since it could also be used in other cases in the future developments. 

I have tested in your branch:

Api21+ | Api21-
---- | ---
 | 

> which makes the button almost go disappear

In Android source code, the disabled alpha is `0.26f` in light theme and `0.30f` in dark theme. We can select a proper one or use code to switch this value dynamically.

**Comment by shobhitagarwal1612** [comment]
> I think the reason here is the material design theme introduced by Android 5.0+. So if you only change the icon's color, there will be an inconsistency between Api21+ and Api21-

That's true. But creating another view for setting the alpha values for pre & post lollipop devices seems kind of hacky to me as it would restrict this fix only to this view and not to all views in general. 
Also, reducing alpha doesn't look good in my opinion

**Comment by huangyz0918** [comment]
Now, it looks like:

Api21+ Dark | Api21- Dark | Api21+  Light | Api21- Light
---- | --- | --- | ---
 |  |  | 

please review @grzesiek2010 @shobhitagarwal1612

**Comment by lognaturel** [comment]
Thank you, @huangyz0918! I think the ideal behavior is what @shobhitagarwal1612's branch produces for API 21+. It's unfortunate that it's not consistent in API 21- but I think it's not so bad. I also like that the approach doesn't require introducing very much custom code.

@huangyz0918 am I right in saying that your latest changes essentially make things consistent but using the API 21- look from @shobhitagarwal1612's demo?

**Comment by huangyz0918** [comment]
> am I right in saying that your latest changes essentially make things consistent but using the API 21- look from @shobhitagarwal1612's demo?

It's true @lognaturel. 
I used `Build.VERSION.SDK_INT >= 21` to make things consistent in both Api21- and Api21+. I can update this PR as @shobhitagarwal1612 's demo, if possible, I think I can make things consistent without building a custom widget.

**Comment by lognaturel** [comment]
> I think I can make things consistent without building a custom widget.

Honestly, in this case I think the inconsistency in @shobhitagarwal1612's isn't terrible and I would tend to go with that. But if you have a good idea of how to get the API21+ behavior (alpha of the vector on the button changes but the alpha of the background stays the same), that would be the absolute ideal!

**Comment by huangyz0918** [comment]
@lognaturel I have to prepare for my graduate application recently, so I'll change this PR to [WIP] so that I can update it in next month when I'm free. 
It may need to cool for a while. Looking forward to you guys' review ,Lol 💯

**Comment by lognaturel** [comment]
>  I have to prepare for my graduate application recently

Very exciting! I hope that goes well and if you want to chat about it in #random, please do! Lots of folks in the community have gone through graduate school and might have some ideas for you.

**Comment by huangyz0918** [comment]
@shobhitagarwal1612 I have a question: why my changes will failed in some specific orders of test method? To my knowledge JUnit assumes that all tests can be performed in an arbitrary order, right?

Order 1  | Order 2
------------- | -------------
image  | image

I can't see any flaws in the test code, can I set a specific test order in this test ? @shobhitagarwal1612 @lognaturel

**Comment by huangyz0918** [comment]
The fix is really for a test. @grzesiek2010 @shobhitagarwal1612 @lognaturel

**Comment by lognaturel** [comment]
Thank you, @huangyz0918! I'm afraid I don't have an answer to your question about the tests but can try to dig into it later.

**Comment by mmarciniak90** [comment]
@huangyz0918 I still see inactive buttons as an active on two devices with Android 6.0 and device with Android 5.1.
I also noticed that the trash icon is sometimes active even if there is nothing to clear.

@opendatakit-bot unlabel "needs testing"

**Comment by huangyz0918** [comment]
@mmarciniak90 Thanks for testing. I will take a deep look when I am free.

**Comment by huangyz0918** [comment]
For changing the icon's color, I prefer keeping the same style as Api < 21. So I tried another approach. I think it's ok to meet our requirements.

|Dark|Light|
|:---:|:---:|
|||

It's ok for a review @lognaturel @shobhitagarwal1612  .

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs review"

**Comment by lognaturel** [comment]
Thanks for picking this back up, @huangyz0918! The issue I have is that changing the button's alpha doesn't make it look disabled to me because it's a very subtle change and it's not consistent with any other UI I know. It's changing the icon's alpha that is really important. That means this latest approach, although very clean, doesn't solve the issue to me.

If it's not cleanly possible to get that behavior across API levels, my preference would be to go with a solution that truly makes the buttons look disabled on API 21+ since that's what the majority of users run.

**Comment by huangyz0918** [comment]
@lognaturel Thanks for looking into this, I remember that I used a custom `ImageView` to solve this problem before, which looks very good and can also make the button consistent in all API levels.

In Android 5.0+ UI, the theme's disabled alpha was overwrote by the material design style, that's why the disabled alpha didn't show. I like @shobhitagarwal1612 's proposal to change the icon color in different themes but I don't know why it failed with QA's tests. So I think if we can use the custom `ImageView` to address this issue again since it doesn't affect the color in different themes, what's your opinion?

**Comment by lognaturel** [comment]
To make sure I'm getting it right -- you mean using a custom `ImageView` similar to your original approach but instead of changing the *button background*'s alpha, changing the *icon*'s alpha? I'm not exactly sure how much code that takes but it seems reasonable to me.

I think that after this attempt, if we're not getting the desired behavior, we should go for the approach described [here](https://github.com/opendatakit/collect/pull/2276#issuecomment-395522766).

**Comment by huangyz0918** [comment]
I don't like much custom code, especially for a tiny improvement, but if we must use the custom view, I propose to change the background's alpha instead of the icon color, because the default behavior under API 21 is changing the background.

I have some second thoughts @lognaturel , so it's no hurry  for us to address it, just making some attempts :)

**Comment by lognaturel** [comment]
> because the default behavior under API 21 is changing the background

But why would we match the old behavior rather than the new one?! I have not seen transparency of the background to indicate disabled status in any other context I can think of. 

Thanks for your experimentation, it's always interesting to see what different approaches there might be to a problem! In this case, I really think that what @shobhitagarwal1612 has proposed is "the Android way" and it's ok if it's not exactly the same on different API versions, especially since versions <21 are less and less common.

**Comment by huangyz0918** [comment]
I think I have found the best approach to address this issue. @lognaturel ;)
An improved version from @shobhitagarwal1612 's proposal, it works both in Android 5.1 and 6.0.

The screenshots:

|5.1-dark|5.1-light|
|:---:|:---:|
|||

|6.0-dark|6.0-light|
|:---:|:---:|
|||

|7.1-dark|7.1-light|
|:---:|:---:|
|||

@opendatakit-bot unlabel "needs discussion"

**Comment by lognaturel** [comment]
This behavior looks perfect to me, @huangyz0918!  🎉 The code change also looks nice and clean to me. 

@grzesiek2010 or @shobhitagarwal1612, could one of you please take a look to see if you are happy with the code and if so you can mark as `needs testing`?

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@huangyz0918 I noticed a couple of cases. Could you look at them?

1. **geopoint type with placement-map appearance**
* Google maps - Trash icon looks like active


* Google maps and OSM - GPS is disabled - Trash icon looks like active
* OSM - Trash icon looks like active
* Dark Mode - Trash icon looks like active
2.  **geopoint type with map appearance**
* Google maps - Trash icon looks like active

|screenshot_20181020-140247|screenshot_20181020-140225|
|---|---|


* Google maps and OSM - GPS is disabled - Trash icon looks like active
* OSM - Trash icon looks like active
* Dark Mode - Trash icon looks like active
3.  **geotrace type with no appearance**
* Google maps - looks correct


* Google maps - GPS is disabled - looks correct
* OSM - looks correct
* Dark Mode - looks correct
4. **geoshape type with no appearance**
* Google maps - Trash icon and Zoom to icon look like active


* Google maps - GPS is disabled - Trash icon looks like active. 
* Google maps - GPS is disabled - Zoom to icon is always inactive, even if user select area. User is not able to zoom to saved feature. I checked that this problem was visible without this changes too, but icon looks like active. @lognaturel, could it be fixed as a part of this issue?

|screenshot_20181020-142127|screenshot_20181020-142119|
|---|---|

* OSM - looks correct
* Dark Mode - Trash icon looks like active

@opendatakit-bot unlabel "needs testing"

**Comment by huangyz0918** [comment]
Thanks for your detailed testing! @mmarciniak90 👍 
Are those issues happened in all api levels? According to my tests, the trash button was real active (means the button was controlled by the incorrect code ), has no relationship with the theme and style.

**Comment by mmarciniak90** [comment]
@huangyz0918 I tested these geo widgets on Android 4.4, 5.1, 6.0, 7.0, 8.1

**Comment by huangyz0918** [comment]
@mmarciniak90 I can fix these issues but I think these problems have different essences from the problems we solved here, so I would like to open another github issue which can describe them better.

**Comment by lognaturel** [comment]
Are the problems @mmarciniak identified more about when the buttons are marked as enabled/disabled? The fact that the problems are visible on 4.4 means it's a logic problem and not a display problem, right? I'm also in Slack if you want to discuss more!

**Comment by huangyz0918** [comment]
@lognaturel Yes, it's a logic problem rather than a display problem, we should open another for that.

**Comment by lognaturel** [comment]
Thanks @mmarciniak90! Agreed that we can merge these layout fixes and then address the button logic problems that are now visible in a separate PR.

🎉
