### PR TITLE
Announce upcoming deprecation of Google Drive support

### LINKED ISSUE #5296: Announce upcoming deprecation of Google Drive support
About 5% of users in the last few months have used direct submission to Google Drive. It's completely untested and requires periodic intervention as Google APIs change. We also know that it has a number of quirks and unexpected behavior that we don't have the capacity to fix at this time.

As discussed with the TAB on March 16th 2022, we will be putting Google Drive support on a deprecation path. The first step will be to notify users of this within the app.

Forum post: https://forum.getodk.org/t/40097

### Acceptance

- [ ] Given I have a project configured to use Google Drive
When I switch to that project
Then I see a banner warning me about Google Drive deprecation
And the banner has a "Learn more" button
And the banner does not have a "Dismiss" button

- [ ] Given I have a project configured to use Google Drive
When I switch to that project
And I click "Learn more"
Then I am taken (in my browser) to the forum post explaining Google Drive deprecation

- [ ] Given I have a project configured to use Google Drive
When I switch to that project
And I click "Learn more"
And I return to the app
And I click "Dismiss" on the Google Drive banner
Then I no longer see the Google Drive deprecation banner

- [ ] Given I have a project configured to use Google Drive
And a project configured to use an ODK Server
When I switch to the ODK Server project
Then I do not see the Google Drive deprecation banner

- [ ] Given I have two projects configured to use Google Drive
When I switch to one of those projects
And I click "Learn more"
And I return to the app
And I click "Dismiss"
Then I no longer see the Google Drive deprecation banner
And I do see the banner in the other Google Drive project

### Notes

The text for the banner should is "This project uses Google Drive. This functionality will be removed in the next app update.".

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5296 

#### What has been done to verify that this works as intended?
I've tested the banner manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I've implemented the banner according to the discussion in the issue. Not much to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test the banner. I can't think of any other parts of the app that could be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+            .switchToManualMode()
+            .openGooglePickerAndSelect(googleAccount)
+            .clickOnString(R.string.learn_more_button_text)
+            .pressBack(MainMenuPage())
+            .clickOnString(R.string.dismiss_button_text)
+            .assertTextNotDisplayed(R.string.google_drive_deprecation_message)
+            .openProjectSettingsDialog()
+            .clickSettings()
+            .clickProjectManagement()
+            .deleteProject()
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt]: I don't think you need to delete the first project in this test. In fact, deleting might actually allow a bad implementation where the banner is hidden for all projects if it's dismissed in one (which wouldn't be caught in the test if the project is deleted).

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+        rule.startAtMainMenu()
+            .openProjectSettingsDialog()
+            .clickAddProject()
+            .switchToManualMode()
+            .openGooglePickerAndSelect(googleAccount)
+            .clickOnString(R.string.learn_more_button_text)
+            .pressBack(MainMenuPage())
+            .clickOnString(R.string.dismiss_button_text)
+            .assertTextNotDisplayed(R.string.google_drive_deprecation_message)
+            .rotateToLandscape(MainMenuPage())
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt:97]: Is the rotation added to attempt to make sure that banner stays dismissed between different instances of `MainMenuActivity`? I'm finding that I can comment out the `unprotectedSettings.save(ProjectKeys.GOOGLE_DRIVE_DEPRECATION_BANNER_DISMISSED, true);` line and this test will still pass. Maybe the assertions don't wait long enough?

Rotation is definitely a little flakey: I'm wondering if a stabler approach would be to write a test for `MainMenuActivity` that checks it doesn't show the banner if `ProjectKeys.GOOGLE_DRIVE_DEPRECATION_BANNER_DISMISSED` is true and then another test to check that clicking "Dismiss" sets it to true. Using that approach, you might be able to avoid any Espresso tests, but I'll leave how you slice that up to you.

File: settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt [hunk 3]
```diff
@@ -73,4 +73,7 @@ object ProjectKeys {
     const val BASEMAP_SOURCE_USGS = "usgs"
     const val BASEMAP_SOURCE_STAMEN = "stamen"
     const val BASEMAP_SOURCE_CARTO = "carto"
+
+    const val GOOGLE_DRIVE_DEPRECATION_LEARN_MORE_CLICKED = "gd_lear_more_clicked"
+    const val GOOGLE_DRIVE_DEPRECATION_BANNER_DISMISSED = "gd_banner_dismissed"
```
Comment (seadowg) [inline settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt:78]: Storing this state as a project setting does mean that resetting all settings, then setting the project up as a Google Drive project will that the user would see the banner again even if they've already dismissed. I think this totally OK though. Just wanted to note that for @getodk/testers.

File: collect_app/src/main/res/layout/google_drive_deprecation_banner.xml [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+            android:layout_marginEnd="@dimen/margin_small"
+            android:text="@string/dismiss_button_text"
+            android:textAllCaps="true"
+            app:layout_constraintBottom_toBottomOf="parent"
+            app:layout_constraintEnd_toStartOf="@id/learn_more_button"
+            app:layout_constraintTop_toBottomOf="@+id/message" />
+
+        <com.google.android.material.button.MaterialButton
+            android:id="@+id/learn_more_button"
+            style="@style/Widget.MaterialComponents.Button.TextButton"
```
Comment (seadowg) [inline collect_app/src/main/res/layout/google_drive_deprecation_banner.xml:43]: I think we should use `Widget.Material3.Button.TextButton` for these buttons and drop the `textAllCaps`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/res/layout/google_drive_deprecation_banner.xml (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/res/layout/google_drive_deprecation_banner.xml:43]: Drop the `textAllCaps` because you think they should not be capitalized? In https://m2.material.io/components/banners it is capitalized.

Comment (seadowg) [reply collect_app/src/main/res/layout/google_drive_deprecation_banner.xml:43]: Ah true. I'd forgotten that the "Banner" is an actual Material 2 component.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt:97]: > Is the rotation added to attempt to make sure that banner stays dismissed between different instances of MainMenuActivity? I'm finding that I can comment out the unprotectedSettings.save(ProjectKeys.GOOGLE_DRIVE_DEPRECATION_BANNER_DISMISSED, true); line and this test will still pass. Maybe the assertions don't wait long enough?

Actually, it was a problem with our methods responsible for checking if the text was displayed. In this case, the problem was that the device was rotated and the main menu was scrolled down so the banner existed but was not visible. We could have similar issues with many other tests so I've implemented improvements in commits 3-7. Thanks to that I check if a particular text exists and is displayed not if it's visible at the moment so I don't need to try to scroll to that element first.

> Rotation is definitely a little flakey: I'm wondering if a stabler approach would be to write a test for MainMenuActivity that checks it doesn't show the banner if ProjectKeys.GOOGLE_DRIVE_DEPRECATION_BANNER_DISMISSED is true and then another test to check that clicking "Dismiss" sets it to true. Using that approach, you might be able to avoid any Espresso tests, but I'll leave how you slice that up to you.

I was thinking about it but it's a test just for now and will be removed once we remove GD so it was easier.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt]: Ok, I've updated the test so now it adds a new GD project. Doing that I discovered a bug... If you add two GD projects the second one is treated as a duplicate and there is a dialog that asks if you want to add it or switch to the existing one. That's why I've updated this method: https://github.com/getodk/collect/pull/5414/commits/c15d4ca24e3b925965fd35b2b34d7434fb5679f4#diff-37878b479841035eb4ab6e19b89c4057744c0f7a948dcebebff40f9607cb39c2R36
I didn't file it because I think we can ignore it:
- I don't think people use two different GD projects
- no one has complained about it
- we are going to remove the GD integration

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13

**Verified cases;**
- Adding new project;
- Resetting the project and the project settings;
- Adding duplicated project;
- Dismiss the info;
- Rotate the screen, minimize the app;
- Light and Dark mode

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10
