### PR TITLE
Capitalize 'gps' in user-facing notifications. Closes #2156.

### LINKED ISSUE #2156: Show GPS as all caps
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
GPS shows as gps in the dialog that appears when a GPS fix is being acquired. Search the source for `location.getProvider()`. One of the values `getProvider` returns is `gps`. That value, and probably only that value, should be changed to `GPS` before being presented to the user.

#### Steps to reproduce the problem
Fill the All widgets form and select the GeoPoint Widget. Push Start GeoPoint. You should see this, eventually:

screen shot 2018-04-25 at 12 03 03 pm

#### Expected behavior
“GPS”, being an initialism, should always appear capitalized to the user.

### PR DESCRIPTION
**Pull request by KiaFarhang**
When using location-related form widgets like geopoints, users will see a message like 'Using gps. Accuracy is 10 m.' while Collect poinpoints their location. Since GPS is a standardized acronym, this commit changes occurrences of the term in these notifications to properly say 'Using GPS' instead.

Three classes - GeoPointActivity, GeoPointMapActivity and GeoPointsOsmMapActivity - use the Android Location.getProvider() call to build strings in this way. Since they all inherit from CollectAbstractActivity, this commit creates an abstract LocationActivity superclass for those three classes. The LocationActivity class contains just a single method, which, given a string, returns 'GPS' if the parameter is 'gps' and otherwise just returns the parameter untouched.

This lets the three location classes inherit from LocationActivity and simply slightly tweak their accuracy-generating methods to capitalize GPS for the user.

Closes #2156 

#### What has been done to verify that this works as intended?

Ran the Gradle test suite and found my original approach caused a failed GeoPointActivity test due to a NullPointerException. It appears the testLocationClientLifecycle() test at one point passes `null` to the activity as a location. 

This has been resolved - should the superclass's capitalization method receive null instead of a string, it simply returns null instead of trying to work with it. (It appears this is what would happen if the location was ever really null and we added it to our user-facing string).

I also ran my changes on an Android and verified the user now sees "Using GPS" instead of "using gps" when pinpointing location with any of the three affected widgets/activities.

#### Why is this the best possible solution? Were any other approaches considered?

Rather than hard-coding the check for `"gps"` in the capitalization method, I considered whether it might be better to use a string resource instead. A little bit of looking around online tells me GPS seems to be known as GPS everywhere and thus wouldn't require translation. However, I'm curious if the team thinks we should use a string resource instead - and I'm happy to make the change if so.

@dcbriccetti was extremely helpful and suggested creating a new abstract parent for the three activities - the only other way I could think of would require duplicating the check for the string `"gps" across all three classes, but I'd be curious as to the team's thoughts.

#### Are there any risks to merging this code? If so, what are they?

None that I can think of, other than it adding another abstract class and whether we want to take on that weight.

#### Do we need any specific form for testing your changes? If so, please attach one.

Nope!

#### Does this change require updates to documentation? If so, please file an issue at [Here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

Nope!

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors so that they work with both light and dark themes.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java [hunk 1]
```diff
@@ -255,7 +255,7 @@ public String getAccuracyMessage(@NonNull Location location) {
     }
 
     public String getProviderAccuracyMessage(@NonNull Location location) {
-        return getString(R.string.location_provider_accuracy, location.getProvider(), truncateDouble(location.getAccuracy()));
+        return getString(R.string.location_provider_accuracy, capitalizeGPS(location.getProvider()), truncateDouble(location.getAccuracy()));
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java]: This is ironic, but GPS must be Gps here, to follow naming conventions about initialisms in identifiers.

File: collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java [hunk 2]
```diff
@@ -0,0 +1,13 @@
+package org.odk.collect.android.activities;
+
+/**
+ * Wraps location-based activity classes GeoPointActivity, GeoPointMapActivity and
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: I’d argue that being a superclass isn’t the same as “wrapping”. Maybe you can find a better wording. Also “sanitize” may not be the right word. “correct”?

File: collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+ * GeoPointOsmMapActivity. Provides a method to sanitize location provider names so "gps" displays
+ * as "GPS" in user-facing messaging.
+ */
+
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: We generally don’t have a blank line between the doc comment and the method.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
Looks really nice, and very well documented in the PR

**Comment by dcbriccetti** [comment]
>Since GPS is a standardized acronym

This is picky, but since this is the precise topic of the PR, we should be. GPS is an initialism. It’s not an acronym because you can’t pronounce it as a “word”, like NASA. I’ve heard Josh Bloch make the distinction, so it’s not just me.

File: collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+public abstract class LocationActivity extends CollectAbstractActivity {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: I would rather create a util class instead of adding a new activity just for one method.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: But is it an activity?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: It extends activity so it's also an activity.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: It contains behavior common to one subset of CollectAbstractActivity. I don’t see it as we’re adding another activity. How do you see it that way?

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: We’re not increasing the number of concrete Activity classes.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: I mean it's not a separate activity we use somewhere (since it's abstract) but it's another layer created just for one method what doesn't really make sense to me.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: OK, I understand your objection.

How would creating a util class be an improvement? It too would be a class created just for one method.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: Yes but then in:
GeoPointActivity
GeoPointMapActivity
GeoPointOsmMapActivity

you don't need to extend that new class and you can use CollectAbstractActivity as it was what makes the code clearer. I know that maybe it doesn't go really well so far but we wanted to start introducing patterns like MVVM and separating such code from activities, so creating a new activity layer just for that method doesn't look good.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: I find your argument compelling that we shouldn’t add code like this to a class in the Activity hierarchy, because it not a concern of an activity. Thanks for explaining. 

What would you recommend for the name of a class to hold this new method, and in what package would you put it? And would you make the method static? (I’ve seen the argument that such methods shouldn’t be static so they can be more easily mocked.)

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: the package is easy because we have one called `org.odk.collect.android.utilities` but when it comes to the name... maybe just `GeoPointUtils`  I'm not sure but probably there are more methods we could move to such a class.

Comment (dcbriccetti) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: Thanks, @grzesiek2010! @KiaFarhang, how does this sound to you?

Comment (KiaFarhang) [reply collect_app/src/main/java/org/odk/collect/android/activities/LocationActivity.java]: I feel like I just got a free Java best practices class by reading these comments :) Thanks very much @grzesiek2010 and @dcbriccetti - here's a list of the changes I'll make:

- Cut the abstract `LocationActivity` class in favor of a `GeoPointUtils` utility class under `org.odk.collect.android.utilities`
- Looking at other utility classes I'm seeing a fair number of static methods for issues like these when we just need to modify a String. I'll go with static for now, but changing would be easy so let me know if we should take another approach.
- I'll follow @dcbriccetti's recommendations on formatting, wording and capitalization in the method name.
- Will also throw a test class in for the utility class, with a couple quick unit tests for this capitalization method.

Thanks again to both of you for the help!

**Comment by dcbriccetti** [comment]
Hi. Here’s a guide to interactive rebase, which would allow you to combine your three commits into one:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
Then you do a force push (not Star Wars, git).

**Comment by KiaFarhang** [comment]
Hmm. I'll preface this by saying I'm not familiar with a CI workflow, so the error may be mine. The `./gradlew lint checkstyle pmd findbugs` task runs successfully on my machine, even after cleaning the Gradle cache. Looks like it failed on the CI machine, though.

Gradle threw the following error in CircleCI:

```
Execution failed for task ':collect_app:transformClassesWithDesugarForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar
```
Some googling tells me this might just be library mismatches or a caching issue. I tried searching the Gradle log for references to checkstyle or the names of the files I changed and nothing came up, so perhaps this is just some weird bug? Wondering if @dcbriccetti or others have any advice on how to proceed. Thanks in advance!

**Comment by dcbriccetti** [comment]
I’m guessing that error will disappear as mysteriously as it appeared. When you push, it might get a little nudge. Oh, I see you’ve already combined the commits and pushed.

File: collect_app/src/main/java/org/odk/collect/android/utilities/GeoPointUtils.java [hunk 5]
```diff
@@ -0,0 +1,15 @@
+package org.odk.collect.android.utilities;
+
+public class GeoPointUtils {
+
+    private GeoPointUtils(){
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/utilities/GeoPointUtils.java]: Checkstyle allowed the ){ with no space?

File: collect_app/src/test/java/org/odk/collect/android/utilities/GeoPointUtilsTest.java [hunk 6]
```diff
@@ -0,0 +1,20 @@
+package org.odk.collect.android.utilities;
+
+import org.junit.Test;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertNull;
+
+public class GeoPointUtilsTest {
```
Comment (dcbriccetti) [inline collect_app/src/test/java/org/odk/collect/android/utilities/GeoPointUtilsTest.java:8]: The test is a nice bonus.

**Review by dcbriccetti — APPROVED** [review]

**Comment by KiaFarhang** [comment]
Hi @dcbriccetti - thank you for your quick note on squashing. You are giving me (a mostly one-man programming team so far) such a thorough introduction to work on large projects I owe you a coffee.

Squashed, force pushed and the build failed at a different step, this time on the `transformClassesWithDesugarForDebugAndroidTest` task. 

Wondering if this is just a weird caching issue on the CI machine, so I'll defer to others' judgment for now. Happy to help if there's anything needed on my end, though.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 8.1
Verified cases:
* Geopoint widget no appearance
* Geopoint widget with placement-map appearance
* Geopoint widget with maps appearance
* Google maps
* OSM maps

| | | | | |
|---|---|---|---|---|
|screenshot_2018-05-15-12-28-23|screenshot_2018-05-15-12-37-16|screenshot_2018-05-15-12-37-02|screenshot_2018-05-15-12-36-24|screenshot_2018-05-15-12-36-39|

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thanks very much, @KiaFarhang!

You're totally right, the CircleCI failure is related to general CI woes we're having. Updates in Slack as they become available.
