### PR TITLE
Include DynamicPreloadExtra in formDef only if a form contains search or pulldata

### LINKED ISSUE #6447: CannotCreateObjectException: DynamicPreloadExtra not instantiable during form loading
#### ODK Collect version
v2024.2.1 and newer versions

#### Problem description
While working on https://github.com/getodk/collect/issues/6446 I've noticed that many errors contain an additional exception:
```java
W/null: org.javarosa.core.util.externalizable.CannotCreateObjectException: 
    org.odk.collect.android.dynamicpreload.DynamicPreloadExtra: not instantiable at 
    org.javarosa.core.util.externalizable.PrototypeFactory.getInstance(PrototypeFactory.java:130) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:182) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:177) at 
    org.javarosa.core.util.externalizable.ExtWrapExternalizable.readExternal(ExtWrapExternalizable.java:37) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217) at 
    org.javarosa.core.util.externalizable.ExtWrapList.readExternal(ExtWrapList.java:80) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217) at 
    org.javarosa.core.util.externalizable.ExternalizableExtras.readExternal(ExternalizableExtras.java:16) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:183) at 
    org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:177) at 
    org.javarosa.core.model.FormDef.readExternal(FormDef.java:1045) at
```

#### Steps to reproduce the problem
I'm not able to reproduce the issue.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6447

In [issue #6446](https://github.com/getodk/collect/issues/6446), I mentioned that the problem with initializing `DynamicPreloadExtra` is likely not the main cause of the memory issues. However, when this exception is thrown, it indicates that we cannot read the form from cache and must load it from the file instead. This process consumes more memory and could be one of the factors contributing to the numerous out-of-memory issues we are experiencing.

#### Why is this the best possible solution? Were any other approaches considered?
As I mentioned in the issue, I cannot reproduce it and don’t fully understand why `DynamicPreloadExtra` sometimes cannot be instantiated, but I have some suspicions. Initially, I thought the issue might be related to ProGuard and the app shrinking process. We need an empty constructor to instantiate `DynamicPreloadExtra` using the `newInstance()` method in javarosa, and I wondered if that constructor had been removed. However, after installing the app version from the store, I didn’t encounter that exception, so that can’t be the cause.

Since this issue occurs for only some users, I suspect that `newInstance()` may have trouble creating an object from a Kotlin class. I know this sounds unusual, but after working on [issue #6364](https://github.com/getodk/collect/issues/6364), I have become more open to the idea that such unexpected issues can arise.

Although I can’t be certain about the root cause of the issue, I have a plan to at least mitigate it. For now, we add `DynamicPreloadExtra` to `formDef` regardless of whether a form uses `pulldata` or `search`. There is a true/false value that determines this, but I believe it is unnecessary. For instance, `EntityFormExtra` is only added if the form actually contains entities (see: [EntityFormParseProcessor.java#L63](https://github.com/getodk/collect/blob/master/entities/src/main/java/org/odk/collect/entities/javarosa/parse/EntityFormParseProcessor.java#L63)). I think `DynamicPreloadExtra` should operate in the same way and thanks to that it should not need to store any value. If it is present, it indicates that the form contains `search` or `pulldata`, if it is absent, then it does not.

If I’m correct that `newInstance()` may have difficulties creating objects from Kotlin classes, these changes might help, as the empty constructor is now the primary one. Could this have been the issue?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This requires testing forms with search/pulldata.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadParseProcessorTest.kt [hunk 1]
```diff
@@ -14,50 +15,50 @@ class DynamicPreloadParseProcessorTest {
     private val processor = DynamicPreloadParseProcessor()
 
     @Test
-    fun `usesDynamicPreload is false when xpath does not contain pulldata`() {
+    fun `usesDynamicPreload is null when xpath does not contain pulldata`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadParseProcessorTest.kt]: These tests should probably be renamed so they read like "DynamicPreloadExtra is..." instead of referencing the now gone `usesDynamicPreload`.

File: collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCasesTest.kt [hunk 2]
```diff
@@ -27,8 +25,23 @@ class ExternalDataUseCasesTest {
     }
 
     @Test
-    fun `create() works if the FormDef does not have a DynamicPreloadExtra()`() {
+    fun `create() does not create a db file if the FormDef has not a DynamicPreloadExtra()`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCasesTest.kt]: `...if the `FormDef` does not have a...`

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14

**Verified cases:**

- Forms with search and pulldata
- Pulldata in entity forms

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
