### PR TITLE
Replace the use of 'or' with an sql 'in' when selecting instances for…

### LINKED ISSUE #323: Expression tree too large when submitting results
#### Software and hardware versions 
Collect v1.4.11, Android v unknown, device used unknown

#### Problem description
A user reported a problem on submitting results.  The error message was:  

> Expression tree is too large (maximum depth 1000): while compiling: SELECT ... FROM instances WHERE (_id=? or _id=? or _id=?............)

#### Steps to reproduce the problem
I haven't reproduced this problem it seems to involve a very large number of results instances to be sent.  I suggested to the users manager that they select only some of the instances to send at a time and also subsequently made available a "fix" in the fieldTask fork.  I'm not sure which approach worked however as far as I know they were able to submit their results through one or the other of these approaches.

#### Expected behavior
Error should not be shown under any circumstances.

#### Other information 
The "fix" involved replacing the use of "or" by the use of an "IN" clause to select the instances.

### PR DESCRIPTION
**Pull request by nap2000**
… upload. Fix #323 

This is more of a suggestion than a "fix".  I've not reproduced the error which appeared to be caused by having a large number of instances to upload and hence have not demonstrated that the code changes here fix the issue.  

However based on an internet search it looks like using "IN" instead of "OR" is supposed to be a fix.  http://stackoverflow.com/questions/20838301/android-sqlite-correct-way-to-build-a-cursor-with-a-large-array-of-selection 

The code changes have also been tested in the fieldTask odk fork and instance uploads still work.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java [hunk 1]
```diff
@@ -522,16 +522,19 @@ private boolean uploadOneSubmission(String urlString, String id, String instance
     protected Outcome doInBackground(Long... values) {
         Outcome outcome = new Outcome();
 
-        String selection = InstanceColumns._ID + "=?";
+        StringBuffer selectionBuf = new StringBuffer(InstanceColumns._ID + " IN (");
         String[] selectionArgs = new String[(values == null) ? 0 : values.length];
-        if (values != null) {
+        if(values != null) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java]: There should be a space between the if and the opening paren! I think that's a generally-accepted convention for C-like languages and [here](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace) it is from Google's conventions. We follow the Android open source style guide.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Please make the little nitpicky spacing change and I'll merge! 😊

**Comment by nap2000** [comment]
ok.  hopefully the updated commit fits the bill
