### PR TITLE
Cache BitmapDescriptor

### LINKED ISSUE #5007: java.lang.RuntimeException: Could not allocate dup blob fd.
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/bb3de6a367388d12a48d24f90bab97a6?versions=v2022.1.0%20(4359)&time=last-seven-days&types=crash&sessionEventKey=61F6AB76002B000177D2525D3AABD425_1637466206334167960

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.odk.collect.android/org.odk.collect.android.activities.FormMapActivity}: java.lang.RuntimeException: Could not allocate dup blob fd.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4559)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4591)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7844)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
```

```
Caused by java.lang.RuntimeException: Could not allocate dup blob fd.
       at android.graphics.Bitmap.nativeCreateFromParcel(Bitmap.java)
       at android.graphics.Bitmap.access$000(Bitmap.java:48)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2132)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2124)
       at ars.a(ars.java:2)
       at com.google.android.gms.maps.model.internal.a.bj(a.java:7)
       at arr.onTransact(arr.java:4)
       at android.os.Binder.transact(Binder.java:1052)
       at com.google.android.gms.internal.maps.zza.zzH(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.0.0:3)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.0.0:2)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5007 

#### What has been done to verify that this works as intended?
I've just reviewed implemented changes and played with google maps to make sure there is no regression.

#### Why is this the best possible solution? Were any other approaches considered?
I can't reproduce the issue but it seems to be too common to ignore it so I decided to at least try to fix it. To do that I implemented a similar solution we have added some time ago for caching bitmaps https://github.com/getodk/collect/pull/5010. Markers in google maps use `BitmapDescriptor` not just `Bitmap` like in mapbox or osm so my gut says we might need to cache that whole `BitmapDescriptor` in this case. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify that displaying markers (map of forms + geo widgets) works well with Google maps.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java [hunk 1]
```diff
@@ -194,7 +192,7 @@ public void onSaveInstanceState(@NonNull Bundle outState) {
     }
 
     @Override public void onDestroy() {
-        MapsMarkerCache.clearCache();
+        BitmapDescriptorCache.clearCache();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java:195]: You'll still want to clear the `MapsMarkerCache` I think? `BitmapDescriptorCache` ends up sticking bitmaps in there. Maybe `BitmapDescriptorCache#clearCache()` should clear the `MapsMarkerCache`?

We probably want a more general cache solution that could simplify these kinds of interactions (and possibly event interact with Android Lifecycle), but I think waiting for a third object is worth it before trying to create that kind of abstraction.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java:195]: Right, fixed.

**Comment by srujner** [comment]
**Tested with Success!**
Verified on Androids: 5.1, 10 and 12

**Verified cases:**

- Regression check on GeoPoint widgets with Google Maps:
- View Submissions on map;
- Forms with displaying markers: Select one from map, Internal map selects
- Collecting Location in background;
- Offline Layers;
- Placement by tapping;
- Manual and Automatic location recording;
- Edit and send submission to Central;
- Screen rotation, minimize app, using backward button.

**Comment by dbemke** [comment]
**Tested with Success!**
Verified on Androids: 8.1, 11
