### PR TITLE
Fixed handling translations

### LINKED ISSUE #3988: Notifications not being translated
~~Blocked by #3986.~~

#### Software and hardware versions 

Collect v1.27.3 (older versions as well)

#### Problem description

It seems notifications for auto send and auto update are not being translated.

#### Steps to reproduce the problem

1. Set Collect's language to something other than English
1. Enabled auto send
1. Fill out and finalize a form

You'll see the notification is in English.

#### Expected behavior

Notifications use the same language as the rest of the app.

#### Other information 

This will be problem wherever we use the `Application` to grab resource strings rather than an `Activity`. This is because the way we change the language only does so for `Activity` contexts, but we're unable to change the resource locale at an `Application` level. We're seeing this in Notifications as they are mostly created from background jobs that would use the application context as they don't have access to an `Activity`. 

#3986 introduces code that lets us create resource objects with the correct locale from the application context (in `NotificationManagerNotifier`). Once that is merged we can use that for all the notifications.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3988 #3029

#### What has been done to verify that this works as intended?
I tested the scenario from #3988 

#### Why is this the best possible solution? Were any other approaches considered?
It's the only solution. Sometimes we just can access application context only and we need to get translations using it however the application context is not updated when we change language so we need the helper class I created.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pr touched many classes but I don't think we should test the whole app. I think we can confirm that it fixes #3988 and merge then test it on a daily basis.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java [hunk 1]
```diff
@@ -102,10 +103,10 @@
                     } catch (SubmitException e) {
                         switch (e.getType()) {
                             case GOOGLE_ACCOUNT_NOT_SET:
-                                notifier.onSubmission(true, Collect.getInstance().getString(R.string.google_set_account));
+                                notifier.onSubmission(true, TranslationHandler.getString(Collect.getInstance(), R.string.google_set_account));
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java]: We can actually use the `context` param here instead of `Collect.getInstance()`

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/BackgroundWorkUtils.java [hunk 2]
```diff
@@ -15,13 +16,13 @@ private BackgroundWorkUtils() {
     }
 
     public static long getPeriodInMilliseconds(String period) {
-        if (period.equals(Collect.getInstance().getString(R.string.every_one_hour_value))) {
+        if (period.equals(TranslationHandler.getString(Collect.getInstance(), R.string.every_one_hour_value))) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/backgroundwork/BackgroundWorkUtils.java]: This method could take a `Context` param in our just be inlined it looks like as it's only called from one place that has access to `Application`.

File: collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java [hunk 3]
```diff
@@ -95,7 +96,7 @@
     private static HashMap<String, Object> getHashMap() {
         HashMap<String, Object> hashMap = new HashMap<>();
         // odk_server_preferences.xmll
-        hashMap.put(KEY_SERVER_URL,                 Collect.getInstance().getString(R.string.default_server_url));
+        hashMap.put(KEY_SERVER_URL,                 TranslationHandler.getString(Collect.getInstance(), R.string.default_server_url));
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java]: All the values in here should be in `unstranslated.xml` right? I think we should probably just use `getString` directly here.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java [hunk 4]
```diff
@@ -1,23 +1,17 @@
...
 import org.odk.collect.android.R;
+import org.odk.collect.android.application.Collect;
 import org.odk.collect.android.openrosa.api.FormApiException;
+import org.odk.collect.android.utilities.TranslationHandler;
 
 public class FormApiExceptionMapper {
 
-    private final Resources resources;
-
-    public FormApiExceptionMapper(Resources resources) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java:12]: I think it'd still be nice for this object to take in `Context` as a constructor dependency so it doesn't have to rely on `Collect.getInstance()`

**Review by seadowg — CHANGES_REQUESTED** [review]
Looks great! Just noted a few places where it looks like we could use a local context object.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java]: Done.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java:12]: Done.

File: collect_app/src/main/java/org/odk/collect/android/backgroundwork/BackgroundWorkUtils.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/backgroundwork/BackgroundWorkUtils.java]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 looks like this has collected conflicts ☹️

**Comment by grzesiek2010** [comment]
> looks like this has collected conflicts

fixed.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases:
* Spanish language set on device, German language set on Collect
* English language set on device, Spanish language set on Collect
* English language set on device, French language set on Collect
* toast when user clicks on save icon while filling form
* toast when user clicks on button `Save Form and Leave`
* toast when user puts incorrect email in Form Metadata
* toast when user imports settings
* autosend notification
* autodownload the latest form version notification
* light/dark mode

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 9.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
