### PR TITLE
Keep scanning codes when the result is not accepted

### LINKED ISSUE #6687: Issue with scanning non-project QR code when configuring project
**ODK Collect version**
the master version ca16422060d0e46303d427112e6a511947e33626
Version from PR #6672 

**Android version**
10, 12, 14

**Device used**
Redmi 9T, Pixel 3a, Pixel 7a, Samsung Gaaxy M23

**Problem description**
There is a problem with scanning the inverted QR Code with Google Drive project. 
On PR version,after scanning the QR the scanner hangs till you rotate the screen or go back to the previous screen. 
On Master version it just keeps scanning and spamming with a toast and beeps.

**Steps to Reproduce**

1. Install the app
2. Scan the invertQRGD.png code from here: https://drive.google.com/drive/u/2/folders/1NMufYB2wCTDJADcNl6XEEF3MEq6Bk9cB

**Expected Behavior**
- The scanner should stop for a few seconds, so the user has time to read the error and then start scanning again

### LINKED ISSUE #6755: App crash due to null rawValue in MLKit scanning result
**ODK Collect version**
v2025.2.0-beta

**Problem description**
The app crashes when attempting to access `rawValue` from a barcode scanning result using MLKit without checking for null.

https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/af0084905d93ff9a200f0cc7719da6d9?time=last-seven-days&sessionEventKey=683DF152019D000176B8BE21392A984E_2089870726904211617

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6687
Closes #6755 

#### Why is this the best possible solution? Were any other approaches considered?
I updated the shared method used by both MLKit and Zxing to delay scanning new codes by 1s when the previously scanned code cannot be accepted. This change is a result of the discussion we had in: https://github.com/getodk/collect/pull/6737

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change should fix the issue where scanning stops even though the result wasn’t accepted (e.g., due to incorrect settings or when trying to add a Google Drive project). It now allows users to continue scanning in such cases.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@seadowg I'm opening a new PR because I accidentally closed the previous one by force-pushing the wrong commits. Unfortunately, I’m unable to reopen it.

**Review by seadowg — CHANGES_REQUESTED** [review]
@grzesiek2010 it looks like there is a crash due to a `!!` in the MLKit code: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/af0084905d93ff9a200f0cc7719da6d9?time=last-seven-days&sessionEventKey=683DF152019D000176B8BE21392A984E_2089870726904211617.

Are you able to fix that here? I think that's better than me creating a PR that'll probably just conflict.

**Comment by grzesiek2010** [comment]
> Are you able to fix that here? I think that's better than me creating a PR that'll probably just conflict.

I'm on it.

File: qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt [hunk 1]
```diff
@@ -43,10 +47,22 @@ abstract class BarcodeScannerView(context: Context) : FrameLayout(context) {
...
-        return MutableLiveData<String>().also {
-            this.decodeContinuous { result -> it.value = result }
+    fun waitForBarcode(scope: CoroutineScope): LiveData<String> {
+        val liveData = MutableLiveData<String>()
+        var acceptResult = true
+
+        this.decodeContinuous { result ->
+            if (acceptResult) {
+                acceptResult = false
+                liveData.value = result
```
Comment (seadowg) [inline qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt]: There's a potential race condition here given that `decodeContinuous` now doesn't stop "emitting" new barcodes after it finds one: if something takes more than a second to process a new result from the returned `LiveData` here it may end up processing two results. An example would be something like this:

1. Bad qr code is scanned
2. Project creation with the barcode and fails
3. Simultaneously to **2** another barcode is scanned and project creation is kicked off again

I **think** we're protected from this right now because `QrCodeProjectCreatorDialog` does project creation on the UI thread, but that's not ideal and any setup we have here should not rely on that. Instead, I think we want an implementation where `decodeContinuous` reverts back to the behaviour of stopping scanning once a barcode is found (adding back the `cameraController.unbind()`) and then `QrCodeProjectCreatorDialog` restarts scanning (calling `decodeContinuous` again) if project creation fails (probably after a small delay using something like `post`). 

One alternative might be to move to a differnet implementaton with `start`/`stop` methods on `BarcodeScannerView`, and I'm sure there are other ways to get the "scan until a barcode is found and then restart" behaviour here.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt (hunk 1 above)
Comment (grzesiek2010) [reply qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt]: How about this?: https://github.com/getodk/collect/pull/6752/commits/361dc828ec6c55a62a2b38318d1d940494884f1e

Comment (seadowg) [reply qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt]: The more I think about it, the more I'd prefer to get rid of `BarcodeScannerView#decodeContinuous` and replace it with a method that only fires the passed callback for the first barcode it finds (and could be recalled). That would work as lot better with this flow. 

I think what you've got is a good solution that avoids us having to change the underlying MLKit and Zxing implementations though. We can follow up with a rework to `BarcodeScannerView` that better gits this new behaviour. The one thing I'd change is just to use `Handler` to delay the call to `continueScanning` - we're not really using coroutines directly anywhere in the code, and it feels a little surprising to see it here.

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6752#discussion_r2128995932

**Review by seadowg — CHANGES_REQUESTED** [review]
Let's remove the fallback to `getDisplayValue` for now until we've been able to discuss further.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
There is still problem with inverted QR Code with Google Drive project, after scanning it scanner does not hang, but it is not possible to scan any qr code, steps i used are the same as in issue #6687

**Comment by seadowg** [comment]
Moved this back to a draft. https://github.com/getodk/collect/issues/6755 can replace this for the moment.

**Comment by seadowg** [comment]
This now fixes the issues as described, but there are other cases not accounted for:

1. Scanning a duplicate project QR
2. Scanning invalid/Google Drive codes on the "Reconfigure with QR code" screen

Let's see if there are any more and then I can write some more issues. I don't think it's worth holding this PR up to solve those problems as we should prioritize getting https://github.com/getodk/collect/issues/6762 out in a beta.

File: collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt [hunk 2]
```diff
@@ -171,6 +179,9 @@ class QrCodeProjectCreatorDialogTest {
             )
         )
         verifyNoInteractions(projectCreator)
+
+        scheduler.runForeground()
+        assertThat(barcodeScannerViewFactory.isScanning, equalTo(true))
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt:184]: I think we should update the titles of these two tests to include `...and scanning is continued.`

File: qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt [hunk 3]
```diff
@@ -39,13 +39,19 @@ class BarcodeScannerViewContainer(context: Context, attrs: AttributeSet?) :
 }
 
 abstract class BarcodeScannerView(context: Context) : FrameLayout(context) {
-    protected abstract fun decodeContinuous(callback: (String) -> Unit)
+    private val latestBarcode = MutableLiveData<String>()
```
Comment (grzesiek2010) [inline qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt]: Can we follow the same convention we use elsewhere, like:

```kotlin
private val _latestBarcode = MutableLiveData<String>()
val latestBarcode: LiveData<String> = _latestBarcode
```
instead of using a function to expose `latestBarcode`?

File: test-shared/src/main/java/org/odk/collect/testshared/FakeBarcodeScannerView.kt [hunk 4]
```diff
@@ -35,6 +41,11 @@ class FakeBarcodeScannerViewFactory : BarcodeScannerViewContainer.Factory {
 
     private val views = mutableListOf<FakeBarcodeScannerView>()
 
+    val isScanning: Boolean
+        get() {
```
Comment (grzesiek2010) [inline test-shared/src/main/java/org/odk/collect/testshared/FakeBarcodeScannerView.kt]: This could be just:
`get() = views.any { it.isScanning }`

**Comment by dbemke** [comment]
I'm not able to scan the first QR code (to add a project) on Redmi 9T Android 10 unless it's a new Central-made QR code. I don't know why it's the only device that does that (e.g. Android 8.1 is able to scan the codes). I tried to scan QR codes made by Collect 2024 and 2025 - project isn't added. If I reopen the scanner it works as expected, or if the QR codes are scanned later on (not as the first one) it works as expected.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
> If I reopen the scanner it works as expected, or if the QR codes are scanned later on (not as the first one) it works as expected.

So you can add a project later via the "Add project" button, but can't do it from the welcome first launch screen? Have you checked the store version with that device?

**Comment by dbemke** [comment]
> So you can add a project later via the "Add project" button, but can't do it from the welcome first launch screen? Have you checked the store version with that device?

I works if I even reopen the scanner in the welcome first launch screen. Which store version exactly? I lost track which camera version is on which version

**Comment by seadowg** [comment]
> Which store version exactly? I lost track which camera version is on which version

The last release: v2025.1.5.

**Comment by dbemke** [comment]
> The last release: v2025.1.5.

2025.1.5 - scans the codes as expected

**Comment by seadowg** [comment]
@dbemke could you write up an issue please?

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15

**Verified cases:**
- Issue #6687 does not occur

Other connected issue are filed separate

**Comment by dbemke** [comment]
**Tested with success**

Verified on device with Android 10
