### PR TITLE
Fix crash when rotating shape/trace screen

### LINKED ISSUE #7066: Crash on OSM after rotating the screen with incremental=true
**ODK Collect version**
the master version 536d3dbd7c65e4986d952d85c99fbf05e3757b60

**Android version**
12,14 

**Device used**
Pixel 3a, Samsung Galaxy M23

**Problem description**

It's similar to this one: https://github.com/getodk/collect/issues/6999, 
but here it's happening using Placement by tapping. 
There's a crash after adding points in GeoTrace or GeoShape and rotating the screen on a question with incremental=true only in OSM

https://github.com/user-attachments/assets/40dacb61-87bb-41db-83d4-e31c9f016b0c

**Steps to reproduce the problem**

1. Scan user: Invalid Polygons new forms  https://test.getodk.cloud/projects/681/app-users
2. Go to geoshape/ geotrace - not intersects + area constraint question.
3. Open the map and add some points using Placement by tapping method. 
4. Rotate the screen few times -> if you can't reproduce it **Make sure that last added point intersects with others**

**Expected behavior**
App should not crash

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7066

#### Why is this the best possible solution? Were any other approaches considered?

There were a couple of features of the code that causes this issue:
1. The `invalidMessage` object passed to `GeoPolyFragment` was the product of `LiveData` which had been created via a `map` that referenced `getString` - implicitly requiring the `Fragment` where it was executed.
2. That `LiveData` is then passed to a `ViewModel` meaning it would be retained between configuration changes - the "original" instance would be reused, and the new one created as part of recreation would effectively be ignored

Combining 1 with 2 gets you a crash as re-executing the `map` operation after recreation requires a `Fragment` that's been destroyed.

1 was definitely an issue - `map` operations should never have side-effects and shouldn't rely on life-cycleable objects. I did also consider changing 2, but alternatives (like using a mediator that both ViewModels could share) felt over-architected. I think this is just a quirk of any stateful view component (be it a Fragment or a Composable or a View): initial state will be ignored when the component is recreated.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue. No maps code has been touched.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 1]
```diff
@@ -65,9 +66,12 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
             retainMockAccuracy,
             inputPolygon,
             constraintValidationResult.map {
-                val validationResult = it.value
-                if (validationResult is FailedValidationResult && validationResult.index == prompt.index) {
-                    validationResult.customErrorMessage ?: getString(validationResult.defaultErrorMessage)
+                if (it is FailedValidationResult && it.index == prompt.index) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt]: @grzesiek2010 I don't think we need the index check here any longer right?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt]: Yes, it seems to be redundant now.

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/DisplayString.kt [hunk 2]
```diff
@@ -0,0 +1,16 @@
+package org.odk.collect.androidshared.ui
+
+import android.content.Context
+
+sealed class DisplayString {
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/ui/DisplayString.kt:5]: @grzesiek2010 please let me know if I've already created this abstraction! I've definitely used it on other Android projects.

File: collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt [hunk 3]
```diff
@@ -505,36 +502,35 @@ class GeoPolyDialogFragmentTest {
...
             bundleOf(ARG_FORM_INDEX to prompt.index)
         ) {
-            assertThat(it.invalidMessage.getOrAwaitValue(), equalTo("blah"))
+            assertThat(it.invalidMessage.getOrAwaitValue(), equalTo(DisplayString.Resource(R.string.cancel)))
         }
     }
 
+    /**
+     * This scenario can cause a crash if there's a [androidx.fragment.app.Fragment.getString]
+     * call the evaluation chain for however [GeoPolyDialogFragment] or its children deal with
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragmentTest.kt]: ...call **IN** the evaluation...

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/DisplayString.kt (hunk 2 above)
Comment (grzesiek2010) [reply androidshared/src/main/java/org/odk/collect/androidshared/ui/DisplayString.kt:5]: I don't remember anything like that.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified cases:**
- issue #7066 doesn't occur
- rotating and adding points in geoshape and geotrace with and without `incremental=true ` in Google Maps, OSM, Mapbox

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 14

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16
