### PR TITLE
Fixed adding offline layers

### LINKED ISSUE #5236: Offline layers do not work with mapbox + satellite
#### ODK Collect version
v2022.3.0

#### Problem description
Offline layers do not work with mapbox + satellite

#### Steps to reproduce the problem
1.  Select mapbox + sattelites in Settings -> Maps
2.  Add and select the attached offline layers: [test.zip](https://github.com/getodk/collect/files/9251248/test.zip)
3. Open any map view and navigate to Corsica

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5236 

#### What has been done to verify that this works as intended?
I've verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
Adding offline layers is a bit problematic we have to add them above style layers (such a layer might consist of over 100 layers like streets for example) but below layers that represent points/lines (to keep points and lines visible) etc. The previous solution attempted to remember the index of the top style layer but it was faulty and selected offline layer was added below the last of layers that selected style layer consisted of. The current solution with using ids instead of indexes works well.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify the case described in the issue and generally changing styles and offline layers. There is no need to test other providers than Mapbox.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt [hunk 1]
```diff
@@ -95,7 +95,7 @@ class MapboxMapFragment :
     private var tileServer: TileHttpServer? = null
     private var referenceLayerFile: File? = null
     private var clientWantsLocationUpdates = false
-    private var offlineLayerPosition = -1
+    private var topStyleLayerId = ""
```
Comment (seadowg) [inline mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt]: Could this just be a nullable type? That would enforce that we don't use it before it's set.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt (hunk 1 above)
Comment (grzesiek2010) [reply mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt]: It could be but I can't see any benefit in this case. Could you explain why it's better to you? It's always set before we use it. Even if it's not set we do not block adding offline layers.

Comment (seadowg) [reply mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt]: Ah will it not matter if we pass `""` to `addLayerAbove`?

Comment (grzesiek2010) [reply mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt]: It shouldn't I guess but ok let's not do that.

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**
Verified on Androids: 5.1, 10, 12

**Verified Cases:**

- Issue #5236  is no longer reproducing;
- Regression checks on GeoWidgets for Mapbox;
- Select Map forms;
- Changing map styles;
- Offline Layers in Collect and Project folder + Attached Layer;
- View Submission on map and sending submission to Central;
- Collecting Location in Background;
- External map widgets;
- Quick regression check on Google Maps and OSM
- screen rotation, minimize app, using backward button
- Light and Dark mode;

**Comment by dbemke** [comment]
**Tested with Success!**
Verified on Androids: 8.1, 11

 Issue #5240 still occurs on Android 11
