### PR TITLE
Setting to prevent backwards movement can be bypassed

### LINKED ISSUE #1675: Setting to prevent backwards movement can be bypassed
#1457 added a setting to prevent backwards movement in forms. From @kkrawczyk123, this can be bypassed under certain conditions:
- When minimizing throws user out to main collect menu, it happens sometimes but it can be difficult to reproduce.
- The same happens when user restart phone or turn it off during filling form which user can do accidentally.
- In case of incoming call during filling form.
- And when user’s phone discharge during filling survey.

I believe this is all because it then recovers from a savepoint and displays the hierarchy view/jump screen, allowing the user to select an arbitrary question to start from.

What are options for preventing this? Can we find out the last question that was edited and go straight there?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1675 

#### What has been done to verify that this works as intended?
I've tested that scenario when the form is recovered from a savepoint and I can confirm that we are moved to the last know question if the `allow moving backwards` option is disabled.

#### Why is this the best possible solution? Were any other approaches considered?
It's the only solution I was able to imagine. It's also pretty easy.

#### Are there any risks to merging this code? If so, what are they?
It doesn't change existed behavior much so it should be safe. It saves and reads FormIndex from a file only if the `allow moving backwards` option is disabled. 
I've also added a test case for saving and reading FormIndex.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java [hunk 1]
```diff
@@ -239,6 +241,14 @@ public static File savepointFile(File instancePath) {
         return new File(tempDir, instancePath.getName() + ".save");
     }
 
+    /**
+     * Return the name of the savepoint formIndex file for a given instance.
+     */
+    public static File savepointFormIndexIndexFile(File instancePath) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: Looks like an extra `Index`. The name should ideally capture what this does. `getFormIndexFile`?

The comment is also inaccurate since this returns the `File` itself. You can also pass in `String instancePathName` rather than the file. Seems it might go better in `SaveFormIndexTask`.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java [hunk 2]
```diff
@@ -129,8 +129,10 @@ protected SaveResult doInBackground(Void... nothing) {
 
             // attempt to remove any scratch file
             File shadowInstance = savepointFile(formController.getInstancePath());
+            File shadowFormIndex = savepointFormIndexIndexFile(formController.getInstancePath());
             if (shadowInstance.exists()) {
                 FileUtils.deleteAndReport(shadowInstance);
+                FileUtils.deleteAndReport(shadowFormIndex);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: Just because the instance savepoint exists doesn't mean this file will.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java [hunk 3]
```diff
@@ -41,10 +43,12 @@
 
     private final SavePointListener listener;
     private int priority;
+    private FormIndex formIndex;
 
-    public SavePointTask(SavePointListener listener) {
+    public SavePointTask(SavePointListener listener, FormIndex formIndex) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: It feels unfortunate to give this another responsibility that's not really related and to have to deal with null `formIndex`? Could it be its own `SaveFormIndexTask` that's only scheduled when needed?

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: I realize that this is by analogy to `savepointFile` but that one didn't really make sense either.

**Review by lognaturel — COMMENTED** [review]
All of the classes you're working with are pretty tangled so this is tricky (not your fault -- I mean the existing code). I think it would help to keep the index writing separate from the savepoint writing and I've given some suggestions for that inline.

What are the tests actually testing? It's not clear to me that they test different things. What changes between the different tests is the `FormIndex` that's saved but I don't think there are any difference in your code that are exercised by those changes, right?

The things that seem important to test for this are:
- is the form index saved **when swiping backwards is disabled**
- is the form index restored **when swiping backwards is disabled**
- is the form index ignored **when swiping backwards is enabled**

Unfortunately I don't think there's any straightforward way to write those with the current structure.

**Comment by lognaturel** [comment]
@grzesiek2010 Once you've looked over my suggestions and made the changes you think make sense, please tag for testing!

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: Yes we shouldn't check for existing here at all since it's checked here: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java#L398

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: I fixed naming and comments.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: In my opinion, FormIndex is a part of savepoint so it should be saved in the same task. I decided to leave it and we can refactor the code in the future if you really want (an if you can explain why :smile: )

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs-testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"
@opendatakit-bot unlabel "needs review"

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.

@opendatakit-bot unlabel "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java (hunk 3 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: It's a single responsibility thing. When I start seeing parameters added to constructors, `null`s being passed in and conditionals both in the class and in the clients it feels like we've gone from SavePointTask to SavePointAndIndexTask which feels like a red flag. Again, I understand all of this code is messy to start with so it's hard to know where to try to be principled. @jknightco would love your opinion on this.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: Even better.

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+import org.odk.collect.android.logic.FormController;
+import org.odk.collect.android.tasks.SaveToDiskTask;
+
+import java.io.File;
+
+import static org.junit.Assert.assertEquals;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+@RunWith(AndroidJUnit4.class)
```
Comment (heyjamesknight) [inline collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: You can use the Mockito runner and then you won't have to manually call mock() in your `@Before`.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 5]
```diff
@@ -600,7 +600,7 @@ protected void onSaveInstanceState(Bundle outState) {
                         formController.getXPath(waiting));
             }
             // save the instance to a temp path...
-            nonblockingCreateSavePointData();
+            nonblockingCreateSavePointData(allowMovingBackwards ? null : formController.getFormIndex());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: This line is difficult to read.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java (hunk 3 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: Agreed with @lognaturel, the way the code runs now is that a SavePointTask has a FormIndex if in a single place `allowMovingBackwards` is false, otherwise (the other two places its called) it doesn't. Basically we're delaying the logical conclusion of if we `allowMovingBackwards` through a method call, a constructor, and finally a null check. This is the kind of stuff that breaks down the line when more changes get made.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 6]
```diff
@@ -2062,27 +2062,24 @@ public void onClick(DialogInterface dialog, int id) {
...
-                .getFormController();
+        FormController formController = Collect.getInstance().getFormController();
 
         // attempt to remove any scratch file
-        File temp = SaveToDiskTask.savepointFile(formController
-                .getInstancePath());
-        if (temp.exists()) {
-            temp.delete();
-        }
+        File tempInstanceFile = SaveToDiskTask.getSavepointFile(formController.getInstancePath().getName());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:2073]: Should this chunk maybe be the responsibility of the SaveToDiskTask? It seems weird to pull the `File`s out and then delete them here.

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+public class FormIndexSavepointTest {
+
+    private File instancePath;
+
+    @Before
+    public void setUp() {
+        instancePath = new File(Collect.INSTANCES_PATH + File.separator + "test.xml");
```
Comment (heyjamesknight) [inline collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: Where does `test.xml` live? Does this test only work if `test.xml` is present on the emulator/device where its being run?

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+        FormController formController = mock(FormController.class);
+        when(formController.getInstancePath()).thenReturn(instancePath);
+        Collect.getInstance().setFormController(formController);
+    }
+
+    @Test
+    public void testBeginningOfForm() {
+        FormIndex originalFormIndex = FormIndex.createBeginningOfFormIndex();
```
Comment (heyjamesknight) [inline collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: Can you describe what these tests do? Either via a comment or by changing the name of the test?

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+        TreeReference treeReference = TreeReference.rootRef();
+        FormIndex originalFormIndex = new FormIndex(1, 2, treeReference);
+        File tempIndex = SaveToDiskTask.getFormIndexFile(instancePath.getName());
+        FileUtils.exportFormIndexToFile(originalFormIndex, tempIndex);
+
+        FormIndex readFormIndex = FileUtils.loadFormIndexFromFile();
+        assertFormIndex(originalFormIndex, readFormIndex);
+    }
+
+    private void assertFormIndex(FormIndex expected, FormIndex actual) {
```
Comment (heyjamesknight) [inline collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: Should this be `assertFormIndexesEqual?`?

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java [hunk 10]
```diff
@@ -128,10 +128,10 @@ protected SaveResult doInBackground(Void... nothing) {
             exportData(markCompleted);
 
             // attempt to remove any scratch file
-            File shadowInstance = savepointFile(formController.getInstancePath());
-            if (shadowInstance.exists()) {
-                FileUtils.deleteAndReport(shadowInstance);
-            }
+            File shadowInstance = getSavepointFile(formController.getInstancePath().getName());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java:131]: So yeah, the SaveToDiskTask also performs this. This should probably be a method that gets called both places rather than duplicated code.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java [hunk 11]
```diff
@@ -232,11 +232,19 @@ private void updateInstanceDatabase(boolean incomplete, boolean canEditAfterComp
     }
 
     /**
-     * Return the name of the savepoint file for a given instance.
+     * Return the savepoint file for a given instance.
+     */
+    public static File getSavepointFile(String instanceName) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java:237]: Is it totally necessary for this to be exposed?

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java [hunk 12]
```diff
@@ -70,6 +74,11 @@ protected String doInBackground(Void... params) {
                 // write out xml
                 SaveToDiskTask.exportXmlFile(payload, temp.getAbsolutePath());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: If we're pulling `temp` out of SaveToDiskTask just to pass it back in we should probably consider an alternative.

File: collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java [hunk 13]
```diff
@@ -317,7 +317,7 @@ private boolean initializeForm(FormDef formDef, FormEntryController fec) {
         boolean usedSavepoint = false;
         if (instancePath != null) {
             File instance = new File(instancePath);
-            final File shadowInstance = SaveToDiskTask.savepointFile(instance);
+            final File shadowInstance = SaveToDiskTask.getSavepointFile(instance.getName());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:320]: This could become a `SaveToDiskTask.doesSavepointFileExistForName()` method.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 14]
```diff
@@ -505,4 +509,29 @@ public static Bitmap getBitmap(String path, BitmapFactory.Options originalOption
         Collections.addAll(mediaFiles, new File(mediaFilesDir).listFiles());
         return mediaFiles;
     }
+
+    public static void exportFormIndexToFile(FormIndex formIndex, File savepointIndexFile) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: I'd like to see fewer static methods in Collect, but its fine for now.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java [hunk 15]
```diff
@@ -505,4 +509,29 @@ public static Bitmap getBitmap(String path, BitmapFactory.Options originalOption
...
+            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(savepointIndexFile));
+            oos.writeObject(formIndex);
+            oos.flush();
+            oos.close();
+        } catch (Exception e) {
+            Timber.e(e);
+        }
+    }
+
+    public static FormIndex loadFormIndexFromFile() {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: If this doesn't require a `savepointIndexFile`, does the other one? I'd prefer to limit our `Collect.getInstance` but if we're only ever saving/loading the current index, shouldn't these calls mirror each other?

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java (hunk 8 above)
Comment (heyjamesknight) [reply collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: So after looking at this more, it seems like the only question these tests answer is "Does `loadFormIndexFromFile()` load the index saved at the current instancePath. There's no reason to expect `ObjectOutputStream`/`ObjectInputStream` to fail, so the only real variable here is our tempIndex file.

I think we can probably do away with all but one of these tests.

**Review by heyjamesknight — CHANGES_REQUESTED** [review]
Great overall improvement, although I agree with @lognaturel regarding the SaveToDiskTask. I also have some questions/suggestions around the tests.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java (hunk 3 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: @jknightco what do you think of introducing a simple `SaveFormIndexTask` that just saves the index and is executed in the one necessary case? Is there another simple alternative you prefer?

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 15 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: I don't understand... it does require but this file is read a few lines below.

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java (hunk 7 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: It's just a test file stored in odk/.cache and i use it to save tested form index and then read it.

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java (hunk 9 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: Yes, it's a better name.

File: collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java (hunk 13 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:320]: Why? We want to get a file here.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 10 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java:131]: It's not duplicated. this part is called when you save a form and that from the FormEntryActivity.class when you ignore changes.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:2073]: It's called when you ignore changes not when you save them to disk.

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 11 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java]: Just for testing

**Comment by mmarciniak90** [comment]
**Re-tested with success after last changes!**
Verified on Android 7.0

File: collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java (hunk 10 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java:131]: The 4 lines of code are identical between the two sections, aren't they? We get the savepointFile, get the FormIndexFile, and then call delete on both of them.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java (hunk 15 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java]: Right but the signature of `exportFormIndexToFile` takes the savepointIndexfile, while this one retrieves it from the FormController. Shouldn't they mirror eachother? Is there a use case for specifying a different savepointIndexFile on export?

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java (hunk 7 above)
Comment (heyjamesknight) [reply collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: Right, but if I don't have that file in ODK/.cache these tests will fail, right? The AllWidgetsFormTest shows an example of storing these test files in the test assets and moving them onto disk prior to testing.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 6 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:2073]: Right, which I guess is the bigger issue here: why is information relating to the savePointFile being passed around? Shouldn't we wrap the responsibility for clearing, loading, etc. that file in a single class?

File: collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java (hunk 13 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java:320]: Ah, I see now. The logic here is a bit confusing. Create a new File, get a savepoint file based on its name, then if it exists ignore the old file and use the savepoint "shadow" one (what is a shadow instance?). Can you add some comments explaining why we're overwriting the instance variable and what that means?

File: collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java (hunk 3 above)
Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java]: Sounds like a good call to me.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 6 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java:2073]: The tricky thing is always deciding what details to reveal where. When we have `thing1` and `thing2` that need to happen in sequence do we make two methods? If so, does `thing1` call `thing2` or do we call them sequentially? We've been talking about this on other PRs as well. The goal should be to reduce the mental overhead for a developer coming after you and keep responsibilities as distinct as possible. Granted, this is difficult in a context like `FormEntryActivity` that knows about everything. But we'll increase our chances of making it more livable in the future if we can keep ourselves from giving it more responsibilities.

I think what @jknightco is getting at here is that `FormEntryActivity` doesn't need to have any knowledge of the files themselves. We could have a method like `cleanupTempFiles(formController.getInstancePath().getName())` that abstracts all of that away. Or one level simpler, we could overload `deleteAndReport` to provide a variant that takes in a path or a path name so the file doesn't have to be constructed here.

`SaveToDiskTask` performs this exact same work in lines 131-134.

**Review by lognaturel — APPROVED** [review]
Thanks, @grzesiek2010! This feels a lot less invasive to `FormEntryActivity` which is great.

I'm going to merge this now so it's part of the overall release tests. Then I'm going to try my hand at a couple of small changes to illustrate some of what we've discussed in comments so we can continue developing some shared strategies for code structure together.

File: collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java (hunk 7 above)
Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java]: If it doesn't exist it gets created by the ObjectOutputStream calls.
