### PR TITLE
Fixed problem with daylight saving

### LINKED ISSUE #356: ODK crashes after entering "1 Jan 1960" in Nairobi time zone
#### Software and hardware versions 
Discovered on Collect v1.4.12, Android v5.0.1, Samsung Galaxy S4

#### Problem description
ODK crashes after entering "1 Jan 1960" in Nairobi time zone

#### Steps to reproduce the problem
1. Change time zone to Nairobi (East Africa Time Zone (GMT+03:00))
2. Use DateWidget or DateTimeWidget (if you use DateTimeWidget you have to set time to 00:00)
3. Enter "1 Jan 1960"

#### Actual behavior
ODK crashes.
                                                                           at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
                                                                           at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
                                                                           at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
                                                                           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
                                                                           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:198)
                                                                           at org.joda.time.DateTime.<init>(DateTime.java:397)
                                                                           at org.odk.collect.android.widgets.DateTimeWidget.getAnswer(DateTimeWidget.java:295)
                                                                           at org.odk.collect.android.views.ODKView.getAnswers(ODKView.java:265)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.saveAnswersForCurrentScreen(FormEntryActivity.java:918)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1282)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2789)
                                                                           at android.view.GestureDetector.onTouchEvent(GestureDetector.java:620)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1255)

This has also been reproduced with:
- the Sao Paulo time zone and "16 Oct 2016" as the date ([here](https://github.com/opendatakit/collect/issues/227#issuecomment-275272870), note also the crazy calendar issues which may or may not be related)
- an unspecified time zone and May 01 1990 in issue #145 
- the Peru time zone and "1 Jan 1990/1994/1986/1987" in #217

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #356

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java [hunk 1]
```diff
@@ -372,4 +374,15 @@ public void stopAudio() {
             mPlayer.reset();
         }
     }
+
+    // Today clocks are almost always set one hour back or ahead.
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java]: If I understand correctly, the problem is that on the day of a daylight savings transition, certain times don't exist. For example, if the time change happens at midnight and goes forward an hour, there is no midnight on that day. The problem showed up for timezones that happen to have a change at midnight because that was the default time used. We didn't see it for more "common" timezones because they change their time at 2AM or other odd times.

If I got that right, I think it would useful to add a first sentence to this comment that explains that. For example - "Skip over a "daylight savings gap." This is needed on the day and time of a daylight savings transition because that date/time doesn't exist."

**Review by lognaturel — CHANGES_REQUESTED** [review]

**Review by lognaturel — APPROVED** [review]
