### PR TITLE
Fixed problems with scanning project QR codes

### LINKED ISSUE #6783: Problems scanning project QR codes
There are cases where scanning a QR code won't create a project and the user will need to exit and reenter the scanning screen to resume scanning:

- Scanning a duplicate project QR and then pressing back
- Scanning invalid/Google Drive codes on the "Reconfigure with QR code" screen

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6783

#### Why is this the best possible solution? Were any other approaches considered?
The solution is consistent with what we introduced recently to address other related issues: https://github.com/getodk/collect/pull/6752

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pull request should resolve the issues it addresses without introducing any side effects. It would be good to test QR code scanning more extensively to check for any similar issues that might not yet be discovered.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt [hunk 1]
```diff
@@ -62,15 +62,21 @@ class QRCodeScannerFragment : BarCodeScannerFragment() {
...
-                getString(
-                    org.odk.collect.strings.R.string.invalid_qrcode
+            ProjectConfigurationResult.INVALID_SETTINGS -> {
+                showLongToast(
+                    getString(
+                        org.odk.collect.strings.R.string.invalid_qrcode
+                    )
                 )
-            )
+                restartScanning()
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt]: This and the other `restartScanning()` call aren't tested. Is there any way we could have a common component shared between this and `QrCodeProjectCreatorDialog` so we don't have to test/implement in two places?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt]: It's not possible to have a shared component that could be tested in one place as the flow differs but I added some tests.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- scanning in adding and reconfiguring a project
- importing QR codes
- adding a duplicate project/ switching to a project
- scanning QR codes and barcodes in the barcode widget
- scanning QR codes and barcodes of different quality
- regression checks in scanning

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 16

**Comment by srujner** [comment]
**Tested with Success!**

Verified on a device with Android 14
