### PR TITLE
Filter out case-insensitive duplicate properties

### LINKED ISSUE #6501: Crash processing Entity List when there are Entity properties with names that are identical except for case
#### ODK Collect version
the master version 90d41ae9a7b0af8d2fddd87cb198dcb233473627
#### Android version
15, 10
#### Device used
Pixel 6a, Redmi 7
#### Problem description
App crashes after refreshing blank forms when there is "P_" entity property.

#### Steps to reproduce the problem
1. Scan user "Cactus" from project https://staging.getodk.cloud/#/projects/103/app-users
2. Go to start new form
3. Refresh list of blank forms
#### Expected behavior
App should not crash after refreshing blank forms

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6501 

#### Why is this the best possible solution? Were any other approaches considered?
The real issue here is that SQLite is case-insensitive, so attempting to add columns with names like `col` and `Col` results in an exception. I don't think we need to implement any special handling for this, as it doesn't make much sense to add such properties in the first place. Therefore, I believe filtering out duplicates is a good solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be enough to test entities with duplicate properties like `col` and `Col`.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt [hunk 1]
```diff
@@ -36,4 +37,19 @@ class DatabaseEntitiesRepositoryTest : EntitiesRepositoryTest() {
         repository.save("things", savedEntity)
         assertThat(repository.getEntities("things")[0], sameEntityAs(savedEntity))
     }
+
+    @Test
+    fun `#save ignores case-insensitive duplicate properties`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt]: From the conversation on Slack, it looks like we want this to be a feature of entities in general, so I think this should move to `EntitiesRepostitoryTest`.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Comment by seadowg** [comment]
Marking this as "needs testing" early as the requested changes are just for tests.

**Comment by lognaturel** [comment]
In that Slack conversation, I had some questions about whether we should do this at all given how surprising the outcome is. 

I think our only real alternative would be to throw an exception when processing. The advantage of an exception is that it would at least tell the user that something unexpected happened. But given that we're very likely going to address the issue on the server side, this case would only be for other hypothetical servers. Let's go with it.

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 15

**Verified cases:**

- Adding different entity properties by "+new" button
- Adding different entity properties by uploading form with new properties

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10
