### PR TITLE
Fix audio playback crashes

### LINKED ISSUE #6085: Occasional crash in form with many audio questions that autoplay
#### ODK Collect version
v2024.1.0 - v2024.1.3 ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/04af9a6161835d2221134d97d1479a0a?time=last-ninety-days&types=crash&sessionEventKey=660F9F2E025D0001163775502B98BE34_1935004671239229137))

#### Android version
87% Android 13 since start (but also some 9, 12, 14 so maybe it's just the devices that happen to have forms that trigger this)

#### Device used
91% Samsung since start, reported by a user with a fleet of `Galaxy Tab S7 5G`, 82% of occurrences are with `Galaxy Tab Active3` (probably just happens to be those devices that have forms that trigger this)

#### Problem description
A user reports seemingly-random crashes while navigating through the section of a form that is many select questions with autoplay audio media. Users don't see any crash message when Collect restarts.

<details>
<summary>Crashlytics shows two stacktraces from crashes from `mediaplayer.prepare` and `mediaplayer.setDataSource`</summary>
```javarosa
Fatal Exception: java.lang.IllegalStateException:
       at android.media.MediaPlayer._prepare(MediaPlayer.java)
       at android.media.MediaPlayer.prepare(MediaPlayer.java:1435)
       at org.odk.collect.audioclips.AudioClipViewModel.loadNewClip$lambda$3(AudioClipViewModel.kt:26)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```

```javarosa
Fatal Exception: java.lang.IllegalStateException:
       at android.media.MediaPlayer._setDataSource(MediaPlayer.java)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1251)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1234)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1188)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
       at org.odk.collect.audioclips.AudioClipViewModel.loadNewClip$lambda$3(AudioClipViewModel.kt:23)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```
</details>

We always call
```
mediaPlayer.reset()
mediaPlayer.setDataSource(uri)
mediaPlayer.prepare()
```

which should put the player in the correct states according to [the state diagram](https://developer.android.com/reference/android/media/MediaPlayer#StateDiagram).

#### Steps to reproduce the problem
It can't be reproduced systematically.

I've used [audio crash.zip](https://github.com/getodk/collect/files/14950890/audio.crash.zip) to try to reproduce but can't.

#### Expected behavior
No crash.

#### Other information 
Presumably introduced by https://github.com/getodk/collect/pull/5836/files#diff-dd7070cc2905fbf7e644eac39e7590ff53ccf92fc0dfb39512a55315099e9619

I'm opening this issue to have a record of what we've considered/discovered here. I think it's likely there's some weird Samsung-Android 13 platform bug that we're hitting so I don't think we need to take immediate action.

Another idea is that mediaplayer is not threadsafe. Is there a way we could somehow be calling mediaplayer methods from different threads under some conditions?

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6085 

#### Why is this the best possible solution? Were any other approaches considered?

Our only theory for why the crash happens is that `MediaPlayer` is able to get into weird states because we set it up on a background thread. The fix here is just to wrap `MediaPlayer` in a simplified interfaced that only allows one thread at a time to call methods that mutate the internal state.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

We don't have reproduction steps for the crash, so the main focus here is just to check that audio playback in the app still works as expected.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by dbemke** [comment]
I think I managed to reproduce it. There's a crash without any information in the launch screen. If I find  more info I'll edit the post.
**Steps to reproduce:**
1. Open the form.
[audioAutoplayrepeat.xlsx.txt](https://github.com/user-attachments/files/21404739/audioAutoplayrepeat.xlsx.txt)
audio: https://drive.google.com/drive/u/1/folders/1IeuxQZU8Sw90PAOnTRlMToB3Wp_LuCoN
2. Swipe to following question and add repeats.

**Comment by seadowg** [comment]
@dbemke is with or without the PR changes?

**Comment by dbemke** [comment]
> is with or without the PR changes?

I reproduced it on the master and the store version. I just checked this form on the PR and the issue hasn't occurred.

File: audio-clips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt [hunk 1]
```diff
@@ -162,11 +159,13 @@ class AudioClipViewModel(private val mediaPlayerFactory: Supplier<MediaPlayer>,
...
         positionUpdatesCancellable = scheduler.repeat(
             {
-                _mediaPlayer?.let {
-                    val currentlyPlaying = currentlyPlaying.value
-                    if (currentlyPlaying != null) {
-                        val position = getPositionForClip(currentlyPlaying.clip.clipID)
-                        position.postValue(it.currentPosition)
+                val currentlyPlaying = currentlyPlaying.value
+                if (currentlyPlaying != null) {
+                    val position = getPositionForClip(currentlyPlaying.clip.clipID)
```
Comment (grzesiek2010) [inline audio-clips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt:165]: This could be moved down so that it is only set up if `currentPosition != null`.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
I'm not sure if it's exactly the same case but it seems similar - if it's the same is it expected that there's an error instead of the crash?
errorAudio

**Comment by seadowg** [comment]
@dbemke that looks like a different bug. Could you file it separately?

**Comment by dbemke** [comment]
> Could you file it separately?

Ok. I'll file an issue when I figure out a way to reproduce it.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6085 doesn't occur
- different form with autoplay in selects, on a field-list and in repeats
- different forms with missing audio media + media update
- regression checks in audio

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15
