### PR TITLE
Stop running `ExistingProjectMigrator` incorrectly

### LINKED ISSUE #4927: Demo project is duplicated after updating app
#### Software and hardware versions 
Collect v2021.3 Android all device used...

#### Problem description
When testing Collect's update I have noticed that demo project is duplicated when it's used before updating app.
ezgif com-gif-maker (14)

#### Steps to reproduce the problem
1. Install Collect ex. v2021.3.1
2. Use demo project
3. Update Collect to v2021.3.2
4. See that you have 2 demo projects

#### Expected behavior
Projects should not be duplicated when updating the app. 

#### Other information 
I have tried also app update when using other project - demo project is also created but it's not a duplicate then.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4927

This brings over the fix made in #4928 to `master` and also restructures the upgrade code to prevent similar issues in the future and to isolate it from the rest of the app (in a new module).

This also includes a bunch of changes to our CI JVM configuration as the other changes in this PR for some reason aggravated some OOM problems we'd seen before.

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue. Good to check upgrades as it's hard to write tests that cover a full app upgrade.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/activities/viewmodels/SplashScreenViewModelTest.kt [hunk 1]
```diff
@@ -8,21 +8,18 @@ import org.mockito.Mockito.`when`
...
 import org.odk.collect.android.preferences.keys.ProjectKeys
 import org.odk.collect.android.preferences.source.SharedPreferencesSettings
-import org.odk.collect.android.utilities.LaunchState
 import org.odk.collect.projects.Project
 import org.odk.collect.projects.ProjectsRepository
 
 class SplashScreenViewModelTest {
 
     private lateinit var generalSettings: SharedPreferencesSettings
-    private lateinit var launchState: LaunchState
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/activities/viewmodels/SplashScreenViewModelTest.kt:18]: Not sure why this was here. Probably in use at some point.

File: upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+                if (key == null) {
+                    it.run()
+                } else if (!settings.getBoolean(key)) {
+                    it.run()
+                    settings.save(key, true)
+                }
+            }
+        } else {
+            upgrades.forEach {
```
Comment (seadowg) [inline upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt:44]: Doing this protects us from running into the problems we ran into with `ExistingProjectMigrator` with any other "run once" upgrades we add in the future. We don't need it at the moment, but I wanted to include the functionality now while we're thinking about it as it'll be easy to forget about later.

File: upgrade/src/main/java/org/odk/collect/upgrade/Upgrade.kt [hunk 3]
```diff
@@ -0,0 +1,13 @@
+package org.odk.collect.upgrade
+
+interface Upgrade {
+
+    /**
+     * If this returns a non-`null` value, the [Upgrade] will only be run once (the next app
+     * upgrade). [Upgrade] implementations that return `null` from [Upgrade.key] will be run on
+     * every app upgrade.
+     */
+    fun key(): String?
```
Comment (seadowg) [inline upgrade/src/main/java/org/odk/collect/upgrade/Upgrade.kt:10]: @grzesiek2010 hopefully this makes more sense now? If not, let's try and work out something we both like!

File: buildSrc/src/main/java/dependencies/Dependencies.kt [hunk 4]
```diff
@@ -91,7 +91,7 @@ object Dependencies {
     const val okhttp3_mockwebserver = "com.squareup.okhttp3:mockwebserver:${Versions.okhttp3}"
     const val kotlinx_coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.2"
     const val hamcrest = "org.hamcrest:hamcrest:2.2"
-    const val robolectric = "org.robolectric:robolectric:4.5.1"
-    const val robolectric_shadows_multidex = "org.robolectric:shadows-multidex:4.5.1"
+    const val robolectric = "org.robolectric:robolectric:4.7.3"
```
Comment (seadowg) [inline buildSrc/src/main/java/dependencies/Dependencies.kt]: This fixes some memory leaks caused by Robolectric

**Review by lognaturel — APPROVED** [review]
I'll admit that I'm still warming up to everything becoming a micro-framework! The balance between isolation and not getting lost in abstraction/many layers is tricky. I mostly focused on the tests to get confidence that the layers do what they're supposed to. I read through the commits and the code. All looks good to me.

I think it would be good for @grzesiek2010 to take a look as well, at least around the question asked to him. @grzesiek2010 please mark as ready for QA when you're ready.

**Comment by lognaturel** [comment]
One idea would be to QA this on `master` so we can verify all the fiddly upgrade path stuff carefully once as part of regression testing rather than twice?

**Comment by seadowg** [comment]
> One idea would be to QA this on master so we can verify all the fiddly upgrade path stuff carefully once as part of regression testing rather than twice?

That sounds good to me. What do you think @kkrawczyk123?

File: collect_app/src/test/java/org/odk/collect/android/activities/viewmodels/SplashScreenViewModelTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/activities/viewmodels/SplashScreenViewModelTest.kt:18]: probably

**Comment by grzesiek2010** [comment]
> I think it would be good for @grzesiek2010 to take a look as well, at least around the question asked to him. @grzesiek2010 please mark as ready for QA when you're ready.

I'm on it, will be done today/tomorrow morning.

**Comment by seadowg** [comment]
I've made this a draft while I pull out the CI tweaks to a different PR

File: collect_app/src/main/java/org/odk/collect/android/application/initialization/upgrade/BeforeProjectsInstallDetector.kt [hunk 5]
```diff
@@ -0,0 +1,22 @@
+package org.odk.collect.android.application.initialization.upgrade
+
+import android.content.Context
+import androidx.preference.PreferenceManager
+import org.odk.collect.android.utilities.FileUtils
+import org.odk.collect.upgrade.InstallDetector
+import java.io.File
+
+class BeforeProjectsInstallDetector(private val context: Context) : InstallDetector {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/application/initialization/upgrade/BeforeProjectsInstallDetector.kt:16]: I think it would be good to have a comment that explains what that `BeforeProjectsInstall` means. Now we know it but in the future who knows... you can explain it a bit and include version name that was the first one with projects.

File: upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+interface LaunchState {
+    fun isUpgradedFirstLaunch(): Boolean
+    fun appLaunched()
+}
+
+class VersionCodeLaunchState(
+    private val key: String,
+    private val settings: Settings,
+    private val currentVersion: Int,
+    private val installDetector: InstallDetector? = null
```
Comment (grzesiek2010) [inline upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt]: Why is this nullable?

File: upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+            return installDetector?.installDetected() ?: false
+        }
+    }
+
+    override fun appLaunched() {
+        settings.save(key, currentVersion)
+    }
+}
+
+interface InstallDetector {
```
Comment (grzesiek2010) [inline upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt:30]: Why did you put this interface here? I think we usually would do that in the same class with its implementation if it has only one implementation.

File: collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java [hunk 8]
```diff
@@ -584,17 +580,33 @@ public ExistingSettingsMigrator providesExistingSettingsMigrator(ProjectsReposit
     }
 
     @Provides
-    public AppUpgrader providesAppUpgrader(SettingsProvider settingsProvider, ExistingProjectMigrator existingProjectMigrator, FormUpdatesUpgrade formUpdatesUpgrade, ExistingSettingsMigrator existingSettingsMigrator) {
-        return new AppUpgrader(settingsProvider.getMetaSettings(), asList(
+    public AppUpgrader providesAppUpgrader(Context context, SettingsProvider settingsProvider, ExistingProjectMigrator existingProjectMigrator, FormUpdatesUpgrade formUpdatesUpgrade, ExistingSettingsMigrator existingSettingsMigrator) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java]: Is this used anywhere?

File: upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+) {
+    constructor(
+        key: String,
+        settings: Settings,
+        versionCode: Int,
+        installDetector: InstallDetector,
+        upgrades: List<Upgrade>
+    ) : this(
+        settings,
+        VersionCodeLaunchState(key, settings, versionCode, installDetector),
```
Comment (grzesiek2010) [inline upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt:19]: Wouldn't it be better to pass it as a parameter then you wouldn't need this secondary constructor at all.

File: upgrade/build.gradle [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+    testOptions {
+        unitTests {
+            includeAndroidResources = true
+        }
+    }
+}
+
+dependencies {
+    implementation Dependencies.androidx_core_ktx
+    implementation project(path: ':shared')
```
Comment (grzesiek2010) [inline upgrade/build.gradle:47]: You can skip `path: ` we use both versions it would be good to choose one and use across the app.

Comment (grzesiek2010) [inline upgrade/build.gradle]: You can skip path: we use both versions it would be good to choose one and use across the app.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
Generally it looks good, a few comments from me and conflicts to solve.

File: upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt (hunk 7 above)
Comment (seadowg) [reply upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt:30]: The `upgrade` module owns the interface here - `LaunchState` and `BeforeProjectsInstallDetector` both depend on `InstallDetector`. In Java, I'd probably have given this its own file but I kind of like it just sitting beside the place that needs it in Kotlin?

File: upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt (hunk 9 above)
Comment (seadowg) [reply upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt:19]: The idea here is that we can keep `LaunchState` and `VersionCodeLaunchState` internal to `upgrade` - dependent modules don't need to know anything about them and can just pass in an `InstallDetector` etc. I intended to make `LaunchState` etc `internal` to make use of this but completely forgot. I've taken care of that now, so it's hopefully clear what the benefit of the secondary "convenience" constructor is.

File: upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt (hunk 7 above)
Comment (grzesiek2010) [reply upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt:30]: But if `BeforeProjectsInstallDetector` was in `upgrade` module you would probably put that interface there since it's the only implementation?
Is there any reason why `BeforeProjectsInstallDetector` is not there (in `upgrade` module) it seems like it is not coupled with any other modules so it could be I guess?

File: upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt (hunk 9 above)
Comment (grzesiek2010) [reply upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt:19]: I see that makes sense.

File: upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt (hunk 2 above)
Comment (grzesiek2010) [reply upgrade/src/main/java/org/odk/collect/upgrade/AppUpgrader.kt:44]: Now I understand it especially that you added this comment but it would be good to have a short comment in that class as well because it is really confusing and I think without it  we might want to remove this code next time we touch this class because at first glance it seem s like fomenting we do not need.

File: upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt (hunk 7 above)
Comment (seadowg) [reply upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt:30]: It could be moved to `upgrade` given that there are no logical dependencies between `BeforeProjectsInstallDetector` and anything else in `collect_app`, but for me `BeforeProjectsInstallDetector` is "Collect specific" code whereas `upgrade` could work with any Android app(theoretically). I'd see it as a domain split. In other words, by exposing the `InstallDetector` interface `upgrade` is saying to `collect_app`: "I need one of these passed to me - you choose how it works".

Comment (grzesiek2010) [reply upgrade/src/main/java/org/odk/collect/upgrade/LaunchState.kt:30]: ok if it's a matter of taste and not something important the one who implemented it (you in this case) can decide so let's leave what you like more.

File: upgrade/src/main/java/org/odk/collect/upgrade/Upgrade.kt (hunk 3 above)
Comment (grzesiek2010) [reply upgrade/src/main/java/org/odk/collect/upgrade/Upgrade.kt:10]: Yes now it's a bit clearer. I'm not sure if it's the best option but probably it would be difficult to implement something simpler but with backwards compatibility at the same time. Let's leave it maybe next time you or me touch that class will be able to improve it.

**Review by grzesiek2010 — APPROVED** [review]
I would add one comment what I described here https://github.com/getodk/collect/pull/4934#discussion_r782125422
but since it's just a comment I'm accepting this pr.
