### PR TITLE
Fixed creating savepoints for saved forms that were started from a blank form (not the list of already saved forms)

### LINKED ISSUE #6051: A form with saveIncomplete creates both a savepoint in a new form and a draft.
#### ODK Collect version
the master version 38a4b0ec4eea71fda685493b3931137b11ec5621
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
A form with saveIncomplete creates both a savepoint (in a form in "Start new form”) and a draft.
The issue doesn’t occur in the store version 2024.1.3 (after creating a savepoint in Start new form the form doesn’t open in the hierarchy view with saved answers).
#### Steps to reproduce the problem
1. Open the form and fill 2 questions.
[saveIncomplete(2).xlsx.txt](https://github.com/getodk/collect/files/14785737/saveIncomplete.2.xlsx.txt)
2. Go to the end page.
3. While at the end page go to settings and change the theme of the app so that a savepoint is created.
4. Check if a draft was created (don’t open it).
5. Go to "Start new form” and open the form.
6. In the recovery dialog choose "Recover”.
7. Save the form as draft.
#### Expected behavior
I’m not sure what should be the expected behavior in this case. In the store version the form was saved as a draft.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6051

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that `FormSession` I used to get a form and an instance from in order to create a savepoint (https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java#L747) was not updated. That means if it was a blank form the instance was always null even after saving such a form. It was only not null after editing such a saved form. As a result, savepoints were created for a blank form even after saving it because the instance object was null.
I don't see any reason why `FormSession` should not be updated once a form changes its state from a blank one to a saved one.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
As I said in the issue once a blank form is saved by a user (by clicking the save icon and continuing filling it) it becomes a saved one and savepoints that are created during filling that form should not be loaded when we start a blank form again. This should just fix the issue and nothing else should be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt [hunk 1]
```diff
@@ -225,6 +225,28 @@ class SavePointTest {
         rule.fillNewForm("two-question-audit.xml", "Two Question")
     }
 
+    @Test
+    fun whenBlankFormStartedThenSavedAndKilled_aSavepointShouldBeCreatedForASavedFormNotForTheBlankOne() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt:229]: Might be good to link to the issue in a comment here as this is pretty specific.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt [hunk 2]
```diff
@@ -37,6 +39,12 @@ class AppStateFormSessionRepository(application: Application) : FormSessionRepos
         getLiveData(id).value = FormSession(formController, form, instance)
     }
 
+    override fun update(id: String, instance: Instance?) {
+        getLiveData(id).value?.let {
+            getLiveData(id).value = FormSession(it.formController, it.form, instance)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt]: Could this just use `copy`? You also shouldn't need to do the live data look up (`getLiveData` twice here).

Same for the `InMemFormSessionRepository`

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt:229]: Done.

File: collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10, 14

**Verified Cases:**
- issue #6051 doesn’t occur
- savepoints after using the save button
- savepoints in saveIncomplete forms
- savepoints in new forms and drafts

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on devices with Android 11
