### PR TITLE
Pull display code out of FormMapViewModel and add Activity-level tests

### LINKED ISSUE #3546: IndexOutOfBoundsException in FormMapActivity.java:65
#### Software and hardware versions 
Collect v1.25.0

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/22688dd6b5390b11013bfb38148dedcd?time=last-seven-days&sessionId=5DF8EBF4000700012C1E0AD753D1A008_DNE_1_v2

`Caused by java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.odk.collect.android.activities.FormMapActivity.onCreate(FormMapActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6609)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3104)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
       at android.app.ActivityThread.access$1000(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)`

### PR DESCRIPTION
**Pull request by lognaturel**
In response to @seadowg's feedback at https://github.com/opendatakit/collect/pull/3447#discussion_r350645070, I have pulled out display-related code from the `FormMapViewModel`.

Incidentally closes #3546 

#### What has been done to verify that this works as intended?
I have added automated tests and clicked around a map for All Widgets for basic manual verification.

#### Why is this the best possible solution? Were any other approaches considered?

I decided to write my own test double for the `MapFragment`. I took a stateful spy approach since these maps are inherently stateful. I'm pretty happy with how it lets me test behavior without being too tightly coupled to the implementation.

I'm not sure I'm super happy with the `map` field of `FormMapActivity` being public and set by the test but I couldn't come up with a great alternative other than using Dagger which y'all know I really try to avoid. The unfortunate thing about this setup is that I can't test configuration changes as far as I can tell. I've put the test in so we don't forget about it but ignored it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This change is isolated to the submission map feature so that's where the risk is. Everything for that feature gets moved around but it should all be supported by tests. The only change to cross-cutting code is adding methods so nothing else is at risk.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any with a geopoint.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java [hunk 1]
```diff
@@ -56,15 +64,45 @@
...
+    @VisibleForTesting public ViewModelProvider.Factory viewModelFactory;
 
     @Override public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
 
         FormsDao dao = new FormsDao();
-        Form form = dao.getFormsFromCursor(dao.getFormsCursor(getIntent().getData())).get(0);
-        viewModel = ViewModelProviders.of(this,
-                new FormMapActivity.FormMapViewModelFactory(form, new DatabaseInstancesRepository())).get(FormMapViewModel.class);
+        Form form = null;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:91]: @grzesiek2010 this is incidentally a fix for #3546 and the one I would recommend if you feel strongly about addressing it before v1.26 goes out with this change.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java [hunk 2]
```diff
@@ -75,9 +113,16 @@
...
-            .addTo(this, R.id.map_container, this::initMap, this::finish);
+        if (map == null) { // tests set their maps directly
+            Context context = getApplicationContext();
+            map = MapProvider.createMapFragment(context);
+        }
+
+        if (map != null) {
+            map.addTo(this, R.id.map_container, this::initMap, this::finish);
+        } else {
+            finish(); // The configured map provider is not available
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:124]: I haven't tested/tried it yet but I think this will address @mmarciniak90's find at https://github.com/opendatakit/collect/pull/3503#issuecomment-567511721.

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java [hunk 3]
```diff
@@ -66,129 +46,126 @@ public String getFormId() {
...
 
+    private void initializeFormInstances() {
         List<Instance> instances = instancesRepository.getAllBy(form.getJrFormId());
-        totalInstanceCount = instances.size();
-        for (Instance instance : instances) {
+
+        // Note: there is currently no way to delete instances from FormMapActivity so this works
+        // because a change in size means a refresh is needed. Compromise because we don't currently
+        // have an easy way to observe database changes.
+        if (mappableFormInstances == null || instances.size() != totalInstanceCount) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: Kind of shady. Any alternative option I looked into -- getting some kind of callback when there's a DB change -- seemed terribly complex for not much gain. @seadowg you may have some ideas.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java [hunk 4]
```diff
@@ -56,15 +64,45 @@
 
     private FormMapViewModel viewModel;
 
-    private MapFragment map;
+    @VisibleForTesting public MapFragment map;
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: I think it would be nice to use a factory for injection here rather the `MapFragment` itself. Google talked about introducing `FragmentFactory` in the near future (https://www.notion.so/Fragments-Past-Present-and-Future-f21afdfc5e5346f9bba1c89707ff3358) so this feels in keeping with where the framework is going as well.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java [hunk 5]
```diff
@@ -56,15 +64,45 @@
...
+        List<Form> forms = dao.getFormsFromCursor(dao.getFormsCursor(getIntent().getData()));
+        if (forms.size() == 1) {
+            form = forms.get(0);
+        } else {
+            // This shouldn't be possible because the instance URI had to be used in the calling
+            // activity but it has been logged to Crashlytics.
+            finish();
+        }
+
+        if (viewModelFactory == null) { // tests set their factories directly
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:101]: Is it possible to do this at field initialization or do we need to be in `onCreate` for some things to work?

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java [hunk 6]
```diff
@@ -0,0 +1,198 @@
...
+    @Test public void startingFormMap_doesNotZoom_ifThereAreNoInstanceMarkers_andLocationIsUnavailable() {
+        ActivityController controller = RobolectricHelpers.buildThemedActivity(FormMapActivity.class);
+        FormMapActivity activity = (FormMapActivity) controller.get();
+
+        TestInstancesRepository testInstancesRepository = new TestInstancesRepository(new ArrayList<>());
+        FormMapViewModel viewModel = new FormMapViewModel(FormMapViewModelTest.testForm1, testInstancesRepository);
+        activity.viewModelFactory = new TestFactory(viewModel);
+        activity.map = new TestMapFragment();
+
+        controller.setup().visible().start().resume();
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java]: `setup` runs all the following method calls here (unless you're meaning to go through the lifecycle twice). I wrote the method 😉.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 4 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: I should perhaps have given a bit more detail here about what I was running into. There's already a static `MapProvider` which uses general settings to build a configurator which can itself build a `MapFragment`. I think that ideally the `MapProvider` wouldn't be static but that will require (some) rework of all the geo components as far as I can see. Is that what you have in mind? Do you think it's appropriate to do here/now?

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 5 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:101]: The content provider URI of the form is passed via intent to the activity. That feels like way too low-level of a concern for `FormMapViewModel` to have which is why I resolved it to a `Form` in `onCreate`. If the `Form` is passed in to the factory constructor, then the factory can't be built at the field initialization. I suppose I could use a setter on the factory? Or do you think the view model should get the form uri?

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java (hunk 6 above)
Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java]: Yikes, thank you! Did I get confused with `create`? I guess this is exactly why `ActivityScenario` is being pushed. Too may newbs like me putting together "creative" lifecycle calls.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: Ah actually it looks [`FragmentFactory`](https://developer.android.com/reference/androidx/fragment/app/FragmentFactory) already exists and can be set on the `FragmentManager`. I'm not too in to the design of it - you basically create a `FragmentFactory` implementation that handles all the Fragments in your app.

I had a quick play with using this approach but I think you're right in that because we have multiple of the way the `MapFragment` is designed (it's not a fragment) this approach wouldn't work. Happy to go with your approach right now I think. Alternatively if you're up for it you could wrap the call to `MapProvider.createMapFragment` in a simple Factory that you can swap out in the test.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 5 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:101]: Nah I think I like the way you have it then. I haven't found a nice way to set these up in `onCreate`. In `FormEntryActivity` I've ended up with `setupViewModels` method to try and seperate it out from all the other `onCreate` logic.

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: I'm probable being dumb but I can work out how you end up with the instance number changing during the lifecycle of this View Model. Does the user not have to leave the map view to delete/add something and then when they come back they'll have a new View Model?

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 4 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: > it's not a fragment

I guess you mean that the concrete classes are `Fragment`s but the interface itself doesn't include anything `Fragment`-like? That is quite odd now that you mention it. And I guess there's no way to require that subclasses be `Fragment`s since there is no `Fragment` interface? Yikes. Not sure what to do about this. It seems like semantically we want something like `MapFragment extends Fragment`. Or maybe `MapFragment` should be more of a fragment container?

> you could wrap the call to MapProvider.createMapFragment in a simple Factory that you can swap out in the test.

That makes sense. Feels a little inception-like (a factory for a provider of factories) but will play with it!

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: > It seems like semantically we want something like `MapFragment extends Fragment`. Or maybe `MapFragment` should be more of a fragment container?

Yeah my first though is that `MapFragment` should extend `Fragment` and should have a `setMap`/`getMap` that takes the interface we currently call `MapFragment` (The interface formerly known as...)

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java (hunk 3 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: This surprised me but it appears that the `ViewModel` is retained when the user goes to the form entry activity. I've done some digging just now and am even more confused. Do you have a reference that describes what you think should happen?

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 4 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: > `MapFragment` should extend `Fragment`

But that's not possible because there's no `Fragment` interface, right? Or am I missing something...

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:67]: I mean we make a MapFragment extends the Android Fragment class and that it can support any of the mapping engines (maybe by using a Fragment container). That's future us's problem though - not for this PR.

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: Ah sorry you can click on an instance and then come back to this page right? That makes sense. The ViewModel will be retained while the Activity is in the back stack.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: Do you have a reference for this? I couldn't find it anywhere. The `Activity` itself gets killed, right?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: After chatting on Slack I think @lognaturel is right. We can get back to this screen after changing the instances so do need to think about reloads!

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java:63]: What I was confused about was just the normal behavior for activities on the back stack. [They live on in a paused state](https://developer.android.com/guide/components/activities/activity-lifecycle) so all this makes sense. I'm not sure what I was getting confused about. Perhaps too much usage of "Don't keep activities."

What @seadowg was unsure about is the flow back to the map because typically exiting `FormEntryActivity` ignores the back stack and goes straight back to the main activity. We made a decision to return to the map on save because we want to enable a map-centric workflow where an enumerator uses the map as their landing place to fill and edit forms.

So I think we're all on the same page, now!

File: collect_app/src/main/java/org/odk/collect/android/instances/DatabaseInstancesRepository.java [hunk 7]
```diff
@@ -25,7 +25,7 @@
 
     @Override
     public Instance getBy(long databaseId) {
-        Cursor c = dao.getInstancesCursorForId("" + databaseId);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instances/DatabaseInstancesRepository.java]: This was such a cheeky line of code 😁. Took me a second to understand what was happening.

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java [hunk 8]
```diff
@@ -31,87 +31,87 @@
...
         List<FormMapViewModel.MappableFormInstance> mappableFormInstances = viewModel.getMappableFormInstances();
 
         assertThat(mappableFormInstances.size(), is(0));
     }
 
     @Test public void getDeletedDateOf_returnsDeletedDate() {
-        FormMapViewModel viewModel = new FormMapViewModel(testForm1, testInstancesRepository);
+        FormMapViewModel viewModel = new FormMapViewModel(TEST_FORM_1, testInstancesRepository);
 
         assertThat(viewModel.getDeletedDateOf(0L), is(1487782554846L));
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java]: Minor nitpick: could the assertion be that it's equal to `testInstance[0].getDeletedDate()` instead. Just a bit hard to track where this value is coming from.

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java [hunk 9]
```diff
@@ -31,87 +31,87 @@
     }
 
     @Test public void getFormTitle_returnsFormTitle() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java:33]: I'm wondering if we can have a data object that encapsulates the form title and id here. I've been feeling like something along those lines would be helpful for decoupling other `ViewModel`s from the `FormController`. I've been strugging to find a simple place to start with this but this feels like it might be it?

**Review by seadowg — APPROVED** [review]
Looking good! Just a nitpick and a suggestion but good to go to QA.

File: collect_app/src/main/java/org/odk/collect/android/instances/DatabaseInstancesRepository.java (hunk 7 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/instances/DatabaseInstancesRepository.java]: Yeah, sorry, not my best work. 😄

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java (hunk 8 above)
Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java]: Thanks, done.

File: collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java (hunk 9 above)
Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java:33]: I struggle a bit with where those kinds of limited façades into domain objects are simplifying vs. obfuscating. In this case, we don't really need the id, it's just being used in a log that perhaps should be cleaned up. The `activity` knows about the `Form` that is being mapped so it might even make more sense to remove those two methods from the view model and have the activity directly get the values it needs from the `Form` object. What do you think?

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java:33]: @lognaturel yeah I like that!

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on device: 4.4, 5.1, 6.0, 7.0, 8.1, 9.0, 10.0
I  didn't notice regression. I wasn't able to reproduce a crash from #3546 but also I didn't notice crash on apk with these changes.

**Verified cases:**
* test cases from regression issue NODK-217 GeoPoint widget
* test cases from regression issue NODK-203 Location widgets
* light/dark mode

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
