### PR TITLE
Catch sqlite exceptions when filter entities

### LINKED ISSUE #6597: Error when trying to access Entity property that doesn't exist
#### ODK Collect version
v2025.1 Beta 3
#### Android version
10, 15
#### Device used
Redmi 7, Pixel 6a
#### Problem description
Error when opening card distribution form after creating entity on blank dataset.
Issue does not occur on store version 

#### Steps to reproduce the problem
**Preconditions**:
 Blank dataset

1. Scan user "2039" from https://test.getodk.cloud/#/projects/557/app-users 
2. Go to start new form
3. Open Voter registration form, fill it and finalize
4. Open card distribution form
#### Expected behavior
Error should not appear when opening card distribution form

### LINKED ISSUE #6600: Crash when filtering entities using an unkown column name
#### Problem description
The app crashes when filtering entities using an expression that checks if another question in a form has no answer, using `undefined` or `null` instead of an empty string. Logic like: `${q0} = undefined`.

```
android.database.sqlite.SQLiteException: no such column: p_undefined (code 1 SQLITE_ERROR): , while compiling: SELECT *, i.rowid
                                                                                                    FROM "peopleUndefined" e, "peopleUndefined_row_numbers" i
                                                                                                    WHERE e._id = i._id AND p_undefined = ?
                                                                                                    ORDER BY i.rowid
```

#### Steps to reproduce the problem
1. Open this form https://staging.getodk.cloud/#/projects/137/forms/peopleUndefined2
2. Try to navigate till the end of it.

#### Expected behavior
There should be no crash. We can't optimize such filters that reference other questions, as the SQLite queries we build for optimization rely solely on the entities database.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6600 
Closes #6597 

#### Why is this the best possible solution? Were any other approaches considered?
For: #6600 
When a filter applied to entities contains an expression referencing another question, we cannot build an optimized SQLite query. Instead, we need to fall back to Javarosa, which has all the necessary knowledge to evaluate such an expression. The optimized way of filtering can be used only if it uses entity properties available in the entity database.
For: #6597 
At the moment of building an SQLite query to optimize filtering, both **#6600** and **#6597** appear to be the same issue (a missing column). However, when we fall back to Javarosa, **#6600** is evaluated with the referenced question, while **#6597** is still treated as a missing property.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
For: #6600 
We need to test filtering with expressions that reference other questions in a form, not just expressions that use entity properties. The form attached to the issue is an example of it.
For: #6597 
We need to test filtering with expressions that simply use non-existing properties.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form is attached to the issue. 

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
Would it be possible to solve this at the `DatabaseEntitiesRepository` level instead by adding tests for these cases to/modifying `#query`?

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt [hunk 1]
```diff
@@ -541,6 +541,121 @@ class LocalEntitiesFilterStrategyTest {
...
+                        "label"
+                    )
+                )
+            ),
+            controllerSupplier
+        )
+
+        val choices = scenario.choicesOf("/data/question").map { it.value }
+        assertThat(choices.isEmpty(), equalTo(true))
+        assertThat(fallthroughFilterStrategy.fellThrough, equalTo(true))
```
Comment (lognaturel) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:702]: `works correctly in the optimized way` -- what makes it optimized? This looks like it fell through which I thought would be non-optimized.

This test looks identical to https://github.com/getodk/collect/pull/6601/files#diff-4a25b4c0ba0780186c2edabe26d8518d4e3e6a022a482669373e2a71ceac6dfbR585 to me

In this test `not_existing_property` is the reference in the secondary instance and `'value'` is a static value.

In the test above, `undefined` is the reference in the secondary instance and `/data/ref_question` is a static value that came from the form.

It's confusing because the order is different and the intended meaning is different! But I believe that from the system's standpoint they should be in the same category. If there's code somewhere that treats them as different we should dig into it, I think.

Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:702]: > works correctly in the optimized way -- what makes it optimized? This looks like it fell through which I thought would be non-optimized.

I made a mistake in the title it's not optimized of course. I will fix that.

If you set `not_existing_property='value'`, it will always return an empty list of entities (because `not_existing_property` does not exist).  
However, if you use `undefined=/data/ref_question` or `'value'=/data/ref_question` (because we focus too much on the `undefined` case), the list won't be empty - as long as the expected value matches the one entered in the question.
Wouldn't it be enough to treat these two cases as distinct and have separate tests for each?

**Comment by grzesiek2010** [comment]
> Would it be possible to solve this at the DatabaseEntitiesRepository level instead by adding tests for these cases to/modifying #query?

We have to catch queries that contain non-existent columns and fall back to Javarosa so no there is nothing we can do just in the `DatabaseEntitiesRepository`

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt (hunk 1 above)
Comment (lognaturel) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:702]: > If you set not_existing_property='value', it will always return an empty list of entities (because not_existing_property does not exist).

And with `not_existing_property=''`, you should always get all Entities. That's the same as the `undefined=/data/ref_question` case when `/data/ref_question` has a blank value.

I sort of see the distinction that you're making, thanks for explaining it again, that was helpful. It doesn't hurt to have a few extra tests and I don't think there's a fundamental misunderstanding here. 👍 

> 'value'=/data/ref_question

This one does definitely feel different from the other two to me. This should be identified as not an expression that can use the optimized filter strategy and bypass before it even gets there (maybe good to double check this?). The other two should be identified as candidates for the filter strategy and then be kicked back to the next one once the column is determined to be unknown.

**Comment by lognaturel** [comment]
> there is nothing we can do just in the DatabaseEntitiesRepository

An alternative would be to "look before you leap" and fall back if there are any unknown properties in the expression, I think. I believe that's what @seadowg said the code did before.

**Comment by lognaturel** [comment]
I think one step even further would be to detect unknown columns in subexpressions, treat those as ‘’, and then evaluate the sub expression. That should always be possible for the shape of subexpression that makes it to the entities filter strategy.

For example, /data/ref=undefined would be detected as such an expression, it would be evaluated as /data/ref=‘’ and then the result (true or false) would be used in the SQL. That would avoid the need to fall back to another filter strategy. Not a must but hopefully the example further illustrates why I think of all the cases with unknown properties as being in the same category.

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:702]: > And with not_existing_property='', you should always get all Entities.

Correct.

> This one does definitely feel different from the other two to me. This should be identified as not an expression that can use the optimized filter strategy and bypass before it even gets there (maybe good to double check this?). The other two should be identified as candidates for the filter strategy and then be kicked back to the next one once the column is determined to be unknown.

Right, these cases throw an SQLiteException because of the missing columns:
- `undefined=/data/ref_question`
- `null=/data/ref_question`
- `not_existing_property=""`
- `not_existing_property="value"`

These cases are identified as not an expression that can use the optimized:
- `'value'=/data/ref_question`
- `''=/data/ref_question`

**Comment by seadowg** [comment]
> We have to catch queries that contain non-existent columns and fall back to Javarosa so no there is nothing we can do just in the DatabaseEntitiesRepository

We could identify `Query` objects that use columns we don't recognize and then throw a specific exception (like `UnsupportedQueryException`). I recognize that requires a recursive search though so definitely isn't the simplest solution. For now could we at least avoid bubble `SQLiteException` up beyond the `EntitiesRepository` (which is not a sql specific interface)? We could catch `SQLiteException` within `#query` and wrap it in a specific `EntitiesRepository` exception.

**Comment by grzesiek2010** [comment]
> For now could we at least avoid bubble SQLiteException up beyond the EntitiesRepository (which is not a sql specific interface)? We could catch SQLiteException within #query and wrap it in a specific EntitiesRepository exception.

Done.

File: entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt [hunk 2]
```diff
@@ -56,7 +56,7 @@ class InMemEntitiesRepository : EntitiesRepository {
                         EntitySchema.VERSION -> it.version.toString()
                         else -> it.properties.find { propertyName ->
                             propertyName.first == query.column
-                        }?.second
+                        }?.second ?: throw QueryException("No such column: ${query.column}")
```
Comment (seadowg) [inline entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt:59]: There should really be a test in `EntitiesRepositoryTest` to make sure that both implementations are consistent here. I'm going to be doing a quick pass over at #6614 anyway though so will tidy that up when moving tests from `getAllByProperty` to `query`.

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt [hunk 3]
```diff
@@ -541,6 +541,124 @@ class LocalEntitiesFilterStrategyTest {
...
+                    ),
+                    select1Dynamic(
+                        "/data/question2",
+                        "instance('things')/root/item[/data/ref_question=undefined]",
+                        "name",
+                        "label"
+                    ),
+                    select1Dynamic(
+                        "/data/question3",
+                        "instance('things')/root/item[/data/ref_question=null]",
```
Comment (seadowg) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt]: We don't need a case for `undefined` and `null` here as they're testing the same thing. Also can we make it clearer that we're testing against a non-existent child here by using `not_existing_property` instead of either like below?

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt [hunk 4]
```diff
@@ -541,6 +541,124 @@ class LocalEntitiesFilterStrategyTest {
...
+        choices = scenario.choicesOf("/data/question3").map { it.value }
+        assertThat(choices, containsInAnyOrder("thing1"))
+
+        scenario.next()
+        scenario.answer("blah")
+
+        choices = scenario.choicesOf("/data/question1").map { it.value }
+        assertThat(choices.isEmpty(), equalTo(true))
+
+        assertThat(fallthroughFilterStrategy.fellThrough, equalTo(true))
```
Comment (seadowg) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt:626]: This assertion doesn't really work in this context (and in the test below) because only one of the expressions has to cause a fall through - the others could be optimized. I'd be tempted to break these into separate tests. That would also probably make them easier to read anyway as the test descriptions could be more specific and the XForms would be simpler.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt [hunk 5]
```diff
@@ -541,6 +541,166 @@ class LocalEntitiesFilterStrategyTest {
         assertThat(fallthroughFilterStrategy.fellThrough, equalTo(false))
         assertThat(instanceProvider.fullParsePerformed, equalTo(false))
     }
+
+    @Test
+    fun `works correctly but not in the optimized way with question = ''`() {
```
Comment (seadowg) [inline entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt]: I think just to clarify these tests this one should be "...unanswered question..." and the below one should be "...answered question..." right?

**Review by seadowg — CHANGES_REQUESTED** [review]
Just one tiny tweak!

File: entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt]: Right.

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 15

**Verified cases:**
- Listeed issues do not occur
#6600 
#6597
- Update and follow up forms referencing other questions
- Update forms using non existing property
- Blank dataset

**Comment by srujner** [comment]
**Tested with success**

Verified on device with Android 10, 12
