### PR TITLE
GeoTrace/GeoShapeActivity: Preserve instance state on screen rotation

### LINKED ISSUE #2492: Geoshape: deleted polygon is visible after screen rotation
#### Software and hardware versions 
Collect v1.16.x, Android v from 4.1 to 8.1. 

#### Problem description
After clearing and rotation of the screen, the deleted polygon is restored.

#### Steps to reproduce the problem
1. Open Geoshape widget.
2. Add a polygon.
3. Click on the clear button.
4. Rotate the device screen. 

#### Expected behavior
As polygon has been cleared it shouldn't be restored after screen rotation. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by zestyping**
Closes #2492.

Addresses #2310 for GeoShapeActivity and GeoTraceActivity but not for GeoPointActivity.

#### What has been done to verify that this works as intended?
I manually tested GeoShape in both Google and OSM modes:
  * Added a polygon, then rotated the screen to verify it was preserved (#2310)
  * Cleared the polygon, then rotated the screen to verify it didn't reappear (#2492)
  * After rotating the screen, verified that long-presses added more points as expected
  * After rotating the screen, verified that the "Back" button triggered the confirmation prompt when it was supposed to

I manually tested GeoTrace in both Google and OSM modes:
  * Added a trace, then rotated the screen to verify it was preserved (#2310)
  * While a trace was actively being recorded in manual mode, rotated the screen and continued recording
  * While a trace was actively being recorded in automatic mode, rotated the screen and verified that recording continued with the same time interval between points
  * While a trace was actively being recorded in manual mode, paused recording, rotated the screen, and unpaused recording
  * While a trace was actively being recorded in automatic mode, paused recording, rotated the screen, and unpaused recording

#### Why is this the best possible solution? Were any other approaches considered?
`onSaveInstanceState` is the recommended way to handle orientation changes.  A nice side benefit of this change is that this also preserves state when the activity is killed for any other reason (e.g. incoming phone call, switch to other apps, etc.)

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only observable change to behaviour should be that the activity appears to continue working normally when the screen is rotated, instead of discarding entered data and losing track of the map view.

Note the following limitations:
* Rotating the screen in GeoTraceActivity while automatic recording is running will restart the recording timer.  So, for example, if your interval is 10 seconds, and 8 seconds have elapsed since the last points, rotating the screen will restart the timer and the next point will be recorded 10 seconds later instead of only 2 seconds later.
* The offline basemap tile selection is not preserved; it is still lost when the screen is rotated.

#### Do we need any specific form for testing your changes?
Any form with geo widgets will do.  Here is one:
[geo-widgets.zip](https://github.com/opendatakit/collect/files/2472813/geo-widgets.zip)

#### Does this change require updates to documentation?
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java [hunk 1]
```diff
@@ -73,7 +82,7 @@
 
     private boolean beenPaused;
     private boolean modeActive;
-    private Integer traceMode = 1; // 0 manual, 1 is automatic
+    private Integer traceMode = 0; // 0 manual, 1 is automatic
```
Comment (zestyping) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java:85]: Previously, the initial value of 1 here had no effect: the radio group comes up with `Manual` selected (because it has `checked="true"` in the layout XML file, and the radio buttons are never updated based on `traceMode`, `traceMode` is only updated by reading the radio buttons).

Now, upon initialization, we update the radio buttons based on the restored value of `traceMode`.  To preserve the current user-visible behaviour, we need `traceMode` to be `0` so that `Manual` remains pre-selected.

**Comment by lognaturel** [comment]
> Rotating the screen in GeoTraceActivity while automatic recording is running will restart the recording timer.

Seems it would be possible to keep a reference to the scheduler to address that? I'm not immediately seeing what happens to it on rotation now.

> The offline basemap tile selection is not preserved; it is still lost when the screen is rotated.

Seems like something to address in a future PR?

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @zestyping, @kkrawczyk123! @zestyping and I talked briefly about this and he does intend to address the limitations discussed above in the future. The limiting factor for the timer preservation on rotate is figuring out what exactly the ideal behavior is and for offline basemap tile selection, it will be better addressed once `MapHelper` is reworked.

**Comment by zestyping** [comment]
Future issues to fix are filed as #2646 and #2647.
