### PR TITLE
Fixed crash in FormDownloadList

### LINKED ISSUE #3267: App crashes when Storage permission is unselected and user tries to return to `Get Blank Form` view
### Software and hardware versions 
Collect v1.22.4 (older versions were not verified)

#### Problem description
App crashes when Storage permission is unselected and user tries to return to `Get Blank Form` view

#### Steps to reproduce the problem
1. User uses Collect. **Aggregate** is set as a server.
2. User opens Get Blank Form
3. Storage permission is unselected
4. User returns to Collect
5. App crashes

Screenshot from 2019-07-31 14-12-56

#### Expected behavior
App does not crash
User is able to continue work

#### Other information 
The crash is not visible when Google Drive is set as a server

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3267 

#### What has been done to verify that this works as intended?
Reproduced the described crash and confirmed it fixes the problem.

#### Why is this the best possible solution? Were any other approaches considered?
I just added a check to avoid calling `updateAdapter()` if storage permissions are not granted. It's the only solution here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix. It won't change anything else apart from fixing the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java [hunk 1]
```diff
@@ -339,8 +339,9 @@ private void downloadFormList() {
     @Override
     protected void onRestoreInstanceState(Bundle state) {
         super.onRestoreInstanceState(state);
-        toggleButtonLabel(toggleButton, listView);
-        updateAdapter();
+        if (PermissionUtils.areStoragePermissionsGranted(this)) {
+            updateAdapter();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java:343]: I can't recall why it's needed here, maybe it's not at all but I guess there is a tricky case that needs this fix so I decided to keep it and add if statement instead of removing what also would fix the crash but could bring some strange problems.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks for separating out that first commit -- I had a moment where I wondered where that call went, was about to look into it, but the answer was right there! ✨

**Comment by grzesiek2010** [comment]
No testing? The solution seems obvious but we both have seen even more obvious that we merged without testing and there was something wrong.

**Comment by lognaturel** [comment]
Sigh, I suppose you're right. I think we're ok to release it but @grzesiek2010 is right that it'd be good to get a check @kkrawczyk123, @mmarciniak90.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 9.0, 8.1, 7.0, 6.0
Verified on v1.23 downloaded from `Play Store`

Verified cases:
* Storage permission denied on `Get Blank Form` when **Aggregate** was set as a server
* Storage permission denied on `Get Blank Form` when **Google Drive** was set as a server

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
