### PR TITLE
Fixed building map fragments based on settings

### LINKED ISSUE #5322: Source of maps chosen in the first project is applied in the second project or causes the crash of the app
#### ODK Collect version
v2022.3.0, the store version, master 8dc41e9328132b1f0f8db3aad92de49bf5493104
#### Android version
8.1, 10, 11, 12, 13
#### Device used
Nexus 5X, Redmi 9T, Galaxy M12, Pixel 3a, Pixel 6a
#### Problem description
If the user chooses a source of maps in the first project, the same source of maps is applied in the second project (although different source is chosen in project settings). The user is not able to change the source of maps in the second project.

#### Steps to reproduce the problem
1. Download the Collect app.
2. Open the demo project.
3. Get All widgets form.
4. Go to app settings and choose Mapbox as a source of maps.
5. Go to "Fill Blank Form".
6. Tap on the form map of All widgets and click the device back button.
7. Add another project (with some forms with maps).
8. Open any map/ form map in that project and check the source of maps.
(9. Try to change the source of maps.)

Mapbox is applied in the second project.
#### Expected behavior
In a new project Google maps should be chosen by default. The user should be able to choose different sources of maps in different projects.
#### Other information 
On Android 8.1 going back to the first project and opening a map crashes the app.
In Collect v2022.1.0 I wasn’t able to reproduce the problem.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5322 

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
`MapFragmentFactoryImpl` is created once and passed to the geo module so that it can be injected in the classes that belong to that module. The problem was that as a constructor parameter we passed settings to `MapFragmentFactoryImpl` like it was created for every single usage. As a result `MapFragmentFactoryImpl` was always used with the same settings (from the first project). I fixed it passing settingsProvider to `MapFragmentFactoryImpl` instead.

BTW. it is a bit misleading that such dependencies that we pass to other modules are singletons but they are not annotated with `@Singleton` annotation. This is something we might want to change in the future @seadowg.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The implemented changes are only in the class responsible for creating map views (Google/Mapbox/OSM) based on settings so this is the only source of risk.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt [hunk 1]
```diff
@@ -0,0 +1,81 @@
+package org.odk.collect.android.geo
+
+import org.hamcrest.CoreMatchers.instanceOf
+import org.hamcrest.MatcherAssert.assertThat
+import org.junit.Test
+import org.odk.collect.osmdroid.OsmDroidMapFragment
+import org.odk.collect.settings.InMemSettingsProvider
+import org.odk.collect.settings.keys.ProjectKeys
+
+class MapFragmentFactoryImplTest {
```
Comment (lognaturel) [inline collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt:10]: I'm not seeing how the tests relate to the issue! I would expect something related to multiple projects. Or is writing a non-Espresso test for that too difficult?

These test the relationship between basemap source configs and the engine used by the map fragment, right? That does seem like a good thing to have coverage for that isn't covered elsewhere. Any reason not to include Mapbox?

**Review by lognaturel — COMMENTED** [review]
Change looks good to me. One question about tests but QA can start.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified Cases:**
- issue #5322 is no longer reproducing
- Android 8.1 steps from the issue
- changing the source of maps in settings and switching between projects
- changing the source of maps in a duplicate project
- reconfiguring a project via QR code with a project with different source of maps set in settings
- form map and maps in forms
- offline layers added in the folder for all projects and for just one project
- changing the source of map when in an opened form
- different map styles
- deleting all the projects and adding the same projects

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13

File: collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt:10]: The problem was that `MapFragmentFactoryImpl` as a parameters received `Settings` and it was easy to make a mistake and pass incorrect ones (from a different project). Now it takes `SettingsProvider` so we do not need to test if we pass correct ones (there is one settings provider for all of them). We just need to verify that creating map fragments it takes settings that belong to the current project (from that `SettingsProvider`) what we do in the test because in both (tests and code base) we use `getUnprotectedSettings()` without any parameter (what returns settings for the current project)

> Any reason not to include Mapbox?

I've only tested `OSM` and `Google` because `Mapbox` classes do not exist without tokens so it's not possible to verify it.

Comment (lognaturel) [reply collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt:10]: Thanks for the explanations!

**Review by lognaturel — APPROVED** [review]
