### PR TITLE
Fix property names clashing with DB column names

### LINKED ISSUE #6486: Entity property "_id" crashes the app after refreshing the list of blank forms
#### ODK Collect version
the master version c7c4719561d269f65a7b9644c1084336ec033414
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Refreshing the list of blank forms with a form (update or follow-up) using a dataset with a property "_id” crashes the app.
idproperty

#### Steps to reproduce the problem
1. Download Collect.
2. Scan "trees” QR code https://test.getodk.cloud/#/projects/575/app-users
3. Go to "Start new form” and tap the arrow to download forms.
#### Expected behavior
The app shouldn't crash.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6486

#### Why is this the best possible solution? Were any other approaches considered?

Other alternatives might have been to index properties in some way (in the `lists` table for example), but using a prefix felt like the simplest way to fix this to me. Even if a property clashes with the prefix (a property named `p_id` for example) we would still add/remove the prefix correctly as it's isolated to `DatabaseEntitiesRepository` (the previous example would end up with a column named `p_p_id`).

We also decided (on a call) to go with just clearing out the entities DB when upgrading rather than writing proper migration code. This mitigates any risk of migrating data incorrectly, and has minimal impact as the entities DB only exists for beta users at this time.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Along with fixing the bug, any local entities on device will be wiped. It's definitely worth playing with upgrades from the last beta to check this works as expected.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — DISMISSED** [review]
This doesn't need to be human-readable so let's go with an even shorter prefix like `p_`

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt [hunk 1]
```diff
@@ -15,4 +19,21 @@ class DatabaseEntitiesRepositoryTest : EntitiesRepositoryTest() {
...
+            "1",
+            "One",
+            properties = listOf(Pair("_id", "value"), Pair("version", "value"))
+        )
+
+        repository.save("things", entity)
+        val savedEntity = repository.getEntities("things")[0]
+        assertThat(savedEntity, sameEntityAs(entity))
+
+        repository.save("things", savedEntity)
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt:36]: Why do you need to save twice?

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt [hunk 2]
```diff
@@ -15,4 +19,21 @@ class DatabaseEntitiesRepositoryTest : EntitiesRepositoryTest() {
             TempFiles.createTempDir().absolutePath
         )
     }
+
+    @Test
+    fun `#save supports properties with db column names saving new entities and updating existing ones`() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt:24]: Couldn't it be simply: `#save supports properties with db column names`?

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt [hunk 3]
```diff
@@ -399,29 +397,28 @@ class DatabaseEntitiesRepository(context: Context, dbPath: String) : EntitiesRep
         }
     }
 
+    private fun addPropertiesToContentValues(contentValues: ContentValues, entity: Entity) {
+        entity.properties.forEach { (name, value) ->
+            contentValues.put("\"${EntitiesTable.getPropertyColumn(name)}\"", value)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt:402]: Couldn't this be just:
`contentValues.put(EntitiesTable.getPropertyColumn(name), value)`

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt (hunk 1 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt:36]: We're checking creating and updating.

File: collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt (hunk 2 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt:24]: https://github.com/getodk/collect/pull/6495/files/f0a4c3e32164ebfcb1ca5e3347334243993bbdc5#r1830770726

File: collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt:402]: You'll see that `#save supports properties with dots and dashes when saving new entities and updating existing ones` fails if you change to that. We need to quote the column property column names as they might contain special characters that SQL queries don't support.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 15
Dominika also verified on device with Android 10

**Verified cases:**
- Issue #6486 does not occur
- Adding different entity properties
- Upgrading from last beta and store version
