### PR TITLE
Avoid starting asynctask responsible for uploading forms to GS twice

### LINKED ISSUE #3466: java.lang.IllegalStateException in GoogleSheetsUploaderActivity.java:346
#### Software and hardware versions 
Collect v1.24.1 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/fe6c6f55e1e224d56a09e8a149ec7f76?time=last-seven-days&sessionId=5DD7CB9A003200011E64E17E8ECF7544_DNE_0_v2

`Fatal Exception: java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:640)
       at android.os.AsyncTask.execute(AsyncTask.java:595)
       at org.odk.collect.android.activities.GoogleSheetsUploaderActivity.authorized(GoogleSheetsUploaderActivity.java:346)
       at org.odk.collect.android.activities.GoogleSheetsUploaderActivity.access$200(GoogleSheetsUploaderActivity.java:62)
       at org.odk.collect.android.activities.GoogleSheetsUploaderActivity$AuthorizationChecker.onPostExecute(GoogleSheetsUploaderActivity.java:389)
       at org.odk.collect.android.activities.GoogleSheetsUploaderActivity$AuthorizationChecker.onPostExecute(GoogleSheetsUploaderActivity.java:367)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6606)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

#### Other information 
It's the most common issue in the latest version, so it would be good to fix it:
image

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3466

#### What has been done to verify that this works as intended?
I tested uploading forms to GS.

#### Why is this the best possible solution? Were any other approaches considered?
I wasn't able to reproduce the issue so I'm not sure what is the real cause but at least we can avoid it what I did in the [second commit](https://github.com/opendatakit/collect/commit/90728bf7c1586cfb8d9036147f3021fca1a4730d).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The implemented changes are only related to uploading forms to GS so please just test that functionality.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 1]
```diff
@@ -122,22 +120,16 @@ protected void onCreate(Bundle savedInstanceState) {
     }
 
     private void runTask() {
-        instanceGoogleSheetsUploaderTask = (InstanceGoogleSheetsUploaderTask) getLastCustomNonConfigurationInstance();
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java:125]: Using `getLastCustomNonConfigurationInstance()` comes from very first versions of this functionality when we allowed calling this part of code again. Now it's called only from `onCreate()` but in `onDestroy()` we have `finish()` that means `onCreate()` can't be called again according to the lifecycle:
https://developer.android.com/guide/components/activities/activity-lifecycle

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java [hunk 2]
```diff
@@ -295,20 +279,19 @@ public void progressUpdate(int progress, int total) {
...
-                gudBuilder.setMessage(getString(R.string.google_set_account));
-                gudBuilder.setPositiveButton(R.string.ok, new DialogInterface.OnClickListener() {
-                    @Override
-                    public void onClick(DialogInterface dialog, int which) {
-                        finish();
-                    }
-                });
-                gudBuilder.setCancelable(false);
-                return gudBuilder.create();
+        if (id == GOOGLE_USER_DIALOG) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java:282]: It's more idiomatic in Android to match ids with switches so I think it's ok to leave even if there's only one branch. Annoying that Android Studio always complains about that, though. I don't feel strongly either way but wanted to highlight that I don't think we should be changing all.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

I did not notice regression.
Verified on Android: 4.2, 4.4, 6.0, 7.0, 8.1, 9.0, 10 

Verified cases:
- downloading forms from GD
- sending submissions to declared GS
- sending submissions to general GS
- forms with media
- forms with repeat sections
- forms with cascading select

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
