### PR TITLE
Fixed deleting current layer

### LINKED ISSUE #6189: Deleting the selected offline layer and cancelling choosing another layer
#### ODK Collect version
the master version 515a8f9636aced3591ccfd5f42fa4916423d4630
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
If an already selected offline layer gets deleted and after that the user chooses to cancel selecting another layer, the deleted layer is still visible in the map and in "Select reference layer" nothing is selected.
cancelSelect

#### Steps to reproduce the problem
1. Go to a form with maps and open the map.
2. Add an offline layer and save it.
3. Tap the offline layer button, "Delete layer” and confirm to delete the layer.
4. In "Select reference layer” tap "cancel”.
#### Expected behavior
If an offline layer was deleted and none other layer was selected, the settings should change to "none” and the deleted layer should be removed form the map view.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6189 

#### Why is this the best possible solution? Were any other approaches considered?
When the current layer is deleted we not only have to set the selection to `none` but also save it in settings. That second action was missing.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should only fix the issue. I don't think it can have any side effects or put at risk anything else.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt [hunk 1]
```diff
@@ -91,9 +91,12 @@ class OfflineMapLayersViewModel(
         settingsProvider.getUnprotectedSettings().save(ProjectKeys.KEY_REFERENCE_LAYER, layerId)
     }
 
-    fun deleteLayer(layerId: String) {
+    fun deleteLayer(layerId: String, checkedLayerDeleted: Boolean) {
         _isLoading.value = true
         scheduler.immediate {
+            if (checkedLayerDeleted) {
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: We could just work out if we're deleting the current layer here right? Then we only need to have a check in one place. Plus that would mean we're not using the UI state as a source of truth for which layer is the current one in settings.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt (hunk 1 above)
Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: No, I need to pass either this boolean or `checkedLayerId` and then compare `layerId` with that `checkedLayerId` to know if this is the selected layer as this view model has no knowledge about the state.

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: We can grab it from settings right? The tests pass with the following:

```kotlin
if (layerId == settingsProvider.getUnprotectedSettings().getString(ProjectKeys.KEY_REFERENCE_LAYER)) {
    saveCheckedLayer(null)
}

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: There is a difference between the saved layerId and the currently selected layerId. Imagine you have two layers `Layer1` and `Layer2`. `Layer1` is the one saved in settings. When you open the bottom sheet this layer will be selected. Then you can click on `Layer2` (without saving) and now you are in the state where the saved layer is `Layer1` but the currently selected one is `Layer2`.
Ahh so it's more complex we need to handle both cases:
1. When the selected layer is the saved one
2. When the selected layers is different than the selected one

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: Actually there are 3 cases:
1. You can delete the layer that is saved and selected at the same time
2. You can delete the layer that is selected but not saved.
3. You can delete the layer that is saved but not selected.

Do you agree to reset to none in all those cases for simplicity?

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: Right! It feels like `OfflineMapLayersStateViewModel` needs to know more about the actual data to deal with the fact that it can be modified at any time. It could actually observe `OfflineMapLayersViewModel#existingLayers` like we do in `MultiSelectViewModel` (although the use case is far more complex). The simplest version of that for now might be to something like this:

```kotlin
sharedViewModel.existingLayers.observe { layers ->
    stateViewModel.setLayers(layers)
}
```

Then in `OfflineMapLayersStateViewModel`:

```kotlin
fun setLayers(layers: <List<ReferenceLayer>>) {
    if (layers.none { it.id == _checkedLayerId.value } {
        _checkedLayerId.value = null
    }
}
```

I think eventually we'd want some kind of generic type that provides this data to a generic selection view model (like we've discussed before), but that's probably for later.

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: This got really stuck in my head, so I wanted to quickly sketch out how a generic select view model might handle this:

```kotlin
data class SelectItem(val id: String, val selected: Boolean)
class SelectViewModel(data: LiveData<List<SelectItem>>) {

    private val _selected = MutableLiveData<String?>()
    val selected: LiveData<String?> = LiveDataUtils.zip(_selected, data).map { (selected, items) ->
        if (selected != null && items.any { it.id == selected }) {
            selected
        } else {
            items.find { it.selected }?.id
        }
    }

    fun select(id: String) {
        _selected.value = id
    }
}
```

Here'd you'd `map` the underlying data (existing layers and settings) into a `LiveData<SelectItem>`. The `zip` and `map` then allows you to combine that with a mutable selection, and you can basically say: "if I've selected one and it's in the data use that and if not use the selected one from the data (if there is one)".

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: I've improved the fix with the first approach please take a look.
If you strongly feel like we should have a more generic approach here feel free to push your changes because I think I might not have enough time to understand your way of thinking and implement those changes before my vacation.

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: Yeah, that's fine. To be clear, I agree the generic approach is better as a follow-up, but I needed to get that first thought out of my head 😆. I can always give that a go next week so we can discuss when you're back!

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt]: If you want to keep it open then https://github.com/getodk/collect/pull/6188 shouldn't be blocked I think. https://github.com/getodk/collect/pull/6188 brings more changes so if one of them needs to be blocked it should be rather this one.

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

**Verified cases:**
- Issue is no longer reproducing;
- Regression check on Maps;
- Offline Layers tested in General;
- Different Map sources;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue #6189 doesn't occur
- deleting an offline layer added to the current project / all project
- deleting an offline layer and going to map settings
- deleting a saved offline layer

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14
