### PR TITLE
Remove ignore from field list test

### LINKED ISSUE #5996: Fix `FieldListUpdateTest#listOfQuestionsShouldNotBeScrolledToTheLastEditedQuestionAfterClickingOnAQuestion`
~~Blocked by #6059~~

This test fails on Test Lab, but not locally ([example](https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/6782266433663054701)).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5996

#### Why is this the best possible solution? Were any other approaches considered?

I was only able to get this to fail once, only on Test Lab and not since 40148aa58f678fa6a7e8f47b4d871419a616f66d. The main change I've made here is to deprecate `withIndex` due to it presenting subtle problems (because it's stateful). I suspect some of the other work we've done on UI tests recently has made this more stable, and I'm optimistic that the new method for scrolling to a question is more robust as well.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This just changes tests, so there is nothing to verify.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/matchers/CustomMatchers.kt [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+/**
+ * Grab bag of Hamcrest matchers.
+ */
+object CustomMatchers {
+    /**
+     * Matches the view at the given index. Useful when several views have the same properties.
+     * https://stackoverflow.com/a/39756832
+     *
+     */
+    @Deprecated("this matcher is stateful and will cause problems if used more than once")
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/matchers/CustomMatchers.kt:35]: The problems with this are actually mentioned in a comment on the SO answer, but for some reason the answer has stayed up. I've flagged it, so others don't run into the same problems.

To be clear, I'm not sure if it actually broke anything for us, but while experimenting with different ways of scrolling and clicking I ended up running into problems caused by the state here.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/matchers/CustomMatchers.kt [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    @JvmStatic
+    fun isQuestionView(questionText: String): Matcher<View> {
+        return object : TypeSafeMatcher<View>() {
+            override fun describeTo(description: Description) {
+                description.appendText("is question view with text: ")
+                description.appendValue(questionText)
+            }
+
+            override fun matchesSafely(item: View): Boolean {
+                return if (item is QuestionWidget) {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/matchers/CustomMatchers.kt:62]: I'm not a big fan of UI tests that know this much about the view hierarchy, but I've tried to keep this as general as possible: `QuestionWidget` is a pretty fundamental view type and there just needs to be a `text_label` somewhere within it for this to work (the actual structure doesn't matter).

**Review by grzesiek2010 — APPROVED** [review]
