### PR TITLE
Recreate project directories if they have been deleted

### LINKED ISSUE #4756: Crash trying to connect to db when current project doesn't exist
#### Software and hardware versions 
Collect v2021.2

#### Problem description
If the project id saved in meta settings corresponds to a project that was deleted from the filesystem, Collect will crash on open. This is likely not a very common operation but given that we now see clear evidence that people are pushing both forms and instances through the filesystem, it wouldn't be surprising if they're also deleting projects that way.

I believe this explains a subset of [the database crashes we see in Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?versions=v2021.2.0%20(4242)&time=last-seven-days&sessionEventKey=61031FAD03BA00010D413B71613F3C76_1568911492518499770).

#### Steps to reproduce the problem
1. Create a project from Collect
2. `adb shell` and delete the project
3. launch Collect

#### Expected behavior
No crash.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4756 

#### What has been done to verify that this works as intended?

New tests and verified manually by deleting directories and then returning to/restarting the app.

#### Why is this the best possible solution? Were any other approaches considered?

Lots of approaches considered! We've had long discussions about this on Slack and there are thoughts in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the issue. It'd be good to check deleting `files` (or the `org.odk.collect.android`) directory as well as the `project` or current project's directory. This solution seems to work for both returning to (multi tasking away and back after deleting files) and for restarting (killing the app and starting again after deletion).

As a heads-up, it's very likely that there are places in the app other than the main menu that will still break, but we haven't actually seen that in the wild so chose not to address that yet. It's also likely that deleting a project directory for an inactive project and then switching to it will break, but we also haven't seen that in the wild.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectSettingsDialogPage.kt [hunk 1]
```diff
@@ -45,8 +45,8 @@ internal class ProjectSettingsDialogPage() : Page<ProjectSettingsDialogPage>() {
         return this
     }
 
-    fun assertNotInactiveProject(projectName: String, subtext: String): ProjectSettingsDialogPage {
-        onView(allOf(hasDescendant(withText(projectName)), hasDescendant(withText(subtext)), withContentDescription(getTranslatedString(R.string.switch_to_project, projectName)))).check(doesNotExist())
+    fun assertNotInactiveProject(projectName: String): ProjectSettingsDialogPage {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectSettingsDialogPage.kt:48]: I don't think we need to assert on the URL when checking a project doesn't exist.

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/CurrentProjectViewModel.kt [hunk 2]
```diff
@@ -23,19 +26,36 @@ class CurrentProjectViewModel(
...
         analyticsInitializer.initialize()
-        refresh()
+        updateCurrentProjectIfNeeded()
     }
 
     fun refresh() {
+        updateCurrentProjectIfNeeded()
+
+        if (!File(storagePathProvider.getProjectRootDirPath()).exists()) {
+            Analytics.log(AnalyticsEvents.RECREATE_PROJECT_DIR)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/CurrentProjectViewModel.kt:36]: I thought about a call that works out exactly what has been deleted, but I realized that it wouldn't work properly due to our application initialization recreating the `projects` dir and obscuring the cases where the user has deleted the external files dir or cleared it out.

File: collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/CurrentProjectViewModel.kt [hunk 3]
```diff
@@ -23,19 +26,36 @@ class CurrentProjectViewModel(
...
+            storagePathProvider.getProjectDirPaths(currentProject.value.uuid).forEach { FileUtils.createDir(it) }
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/CurrentProjectViewModel.kt:37]: This is duplicated code. I think instead of diving into addressing that, I can just work on a follow-up immediately. I'm also wondering about moving this on-the-fly directory creation to `CurrentProjectProvider` as that might cover every case (including normal project creation).

File: collect_app/src/main/java/org/odk/collect/android/projects/CurrentProjectProvider.kt [hunk 4]
```diff
@@ -31,4 +31,8 @@ class CurrentProjectProvider(private val settingsProvider: SettingsProvider, pri
     private fun getCurrentProjectId(): String? {
         return settingsProvider.getMetaSettings().getString(MetaKeys.CURRENT_PROJECT_ID)
     }
+
+    fun clear() {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/projects/CurrentProjectProvider.kt]: This seems to be unused.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/projects/CurrentProjectProvider.kt]: Ach thanks. Will remove.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/ProjectsAdbTest.kt [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+
+    val rule = CollectTestRule()
+
+    @get:Rule
+    var chain: RuleChain = TestRuleChain
+        .chain()
+        .around(rule)
+
+    @Test
+    fun clearingStorage_andReturningToApp_recreatesStorageForProject() {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/ProjectsAdbTest.kt:25]: Here you test going back to the `MainMenuActivity` so only `onResume()` will be called. Have you tested cases where the that activity is destroyed but the app is not killed entirely so that `ApplicationInitializer` won't be called?
I'm wondering if something bad wouldn't happen earlier (in `onCreate()` for example, before you call `currentProjectViewModel.refresh()` in `onResume()`).

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/ProjectsAdbTest.kt:25]: Oh you mean like if "Don't keep activities" is on? I've just given that a go and it seems to be happy. I think the reason we're seeing that crash specifically at the `refreshInstances` call is that happens to be the first time we need the database in the flow of opening the app.

Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/ProjectsAdbTest.kt:25]: Ok I think @mmarciniak90 and @kkrawczyk123 will test this scenario.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
@seadowg I can see crash when try to open Collect after deleting single project's folder (I had only one project added) via adb on my Android 5.1 device. 
stacktrace:
`08-04 12:29:32.720 11769-11856/org.odk.collect.android E/SQLiteDatabase: Failed to open database '/storage/emulated/0/Android/data/org.odk.collect.android/files/projects/DEMO/metadata/instances.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
        at org.odk.collect.android.database.DatabaseConnection.getReadableDatabase(DatabaseConnection.kt:27)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.query(DatabaseInstancesRepository.java:217)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCursorForAllByStatus(DatabaseInstancesRepository.java:213)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCountByStatus(DatabaseInstancesRepository.java:108)
        at org.odk.collect.android.formmanagement.InstancesAppState.update(InstancesAppState.kt:36)
        at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.lambda$refreshInstances$0$MainMenuViewModel(MainMenuViewModel.java:121)
        at org.odk.collect.android.activities.viewmodels.-$$Lambda$MainMenuViewModel$YcoOrSsMfVfE3us74hHtJ7C_gUA.get(lambda)
        at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-04 12:29:37.210 11769-11769/org.odk.collect.android E/WILLIS: ERROR
    java.util.concurrent.TimeoutException
        at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:122)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:237)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:154)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:54)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
        at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
08-04 12:29:37.211 11769-11769/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 11769
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
        at org.odk.collect.android.database.DatabaseConnection.getReadableDatabase(DatabaseConnection.kt:27)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.query(DatabaseInstancesRepository.java:217)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCursorForAllByStatus(DatabaseInstancesRepository.java:213)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCountByStatus(DatabaseInstancesRepository.java:108)
        at org.odk.collect.android.formmanagement.InstancesAppState.update(InstancesAppState.kt:36)
        at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.lambda$refreshInstances$0$MainMenuViewModel(MainMenuViewModel.java:121)
        at org.odk.collect.android.activities.viewmodels.-$$Lambda$MainMenuViewModel$YcoOrSsMfVfE3us74hHtJ7C_gUA.get(lambda)
        at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**Comment by seadowg** [comment]
@kkrawczyk123 right sorry I completely forgot that this only covers the cases where the `projects` dir is deleted or the whole external files dir is deleted. Can you create an issue for that other case? I think it's still worth merging this, as we think the most likely thing is that users are just deleting/clearing the external files dir.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 8.1, 9.0, 10.0

* removed org.odk.collect.android directory
* removed files directory
* removed projects directory
* removed only one, active project
* removed only one, inactive project and switched to it
* removed all projects 
* removed project with match exactly 
* settings are not reverted to default
* returning to collect
* launch restarted app
* Don't keep activities

I noticed that an empty file with the project name is not recreated -> I'm going to add this case to #4766

**Comment by kkrawczyk123** [comment]
Tested with success also on Androids 5.1 and 11 - for Android 5.1 without case mentioned in my comment above. I am not sure if it's worth creating a new issue as we were not able to reproduce it on any other devices.

**Comment by seadowg** [comment]
@kkrawczyk123 ah interesting. I'm working on the follow-up with some code tweaks that should make this all more robust, so we can just keep that in mind for when we test it!
