### PR TITLE
Prevent crashes in form filling when restoring process

### LINKED ISSUE #5240: Crash when restoring to some form entry screens
~~Blocked by #5338 (which adds testing for the flows we're changing)~~

Covers this [crash report](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7ef6006d57c29eff231ee9f78d2f188e?time=last-seven-days&versions=v2022.3.0%20(4477)&types=crash&sessionEventKey=62EB9C8D00D100017025055AC3E08E99_1706408576049390202) (and [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7ef6006d57c29eff231ee9f78d2f188e?time=last-seven-days&versions=v2022.3.0%20(4477)&types=crash&sessionEventKey=62EB9C8D00D100017025055AC3E08E99_1706408576049390202)).

#### ODK Collect version

v2022.2.3+

#### Android version

Reproduced on Android 10, but likely a problem in all versions

#### Device used

Pixel 2 emulator

#### Problem description

The app crashes when "restoring" (being reopened after being kicked out of memory rather than closed by the user) if the user was last on some form entry screens. An example is the Select One From Map map view (used in the example below).

#### Steps to reproduce the problem

1. Set "Background process limit" to "No background processes" in Developer Options
2. Open a form with a Select One From Map question
3. Go to question and click "Select Place"
4. Switch to another app and then back again

The app crashes. This also happens (or the app behaves weirdly) when restoring to the:

* Quit form dialog - will show the hierarchy and then the dialog when you exit the hierarchy. Additionally, the dialog title will just be "no form loaded".
* The form hierarchy - will show normal form entry instead of the hierarchy
* Form saving in progress (harder to reproduce but does [happen in reality](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/b7ee403472493aaecd327e67d5560ce7?time=last-seven-days&versions=v2022.4.1%20(4543)&types=crash&sessionEventKey=63971D31037100013CB113600829941E_1754682268331899682)) - will crash

#### Expected behavior

For the moment, we're going to avoid restoring view state when we do a process restore. This means that, to the user, the flow will look exactly the same as loading a form from a save point. To be explicit, in the case where a user is filling a form:

1. User answers some questions
2. Process is killed (either via background process kill or changing permissions in Android settings)
3. User navigates back to app
4. User sees hierarchy and pressing back takes them to the first question of the form (no dialogs etc are restored)

We'll need to be able to detect that a restore is happening for this to work.
 
#### Other information 

Restoring from background is a flow we've mostly forgotten about. @getodk/testers this (enabling "No background processes" and then switching apps) is a good way to find bugs/crashes that we probably miss while developing features.

The stack trace for the crash is:

```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'org.javarosa.form.api.FormEntryPrompt org.odk.collect.android.javarosawrapper.FormController.getQuestionPrompt(org.javarosa.core.model.FormIndex)' on a null object reference
       at org.odk.collect.android.formentry.FormEntryViewModel.getQuestionPrompt(FormEntryViewModel.java:237)
       at org.odk.collect.android.widgets.items.SelectOneFromMapDialogFragment.onAttach(SelectOneFromMapDialogFragment.kt:58)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:252)
       at org.odk.collect.android.activities.CollectAbstractActivity.onCreate(CollectAbstractActivity.java:42)
       at org.odk.collect.android.activities.FormEntryActivity.onCreate(FormEntryActivity.java:383)
```

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5240

As described in the issue: 

> For the moment, we're going to avoid restoring view state when we do a process restore

#### What has been done to verify that this works as intended?

New tests.

#### Why is this the best possible solution? Were any other approaches considered?

There's probably a bunch of other tricks we could use here, but I'm pretty happy with what I've gone for: write a UUID out to the `outState` and to application level state during `onSaveInstanceState`, and then compare later to determine whether the Activity is being recreated within the same or a new process.

I'm feeling pretty unhappy with some of the code required to test this, but I've left a comment about that inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

As well as checking the issue is resolved, it'd be good to test filling/editing and resuming (from save points) forms, forms with audit logs and the form hierarchy.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -418,7 +423,14 @@ public void onCreate(Bundle savedInstanceState) {
                 .forClass(SelectOneFromMapDialogFragment.class, () -> new SelectOneFromMapDialogFragment(viewModelFactory))
                 .build());
 
+        savedInstanceState = savedInstanceStateProvider.getState(savedInstanceState);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:426]: I don't feel great about this solution of forcing in a provider for `savedInstanceState`, but there's no existing way to start an Activity with previous state using `ActivityScenario`, and this is the best I could come up with (without forking AndroidX Test).

It currently **is** possible to write pure Robolectric code that that creates an Acivity with previous state so it should be possible to add that to `ActivityScenario` for "local" tests (that under the hood use the Robolectric backed `LocalActivityInvoker`), but I don't have enough knowledge of Android internals to know if it'd be doable for instrumentation tests. I'll file an issue over at AndroidX Test for this (and update this comment with a link).

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:426]: Link to issue: https://github.com/android/android-test/issues/1825.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
@dbemke Tested this PR earlier this week.

**Tested with Success!**

**Verified on device with Android**: 10,12,13

**Verified Cases:** 
- Issue #5240 is no longer reproducing;
- Sending finalized Forms, Editing saved Forms, Viewing sent Forms, Deleting saved Forms;
- Restoring Forms when Editing, Viewing, Sending, in Hierarchy View;
- Regression checks in Audit file;
- Regression check in Hierarchy View;
- In device settings - no background processes;
- Don’t keep activities enabled/disabled;
- Minimize the app and rotate the screen;
- Light and Dark Mode.
