### PR TITLE
Fixed showing keyboard

### LINKED ISSUE #5828: Keyboard collapsed on some text field (every other?)
#### ODK Collect version
v2023.3.0

#### Android version
13

#### Device used
Samsung Galaxy A13

#### Problem description

https://github.com/getodk/collect/assets/967540/77044f23-f303-4418-909f-ef00cb71cb34

#### Steps to reproduce the problem
Unsure! On my device, any form with fields that require keyboard input one after the other will repro. I asked @alyblenkin about this and she says that on her device the keyboard is always shown when expected.

The Galaxy A13 I'm using now is our second-most popular device so it does feel important to look into. @dbemke and @srujner can you please see whether you can reproduce?

#### Expected behavior
The keyboard is shown when the first field on the screen has text input.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5828 

#### Why is this the best possible solution? Were any other approaches considered?
It looks like on some devices there is a problem with showing a keyboard just after hiding it. We used to hide the keyboard every time we created a new question view and then show it if needed. I guess the short time between those two operations might be the cause.
To fix the problem I've removed hiding the keyboard before creating a new question view. We do that either way for questions that do not need the keyboard in `setFocus` method. The only problem is that it will happen a little bit later and that difference might be visible on some devices.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's important to test the changes on all our devices. The risk here is that on some of them showing/hiding the keyboard might not work well.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Works great on the Galaxy A13 🎉 

I did notice that when I jump to a text question the keyboard is not shown. I believe that's a change but I'll need to verify. We should also check things like whether the keyboard shows if the first question in a form requires it.

**Comment by grzesiek2010** [comment]
> I did notice that when I jump to a text question the keyboard is not shown. I believe that's a change but I'll need to verify.

I can reproduce it too but it's not caused by this pr. I will try to address that issue as well if it's possible.

**Comment by grzesiek2010** [comment]
@lognaturel I think I was able to fix that second issue, please test it.
I don't like the solution: https://github.com/getodk/collect/pull/5843/files#diff-c2ee7ae36f7c566b42448bec3d149e4f128d0e941e5450d5ad3f64aa37692613R12 but this is what we also do in other places:
- to play videos automatically https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java#L248
- to scroll to a question with an invalid answer https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java#L623

I'm going to file a separate issue for reviewing those problems and implementing a better and more reliable solution.

**[EDIT]** the issue is here https://github.com/getodk/collect/issues/5853

**Comment by grzesiek2010** [comment]
@lognaturel is off so I'm adding @seadowg as a reviewer too.

**Comment by lognaturel** [comment]
I’m not at a computer today 🦃 but wanted to say that it’s not a very significant issue so if you both dislike the implementation we could address it another time or not at all.

**Comment by grzesiek2010** [comment]
> I’m not at a computer today 🦃 but wanted to say that it’s not a very significant issue so if you both dislike the implementation we could address it another time or not at all.

I mean I don't like it because it's another case where we use a workaround like that what I have described in https://github.com/getodk/collect/issues/5853 but if it works that's ok for v2023.3.1. I think it's not risky and 100ms is not a significant delay.

File: collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt [hunk 1]
```diff
@@ -1,15 +1,21 @@
...
 
 object SoftKeyboardController {
     fun showSoftKeyboard(view: View) {
-        if (view.requestFocus()) {
-            val inputMethodManager = view.context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
-            inputMethodManager.showSoftInput(view, 0)
-        }
+        // Subtle delay in displaying the keyboard is necessary for the keyboard to be displayed at all,
+        // for example, when returning from the hierarchy view.
+        Handler(Looper.getMainLooper()).postDelayed({
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt:13]: Were you able to experiment shorter delays than 100ms here or even just adding no time based delay (with just a `post`)?

Also, we should probably use `Scheduler` here rather than referencing `Handler` directly here.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt:13]: > Were you able to experiment shorter delays than 100ms here or even just adding no time based delay (with just a post)?

I think I did and maybe it even worked but wanted to use a delay similar to what we have in other places (see above) to not risk that on some devices it wouldn't be enough.

> Also, we should probably use Scheduler here rather than referencing Handler directly here.

As I said it's rather a temporary solution so I didn't want to implement too many changes but passing `scheduler` to SoftKeyboardController would require more work.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt:13]: Ah you mean that we'd get rid of this after #5853? I'll make sure that's in the next milestone.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
When the issue was filed I wasn't able to reproduced it on my devices (one of them is Samsung Galaxy M12 Android 11). I've seen the keyboard missing twice in 2 months (happening randomly) but wasn't able to reproduce it afterwards. 
I tested the PR on Android 8.1 (Nexus), Android 10 (Redmi 9t), Android 11 ( Galaxy M12) after many tries I managed to get to this state once. 
identifyUserDontKeepAct

It's the identify User form + don't keep activities enabled in device settings and some minimizing the app and some swipe. I'm not able to determine the factors/ steps as I'm not able to reproduce it again.

**Comment by srujner** [comment]
In the same form (Identity user) + don't keep activities enabled I was able to reproduce the missing keyboard:

https://github.com/getodk/collect/assets/85225519/83064e63-0eff-4d91-bcb7-e54b1781d56c

Other than that I checked on Android 5.1, 12 and 13 and all other issues has been fixed

@lognaturel @grzesiek2010 if you decide that the one thing that we found with the Identity User form is not something that we should be worried about, then we're Ok with Closing this PR and merging it.

**Comment by lognaturel** [comment]
Wow! That’s an interesting case. I think we shouldn’t worry about it for this PR because it seems much rarer. If that sounds right to the rest of you, let’s merge and get this point release out!

**Comment by grzesiek2010** [comment]
I agree @srujner you can file a separate issue for that case.
