### PR TITLE
Show thousands separators in hierarchy view

### LINKED ISSUE #1709: Questions with appearance thousands-sep shown without separator in hierarchy view
#### Software and hardware versions 
Collect v1.12.0-beta.0

#### Problem description
Questions with appearance thousands-sep shown without separator in hierarchy view.

#### Steps to reproduce the problem
Fill out some values with thousands separators.
Tap on the jump icon
The values are shown without thousands separators.

#### Expected behavior
The values should be shown with thousands separators.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #1709. Best reviewed commit by commit.

#### What has been done to verify that this works as intended?
Filled out the form [thousands-separator.xml.txt](https://github.com/opendatakit/collect/files/1557666/thousands-separator.xml.txt) in a couple different locales and with varying numbers of digits.

#### Why is this the best possible solution? Were any other approaches considered?
I used standard Java methods instead of writing something custom. Without calling `setMaximumFractionDigits` fraction digits were limited to 3. I considered the max of 340 described at https://developer.android.com/reference/java/text/DecimalFormat.html#setMaximumFractionDigits(int) but that seemed like a weird magic number.

#### Are there any risks to merging this code? If so, what are they?
This affects how all questions' answers are shown on the hierarchy view so an error could make that screen unusable.

#### Do we need any specific form for testing your changes? If so, please attach one.
[thousands-separator.xml.txt](https://github.com/opendatakit/collect/files/1557666/thousands-separator.xml.txt)

### CODE REVIEW

**Comment by dr0pdb** [comment]
@lognaturel I am getting a null pointer exception while testing it locally.  

screenshot_2017-12-14-07-52-39-05


Upon further investigation i found out that it only happens when atleast one of the fields with appearance "thousands-sep" is empty. If all of them are filled then error won't be encountered.


screenshot_2017-12-14-07-57-09-53

**Review by dr0pdb — CHANGES_REQUESTED** [review]
Error mentioned in the above comment.

##### Edit

Stacktrace:

<pre>
12-14 08:01:15.845 1338-1338/org.odk.collect.android E/FormHierarchyActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                  at java.math.BigDecimal.<init>(BigDecimal.java:425)
                                                                                  at org.odk.collect.android.utilities.FormEntryPromptUtils.getAnswerText(FormEntryPromptUtils.java:48)
                                                                                  at org.odk.collect.android.activities.FormHierarchyActivity.refreshView(FormHierarchyActivity.java:333)
                                                                                  at org.odk.collect.android.activities.FormHierarchyActivity.onCreate(FormHierarchyActivity.java:153)
                                                                                  at android.app.Activity.performCreate(Activity.java:6107)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
                                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:164)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:159)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
</pre>

**Comment by lognaturel** [comment]
That's an important case! Thanks, @srv-twry. 😊

**Review by dr0pdb — APPROVED** [review]
Looks good and works fine locally!

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 7.0, 8.0.
Verified cases:
* filled all answers
* empty answers
* new, saved, autosaved form

screenshot_2017-12-14-00-42-11

@opendatakit-bot unlabel "needs testing"

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java [hunk 1]
```diff
@@ -23,23 +23,40 @@
...
+            return DateTimeUtils.getDateTimeLabel((Date) data.getValue(),
+                    DateTimeUtils.getDatePickerDetails(appearance), true, context);
+        }
+
+        if (data instanceof DateData) {
+            return DateTimeUtils.getDateTimeLabel((Date) data.getValue(),
+                    DateTimeUtils.getDatePickerDetails(appearance), false, context);
+        }
+
+        if (data != null && appearance != null && appearance.contains("thousands-sep")) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java:46]: Maybe we should check for null in other cases above too?

**Review by grzesiek2010 — APPROVED** [review]
Just one question, everything else looks good.

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java:46]: Do you mean for the `instanceOf` cases? We're ok there because `instanceOf` is always false when `null` is on the left -- https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.20.2

**Comment by lognaturel** [comment]
Thank you @mmarciniak90, @srv-twry, @grzesiek2010!

@grzesiek2010 if I didn't understand your question let me know and I can address it in another PR.
