### PR TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String

### LINKED ISSUE #1739: Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String
#### Software and hardware versions 
Collect v1.12.0

#### Problem description

> Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:325)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
arrow_drop_down
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
org.odk.collect.android.tasks.DownloadFormsTask.getMd5Hash (DownloadFormsTask.java:758)
org.odk.collect.android.tasks.DownloadFormListTask.doInBackground (DownloadFormListTask.java:233)
org.odk.collect.android.tasks.DownloadFormListTask.doInBackground (DownloadFormListTask.java:52)
android.os.AsyncTask$2.call (AsyncTask.java:305)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/b84b13e4?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

https://play.google.com/apps/publish/?account=6923365842552008664&dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=2608&clusterName=apps/org.odk.collect.android/clusters/b84b13e4&detailsSpan=7

#### Other information 
It's not a big problem, only about 12-14 reports.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1739 

#### What has been done to verify that this works as intended?
Since I wasn't able to reproduce the issue I tested it only with hardcoded null values.

#### Why is this the best possible solution? Were any other approaches considered?
It's just for avoiding NullPointerExceptions.

#### Are there any risks to merging this code? If so, what are they?
No. I just protect form NullPointerExceptions, but downloading forms and displaying a message about available update may be tested just in case.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java [hunk 1]
```diff
@@ -401,7 +401,7 @@ private boolean isThisFormAlreadyDownloaded(String formId) {
     }
 
     private boolean isNewerFormVersionAvailable(String md5Hash) {
-        return new FormsDao().getFormsCursorForMd5Hash(md5Hash).getCount() == 0;
+        return md5Hash != null && new FormsDao().getFormsCursorForMd5Hash(md5Hash).getCount() == 0;
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:404]: I think the version check should take the formID into account. Consider this scenario:
- I have a form with formID form1 and file contents with hash1
- I have a second form with formID form2 and file contents with hash2
- I change the form with formID form1 to have contents with hash2
form1 will not say it has an update available.

This may not be a super likely scenario but this check still seems very strange to me. It's not that we want to see if the hash is in the table at all. We want to see if a specific form's hash matches the remote one.

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java [hunk 2]
```diff
@@ -706,7 +706,7 @@ private String downloadManifestAndMediaFiles(String tempMediaPath, String finalM
                     String currentFileHash = FileUtils.getMd5Hash(finalMediaFile);
                     String downloadFileHash = getMd5Hash(toDownload.getHash());
 
-                    if (!currentFileHash.contentEquals(downloadFileHash)) {
+                    if (currentFileHash != null && downloadFileHash != null && !currentFileHash.contentEquals(downloadFileHash)) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java:709]: The downloadFileHash null check isn't necessary because it's not dereferenced.

**Review by lognaturel — APPROVED** [review]

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:404]: But if you change the form with formID form1 to have contents with hash2 then both forms have the same id an version. It's this case https://github.com/opendatakit/collect/issues/1693 and we can't use both.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:404]: The case I'm talking about is two different IDs but the same form contents. Since we're currently considering formID the differentiator for forms, the test here should ask whether the form with a matching formID has a matching hash rather than asking if the hash is in the table at all.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:404]: But you can't have two forms with different id but the same hash. If you change the id then the hash is different too.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:404]: Ah, because the form does have to contain a matching ID, doesn't it. Ok, I suppose that's ok, then.
