### PR TITLE
Button view is active after refresh cancel

### LINKED ISSUE #1805: User should see buttons on Get Blank Form list even if the list is empty
#### Software and hardware versions 
Collect with https://github.com/opendatakit/collect/pull/1799

#### Problem description
User should see buttons on `Get Blank Form` list even if the list is empty

#### Steps to reproduce the problem
1. User goes to `Get Blank Form`
2. User clicks on Refresh
3. User cancels
4. User sees empty form list:

5. User needs to move back to main screen and again open `Get Blank Form`

#### Expected behavior
* Attached view contains  `Select All` / `Refresh` / `Get selected`
* Only `Refresh` button is active.

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Closes #1805 

#### What has been done to verify that this works as intended?
Tried on Physical Device (Android 5.0 and 6.0) and behaviour found correct 
#### Why is this the best possible solution? Were any other approaches considered?
TextView with id `android:id="@android:id/empty"` automatically understands we're asking if the `Listview` is empty. So whenever list gets empty, textview gets displayed and everything in that view gets invisible.
So to make sure the button view gets visible even after list gets empty I've added `List` and `TextView` in another `LinearLayout`

Another solution could be adding `TextView` and checking whenever adapter gets updated whether the list is empty or not, if it is empty then show `TextView` and make visibilty of `ListView` `Gone.`
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java [hunk 1]
```diff
@@ -437,7 +437,11 @@ protected void updateAdapter() {
         } else {
             ((FormDownloadListAdapter) listView.getAdapter()).notifyDataSetChanged();
         }
-
+        if(filteredFormList.size() > 0){
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java]: The build is failing because of the white space here! Run `./gradlew checkstyle` or look at the build detail artifacts to see the details.

But regardless, you can simplify this by using `toggleButton.setEnabled(filteredFormList.size() > 0)`!

**Review by lognaturel — COMMENTED** [review]
Thank you @lakshyagupta21! This approach works for me. See inline for a quick style comment.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java (hunk 1 above)
Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java]: Thanks @lognaturel for suggesting the changes.

**Review by lognaturel — APPROVED** [review]
