### PR TITLE
Fix layers import view in landscape mode

### LINKED ISSUE #6212: List of layers to import disappears in landscape view
#### ODK Collect version
the master version 6993f66a733c5ce7a8bf758f982c84ccc340fb90

#### Android version
10, 14

#### Device used
Redmi 7, Galaxy M23

#### Problem description
List of layers to import disappears in landscape view, when rotating back to portrait view, list of layers to import is again visible.

#### Steps to reproduce the problem
1. Go to Project settings > Maps
2. Tap on Layer
3. Tap on Add Layers
4. Add any layer
5. Rotate device, while on list of layers to import view

#### Expected behavior
List of layers to import should be visible in landscape view

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6212

This makes the whole layers import view scrollable, but also limits the max height of the list of layers so that it can also remain scrollable in cases with very long lists:

So in landscape we end up with this:

#### Why is this the best possible solution? Were any other approaches considered?

I haven't changed much here at the layout level other than nesting everything in a scroll view, adding a max height to the list and adjusting other parts to compensate for those changes.

Test wise, I've moved our `Interactions` helpers into `test-shared` so I could use them here to deal with clicks that might have to scroll.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only thing changed here is the import list, so that's all that needs to be looked at really!

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt [hunk 1]
```diff
@@ -21,19 +21,21 @@ class OfflineMapLayersImporter(
...
 
-    private lateinit var binding: OfflineMapLayersImporterBinding
-
     override fun onCreateView(
         inflater: LayoutInflater,
         container: ViewGroup?,
         savedInstanceState: Bundle?
     ): View {
-        binding = OfflineMapLayersImporterBinding.inflate(inflater)
+        val binding = OfflineMapLayersImporterBinding.inflate(inflater)
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt:38]: @grzesiek2010 This is something I always forget about! It's dangerous to hold bindings in a field in `Fragment`: https://developer.android.com/topic/libraries/view-binding#fragments.

**Review by lognaturel — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue #6212 doesn't occur
- adding offline layers : scrollable list, progress indicator
- adding offline layers with "don't keep activities" enabled, "no background processes" setting
- dark and light mode
- rotating the screen, minimizing the app
- switching between offline layers, deleting offline layers

**Comment by srujner** [comment]
**Tested with Success!**

Verified on a device with Android 13
