### PR TITLE
Fix issues with incremental question

### LINKED ISSUE #6992: Crash after saving a trace or a shape and tapping the device back button
#### ODK Collect version
the master version d4a41fb8c4ee4ebf98414fc2f557c738baa34246
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There’s a crash after  saving a trace or a shape and tapping the device back button

Image

#### Steps to reproduce the problem
1. Go to All question types form to geoshape or geotrace.
2. Save some points.
3. When moved to the question, tap the device back button (there’s a crash).
4. Go back to the form and recover the savepoint and try to open the map in the question (there’s a crash).

### LINKED ISSUE #6995: Snackbar with constraint message while creating the second point in a polygon
#### ODK Collect version
the master version cba0e5aca791438d0a8813c89f414db94f579910
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There is the snackbar with constraint message while creating the second point in a geoshape

https://github.com/user-attachments/assets/40aababb-a70b-49f9-ab85-994862e8a83a

#### Steps to reproduce the problem
1. Go to the geoshap1e question not intersects question.

[geoshapeTraceInvalidPolygonIncrementalxml.xml](https://github.com/user-attachments/files/24213273/geoshapeTraceInvalidPolygonIncrementalxml.xml)

2. Open the map and select placement by tapping.
3. Add 2 points – check the snackbar

#### Expected behavior
There shouldn’t be a snackbar  while adding the second point in a polygon

### LINKED ISSUE #6996: Snackbar with constraint message disappears after adding another point
#### ODK Collect version
cba0e5aca791438d0a8813c89f414db94f579910
#### Android version
10, 16
#### Device used
Redmi 7, Pixel 6a
#### Problem description
Snackbar with constraint message disappears after adding another point
#### Steps to reproduce the problem
1. Scan user "intersect" from https://test.getodk.cloud/projects/513/app-users
2. Open  geoshapeTraceInvalidPolygonIncremental form
3. Add points to make intersect
4. After making intersect add another point

https://github.com/user-attachments/assets/205110ed-f62c-4ea4-a75d-1e3abb763402

### LINKED ISSUE #6997: Geotrace/geoshape can be saved by using back button
#### ODK Collect version
cba0e5aca791438d0a8813c89f414db94f579910
#### Android version
10, 16
#### Device used
Redmi 7, Pixel 6a
#### Problem description
Geotrace/geoshape can be saved by using back button
Issue does not occur on store version 2025.3.3
#### Steps to reproduce the problem
1.  Scan user "intersect" from https://test.getodk.cloud/projects/513/app-users
2. Open geoshapeTraceInvalidPolygonIncremental form
3. Create any trace or shape and press back button
4. Reopen trace or shape

https://github.com/user-attachments/assets/d0b73969-479c-4b59-bf0c-550a7881a8a3

#### Expected behavior
Geotrace/geoshape should not be saved by using back button

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6996
Closes #6995
Closes #6992
Closes #6997

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot to discuss here. I've just fixed the issues above as well as fixing the problem of `incremental` being read from the wrong place.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The changes are pretty small - I've avoided doing too much refactoring as it's still feeling like the test coverage isn't amazing for the geo poly flow. The main thing to verify is just that the above issues have been fixed and that there isn't any new issues playing around with geo trace/shape with `incremental` both enabled and disabled.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by dbemke** [comment]
I just verified issues and they're fixed.

File: collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt [hunk 1]
```diff
@@ -25,7 +26,7 @@ class GeoPolyDialogFragment(viewModelFactory: ViewModelProvider.Factory) :
         ) { _, result ->
             val geopolyChange = result.getString(GeoPolyFragment.RESULT_GEOPOLY_CHANGE)
             val geopoly = result.getString(GeoPolyFragment.RESULT_GEOPOLY)
-            val incremental = FormEntryPromptUtils.getBindAttribute(prompt, INCREMENTAL)
+            val incremental = FormEntryPromptUtils.getAdditionalAttribute(prompt, INCREMENTAL)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoPolyDialogFragment.kt:29]: Reading a bind attribute was a mistake. `incremental` is a body attribute (https://www.w3.org/TR/xforms20/#ui-input).

**Review by grzesiek2010 — APPROVED** [review]

**Comment by seadowg** [comment]
@dbemke is this "behaviour verified" or is there more you'd like to test?

**Comment by dbemke** [comment]
> is this "behaviour verified" or is there more you'd like to test?

When it comes to issues it's verified, there are some minor issues/question which we'll file when it's merged.
If it's the last PR for the whole invalid polygon feature before the beta then we're still testing -regression testing + exploratory testing.

**Comment by seadowg** [comment]
@dbemke I think we merge this so we can keep the fix PRs relatively small. That keeps the review noise down for @grzesiek2010. We've still got a few features (UX improvements and styling changes) to work on as well as issues, so we're not near the "final" PR yet!
