### PR TITLE
Prevent editing of submissions that failed to send

### LINKED ISSUE #4589: Prevent editing of submissions that failed to send
We've been getting more and more reports of users getting submission errors because the server has already received a submission with the current submission's id but with different XML. From Central, the error message is 

> A submission already exists with this ID, but with different XML. Resubmissions to attach additional multimedia must resubmit an identical xml_submission_file.

See [this forum post](https://forum.getodk.org/t/odk-central-upload-error-a-submission-already-exists-with-this-id-but-with-different-xml/33596) for an example.

I think the majority of these errors would be prevented if we didn't allow editing of submissions that failed to send. I can't think of a downside of doing this -- it really is unexpected that those could be edited. My guess is that data collectors open failed submissions to try to see what could have happened and then save them when they exit which would change the value of an end timestamp if there is one.

Longer-term I think we should stop allowing edits of any finalized forms but that's a much more disruptive change so I'd like us to consider the narrower proposal above first.

### PR DESCRIPTION
**Pull request by dimwight**
Closes #4589

Revives (with improvements) #4629 closed accidentally

#### What has been done to verify that this works as intended?
Tested with new `FormResubmissionTest`.

#### Why is this the best possible solution? Were any other approaches considered?
See design notes as updated below.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Small change to behaviour from user perspective. 
No obvious regression risks. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No form required. 

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
https://github.com/getodk/docs/issues/1367

#### Before submitting this PR, please make sure you have:
- [x ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

-----

#### _`CursorLoaderFactory`_
The single-argument version of `createSavedInstancesCursorLoader` adds `STATUS_SUBMISSION_FAILED` to the filter along with `STATUS_SUBMITTED`.

The two-argument version remains unchanged as it's not obvious how to test it - maybe leave for now?

Preceding methods have been reordered to match the subsequent ones. 
	
#### _`FormResubmissionTest`_
Closely derived from `SendFinalizedFormTest`.
Setting flag `noHttpPostResult` causes a series of calls to `Thread.sleep()`, simulating a connection drop-out.

`whenFailedForm…Resubmission` simulates the server behaviour and tests the updated application response to this. The method
- depends on the `StubOpenRosaServer` detailed below first to set `STATUS_SUBMISSION_FAILED` and then to accept resubmission.
- needs manual intervention as I haven't been able to work out how to simulate clicking on a _CANCEL_ dialog. 
- calls the slightly tweaked `clickViewSentForm` in `MainMenuPage`.

Server response is simulated in the override of `uploadSubmissionAndFiles` in the anonymous `StubOpenRosaServer` passed to the `TestDependencies` in the `RuleChain`.

This necessitated constructors for `TestDependencies` that set the final `StubOpenRosaServer` member.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks! I think some of my inline comments on the prior PR got lost so I'm going to go ahead and push some updates addressing them to this branch.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+                .clickOnForm(TEXT_FORM_NAME)
+                .clickSendSelected()
+                .clickOK(new SendFinalizedFormPage())
+                .pressBack(new MainMenuPage())
+
+                .assertNumberOfEditableForms(0)
+                .clickEditSavedForm()
+                .assertTextDoesNotExist(TEXT_FORM_NAME)
+
+                .clickMenuFilter()
```
Comment (lognaturel) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java:48]: This block tests the `createEditableInstancesCursorLoader` with a `charSequence`.

**Comment by lognaturel** [comment]
@dimwight thanks again for getting this started and do let me know if you have any questions about what I added on. There ended up being three areas that needed to be changed and tested:
- excluding failed submissions from the edit saved form menu without search
- excluding failed submissions from the edit saved form menu with search
- excluding failed submissions from the edit saved form count of editable forms

**Comment by dimwight** [comment]
Fascinating! So much I hadn't even considered in my ignorance, hopefully my input was of some use.

**Comment by lognaturel** [comment]
Yes, thank you! There are a lot of moving pieces and I apologize for underestimating the context required for this one.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+import org.odk.collect.android.support.CollectTestRule;
+import org.odk.collect.android.support.TestDependencies;
+import org.odk.collect.android.support.TestRuleChain;
+import org.odk.collect.android.support.pages.MainMenuPage;
+import org.odk.collect.android.support.pages.SendFinalizedFormPage;
+
+@RunWith(AndroidJUnit4.class)
+public class EditSavedFormTest {
+
+    public static final String TEXT_FORM_NAME = "One Question";
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java]: (Very) Minor nitpick here, but I actually find moving test data into constants like this makes the test harder to read. I think in general, the more of the test that is colocated, the easier it can be comprehended as you don't have to jump anywhere else to see what the input data is. 

Another disadvantage in mind is that it can enforce a consistency that isn't really required. What if I need to use a different form in one of these tests? Do I change all of them?

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java (hunk 1 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java:48]: Could we add a comment to the two blocks to highlight that these could probably be replaced at a lower level when we're moving this data fetching here away from `CursorLoader`? My hope is that whoever is doing that will be running these tests and a comment will make them more likely to transfer that coverage.

Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java:48]: A reply to myself: an alternative would be to move these assertions to a separate test (maybe in a new `EditSavedFormTest`) that checks both cases and also has a comment about it probably being a test that could probably live further down the stack.

**Review by seadowg — APPROVED** [review]
Some little nitpicks around tests (of course) but this looks good and I think it's ready for QA!

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 8.1, 10 and 11.

Verified cases:
- Cancel sending very fast
- Cancel sending when big media attached to form
- sending failed when the server's url invalid
- sending filed when server not working
- Closed-form on Central 
- fill submissions after failed sending
- send submission when first sending try failed
- Aggregate, Central, Google sheet
- missing submission url, invalid submission url
- turn off the internet connection while sending

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java:48]: I went with comments for now. I initially wanted to separate them but these tests take so long that I just can't bring myself to do it for something like this! I agree it should be lower. I do think it's important to include since the initial implementation had a bug around the search behavior.

**Review by seadowg — APPROVED** [review]
