### PR TITLE
Fixed crash caused by deleted media folder

### LINKED ISSUE #4101: Collect crashes when user opens Get blank form view if a folder with media is removed
#### Software and hardware versions 
Collect master

#### Problem description
Collect crashes when user opens Get blank form view if a folder with media is removed

#### Steps to reproduce the problem
1. User downloads form with media
2. Media folder is removed
3. User opens `Get Blank Form`
4. **Collect crashes**

#### Expected behavior
User opens `Get Blank Form` and sees information about available update

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4101

#### What has been done to verify that this works as intended?
I tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It''s just a bug fix that didn't take into account that the file we call `listFiles()` on might not exist. I can't imagine any better solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This fix should just solve the problem and shouldn't affect anything else so testing the scenario from the issue should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java [hunk 1]
```diff
@@ -15,6 +18,32 @@ public void whenThereIsNoFormForgivenFormIdAndVersion_shouldGetAllMethodReturnEm
...
         when(formsDao.getFormMediaPath("1", "1")).thenReturn(null);
 
-        assertThat(new DatabaseMediaFileRepository(formsDao).getAll("1", "1").size(), is(0));
+        assertThat(new DatabaseMediaFileRepository(formsDao, new FileUtil()).getAll("1", "1").size(), is(0));
+    }
+
+    @Test
+    public void whenMediaFolderFileDoesNotExist_shouldGetAllMethodReturnEmptyArray() {
+        FormsDao formsDao = mock(FormsDao.class);
+        FileUtil fileUtil = mock(FileUtil.class);
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: I think we could cut out a lot of the mocking here by having `formsDao.getFormMediaPath` just return a file path to something that doesn't exist.  You could create a temp dir (using `File.createTempDir`) and then return a path of a directory in there (that you don't create). Then we wouldn't need to mock a `File` or `FileUtils` and `listFiles` might even work as just a static helper rather than needing to pass in the util as a dependency. What do you think?

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java [hunk 2]
```diff
@@ -15,6 +18,32 @@ public void whenThereIsNoFormForgivenFormIdAndVersion_shouldGetAllMethodReturnEm
...
+    }
+
+    @Test
+    public void whenMediaFolderFileIsNull_shouldGetAllMethodReturnEmptyArray() {
+        FormsDao formsDao = mock(FormsDao.class);
+        FileUtil fileUtil = mock(FileUtil.class);
+        String formMediaPath = "/samplePath/";
+
+        when(formsDao.getFormMediaPath("1", "1")).thenReturn(formMediaPath);
+        when(fileUtil.getFileAtPath(formMediaPath)).thenReturn(null);
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: I could be missing something but I don't understand how this case can happen? `FileUtil#getFileAtPath` looks like it couldn't return `null`.

**Review by seadowg — CHANGES_REQUESTED** [review]
I think the tests need a bit of rework/discussion here. I'll mark this as ready for testing as I think the core logic change makes sense.

@getodk-bot label "needs testing"

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: Theoretically you are right but after fixing bugs like https://github.com/getodk/collect/issues/4102 I'm trying to check more than usually. Is that bad? Those are just tests so I think it's ok to tests **more** sometimes.

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: But then we would need to move this test to android tests you you want to check if a file really exists or not. Would that improve anything?

Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: It should work in normal `test` as we're just using `File` rather than any Android specific code right? I think if you just have `FormsDao#getFormMediaPath` return `"/samplePath/"` (like you're doing) then the as that path doesn't exist you should end up creating the environment you need to check that `getAll` returns an empty list.

File: collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java (hunk 2 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java]: Yeah true. I guess I'm thinking about if we've not mocked `FileUtil` as we have we can't guarantee that the method won't return `null` from this test.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids:5.1, 7.1 and 9
Tested cases:
- scenario from issue before migartion
- scenario from issue after migartion
- download before migaration, delete after
- download and delete before migration
- the same scenarios with filled submission

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Review by seadowg — APPROVED** [review]
