### PR TITLE
Fixed refreshing the list of forms

### LINKED ISSUE #5331: List of forms might be not updated in match exactly mode
#### Problem description
List of forms might be not updated in match exactly mode after going to the list of forms if we do that when the process of downloading forms is not finished.

#### Steps to reproduce the problem
1. Add a new project with a big form so that downloading will take some time
2. Go to the list of blank forms
3. Wait for the downloading to finish (you will see a progress bar disappearing)

#### Expected behavior
The list of forms should be updated.

#### Other information 
The issue has been originally reported on the forum: https://forum.getodk.org/t/formlist-refresh-bug-in-collect/39346

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5331

#### What has been done to verify that this works as intended?
I've tested the fix manually and added an automated test.

#### Why is this the best possible solution? Were any other approaches considered?
I've just added missing reloading of the list of forms after finished syncing with server. Not much to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I haven't implemented a lot of changes so generally the fix should be safe but please verify that the list of forms is updated in all expected cases:
- immediately after opening the list of forms
- after syncing with storage (this is triggered automatically after opening the list)
- after syncing with server in both cases if triggered automatically after adding a new project / after triggering by a user by clicking the refresh icon (it worked well only in the second case) 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt [hunk 1]
```diff
@@ -187,6 +186,9 @@ class BlankFormListViewModel(
             syncRepository.isSyncing(projectId)
         ) { isSyncing ->
             isSyncingWithServerRunning.value = isSyncing
+            if (!isSyncing) {
+                loadFromDatabase()
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt]: We really shouldn't have code with side effects in `map` calls in general (as it can cause unexpected results), but it's definitely a problem here due to `isSyncingWithServer` returning a new `LiveData` as the result of a `map` call every time. This would mean that when the value of `syncRepository.isSyncing(projectId)` switches from `true` to `false` we would call the side effects (`loadFormDatabase` and the update to `isSyncingWithServerRunning`) once for every time we've called `isSyncingWithServer`. I'd completely missed the interaction with  `isSyncingWithServerRunning` in here when we introduced the `BlankFormListViewModel`, but should have brought this up then.

This implementation initially confused me as well as it requires `isSyncingWithServer` to have been called (and the result observed) at least once for `formsToDisplay` or `isLoading` to be updated correctly which feels surprising. Here's a test that demonstrates the problem:

```kotlin
@Test
fun `isLoading is true while syncing`() {
    val syncing = MutableLiveData(false)
    whenever(syncRepository.isSyncing(projectId)).thenReturn(syncing)

    createViewModel()
    assertThat(viewModel.isLoading.getOrAwaitValue(), equalTo(false))

    syncing.value = true
    // viewModel.isSyncingWithServer().observeForever { }
    assertThat(viewModel.isLoading.getOrAwaitValue(), equalTo(true))
}
```

That test fails, but it will pass if I uncomment the second last line. This will all work in the app as we happen to call the right methods in the right order, but it could definitely cause problems later on if we move things around. I think should move things around so that `isLoading` and `formsToDisplay` aren't dependent on `isSyncingWithServer` being called. A few thoughts on that:

- Why do we need `isSyncingWithServer` and `isLoading`? I feel like there's an answer on the tip of my tongue, but I can't quite get to it.
- We can probably just use `SyncRepository#isSyncing` in the zip that defines `isLoading` instead of needing a separate `isSyncingWithServerRunning` field.
- To fix #5331, I think `SyncRepository#isSyncing` could be used with `observerForever`/`removeObserver`/`ViewModel#onCleared` to perform a db load whenever there isn't a sync in progress from `BlankFormListViewModel`. We definitely want a structure like `InstancesAppState` in place for blank forms down the line. Not sure if that's the easiest thing right now though.
- As far as I can see there aren't any tests for `isLoading` at the moment. We should add those (like the above example) here.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt]: > Why do we need isSyncingWithServer and isLoading? I feel like there's an answer on the tip of my tongue, but I can't quite get to it.

We need both `isSyncingWithServer` and `isOutOfSyncWithServer` because based on changes we update icons in `BlankFormListMenuDelegate`. 

> We can probably just use SyncRepository#isSyncing in the zip that defines isLoading instead of needing a separate isSyncingWithServerRunning field.

No because as I said above it's used in `BlankFormListMenuDelegate` as well.

> We really shouldn't have code with side effects in map calls in general (as it can cause unexpected results)

I thought the same but as this structure already exist and is needed (see above) I decided to use it.

**Comment by seadowg** [comment]
> We need both isSyncingWithServer and isOutOfSyncWithServer because based on changes we update icons in BlankFormListMenuDelegate.

Totally understand `isOutOfSyncWithServer()`, but I think we could potentially just use `isLoading` instead of `isSyncingWithServer()`. The meaning is slightly different, but I think it would make possibly even more sense to use `isLoading` where we currently use `isSyncingWithServer()`: disabling the refresh icon if we're "syncing".

> No because as I said above it's used in BlankFormListMenuDelegate as well.

I think I explained what I meant badly. I mean instead of having the `isSyncingWithServerRunning` at all. The implementation of `isSyncingWithServer()` could just be:

```kotlin
fun isSyncingWithServer(): LiveData<Boolean> {
    return syncRepository.isSyncing(projectId)
}
```

And `isLoading` could then be:

```kotlin
val isLoading: LiveData<Boolean> = Transformations.map(
    LiveDataUtils.zip3(
        isFormLoadingRunning,
        isSyncingWithStorageRunning,
        syncRepository.isSyncing(projectId),
    )
) { (one, two, three) -> one || two || three }
```

#5331 could be solved using an `observeForever` (and using `removeObserver` in `onCleared`) to always load from the db after a sync finishes:

```kotlin
init {
    loadFromDatabase()
    syncWithStorage()

    syncRepository.isSyncing(projectId).observeForever {
       if (!it) {
           loadFromDatabase()
       }
    }
}
```

**Comment by grzesiek2010** [comment]
@seadowg I've improved the implementation according to your comments. Please take a look.

**Review by seadowg — APPROVED** [review]
👍 Looks great! It would be good to add tests for `isLoading` if you get a chance, but we can definitely merge without them. This should be ready for QA now.

**Comment by srujner** [comment]
**Tested with Success!**

Verifed on Androids 12, 13

Verified Cases:
- Issue #5331 is no longer reproducing;
- Loading the Fill Blank Form list with small and big amount of forms;
- Refreshing the list of forms;
- Match Exactly;
- Automatic and Manual download updated versions of forms;
- Automatic and Manual download the list of forms;
- Rotating the screen and minimizing the app during forms loading;
- Light and Dark mode;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 8.1, 10
