### PR TITLE
Make Form subtext translatable

### LINKED ISSUE #3026: Form subtext should be translated on the currently set language in Collect
#### Software and hardware versions 
Verified Collect v1.19.0 and 1.21.1
Different behavior on Android version >= 7.0 and <= 6.0

#### Problem description
Form subtext should be translated on the currently set language in Collect

#### Steps to reproduce the problem
1. User sets the English language on Collect
2. User downloads form - form has `Added on ... ` information under the form name
3. User sets the Spanish language on Collect
4. User downloads form
5. User sets the French language on Collect
6. User downloads form

### Android 7.0 and newer
* `Added` is never translated
* Only date is translated

| | |
|---|---|
|Screenshot_20190418-071240|Screenshot_20190418-071733|

### Android 6.0 and older
* Subtext is translated on the language which was set during downloading

| | |
|---|---|
|Screenshot_20190418-070843|Screenshot_20190418-070853|

#### Expected behavior
* The same behavior on all Android versions
* Subtext should be translated on the currently set language in Collect

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3026 

#### What has been done to verify that this works as intended?
- tested installing apk with database v7 on v6 and v6 on v7
- tested the content of form subtext

#### Why is this the best possible solution? Were any other approaches considered?
I decided to remove `displaySubtext` which keeps an untranslatable form subtext and use `date` column to create such subtext dynamically (to make it translatable). `date` column stores downloading dates so it's the same value as in `displaySubtext`. There is no need to use the `displaySubtext` column.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I upgraded the forms database version so it's a thing that should be carefully tested, upgrading/downgrading @mmarciniak90 I'm counting on your creativity here.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — DISMISSED** [review]

**Comment by lognaturel** [comment]
Ahh, I understand why I thought this was a hard problem and you didn't! I was thinking of form and instance subtext as the same problem. Instance subtext is the hard one because instances have different states that they can be in. But it's true that they can be split and that fixing the form case is a great start.

File: collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    private final ViewBinder originalBinder;
+
+    public VersionHidingCursorAdapter(String versionColumnName, Context context, int layout,
+            Cursor c, String[] from, int[] to) {
+        super(context, layout, c, from, to);
+        ctxt = context;
+        originalBinder = getViewBinder();
+        setViewBinder((view, cursor, columnIndex) -> {
+            String columnName = cursor.getColumnName(columnIndex);
+            if (columnName.equals(FormsProviderAPI.FormsColumns.DATE) || columnName.equals(FormsProviderAPI.FormsColumns.MAX_DATE)) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java:49]: Adding `MAX_DATE` to the API explicitly seems odd to me because it's not a column name. Can you leave the call on `max` in `FormsProvider` like you had it before and do a check for `columnName.contains(FormsColumns.DATE)` here? It's still odd because a call on `.getColumnName` returns a function call but at least it's isolated here.

**Comment by lognaturel** [comment]
There's one decision I have a question about described inline (`MAX_DATE`). Please mark for testing once you've considered it.

Also, is there any benefit to minimizing the number of migrations and doing the instance fix in the same one? I don't think so but wanted to ask.

File: collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java:49]: I added a comment that it is used only to get latest forms for each form_id.
`columnName` is a String so I can't call `contains()` on it I could use `cursor.getColumnNames()` but it returns String[] so also suing  `contains()` is not possible I would need to convert it and it would require more code.
If could just remove the last commit at all and use `MAX(" + FormsProviderAPI.FormsColumns.DATE + ")` but I don't think it's better.

**Comment by grzesiek2010** [comment]
> Also, is there any benefit to minimizing the number of migrations and doing the instance fix in the same one?

You mean not bumping the forms db version and just removing the redundant column? I was thinking about the same but it might cause problems like:
1. Install a fresh app, you will have forms db v6 but without `displaySubtext` column
2. Downgrade your app to v1.22.4 - it's the same forms db version (not lower) so onDowngrade() won't be called you won't have `displaySubtext` column but the code will require it.

File: collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java:49]: > columnName is a String so I can't call contains() on it

https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#contains-java.lang.CharSequence- Am I misunderstanding?

**Comment by lognaturel** [comment]
> You mean not bumping the forms db version and just removing the redundant column?

I agree that all changes to the database should result in a version bump. I meant combining it with the instance migration from #3200 but I forgot that they're not even in the same database so that doesn't make sense, sorry.

Adding `createFormsTableV7` makes sense for the "install from scratch" case. But can you avoid it in the 6->7 upgrade case and simply remove the column rather than recreating the table?

**Comment by grzesiek2010** [comment]
> simply remove the column

there is no such thing like removing a column in sqlite I need to recreate the table https://stackoverflow.com/a/8442173/5479029

Or maybe you mean to keep the column migrating from 6>7?

**Comment by lognaturel** [comment]
> there is no such thing like removing a column in sqlite I need to recreate the table stackoverflow.com/a/8442173/5479029

👎👎👎I didn't know that! Then this seems like the best that can be done. Thanks for the reference.

File: collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java:49]: Ok got it I thought you mean contains() on the array of columns to determine if it contains `date` or `MAX(date)`... 
but still, I will need to use `"MAX(" + FormsColumns.DATE + ")"` not only in FormsProvider but also here https://github.com/opendatakit/collect/pull/3193/files#diff-af25ce4b576502ac52785c5d4cd8a844R174

isn't it more confusing?

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/adapters/VersionHidingCursorAdapter.java:49]: I don't feel strongly about it.

**Review by lognaturel — APPROVED** [review]

**Comment by bognasoldev89** [comment]
*Tested with success*

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases:
- Form subtext should be translated on the currently set language in Collect
- Tested on the most translated languages
- Tested on the least translated languages
- On every Android languages changed numerous times
- On every Android forms downloaded numerous times after changing language

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
Thanks, @bognasoldev89 for testing basic test cases. 
I will check cases with upgrading/downgrading.

@opendatakit-bot label "needs testing"
@opendatakit-bot unlabel "behavior verified"

**Comment by mmarciniak90** [comment]
**Tested with success**

**Verified on Android:** 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified upgrade from v1.22.2, v1.23-beta and v1.13.0.
Downgrade the application is not possible.

During upgrades, I manipulated language in ODK and language in the device as well
Also, confirm that form subtext translatable. Changes are visible on the `Fill Blank Form` page and `Delete Saved Form -> Blank Forms`

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
