### PR TITLE
Fixed calculating progress for the NumberPicker

### LINKED ISSUE #5408: In range picker widget after opening the spinner the value shown is different form the value that was already chosen
#### ODK Collect version
The current master 83d5b82a51de96d0483d433a5475e3ff043bf0b6, the store version
#### Android version
10, 11, 13
#### Device used
Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
After going to the hierarchy view or swiping to the next question and back a chosen answer in the range picker widget is different from  value shown after opening the spinner if in the form the range is set to start from the higher value and end with a lower value (e.g.start=10;end=1;step=1).
#### Steps to reproduce the problem
1. Go to rangewidgetendotstart.xlsx
[rangewidgetendotstart.xlsx.txt](https://github.com/getodk/collect/files/10447649/rangewidgetendotstart.xlsx.txt)
2. Go to range picker widgets.
3. Tap "Select value”.
4. Choose a number and tap "ok”
5. Swipe to the next question.
6. Go back to the range picker questions.
7. Tap "Edit value”
8. Compare the chosen number with the number shown in the spinner.
#### Other information 
The issue is not present in Collect v2022.3.0

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5408 

#### What has been done to verify that this works as intended?
I've added automated tests and verified the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
It's just a bug fix so nothing to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should only fix the issue and not cause any other bugs but be careful similar issues might be around.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtils.kt [hunk 1]
```diff
@@ -32,4 +33,18 @@ object RangePickerWidgetUtils {
 
         return displayedValuesForNumberPicker.toTypedArray()
     }
+
+    @JvmStatic
+    fun getProgressFromPrompt(prompt: FormEntryPrompt, listOfValues: Array<String>): Int {
+        var actualValue: BigDecimal? = null
+        val answerValue = prompt.answerValue
+        if (answerValue != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/range/RangePickerWidgetUtils.kt:41]: It would be good to add a test to drive this (and the below) `if` statement out. I think there's only one case (`null` answer value on `prompt`) that actually requires them both.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android: 13

**Verified Cases:**

- Issue #5408 is no longer reproducing;
- checking the chosen values after going to the hierarchy view, swiping, rotating, minimizing, locking the screen;
- don’t keep activities enabled /disabled;
- RTL;
- dark/light mode;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android: 10
