### PR TITLE
Handle NPE in DatabaseMediaFileRepository#getAll()

### LINKED ISSUE #4034: NPE in DatabaseMediaFileRepository.java line 15
#### Software and hardware versions 
Collect v1.28.0-beta

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/776021de55f48298e0fedd54d67f76c5?time=last-seven-days&sessionId=5F4244EC034300015F9A81F660321501_DNE_0_v2

```
Caused by java.lang.NullPointerException
       at java.io.File.<init>(File.java:283)
       at org.odk.collect.android.forms.DatabaseMediaFileRepository.getAll(DatabaseMediaFileRepository.java:15)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.areNewerMediaFilesAvailable(ServerFormsDetailsFetcher.java:122)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.fetchFormDetails(ServerFormsDetailsFetcher.java:72)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:63)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:39)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4034

#### What has been done to verify that this works as intended?
I reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
The issue was caused by null `formMediaPath`. if that value is null and we call `newFile(formMediaPath)` NPE is thrown. Another solution would be to catch that exception but since we now what is the cause its' a better approach to just avoid it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think this doesn't require testing. A review from another contributor should be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@seadowg 
I'm thinking about that class `DatabaseMediaFileRepository` you have created. Shouldn't that be one class with `DatabaseFormsRepository`? It uses the same database and at this moment contains just one method so what was the rationale for creating a separate repository class?

**Comment by seadowg** [comment]
@grzesiek2010 I guess my thinking here was that the two different repositories are for fetching two distinct "entities": "forms" and "media files". I could see it being one repository though if you just think of the media files as a part of the form rather than a related to the form. My assumption is that some parts of the code care about the forms and not the media files and vice versa but that could totally be wrong! 

I guess if nothing else it feels like a nice split to me to avoid the interfaces getting too large.

File: collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java [hunk 1]
```diff
@@ -12,7 +12,10 @@
     @Override
     public List<File> getAll(String jrFormID, String formVersion) {
         String formMediaPath = new FormsDao().getFormMediaPath(jrFormID, formVersion);
-        File[] files = new File(formMediaPath).listFiles();
+        File[] files = new File[0];
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java]: I think we could avoid the array initialization here with an `if-else` on the `formMediaPath != null` and just returning `emptyList` in the `else` case. The `new File[0]` going into the `asList` confused me.

File: collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java [hunk 2]
```diff
@@ -12,7 +12,10 @@
...
+        if (formMediaPath != null) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java]: I think we need a test to drive this out so we avoid regressing at any point. As far as I can see the situation that gives us the NPE (for the previous code) was if `getAll` was queried for a `jrFormID` and `formVersion` not in the database. If that's right we could have a `DatabaseMediaFileRepositoryTest` similar to the `DatabaseFormRepositoryTest` and a test that just checks we get back an empty list when there is nothing in the database.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java]: Done.

File: collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/forms/DatabaseMediaFileRepository.java]: Done.

**Comment by grzesiek2010** [comment]
> I guess my thinking here was that the two different repositories are for fetching two distinct "entities": "forms" and "media files".

I'm not sure about it but we can leave it as is for now and we will see how it evolves.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 looks like the last PR merged added a conflict but this looks good to go!

@getodk-bot label "needs testing"

**Comment by seadowg** [comment]
@grzesiek2010 oh sorry you'd pointed out we could probably skip QA on this one and I think I agree. If you fix the conflicts I'll merge!

**Comment by grzesiek2010** [comment]
> If you fix the conflicts I'll merge!

fixed.
