### PR TITLE
Fix #1552. Pictures taken by the SelfieWidget are rotated incorrectly on some devices.

### LINKED ISSUE #1552: Pictures taken by the SelfieWidget are rotated incorrectly on some devices
#### Software and hardware versions 
Collect v1.10.2

#### Problem description
Pictures taken by the SelfieWidget are rotated incorrectly on some devices.

#### Other information 
This table is from https://github.com/opendatakit/collect/pull/1541 so it might look a little different on v1.10.2 but the problem is visible there too and once we have merged #1541 it will look the same.

| case/device  | Samsung S7 | huawei | sony z3 | samsung J1 | infinix | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| image widget, front camera, vertical | vertical | vertical | vertical | vertical | vertical |
| image widget, front camera, horizontal | horizontal | horizontal | horizontal | horizontal | horizontal |
| selfie widget, front camera, vertical | vertical | vertical | vertical | horizontal | horizontal |
| selfie widget, front camera, horizontal | crash  | upside down | upsiede down | horizontal | horizontal |

### PR DESCRIPTION
**Pull request by ShenJack**
Closes #1552

What has been done to verify that this works as intended?
Fix #1552. Pictures taken by the SelfieWidget are rotated incorrectly on some devices

Why is this the best possible solution? Were any other approaches considered?
Using official api, and maybe the least code, actually I‘ve just change some number and experession.

Are there any risks to merging this code? If so, what are they?
Maybe not support devices whose front camera isn't 270, I don’t have devices like that.

Do we need any specific form for testing your changes? If so, please attach one.
Test it on more devices, especially whose front camera isn't 270° placed.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 1]
```diff
@@ -82,15 +82,34 @@
     /**
      * Conversion from screen rotation to JPEG orientation.
      */
+
+    /*
+     * For front camera only.
+     * Bug fixed on 2018.2.17.
+     */
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: I don’t think this comment adds much value, especially the note about the bug fix. We have issues, pull requests, and commit histories to record when bugs are fixed.

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 2]
```diff
@@ -82,15 +82,34 @@
...
+    *
+    * static {
+    * ORIENTATIONS.append(Surface.ROTATION_0, 90);
+    * ORIENTATIONS.append(Surface.ROTATION_90, 0);
+    * ORIENTATIONS.append(Surface.ROTATION_180, 270);
+    * ORIENTATIONS.append(Surface.ROTATION_270, 180);
+    * }
+    *
+    * For front camera, we use this:
+    * */
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: I don’t see any value in this comment. The old values will be in the commit history. The doc comment is malformed and misplaced.

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 3]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
      *
      * @param rotation The screen rotation.
      * @return The JPEG orientation (one of 0, 90, 270, and 360)
+     * <p>
+     * Back Sensor orientation is 90 for most devices, or 270 for some devices (eg. Nexus 5X)
+     * Front Sensor is normally 270.
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: The back sensor .... (end with period)
The front sensor ...

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 4]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
...
+     * <p>
+     * Following code use only for back camera , not suitable for front camera
+     * {@code return (ORIENTATIONS.get(rotation) + sensorOrientation + 270) % 360;}
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: No need to record here what the code was.

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 5]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
...
+     * <p>
+     * <p>
+     * The final degrees the jpeg need to be rotated will be the sum degrees of screen orientation and
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: The final angle the JPEG needs to be rotated is the sum of the screen orientation angle and the {@link CameraDevice }'s orientation angle. Just like the code below. And orientation is always the angle something needs to rotated clockwise to be upright.

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 6]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
...
+     * {@link CameraDevice } 's orientation.Just like the code below.
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: Space after period, and perhaps not before the apostrophe?

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 7]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
...
+     * And orientation is always the degrees something needs to rotate clockwise to be upright.
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: ... always the number of degrees ...
or
... always the angle (in degrees) ...

File: collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java [hunk 8]
```diff
@@ -819,13 +838,23 @@ public void onCaptureCompleted(@NonNull CameraCaptureSession session,
...
      */
     private int getOrientation(int rotation) {
-        // Sensor orientation is 90 for most devices, or 270 for some devices (eg. Nexus 5X)
-        // We have to take that into account and rotate JPEG properly.
-        // For devices with orientation of 90, we simply return our mapping from ORIENTATIONS.
-        // For devices with orientation of 270, we need to rotate the JPEG 180 degrees.
-        return (ORIENTATIONS.get(rotation) + sensorOrientation + 270) % 360;
+
+        // After bug #1552 fixed on 2018.2.17, we use this orientation expression to amend the camera direction.
```
Comment (dcbriccetti) [inline collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java]: No need to mention the bug fix.

**Review by dcbriccetti — CHANGES_REQUESTED** [review]
Hi! I can confirm that this fixes an upside-down problem when in landscape orientation, on my Nexus 7. I made some suggestions about your comments. Others who know more about this code should also review.

**Comment by ShenJack** [comment]
@dcbriccetti Thanks for your reminder, I'll make changes right away.

**Review by dcbriccetti — APPROVED** [review]
Thanks, @ShenJack. OK, now an Android expert review, please?

**Review by grzesiek2010 — APPROVED** [review]
It should be tested carefully on different devices so I'm going to approve and let our QA test it.

**Comment by mmarciniak90** [comment]
**Not all cases are resolved.** 
Despite that, I would suggest to merge this PR because it fixes problem on higher Android versions which are more popular than Android 4.4 and 4.1. I can create a separate issue for mentioned Android versions.
It will be good to have this in newest Collect version.

@S2606 @lognaturel 

| case/device  | Nexus 5X | Samsung S7 | Sony z3 | Nexus 5 | Huawei | Samsung J1 | Infinix | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Android | 8.0 | 7.0 | 6.0 | 6.0 | 5.1 | 4.4 | 4.2 |
| selfie widget, front camera, vertical device orientation | vertical | vertical |vertical |vertical | vertical | **horizontal** | **horizontal** |
| selfie widget, front camera, horizontal device orientation | horizontal | horizontal | horizontal | horizontal | horizontal | horizontal | horizontal |

@opendatakit-bot label "needs discussion"

**Comment by shobhitagarwal1612** [comment]
@ShenJack  @grzesiek2010 This PR only fixes the orientation issue in the `Camera2Fragment` class. And if we look at this [line](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L169), it is clearly defined that for devices running Android Lollipop (5.0) and above, the `CameraSelfieActivityNewApi` is being used(which uses `Camera2Fragment`) and for other devices `CameraSelfieActivity` is being used (which uses Camera api v1). So that's why, the fix didn't work for Android 4.4 and 4.1 devices.

**Comment by lognaturel** [comment]
Thanks for taking this on @ShenJack and for the explanation for why the fix is partial, @shobhitagarwal1612. I agree with @mmarciniak90, let's merge this and file an issue for Android <=4.4.

**Comment by mmarciniak90** [comment]
New issue #1900 is created.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs discussion"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
