### PR TITLE
Fixed styling required questions

### LINKED ISSUE #5281: Some styling might not work with required questions
#### Problem description
Some styling might not work with required questions. 

#### Steps to reproduce the problem
1. Open the attached form: [Required-style.xlsx](https://github.com/getodk/collect/files/9564256/Required-style.xlsx)
2. Go to the third question - [headers](https://docs.getodk.org/form-styling/#headers) do not work well

#### Expected behavior
Styling should work well no matter if a question is required or not

#### Other information 
The problem has been originally reported on the forum: https://forum.getodk.org/t/required-option-ruins-headers-in-odk-collect/38953/2

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5281 

#### What has been done to verify that this works as intended?
I've tested the fix manual and added an automated test.

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that we were styling question labels with the asterisk mark (that represents required questions) as a one text. As a result styling headers with `#` (or `####` like in the issue) was broken because the first element in such a question label was `*` not `#`. If we style text with `#` it must start with it and if we need something more complex like mixing normal text with headers we can use `<h4>` tags.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test styling questions labels displayed in a form and in the hierarchy view. We also support styling other elements not only questions but the risk here is just related to questions.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used [Required-style.xlsx](https://github.com/getodk/collect/files/9570037/Required-style.xlsx)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt [hunk 1]
```diff
@@ -28,6 +28,14 @@ class FormStylingTest {
             .assertText("Note text")
     }
 
+    @Test
+    fun requiredQuestionLabelWithHeaderStyleTest() {
+        rule.startAtMainMenu()
+            .copyForm(FORM_FILE_NAME)
+            .startBlankForm(FORM_NAME)
+            .swipeToNextQuestion("Required text question with header style", true)
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt:36]: We need to assert on the question in the hierarchy as well for this case. Alternatively, we could remove this test and just add a test for `styledQuestionText` which I think might be preferrable.

**Review by seadowg — DISMISSED** [review]

**Review by seadowg — CHANGES_REQUESTED** [review]
See comment

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt:36]: We have a separate test for the hierarchy so I've added it there.

> Alternatively, we could remove this test and just add a test for styledQuestionText which I think might be preferrable.

I was also thinking about it but the fact that method works well doesn't mean we display such styled strings properly. It's tricky and we might for example convert `CharSequence` to `String` after using that method and break it. That's why I preferred to have a UI test.

**Comment by dbemke** [comment]
[Required-style2.xlsx](https://github.com/getodk/collect/files/9819047/Required-style2.xlsx)
[styletest.xlsx](https://github.com/getodk/collect/files/9819048/styletest.xlsx) (without required questions)

I've created 2 forms to compare styling for required and not required questions and there is a difference for centered labels. In required question the label is not centered (also not in the hierarchy view).
centered

**Comment by grzesiek2010** [comment]
Is that regression compared to master? If not please file a separate issue.

**Comment by dbemke** [comment]
On master required question is centered but it also has some extra space, but the space is present also in other questions (not centered).
master

**Comment by grzesiek2010** [comment]
Ok now it should work well.

**Comment by dbemke** [comment]
**Tested with Success!**
Verified on Android: 10, 13

**Verified cases:**
- issue #5281 and central alignment issue are no longer reproducing
- styling in required and non-required questions
- labels and hints styling
- select one styling
- headers created with # and \<h1>
- paragraphs
- bold and italic styling created with _ and *
- including hyperlinks
- fonts and colors
- centered alignment
- including literal asterisks, underscores, slash, hash
- validate upon forward swipe, defer validation until finalized
- message in required question
- hierarchy view
- regression checks for required questions

**Review by seadowg — APPROVED** [review]
