### PR TITLE
Fixed date display issue (#2683) for languages other than EN(US)

### LINKED ISSUE #2683: Gregorian date in Islamic/Coptic/Ethiopian/Nepali date widget should be visible in the language which is set in device
#### Problem description
Gregorian date in Islamic/Coptic/Ethiopian/Nepali date widget should be visible in the language which is set in device

#### Steps to reproduce the problem
1. The user has set other device language than English
2. The user adds date to Islamic/Coptic/Ethiopian or Nepali date wigdet
3. Gregorian date is visible in English 

| | | |
|---|---|---|
|screenshot_20181024-133933|screenshot_20181024-133926|screenshot_20181024-133921|

#### Expected behavior
Gregorian date should be visible in the language which is set in the device

### PR DESCRIPTION
**Pull request by ajwad-shaikh**
Closes #2683 

#### What has been done to verify that this works as intended?
Tested on local device Moto G5 Plus

#### Why is this the best possible solution? Were any other approaches considered?
Minimal Changes to existing code. Conforms to Android best practices.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
None.

#### Do we need any specific form for testing your changes? If so, please attach one.
None.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Nope.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
Thanks for your contribution! 

In fact, this is the only change you need https://github.com/opendatakit/collect/pull/2745/files#diff-d8855c7830570c1dcfbc871ef248f64eR54

additionally, you decided to change the way we display months before it was eg. dec and now it's full December. If you think we should change it please file another issue because this one is not about it so you shouldn't implement such a change.

File: collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java [hunk 1]
```diff
@@ -134,7 +134,7 @@ public static DatePickerDetails getDatePickerDetails(String appearance) {
         DatePickerDetails.DatePickerType datePickerType = DatePickerDetails.DatePickerType.GREGORIAN;
         DatePickerDetails.DatePickerMode datePickerMode = DatePickerDetails.DatePickerMode.CALENDAR;
         if (appearance != null) {
-            appearance = appearance.toLowerCase(Locale.US);
+            appearance = appearance.toLowerCase(Locale.getDefault());
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: This change is not related to the way we display dates. it should be `Locale.US` like before because we use English words for appearances so we shouldn't use any other languages in `toLowerCase`.

**Comment by ajwad-shaikh** [comment]
@grzesiek2010  Thanks for the review!

**I am reverting changes to the line 48 and line 137 following your recommendation.**

I had earlier filed a PR that had to be closed because it was too dirty. However, before I pushed a lot of unchecked commits that made a mess of it, @zestyping had reviewed it and recommended changes to the datePattern variable. 
Please find the discussion here -> https://github.com/opendatakit/collect/pull/2736#discussion_r234897553

```
The method name getDateTimePattern and variable name datePattern are misleading, then—this string is not a date pattern; it is a skeleton. Could you rename the method to getDateTimeSkeleton and rename the variable to skeleton?
```

If there's anything else, please let me know

File: collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java (hunk 1 above)
Comment (ajwad-shaikh) [reply collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: Fixed in latest commit. Thanks for pointing out! 😄

File: collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java [hunk 2]
```diff
@@ -104,19 +104,19 @@ private static String getCustomDateTimeLabel(Date date, DatePickerDetails datePi
         return String.format(context.getString(R.string.custom_date), customDateText, gregorianDateText);
     }
 
-    private static String getDateTimePattern(boolean containsTime, DatePickerDetails datePickerDetails) {
-        String datePattern;
+    private static String getDateTimeSkeleton(boolean containsTime, DatePickerDetails datePickerDetails) {
+        String dateSkeleton;
         if (containsTime) {
-            datePattern = "yyyyMMMdd HHmm";
+            dateSkeleton = "yyyyMMMMdd HHmm";
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: Why do we need this change in months? Isn't it because before you used full month names? (the previous commit) now it would be unnecessary I think.

Comment (ajwad-shaikh) [reply collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: The Method `getBestDateTimePattern` on line 45 to which the skeleton is passed return the Best Possible Date Time Pattern depending upon the locale. During testing, I found out that the function returns shorter month names even with `MMMM` in the `dateSkeleton`
Refer -> https://developer.android.com/reference/android/text/format/DateFormat#getBestDateTimePattern(java.util.Locale,%20java.lang.String)
The only reason I added an `MMMM` instead of  `MMM` is that `MMM` are not as common in other locales especially the vernacular ones as much as in EN(US) and MMMM is a still a standard. The output remains the same for EN(US) as I have tested but it may give better results for other locales

Comment (ajwad-shaikh) [reply collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: Quoting the Docs

> public static String getBestDateTimePattern (Locale locale,
> String skeleton)
> 
> Returns the best possible localized form of the given skeleton for the given locale. A skeleton is similar to, and uses the same format characters as, a Unicode UTS#35 pattern.
> 
> One difference is that order is irrelevant. For example, "MMMMd" will return "MMMM d" in the en_US locale, but "d. MMMM" in the de_CH locale.
> 
> Note also in that second example that the necessary punctuation for German was added. For the same input in es_ES, we'd have even more extra text: "d 'de' MMMM".
> 
> This method will automatically correct for grammatical necessity. Given the same "MMMMd" input, this method will return "d LLLL" in the fa_IR locale, where stand-alone months are necessary. Lengths are preserved where meaningful, so "Md" would give a different result to "MMMd", say, except in a locale such as ja_JP where there is only one length of month.
> 
> This method will only return patterns that are in CLDR, and is useful whenever you know what elements you want in your format string but don't want to make your code specific to any one locale.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java]: Ok, I see.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.4, 5.1, 6.0, 7.0 and 8.1. However, I can see that now whole month name is displayed (December) but it used to be a 3 letter shortcut (Dec) I don't think is a bad thing.
I've checked English, German, Spanish, Italian and Polish. 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by grzesiek2010** [comment]
Ahhh I thought you get rid of that change (full month names) but it still occurs so you need to remove those changes in months (additional M) as well.
I'm not sure which version of month names is better but I'm sure that change is not a part of the issue so you can file another one if you really think it should be changed.

**Comment by grzesiek2010** [comment]
@ajwad-shaikh 

Do you have time to fix the issue with month names?

**Comment by ajwad-shaikh** [comment]
@grzesiek2010 Ah, I'll definitely be reverting the unnecessary changes. Apologize for the delay

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
Thanks @ajwad-shaikh 
@kkrawczyk123 please continue testing.

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed!
Verified on Androids 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by kkrawczyk123** [comment]
@opendatakit-bot label "behavior verified"

**Comment by grzesiek2010** [comment]
Thanks @ajwad-shaikh @kkrawczyk123
