### PR TITLE
Fixed starting First Launch Screen

### LINKED ISSUE #4538: First Launch Screen appears every time the app is started if the app is newly installed (not upgraded)
#### Software and hardware versions 
Master branch

#### Problem description
First Launch Screen appears every time the app is started if the app is newly installed (not upgraded)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4538 

#### What has been done to verify that this works as intended?
I tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
The previous approach that we used in `AppStateProvider` didn't work when the app was newly installed (`packageInfo.firstInstallTime == packageInfo.lastUpdateTime`) so I mixed it with shared preferences to make sure it works in all the cases.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's just a bug fix that should solve the problem described in the issue. Nothing else might be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/utilities/AppStateProviderTest.kt [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        packageInfo = PackageInfo()
+        metaSettings = mock(Settings::class.java)
+        appStateProvider = AppStateProvider(packageInfo, metaSettings)
+    }
+
+    @Test
+    fun `When app is newly installed isFreshInstall() should return true when opened for the first time`() {
+        packageInfo.firstInstallTime = 100
+        packageInfo.lastUpdateTime = 100
+        `when`(metaSettings.contains(MetaKeys.FIRST_LAUNCH)).thenReturn(false)
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/AppStateProviderTest.kt]: We can start using `mockito-kotlin` now to avoid the back ticks: https://github.com/mockito/mockito-kotlin/wiki/Mocking-and-verifying

**Review by seadowg — CHANGES_REQUESTED** [review]
Looks good! I noticed this problem yesterday but saw you'd already started on a fix. Just one comment about moving to mockito-kotlin for new tests.

File: collect_app/src/test/java/org/odk/collect/android/utilities/AppStateProviderTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/utilities/AppStateProviderTest.kt]: Done.

**Review by seadowg — APPROVED** [review]
Will merge after checks
