### PR TITLE
Use media file `type` to determine entity lists

### LINKED ISSUE #6161: Entities header in entities lists in experimental settings
#### ODK Collect version
the master version d67e55a75cc20d31fdd9468f575ed2c2aa239dac
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
When I go to experimental settings - View entity list I open the list of entity lists but the header says that these are entities. Is this expected?
entityListVsEntities
#### Steps to reproduce the problem
1. In experimental settings enable local entities.
2. Tap "view entity lists".

### LINKED ISSUE #6229: `entityList` type media files should be treated as entity lists
If a `mediaFile` in the [manifest](https://docs.getodk.org/openrosa-form-list/#the-manifest-document) has a `type` attribute equal to `entityList`, the media file should be treated as an entity list. This means:

* Entity lists should be consistent between forms (as in #6029)
* Registration and update forms should create/update entities locally (assuming other conditions for local entities are met)
* Entities in the list should be visible in the experimental entity browser

This will replace the manual route for adding entity lists, and people wanting to try out offline entities post this change will have to use a newer server.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6161 
Closes #6229

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot to discuss here! I just updated how we parse the form manifest.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This does remove the ability to manually add entity lists manually to make things less confusing, but it will mean that this (and any future entity features/changes) will require testing against a version of Central that supports the `type` attribute. [This change](https://github.com/getodk/central-backend/commit/e1c74de7e926c9d03a761b6349f7598c5f6df8e5) hasn't been released yet, but should be available at https://staging.getodk.cloud.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImplTest.kt [hunk 1]
```diff
@@ -71,4 +71,29 @@ class OpenRosaResponseParserImplTest {
         val formList = OpenRosaResponseParserImpl().parseManifest(Document())
         assertThat(formList, equalTo(null))
     }
+
+    @Test
+    fun `parseManifest() when media file has type entityList returns isEntityList as true`() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImplTest.kt:76]: We should have a test to check if it returns false otherwise.

File: strings/src/main/res/values-fi/strings.xml [hunk 2]
```diff
@@ -941,8 +941,7 @@
   <!--Text for button that deletes all entities for the project-->
   <string name="clear_entities">Poista kaikki</string>
   <!--Text for button that adds a new entity list-->
```
Comment (grzesiek2010) [inline strings/src/main/res/values-fi/strings.xml:943]: You should also get rid of the explanation text above.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: strings/src/main/res/values-fi/strings.xml (hunk 2 above)
Comment (seadowg) [reply strings/src/main/res/values-fi/strings.xml:943]: I've removed it for the string in `values`, but won't touch it for the translated files as that should happen automatically for when new translations are added.

**Review by grzesiek2010 — APPROVED** [review]
