### PR TITLE
Display errors inline rather than in toast

### LINKED ISSUE #5618: Display errors inline rather than in toast
#### Problem description
We want to improve how we display errors by adding clear error messages to make it easier for data collectors to scan and address the issue. Currently, we have the toast that pops up, and it's easy to miss. I do think it's improved now that it's darker and centred, but we want to improve this further. 

We are not doing the hierarchy view yet, which you will see in [Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1761%3A60286&t=yiG40KoHuGRmotn1-1). This issue is focusing on errors within the form experience.

Image

#### Solution

- Adding a red outline with rounded corners to highlight the error (we don't want to add more margin). 
- Error message is the same for all types of errors (exclamation mark icon and text "Required question" or incorrect if they have specific logic defined.
- The only question type that is different is how we display [text field errors](https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec), we will display the exclamation at the end of the field with supporting text "This question is required". For the moment, we'll text fields should show errors in the same way as everything else. We can add the text field specific error appearance later.
- If the question is really long, we want to scroll the user to the bottom of the page if there is an error (similar to what we do for multiple questions). 
- Currently, the error fades in when you have a group of questions, which we want to keep inside the bounds of the outline. This might be something we want to pair on to get right. 

#### Other information 

One thing that is related, but out of scope for this issue, is potentially allowing data collectors to skip a required question. In a recent user research session, a project manager told me that they have required questions, but sometimes the data collector can't, for whatever reason, submit an answer. 

They explained that data collectors add dummy text or anything to bypass the question, which means they have to clean up the data after. They could just make the question not required, but they said having some sort of option to skip and come back later would be helpful. I'm adding this here because I think it's interesting in the context of errors for us to consider down the road if it's a common issue.

### LINKED ISSUE #5751: Fix spacing for read-only text widget
This is a follow-on issue from [#5725](https://github.com/getodk/collect/pull/5725#issuecomment-1731989207)

In the read-only text widget the answer is indented because the M3 text field has more padding. We want to fix this so everything is aligned to the left.

Screenshot 2023-09-22 at 11 35 46 AM

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5618 
Closes #5751 

#### What has been done to verify that this works as intended?
I've tested the changes manually and fixed automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is what we agreed on in the issue and when it comes to the implementation there is nothing to discuss here.

The final solution differs a little bit from what was described in the issue so let me list the changes that we introduced:

- Added a red outline with rounded corners to highlight the error. The outline should be displayed no matter what the question type is but there should be a small difference in displaying the error message when it's a text question. See the issue.
- Removed the red animation that we used to highlight required/invalid answers when there were multiple questions on the same page
- Updated the look of text fields. See: https://github.com/getodk/collect/pull/5725#issuecomment-1710785311 that's why testing read-only text widgets (plus external widgets and the Bearing widget too) is so important. See https://github.com/getodk/collect/issues/5751

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Please test how different widgets look like when they are required but there is no answer or when constraints are violated. It's also important to keep in mind that apart from the default error messages we have when an error is displayed we can set custom ones too using the `required_message` and `constraint_message` columns in xls (see https://xlsform.org/en/#required-message and https://xlsform.org/en/#constraint-message)

#### Do we need any specific form for testing your changes? If so, please attach one.
I used the `All widgets` form but with all questions required to test every single widget:
[All widgets.xml.txt](https://github.com/getodk/collect/files/12607315/All.widgets.xml.txt)

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@alyblenkin, it would be good to have early feedback from you. You can download the apk from CircleCI and here I'm attaching two forms I've used so far:
[all-widgets.xlsx](https://github.com/getodk/collect/files/12524188/all-widgets.xlsx) - all questions are required so you can see how it looks like with different widgets.
[RequiredAndConstraint.xlsx](https://github.com/getodk/collect/files/12524189/RequiredAndConstraint.xlsx) - it contains only 4 questions and two of them have custom messages (see https://xlsform.org/en/#required-message and https://xlsform.org/en/#constraint-message)

I've already noticed that some widgets will need to be updated because even if they do not have answers they still keep room for them visible for example:

Screenshot_1693920480

List widgets also would need to be updated because they don't have any margin end/right and some elements are visible out of the red outline:
 
Screenshot_1693920509

what do you think about those two? Any other thoughts?

**Comment by alyblenkin** [comment]
Hey @grzesiek2010, I haven't been feeling well so I haven't gone through all of the widgets, but it's going in the right direction! My first reaction was we need a bit more padding between the question and the red line because it feels a bit squishy. However, we don't want the error to take up too much space, especially for smaller phones – so what you've done works.

I agree we would want to reduce the spacing on the ones that don't have answers. And fix the margin for the list widgets, so things don't overlap. For text field errors, I thought we should use https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec 

A few interaction things I noticed: 

The error doesn't go away once you've addressed the error in some cases, like when I uploaded the image.

Screenshot_20230905-231445_ODK Collect

I also noticed the error message disapears when you rotate the device. But it works if you have the device already rotated and try to go ahead without answering the question. 

I assume this is another issue, but the toast message is truncated here, which isn't ideal. 

Screenshot_20230905-233208_ODK Collect

**Comment by grzesiek2010** [comment]
> I assume this is another issue, but the toast message is truncated here, which isn't ideal.

I'm not sure if this is related to this issue that was supposed to be about required questions and constraints. That toast is displayed when a user tries to start an external app (using external widgets) or widgets like image/video but for some reason, there is no app installed on their device that can handle it. Probably it's something you can explore later and maybe we should get rid of those toasts too and display them in a similar way like constraints but it's a separate thing I would say.

**Comment by grzesiek2010** [comment]
>  For text field errors, I thought we should use https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec

Yeah I know but in the issue, we discussed implementing the same style for all widgets first and then (maybe in a separate pr) handling text widgets.

**Comment by grzesiek2010** [comment]
> My first reaction was we need a bit more padding between the question and the red line because it feels a bit squishy

I thought we wanted to avoid increasing the margins, and I haven't done that; I've simply introduced an outline between the screen edge and the questions. Do you think the outline should be shifted slightly towards the screen edge without expanding the margin between the edge and the questions? Or maybe you want to add more margin?

**Comment by alyblenkin** [comment]
> > My first reaction was we need a bit more padding between the question and the red line because it feels a bit squishy
> 
> I thought we wanted to avoid increasing the margins, and I haven't done that; I've simply introduced an outline between the screen edge and the questions. Do you think the outline should be shifted slightly towards the screen edge without expanding the margin between the edge and the questions? Or maybe you want to add more margin?

Yes, we absolutely want to avoid increasing the margins. If it isn't too much work, I would be curious to see what it looks like slightly shifted towards the screen edge, but I also think what you have works!

**Comment by alyblenkin** [comment]
> > I assume this is another issue, but the toast message is truncated here, which isn't ideal.
> 
> I'm not sure if this is related to this issue that was supposed to be about required questions and constraints. That toast is displayed when a user tries to start an external app (using external widgets) or widgets like image/video but for some reason, there is no app installed on their device that can handle it. Probably it's something you can explore later and maybe we should get rid of those toasts too and display them in a similar way like constraints but it's a separate thing I would say.

Yes, I think it's a different issue as well. I agree we should do away with the toast and make it more actionable as well, so the user knows what to do to resolve it. I'll add this to my backlog to investigate!

**Comment by grzesiek2010** [comment]
> The error doesn't go away once you've addressed the error in some cases, like when I uploaded the image.

Handling this properly (deciding if the error should be still visible or not)  would require form validation every time we receive a new answer. I'm not sure if it's a good idea because it would slow down the process. Maybe just removing the error in such cases would be enough (when we start an external app) then when a user is back the error would appear again on moving forward (if needed)?
But I'm not sure... I'm also ok with leaving this as-is. If you have other types of questions the error message won't disappear immediately when for example in select_one question you select something so why would we need to do that for widgets that start external apps?

**Comment by grzesiek2010** [comment]
> For text field errors, I thought we should use https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec

You can test it now @alyblenkin. There is only one thing... I used [outlined text fields](https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec) because I think they look better. You can install the app and let me know if you agree.

**Comment by grzesiek2010** [comment]
> I agree we would want to reduce the spacing on the ones that don't have answers. And fix the margin for the list widgets, so things don't overlap.

This is also ready so you can test it if you want.

**Comment by alyblenkin** [comment]
> > The error doesn't go away once you've addressed the error in some cases, like when I uploaded the image.
> 
> Handling this properly (deciding if the error should be still visible or not) would require form validation every time we receive a new answer. I'm not sure if it's a good idea because it would slow down the process. Maybe just removing the error in such cases would be enough (when we start an external app) then when a user is back the error would appear again on moving forward (if needed)? But I'm not sure... I'm also ok with leaving this as-is. If you have other types of questions the error message won't disappear immediately when for example in select_one question you select something so why would we need to do that for widgets that start external apps?

I can see how that would slow down performance. I think removing the error would be helpful feedback for any type of question, so the user knows it's no longer invalid. I think this wasn't as obvious before because we just had the toast, now it's very clear something is wrong and the expected behaviour would be that it goes away once I've addressed the error.

**Comment by alyblenkin** [comment]
> You can test it now @alyblenkin. There is only one thing... I used [outlined text fields](https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec) because I think they look better. You can install the app and let me know if you agree.

Testing this now :) I think the outline is growing on me and it's super clear what the user needs to engage with! We may want to add a bit more spacing between the question and the text field because it's a bit tight. 

Screenshot_20230907-163529_ODK Collect

I also noticed the outline text field is nearly touching the red error border here 
Screenshot_20230907-163124_ODK Collect

I also don't think the list widget was updated because everything is still overlapping.

**Comment by alyblenkin** [comment]
> > I agree we would want to reduce the spacing on the ones that don't have answers. And fix the margin for the list widgets, so things don't overlap.
> 
> This is also ready so you can test it if you want.

This looks much better!

**Comment by alyblenkin** [comment]
@grzesiek2010 I was wondering if we could also try using the [surface container for the text field](https://m3.material.io/components/text-fields/specs#544d001a-e0ce-49eb-b77b-89fe08acccc5)? For the text field colour, we could use light grey. I think that might be a bit more subtle than the outline. 

This will also help us move towards our goal of creating consistency across the tools. Central uses this pattern already, and we would look to the same with Enketo. Central doesn't have a small radius on the corners, but we could move in that direction so everything is rounded. 

Screenshot 2023-09-07 at 2 08 57 PM

**Comment by grzesiek2010** [comment]
> @grzesiek2010 I was wondering if we could also try using the [surface container for the text field](https://m3.material.io/components/text-fields/specs#544d001a-e0ce-49eb-b77b-89fe08acccc5)? For the text field colour, we could use light grey. I think that might be a bit more subtle than the outline.

Done. You can test it.

**Comment by grzesiek2010** [comment]
> I also don't think the list widget was updated because everything is still overlapping.

I only added the margin end so that the red outline doesn't overlap the labels. Those list widgets have labels and choices placed horizontally and are rather supposed to be used on larger screens otherwise the choices/labels will overlap.

**Comment by grzesiek2010** [comment]
> I can see how that would slow down performance. I think removing the error would be helpful feedback for any type of question, so the user knows it's no longer invalid. I think this wasn't as obvious before because we just had the toast, now it's very clear something is wrong and the expected behaviour would be that it goes away once I've addressed the error.

I've added removing the error every time the answer changes (no matter what widget it is) please play with it and let me know if you like it. The fact that there is a new answer doesn't mean there should be no error. We would need to validate constraints to check it but maybe it's better than assuming that the new answer is still wrong and removing the error only after navigating forward. So basically there is no perfect way but I think I like what I've implemented now a little bit more.

**Comment by grzesiek2010** [comment]
> I also noticed the error message disapears when you rotate the device

If you asked me to fix this a few years ago I would say of course but my thinking has changed a little bit over the past few years and now I'm more into keeping only crucial things like answers etc. after rotating a device. We have talked about that with @seadowg a few times and I think we were generally on the same page. 
@seadowg is this error something that you would rather keep or you agree it's not a must and maybe we can add it later if we change our mind?

**Comment by alyblenkin** [comment]
> > @grzesiek2010 I was wondering if we could also try using the [surface container for the text field](https://m3.material.io/components/text-fields/specs#544d001a-e0ce-49eb-b77b-89fe08acccc5)? For the text field colour, we could use light grey. I think that might be a bit more subtle than the outline.
> 
> Done. You can test it.

Thanks so much for trying this out! I prefer this option over the outline. Could we make the grey a bit lighter? Perhaps the same colour as the main menu buttons? 

The spacing between the question and text field looks a lot better too!

**Comment by alyblenkin** [comment]
> > I can see how that would slow down performance. I think removing the error would be helpful feedback for any type of question, so the user knows it's no longer invalid. I think this wasn't as obvious before because we just had the toast, now it's very clear something is wrong and the expected behaviour would be that it goes away once I've addressed the error.
> 
> I've added removing the error every time the answer changes (no matter what widget it is) please play with it and let me know if you like it. The fact that there is a new answer doesn't mean there should be no error. We would need to validate constraints to check it but maybe it's better than assuming that the new answer is still wrong and removing the error only after navigating forward. So basically there is no perfect way but I think I like what I've implemented now a little bit more.

I really like what you implemented. I think this is more consistent with what the user would expect. Before, I kept thinking my new answer was wrong because the error message persisted. I think it makes more sense to validate the new answer once they try to move forward. 

I also noticed you added the field text error message! It looks great :) 

Small note: It looks like the bearing widget is still using the underline, instead of the new text field with the surface colour in the background.

**Comment by grzesiek2010** [comment]
> Thanks so much for trying this out! I prefer this option over the outline

Done.

> Could we make the grey a bit lighter? Perhaps the same colour as the main menu buttons?

Done.

> Small note: It looks like the bearing widget is still using the underline, instead of the new text field with the surface colour in the background.

Fixed.

@alyblenkin Do we need to change anything else?

**Comment by alyblenkin** [comment]
> @alyblenkin Do we need to change anything else?

Not that I can think of! I think we are good to go :)

**Comment by grzesiek2010** [comment]
Ok so two questions from me:

In the issue, you said:
> Currently, the error fades in when you have a group of questions, which we want to keep inside the bounds of the outline. This might be something we want to pair on to get right.

are you ok with the fact that I removed that old animation? I think the outline is enough.

What do you think about displaying answers in widgets that should start an external app or use a sensor but it's not available and then we want to allow adding answers manually? It's always been handled using text fields but those text fields were disabled by default and their background were removed so that initially they looked like text views. I think we wanted that because if the external app existed we wanted the answer to look like in any other widget with buttons + text (eg. geo widgets, barcode widget etc.). But if the external app is not available we wanted to allow adding the answer manually and enable that text field. In this pr I didn't implement that first part (removing the background and making it look like a text view).
Screenshot_1694680607
Maybe it's something for a separate issue if we want it? I'm kind of torn.

**Comment by seadowg** [comment]
> If you asked me to fix this a few years ago I would say of course but my thinking has changed a little bit over the past few years and now I'm more into keeping only crucial things like answers etc. after rotating a device. We have talked about that with @seadowg a few times and I think we were generally on the same page.
@seadowg is this error something that you would rather keep or you agree it's not a must and maybe we can add it later if we change our mind?

Good question! Without looking at/thinking about the code, I think with this one I'd lean towards it not needing to if it's more work. We could always add it later, and my assumption is that rotating the device while fixing an error would be rare.

**Comment by grzesiek2010** [comment]
@seadowg 
I was also thinking about what I said in the issue regarding reworking that asterisk mark displayed when a question is required. Initially, I thought that adding a separate view for that would be better instead of treating it as a part of the text itself but it's not as easy and perfect as I thought. The problem would be that with long question labels, there would be a margin not only in the first line (where the view would be placed) but also in other lines. It would look like:
Screenshot_1694643205
so I'm not going to do this here because we probably need to think of it more. If you have any thoughts (or @alyblenkin ) please share.

**Comment by alyblenkin** [comment]
> are you ok with the fact that I removed that old animation? I think the outline is enough.

Yes, I think the outline is enough! We can always iterate on it later. 

> What do you think about displaying answers in widgets that should start an external app or use a sensor but it's not available and then we want to allow adding answers manually? It's always been handled using text fields but those text fields were disabled by default and their background were removed so that initially they looked like text views. I think we wanted that because if the external app existed we wanted the answer to look like in any other widget with buttons + text (eg. geo widgets, barcode widget etc.). But if the external app is not available we wanted to allow adding the answer manually and enable that text field. In this pr I didn't implement that first part (removing the background and making it look like a text view).

Yes, I think allowing people to answer manually is perfect so they can still achieve their task. We can always add the background to the text field in another issue. As long as they can still answer manually I think that's good for this issue. 

I noticed the text field cursor becomes white when there is an error, is it possible for it to be blue?

**Comment by alyblenkin** [comment]
> @seadowg I was also thinking about what I said in the issue regarding reworking that asterisk mark displayed when a question is required. Initially, I thought that adding a separate view for that would be better instead of treating it as a part of the text itself but it's not as easy and perfect as I thought. The problem would be that with long question labels, there would be a margin not only in the first line (where the view would be placed) but also in other lines. It would look like: !

> so I'm not going to do this here because we probably need to think of it more. If you have any thoughts (or @alyblenkin ) please share.

This might be a silly idea and not ideal visually, but I guess the asterisk could go above the textbox for longer questions temporarily if it's tricky to implement right now. Perhaps that's not possible but I wanted to put the idea out there :)

**Comment by alyblenkin** [comment]
Hi @grzesiek2010, following up on some of the feedback from the call earlier. 

**1. The supporting text for the error message is VERY small 🐜**
Could we make it the same size as the widget error messages, so it's consistent? 

**2. Extra spacing because we don't display the label in the text field**
I think we should evenly distribute the spacing within the text box, like the image below. If we feel that looks like it's still taking up too much space, we could reduce the height, but we don't want the touch target to be too small, so I think we should try this first.

Screenshot 2023-09-19 at 8 56 33 AM

**Comment by grzesiek2010** [comment]
> I noticed the text field cursor becomes white when there is an error, is it possible for it to be blue?

I haven't experienced anything like that. What android version are you using?

> 1. The supporting text for the error message is VERY small 🐜
Could we make it the same size as the widget error messages, so it's consistent?

Fixed.

> 2. Extra spacing because we don't display the label in the text field
I think we should evenly distribute the spacing within the text box, like the image below. If we feel that looks like it's still taking up too much space, we could reduce the height, but we don't want the touch target to be too small, so I think we should try this first.

Fixed.

**Comment by alyblenkin** [comment]
The new fixes look great 🎉 

I'm using Android version 12 
Screenshot_20230920-222437_ODK Collect 1

**Comment by lognaturel** [comment]
It's looking great! With [this form](https://docs.google.com/spreadsheets/d/13pdMv3wNbd14hjN-dqxXgmgLN0fzvfGxbQa6OXvJNpU/edit#gid=0), when I swipe forward without filling in name, it generally scrolss "What is your birthdate" to the top. I see the same white cursor that @alyblenkin mentioned, also Android 12.

**Comment by grzesiek2010** [comment]
> It's looking great! With [this form](https://docs.google.com/spreadsheets/d/1tfrpIrixbOHdAb_aLejWq7HTeJaSjZVqcQLdAP86WA0/edit#gid=0), when I swipe forward without filling in name, it generally scrolss "What is your birthdate" to the top.

Are you sure you have attached the form you wanted? This one has no constraints and only one required question and I can't see any question with `What is your birthdate`.

**Comment by grzesiek2010** [comment]
> I see the same white cursor that @alyblenkin mentioned, also Android 12.

Fixed.

> This might be a silly idea and not ideal visually, but I guess the asterisk could go above the textbox for longer questions temporarily if it's tricky to implement right now. Perhaps that's not possible but I wanted to put the idea out there :)

I'm not sure if this would look good. Let's leave it for now I thought it would be easier and more beneficial for us but it's not the case. Of course you can think about it and file a separate issue if you think there is anything we can improve there.

**Comment by grzesiek2010** [comment]
> Yes, I think allowing people to answer manually is perfect so they can still achieve their task. We can always add the background to the text field in another issue. As long as they can still answer manually I think that's good for this issue.

eventually I've fixed that because it was a problem not only with external widgets but with normal but read-only text widgets too.
@lognaturel thanks for asking abut that!
The only difference now is that if we have a read-only text widget the answer is displayed with more margin (because the material text filed has more padding):

| master  | this branch |
| ------------- | ------------- |
| Screenshot_1695297266 | Screenshot_1695298461  |

@lognaturel do you think it's a problem? If so I would consider doing something else and displaying answers in text views (not text fields) if the text field is disabled so that we don't need all those customization we add to text fields. That's not perfect too because we would need to keep two elements (text field and text view) and display only one depending on the conditions but probably a little bit easier that forcing text fields to look like text views if they are disabled.

**Comment by lognaturel** [comment]
> @lognaturel do you think it's a problem?

😬 It does feel distracting to me. Might be easier to handle as a follow-on issue? Either way is fine.

**Comment by grzesiek2010** [comment]
> It does feel distracting to me. Might be easier to handle as a follow-on issue? Either way is fine.

Yes we can have it in a separate pr. I can even start working on it on top of this pr and then rebase.

**Comment by lognaturel** [comment]
> Are you sure you have attached the form you wanted? 

Sorry, [this form](https://docs.google.com/spreadsheets/d/13pdMv3wNbd14hjN-dqxXgmgLN0fzvfGxbQa6OXvJNpU/edit#gid=0)

**Comment by grzesiek2010** [comment]
> It's looking great! With [this form](https://docs.google.com/spreadsheets/d/13pdMv3wNbd14hjN-dqxXgmgLN0fzvfGxbQa6OXvJNpU/edit#gid=0), when I swipe forward without filling in name, it generally scrolss "What is your birthdate" to the top.

> Sorry, [this form](https://docs.google.com/spreadsheets/d/13pdMv3wNbd14hjN-dqxXgmgLN0fzvfGxbQa6OXvJNpU/edit#gid=0)

Ah ok now it's fixed.

**Comment by grzesiek2010** [comment]
@alyblenkin 
there is one thing from your description that I have't implemented because it's not easy:

> If the question is really long, we want to scroll the user to the bottom of the page if there is an error (similar to what we do for multiple questions).

If you feel that it's something important please file a separate issue.

**Comment by alyblenkin** [comment]
@grzesiek2010, the new changes look good - thanks for fixing the cursor. I'll chat with Hélène about scrolling to the end of long questions and see when/ if we still want to implement it. I don't think it's pressing right now.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -556,15 +556,7 @@ private void setupViewModels(FormEntryViewModelFactory formEntryViewModelFactory
...
-                try {
-                    createConstraintToast(failedValidationResult.getIndex(), failedValidationResult.getStatus());
-                    if (getFormController().indexIsInFieldList() && getFormController().getQuestionPrompts().length > 1) {
-                        getCurrentViewIfODKView().highlightWidget(failedValidationResult.getIndex());
-                    }
-                } catch (RepeatsInFieldListException e) {
-                    createErrorDialog(new FormError.NonFatal(e.getMessage()));
-                }
-
+                getCurrentViewIfODKView().setErrorForQuestionWithIndex(failedValidationResult.getIndex(), formEntryViewModel.getErrorMessage(failedValidationResult, this));
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: I'm generally really liking the structure of all this, but before I get into all the details: I was wondering if it would make sense to have the error message be part of the `FailedValidationResult` rather than having to reach back in the `FormEntryViewModel` to get it here?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Not really. The only place where we construct `FailedValidationResult` is `JavaRosaFormController` because that's where the validation takes place. On one hand, it would be good to move the method responsible for generating error messages there since first that method calls some javarosa methods to check if there is a custom error message but if not it needs to read our strings, and to do that we need `context` that would need to be passed through a few methods and that wouldn't be easy.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Ah good point. I still think it'd be better to have the observation not have to reach back into the `FormEntryViewModel` to simplify the amount of interactions here. Maybe instead of `getValidationResult` returning the JavaRosa type, it could return a `Result<Unit, String>?` so the `FormFillingActivity` side would look like:

```kotlin
formEntryViewModel.getValidationError().observe(this, consumable -> {
    if (consumable.isConsumed()) {
        return;
    }
    String result = consumable.getValue();
    if (result instance Result.Error) {
        getCurrentViewIfODKView().setErrorForQuestionWithIndex(failedValidationResult.getIndex(), ((Result.Error) result.value));
        swipeHandler.setBeenSwiped(false);
    } else if (result insanceof Result.Success) {
        SnackbarUtils.showLongSnackbar(findViewById(R.id.llParent), getString(org.odk.collect.strings.R.string.success_form_validation), findViewById(R.id.buttonholder));
    }

    consumable.consume();
});
```

That way the `FormEntryViewModel` API is smaller, and we don't expose JavaRosa types from it.

**Review by seadowg — CHANGES_REQUESTED** [review]
See https://github.com/getodk/collect/pull/5725#discussion_r1347296755

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: but I need `FormIndex` here. In your example, it's `failedValidationResult.getIndex()` but `failedValidationResult` does not exist anymore. I would rather need a wrapper around `ValidationResult` that would add the message and then I would be able to use it in a similar way as you described. Or maybe I'm missing something?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: > I would rather need a wrapper around ValidationResult that would add the message and then I would be able to use it in a similar way as you described. Or maybe I'm missing something?

Ah sorry that was a mistake on my part. I like the idea of a wrapper that `FormEntryViewModel` owns though that gives you a message and an index.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Ah it would still require passing context through many different methods to be able to read strings. I gave it a try and I think it doesn't make sense. In the view model class I would need to edit and pass context to:
- `public void moveForward(HashMap<FormIndex, IAnswerData> answers)`
- `public void moveForward(HashMap<FormIndex, IAnswerData> answers, Boolean evaluateConstraints) `
- `public void moveBackward(HashMap<FormIndex, IAnswerData> answers)`
- `public boolean updateAnswersForScreen(HashMap<FormIndex, IAnswerData> answers, Boolean evaluateConstraints)`
- `public boolean saveScreenAnswersToFormController(HashMap<FormIndex, IAnswerData> answers, Boolean evaluateConstraints)`
- `public void validate()`

those methods are usually used in more than one place so that means a lot of changes. Do you agree that it doesn't make sense?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Yeah sorry I'd not fully considered the strings needing to be loaded. 

I guess the wrapper could include the data the UI needs to create the string. It looks to me like the error message is either a string we get from the `FormController` or an Android string so the wrapper could include either a `String` or an `int` string ID.

I think an even nicer structure would be to a have a sealed validation error type here where some include strings from JavaRosa:

```
sealed class ValidationError {
    data class Constraint(val message: String?) : ValidationError
    data class Required(val message: String?) : ValidationError
}
```

The UI could then show the message if it's non-null, or just load the string if it's null. This would keep string loading (and `Context`) out of the ViewModel and `FormController` interactions out of the UI.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Ok I've implemented something like that.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java [hunk 2]
```diff
@@ -122,6 +122,11 @@ public int getColorOnSurface() {
         return getThemeAttributeValue(context, com.google.android.material.R.attr.colorOnSurface);
     }
 
+    @ColorInt
+    public int getColorSurface() {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java]: I don't think this is being used?

File: collect_app/src/main/res/layout/question_error_layout.xml [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    <com.google.android.material.textview.MaterialTextView
+        android:id="@+id/error_message"
+        android:layout_width="0dp"
+        android:layout_height="wrap_content"
+        android:layout_marginStart="@dimen/margin_small"
+        android:layout_marginEnd="@dimen/margin_standard"
+        android:textColor="?colorError"
+        android:layout_gravity="center_vertical"
+        style="@style/TextAppearance.Collect.Subtitle1"
```
Comment (seadowg) [inline collect_app/src/main/res/layout/question_error_layout.xml]: This should us a theme attribute rather than direct style reference. Also, `Subtitle1` is a Material 2 text appearance so we should probably use a Material 3 one instead here.

File: collect_app/src/main/res/layout/widget_answer_text_field.xml [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+<com.google.android.material.textfield.TextInputLayout xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"
+    android:id="@+id/text_input_layout"
+    android:layout_width="match_parent"
+    android:layout_height="wrap_content"
+    android:paddingHorizontal="@dimen/margin_standard"
+    android:paddingTop="@dimen/margin_standard"
+    app:boxBackgroundColor="?colorSurfaceContainerLow"
+    app:errorTextAppearance="@style/TextAppearance.Collect.Subtitle1">
```
Comment (seadowg) [inline collect_app/src/main/res/layout/widget_answer_text_field.xml]: Again, this should use a theme attribute and a Material 3 text appearance.

File: collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java [hunk 5]
```diff
@@ -73,13 +73,15 @@ protected View onCreateAnswerView(Context context, FormEntryPrompt prompt, int a
             binding.barcodeButton.setText(getContext().getString(org.odk.collect.strings.R.string.replace_barcode));
             binding.barcodeAnswerText.setText(answer);
         }
+        binding.barcodeAnswerText.setVisibility(binding.barcodeAnswerText.getText().toString().isBlank() ? GONE : VISIBLE);
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java:75]: It would be good to add tests for the widget behaviour updated in 7338895c391c7b0995f5b06ba254257a56fbf11f

File: collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java [hunk 6]
```diff
@@ -101,6 +101,7 @@ public IAnswerData getAnswer() {
     @Override
     public void clearAnswer() {
         binding.ratingBar1.setRating(0.0F);
+        widgetValueChanged();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java]: Also good to add tests for the behaviour changes in a610987094d967a1b7348eca7540253164783ae8

**Review by seadowg — CHANGES_REQUESTED** [review]
Looking good! Just a few tweaksI think it'd be nice to make, but this is ready for testing.

File: collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java]: Right, fixed.

File: collect_app/src/main/res/layout/question_error_layout.xml (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/res/layout/question_error_layout.xml]: Fixed.

File: collect_app/src/main/res/layout/widget_answer_text_field.xml (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/res/layout/widget_answer_text_field.xml]: Fixed.

File: collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java (hunk 6 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java]: Done.

**Comment by grzesiek2010** [comment]
@seadowg I think it would be good to fix https://github.com/getodk/collect/issues/5751 in one pr so that we don't have to test similar things twice. There is a bunch of commits that address that issue and some that fix things you pointed out during your last review. I think the last commit you reviewed was https://github.com/getodk/collect/pull/5725/commits/10da040a2860bfdcf1c38bce4b7185436b5f24b3 so you can focus on newer ones.

File: collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java:75]: Hmm, I'm torn... generally I agree but I think we need such tests for every single widget not only those that I have updated here. I think I will file a separate issue and maybe even try to fix it as a part of this pr but it shouldn't block reviewing and testing. Does that sound right?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java:75]: Yeah I'm happy with that being a separate issue! Go ahead and file it and add it to the v2023.4 milestone.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
In audio widget (All widgets required form) the red error outline in shown after adding the audio.
audioerror

**Comment by dbemke** [comment]
In Select with images the red outline is "covered" by images on the right.
selectImagesOutline

**Comment by dbemke** [comment]
In selects the line under choices goes beyond the red outline.
selectLines

**Comment by dbemke** [comment]
Is this the expected look of the field to enter e.g strings?
field

**Comment by srujner** [comment]
In Select Multiple widget with packed columns and no buttons, selected choice goes beyond the red outline.

**Comment by grzesiek2010** [comment]
> In audio widget (All widgets required form) the red error outline in shown after adding the audio.

Fixed.

> Is this the expected look of the field to enter e.g strings?

Yes.

> In Select with images the red outline is "covered" by images on the right.

> In selects the line under choices goes beyond the red outline.

> In Select Multiple widget with packed columns and no buttons, selected choice goes beyond the red outline.

This will be fixed in https://github.com/getodk/collect/issues/5731 let's leave it for now as it is.

File: collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java:75]: The issue is ready https://github.com/getodk/collect/issues/5842

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

Verified cases:

- Forms with required questions;
- Forms with ReadOnly questions;
- Light and Dark mode;
- Minimize the app, rotate the screen;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10
