### PR TITLE
Fixed layers directory path

### LINKED ISSUE #3741: The layers directory path is incorrect after storage migration
#### Software and hardware versions 
Collect v1.26.1

#### Problem description
When setting a reference layer, the layers directory path is incorrect after storage migration

#### Steps to reproduce the problem
1. Make sure the storage migration has completed successfully
1. Go to General Settings > Maps
1. Tap `Layer data file`

#### Expected behavior

It should say `/sdcard/Android/data/org.odk.collect.android/files/layers` but just says `/layers` instead.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3741

#### What has been done to verify that this works as intended?
Verified the case described in the issue manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It's just a small fix.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Verifying the case described in the issue would be enough, it's not a risky change.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

File: collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilsTest.java [hunk 1]
```diff
@@ -276,4 +276,13 @@ public void mediaDirNameIsCorrect() {
         assertThat(metadataFromFormDefinition.get(FileUtils.FORMID), is("set-geopoint-before"));
         assertThat(metadataFromFormDefinition.get(FileUtils.GEOMETRY_XPATH), is("/data/location1"));
     }
+
+    @Test
+    @SuppressWarnings("PMD.DoNotHardCodeSDCard")
+    public void simplifyScopedStoragePathTest() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilsTest.java:282]: 👍. I had always though `is` was equivelant to `==` rather than just an alias of `is(equalTo())`. Will use in future!

**Comment by mmarciniak90** [comment]
@grzesiek2010, please, take a look at this again. There are 2 places where the layers directory path is visible. I see that you fixed it in the lower message. This path is visible also under each name of the layer. Before storage migration, path contained a full directory path in **both places**. 

|Before migration | After migration without changes | After migration with changes|
|---|---|---|
|Screenshot_20200326-134822|Screenshot_20200326-134850|Screenshot_20200326-135052|

**Comment by grzesiek2010** [comment]
Yes but it was shorter I don't know if it makes sense to keep full paths in both places @lognaturel what do you think?

**Comment by lognaturel** [comment]
Good catch, @mmarcianiak90. I think it’s important to put the full path in the message below because that one is a hint about where to put the files if none are available. We could just do /layers under each option but I prefer that it be consistent.

**Comment by grzesiek2010** [comment]
> but I prefer that it be consistent

ok it's done.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 6.0, 7.0, 8.1, 9.0

Verified cases:
* offline layer before migration - correct path under option and in lower message
* offline layer after migration- correct path under option and in lower message
* correct source in lower message
* additional directory in /layer 
* the offline map list in Geo widget
* the offline map list on a view that display form submissions on map
* English/Spanish language
* light/dark mode

|Screenshot_20200327-143421|Screenshot_20200327-143216|
|---|---|

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
