### PR TITLE
Reset reference manager on quitting a form

### LINKED ISSUE #6097: Broken geojson attachment makes downloading new attachment impossible
#### ODK Collect version
the store version 2024.1.3, the master version
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After downloading to Collect a form with a broken geojson attachment it’s impossible to download the correct attachment afterwards. There is download failure (the notification and arrow with exclamation mark in Start new form). Only after deleting the project it’s possible to download the newest version.
#### Steps to reproduce the problem
1. In Central upload the form with the broken attachment.
[abc.geojson.txt](https://github.com/getodk/collect/files/15023930/abc.geojson.txt)
[geojsonUpdateBug.xlsx.txt](https://github.com/getodk/collect/files/15023931/geojsonUpdateBug.xlsx.txt)
2. Download this form to Collect.
3. Change something in the geojson file.
4. In Central upload the changed geojson file.
5. Try to download the new version of the form to Collect.
Additional steps
6. Delete the project.
7. Download the form with the newest version to Collect.
#### Expected behavior
It should be possible to download different version of form with changed media.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6097 

#### Why is this the best possible solution? Were any other approaches considered?
In https://github.com/getodk/collect/issues/6097#issuecomment-2091609975 I've described three options:
- changes in Central
- changes in Javarosa
- changes in Collect

we have agreed that the easiest solution for now is to handle this in Collect and improvements in Javarosa/Central are something we might want to have either way.

I've only made one mistake regarding what we can do to fix the issue in Collect saying that it would be enough to download media files before parsing a form. I don't know why I thought so but it's not doable as we need to read form metadata (parse the form) to download and copy media files.
Fortunately, I was able to come up with another (even better solution) which is resetting the reference manager on quitting a form. Thanks to that during parsing a form we don't have references to the old (and maybe even outdated) attachments and the problem does not take place. We don't need them during reading metadata so it's safe to get rid of them. When we open anew form the new references are populated and everything works fine.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should just fix the issue without any side effects. I can't think of any risk here or any particular feature that should be tested more.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -2109,6 +2110,7 @@ private void finishAndReturnInstance() {
     }
 
     private void exit() {
+        ReferenceManager.instance().reset();
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Could we instead reset the `ReferenceManager` before parsing the form when downloading? I'm guessing there's some potentially weird scenarios in the existing code where the `ReferenceManager` is set up for whatever form was viewed last. We could definitely clear it on form exit, but I think it'd be good to unify on any code parsing/loading a form reseting beforehand.

This also makes me wonder if there are weird interactions between form download and form entry given they share a `ReferenceManager` instance. Ideally we want to remove the static state here (it's a blocker for multiple form entry sessions as well), and I'm also wondering if we should take the hit to solve this issue.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Another thought: do we actually need to use JavaRosa's XForm parsing to get the data we need out of the XForm? If parsing works the first time, it'd imply to me that we don't care about actually having a setup `ReferenceManager` when downloading a form. If that's the case, we could just write our own XML parse code (or expose a subset of JavaRosa's) to grab the form metadata.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: > Could we instead reset the ReferenceManager before parsing the form when downloading?

Yes but:
1. We do the reset when opening a form so it's more natural to me to reset it on exiting as well. We don't need to keep those references after exiting.
2. It would be impossible to write a test that is failing first (the same I've added) as we need to parse a form before adding it to our `StubOpenRosaServer` so the test would fail there. I would need to reset the manager before doing that first parsing but after doing that it would be enough and during downloading the failure would not take place.

> This also makes me wonder if there are weird interactions between form download and form entry given they share a ReferenceManager instance. Ideally we want to remove the static state here (it's a blocker for multiple form entry sessions as well), and I'm also wondering if we should take the hit to solve this issue.

Yes currently it's weird but we wouldn't need to parse the whole form with external datsets to read the metadata.

> Another thought: do we actually need to use JavaRosa's XForm parsing to get the data we need out of the XForm? If parsing works the first time, it'd imply to me that we don't care about actually having a setup ReferenceManager when downloading a form. If that's the case, we could just write our own XML parse code (or expose a subset of JavaRosa's) to grab the form metadata.

As I said above we shouldn't need to parse the whole form and it would be better to have a parser that only reads the metadata we need. But I think it could be a separate issue focused on improving the process of downloading forms rather than fixing the issue as resetting the manager is enough.

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt [hunk 2]
```diff
@@ -149,4 +150,32 @@ class FormUpdateTest {
             .startBlankForm("One Question Last Saved")
             .assertText("32")
     }
+
+    @Test
+    fun itIsPossibleToDownloadAnUpdate_afterDownloadingAndOpeningAFormWithBrokenExternalDataset() {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt:155]: Lets link the issue here. The problem we're testing is pretty specific.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: All good points! I'll have a think about what we might wnat to plan for the next release, but it definitely feels like something about `ReferenceManager` and or the parsing needs to change.

Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: I think this should move to `FormEntryViewModel#exit`. I'm hoping in the future we're have some kind of `FormEntryDataService` than can look after loading and saving forms as well as clean up and I imagine that would get called from there.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt:155]: Done.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6097 doesn't occur
- updating geojson files in a form in one and more projects
- hide old versions enabled/disabled
- updating media files

**Comment by WKobus** [comment]
**Tested with success!**

Verified on a device with Android 14

**Comment by srujner** [comment]
**Tested with success!**

Verified on a device with Android 13
