### PR TITLE
FIx #2258 The user is not able to add files from Google Drive to File…

### LINKED ISSUE #2258: The user is not able to add files from Google Drive to File widget
#### Software and hardware versions 
Collect master
Android 5.1, 6.0, 7.0, 8.0

#### Problem description
The user is not able to add files from Google Drive to `File widget`

#### Steps to reproduce the problem
1. The user tries to add a file from Google Drive to `File widget`
2. The user sees a message in toast and file is not attached

#### Expected behavior
The user is able to add a file from Google Drive to `File widget`

### PR DESCRIPTION
**Pull request by ShenJack**
FIx #2258 The user is not able to add files from Google Drive to File…

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -765,7 +765,15 @@ protected void onActivityResult(int requestCode, int resultCode, final Intent in
                 break;
 
             case RequestCodes.ARBITRARY_FILE_CHOOSER:
-                saveFileAnswer(intent.getData());
+
+                showDialog(SAVING_DIALOG);
+                Runnable saveFileRunnable = new Runnable() {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: It seems to me that you could let this drop down to the video case as you did with audio. I think the only difference is the name of the `Runnable`. `saveMediaRunnable` seems fine to me for all of them or you could go with the slightly more general `saveFileRunnable`.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 4.4, 5.1, 6.0, 7.0, 8.1

Verified new and saved the form.
Verified formats: xml, png, mp3, 3gp, jpg

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks so much, @ShenJack!
