### PR TITLE
Ignore expired savepoints

### LINKED ISSUE #6038: Savepoint from one form can load on other form
#### ODK Collect version
the master version 2a06bf580b90d75d9e7089a1066ac469eb1f1589
#### Android version
10, 11, 13
#### Device used
Samsung Galaxy M12, Redmi 9T, Google Pixel 6a

#### Problem description
Deleting blank form with savepoint created and downloading any other form, results in recovery dialog from previously deleted blank form showing for newly downloaded blank form.
Issue doesn’t occur in the store version 2024.1.2.
#### Steps to reproduce the problem
Precondition: 
Blank form update mode set to manual

1. Open any form
2. Kill app to create savepoint
3. Open app again
4. Go to Delete form - Blank Forms
5. Delete Blank Form with savepoint
6. Go to Download form
7. Download any other form
8. Go to Start new form
9. Open previously downloaded form

#### Expected behavior
Recovery dialog should not appear for newly downloaded form

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6038 

#### Why is this the best possible solution? Were any other approaches considered?
The problem here is that the `savepoints` db uses db ids from the `forms` db and the `savepoints` db to refer to the forms they belong to. If we download a form (let's say it's our first form) in sqlite its db id will be 1. Once we create a savepoint for this form it will be keeping that value (1) as a reference in the database. However, sqlite works in the way that it can reuse ids that are no longer used, so if we remove such a form and redownload it (or download any other form) it will be saved into the forms database with 1 as a db id. As a result after opening the new form, the old savepoints will be found and loaded.
I thought that maybe we would need to rework the `savepoints` db but it would require a lot of work (and would not be perfect too). ~~Instead, I think a better solution is to do what we already do for saved forms (comparing the time of the last modification of a savepoint and a form) https://github.com/getodk/collect/pull/6049/files#diff-8ec04b331c791ac6110c2bb601e45c92aafffcc7e7eedfd7b43b78bd9af3c34fL40 so I've added a similar check for blank forms here https://github.com/getodk/collect/pull/6049/files#diff-8ec04b331c791ac6110c2bb601e45c92aafffcc7e7eedfd7b43b78bd9af3c34fR29~~

~~Another solution (than editing `SavepointUseCases.findValidSavepoint()`) would be to remove savepoints when forms they refer to are being removed but that would require handling this in a few different places (or adding `SavepointsRepository` as a dependency to `FormsRepository`) what I don't like so doing that in `SavepointUseCases.findValidSavepoint()` seems to be better.~~

After discussing potential solutions with @seadowg we have decided that changing the way our databases work (avoiding resuing db ids) is the best solution here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
As described in the issue, savepoints that were created before downloading a form should not be loaded even if they were created for exactly the same form (it's a scenario when we remove and download again the same form, not a different one as described in the issue). The fix contains changes in the databases (forms and instances dbs) which has always been tricky so please test upgrading the app from v2023.1.3 to make sure those dbs work well.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
Before I dive in here, did you consider migrating all the DBs so that we use UUID primary keys instead of an auto incrementing integer? I might be missing something, but I think that would allow us to map directly between them without worrying about the IDs being reused (and needing to account for that later).

**Comment by grzesiek2010** [comment]
> Before I dive in here, did you consider migrating all the DBs so that we use UUID primary keys instead of an auto incrementing integer? I might be missing something, but I think that would allow us to map directly between them without worrying about the IDs being reused (and needing to account for that later).

Yeah, I have considered such a refactoring and I mentioned it in the description (it wasn't clear enough, sorry):

> I thought that maybe we would need to rework the savepoints db but it would require a lot of work (and would not be perfect too).

So as I said this would require more work to change the current approach and such an approach wouldn't be perfect because:
- after removing a form and redownloading (the same form) it a savepoint (generated by the old one) would be available and loaded which I don't think should happen.
- a scenario where you remove a form with the given formId and version and download a completely different one (but with the same formId and version) might be possible (maybe not using central but still) and then we might end up with a savepoint from a completely different form loaded during starting our new form.

so to handle such edge cases we would need to compare the time of creation (savpoints and forms) as I do now either way.

**Comment by seadowg** [comment]
> So as I said this would require more work to change the current approach and such an approach wouldn't be perfect 

Just to be clear, I meant using a UUID as the database level primary key for both forms and instances. That would involve migrating their `_id` columns to a `text` and populating it with a generated UUID. That way, we don't end up with primary keys that can be reused if the database is wiped. This would be a pretty big change, but it feels like bugs like this demonstrate that we most likely should be using non sequential primary keys.

Alternatively, we could look at combining all our tables into one DB so that we could mange data integrity problems like this using foreign keys - here we could use [`ON DELETE CASCADE`](https://www.sqlite.org/foreignkeys.html) to make sure save points are deleted when either "parent" is deleted.

I get that these are much bigger solutions, but I wanted to make sure we discuss them!

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/6049#issuecomment-2034596337

**Comment by grzesiek2010** [comment]
> I get that these are much bigger solutions, but I wanted to make sure we discuss them!

That would be good but yeah it means a lot of work and risk. Instead what we can do for now is to start using [The AUTOINCREMENT Keyword](https://www.sqlite.org/autoinc.html) that prevents resuing ids. It should be an extra thing so I would keep what I have in this pr either way. What do you think?

**Comment by seadowg** [comment]
> Instead what we can do for now is to start using [The AUTOINCREMENT Keyword](https://www.sqlite.org/autoinc.html) that prevents resuing ids

That's a nice compromise! I think there'd still be a potential problem (compared to UUIDs or a multi table DB) if someone deleted just the `forms.db` or `instances.db` and left the save points db intact (stuff like this makes me really keen to move these dbs to private storage). That feels allowable though. I haven't had a chance to look at this PR yet, so I think it would make sense to just change it here so we don't go through multiple iterations for the solution.

**Comment by grzesiek2010** [comment]
> That's a nice compromise! I think there'd still be a potential problem (compared to UUIDs or a multi table DB) if someone deleted just the forms.db or instances.db and left the save points db intact (stuff like this makes me really keen to move these dbs to private storage). That feels allowable though. I haven't had a chance to look at this PR yet, so I think it would make sense to just change it here so we don't go through multiple iterations for the solution.

Done, please review.

File: collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+        database.insert(DatabaseConstants.INSTANCES_TABLE_NAME, null, contentValues)
+        instancesDatabaseMigrator.onUpgrade(database, oldVersion)
+        database.rawQuery("SELECT * FROM " + DatabaseConstants.INSTANCES_TABLE_NAME + ";", arrayOf<String>()).use { cursor ->
+            assertThat(cursor.columnCount, equalTo(12))
+            assertThat(cursor.count, equalTo(1))
+
+            cursor.moveToFirst()
+
+            assertThat(cursor.getString(cursor.getColumnIndex(DISPLAY_NAME)), equalTo(contentValues.getAsString(DISPLAY_NAME)))
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt:81]: Should we check that the DB IDs (and in the forms test as well) are the same as before here? Maybe that doesn't matter?

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt:81]: We can do that. It's not that important here so I have also added new tests to make sure db ids are not reused.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 @getodk/testers I think it's worth holding this for merge so we don't end up in any weird states on test devices if there's problems.

**Comment by seadowg** [comment]
@getodk/testers I think playing around with deleting the databases (in the `metadata` directory) on disk as well as deleting instances/forms from the UI is a good exercise here as it'll be interesting to see what kinds of things happen.

**Comment by grzesiek2010** [comment]
@dbemke @srujner @WKobus 
Here are the apks for testing upgrading databases. If you install the first one and the second one you should be able to verify if everything is fine.
https://drive.google.com/file/d/19degh6czjpUzA647wuslETWKimCV1yGT/view?usp=sharing

**Comment by WKobus** [comment]
ID of forms deleted before upgrade are not recognized as already used, due to this forms downloaded after upgrade have same ID, as the ones deleted before upgrade. In this case fix would work only for forms deleted after upgrade.

**Comment by grzesiek2010** [comment]
> ID of forms deleted before upgrade are not recognized as already used, due to this forms downloaded after upgrade have same ID, as the ones deleted before upgrade. In this case fix would work only for forms deleted after upgrade.

@seadowg we have missed that the IDs are remembered as already used only after upgrading the databases so the ones used before could potentially be reused. As a result, this scenario is possible:
1. There is a user that downloads a form and creates a savepoint.
2. The user deletes the form.
3. The user upgrades the app.
4. The user downloads a new form (the form will have the ID of the previously used form in the database).
5. When the user tries to open the new form, the app will attempt to load the savepoint created for the old, non-existing form.

I think we need to handle this by comparing the dates as in my previous implementation. Or maybe you think that we should ignore it as this shouldn't be that common and harmful?

**Comment by seadowg** [comment]
> When the user tries to open the new form, the app will attempt to load the savepoint created for the old, non-existing form.

I'm really confused by this. The save point here won't be in the save points DB if it was created in v2024.1.3 right? Is there something wrong with the way we're testing upgrades here? We want to test upgrading from v2024.3.1 to this PR, but this situation sounds like it's created by upgrading from `master` to this PR.

**Comment by grzesiek2010** [comment]
Ahh right something weird has happened here. @WKobus did you use my apks https://github.com/getodk/collect/pull/6049#issuecomment-2068167595? Please test again as @seadowg said the scenario we thought happened should not happen.

**Comment by WKobus** [comment]
@grzesiek2010 Ye, I've used apk from your comment, however I downloaded them once again and I'm not seeing savepoint from first apk loading on form after upgrade anymore, but forms deleted before upgrade are still not recognized as used and after upgrade those IDs are reused.

**Comment by seadowg** [comment]
> but forms deleted before upgrade are still not recognized as used and after upgrade those IDs are reused.

That makes sense. It doesn't cause any problems though right?

**Comment by WKobus** [comment]
@seadowg I haven't encountered any other issues with savepoints due to reused IDs.

**Comment by dbemke** [comment]
> We want to test upgrading from v2024.3.1 to this PR

In the apks we got to test there is 2023.3.1 version. Is it ok to test upgrades from 2023.3.1 or should it be 2024.1.3?

**Comment by seadowg** [comment]
> In the apks we got to test there is 2023.3.1 version. Is it ok to test upgrades from 2023.3.1 or should it be 2024.1.3?

It should really be v2024.1.3 to this PR.

**Comment by dbemke** [comment]
> It should really be v2024.1.3 to this PR.

@grzesiek2010 Could you add the apk?

**Comment by grzesiek2010** [comment]
> Could you add the apk?

The apks linked above are v2024.1.3 and this pr as I remember. Did you install it and see other versions?

**Comment by dbemke** [comment]
> Did you install it and see other versions?

yes. V1 is 2023.3.1

**Comment by grzesiek2010** [comment]
Ah I remember... if you build and install this pr the version you see is v2024.1.2 so if you try upgrading from v2024.1.3 to this pr you will see v2024.1.3 changing to v2024.1.2. Under the hood the migration would work fine but I'm pretty sure you would notice that weird change (downgrade) and it would be confusing.
Upgrading from v2023.3.1 to this pr is completely fine as v2023.3.1 and v2024.1.3 do not differ in terms of savepoints (they both have the old implementation), so I think you can test this scenario.

**Comment by dbemke** [comment]
I'm not sure about this case:
In older versions IDs get reused when all of forms are deleted. If I create a project in the old version of Collect and delete all forms. After that I upgrade and e.g. refresh the list of forms the first form gets ID 1. In the old version if all forms are removed there is no trace after forms that existed earlier in the project (used IDs) and after upgrading the first form get ID 1 (doesn't need to be the same form which had id 1 before the upgrade). Is this case ok?

**Comment by grzesiek2010** [comment]
> I'm not sure about this case:
In older versions IDs get reused when all of forms are deleted. If I create a project in the old version of Collect and delete all forms. After that I upgrade and e.g. refresh the list of forms the first form gets ID 1. In the old version if all forms are removed there is no trace after forms that existed earlier in the project (used IDs) and after upgrading the first form get ID 1 (doesn't need to be the same form which had id 1 before the upgrade). Is this case ok?

Yes. The old version did not remember the already used IDs so there is no way to know them. This is what @WKobus asked about here https://github.com/getodk/collect/pull/6049#issuecomment-2090211458 right?

**Comment by dbemke** [comment]
I'm a bit confused with 2 similar scenarios:
From the users perspective (not knowing what happens in the db)
1. I create a savepoint, delete the form, add the same form again - go to start new form, open the form -> there's no savepoint
2.  I create a savepoint of a form which has a saved draft, delete the form, add the same form again - go to start new form, open the form -> there's a savepoint (cause there was a softdelete but the user doesn't know about it)

**Comment by grzesiek2010** [comment]
> I'm a bit confused with 2 similar scenarios:
From the users perspective (not knowing what happens in the db)

> I create a savepoint, delete the form, add the same form again - go to start new form, open the form -> there's no savepoint
I create a savepoint of a form which has a saved draft, delete the form, add the same form again - go to start new form, open the form -> there's a savepoint (cause there was a softdelete but the user doesn't know about it)

I would say that in both cases the savepoint should not persist. If a user removes a form and redownloads it we don't need to care about savepoints. Do you agree @seadowg?

**Comment by dbemke** [comment]
Just to doublecheck. Savepoints shouldn't appear after upgrading the app (are removed during the upgrade)?

**Comment by grzesiek2010** [comment]
> Just to doublecheck. Savepoints shouldn't appear after upgrading the app (are removed during the upgrade)?

They should appear but they need to be migrated first: https://github.com/getodk/collect/pull/6068

**Comment by dbemke** [comment]
> > 
> 
> They should appear but they need to be migrated first: #6068

So my guess would be that after that PR the case described by Wiktor and I makes issue #6038 reproducible on upgrading the app?

**Comment by grzesiek2010** [comment]
> So my guess would be that after that PR the case described by Wiktor and I makes issue #6038 reproducible on upgrading the app?

The migration should be smart enough to avoid such issues but you will have a chance to test it once https://github.com/getodk/collect/pull/6068 is ready.

**Comment by dbemke** [comment]
We finished testing. We focused on the changes in the database and upgrades. Savepoints seem to be working well- there is one unresolved conversation in the PR but we don't want to block merging it so I guess that issue will be fixed (or not) separately.

**Comment by WKobus** [comment]
**Tested with Success!**

**Comment by seadowg** [comment]
> I would say that in both cases the savepoint should not persist. If a user removes a form and redownloads it we don't need to care about savepoints. Do you agree @seadowg?

Yeah that sounds correct to me. I think we can merge this now, and do a follow up for the draft case. @dbemke could you file an issue please?
