### PR TITLE
Fix invalid polygon state issues

### LINKED ISSUE #7054: Flickering points in a geoshape/geotrace with incremental=true
#### ODK Collect version
the master version fae66cca90720dd322aeea30993b9431a37df55c
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Flickering points in a geoshape/geotrace with incremental=true in Google maps and Mapbox

https://github.com/user-attachments/assets/3e0351de-dcda-480d-938f-79509a86ca91

#### Steps to reproduce the problem
1. Download the form 

[geoshapeTraceInvalidPolygon.xlsx.txt](https://github.com/user-attachments/files/24966543/geoshapeTraceInvalidPolygon.xlsx.txt)
or use "invalid polygon..." https://test.getodk.cloud/projects/681/app-users
2. Set Google Maps or Mapbox as a source of maps.
3. Open the form.
4. Go to "Geotrace- not intersects +incremental" or "Geoshape - not intersects +incremental" question.
5. Start adding some points (the issue occurs in all input methods).

### LINKED ISSUE #7055: Saved points are not visible in the map until new one is added
**ODK Collect version**

the master version fae66cca90720dd322aeea30993b9431a37df55c

**Android version**
12, 14

**Device used**
Pixel 3a, Samsung Galaxy M23

**Problem description**
Found during testing #7021 and #7052 Saved points are not visible in the map until new one is added. 
Reproduces on all map sources.
**Rotating the screen also makes points disappear**
 
https://github.com/user-attachments/assets/a8acae3e-db93-4d1c-85e2-1568af6d876a

**Steps to reproduce the problem**

1. Have demo project on ODK Collect
2. Navigate to the Geotrace/Geoshape question
3. Click on the Get Line/Get Polygon button
4. Add some points and save the map
5. View map again -> Saved points won't be visible in the map
6. Click on the Add Points button select Placement by Tapping and add point -> Saved points become visible again. 

**Expected behavior**
Points should not disappear from the map view.

### LINKED ISSUE #7056: Crash after saving a trace or a shape in a question with `incremental=true` in OSM
#### ODK Collect version
the master version fae66cca90720dd322aeea30993b9431a37df55c
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's a crash after saving a trace or a shape in a question with `incremental=true` in OSM

Image

#### Steps to reproduce the problem
1. Download the form
[geoshapeTraceInvalidPolygon.xlsx.txt](https://github.com/user-attachments/files/24966893/geoshapeTraceInvalidPolygon.xlsx.txt)
 or use "invalid polygon..." in https://test.getodk.cloud/projects/681/app-users
2. Go to geoshape/ geotrace - not intersects +incremental quesiton.
3. Open the map and add some points.
4. Tap the save button

### LINKED ISSUE #7057: Not possible to move a point in geoshape/geotrace with incremental = true
#### ODK Collect version
master version fae66cca90720dd322aeea30993b9431a37df55c
#### Android version
16, 10
#### Device used
Pixel 6a, Redmi 7
#### Problem description
Not possible to move a point in geoshape/geotrache with incremental = true
#### Steps to reproduce the problem
1. Scan user "Invalid polygon new forms"
2. Open geoshapeincrementalFormMap form
3. Add some points
4. Try to move point
#### Expected behavior
It should be possible to move a point in geoshape/geotrace with incremental = true

### PR DESCRIPTION
**Pull request by seadowg**
Closes #7055
Closes #7054 
Closes #7057
Closes #7056

This fixes issues with invalid polygon points not updating on the map properly.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

These changes do not touch the map engines so test with one is fine. It does however end up making some changes that affect other areas of the app:

- Managing offline map layers
- Audio recording
- Deleting blank and saved forms

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: androidshared/src/main/java/org/odk/collect/androidshared/livedata/LiveDataExt.kt [hunk 1]
```diff
@@ -4,8 +4,8 @@ import androidx.lifecycle.LiveData
 import androidx.lifecycle.MediatorLiveData
 
 object LiveDataExt {
-    fun <T, U> LiveData<T>.zip(other: LiveData<U>): LiveData<Pair<T, U>> {
-        return LiveDataUtils.zip(this, other)
+    fun <T, U> LiveData<T>.combine(other: LiveData<U>): LiveData<Pair<T, U>> {
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/livedata/LiveDataExt.kt:7]: Calling this `zip` was misleading as it behaves like `combine` and that mismatch was what ended up causing the problems in #7055.

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt [hunk 2]
```diff
@@ -297,7 +301,6 @@ class GeoPolyFragment @JvmOverloads constructor(
             }
 
             updateUi()
-            setChangeResult()
```
Comment (seadowg) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt:300]: This was causing an infinite loop! I couldn't work out how to reproduce with the threading setup in tests.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16

**Verified cases:**

-Listed issues no longer occur

1.  #7055 
2. #7054 
3. #7057
4. #7056
- Different map sources
- Regression check on audio widget
- Deleting saved and blank forms
- Regression check on maps

**Comment by srujner** [comment]
**Tested with success**

Verified on Android 14

**Comment by dbemke** [comment]
**Tested with success**

Verified on Android 10
