### PR TITLE
Restyle geoshape/geotrace

### LINKED ISSUE #6999: Crash after rotating the screen with automatic location recording on in geoshape and geotrace
#### ODK Collect version
the master version cba0e5aca791438d0a8813c89f414db94f579910
#### Android version
10, 16
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There is a crash after rotating the screen a few times when automatic location recording is on in geoshape and geotrace. I reproduced it in a geoshape/trace with not intersects and incremental=true but I think I have also noticed it in a geoshape/trace without incremental=true. I haven't been able to reproduce it in a regular geoshape/trace.
Sometimes I can reproduce it really quickly but sometimes it takes more time (more screen rotations).

Image
 
#### Steps to reproduce the problem
1. Go to the geoshape1 question not intersects question.
[geoshapeTraceInvalidPolygonIncrementalxml.xml.txt](https://github.com/user-attachments/files/24229045/geoshapeTraceInvalidPolygonIncrementalxml.xml.txt)
2. Open the map and set automatic location recording (1sec, accuracy-none)
3. Rotate the device a few times

### PR DESCRIPTION
**Pull request by seadowg**
Work towards #6962
Closes #6999
Closes #7019

This restyles traces and shapes in OSM. I also fixed a crash that could happen on rotate (#6999) as it fitted in to some work I needed to do anyway (@grzesiek2010 discussed that in #7019).

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### Do we need any specific form for testing your changes? If so, please attach one.

It's worth playing with all map engines to see if there are any performance regressions with adding/removing points with shapes/traces as how they are rendered has been changed across the board. Other than that (and the fixed issue), the style changes are isolated to OSM - Google Maps and Mapbox look a little wonky, but we'll be fixing that in follow-ups. It might be worth just doing a quick pass of things for now as we'll be making further changes to the maps with #6970.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@alyblenkin I've updated the style for OSM. Take a look and let me know if the behaviour/style is as expected, and then I can get working on making it work in Google Maps/Mapbox.

**Comment by alyblenkin** [comment]
Based on our conversation in slack, we want to align more closely with the designs from Web Forms. 
image

https://effortless-dragon-d2ff5f.netlify.app/

**Comment by seadowg** [comment]
@dbemke @srujner @WKobus are you able to have a quick play with traces/shapes? They should look inconsistent right now, but I've made some changes to simplify how they work, and I'm interested to see if it has any performance drawbacks. I'm going to have a go as well. I can end a Google Maps APK if you need it!

**Comment by srujner** [comment]
@seadowg Can it wait until Monday?
We're focusing on testing #7016 right now, and there's a lot to check there.

Google Maps APK would be helpful :)

**Comment by seadowg** [comment]
Absolutely! Not a priority, just something to check before I finish the PR off.

**Comment by alyblenkin** [comment]
Noting down a few things from my chat with Callum: 

- **Points size**: They are currently 6×, which feels better than before. They feel appropriate while actively mapping, but appear pretty large when zoomed out. Dynamically resizing markers based on zoom would be a larger lift, so we’re planning to leave this for now.
- **Invalid state**: the most recently placed point will not be highlighted when invalid, since all points will be shown in red. This may be revisited later based on feedback.
- **Select state:** later we want to clearly indicate the selected point so that moving points is more discoverable, like we do with WF.

**Comment by dbemke** [comment]
> I'm interested to see if it has any performance drawbacks.

Can you give us a hint where to look for the performance issues - adding points, saving points etc?

**Comment by seadowg** [comment]
> Can you give us a hint where to look for the performance issues - adding points, saving points etc?

Adding and removing points with shapes/traces mainly!

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt [hunk 1]
```diff
@@ -88,20 +84,25 @@ class GeoPolyFragment @JvmOverloads constructor(
...
-                if (!readOnly && map != null && originalPoly != map!!.getPolyLinePoints(featureId)) {
+                if (!readOnly && map != null && originalPoly != viewModel.points.value) {
                     showBackDialog()
                 } else {
                     cancel()
                 }
             }
         }
 
+    private val viewModel: GeoPolyViewModel by viewModels {
```
Comment (seadowg) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyFragment.kt:98]: We can probably move a bunch more of the Fragment's state in to this (or another) ViewModel, but I think this is a good start for now: we can continue improving this as part of #6970.

File: maps/src/main/java/org/odk/collect/maps/MapFragment.kt [hunk 2]
```diff
@@ -167,6 +160,10 @@ interface MapFragment {
      */
     fun hasCenter(): Boolean
 
+    fun supportsDraggablePolygon(): Boolean {
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/MapFragment.kt:163]: This lets us implement in just OSM while not completely breaking other engines. I think we should follow up with Mapbox/Google Maps implementations as that allows us to keep the change sets small and do the work in parallel if we can.

File: maps/src/main/java/org/odk/collect/maps/MapFragment.kt [hunk 3]
```diff
@@ -93,27 +93,20 @@ interface MapFragment {
...
-
-    /** Appends a vertex to the polyline or polygon specified by featureId.  */
-    fun appendPointToPolyLine(featureId: Int, point: MapPoint)
-
-    /**
-     * Removes the last vertex of the polyline or polygon specified by featureId.
-     * If there are no vertices, does nothing.
-     */
-    fun removePolyLineLastPoint(featureId: Int)
+    fun updatePolygon(featureId: Int, polygonDescription: PolygonDescription)
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/MapFragment.kt:103]: For the moment, `updatePolyLine` and `updatePolygon` aren't optimized at all, but I thought it would be good to have it set up so we can work on optimizations within the map engine code without risk of merge conflicts with work happening in `GeoPolyFragment`.

File: maps/src/main/java/org/odk/collect/maps/LineDescription.kt [hunk 4]
```diff
@@ -7,7 +7,7 @@ data class LineDescription(
     private val strokeWidth: String? = null,
     private val strokeColor: String? = null,
     val draggable: Boolean = false,
-    val closed: Boolean = false
+    @Deprecated("Use PolygonDescription instead") val closed: Boolean = false
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/LineDescription.kt:10]: Our line/polygon API for `MapFragment` was in a weird state where you could add draggable or static lines, static polygons and draggale or static closed lines. We got away with the latter because we didn't need to fill them, but now we do they need to be proper polygons under the hood.

**Comment by dbemke** [comment]
I think I found an Easter egg !!! Hidden point in the geotrace (on all devices).
esterEgg


**Steps to reproduce:**
1. Open All question types form in the demo project.
2. Tap "get line" in geotrace.
3. Select e.g. placement by tappping and add some point.
4. Tap pause and remove the points except from one
5. Tap the back button and discard changes.
6. Open the map again - the hidden point is there ;)

The way points are entered and removed doesn't matter. I haven't found it on the master version or the store version.

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+            }
+        } else {
+            points
+        }
+    )
+    val points: StateFlow<List<MapPoint>> = _points
+    private var accuracyThreshold: Int = 0
+
+    init {
+        viewModelScope.launch {
```
Comment (seadowg) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt:33]: We've talked off and on about whether to use coroutines directly like this (as opposed to through our Scheduler interface) - especially with ViewModels as it gives us `viewModelScope`. I can't immediately think of a benefit to using `Scheduler` here as this work is dispatched on the UI thread, so there's no need to integrate with `IdlingResource` for Espresso. That said, as far as I can tell, there are no tests for the automatic location recording. I'll backfill those as a follow up and see how this fits in.

**Comment by seadowg** [comment]
> I think I found an Easter egg !!! Hidden point in the geotrace (on all devices).

I can't reproduce. Could you double-check the steps? Is the point you see always in the same place?

File: maps/src/main/java/org/odk/collect/maps/MapConsts.kt [hunk 6]
```diff
@@ -1,7 +1,14 @@
 package org.odk.collect.maps
 
+import android.graphics.Color
+
 object MapConsts {
-    const val DEFAULT_STROKE_COLOR = -65536 // color-int representation of #ffff0000
+    @JvmField
+    val DEFAULT_STROKE_COLOR = Color.parseColor("#3e9fcc")
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/MapConsts.kt:7]: There is a nice `toColorInt` ext fun which you can use here and below: `Color.parseColor("#3e9fcc")` -> `#3e9fcc".toColorInt()`.

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 7]
```diff
@@ -764,7 +790,7 @@ private class MarkerFeature implements MapFeature {
         }
 
         public void setIcon(MarkerIconDescription markerIconDescription) {
-            marker.setIcon(MarkerIconCreator.getMarkerIconDrawable(map.getContext(), markerIconDescription));
+            marker.setIcon(toDrawable(getBitmap(markerIconDescription, requireContext()), requireContext().getResources()));
```
Comment (grzesiek2010) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java]: This is shor but not very readable. I would rather convert it to:
```
public void setIcon(MarkerIconDescription markerIconDescription) {
   Context context = requireContext();
   Bitmap bitmap = getBitmap(markerIconDescription, context);
   Drawable drawable = toDrawable(bitmap, context.getResources());

   marker.setIcon(drawable);
}
```

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 8]
```diff
@@ -591,7 +603,7 @@ private Marker createMarker(MapView map, MarkerDescription markerDescription) {
         marker.setPosition(toGeoPoint(markerDescription.getPoint()));
         marker.setSubDescription(Double.toString(markerDescription.getPoint().accuracy));
         marker.setDraggable(markerDescription.isDraggable());
-        marker.setIcon(MarkerIconCreator.getMarkerIconDrawable(map.getContext(), markerDescription.getIconDescription()));
+        marker.setIcon(toDrawable(getBitmap(markerDescription.getIconDescription(), requireContext()), requireContext().getResources()));
```
Comment (grzesiek2010) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java]: Similar to what I said in:
https://github.com/getodk/collect/pull/7017/files#diff-f6aeda0713ed08a5e38c4cf325e723590ec3a7143786a33cda2735069a782957R793

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt [hunk 9]
```diff
@@ -83,4 +124,9 @@ object MarkerIconCreator {
     fun clearCache() {
         cache.evictAll()
     }
+
+    @JvmStatic
+    fun MarkerIconDescription.getBitmap(context: Context): Bitmap {
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt]: `MarkerIconDescription` is our class which we can edit. Why not to put this method there instead of creating an ext fun?

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt]: `toBitmap` wouldn't be better?

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconDescription.kt [hunk 10]
```diff
@@ -4,18 +4,22 @@ import org.odk.collect.androidshared.utils.toColorInt
...
 import java.util.Locale
 
-class MarkerIconDescription @JvmOverloads constructor(
-    val icon: Int,
-    private val color: String? = null,
-    private val symbol: String? = null
-) {
-    fun getColor(): Int? = color?.toColorInt()
+sealed interface MarkerIconDescription {
+    class Resource @JvmOverloads constructor(
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/markers/MarkerIconDescription.kt]: Resource feels a bit too generic. Maybe something else?

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt [hunk 11]
```diff
@@ -22,19 +22,60 @@ object MarkerIconCreator {
...
-        val symbol = markerIconDescription.getSymbol()
+            is MarkerIconDescription.Resource -> {
+                val drawableId = markerIconDescription.icon
+                val color = markerIconDescription.getColor()
+                val symbol = markerIconDescription.getSymbol()
+
+                val bitmapId = drawableId.toString() + color + symbol
+                fromCache(bitmapId) {
+                    createBitmap(context, drawableId, color, symbol).also {
+                        cache.put(bitmapId, it)
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt]: `#fromCache` already saves Bitmap so here you don't need it.

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 12]
```diff
@@ -939,28 +964,93 @@ public List<MapPoint> getPoints() {
             }
             return points;
         }
+    }
+
+    private  class DynamicPolygonFeature implements LineFeature {
```
Comment (grzesiek2010) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java]: Hmm no error thrown for that double space between `private` and `class`?

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 13]
```diff
@@ -939,28 +964,93 @@ public List<MapPoint> getPoints() {
...
 
-        public void addPoint(MapPoint point) {
-            markers.add(createMarker(map, new MarkerDescription(point, true, CENTER, new MarkerIconDescription(org.odk.collect.icons.R.drawable.ic_map_point))));
+            map.getOverlays().add(polygon);
+            for (int i = 0; i < polygonDescription.getPoints().size(); i++) {
+                MapPoint point = polygonDescription.getPoints().get(i);
+                markers.add(getLinePointMarker(point, polygonDescription.getStrokeWidth(), i == polygonDescription.getPoints().size() - 1));
+            }
             update();
         }
```
Comment (grzesiek2010) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java:1002]: There's an extra empty line here

File: geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt [hunk 14]
```diff
@@ -128,30 +127,36 @@ class FakeMapFragment(private val ready: Boolean = false) : Fragment(), MapFragm
...
+        featureId: Int,
+        polygonDescription: PolygonDescription
+    ) {
+        polygons[featureId] = polygonDescription
     }
 
-    override fun getPolyLinePoints(featureId: Int): List<MapPoint> {
-        return polyLines[featureId]!!.points
+    override fun getPolyPoints(featureId: Int): List<MapPoint> {
+        return polyLines[featureId]?.points ?: polygons[featureId]?.points ?: emptyList()
```
Comment (grzesiek2010) [inline geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt:152]: Could we rename `polyLine` -> `polyline` for consistency?

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt [hunk 15]
```diff
@@ -22,19 +22,60 @@ object MarkerIconCreator {
...
+        val bitmap =
+            Bitmap.createBitmap(diameter.toInt(), diameter.toInt(), Config.ARGB_8888)
 
-        val bitmapId = drawableId.toString() + color + symbol
+        Canvas(bitmap).also { canvas ->
+            val radius = diameter / 2
 
+            val fill = Paint().also {
+                it.style = Paint.Style.FILL
+                it.color = Color.parseColor("#ffffff")
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt:59]: Here we can use the ext fun as well: `"#ffffff".toColorInt()`

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+import org.odk.collect.geo.geopoly.GeoPolyFragment.OutputMode
+import org.odk.collect.location.tracker.LocationTracker
+import org.odk.collect.maps.MapPoint
+
+class GeoPolyViewModel(
+    outputMode: OutputMode,
+    points: List<MapPoint>,
+    private val locationTracker: LocationTracker
+) :
+    ViewModel() {
```
Comment (grzesiek2010) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt]: It should be in the same line with `) :`

File: location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt [hunk 17]
```diff
@@ -81,7 +86,7 @@ class LocationTrackerService : Service(), LocationClient.LocationClientListener
             val interval = intent.getLongExtra(EXTRA_UPDATE_INTERVAL, -1)
             locationClient.setUpdateIntervals(
                 interval,
-                interval / 2
```
Comment (grzesiek2010) [inline location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt:84]: Should we simplify `#setUpdateIntervals` as now we alwasy pass the same values?

File: mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt [hunk 18]
```diff
@@ -357,36 +370,36 @@ class MapboxMapFragment :
...
     }
 
     override fun addPolygon(polygonDescription: PolygonDescription): Int {
         val featureId = nextFeatureId++
+        addPolgon(featureId, polygonDescription)
+
+        return featureId
+    }
+
+    private fun addPolgon(
```
Comment (grzesiek2010) [inline mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt]: Typo.

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt [hunk 19]
```diff
@@ -0,0 +1,81 @@
...
+
+    private val _points = MutableStateFlow(
+        if (!points.isEmpty()) {
```
Comment (grzesiek2010) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt]: You can use `isNotEmpty`.

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt [hunk 20]
```diff
@@ -0,0 +1,81 @@
...
+                        }
+                    }
+                }
+            }
+        }
+    }
+
+    fun add(point: MapPoint) {
+        val points = _points.value
+        if (points.isEmpty() || point != points[points.size - 1]) {
```
Comment (grzesiek2010) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt]: You can use `points.last()` instead of `points[points.size - 1]`

File: geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt [hunk 21]
```diff
@@ -0,0 +1,81 @@
...
+        }
+    )
+    val points: StateFlow<List<MapPoint>> = _points
+    private var accuracyThreshold: Int = 0
+
+    init {
+        viewModelScope.launch {
+            locationTracker.getLocation().collect {
+                if (it != null) {
+                    accuracyThreshold.let { threshold ->
```
Comment (grzesiek2010) [inline geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyViewModel.kt]: This `let` is redundant.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Comment by grzesiek2010** [comment]
> I think I found an Easter egg !!! Hidden point in the geotrace (on all devices).

> I can't reproduce. Could you double-check the steps? Is the point you see always in the same place?

Yes it was adding a point in the center of the map. I've solved it in https://github.com/getodk/collect/pull/7016 so just rebase.

File: osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java [hunk 22]
```diff
@@ -939,28 +964,93 @@ public List<MapPoint> getPoints() {
...
+        final List<Marker> markers = new ArrayList<>();
+        final Polygon polygon;
+
+        DynamicPolygonFeature(MapView map, PolygonDescription polygonDescription) {
+            this.map = map;
+            polygon = new Polygon();
+            polygon.setStrokeColor(polygonDescription.getStrokeColor());
+            polygon.setStrokeWidth(polygonDescription.getStrokeWidth());
+            polygon.getFillPaint().setColor(polygonDescription.getFillColor());
+            polygon.getFillPaint().setAlpha(MapConsts.DEFAULT_FILL_COLOR_OPACITY);
```
Comment (grzesiek2010) [inline osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java]: This is redundant. The color you use `getFillColor` already sets alpha.

**Comment by dbemke** [comment]
> Could you double-check the steps? Is the point you see always in the same place?

It always the same place. I reproduced it also in All widgets form. Steps are on OSM and I edit one step to leave one point.

File: maps/src/main/java/org/odk/collect/maps/MapConsts.kt (hunk 6 above)
Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/MapConsts.kt:7]: That function returns `Int?` rather than `Int` - I'm guessing it's for dealing with user input rather than static strings.

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt (hunk 9 above)
Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt]: > MarkerIconDescription is our class which we can edit. Why not to put this method there instead of creating an ext fun?

Good question! I guess I generally think of extension functions as just a convenience for being easier to read than static functions (with some amount of autocomplete). Here there's an advantage to using an extension function/static function over adding `getBitmap` to `MarkerIconDescription` - we don't have to add any dependencies or references to bitmap specific classes to the data class which keeps it focused on the "description" or "data" for the icon and not any of the details of how that might be displayed (which `MarkerIconCreator` deals with).

> toBitmap wouldn't be better?

Agreed!

File: geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt (hunk 14 above)
Comment (seadowg) [reply geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt:152]: It's "polyLine" on `MapFragment` so I think it's best to stay consistent with that. I guess we're treating it as "poly line" while "polygon" is one word.

File: maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt (hunk 15 above)
Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/markers/MarkerIconCreator.kt:59]: Again, that only makes sense for parsing colors from non-static Strings.

File: location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt (hunk 17 above)
Comment (seadowg) [reply location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt:84]: I can follow up with that as I'd like to investigate white it was the way it was.

**Comment by seadowg** [comment]
@dbemke I've rebased so that issue should be fixed now!

File: maps/src/main/java/org/odk/collect/maps/MapConsts.kt (hunk 6 above)
Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/MapConsts.kt:7]: >That function returns Int? rather than Int

No, it returns Int:

```
@ColorInt public inline fun String.toColorInt(): Int = Color.parseColor(this)
```

and under the hood it does the same thing.

**Review by grzesiek2010 — APPROVED** [review]

File: maps/src/main/java/org/odk/collect/maps/MapConsts.kt (hunk 6 above)
Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/MapConsts.kt:7]: I've added that change in https://github.com/getodk/collect/pull/7024 so that merging this pr is not blocked.

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/MapConsts.kt:7]: Ah looks like we've shadowed it: https://github.com/getodk/collect/blob/3daae3e6a8e9d697d401de74f90540fdf143cffb/androidshared/src/main/java/org/odk/collect/androidshared/utils/ColorUtils.kt#L7

I can rename that.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android 10

**Verified cases:**
- issues #6999 #7019 don't occur
- shapes/traces not intersecting and incremental=true in OSM, Google Maps, Mapbox
- quick checks in USGS and Carto
- adding and removing points
- snackbars
- error messages
- regression checks in geoshape and geotrace

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on devices with Android 16
