### PR TITLE
Catch OutOfMemoryError

### LINKED ISSUE #2421: Fatal Exception: java.lang.OutOfMemoryError
[From Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b18d6906007d59fcd20c5a7?time=last-seven-days&sessionId=5B54C851032F000168C149A432F7B70C_DNE_0_v2) (requires auth):

```
android.graphics.Bitmap.nativeCreate (Bitmap.java)
arrow_drop_down
android.graphics.Bitmap.createBitmap (Bitmap.java:745)
arrow_right
org.odk.collect.android.utilities.ImageConverter.rotateBitmap (ImageConverter.java:154)
org.odk.collect.android.utilities.ImageConverter.rotateImageIfNeeded (ImageConverter.java:138)
org.odk.collect.android.utilities.ImageConverter.execute (ImageConverter.java:43)
org.odk.collect.android.activities.FormEntryActivity.saveChosenImage (FormEntryActivity.java:887)
org.odk.collect.android.activities.FormEntryActivity.lambda$onActivityResult$3$FormEntryActivity (FormEntryActivity.java:748)
org.odk.collect.android.activities.FormEntryActivity$$Lambda$3.run (Unknown Source)
java.lang.Thread.run (Thread.java:841)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2421 

#### What has been done to verify that this works as intended?
I just tested `ImageWidget` and confirmed that it works well. if an OutOfMemoryError occurs its should just skip rotating an image. 

#### Why is this the best possible solution? Were any other approaches considered?
We can't do anything more here. It just may happen on older devices with low memory.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java [hunk 1]
```diff
@@ -149,9 +149,13 @@ private static void rotateImageIfNeeded(String imagePath) {
     }
 
     private static void rotateBitmap(Bitmap image, int degrees, String imagePath) {
-        Matrix matrix = new Matrix();
-        matrix.postRotate(degrees);
-        image = Bitmap.createBitmap(image, 0, 0, image.getWidth(), image.getHeight(), matrix, true);
+        try {
+            Matrix matrix = new Matrix();
+            matrix.postRotate(degrees);
+            //image = Bitmap.createBitmap(image, 0, 0, image.getWidth(), image.getHeight(), matrix, true);
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: I don't think this should be commented out?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: Ohhhh.. thanks for catching. Fixed.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java]: You just wanted to make sure I was paying attention, right? ;)

👍 Good fixes all around.

**Review by lognaturel — APPROVED** [review]
