### PR TITLE
Filter on single select and multi select question is cleared if user changes device orientation OR minimizes app OR locks and unlocks screen

### LINKED ISSUE #1427: Filter on single select and multi select question is cleared  if user changes device orientation OR minimizes app OR locks and unlocks screen
#### Software and hardware versions 
Issue discovered during testing #1415

#### Problem description
Filter on single select and multi select question is cleared when device orientation is changed, app is minimized and when user locks and unlocks the screen 

#### Steps to reproduce the problem
1. User starts job with single select question and multi select question with appearance="autocomplete" -> [select.txt](https://github.com/opendatakit/collect/files/1284588/select.txt)
2. User is on single select question and user adds some filter
3. User changes device orientation OR minimizes app OR locks and unlocks screen
4. Filter is cleared

#### Expected behavior
- Filter is not cleared even if user changes device orientation OR minimizes app OR locks and unlocks screen
- Filter is cleared only when user clears it manually

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1427 

#### What has been done to verify that this works as intended?
I've prepared a form for testing and I've tested it.

#### Why is this the best possible solution? Were any other approaches considered?
I can't see any better solution. Implemented mechanism will allow as saving state for other widgets if needed to.
 
#### Are there any risks to merging this code? If so, what are they?
Overall it should be ok we should be careful when it comes to any NullPointerExceptions because of saved states (I think I managed it well but just in case).

#### Do we need any specific form for testing your changes? If so, please attach one.
[select.txt](https://github.com/opendatakit/collect/files/1368555/select.txt)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -596,6 +603,10 @@ protected void onSaveInstanceState(Bundle outState) {
         outState.putString(KEY_ERROR, errorMessage);
         outState.putString(KEY_SAVE_NAME, saveName);
         outState.putBoolean(KEY_AUTO_SAVED, autoSaved);
+
+        if (currentView != null && currentView instanceof ODKView) {
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Technically `currentView instanceof ODKView` will return false if `currentView` is null, so you can kill the explicit `null` check.

Comment (heyjamesknight) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: (Not a big deal at all, just bringing it up because I noticed it).

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java [hunk 2]
```diff
@@ -55,6 +57,7 @@
         extends RelativeLayout
         implements Widget, AudioPlayListener {
 
+    protected Bundle state;
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java]: I would make this private and limit access via methods to avoid `state` being accidentally set null in a child class.

File: collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java [hunk 3]
```diff
@@ -246,6 +253,14 @@ protected void addQuestionMediaLayout(View v) {
         addView(v, params);
     }
 
+    public Bundle getState() {
+        saveState();
+        return state;
+    }
+
+    protected void saveState() {
+        state = new Bundle();
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java]: Can you add an `@OverridingMethodsMustInvokeSuper` annotation here? As it stands, if a child doesn't call `super.saveState` or handle managing the `state` variable themselves, then state is never set. Its unclear which is the expected behavior for overriding.

File: collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java [hunk 4]
```diff
@@ -111,6 +114,14 @@ public void onCompletion(MediaPlayer mediaPlayer) {
         super.playAllPromptText();
     }
 
+    @Override
+    protected void saveState() {
+        super.saveState();
+        if (searchStr != null) {
+            state.putString(SEARCH_TEXT + getPrompt().getIndex(), searchStr.getText().toString());
```
Comment (heyjamesknight) [inline collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java]: Example of the above comment: if someone forgets to call `super.saveState();` in another child class before a line like this we'll get an NPE.

**Review by heyjamesknight — COMMENTED** [review]
Looks good, some minor suggestions. I do worry that this adds some complexity to FEA and ODKView, but I'm not really sure what a better solution is before we have the QWidget answer saving changes finished.

**Comment by mmarciniak90** [comment]
@grzesiek2010 I noticed that problem is not resolved in case when user locks and unlocks screen and when user minimizes the app

**Comment by grzesiek2010** [comment]
@mmarciniak90 Fixed.

**Comment by mmarciniak90** [comment]
Tested with success.
All cases works as expected.
Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]
