### PR TITLE
Lint check permissions

### LINKED ISSUE #2528: Enable MissingPermission lint check
According to http://tools.android.com/tips/lint-checks:

```
This check scans through your code and libraries and looks at the APIs being
used, and checks this against the set of permissions required to access those
APIs. If the code using those APIs is called at runtime, then the program will
crash.

Furthermore, for permissions that are revocable (with targetSdkVersion 23),
client code must also be prepared to handle the calls throwing an exception if
the user rejects the request for permission at runtime.
```

https://github.com/opendatakit/collect/pull/2506/files#r213148258 suppressed that check when the target SDK version went up to 23. 

The check should be re-enabled. If it's flagging real issues, those need to be addressed. If it's flagging false alarms, the check should be suppressed locally with the [`SuppressLint`](https://developer.android.com/reference/android/annotation/SuppressLint) annotation.

### PR DESCRIPTION
**Pull request by kaftand**
Closes #2528

#### What has been done to verify that this works as intended?

1.  On master, Analyze > Inspect Code > Create Profile Containing only Missing Permissions
2. On lint-check-permissions, run same tests to show errors removed
3. Break one of the permission fixes on this branch and make sure ./gradlew lint fails
4. On lint-check-permissions, run ./gradlew lint -> build successful

#### Why is this the best possible solution? Were any other approaches considered?
Rather than ignoring MissingPermission lint checks completely in the project, we suppress them locally. Because the current MissingPermissions errors are handled, the MissingPermission check was ignored throughout the project. Incorrectly handled MissingPermissions will result in SecurityException's. Therefore, it is safer to locally suppress the current MissingPermission errors that are known to be safe, so that future MissingPermission checks will be flagged.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This has no direct effect on users. Rather, it provides more checks for developers.

#### Do we need any specific form for testing your changes? If so, please attach one.
No

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [:heavy_check_mark:] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [:heavy_check_mark:] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [N/A] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java [hunk 1]
```diff
@@ -109,7 +108,7 @@ public PropertyManager(Context context) {
         initUserDefined(prefs, KEY_METADATA_EMAIL,       PROPMGR_EMAIL,         SCHEME_MAILTO);
     }
 
-    private IdAndPrefix findDeviceId(Context context, TelephonyManager telephonyManager) {
+    private IdAndPrefix findDeviceId(Context context, TelephonyManager telephonyManager) throws SecurityException {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java:112]: How about adding a comment describing that the security exception could be caused by attempting to get the device id without permissions but that the permission check is handled by the clients of this class? It might be helpful to refer to specifically link to https://github.com/opendatakit/collect/pull/2506 to provide context because the approach is certainly surprising (and could likely eventually be simplified).

**Review by lognaturel — COMMENTED** [review]
Welcome, @kaftand, and thanks so much for the great context you have provided both in the pull request description and in comments. That has inspired me to ask for one more additional comment clarifying the added `throws SecurityException`.

File: collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java (hunk 1 above)
Comment (kaftand) [reply collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java:112]: Thanks for the feedback! Yes, the way I have done it really hides the problem, doesn't it? Let me update. Thanks for the reference to #2506, that's very helpful.

**Comment by kaftand** [comment]
Hello @lognaturel , I added the clarifying comment you requested. Please review at your convenience!

**Comment by zestyping** [comment]
I had a look over this, and it looks good to me!

@yanokwa, want to merge it?

**Review by yanokwa — APPROVED** [review]
