### PR TITLE
Fixed playing audio

### LINKED ISSUE #5989: When there are 2 audio widgets on a field-list the sound which is playing has a malfunctioning seekbar when another sound recording starts.
#### ODK Collect version
the store version 2024.1.1, the master version 8c72f975cd2239764891e99226a93cc17d3d6ced
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It’s possible to play a recorded sound and record a sound at the same time when there are two audio widgets on a field-list and the sound which is playing gets to the moment when the other audio started recording and the slider in the seekbar moves forward and backwards.
The issue doesn’t occur in the 2023.3.1 ( possible to record sound and play sound at the same time but when the sound which is playing the slider in the seekbar doesn't move forwards and backwards). 
#### Steps to reproduce the problem
1. Go to AllQ410withoutText form.
[AllQ4190withoutText.xml.txt](https://github.com/getodk/collect/files/14403236/AllQ4190withoutText.xml.txt)
2. Record sound in "audio 1” question (e.g. 20 seconds).
3. Play the recorded sound (e.g. 5 seconds of the sound).
4. While the sound is playing record sound in "audio 2” question.
5. Check what happens in audio 1 question.
#### Expected behavior
When the sound is playing the seekbar shouldn't go forward and backwards.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5989 

#### Why is this the best possible solution? Were any other approaches considered?
There were two regressions that I have addressed in this pull request:
- the audio player was flashing (after executing the steps described in the issue). This was caused because the widget kept receiving redundant updates which I handled in https://github.com/getodk/collect/pull/5992/commits/bfa07c5ea409a3865f00ceb2add814eb611f9cab. I don't know if we should send so many updates when the session is null at all but didn't feel confident enough (especially now as it will be a point release) to introduce deeper changes
- the seekbar was sometimes moved to the start position sometimes with the wrong time even (this can be reproduced by recording two audios and then playing them one by one multiple times). The problem was introduced (or rather revealed) by putting some operations in the background (specifically I'm talking about creating a new player https://github.com/getodk/collect/pull/5836/commits/f754e0778f48a1e8d3bf6d92d5ef7a0c47f43b53#diff-dd7070cc2905fbf7e644eac39e7590ff53ccf92fc0dfb39512a55315099e9619R202). The real issue according to my investigation was that before playing a new audio we never explicitly stopped the one that was already started. That means the updates were still being produced https://github.com/getodk/collect/pull/5836/commits/b4e9400f28e3dba636b085288b4d1702d00c7d08#diff-dd7070cc2905fbf7e644eac39e7590ff53ccf92fc0dfb39512a55315099e9619R158 even during the process of setting up a new media player for a new clip (see above). As a result, some updates were received after creating a new media player but before finishing its setup (before the two operations were in different threads), and those values were for example negative integers.

@seadowg you know that functionality better since you are the author so please review carefully.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please be creative. We have had multiple issues related to this functionality recently so that shows it's a very tricky area. I can't pinpoint one exact thing that should be tested, just everything audio-related.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue and other forms with audio widgets or even audio attachments.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt [hunk 1]
```diff
@@ -85,6 +86,7 @@ class AudioClipViewModel(private val mediaPlayerFactory: Supplier<MediaPlayer>,
     private fun playNext(playlist: Queue<Clip>) {
         val nextClip = playlist.poll()
         if (nextClip != null) {
+            pause()
```
Comment (seadowg) [inline audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt]: Looking at the state diagram at https://developer.android.com/reference/android/media/MediaPlayer, I think really we should be calling `MediaPlayer#stop` in `AudioClipViewModel#cleanUpAfterClip`. I think when I initially built this I assumed that `onCompletion` being called would mean that we didn't need a `stop()`, but it seems like the pause helping here would suggest that and that lines up with the "Stopped" state in the docs' charts.

We'd definitely want a test for this in `AudioClipViewModelTest`. It looks like the approach there is to use `InOrder` verifiers to check that the `MediaPlayer` is moved through he states correctly.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt (hunk 1 above)
Comment (grzesiek2010) [reply audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt]: > Looking at the state diagram at https://developer.android.com/reference/android/media/MediaPlayer, I think really we should be calling MediaPlayer#stop in AudioClipViewModel#cleanUpAfterClip. I think when I initially built this I assumed that onCompletion being called would mean that we didn't need a stop(), but it seems like the pause helping here would suggest that and that lines up with the "Stopped" state in the docs' charts.

I was thinking about that. The problem is that stops moves the seekbar to the starting position and that's nat what we had in v2023.3.1.

Comment (seadowg) [reply audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt]: > The problem is that stops moves the seekbar to the starting position and that's nat what we had in v2023.3.1.

That feels correct though I think? I guess you could argue either way whether the seeker should move to the beginning or the end when payback stops. We could also make it so the seekbar is always set to the end if the play is "stopped" rather than "paused" regardless of position.

Comment (grzesiek2010) [reply audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt]: I'm not a huge fan of the way it worked in v2023.3 but didn't want to introduce changes. If you think it's ok I can agree I guess. I will play with it.

Comment (grzesiek2010) [reply audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt]: Done.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
When a recorded sound is played and then paused and played again, after pausing the sound is played from the beginning (not the moment it was paused). The issue doesn't occur in the store version 2024.1.1.

**Steps to reproduce:**

1. Go to All widgets form to Audio widget.
2. Record sound.
3. Tap "play" and "pause".
4. Tap "play" again.

**Comment by seadowg** [comment]
@dbemke could you file an issue please? The PR has already been merged.
