### PR TITLE
Request notification permissions on Android 13+

### LINKED ISSUE #5574: Notifications don't work on Android 13
#### ODK Collect version

Current `master` branch (7938500c89f538285add79b90b35b3ab68497c96)

#### Android version

Android 13

#### Device used

Emulator

#### Problem description

Notifications (like auto send success/failure, match exactly errors etc) do not work on Android 13. The user is never asked to grant Collect permission to show notifications the notifications are never seen.

#### Steps to reproduce the problem

1. Perform a fresh installation of Collect (to prevent pre granting of permissions)
1. Enable auto send
1. Fill out and complete a form

A notification (or permissions to show notifications) is never seen. In System settings, the option to enable notifications for the app is disabled.

#### Expected behavior

~~v2023.1 asks for permission to show notifications whenever a new notification channel is created. This is most likely because that version of the app targets API 31, so we get automatic (but uncontrolled) permission requests. I imagine we ideally want to show a permission request when a setting like auto send is enabled (and also when importing settings that contain it).~~

The team discussed this, and it was decided we'd ask for notification permissions the first time the user views the main menu (so after configuring the first project). We'll need to mock up how this will look.

#### Other information 

We most likely need to declare the notification permission and add runtime permission requests as detailed [here](https://developer.android.com/develop/ui/views/notifications/notification-permission).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5574 

Show a dialog about notification permissions (and request permissions if the hit "OK") the first time the user sees the main menu. Once the user has seen the dialog (even if they dismiss it), it won't be shown again. It also won't be shown if the user has already granted notification permissions (only possible through system settings before configuring a project). The dialog will stay on screen if the device changes configuration (rotation, theme, screen size). To be very clear, the new flow for a first time user (on Android 13) will be:

1. See launch screen
2. Go through "Scan QR code" (they will see a system camera permission request here), "Manually enter..." or "Try a demo"
3. See "About permissions" dialog informing them about notification permissions
4. Click OK on dialog
    - Alternatively they dismiss the dialog and just go straight to the Main Menu
6. See a system permission request for notifications

As discussed in the issue, we decided to let the camera permission request show on its own without an explanation as it's requested in an understandable context (scanning a QR code needs the camera).

#### What has been done to verify that this works as intended?

New tests and verified manually.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

There should only be changes on Android 13, so one of the most important things to check is that the experience isn't affected on any other OS versions. It'd also be good to put the new experience through its paces to check the new behaviour on Android 13 makes sense.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt [hunk 1]
```diff
@@ -31,48 +30,69 @@ import org.odk.collect.android.utilities.ApplicationConstants
...
     private lateinit var currentProjectViewModel: CurrentProjectViewModel
 
     override fun onCreate(savedInstanceState: Bundle?) {
         initSplashScreen()
-        super.onCreate(savedInstanceState)
-        binding = MainMenuBinding.inflate(layoutInflater)
 
         CrashHandler.getInstance(this)?.also {
             if (it.hasCrashed(this)) {
+                super.onCreate(null)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:63]: `onCreate()` has to call `super.onCreate()` before returning.

File: strings/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -1186,4 +1186,9 @@
     <string name="crash_app_summary">Force an uncaught exception causing the app to crash</string>
     <string name="predicate_caching">Predicate caching</string>
 
+    <string name="permission_dialog_title">About permissions</string>
+    <string name="permission_dialog_text">You will be asked to allow ODK Collect access to the features below, select “allow” if you want to use them.</string>
+    <string name="notifications">Notifications</string>
+    <string name="required_for_notifications">Required for notifications</string>
```
Comment (seadowg) [inline strings/src/main/res/values/strings.xml]: This string is definitely not the final version. Glad to take any suggestions!

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt [hunk 3]
```diff
@@ -90,6 +110,10 @@ class MainMenuActivity : LocalizedActivity() {
         initMapbox()
         initButtons()
         initAppName()
+
+        if (permissionsViewModel.shouldAskForPermissions()) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:110]: I think this kind of logic is probably ripe to be refactored into using Jetpack's Navigation component. That's kind of "all or nothing though" - probably not worth it for this issue, but something to keep in mind for the future.

**Comment by grzesiek2010** [comment]
I'm not sure if I'm convinced that we should solve this problem in the way it is implemented in this pull request.
1. What's the plan regarding other permissions? I've got the impression that you want to ask for other permissions too in a similar way or just after creating a new project. Could you elaborate on that to make it clear? Do you want to ask for all of them once and then when they are really needed?
2. I think in the past our intention was to explain to the users why a given permission is needed. We decided to do that when such permission is declined but here we have a dialog displayed before asking for the permission with no explanation and when the permission is declined there is no additional dialog like in the case of other permissions in our app. As a result, it's not clear that those notifications are important to track the results of background jobs for example.

@lognaturel I think you should take a look at it too and share your thoughts.

**Comment by seadowg** [comment]
> What's the plan regarding other permissions? I've got the impression that you want to ask for other permissions too in a similar way or just after creating a new project. Could you elaborate on that to make it clear? Do you want to ask for all of them once and then when they are really needed?

Yes down the line we want to add more permissions to this flow (like location, audio etc). We've considered this in the past to allow people setting up the phone to grant all required permissions up front. That's discussed in the issue, but I should have put that here as context for reviewing. Sorry about that!

> I think in the past our intention was to explain to the users why a given permission is needed. We decided to do that when such permission is declined but here we have a dialog displayed before asking for the permission with no explanation and when the permission is declined there is no additional dialog like in the case of other permissions in our app. As a result, it's not clear that those notifications are important to track the results of background jobs for example.

For notification permissions, we're always going to be asking a little "out of context" as it's not like a camera or microphone permission that is usually fairly obvious (like taking a picture for example). Here, the intent is to try and explain why we're asking beforehand given they've not taken an action that would hopefully explain why they're seeing the permission. The dialog currently doesn't do a good job of that (as you point out it doesn't explain what notifications are for), so I'm asking for help with [this string](https://github.com/getodk/collect/pull/5590#discussion_r1199160017) to improve that.

**Comment by grzesiek2010** [comment]
> That's discussed in the issue, but I should have put that here as context for reviewing. Sorry about that!

I've read the issue I always do but what I saw wasn't enough to make me 100% sure this is the direction you want to go. If we are going to add the rest of permissions to that dialog then it probably makes more sense to have something like that.

**Comment by seadowg** [comment]
>  If we are going to add the rest of permissions to that dialog then it probably makes more sense to have something like that.

Great! Probably also good to note that @lognaturel has already reviewed this new flow. We should really have added a comment about that to the issue as well.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+import android.os.Build
+import android.os.Bundle
+import androidx.annotation.RequiresApi
+import androidx.fragment.app.DialogFragment
+import com.google.android.material.dialog.MaterialAlertDialogBuilder
+import org.odk.collect.android.R
+import org.odk.collect.permissions.PermissionListener
+import org.odk.collect.permissions.PermissionsProvider
+
+class PermissionsDialogFragment(
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: I think this dialog should not be cancelable. Now if you tap out of its area it's gone, wouldn't it be better to block it?

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt [hunk 5]
```diff
@@ -31,48 +30,69 @@ import org.odk.collect.android.utilities.ApplicationConstants
...
+    lateinit var viewModelFactory: MainMenuViewModelFactory
 
     @Inject
     lateinit var settingsProvider: SettingsProvider
 
+    @Inject
+    lateinit var permissionsProvider: PermissionsProvider
+
+    @Inject
+    lateinit var permissionChecker: PermissionsChecker
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt]: This is unused.

File: collect_app/src/main/res/drawable/ic_baseline_notifications_24.xml [hunk 6]
```diff
@@ -0,0 +1,5 @@
+<vector android:height="24dp" android:tint="#000000"
```
Comment (grzesiek2010) [inline collect_app/src/main/res/drawable/ic_baseline_notifications_24.xml]: Both `tint` and `fillColor` should be `?colorOnSurface`. Now the icon is always black even in dar mode.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt [hunk 7]
```diff
@@ -37,4 +29,26 @@ object TestRuleChain {
                 )
             )
     }
+
+    private fun createGrantPermissionRule() =
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt:33]: Wouldn't this be more readable:

```java
private fun createGrantPermissionRule() {
        GrantPermissionRule.grant(
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.CAMERA,
            Manifest.permission.RECORD_AUDIO,
            Manifest.permission.GET_ACCOUNTS
        )
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            GrantPermissionRule.grant(Manifest.permission.POST_NOTIFICATIONS)
        }
    }
```

File: settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt [hunk 8]
```diff
@@ -10,4 +10,5 @@ object MetaKeys {
     const val EXISTING_PROJECT_IMPORTED = "existing_project_imported"
     const val LAST_LAUNCHED = "last_launched"
     const val LAST_USED_PEN_COLOR = "last_used_pen_color"
+    const val PERMISSIONS_REQUESTED = "permissions_requested"
```
Comment (grzesiek2010) [inline settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt:13]: If we ask for this permission after creating a project shouldn't this be a project-level setting? Then after creating a new project, we would ask for this permission again if not granted.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:110]: Maybe `PermissionsDialogFragment` should check it on its own and not call `.create()` if `permissionsViewModel.shouldAskForPermissions()` returns false?

File: collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuActivityTest.kt [hunk 9]
```diff
@@ -391,4 +397,16 @@ class MainMenuActivityTest {
             assertThat(editSavedFormButton.visibility, equalTo(View.GONE))
         }
     }
+
+    @Test
+    fun `when shouldAskForPermissions is true, shows permissions dialog`() {
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuActivityTest.kt:402]: There should be a test for the case when it returns false.

File: collect_app/src/test/java/org/odk/collect/android/mainmenu/PermissionsDialogFragmentTest.kt [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+import org.mockito.kotlin.never
+import org.mockito.kotlin.verify
+import org.odk.collect.android.R
+import org.odk.collect.android.fakes.FakePermissionsProvider
+import org.odk.collect.androidshared.ui.FragmentFactoryBuilder
+import org.odk.collect.fragmentstest.FragmentScenarioLauncherRule
+import org.robolectric.annotation.Config
+
+@RunWith(AndroidJUnit4::class)
+@Config(sdk = [33])
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/mainmenu/PermissionsDialogFragmentTest.kt]: This is redundant since by default robolectric runs our code against the targetSdkVersion specified in the manifest. So it will never be lower than 33.

File: collect_app/src/test/java/org/odk/collect/android/mainmenu/RequestPermissionsViewModelTest.kt [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+import org.mockito.kotlin.doReturn
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.whenever
+import org.odk.collect.permissions.PermissionsChecker
+import org.odk.collect.settings.InMemSettingsProvider
+import org.odk.collect.settings.keys.MetaKeys
+import org.robolectric.annotation.Config
+
+@RunWith(AndroidJUnit4::class)
+@Config(sdk = [33])
```
Comment (grzesiek2010) [inline collect_app/src/test/java/org/odk/collect/android/mainmenu/RequestPermissionsViewModelTest.kt]: This is redundant since by default robolectric runs our code against the targetSdkVersion specified in the manifest. So it will never be lower than 33.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt (hunk 7 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt:33]: `GrantPermissionRule.grant` is a factory method that returns a `GrantPermissionRule` (that will grant the passed permissions), so this wouldn't work. There annoyingly isn't a "builder" approach that would make this simpler: an instance `GrantPermissionRule` is immutable.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: My thinking was that we wouldn't offer a "Cancel" button, but would allow the user to dismiss with the back button or by clicking outside the dialog. As I write that though, it feels a little like "dark design" and we should reverse it (offer a "Cancel" and make it not cancellable). @alyblenkin what do you think?

File: settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt (hunk 8 above)
Comment (seadowg) [reply settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt:13]: I think it makes sense to only ask once as the permissions themselves are app-level (not project-level) and I don't think we want to pester the user with multiple requests after the first (although Android will block more than two on newer OSs) if they've explicitly skipped it.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:110]: I did initially have this structure, but it was really difficult to test due to some missing parts of AndroidX test (see `@Ignore` tests in https://github.com/getodk/collect/pull/5590/commits/5909e4ef041450e8fa1a4430aa061c1466661440). It also felt simpler (and actually more efficient) to have the decision about showing the dialog outside.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt (hunk 4 above)
Comment (alyblenkin) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: I was also thinking if they tap outside, it would dismiss the dialog. People may think that tapping "cancel" would mean that they are opting out of these permissions when it's really just an informational dialog. We could have the X at the top so they can dismiss it, but we don't want them to be able to "cancel" anything because that's not actually happening.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt (hunk 7 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt:33]: Ah right but is that a problem if we ask for that permission on lower APIs in tests at all?

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: My thinking is that the ok button is in the corner so it might be easy to tap out of the dialog and close it without seeing the request at all. Maybe the x button would be a good solution...

File: strings/src/main/res/values/strings.xml (hunk 2 above)
Comment (grzesiek2010) [reply strings/src/main/res/values/strings.xml]: Maybe it would be good to emphasize that those notifications are used to inform about the state/result of background jobs like auto-send and auto-download.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt (hunk 7 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/rules/TestRuleChain.kt:33]: Unfortunately yes. Requesting `POST_NOTIFICATIONS` on older APIs throws an exception.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt (hunk 4 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: We could keep this as-is and add analytics for dismissing and OK clicks to see how this does?

Comment (alyblenkin) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: Yeah sounds good to me.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt:17]: Ok I've added those events in!

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:63]: Could you elaborate on this change? Why `super.onCreate(savedInstanceState)` just after `initSplashScreen()` wasn't enough?

**Review by alyblenkin — APPROVED** [review]
Reviewed with Callum this morning.

File: collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt (hunk 1 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt:63]: It's because of fragments being restored. We need to setup the `FragmentFactory` before `super.onCreate` so that Fragments can be reconstructed on rotation etc. We then also need `inject` before `super.onCreate` as injected fields will get used to create the fragments. Because we also want our `CrashHandler` stuff before `inject` to deal with cases where we can't construct the `AppDependencyComponent` (or dependency within it), we now need `CrashHandler.getInstance` above `super.onCreate`.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by srujner** [comment]
Looks like the dialog is cut off and I don't see the "Allow" button:
Screenshot_20230602-080304

**Comment by grzesiek2010** [comment]
> Looks like the dialog is cut off and I don't see the "Allow" button:

The `allow` option will be displayed once you click ok then the real request takes place. This first dialog is just information about what is going to happen but yeah the text inside is cut off.

**Comment by seadowg** [comment]
@srujner that's fixed now!

**Comment by dbemke** [comment]
There is "ED" missing in the "forms are download__" part.
noti

**Comment by seadowg** [comment]
@dbemke fixed!

**Comment by srujner** [comment]
**Tested with Success!**

**Verified on device with Android 13**

Verified cases:

- Issue #5574 is no longer reproducing;
- All notifications: Tapping on notification, clicking on show details, exit from the error list; 
- Rotate the screen, minimize the app;
- Don't keep activities setting enabled/disabled;
- Adding project manually or through QR code; 
- Switching between projects, adding duplicated projects; 
- Light and Dark mode.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10, emulated 13
