### PR TITLE
Check front camera availability and disable/enable button to capture selfie.

### LINKED ISSUE #1617: User sees misleading information in toast in Selfie widget when front camera is not available in device
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
User sees misleading information in toast in Selfie widget when front camera is not available in device

#### Steps to reproduce the problem
1. User uses device **without** front camera
2. User is on the Selfie widget
3. User clicks on 'Take Picture' button
4. User sees toast with message 'Tap the screen to take a picture'
screenshot_2017-11-08-15-51-50

#### Expected behavior
* User should be informed that front camera is not available in device

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1617

#### What has been done to verify that this works as intended?
Tested on Moto M and Moto E (having front camera) and Emulator (Nexus 5 (API 24)) (**without** front camera)
#### Why is this the best possible solution? Were any other approaches considered?
The best solution will be to check the front camera availability and accordingly enable/disable button to start activity to capture selfie. This approach requires minimum changes in code and is easy to implement. Also, it will not affect any other part of code in my opinion.
#### Are there any risks to merging this code? If so, what are they?
Target API of `CameraUtils` class is 21.
#### Do we need any specific form for testing your changes? If so, please attach one.
Need to test on physical device with configuration : API<21 **without** front camera.
Need to test on physical device with configuration : API>21 **without** front camera.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+                }
+            } else {
+                //For API Level >= 21
+                try {
+                    //https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics.html
+                    CameraManager cameraManager = (CameraManager) Collect.getInstance()
+                            .getSystemService(Collect.getInstance().CAMERA_SERVICE);
+
+                    String[] cameraId = cameraManager.getCameraIdList();
+                    for (int j = 0; j < cameraId.length; j++) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: I think you can use foreach loop here. It would look better. SOmething like:

> for (String id : cameraId)

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+                        CameraCharacteristics characteristics = cameraManager.getCameraCharacteristics(cameraId[j]);
+                        if (characteristics.get(CameraCharacteristics.LENS_FACING) == CameraCharacteristics.LENS_FACING_FRONT) {
+                            return true;
+                        }
+                    }
+                } catch (CameraAccessException e) {
+                    Timber.e(e);
+                } catch (NullPointerException e) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: You can collapse catch blocks here and use one for both exceptions.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+import android.os.Build;
+
+import org.odk.collect.android.application.Collect;
+
+import timber.log.Timber;
+
+/**
+ * Created by Akshay on 10/11/17.
+ */
+@TargetApi(21)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: You don't need this.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+                    if (ci.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
+                        return true;
+                    }
+                }
+            } else {
+                //For API Level >= 21
+                try {
+                    //https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics.html
+                    CameraManager cameraManager = (CameraManager) Collect.getInstance()
+                            .getSystemService(Collect.getInstance().CAMERA_SERVICE);
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: It should be Context.CAMERA_SERVICE not Collect.getInstance().CAMERA_SERVICE here.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java [hunk 5]
```diff
@@ -79,12 +80,15 @@ public ImageWidget(Context context, final FormEntryPrompt prompt, final boolean
...
         captureButton.setEnabled(!prompt.isReadOnly());
+
         captureButton.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
                 Collect.getInstance().getActivityLogger().logInstanceAction(this, "captureButton",
                         "click", getFormEntryPrompt().getIndex());
                 errorTextView.setVisibility(View.GONE);
+
+
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java]: Please remove at least one of these empty lines. I think we don't need both.

File: collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java [hunk 6]
```diff
@@ -121,6 +124,7 @@ public void onClick(View v) {
             }
         });
 
+
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java]: The same here we don't need two empty lines.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+
+                    String[] cameraId = cameraManager.getCameraIdList();
+                    for (int j = 0; j < cameraId.length; j++) {
+                        CameraCharacteristics characteristics = cameraManager.getCameraCharacteristics(cameraId[j]);
+                        if (characteristics.get(CameraCharacteristics.LENS_FACING) == CameraCharacteristics.LENS_FACING_FRONT) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: It might be null so you should check whether `characteristics.get(CameraCharacteristics.LENS_FACING)` is null before like here https://medium.com/google-developers/detecting-camera-features-with-camera2-61675bb7d1bf

**Comment by grzesiek2010** [comment]
@akshay-ap it will be ready for testing once you have resolved all bugs.

File: collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java (hunk 3 above)
Comment (akshay-ap) [reply collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java]: If `@TargetApi(21)` is removed, I get error during ` /gradlew lint -Pandroid.useDexArchive=false
 ` task execution as `Class requires API level 21 (current min is 16): android.hardware.camera2.CameraAccessException`. Is there any other way to do this?

**Comment by grzesiek2010** [comment]
Looks ok now. Thanks! 

@opendatakit-bot unlabel "needs review"
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
I noticed crash on two devices:
* Samsung Young without front camera, Android 4.1
* Infinix with front camera, Android 4.2

Crash occurs when user opens image widget and selfie widget.

crash

@akshay-ap this problem need to be fixed
@opendatakit-bot unlabel "needs testing"

**Comment by akshay-ap** [comment]
I think problem is due to use of API < 21. I will look over it.

**Comment by akshay-ap** [comment]
@mmarciniak90 Can you test this commit? I couldn't test it on device with api < 21 and without front camera due to some issues.

**Comment by mmarciniak90** [comment]
Tested with success.
Crash does not occur. 
I verified changes on Android 4.1, 4.2, 4.4, 5.1, 6.0, 8.0.
Only device with Android 4.1 does not have front camera.
screenshot_2017-11-16-09-21-13

**Review by lognaturel — APPROVED** [review]
