### PR TITLE
Fixed using custom LifecycleOwner for ODKView

### LINKED ISSUE #5311: Rotating the screen while a list is opened in select one widget with minimal appearance crashes the app
#### ODK Collect version
master 454905f139520d061c45c7c38adde11ee1bddc7b
#### Android version
8.1, 10, 11, 13 (probably all)
#### Device used
Nexus 5X, Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
Collect crashes when the user rotates the screen while a list is opened in select one widget with minimal appearance.
#### Steps to reproduce the problem
1. Open the demo project.
2. Go to All widgets form.
3. Go to Select one minimal widget.
4. Tap to open the list.
5. Rotate the screen.
#### Expected behavior
The app shouldn’t crash.
#### Other information 
On the store version (2022.3.6) the crash doesn’t occur.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5311 

#### What has been done to verify that this works as intended?
I've tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
In https://github.com/getodk/collect/pull/5267 we removed some redundant (duplicate) widget creations. As a result when `DialogFragment` used to display choices in select minimal widgets is recreated it tries to use `LifecycleOwner` (used to track creating and destroying `ODKView`) before that view is created and `lifecycleRegistry` in that `LifecycleOwner` is null what caused `NPE`. `lifecycleRegistry` should not be null. The method that returns it overrides `getLifecycle` which has `@NonNull `annotation. 
That's why I refactored that `LifecycleOwner` which now is called `FormPageLifecyleOwner` to make sure it never returns null even if the corresponding `ODKView` is not fully set yet.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be a safe fix. Please focus on verifying that the issue no longer exist. You can also play with audio files attached to questions/choices because the change is related to that functionality.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package org.odk.collect.android.utilities
+
+import androidx.lifecycle.Lifecycle
+import androidx.lifecycle.LifecycleOwner
+import androidx.lifecycle.LifecycleRegistry
+
+class FormPageLifecyleOwner : LifecycleOwner {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: I'm not sure that it makes sense to rename this. It's still a utility object that could be used in many different contexts and `DestroyableLifecycleOwner` makes sense with the new (more correct) behaviour in my opinion.

**Review by seadowg — CHANGES_REQUESTED** [review]
Nice change! There's tweak I'd like that I've put in as a comment.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified cases:**
- issue #5311 is no longer reproducing
- forms: All widgets, Nigeria Wards, Birds, gridwidget, mediatest, Select test
- select one/ multi
- regression checks: Fill Blank Form- form with audio 
- don’t keep activities enabled/disabled
- rotating, minimizing, locking the screen
- hierarchy view
- forms with audio files attached to questions
- using external app
- RTL

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13

During testing we encountered a small issue, posted here: https://github.com/getodk/collect/issues/5327

File: collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: Right as you said it could be used in many different contexts so it doesn't make sense to use that `FormPage` prefix. I've reverted that change but... is `Destroyable` a good one here? It's a normal class like many other so why `Destroyable`?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: I guess originally I named it that way because I needed a `LifecycleOwner` I could manually destroy (with the `destroy` method here) from the outside. Agreed it's not the best, but I'm now having trouble thinking of a better name. Any ideas?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: Yeah it's not easy in this case but maybe: `CustomLifecycleOwner`, `PlainLifecycleOwner`, `LifecycleOwnerImpl`... what do you think?

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: How about `ControllableLifecycleOwner`? I think the main feature of this implementation is that the lifecycle can be "controlled" by a client (through `start`/`stop`) as opposed to `Activity`/`Fragment` where the lifecycle transitions are not **directly** controllable.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/utilities/FormPageLifecyleOwner.kt]: Sounds better than `DestroyableLifecycleOwner` so yeah.

**Review by seadowg — APPROVED** [review]
