### PR TITLE
Fix `killAndReopenApp`

### LINKED ISSUE #5899: Fix `killAndReopenApp` implementation
Tests using `killAndReopen` app are currently ignored as they appear to fail sometimes on CI (https://getodk.slack.com/archives/C03QX56DD8C/p1704707135672449?thread_ts=1704705919.638809&cid=C03QX56DD8C) and locally (against the same device as CI).

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5899 

The core change here was to move the code that deals with dismissing the tooltip to `PrepDeviceForTestRule` and to deal with it in a new task rather than the task being used for the current test flow. The idea here is to reduce the risk of running into problems by not interfering with the test task and also by reducing the amount of times the `UIDevice` code will actually need to run.

I've run this multiple times and not seen flakes locally or on Test Lab.

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/UserInterfacePage.java [hunk 1]
```diff
@@ -24,15 +20,7 @@ public UserInterfacePage clickOnLanguage() {
...
-        try {
-            onView(withText(language)).perform(click());
-        } catch (NoMatchingViewException e) {
-            for (int i = 0; i < 10; i++) {
-                onView(withIndex(withId(android.R.id.text1), 1)).perform(ViewActions.swipeUp());
-            }
-            clickOnSelectedLanguage(language);
-        }
-
+        onData(equalTo(language)).perform(click());
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/UserInterfacePage.java:23]: I changed this as I ran into flakes with `clickOnSelectedLanguage` while testing my changes to `killAndReopenApp`.

**Review by grzesiek2010 — APPROVED** [review]
