### PR TITLE
Fixed SignatureWidget

### LINKED ISSUE #794: Signature widget in portrait mode
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
The current signature widget seems to have gone backwards from its previous capabilities. The phone switches into landscape mode for signature but then only shows a small portrait style window within that to take the signature. End results is that captured signature images are a lot smaller than the used to be and in portrait.

#### Steps to reproduce the problem
Create a form with an image with appearance signature

#### Expected behavior
The screen switches to landscape, the user has nearly the whole length of the phone to do their signature, the captured image is in landscape.

#### Other information 
device-2017-03-30-105506

@max2me,  Maxim may have a view on this issue.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #794

Form for testing:
[signature.txt](https://github.com/opendatakit/collect/files/958108/signature.txt)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java [hunk 1]
```diff
@@ -460,16 +460,15 @@ public void reset() {
...
-            // is called upon with flipped w/h (before orientation changes have been applied)
-            if (w > h) {
-                int temp = w;
-                w = h;
-                h = temp;
-            }
-
             if (mBackgroundBitmapFile.exists()) {
+                // Because this activity is used in a fixed landscape mode only, sometimes resetImage()
+                // is called upon with flipped w/h (before orientation changes have been applied)
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java:465]: We need this trick only if we open existed image not if we create new one.

**Comment by lognaturel** [comment]
Well that turned out to be a pretty simple fix! 😄 I hope it wasn't too tricky to identify.
