### PR TITLE
Catch missing configuration row for external choices

### LINKED ISSUE #6792: Missing external CSV should consistently prevent question use regardless of choice type
#### Problem description
If a form includes a `select_one` or `select_multiple` question that uses the `search()` function to retrieve choices from an external CSV file, but the CSV file is not attached, the behavior differs depending on whether internal choices with a matching dataset name are defined and whether those choices are numeric or non-numeric.

For numeric choices: The form can be filled out successfully using the internal choices (**which shouldn't take place**). However, an error occurs when attempting to edit the saved form later.

For non-numeric choices: An error about the missing CSV file is shown immediately when the form is opened, making it impossible to answer the question.

#### Steps to reproduce the problem
Just play with the attached form:
[search_external_csv.xlsx](https://github.com/user-attachments/files/21058658/search_external_csv.xlsx)

#### Expected behavior
The behavior should be consistent in both cases. The current behavior for non-numeric choices is preferable, as it clearly indicates a configuration issue with the question. Allowing a form to proceed using fallback internal choices (as with numeric values) introduces inconsistent behavior and causes errors during form editing. Therefore, the form should fail early when the required external CSV file is missing, regardless of the type of choice values.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6792 

#### Why is this the best possible solution? Were any other approaches considered?
~~The issue was that the `populateExternalChoices` method, which is responsible for reading from external CSV files, returned internal choices if they existed for values represented as integers: [https://github.com/getodk/collect/pull/6794/commits/08fcc82d76afd42c86a09615e20e35f742b4ec88#diff-5dca0a8d3dc453ec1b67830005c61a9c5a3e4d845c06181cff53506e36c3680dL175](https://github.com/getodk/collect/pull/6794/commits/08fcc82d76afd42c86a09615e20e35f742b4ec88#diff-5dca0a8d3dc453ec1b67830005c61a9c5a3e4d845c06181cff53506e36c3680dL175)
However, this method should always read from the CSV file, as that is its intended purpose.~~

~~I'm not really sure why it was implemented in this way.~~

**It turned out that tearting numeric choices in a different way is a feature - see comments in https://github.com/getodk/collect/issues/6792.**

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Playing with forms that read choices from external files is what we need to test here to make sure there is no regression introduced.

#### Do we need any specific form for testing your changes? If so, please attach one.
I've used: [dynamic_and_static_choices.xlsx](https://github.com/user-attachments/files/22568021/dynamic_and_static_choices.xlsx)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
Some details about how I think we should address this at https://github.com/getodk/collect/issues/6792#issuecomment-3201883125

File: collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUtil.java [hunk 1]
```diff
@@ -345,4 +342,30 @@ public static boolean isAnInteger(String value) {
             return false;
         }
     }
+
+    /**
+     * The config row is a special row in the choices worksheet that defines how
+     * choices are mapped from an external .csv file with list_name, name and label,
+     * where these correspond to columns in the .csv file.
+     */
+    private static boolean containsConfigurationChoice(List<SelectChoice> selectChoices) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUtil.java:351]: The test and the name are backwards from each other! If you find a choice that has a non-integer value, you should return true and if you get all the way through without one then return false.

At the call site you want `!containsConfigurationChoice` -- throw an exception if there is no file configuration choice.

File: test-forms/src/main/resources/forms/dynamic_and_static_choices.xml [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    </h:head>
+    <h:body>
+        <select1 ref="/data/fruits" appearance="search('fruits')">
+            <label>Choose a fruit</label>
+            <item>
+                <label>name</label>
+                <value>name_key</value>
+            </item>
+            <item>
+                <label>Apples</label>
```
Comment (lognaturel) [inline test-forms/src/main/resources/forms/dynamic_and_static_choices.xml]: Let's make this more realistic and make the choice label "None of the above." This pattern is mostly useful for this kind of system option that doesn't fit in with the other items to select from.

**Review by lognaturel — CHANGES_REQUESTED** [review]
Couple of changes requested inline!

File: test-forms/src/main/resources/forms/dynamic_and_static_choices.xml (hunk 2 above)
Comment (grzesiek2010) [reply test-forms/src/main/resources/forms/dynamic_and_static_choices.xml]: Done.

File: collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUtil.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUtil.java:351]: Fixed.

**Review by lognaturel — APPROVED** [review]

**Comment by dbemke** [comment]
The apk has been removed. Could you run the build again?

**Comment by grzesiek2010** [comment]
It should be there now.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified cases:**
- issue #6792 doesn't occur
- search function with missing CSV files
- search function with CSV files added
- search function with integers in the external CSV file and internal choices
- search function with integers and string in external CSV file and internal choices
- regression checks in other forms with search function

**Comment by WKobus** [comment]
**Tested with success**

Verified on Android 16
