### PR TITLE
Disable Markup button if default image couldn't be loaded

### LINKED ISSUE #3634: Markup Image button should be disabled when there is no media or path to default image is invalid.
#### Software and hardware versions 
Collect v1.26x, Android v4-10, device used...

#### Problem description
For Annotate widget with default image described Markup Image button should be enabled only when path to default image is described in a correct way. Currently, when delete media and open form Markup button is enabled. The same issue is visible when the default image path is described in incorrect way. Screenshots attached:
| invalid | media deleted |
| -------- | -------- |
Screenshot from 2020-02-11 11-19-30 | Screenshot from 2020-02-11 11-19-12 

#### Steps to reproduce the problem
Just open Annotate widget with default image described in the wrong way or delete media. I have used form: 
[defaultImage.zip](https://github.com/opendatakit/collect/files/4185248/defaultImage.zip)

#### Expected behavior
Markup Image button should be active only when the picture is added/ path to default image is described correctly.

### PR DESCRIPTION
**Pull request by chidauri**
Closes #3634 

#### What has been done to verify that this works as intended?
Tested on android 9 device

#### Why is this the best possible solution? Were any other approaches considered?
This is a simple solution. Another option might be to call `setUpLayout()` after `addCurrentImageToLayout()` .

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
None.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form mentioned in the issue.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java [hunk 1]
```diff
@@ -65,6 +65,9 @@ public AnnotateWidget(Context context, QuestionDetails prompt) {
         imageCaptureHandler = new ImageCaptureHandler();
         setUpLayout();
         addCurrentImageToLayout();
+        if (errorLoadingImage) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: I think you don't need this at all... what about a check like?
```
        if (binaryName == null || imageView == null || imageView.getVisibility() == GONE) {
            annotateButton.setEnabled(false);
        }
```

there is a similar check:
```
if (binaryName == null) {
            annotateButton.setEnabled(false);
        }
```

in `setUpLayout()` method so you could remove it there.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java (hunk 1 above)
Comment (chidauri) [reply collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: Done.

File: collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java [hunk 2]
```diff
@@ -65,6 +65,9 @@ public AnnotateWidget(Context context, QuestionDetails prompt) {
         imageCaptureHandler = new ImageCaptureHandler();
         setUpLayout();
         addCurrentImageToLayout();
+        if (binaryName == null || imageView == null || imageView.getVisibility() == GONE) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java]: It would be good to factor it out to a separate method like adjustAnnotateButtonaAailability(0 for example.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
It looks good just one possible improvement I mentioned.
Could you also add an automated test? Ideally in `AnnotateWidgetTest` class if possible. If not it can be also an espresso test.

**Comment by chidauri** [comment]
@grzesiek2010 does the test look good? also sorry for so much delay.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> @grzesiek2010 does the test look good? also sorry for so much delay.

yes it looks great now. Thanks!

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 6.0, 7.0, 8.1, 9.0
Verified on an emulator with Android 5.1.
`Markup Image` button is inactive

Verified cases:
* form with default image described in the wrong way
* form with a correct default image
* Adding/ removing response

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
