### PR TITLE
Catch runtime exceptions that might occur during form validation

### LINKED ISSUE #5671: The app crashes if a form contains a repeatable group that has the number specified dynamically and that number is not an integer
#### ODK Collect version
v2023.2

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/d7c3c3214cb1618c6590e23a2d90da2c?time=last-seven-days&versions=v2023.2.1%20(4675);v2023.2.0%20(4672)&types=crash&sessionEventKey=64AD62C502B600014270DF3CE17A95B7_1833010861648226587

The app crashes if a form contains a repeatable group that has the number specified dynamically and that number is not an integer (double for example).

#### Steps to reproduce the problem
1. Open the attached form [RepeatCountTest.xlsx](https://github.com/getodk/collect/files/12027195/RepeatCountTest.xlsx)
2. Pass and double (eg. 2.3) in the first question.
3. Click the three dots option and select `Check for errors`.

#### Expected behavior
The app should not crash. There should be an error dialog so that the behavior is consistent with what happens when after passing a double in the first question a user navigates forward in the form instead of using the new `Check for errors` option.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5671 

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
As discussed on slack the root issue is https://github.com/getodk/javarosa/issues/686 and there is even a pull request that addresses that issue but for now (for a point release) I don't think we should implement changes in javarosa. It's enough to make sure that when the problem occurs during form validation the app does not crash but an error dialog is displayed.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think that focusing on the issue and verifying that it doesn't exist anymore would be enough here. I don't see any risk.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java [hunk 1]
```diff
@@ -396,15 +396,19 @@ public int answerQuestion(FormIndex index, IAnswerData data) throws JavaRosaExce
...
+            if (validateOutcome != null) {
+                this.jumpToIndex(validateOutcome.failedPrompt);
+                if (indexIsInFieldList()) {
+                    stepToPreviousScreenEvent();
+                }
+                return new FailedValidationResult(validateOutcome.failedPrompt, validateOutcome.outcome);
             }
-            return new FailedValidationResult(validateOutcome.failedPrompt, validateOutcome.outcome);
+            return SuccessValidationResult.INSTANCE;
+        } catch (RuntimeException e) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java:409]: I did here exactly what we already do in `stepToPreviousScreenEvent`/`stepToNextScreenEvent` just catch `RuntimeException` and turn it into `JavaRosaException` so that then it's handled properly and an error dialog is displayed.

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 12 and 13

Verified cases:
- Issue #5671 is no longer reproducing;
- Error dialog is visible instead of crash;
- Hierarchy view;
- Other forms with Repeat;
- Minimize the app, rotate the screen, block the app
