### PR TITLE
Fix external apps returning data when Collect is being restored

### LINKED ISSUE #5646: Minimizing the app with no background processes setting moves the user to the first question
#### ODK Collect version
v 2023.2. Beta 3
#### Android version
10, 11
#### Device used
Redmi 9T, Galaxy M12
#### Problem description
There is a difference in the expected result compared to 2023.1.2. In the present 2023.2 Beta 3 following the steps described below results in being moved to the first question, while in 2023.1.2 the user was moved to the second question.
#### Steps to reproduce the problem
1. Set "Background process limit" to "No background processes" in Developer Options.
2. Open a form with a Select One From Map question.
3. Go to the second question.
4. Go to the hierarchy view.
5. Switch to another app.
6. Go back to Collect.
#### Expected behavior
In the store version 2023.1.2 expected behavior was that the user is at the second question after going back to the form.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #5646
Potentially fixes [this crash](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/e3a3fb3d7d9a95533db04ddc128acc25?time=last-seven-days&versions=v2023.2.3%20(4681)&types=crash&sessionEventKey=64D0A9E70053000112F56C3F4D67F098_1842938818000071237)

As well as fixing the issue above, this fixes the problem discovered by @grzesiek2010:

> 1. Set "Background process limit" to "No background processes"
> 2. Open a form with an image widget
> 3. Click "Take picture"
> 4. Switch to another app and get back to the camera app
> 5. Take a picture in the camera app

#### What has been done to verify that this works as intended?

New (local) tests written to both replace and extend (the now deleted) `ProcessRestoreTest`. These tests use raw Robolectric rather than AndroidX as testing lifecycles like this requires features that [AndroidX does not support](https://github.com/android/android-test/issues/1825). As part of writing these tests, I've pulled a few things out of `androidTest` to shared modules (such as `testshared` and `androidtest` for example) so as not to duplicate test support code in `test`. I also moved our test forms to a new module that allows local tests to access them (also to prevent duplication).

#### Why is this the best possible solution? Were any other approaches considered?

I've just made the minimum changes required to get the new tests passing. I think there's a lot we could do to make this nicer using the new save instance state/activity result APIs, removing reliance on static state etc, but most of the effort here was getting reliable testing in place which I think has given us a big enough PR.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

As well as the issues this fixes, I think testing form loading/entry in general and having a play with "Don't keep activities" and "Background process limit" would be good.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java [hunk 1]
```diff
@@ -2098,17 +2092,6 @@ public void loadingComplete(FormLoaderTask task, FormDef formDef, String warning
                 }
             }
 
-            boolean pendingActivityResult = task.hasPendingActivityResult();
-
-            if (pendingActivityResult) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:2101]: I believe this mechanism was used to handle receiving activity results like for example images (ImageWidget) after process death?
Now (even without this change but using the current master) if you have no background processes set in `Developer options` the result (image in this case) is ignored and the form is reloaded which means we end up in the hierarchy view. As I remember in the past it was possible to receive activity results in such a case. The changes you have implemented in that area recently changed that and I don't know if that was a deliberate decision.
I'm afraid that when using some older devices with little memory it might be difficult to receive some activity results when switching to other apps is required like when taking photos because then the form is reloaded and we are moved to the hierarchy view and the result is ignored.

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:2101]: > Now (even without this change but using the current master) if you have no background processes set in Developer options the result (image in this case) is ignored and the form is reloaded which means we end up in the hierarchy view. As I remember in the past it was possible to receive activity results in such a case. The changes you have implemented in that area recently changed that and I don't know if that was a deliberate decision.

I tried this and it still seems to work. The steps I ran through were:

1. Set "Background process limit" to "No background processes"
2. Open a form with an image widget
3. Click "Take picture"
4. Take a picture in the camera app

In this case in both v2023.1.2 and v2023.2.2 I return to Collect with the picture. Are you seeing different results? I had thought you were probably correct though and that the Collect process would be in "the background" while the Camera is doing it's thing. Maybe Android keeps processes waiting for results in the foreground? Maybe this differs between API levels if that's the case?

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:2101]: I think in my scenario there was one extra step which was switching to another app after opening the camera app. So it would be:

1. Set "Background process limit" to "No background processes"
2. Open a form with an image widget
3. Click "Take picture"
4. Switch to another app and get back to the camera app
5. Take a picture in the camera app

Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java:2101]: Ah I see. That flow is definitely not working any longer (it is in v2022.4.4). I can switch this PR from removing that code, to getting it working again!

**Comment by seadowg** [comment]
@getodk/testers I'm marking this as "needs testing" early as I'm currently not able to write tests for the fix for the issue or for the new one @grzesiek2010 found:

1. Set "Background process limit" to "No background processes"
2. Open a form with an image widget
3. Click "Take picture"
4. Switch to another app and get back to the camera app
5. Take a picture in the camera app

Please verify that both problems are fixed and also have a go at finding any other related problems around process restores and "external" data. I can look at working out automated testing once we know my fixes actually work!

**Comment by dbemke** [comment]
What would be the expected result now for the issue #5646?

**Comment by seadowg** [comment]
> What would be the expected result now for the issue https://github.com/getodk/collect/issues/5646?

I think ideally it should return to the hierarchy in the same place (same group) as it was in before. Do you think that makes sense? Is that currently how it's behaving?

**Comment by dbemke** [comment]
Yes, it returns to the hierarchy view - for me looks great as it's consistent with other cases of returning to a form

**Comment by seadowg** [comment]
@dbemke does it look like the issue that @grzesiek2010 reported is fixed as well? It is as far as I can tell!

**Comment by seadowg** [comment]
I wrote a post going deeper into how all testing works here which might be useful for @grzesiek2010: https://www.seadowg.com/2023/08/14/simulating-activity-recreation-with-robolectric.html.

**Comment by dbemke** [comment]
> does it look like the issue that @grzesiek2010 reported is fixed as well?

Yes. The issue is fixed

**Comment by dbemke** [comment]
I don't know if the PR should influence also this case. In video widget minimizing the app while recording a video with no background processes settings, after going back the recording is stopped/disappears (no crash and possible to start a new recording, but the recording which was on is not saved).

**Comment by seadowg** [comment]
> I don't know if the PR should influence also this case. In video widget minimizing the app while recording a video with no background processes settings, after going back the recording is stopped/disappears (no crash and possible to start a new recording, but the recording which was on is not saved).

I wouldn't expect it to fix this. Does that issue also occur on `master`/Play Store version?

**Comment by dbemke** [comment]
On master version after minimizing it's possible to start a new recording but after tapping "V" to confirm to upload the video, the user is moved to the first page of the form and none of the recordings is saved. In the PR the second recording (the one started after minimizing) is saved.

**Comment by seadowg** [comment]
> On master version after minimizing it's possible to start a new recording but after tapping "V" to confirm to upload the video, the user is moved to the first page of the form and none of the recordings is saved. In the PR the second recording (the one started after minimizing) is saved.

So it's changed, but it's (arguably) better now? Sounds like there is still a bug around not being able to record a a video in the background though that we should file separately?

**Comment by dbemke** [comment]
> So it's changed, but it's (arguably) better now? Sounds like there is still a bug around not being able to record a a video in the background though that we should file separately?

I think it's better. I'll file the issue after merging this PR.

**Comment by dbemke** [comment]
We finished testing for now so we'll remove the label "needs testing". As discussed in Slack, please let us know when/if we should continue testing in case of some changes.
Issues mentioned in the PR are fixed. The issue connected with video widget will be filed separately.

File: test-forms/build.gradle.kts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+plugins {
+    id("java-library")
+    id("org.jetbrains.kotlin.jvm")
+}
+
+java {
+    sourceCompatibility = JavaVersion.VERSION_1_7
```
Comment (grzesiek2010) [inline test-forms/build.gradle.kts]: We have recently started using java 17 in other modules so here it should be the same not 7

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt [hunk 3]
```diff
@@ -90,9 +90,20 @@ class FormEntryActivityTestRule : ExternalResource() {
...
     }
 
-    fun restoreActivity() {
+    fun restoreActivity(): FormEntryActivityTestRule {
         savedInstanceStateProvider.setState(outState)
         scenario = ActivityScenario.launch(intent)
+        return this
+    }
+
+    fun simulateProcessRestart(): FormEntryActivityTestRule {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt:76]: I imagine that we might need those methods in other tests too. Wouldn't it be better to put them in `CollectTestRule` or a helper class so that they can be easily used in tests that start with creating a new project?

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt [hunk 4]
```diff
@@ -90,9 +90,20 @@ class FormEntryActivityTestRule : ExternalResource() {
         return this
     }
 
-    fun restoreActivity() {
+    fun restoreActivity(): FormEntryActivityTestRule {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt]: This method is no longer used.

File: collect_app/src/androidTest/java/org/odk/collect/android/TestSettingsProvider.kt [hunk 5]
```diff
@@ -0,0 +1,21 @@
+package org.odk.collect.android
+
+import androidx.test.core.app.ApplicationProvider
+import org.odk.collect.android.application.Collect
+import org.odk.collect.android.injection.DaggerUtils
+import org.odk.collect.settings.SettingsProvider
+import org.odk.collect.shared.settings.Settings
+
+// Use just for testing
+object TestSettingsProvider {
```
Comment (grzesiek2010) [inline collect_app/src/androidTest/java/org/odk/collect/android/TestSettingsProvider.kt]: We have a separate class for android and unit tests. Does that mean it can't be shared?

File: collect_app/build.gradle [hunk 6]
```diff
@@ -389,6 +381,7 @@ dependencies {
     testImplementation Dependencies.androidx_test_core_ktx
 
     androidTestImplementation project(':androidtest')
+    androidTestImplementation project(':test-forms')
```
Comment (grzesiek2010) [inline collect_app/build.gradle:384]: Should we move other resources like media files there too?

File: testshared/src/main/java/org/odk/collect/testshared/EspressoHelpers.kt [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+    fun assertText(text: String) {
+        onView(allOf(withText(text), withEffectiveVisibility(VISIBLE)))
+            .check(matches(not(doesNotExist())))
+    }
+
+    fun clickOnContentDescription(string: Int) {
+        onView(withContentDescription(string)).perform(click())
+    }
+
+    fun assertIntents(vararg activityClasses: KClass<*>) {
```
Comment (grzesiek2010) [inline testshared/src/main/java/org/odk/collect/testshared/EspressoHelpers.kt]: This method is unused.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt (hunk 3 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt:76]: Ah there's actually a bunch of clean up I should now that we've moved that process restore stuff to Robolectric.

File: collect_app/src/androidTest/java/org/odk/collect/android/TestSettingsProvider.kt (hunk 5 above)
Comment (seadowg) [reply collect_app/src/androidTest/java/org/odk/collect/android/TestSettingsProvider.kt]: The old way of sharing (using a shared source set) isn't supported anymore. The `androidTest` one is actually only used in 3 places, so I can just replace those calls so we don't have the duplicated object.

File: collect_app/build.gradle (hunk 6 above)
Comment (seadowg) [reply collect_app/build.gradle:384]: Yeah sounds good! I'll keep the instances and dbs in where they are for now, but move all the media files so everything for the test forms is in one place.

**Review by grzesiek2010 — APPROVED** [review]
