### PR TITLE
Fixed comparing media files in order to detect updates

### LINKED ISSUE #4882: User sees a message about update after successfully auto-update when `Previously downloaded forms only` option is set
#### Software and hardware versions 
Collect v2021.3 beta 2, v2021.2.4

#### Problem description
User sees a message about update after successfully auto-update when `Previously downloaded forms only` option is set

#### Steps to reproduce the problem
1. Central/Aggregate server is set
2. `Previously downloaded forms only` and `Automatic download` is set
3. User has downloaded form with media - e.g. All widgets
4. New version of this form with new media is added to the server
5. User sees a notification that form was downloaded successfully, user can fill new version
6. User opens `Get Blank Forms` and sees message suggesting that there is a new version

#### Expected behavior
Message in `Get Blank Forms` should not be visible

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4882

#### What has been done to verify that this works as intended?
I have reproduced the issue and confirmed that this fix works well. I Have also added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that if we had multiple forms with the same id but different versions during comparing media files we would get media files from the first one from the list which in our case usually would be the oldest one and not the one with the version and id we are looking for https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4882?expand=1#diff-d241c237e50a73d5233d52f1d174193cc3692fe2aa977b654ac5e02ff39f13d7L83

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please just verify that the issue no longer exists and the message about outdated forms is really displayed when it should be. Nothing else should be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media files.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java [hunk 1]
```diff
@@ -158,4 +160,16 @@ private static boolean isMediaFileAlreadyDownloaded(List<File> localMediaFiles,
     private String getMd5HashWithoutPrefix(String hash) {
         return hash == null || hash.isEmpty() ? null : hash.substring("md5:".length());
     }
+
+    private Form getFormByVersion(List<Form> forms, @Nullable String expectedVersion) {
+        for (Form form : forms) {
+            if (expectedVersion == null && form.getVersion() == null) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java]: You could use `Objects.equals(form.getVersion(), expectedVersion)`, I believe.

File: collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcherTest.java [hunk 2]
```diff
@@ -131,13 +131,48 @@ public void whenAFormExists_andHasUpdatedMediaFileOnServer_isUpdated() throws Ex
...
+
+        formsRepository.save(new Form.Builder()
+                .formId("form-2")
+                .version("2")
+                .md5Hash("form-2-hash")
+                .formFilePath(FormUtils.createXFormFile("form-2", "2").getAbsolutePath())
+                .formMediaPath(mediaDir2.getAbsolutePath())
+                .build());
+
+        File oldMediaFile2 = TempFiles.createTempFile(mediaDir2, "blah", ".txt");
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcherTest.java]: Could you just reference the `mediaFile` field here to make it really explicit we're using the same file?

**Review by seadowg — CHANGES_REQUESTED** [review]
One small tweak and I think @lognaturel's suggestion is good as well.

File: collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java]: Right, fixed.

File: collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcherTest.java (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcherTest.java]: Ok I improved it a bit.

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 8.1 and 10.0

Verified cases:
* Central server with `Previously downloaded forms only` and `Automatic download`
* Aggregate server with `Previously downloaded forms only` and `Automatic download`
* auto-download new version with new media
* auto-download new version of form without media
* Central server and match exactly
* Aggregate server and match exactly

**Comment by kkrawczyk123** [comment]
Verified also on Androids: 5.1, 9.0 and 11.
