### PR TITLE
Fixed displaying the list of forms while creating a shortcut

### LINKED ISSUE #6693: The list of forms isn’t displayed while creating a shortcut
#### ODK Collect version
the store version 2025.1.4, the master version 2c5d4148bb1a71ee3112cbe221e65a7d31c3c84c
#### Android version
8.1, 11, 14
#### Device used
Nexus 5X, Galaxy M12, Pixel 7a
#### Problem description
The list of forms isn’t displayed while creating a shortcut unless the user rotates the screen or goes to "start new form” (after downloading forms) before trying to create the shortcut.
The issue was reported on the forum  https://forum.getodk.org/t/create-shortcut-of-a-form-in-home-screen-still-relevant-for-form-that-seldom-changed-what-about-for-form-that-frequently-changed/54519?
#### Steps to reproduce the problem
1. Install Collect and download the demo project.
2. Download forms (don’t go to Start new form).
3. Try to create a shortcut to a form.
#### Expected behavior
A shortcut should be created.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6693 

#### Why is this the best possible solution? Were any other approaches considered?
The issue was that we observed the list of forms only until we received the first non-null value. As a result, when the default empty list was emitted, we considered it complete and stopped observing. However, we shouldn't stop observing at that point - forms might still be downloading in the background, and the list should continue to be updated accordingly.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should only fix the way the list of foms is displayed. I can't see any big risk here.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
I think we should release this as a hotfix. @grzesiek2010 are you able to change the target branch? I tried just switching it here, but it needs a proper rebase.

File: collect_app/src/test/java/org/odk/collect/android/external/AndroidShortcutsActivityTest.kt [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import org.odk.collect.android.utilities.FormsRepositoryProvider
+import org.odk.collect.android.utilities.InstancesRepositoryProvider
+import org.odk.collect.androidtest.ActivityScenarioLauncherRule
+import org.odk.collect.async.Scheduler
+import org.odk.collect.formstest.InMemInstancesRepository
+import org.odk.collect.settings.SettingsProvider
+import org.odk.collect.testshared.Assertions
+
+@RunWith(AndroidJUnit4::class)
+class AndroidShortcutsActivityTest {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/AndroidShortcutsActivityTest.kt]: Could we not test this in `AndroidShortcutsTest` instead by adding a match exactly project and then running background work once the shortcuts screen is open? That way we don't need a new test file or a lower level test that's in any way tied to the implementation.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Comment by seadowg** [comment]
Adding needs testing as I've only requested test changes.

**Comment by WKobus** [comment]
**Tested with success**

Verified on device with Android 11

**Verified cases:**

- Issue #6693 does not occur
- Quick regression check in shortcuts

**Comment by dbemke** [comment]
**Tested with success**

Verified on device with Android 8.1, 14

File: collect_app/src/test/java/org/odk/collect/android/external/AndroidShortcutsActivityTest.kt (hunk 1 above)
Comment (seadowg) [reply collect_app/src/test/java/org/odk/collect/android/external/AndroidShortcutsActivityTest.kt]: @grzesiek2010 just waiting for a response here!

Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/AndroidShortcutsActivityTest.kt]: Sorry, I've missed it, it is done.

**Review by seadowg — APPROVED** [review]
