### PR TITLE
Dismiss the offline layers confirmation dialog on activity recreation

### LINKED ISSUE #6219: Minimizing the app with "no background processes” removes offline layers to add from the list and then trying to add layers crashes the app
#### ODK Collect version
the master version 7d30e187d65ecb5351a9b029d7b48c1fa0ee9181
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Minimizing the app with "no background processes” settings on removes offline layers to add from the list and then trying to add layers crashes the app.
crashLayers

#### Steps to reproduce the problem
1. Set "no background processes" in the device.
2. Go to any form with maps and open the map.
3. Tap the offline layers icon, "add layers” and select some layers to add.
4. While on "Add layers” with the list of layer to add, minimize the app and go to a different app.
5. Go back to Collect (the list of layers to add is empty).
6. Tap "add layers”.
#### Expected behavior
I'm not sure what is the expected result - if it's possible to keep offline layers on the list in this case or it's better to close all the dialogs/bottom sheets

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6219 

#### Why is this the best possible solution? Were any other approaches considered?
We agreed in the issue that dismissing the dialog is the solution we want for now.
I wanted to handle that case in `OfflineMapLayersImporter` but it didn't seem to be easy so I did it in `OfflineMapLayersPicker` (the dialog that shows the confirmation dialog).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This requires ensuring that the dialog is being dismissed on activity recreation (the case described in the issue). This should not happen on configuration changes (for example when you rotate your device).

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt [hunk 1]
```diff
@@ -116,6 +116,13 @@ class OfflineMapLayersPicker(
             dismiss()
         }
 
+        if (sharedViewModel.layersToImport.value?.value == null) {
```
Comment (seadowg) [inline maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt:119]: This is probably the right way to solve this, but it does feel like we're working against ourselves here a little to have to write specific code for this case.

Considering it more, I'm realizing an alternative would be to fully support this case with Fragment args - pass the list of URIs as an arg to `OfflineMapLayersImporter` (and then have it call `loadExistingLayers`) instead of communicating them via the ViewModel. I don't like this nearly as much, but it does feel like where Android is pushing us given we have state we want to this Fragment to be able between full recreations.

Another alternative (which wouldn't support full recreation) would be to rework the UI a little to not show `OfflineMapLayersImporter` until there `layersToImport` is available. This would prevent us from having to deal with the lifecycle problem at all. 

What do you think? Perhaps we could look at one of those as part of #6198 and go with this approach (just avoiding the crash) for now?

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt:119]: > Another alternative (which wouldn't support full recreation) would be to rework the UI a little to not show OfflineMapLayersImporter until there layersToImport is available. This would prevent us from having to deal with the lifecycle problem at all.

This would require dismissing the confirmation dialog programmatically either way (that's the thing we don't like the most I guess). Plus I think it's better to display that dialog immediately and have the loading indicator there not in the first one (at least it makes more sense with the current UI).

I will take a look at the first option which was my first implementation and I liked it. If it doesn't require a lot of changes I will do that otherwise we can think about it later.

Comment (seadowg) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt:119]: > I will take a look at the first option which was my first implementation and I liked it. If it doesn't require a lot of changes I will do that otherwise we can think about it later.

Sounds good!

Comment (grzesiek2010) [reply maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt:119]: Ok I still like option 1 but I think we should leave it as is for now (merge this pr) and see if it's still the best solution once we figure out how we want to rework the UI in https://github.com/getodk/collect/issues/6198

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14

**Verified Cases:**
- Issue #6219 does not occur
- Check on offline layers in settings and geo questions
- Don't keep activities enabled/disabled
- No background processes
- Rotating device

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10
