### PR TITLE
Do not allow to perform rest of the code in onCreate() if not exactly one matching form was detected

### LINKED ISSUE #4336: NullPointerException in FormMapViewModel.getFormTitle(FormMapViewModel.java:43)
#### Software and hardware versions 
Collect v1.27+

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/27c36d6d10118a0367d013e9bf34592a?time=last-thirty-days&versions=v1.29.2%20(4041)&sessionEventKey=5FF7AFE902960001643FFBE9E19AF159_1493637213128445742

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.odk.collect.android.forms.Form.getDisplayName()' on a null object reference
       at org.odk.collect.android.activities.viewmodels.FormMapViewModel.getFormTitle(FormMapViewModel.java:43)
       at org.odk.collect.android.activities.FormMapActivity.onCreate(FormMapActivity.java:119)
       at android.app.Activity.performCreate(Activity.java:7963)
       at android.app.Activity.performCreate(Activity.java:7952)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4336

#### What has been done to verify that this works as intended?
I tested the behavior hardcoding false in https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4336?expand=1#diff-8dc5817ca05b86da0282112ffd78f381a37cc6e9061c194d4ac355e6dc5f4bcdR105

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that calling finish() is not enough and we need to call return to avoid calling other code in a method.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel I think we can add this fix to v1.29.3 without testing.
The only thing is that maybe we should consider adding a toast when this case takes place? Otherwise we click on the map icon and nothing happens what might be confusing.

**Comment by lognaturel** [comment]
Is it possible maybe that this issue comes from a misunderstanding of the lifecycle of intents? It's making the assumption that the intent that the activity was launched by will continue to exist even after activity/process death. Is that maybe just not the case and we should be saving `form` in `savedInstanceState`?

EDIT: if that were the case I'd expect to be able to reproduce and I can't.

**Comment by lognaturel** [comment]
> we click on the map icon and nothing happens what might be confusing

~I'm a confused by the stacktrace below `Instrumentation.callActivityOnCreate`. `Instrumentation`? Is this real users or some kind of automation that's hitting this?~ I guess that's how activities are launched? Still, are you sure that this problem shows up after clicking the map icon/ on first launch of the activity?

**Comment by lognaturel** [comment]
Yikes, the logs are really strange. See [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/27c36d6d10118a0367d013e9bf34592a?time=last-ninety-days&sessionEventKey=5F9C0F7502A2000120F36C3E41FE2DAA_1467844132319835769) or [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/27c36d6d10118a0367d013e9bf34592a?time=last-ninety-days&sessionEventKey=5F9A940D0270000118B73AA6AE73E9AA_1467426972242572069) where the crash happens immediately after launch. It looks like no activity was even visited. I have no idea what that's about.

Or [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/27c36d6d10118a0367d013e9bf34592a?time=last-ninety-days&sessionEventKey=5F99368601B800013738CD3920BC982E_1467042935523415634) or [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/27c36d6d10118a0367d013e9bf34592a?time=last-ninety-days&sessionEventKey=5F97CCBD0153000145AE07F5C28EC483_1466653722562160001) where the activity displayed before the crash is not `FillBlankFormActivity`. 

I'm fine with adding the `return`. I don't think we should add a toast or anything.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java [hunk 1]
```diff
@@ -104,10 +104,11 @@
         List<Form> forms = dao.getFormsFromCursor(dao.getFormsCursor(getIntent().getData()));
         if (forms.size() == 1) {
             form = forms.get(0);
-        } else {
+        } else if (viewModelFactory == null) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:107]: Why add this condition? I think we want to exit in any other case. For example, it could be possible for no form to match the id.

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:107]: `viewModelFactory` should only be `null` in tests and in that case it will always be `null`.

**Review by lognaturel — CHANGES_REQUESTED** [review]
See inline.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java:107]: Oh, I see. It's `null` in the NON-test case and so you're avoiding this branch for tests. But can't you instead make sure the tests always have exactly one form so the `else` branch doesn't get hit?

**Review by lognaturel — APPROVED** [review]
Right, I see what's going on, now. The `else` branch is only relevant if we're not in a test context because in a test context the viewmodel and its form will have been manually supplied.

As you suggest, let's get it in the point release so we can see if that reveals another crash.
