### PR TITLE
ODK crashes after using geotrace osm with an automatic mode

### LINKED ISSUE #1090: ODK crashes after using geotrace osm with an automatic mode.
#### Software and hardware versions 
Collect v1.7.0

#### Problem description
ODK crashes after using geotrace with an automatic mode.

#### Steps to reproduce the problem

1. Open a form with a geotrace widget
2. Open a map and start recording points automatically
3. Stop recording using "save button" or using device buck button
4. ODK crashes after some time (depends on selected time)

#### Other information 
here is a form for testing: 
[geotrace.txt](https://github.com/opendatakit/collect/files/1044746/geotrace.txt)

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1090

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java [hunk 1]
```diff
@@ -360,8 +360,11 @@ public void finish() {
     @Override
     protected void onDestroy() {
         super.onDestroy();
-    }
 
+        if (schedulerHandler != null && !schedulerHandler.isCancelled()) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java]: As I said in the description the crash occurs only when we use OSM but we should cancel schedulerHandler here as well.

File: collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java [hunk 2]
```diff
@@ -378,6 +378,14 @@ protected void onStop() {
         disableMyLocation();
     }
 
+    @Override
+    protected void onDestroy() {
+        super.onDestroy();
+
+        if (schedulerHandler != null && !schedulerHandler.isCancelled()) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java:385]: As I said in the description the crash occurs only when we use OSM but we should cancel schedulerHandler here as well. I debugged the project and despite the fact it works without any crash recording location is running after we close the map view.
