### PR TITLE
Disabled tapping of list items after one item is selected in My Drive

### LINKED ISSUE #651: Double clicking on folder in Google Drive listing results in crash
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
Double clicking on a folder in "Get Blank Form" when protocol is "Google Sheets, Google Drive" results in crash.

#### Steps to reproduce the problem
1. Set protocol to "Google Sheets, Google Drive"
1. Select a Google account that has at least one folder in its GDrive
1. Tap on "Get Blank Form"
1. Tap "My Drive"
1. Double tap on a folder in the drive

#### Expected behavior
The app should not crash.

#### Other information 
I think this is happening because listing a directory is a time-consuming action and shouldn't be triggered again before completion. This should be fixable by disabling tapping on items in the list until the operation requested completes.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.odk.collect.android.logic.DriveListItem org.odk.collect.android.adapters.FileArrayAdapter.getItem(int)' on a null object reference
E/AndroidRuntime(17777):     at org.odk.collect.android.activities.GoogleDriveActivity.onListItemClick(GoogleDriveActivity.java:371)
E/AndroidRuntime(17777):     at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
E/AndroidRuntime(17777):     at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(17777):     at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime(17777):     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
E/AndroidRuntime(17777):     at android.widget.AbsListView$3.run(AbsListView.java:3860)
E/AndroidRuntime(17777):     at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(17777):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17777):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17777):     at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(17777):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17777):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17777):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(17777):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 4192):   Force finishing activity 1 org.odk.collect.android/.activities.GoogleDriveActivity
```

### PR DESCRIPTION
**Pull request by pratikmjoshi**
Fixes #651

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 1]
```diff
@@ -103,4 +105,22 @@ public View getView(int position, View convertView, ViewGroup parent) {
         }
         return v;
     }
+    @Override
+    public boolean isEnabled(int position) {
+        if (areAllItemsEnabled()) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Given that `areAllItemsEnabled()` is overridden to just return `enabled`, `isEnabled` is equivalent to `return enabled`. Please remove `areAllItemsEnabled()` and simplify the boolean return!

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 2]
```diff
@@ -103,4 +105,22 @@ public View getView(int position, View convertView, ViewGroup parent) {
...
+            return false;
+        }
+        return true;
+    }
+    @Override
+    public boolean areAllItemsEnabled() {
+        return enabled;
+    }
+
+    public void enableAdapterClick(boolean enabled) {
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: I think a better name for this one would be `setEnabled`.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 3]
```diff
@@ -379,6 +380,7 @@ protected void onListItemClick(ListView l, View v, int position, long id) {
                 createAlertDialog(getString(R.string.no_connection));
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java:381]: I think you'll want to re-enable the adapter if the network isn't available, otherwise things won't be clickable when the connection comes back.

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 4]
```diff
@@ -389,7 +391,9 @@ protected void onListItemClick(ListView l, View v, int position, long id) {
                 toDownload.add(o);
             }
             mDownloadButton.setEnabled(toDownload.size() > 0);
+
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Please remove these extra blank lines!

**Review by lognaturel — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java (hunk 2 above)
Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: And I think if you just need the method locally, making it private would tighten the code.

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java [hunk 5]
```diff
@@ -103,4 +105,22 @@ public View getView(int position, View convertView, ViewGroup parent) {
...
+        this.enabled = enabled;
+    }
 }
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: This new line should go into the checkstyle for sure.

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java (hunk 2 above)
Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: @nribeka it's what gets called from `GoogleDriveActivity`

Comment (nribeka) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: Ah nevermind, I thought it's just being used internally. It is exposed. So it should be public.

**Comment by pratikmjoshi** [comment]
@lognaturel Sorry about that. I've made the necessary changes. Please take a look.

File: collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java (hunk 5 above)
Comment (pratikmjoshi) [reply collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java]: @nribeka What exactly does that no new line at end of file mean? Is it necessary to have a new line?

File: collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java [hunk 6]
```diff
@@ -390,6 +393,7 @@ protected void onListItemClick(ListView l, View v, int position, long id) {
             }
             mDownloadButton.setEnabled(toDownload.size() > 0);
         }
+
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java]: Another extra blank line!

**Comment by pratikmjoshi** [comment]
@lognaturel Removed the blank line.

**Review by lognaturel — APPROVED** [review]
