### PR TITLE
Fixed issue #1400

### LINKED ISSUE #1400: FormEntryActivity Refactor - getQuestionPrompts() is called twice back to back in createView.
Line 1325 of FormEntryActivity calls getQuestionPrompts, and then immediately calls it again. Since this is a computed property we're double calculating.

The second call should be removed and the existing `prompts` value should be used.

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1400

#### What has been done to verify that this works as intended?
`getQuestionPrompts()` called only once. 
#### Why is this the best possible solution? Were any other approaches considered?
`prompts` object is used instead of calling `getQuestionPrompts()` again.

#### Are there any risks to merging this code? If so, what are they?
No

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -1315,7 +1315,7 @@ public void onClick(View v) {
                     FormEntryPrompt[] prompts = formController.getQuestionPrompts();
                     FormEntryCaption[] groups = formController
                             .getGroupsForCurrentIndex();
-                    odkv = new ODKView(this, formController.getQuestionPrompts(),
+                    odkv = new ODKView(this, prompts,
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Please just use one line here. It's too short now.

Comment (akshay-ap) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: ok. Will do it.

**Review by lognaturel — APPROVED** [review]
