### PR TITLE
Fixed getFileExtensionFromUri() method

### LINKED ISSUE #2822: The app crashes after returning from audio recorder with saved audio
#### Software and hardware versions 
Collect v1.18.0 and newer versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5bd8d140f8b88c2963e1df64?time=last-seven-days&sessionId=5C497B1003580001677DBDB8D94F5C85_DNE_0_v2

```
org.odk.collect.android.dao.helpers.ContentResolverHelper.getFileExtensionFromUri (ContentResolverHelper.java:88)
org.odk.collect.android.activities.FormEntryActivity.onActivityResult (FormEntryActivity.java:814)
android.app.Activity.dispatchActivityResult (Activity.java:7351)
android.app.ActivityThread.deliverResults (ActivityThread.java:4328)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4376)
android.app.ActivityThread.-wrap19 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1670)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:6635)
```

#### Other information 
I wasn't able to reproduce the issue.
I saw a user report: https://forum.opendatakit.org/t/odk-collect-v1-19-beta/17446/2?u=grzesiek2010
And a few crash reports on Firebase: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5bd8d140f8b88c2963e1df64?time=last-seven-days&sessionId=5C497B1003580001677DBDB8D94F5C85_DNE_0_v2

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2822 

In the description, I said that I'm not able to reproduce the issue but then I realized my wife uses Xiomi which is the most popular device in reports and bingo :smile: 
I doubt Marzena and Kasia have a device to reproduce the issue and I can't share my wife's one of course so looks like you have to believe me it's fixed.

#### What has been done to verify that this works as intended?
I tested the fix on Xiomi Redmi 4A which I was able to reproduce the issue on.

#### Why is this the best possible solution? Were any other approaches considered?
I decided not to remove the original way of receiving a file extension since in most cases it works well (only a few reports). So I use the new way only if the first approach fails (I can't be sure it's perfect that's why I use it as a last resort).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't change anything, it should just fix the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with `AudioWidget` like `AllWidgets` form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java [hunk 1]
```diff
@@ -78,15 +80,21 @@ public static String getFormPath(Uri uri) {
...
+    public static String getFileExtensionFromUri(Context context, Uri fileUri) {
         try (Cursor returnCursor = getContentResolver().query(fileUri, null, null, null, null)) {
             if (returnCursor != null && returnCursor.getCount() > 0) {
+                String filename = null;
                 int nameIndex = returnCursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
-                returnCursor.moveToFirst();
-                String filename = returnCursor.getString(nameIndex);
-                // If the file's name contains extension , we cut it down for latter use (copy a new file).
-                if (filename.lastIndexOf('.') != -1) {
+                if (nameIndex != -1) {
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java:88]: Added just in case because maybe in the future we run into a problem where OpenableColumns.DISPLAY_NAME doesn't exist at all like it was in https://github.com/opendatakit/collect/pull/2613

**Review by cooperka — APPROVED** [review]
Code LGTM, and I trust this fixes the crash on that particular device, but this logic looks like the sort of thing that deserves some unit tests since there are so many different cases. I'm still new here so I'll leave it up to you to decide whether that's a blocker 🤖

**Comment by cooperka** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
I am also using xiaomi phone so I was able to verifed. 
Tested on Andorid 7.1.
I am able to record audio, to play it, finalize form and no crashes visible!
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by grzesiek2010** [comment]
Oh, that's great! Thanks @kkrawczyk123

**Review by yanokwa — APPROVED** [review]

**Comment by yanokwa** [comment]
@grzesiek2010 Can you file an issue to add a few tests? Or if it's easier, add a few tests. Once one of those is done, we can merge.

**Comment by grzesiek2010** [comment]
> Can you file an issue to add a few tests? Or if it's easier, add a few tests. Once one of those is done, we can merge.

Done: https://github.com/opendatakit/collect/issues/2834
