### PR TITLE
Fixed autosend

### LINKED ISSUE #5191: Setting auto send to cellular only sends submissions without SIM card in phone while wifi is on
**Software and hardware versions** 

Collect v2022.3, Android probably all

**Problem description**

User is able to send submissions to Central when in settings there is auto send with cellular only although there is no SIM card in the phone. It happens when wifi is turned on in the phone.

**Steps to reproduce the problem**

1. Take out SIM card
2. Go to Settings→ Form management → Auto send
3. Choose Cellular only
4. Go to All widgets form
5. Fill in some answers
6. Check Mark form as finalized
7. Click Save Form and Exit

**Expected behavior**

Submissions should not be auto sent to Central.

**Other information** 

Also on Collect v2022.2.2.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5191

#### What has been done to verify that this works as intended?
I've added new tests and tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
This is a result of our discussion from https://github.com/getodk/collect/pull/5047. We decided that `AutoSendTaskSpec` should be simple and not responsible for checking network conditions. That's why I moved checking if auto send should be triggered out of that class to small separated classes that we can test easily.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should fix the issue but the pr also contains some additional refactoring so please test autosend carefully.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@seadowg this is a new implementation of https://github.com/getodk/collect/pull/5047. No rush but when you have time please take a look to that it won't hang too long like the previous pull request.

File: collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java [hunk 1]
```diff
@@ -519,8 +521,18 @@ public FormsUpdater providesFormsUpdater(Context context, Notifier notifier, Syn
     }
 
     @Provides
-    public InstanceAutoSender providesInstanceAutoSender(Context context, Notifier notifier, Analytics analytics, GoogleAccountsManager googleAccountsManager, GoogleApiProvider googleApiProvider, PermissionsProvider permissionsProvider, InstancesAppState instancesAppState) {
-        return new InstanceAutoSender(context, notifier, analytics, googleAccountsManager, googleApiProvider, permissionsProvider, instancesAppState);
+    public AutoSendSettingsProvider providesAutoSendSettingChecker(NetworkStateProvider networkStateProvider, SettingsProvider settingsProvider) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java]: `AutoSendSettingsProvider` and `InstanceAutoSendFetcher` could just be constructed in `providesInstanceAutoSender` right? It definitely looks a little cleaner to have separate `@Provides` for each of these objects, but it does mean that they get exposed to (can be injected into) anything that uses Dagger.

**Comment by seadowg** [comment]
@grzesiek2010 I'm liking the structure of this a lot! Was going to dig a little deeper, but are there any other changes you'd like to make first before this comes out of draft?

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProviderTest.kt [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+import org.junit.Test
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.whenever
+import org.odk.collect.androidshared.network.NetworkStateProvider
+import org.odk.collect.projects.Project
+import org.odk.collect.settings.InMemSettingsProvider
+import org.odk.collect.settings.keys.ProjectKeys
+
+class AutoSendSettingsProviderTest {
+    private lateinit var autoSendSettingsProvider: AutoSendSettingsProvider
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProviderTest.kt]: Nitpick: instead of `setupAutoSendSettingChecker` assigning this field, could it just return the `AutoSendSettingsProvider` so that you end up with a local `val` in each of the tests? It's not a big thing here, but I generally find trying to isolate each test method/block as much as possible helps down the road as test files get bigger.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 I'm liking the structure of this a lot! Was going to dig a little deeper, but are there any other changes you'd like to make first before this comes out of draft?

No I left it as a draft but I don't have anything else to add so You can continue reviewing.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    private val settingsProvider: SettingsProvider
+) {
+
+    fun isAutoSendEnabledInSettings(projectId: String): Boolean {
+        val currentNetworkInfo = networkStateProvider.networkInfo ?: return false
+
+        val autosend = settingsProvider.getUnprotectedSettings(projectId).getString(ProjectKeys.KEY_AUTOSEND)
+        var sendwifi = autosend == "wifi_only"
+        var sendnetwork = (autosend == "cellular_only").also {
+            Analytics.log(AnalyticsEvents.CELLULAR_ONLY)
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt]: I think this will log regardless of the value of  `(autosend == "cellular_only")`. Unless I'm misunderstanding, it should be something like:

```kotlin
(autosend == "cellular_only").also {
    if (it) {
        Analytics.log(AnalyticsEvents.CELLULAR_ONLY)
    }
}
```

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+import org.odk.collect.forms.instances.Instance
+import org.odk.collect.formstest.FormUtils.buildForm
+import org.odk.collect.formstest.InMemFormsRepository
+import org.odk.collect.formstest.InMemInstancesRepository
+import org.odk.collect.formstest.InstanceUtils.buildInstance
+import org.odk.collect.projects.Project
+import org.odk.collect.shared.TempFiles.createTempDir
+
+class InstanceAutoSendFetcherTest {
+    private lateinit var instanceAutoSendFetcher: InstanceAutoSendFetcher
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt]: I think you can just assign the field here and avoid the `lateinit` right?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt]: Right, fixed.

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt]: Right, done.

File: collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java]: Done.

File: collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProviderTest.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProviderTest.kt]: Done.

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt [hunk 5]
```diff
@@ -47,15 +47,16 @@ class AutoSendTaskSpecTest {
...
+                settingsProvider: SettingsProvider?,
                 context: Context?,
                 notifier: Notifier?,
                 analytics: Analytics?,
                 googleAccountsManager: GoogleAccountsManager?,
                 googleApiProvider: GoogleApiProvider?,
                 permissionsProvider: PermissionsProvider?,
                 instancesAppState: InstancesAppState?
-            ): InstanceAutoSender {
+            ): InstanceAutoSender? {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: I think this might have slipped in from an auto signature change?

**Review by seadowg — APPROVED** [review]

File: collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt (hunk 5 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt]: Right, fixed.

**Comment by dbemke** [comment]
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
Forms with auto send set to false are send automatically when in settings user chooses options that sends forms automatically (e.g. auto send-wifi only with wifi on, auto send-cellular only with SIM card and wifi off)
#### Steps to reproduce the problem
1. In Collect go to settings → form management → auto send.
2. Choose "wifi or cellular".
3. Go to Auto-Send_False_Auto-Delete_False form.
[Auto-Send_False_Auto-Delete_False.xml.txt](https://github.com/getodk/collect/files/9960030/Auto-Send_False_Auto-Delete_False.xml.txt)
4. Fill and finalize the form.
#### Expected behavior
The form should not be sent automatically.
#### Other information 
On master ffcb17ff5ca59c10b5643311e0164a06c79767d5 the form works as expected.

**Comment by grzesiek2010** [comment]
@dbemke 
The problem should be solved.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Verified Cases:**
- issue #5191 and the issue with forms with autosend set to false are no longer reproducing
- auto send: off, wifi only, cellular, wifi or cellular
- with/ without SIM card
- wifi on/off
- switching between projects with different settings in auto send
- changing auto send settings in duplicate project
- auto sending submissions
- sending submissions manually
- finilizing an edited form
- form with auto send set to true/false and auto delete set to true/false

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13
