### PR TITLE
Fixed auto-delete and auto-sent options

### LINKED ISSUE #3768: Form-level auto-delete option is not read from correct form version
#### Software and hardware versions 
Collect v1.26.1 and prior

#### Problem description
The `InstanceUploader.formShouldBeAutoDeleted` method does not take form version into account. This means that if a form update changes the auto-delete option, that may or may not be reflected in Collect's behavior.

#### Steps to reproduce the problem
1. Transfer a form with auto-delete set to false such as [this one](https://docs.google.com/spreadsheets/d/1rvg8VDX9Z_F_1KGvzPGNyxzw_bl3hImFgpOMk4Xn5UE/edit?usp=sharing)
1. Modify the form to set auto-delete to true and change the form version
1. See that the old auto-delete setting is used because the old form def is returned first in `InstanceUploader.formShouldBeAutoDeleted`

#### Expected behavior
For each instance sent, the attribute value for the version that was used to fill the instance should be used.

#### Other information 
This is a good opportunity to clean up the code here and use higher-level constructs like `Form` domain objects. Ideally each instance wouldn't have to hit the database to get this value.

It would also be good to check `auto-send` and the other columns that may be read in this way.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3768 

#### What has been done to verify that this works as intended?
I reproduced the issue and confirmed that this pr fixes it.

#### Why is this the best possible solution? Were any other approaches considered?
It is just a bug fix. Before we didn't take form versions into account while reading auto-sent and auto-delete props from database.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe change that should just fix the issue. Nothing else should be affacted.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Did you consider tests for this? I'm wondering whether you could use the `FormsRepository` to make that possible. It might then be better to wait for #4013 to be merged.

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 it looks like `FormsRespository#get(String jrFormId, String jrVersion)` is on `master` so this could just use that. It'd make sense for the `FormsRepository` to be a constructor level dependency of the `InstanceSubmitter` I think. That way it should be feasible to write tests for it with the `InMemFormsRepository` (similar to those in `FormDeleterTest`).

**Review by seadowg — CHANGES_REQUESTED** [review]
As above

**Comment by grzesiek2010** [comment]
Ok I used `FormsRespository` and added tests using `InMemFormsRepository`.
I decided to place methods that check autoSend/autoDelete in InstanceUploaderUtils because they are called from various places so I think that utils class is a good choice.
Please review.

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java [hunk 1]
```diff
@@ -1887,7 +1887,7 @@ private void handleSaveResult(FormSaveViewModel.SaveResult result) {
                         // finalized specifies that it should always be auto-sent.
                         String formId = getFormController().getFormDef().getMainInstance().getRoot().getAttributeValue("", "id");
                         String formVersion = getFormController().getFormDef().getMainInstance().getRoot().getAttributeValue("", "version");
-                        if (InstanceUploaderUtils.formShouldBeAutoSent(formsRepository, formId, formVersion, GeneralSharedPreferences.isAutoSendEnabled())) {
+                        if (InstanceUploaderUtils.shouldFormBeSent(formsRepository, formId, formVersion, GeneralSharedPreferences.isAutoSendEnabled())) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Could this not just always call `formSubmitMananer.scheduleSubmit()` at this point? I might have missed something but I think the `InstanceSubmitter` (that the `AutoSendTaskSpec` will use will do the right thing and only send if it needs to.

If that's the case we could just test `InstanceSubmitter` rather than the static method (as it will be the only place we make that decision).

File: collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java [hunk 2]
```diff
@@ -154,7 +154,7 @@ public static boolean formShouldBeAutoSent(FormsRepository formsRepository, Stri
      *
      * If the form explicitly sets the auto-delete property, then it overrides the preference.
      */
-    public static boolean formShouldBeAutoDeleted(FormsRepository formsRepository, String jrFormId, String jrFormVersion, boolean isAutoDeleteAppSettingEnabled) {
+    public static boolean shouldFormBeDeleted(FormsRepository formsRepository, String jrFormId, String jrFormVersion, boolean isAutoDeleteAppSettingEnabled) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java:100]: Might be nice to have these static methods in a new `InstanceUtils` class in either `instancemanagement` or `instances`. I can see us pulling the other methods out at some point (maybe as part of #3988).

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I was thinking about it as well. I didn't change it because I think it would change the default behavior a bit. Now autosend is triggered if we save a form that requires it, that's why we have that check (`InstanceUploaderUtils.shouldFormBeSent()`). If we get rid of it it will be triggered even if just one of already saved forms requires autosend.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I know it's misleading because if you save a form that requires autosend the app will also send other already saved forms that require it too but it doesn't work the other way around - even if all already saved forms require autosend but the one you save in this step doesn't it won't be triggered. Probably we should rethink it @lognaturel

Comment (lognaturel) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: I think (hope?) in most cases the distinction won't matter because the instance currently being saved will be the only one available for auto submission.

One extreme case is if there are multiple submissions that are hanging around and systematically fail AND there's a form in play that doesn't auto send. In that case there's some advantage to the existing check. That doesn't seem very likely to me so I'd be ok with the simpler implementation.

Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java]: Ok I removed that check and moved `shouldFormBeSent()` to `InstanceSubmitter`. However `shouldFormBeDeleted()` is still placed in `InstanceUploaderUtils` because it's used from different classes (InstanceUploaderTask). I noticed that the code between that `InstanceUploaderTask` and `InstanceSubmitter` is duplicated so probably it would be good to refactor it using `InstanceSubmitter` in `InstanceUploaderTask` maybe? Then both `shouldFormBeSent()` and `shouldFormBeDeleted()` would be placed in just one class (`InstanceSubmitter`). What do you think? Maybe as a separate pr if you agree?

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java [hunk 3]
```diff
@@ -35,20 +35,26 @@
...
+        this.formsRepository = formsRepository;
+        this.instancesRepository = instancesRepository;
     }
 
     public Pair<Boolean, String> submitUnsubmittedInstances() throws SubmitException {
         List<Instance> toUpload = getInstancesToAutoSend(GeneralSharedPreferences.isAutoSendEnabled());
+        return submitSelectedInstances(toUpload);
+    }
 
+    public Pair<Boolean, String> submitSelectedInstances(List<Instance> toUpload) throws SubmitException {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java:60]: I think this is meant to be `private`

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java [hunk 4]
```diff
@@ -147,19 +149,11 @@ public InstanceSubmitter(Analytics analytics) {
...
-        Cursor cursor = new FormsDao().getFormsCursorForFormId(jrFormId);
-        String formLevelAutoSend = null;
-        if (cursor != null && cursor.moveToFirst()) {
-            try {
-                int autoSendColumnIndex = cursor.getColumnIndex(AUTO_SEND);
-                formLevelAutoSend = cursor.getString(autoSendColumnIndex);
-            } finally {
-                cursor.close();
-            }
+    public static boolean shouldFormBeSent(FormsRepository formsRepository, String jrFormId, String jrFormVersion, boolean isAutoSendAppSettingEnabled) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java:164]: In my head this would ideally be a `private` method that is just an implementation detail of `InstanceSubmitter`. The `InstanceSubmitter` would then have tests around it that setup instances and check that they are sent in the right contexts. Looking at though there is a lot of dependencies on static calls we'd need to pull out to write that test (`Collect.getInsance().getComponent()` and `GeneralSharedPreferences.isAutoSendEnabled()` for example). This PR moves the needle forward so I don't think it makes sense to block it on that rework.

Could you maybe just add a `@Deprecated` to this method and a `@deprecated` Javadoc explaining that really it should be a private method and that that requires refactoring `InstanceSubmitter` to make it testable/modular?

**Review by seadowg — CHANGES_REQUESTED** [review]
Just a couple of tweaks!

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java (hunk 3 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java:60]: I thought about future and refactoring the code where we could use this method from InstanceUploaderTask because as I sad there are duplicated code here and in that class.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java (hunk 4 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java:164]: Ok, done.

File: collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java (hunk 3 above)
Comment (seadowg) [reply collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java:60]: Ah I see. I would tend to leave this private until then. It might be that when we make that change it would make sense for this logic to move to a different object that's responsible for submitting a single instance and then have this object use that which nicely separates collecting the instances to auto submit from the logic to actually submit one. Not a big deal for the moment though!

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 9.0

Verified cases:
* uploaded to Aggregate 4 different versions
   * orx:auto-delete="false" orx:auto-send="true"
   * orx:auto-delete="true" orx:auto-send="true"
   * orx:auto-delete="true" orx:auto-send="false"
   * orx:auto-delete="false" orx:auto-send="false"
* forms downloaded manually
* `Exactly match server` set
* unselect `Hide old form versions` and fill a version with a lower number

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
