### PR TITLE
Instances synchronization resolved

### LINKED ISSUE #625: Deleted form data still displayed in the UI
#### Software and hardware versions 
Collect latest build from master

#### Problem description
When user delete form data (instances) from the sd card, the form data will still gets displayed in the list of form data because the form data display only use the data from the database.

#### Steps to reproduce the problem
* Fill a blank form
* Delete the xml file from the sdcard (using adb or connecting the phone as drive)
* Go to the list of form data and the deleted form data will still be there.

#### Expected behavior
* Form data record from the database should be in sync with the underlying physical xml file. When user delete the xml file, we should delete the dangling record from the database as well.

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Fix #625 
Slicing is also done on deletion of forms if number of forms deleted is greater than the SQLITE_MAX_VARIABLE_NUMBER then slicing is done so that we don't get "Expression tree is too large " error.

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java [hunk 1]
```diff
@@ -103,14 +107,22 @@ protected String doInBackground(Void... params) {
...
                     }
+
                 } finally {
                     if (instanceCursor != null) {
                         instanceCursor.close();
                     }
                 }
 
+                InstancesDao instancesDao = new InstancesDao();
+                instancesDao.deleteInstancesFromIDs(filesToRemove.toArray(new String[filesToRemove.size()]));
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java]: I think you can change the parameter to list since you're gonna use the array directly (you're going to reassign the values from the array to another array).

File: collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java [hunk 2]
```diff
@@ -145,6 +146,41 @@ public void deleteInstancesDatabase() {
...
+                        ApplicationConstants.SQLITE_MAX_VARIABLE_NUMBER];
+            } else {
+                selectionArgs = new String[count];
+            }
+
+            StringBuilder selection = new StringBuilder();
+            selection.append(InstanceProviderAPI.InstanceColumns.INSTANCE_FILE_PATH + " IN (");
+            int j = 0 ;
+            while (j < selectionArgs.length) {
+                selectionArgs[j] = ids[i];
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java]: This is the assignment that I mention in the other comment. Since you're reassigning it, just pass the list as the parameter instead of casting it.

File: collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java [hunk 3]
```diff
@@ -145,6 +146,41 @@ public void deleteInstancesDatabase() {
         Collect.getInstance().getContentResolver().delete(InstanceProviderAPI.InstanceColumns.CONTENT_URI, null, null);
     }
 
+    public void deleteInstancesFromIDs(String ids[]){
+        int count = ids.length;
+        int i = 0 ;
```
Comment (nribeka) [inline collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java]: I think the code will work as it is.

If you want tighter code, instead of looping and incrementing i for every element, you could use counter here. And then reference of the `ids[i]` will become `ids[counter * ApplicationConstants.SQLITE_MAX_VARIABLE_NUMBER + j]`.

The pros:
* No looping to increment i.

The cons:
* Might make it less understandable.

Comment (lakshyagupta21) [reply collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java]: Yes it can be done, how i missed this i saw same thing was done while doing slicing in upload also in processChunk method. Thanks for pointing out @nribeka
