### PR TITLE
Do not lock the forms db when a form uses entities but is started in view-only mode

### LINKED ISSUE #6485: Entity form opening and match exactly blocked after opening finalized entity form in ready to send
#### ODK Collect version
the master version 2e63b33407128e7e17ca46241683945dd749c48f
#### Android version
15, 10 
#### Device used
Pixel 6a, Redmi 7

#### Problem description
Finalizing entity form and opening it in ready to send blocks entity form opening and match exactly.
#### Steps to reproduce the problem
1. Scan user "Cactus" from project https://staging.getodk.cloud/#/projects/103
2. Go to start new form
3. Open Cactus Registration form, fill it and finalize
4. Go to ready to send, open previously finalized form and close it
5. Go to start new form and open Cactus registration form again

#### Expected behavior
Finalizing entity form and opening it in ready to send should not block entity form opening and match exactly.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6485 

#### Why is this the best possible solution? Were any other approaches considered?
When opening forms in view-only mode (forms that can't be edited), it doesn't make sense to block downloading updates, nor does it make sense to block opening such forms during these processes.
There’s nothing to discuss regarding the implementation, as the location where this case needs to be handled is clear - `FormUriActivity`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test opening finalized and sent forms (forms that can't be edited) to ensure they don't block form updates and can still be opened during such processes.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt [hunk 1]
```diff
@@ -1144,6 +1144,37 @@ class FormUriActivityTest {
         )
     }
 
+    @Test
+    fun `When attempting to view a non-editable form that uses entities and the forms database is locked then start form for view only`() {
```
Comment (seadowg) [inline collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:1148]: Would this test not be enough? We'd maybe want to add an assertion that here that opening the view-only form doesn't lock the forms change lock, but I'm not sure if we need the two connected tests?

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt:1148]: I have added one extra test here and removed those connected ones.

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt [hunk 2]
```diff
@@ -1,12 +1,15 @@
...
 
     override fun assertOnPage(): ViewFormPage {
         assertToolbarTitle(formName)
         assertText(org.odk.collect.strings.R.string.exit)
         return this
     }
+
+    fun clickOnExit(): SendFinalizedFormPage {
+        clickOnString(org.odk.collect.strings.R.string.exit)
+        return SendFinalizedFormPage()
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt]: This should be `return SendFinalizedFormPage().assertOnPage()`

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt (hunk 2 above)
Comment (grzesiek2010) [reply collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt]: Actually, this method is no longer used so I removed it al all.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- issue #6485 doesn't occur
- opening finalized and sent forms before and after updating the list of forms
- trying to open forms new, drafts, finalized, sent while forms are being updated

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 15
