### PR TITLE
[Fixes build] Only block finalization if form with missing instanceID also requests encryption

### LINKED ISSUE #3340: Only block finalization of forms without instanceID if those forms also define encryption
#### Problem description
#3265 attempted to block finalization of forms that request encryption but don't define an `instanceID`. Instead, it blocks finalization of any form without an `instanceID`. This was caught by `org.odk.collect.android.regression.FillBlankFormTest.searchExpression_ShouldDisplayWhenItContainsOtherAppearanceName`.

#### Steps to reproduce the problem
Run test `org.odk.collect.android.regression.FillBlankFormTest.searchExpression_ShouldDisplayWhenItContainsOtherAppearanceName` which incidentally verifies that a form without an `instanceID` is finalized.

#### Expected behavior
That test should pass and in general, the only case that forms without an `instanceID` should not be finalized is when they also require encryption.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3340 

#### What has been done to verify that this works as intended?
Added and ran automated tests; verified that `org.odk.collect.android.regression.FillBlankFormTest.searchExpression_ShouldDisplayWhenItContainsOtherAppearanceName` now passes.

#### Why is this the best possible solution? Were any other approaches considered?
I considered doing a deeper refactor of `getEncryptedFormInformation` but there's no user-facing reason to do so and it's relatively high-risk because there's so much logic there.

I considered adding a targeted test for the case with no `instanceID` and no encryption but because these tests are expensive, I added a comment on `org.odk.collect.android.regression.FillBlankFormTest.searchExpression_ShouldDisplayWhenItContainsOtherAppearanceName` instead. That should help us understand what's going on if it fails again and reminds us that the test has a dual purpose.

I replaced the pure junit test for the missing `instanceID` and encryption test with an Espresso test so that no refactoring of `getEncryptedFormInformation` would be needed. While I was there, I added a test to verify that actually encrypted forms can't be opened.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This brings the code block that checks for missing `instanceID` back to where it used to be so it should be safe. There's again a risk that any form without an `instanceID` or any form with encryption is affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
See tests.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/EditSavedFormPage.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        int desiredImageId = InstanceListCursorAdapter.getFormStateImageResourceIdForStatus(desiredStatus);
+
+        onView(allOf(instanceOf(RelativeLayout.class),
+                    hasDescendant(withText(instanceName)),
+                    not(hasDescendant(instanceOf(Toolbar.class)))))
+                .check(matches(hasDescendant(withTagValue(equalTo(desiredImageId)))));
+        return this;
+    }
+
+    public EditSavedFormPage clickSavedFormWithDialog(String instanceName, int dialogMessageId) {
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/EditSavedFormPage.java]: I think I'd prefer to break this into the actions and assertions - I like "flow" methods for when the steps inside aren't as consequential for the test but I think it's good hear to expose the steps involved in the test itself. We could probably have a standard `Dialog` page that we could do `checkMessage` on. What do you think?

**Review by seadowg — CHANGES_REQUESTED** [review]
Love it! I initially wasn't clear on how Espresso tests would look but I really like what you've come up with. It's also nice that these tests are isolated in their own `EncryptedFormTest`. Having tests that are broken down into features rather than areas of the code can often be easier to work with. It's really easy to build up a codebase that way (basically each feature/epic gets it's own test set) but harder when retrofitting stuff.

File: collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/EditSavedFormPage.java (hunk 1 above)
Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/EditSavedFormPage.java]: I should have called that out. You already set up that pattern with `ErrorDialog` and `ExitFormDialog`. I think my reasoning was that this felt like a one-off but you're probably right that a generic `Dialog` page would be useful. Will do.

Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/EditSavedFormPage.java]: Let me know what you think of 86f6f41. Notice that I identify the dialog by the Ok button because I couldn't find a way to identify just any dialog. See also what you think of `ErrorDialog`.

File: collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/ErrorDialog.java [hunk 2]
```diff
@@ -5,19 +5,21 @@
 import org.odk.collect.android.R;
 
 public class ErrorDialog extends Page<ErrorDialog> {
+    private final OkDialog okDialog;
```
Comment (seadowg) [inline collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/ErrorDialog.java]: I really like the the `OkDialog`. Seems like the best way to verify "any" dialog at the moment. 

For me, it does feel like the `ErrorDialog` should inherit from the `OkDialog` rather than contain one. What do you think?

Comment (lognaturel) [reply collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/ErrorDialog.java]: I feel like I had a reason but I don't even know anymore.

**Review by seadowg — APPROVED** [review]

**Comment by lognaturel** [comment]
@opendatakit/testers please prioritize this so we can hopefully get back to a green build! ✅ ❌

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 6.0, 7.1, 8.1 and 9.0. 
I was able to build app, run tests EncryptedFormTest.java, run FillBlankFormTest.searchExpression_ShouldDisplayWhenItContainsOtherAppearanceName, tested encrypted form with and without instanceId manually.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
