### PR TITLE
Dismiss snackbar before creating a new one

### LINKED ISSUE #5662: `FillBlankFormTest#app_ShouldNotCrash` is flakey
We've seen a this test fail a few times now even though it looks like everything is working correctly in the video (https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/8855972944306261818/details?stepId=bs.de451e242e6def7a&testCaseId=5&tabId=video).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5662 

#### What has been done to verify that this works as intended?
I've reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
As discussed in the issue it seems to be an Android bug and hopefully, this change will help us.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt [hunk 1]
```diff
@@ -103,7 +107,13 @@ object SnackbarUtils {
                     dismiss()
                 }
             }
-        }.show()
+        }.addCallback(object : BaseTransientBottomBar.BaseCallback<Snackbar>() {
+            override fun onDismissed(transientBottomBar: Snackbar?, event: Int) {
+                super.onDismissed(transientBottomBar, event)
```
Comment (seadowg) [inline androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt:112]: You might have already done this, but I think there's a couple of situations that we should double check that this gets called in:
1. When the Snackbar is dismissed after being on screen for its duration
2. When the Snackbar is dismissed manually
3. When the Activity is destroyed before the Snackbar is dismissed

Comment (grzesiek2010) [reply androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt:112]: I've checked those cases and it seems to work well.

**Review by seadowg — APPROVED** [review]
