### PR TITLE
Fixed checking for spaces in underlying values

### LINKED ISSUE #4078: Warnings are not visible for select multi questions
#### Software and hardware versions 
Collect v1.28.x, Android v all, device used...

#### Problem description
Warning messages are not visible for select multi widget on Collect 1.28 see gif:
ezgif com-video-to-gif (23)

Gif of the same form on 1.27/1.27.3:
ezgif com-video-to-gif (24)

#### Steps to reproduce the problem
1. Fill form 
[multi-warning.xml.txt](https://github.com/getodk/collect/files/5208067/multi-warning.xml.txt)

#### Expected behavior
Warnings should be visible for all questions.

#### Other information 
the issue does not occur on 1.27

@getodk-bot label "regression"

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4078

#### What has been done to verify that this works as intended?
I tested implemented changes manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I moved checking for spaces in underlying values to the main ItemsWidget class what is the best solution because all widgets that need the warning extend that class, so we have everything in one place and we can test it easily.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test the form attached to he issue and I think it would be enough since the change is pretty safe and we have automated tests.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue is ok.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java [hunk 1]
```diff
@@ -50,8 +49,8 @@
 
     public RankingWidget(Context context, QuestionDetails prompt) {
         super(context, prompt);
-
-        setUpLayout(getOrderedItems());
+        getOrderedItems();
```
Comment (lognaturel) [inline collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java]: This is not a new change but a getter that mutates is dangerous, I think. A rename to `buildOrderedItems` would help.

**Review by lognaturel — CHANGES_REQUESTED** [review]
It's ok to have spaces in single-select question types so I think this is too aggressive.

This regression shows the tests were clearly not covering enough -- it's important to have a test that verifies the check for spaces is actually done. I wonder whether passing in the `SpacesInUnderlyingValuesWarning` to each relevant widget type is the best way, though. Did you consider a Robolectric test that checks for the warning text in the view? I think it may then be ok for the `SpacesInUnderlyingValuesWarning` dependency to be an implementation detail (managed internally). That does mean you'd have to have an explicit, separate test for each question type that allows multiple selections. Might be worth a quick sanity check with @seadowg on the approach.

**Comment by grzesiek2010** [comment]
@lognaturel you are right I made a mistake implementing the warning for all selects. I prepared a new solution, please review.

**Review by lognaturel — APPROVED** [review]
Thanks, looks great! For QA, the risk here is forgetting one of the multi select types. I double checked and I think all are accounted for.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 9.0

Tested scenarios:
- form from issue
- select one questions
- select multiple questions
- column pack form
- light/dark mode 
- screen rotation/minimize

**Comment by mmarciniak90** [comment]
Tested with success on Androids 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"
