### PR TITLE
Fix memory leak when deleting project

### LINKED ISSUE #6280: Leak after deleting a project
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328, also 2024.2.x b44e199454102b244362836da0cebef022ca1730
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's a leak after deleting a project. 
leakOnDeletingProject

#### Steps to reproduce the problem
1. Add at least 2 projects in Collect.
2. Go to Settings-Project Management - Delete.
3. Delete a project

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6280

I ended up fixing this because I kept running into it while working on something else.

The key problem here was that we tried to unregister our settings listener for fragment like this:

```java
settingsProvider.getProtectedSettings().unregisterOnSettingChangeListener(this);
```

In the case where we delete a project, this ends up getting called after the project has changed meaning that `settingsProvider.getProtectedSettings()` will return a different `Settings` object than was used to register. To prevent this situation, I've made it so that preferences Fragments assign their `Settings` object in `onAttach`. As far as I'm aware, there's no reason for this to be looked up each time.

#### Why is this the best possible solution? Were any other approaches considered?

I did consider adding a constructer for `BaseProjectPreferencesFragment` and `BaseAdminPreferencesFragment` that would take a project ID rather than needing to do a lookup based on `ProjectDataService`. That would be more canoncial now that we have `FragmentFactory`. That change would ripple down to many subclasses though, so I felt like it was best to avoid while trying to just make a small fix.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just fix the leak!

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/BaseAdminPreferencesFragment.java [hunk 1]
```diff
@@ -6,43 +6,40 @@
...
-import javax.inject.Named;
+import org.odk.collect.shared.settings.Settings;
 
 public abstract class BaseAdminPreferencesFragment extends BasePreferencesFragment {
 
-    @Inject
-    @Named("ADMIN_SETTINGS_STORE")
-    SettingsStore adminSettingsStore;
+    String projectId;
+    Settings adminSettings;
```
Comment (grzesiek2010) [inline collect_app/src/main/java/org/odk/collect/android/preferences/screens/BaseAdminPreferencesFragment.java]: Those should be private I think.

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 10, 14

**Verified cases:**
- Issue #6280 does not occur
- Deleting big projects
