### PR TITLE
Close databse connections for given project when it is removed

### LINKED ISSUE #4870: Collect crashes when Try a demo project after deleting all projects on Android 5.1
#### Software and hardware versions 
Collect v current master Android v 5.1, device used...

#### Problem description
When testing #4855 I have noticed crash on Android 5.1 device only when deleted all projects and then run demo project.

#### Steps to reproduce the problem
1. Create project
2. Delete project
3. Click on Try a demo

#### Expected behavior
Collect should not crash.

#### Other information 
stacktrace:
`2021-10-19 10:34:40.451 10957-10957/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 10957
    android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
        at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCountByStatus(DatabaseInstancesRepository.java:109)
        at org.odk.collect.android.formmanagement.InstancesAppState.update(InstancesAppState.kt:36)
        at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.lambda$refreshInstances$0$MainMenuViewModel(MainMenuViewModel.java:121)
        at org.odk.collect.android.activities.viewmodels.MainMenuViewModel$$ExternalSyntheticLambda1.get(Unknown Source)
        at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4870 

#### What has been done to verify that this works as intended?
I've verified the issue manually.

#### Why is this the best possible solution? Were any other approaches considered?
I think it's the only solution we just need to close database connections before removing them at all.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify that the issue does not occur. You can also test deleting other projects (not only demo ones) to make sure ther is no regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
I'm seeing 226 test cases fail on Test Lab when running all the instrumentation tests for this. I remember that was a problem with a related change we tried to make around closing db connections. Are you seeing those fails as well?

**Comment by grzesiek2010** [comment]
> Are you seeing those fails as well?

Yeah there was something wrong but I rebased onto master and it's green.

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt [hunk 1]
```diff
@@ -58,6 +58,22 @@ open class DatabaseConnection(
         private val openHelpers = mutableMapOf<String, SQLiteOpenHelper>()
         private val toClose = mutableListOf<SQLiteOpenHelper>()
 
+        @JvmStatic
+        fun close(projectId: String) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt]: I'm not a huge fan of that this method cares about the project ID, as it doesn't really know (or doesn't need to know) anything about projects. Also, given the implementation, this parameter could really just be called `subDirectory` as if my db was in `/dir1/dir2/projectDir/` I coud pass `dir1` or `dir2` into this and it would close (and clear) the connection.

I'm wondering if an alternative approach would be to have a `cleanUp` method that closes and clears connections that are to no longer existing fils (sort of like we do just-in-time in when grabbing a db helper)? We could call this after deleting the project dir and it should then remove the helpers we want, without us needing to care about any identifiers in `DatabaseConnection`.

**Review by seadowg — CHANGES_REQUESTED** [review]

File: collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt (hunk 1 above)
Comment (grzesiek2010) [reply collect_app/src/main/java/org/odk/collect/android/database/DatabaseConnection.kt]: So it's a similar solution it just check the file existence instead of finding it by project id. Updated, please take a look if it's what you expected.

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 8.1, 10, 11, 13 (on the emulator)

**Verified cases:**

- issue #4870 is no longer reproducing
- deleting the demo project and opening a new demo project
- deleting different projects and opening the demo project
- deleting a duplicate of a demo and a different project
- deleting manually entered project
- deleting Google Drive, Aggregate, Central projects
- trying to delete a project with unsent submissions
- deleting a project after resetting
- deleting an encrypted project
- trying to delete a project when background jobs are still running in the project
- deleting a Draft Testing Form
- adding manually/via QR code the same project which was deleted (demo and other)

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android: 5.1
