### PR TITLE
Fixed updating layers on changing basemaps

### LINKED ISSUE #6248: Added vector offline layer isn’t visible in the bottom sheet in the map after adding in settings
#### ODK Collect version
2024.2.0 BETA 4
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Added vector offline layer isn’t visible in the bottom sheet in the map after the steps described below.
If I don’t open the map (in step 2) before going to settings, the issue doesn’t occur.
#### Steps to reproduce the problem
1. Install Collect and add the demo project (download forms).
2. Go to Select one from map to select a point question and open the map.
3. Tap 3 dots – project settings -maps.
4. Change the source of maps to Mapbox.
5. Tap layers and add a vector offline layer.
6. Select and save the vector layer.
7. Tap the device back button to go back to the form.
8. Tap "Select place” and check the selected offline layer
#### Expected behavior
The layer should be applied and in the list in the map.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6248 

#### Why is this the best possible solution? Were any other approaches considered?
Loading new layers is triggered in the init block of the ViewModel (`OfflineMapLayersViewModel`). That ViewModel is scoped to its activity so the init block is called only on activity creation/recreation. As a result, it is possible to end up with two `OfflineMapLayersViewModel` opened - one scoped to `FormFillingActivity` and one scooped to `ProjectPreferencesActivity`  (see the scenario from the issue). When new layers are added in one of them the second one is not updated.
~~To fix the issue I factored out another ViewModel scoped to its fragment. Thanks to that loading new layers is triggered every time we show the fragment.~~
We decided that to fix the issue we should load the layers every time the fragment is attached (see the discussion below).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This is the last pr in v2024.2 so please these the offline layers once again and not only focus on the issue itself. It's not a big change but definitely something that can break something there. This also makes changes to change map engines (Google, Mapbox etc) so playing with that is a good idea.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPickerViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+import androidx.lifecycle.LiveData
+import androidx.lifecycle.MutableLiveData
+import androidx.lifecycle.ViewModel
+import org.odk.collect.androidshared.async.TrackableWorker
+import org.odk.collect.async.Scheduler
+import org.odk.collect.settings.SettingsProvider
+import org.odk.collect.settings.keys.ProjectKeys
+
+class OfflineMapLayersPickerViewModel(
```
Comment (grzesiek2010) [inline maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPickerViewModel.kt]: Actually, I'm happy that we no longer keep the code that is not shared in the shared ViewModel. Not using a shared ViewModel for communication between fragments is also the direction we were thinking about in https://github.com/getodk/collect/pull/6243#discussion_r1662129936

**Review by seadowg — CHANGES_REQUESTED** [review]
I think this is heavily pointing us towards wanting a data service for layers that allows us to share reactive data between view models rather than sharing them between UI components or using Fragment results to nudge things to get updated. That's another thing to look at when we do #6198 I reckon (I'll make a note there) rather than holding up release.

For the moment though, could we not just fix this by calling `loadExistingLayers`  whenever we show the bottom sheet (in `OfflineMapLayersPicker#onAttach` for example). That feels like a smaller change. It'd mean refreshing on rotate as well, but I'm OK with the trade-off there.

We're also missing tests. I think the only option is to write something with `ActivityScenario` which feels like a bit of an undertaking (we need a test Activity in `debug` etc), so I'd also feel better about going ahead without tests with the smaller change.

EDIT: I quickly spiked adding the following to `OfflineMapLayersPicker` on `master` and it seemed to fix things:

```kotlin
override fun onAttach(context: Context) {
    super.onAttach(context)
    sharedViewModel.loadExistingLayers()
}
```

I also needed to make `loadExistingLayers` public as well. The tests using `recreate` fail, but then pass if a `FakeScheduler#flush` is called after each.

**Comment by grzesiek2010** [comment]
> For the moment though, could we not just fix this by calling loadExistingLayers whenever we show the bottom sheet (in OfflineMapLayersPicker#onAttach for example). That feels like a smaller change. It'd mean refreshing on rotate as well, but I'm OK with the trade-off there.

I would prefer to have such a small change here too. The problem is that it will be called on every screen rotation. Do you think it's ok?

**Comment by seadowg** [comment]
> I would prefer to have such a small change here too. The problem is that it will be called on every screen rotation. Do you think it's ok?

Yeah! I said that in the original comment, but maybe it wasn't clear. It'd definitely not be ideal, but I think gets us to a more "correct" place with less workarounds, risk and disruption to hold things up.

**Comment by grzesiek2010** [comment]
@seadowg I won't be available for the next ~3 hours. If there is something you would like to change here please feel free to do that.

File: collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt [hunk 2]
```diff
@@ -68,6 +68,13 @@ class MapsPreferencesFragment : BaseProjectPreferencesFragment(), Preference.OnP
         super.onSettingChanged(key)
         if (key == ProjectKeys.KEY_REFERENCE_LAYER) {
             findPreference<Preference>(ProjectKeys.KEY_REFERENCE_LAYER)!!.summary = getLayerName()
+        } else if (key == KEY_BASEMAP_SOURCE) {
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt:71]: It looks like there's no testing for anything in `onSettingsChanged` here. No need to block this - I'll just create an issue as a follow-up.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@getodk/testers I'll wait for manual testing to merge here just in case as there's a few changes here that aren't tested.

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 14

Verified cases:
- Issue #6248 does not occur
- Adding vector layers
- Different map sources
- Regression check on offline layers
- Don't keep activities enabled
- No background processes

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13
