### PR TITLE
Stop using localized strings in `DownloadFormsTask`

### LINKED ISSUE #4931: Manual downloads shows as failing when language not set to English
#### Software and hardware versions 
Collect v2021.3.2

#### Problem description
Downloads via "Get Blank Form" will always show as failures if the language is not set to English. The error list will show each form download as having the status "Success" however.

#### Steps to reproduce the problem

1. Set language to anything German (or any language we have translations for)
2. Navigate to Get Blank Form
3. Download one or more forms

We see the "x of y downloads failed!" message in German and can click through to the error list to see each form download was a "Success".

#### Expected behavior

We should see the "All downloads succeeded!" message when all downloads succeed.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4931
~~Blocked by #4929~~

This makes the same changes as #4932 but also removes the source of the problem by taking localized strings out of `DownloadFormsTask`.

#### What has been done to verify that this works as intended?

Existing tests checking download flows.

#### Why is this the best possible solution? Were any other approaches considered?

I didn't want to add the risk of a refactor to the original hotfix, but I feel pretty good about this change after making it. Using the localized success/failure message in our logic was a little strange but it also opened us up to bugs like the one we experienced (a translated string getting compared to a non translated one). I think using a nullable exception to track success/failure is much clearer **and** safer.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to just check the issue is fixed!

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

File: collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java [hunk 1]
```diff
@@ -62,7 +60,7 @@ public DownloadFormsTask(FormDownloader formDownloader) {
                 publishProgress(serverFormDetails.getFormName(), currentFormNumber, totalForms);
 
                 formDownloader.downloadForm(serverFormDetails, count -> {
-                    String message = Collect.getInstance().getString(R.string.form_download_progress,
+                    String message = getLocalizedString(Collect.getInstance(), R.string.form_download_progress,
```
Comment (seadowg) [inline collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java:63]: This is still a localized string but it is actually displayed rather than being used as part of logic.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 8.1 and 10.0.

Tested cases:
- download forms in different languages: German, Spanish, French, English
- download forms from different servers: Central, Google Drive, Kobo, Ona
- send submissions to different servers
- download all forms
- error on failed download
- download the same form twice
